SELECT a.nome_clifor, 
A.ITEM_IMPRESSAO AS CERTO, 
B.ITEM_IMPRESSAO AS ERRADO,
A.SUB_ITEM_TAMANHO, 
A.REFERENCIA,
B.ITEM,
b.req_material
FROM ENTRADAS_ITEM A
INNER JOIN ESTOQUE_RET1_MAT B ON A.REFERENCIA_PEDIDO = B.PEDIDO AND A.REFERENCIA = B.MATERIAL
where nf_entrada='37831' and a.SERIE_NF_ENTRADA ='1'
and nome_clifor = 'PASSAMANARIA DO NORDESTE '
AND A.REFERENCIA ='40.03.0083'

BEGIN TRAN
UPDATE Estoque_ret1_mat SET
ITEM_IMPRESSAO='0003'
WHERE REQ_MATERIAL='043347'
AND MATERIAL ='40.03.0083'
commit
ro
select * from ESTOQUE_RET1_MAT where MATERIAL ='40.03.0017' AND REQ_MATERIAL ='043247'
