select * from SAW_ACESSO_PORTARIA
where TIPO='FUNCIONARIO' AND convert(char(10),DATA_MOVIMENTO,103)='24/04/2013' AND DATA_SAIDA_ENTRADA IS NULL


update SAW_ACESSO_PORTARIA
set STATUS='SAIDA'
where TIPO='FUNCIONARIO' AND convert(char(10),DATA_MOVIMENTO,103)='24/04/2013' AND DATA_SAIDA_ENTRADA IS NULL


SELECT NOME, EMPRESA, TIPO, CONTATO, TIPO_VISITA, DATA_MOVIMENTO, 
CASE [STATUS] WHEN 'ENTRADA' THEN 'PRESENTE' WHEN 'SAIDA' THEN 'AUSENTE' END AS STATUS FROM SAW_ACESSO_PORTARIA 
WHERE (DATA_SAIDA_ENTRADA IS NULL) AND (CONVERT (CHAR(10), DATA_MOVIMENTO, 103) = CONVERT (CHAR(10), GETDATE(), 103))
