--- ACOMPANHAMENTO DA ORDEM DE PRODUÇÃO NO GRUPO
SELECT RECURSO_PRODUTIVO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRIORIDADE,FASE_PRODUCAO,SETOR_PRODUCAO, 
PRODUCAO_TAREFAS.INICIO_REAL,DATEPART(dayofyear, GETDATE())-DATEPART(dayofyear, PRODUCAO_TAREFAS.INICIO_REAL) AS GIRO,
QTDE_PREVISTA,QTDE_A_PRODUZIR,QTDE_EM_PROCESSO
FROM PRODUCAO_TAREFAS 
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE RECURSO_PRODUTIVO LIKE 'GE%' AND (QTDE_A_PRODUZIR+QTDE_EM_PROCESSO)>0 AND YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2013
ORDER BY RECURSO_PRODUTIVO


--- ACOMPANHAMENTO DA ORDEM DE PRODUÇÃO NO ALMOXARIFADO
SELECT RECURSO_PRODUTIVO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRIORIDADE,FASE_PRODUCAO,SETOR_PRODUCAO, 
PRODUCAO_TAREFAS.INICIO_REAL,DATEPART(dayofyear, GETDATE())-DATEPART(dayofyear, PRODUCAO_TAREFAS.INICIO_REAL) AS GIRO,
QTDE_PREVISTA,QTDE_A_PRODUZIR,QTDE_EM_PROCESSO
FROM PRODUCAO_TAREFAS 
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE RECURSO_PRODUTIVO LIKE '002' AND (QTDE_A_PRODUZIR+QTDE_EM_PROCESSO)>0 AND YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2013
ORDER BY GIRO

--- ACOMPANHAMENTO DA ORDEM DE PRODUÇÃO NO CORTE
SELECT RECURSO_PRODUTIVO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRIORIDADE,FASE_PRODUCAO,SETOR_PRODUCAO, 
PRODUCAO_TAREFAS.INICIO_REAL,DATEPART(dayofyear, GETDATE())-DATEPART(dayofyear, PRODUCAO_TAREFAS.INICIO_REAL) AS GIRO,
QTDE_PREVISTA,QTDE_A_PRODUZIR,QTDE_EM_PROCESSO
FROM PRODUCAO_TAREFAS 
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE (FASE_PRODUCAO IN ('006','006.1','007','008','009')) AND (QTDE_A_PRODUZIR+QTDE_EM_PROCESSO)>0
ORDER BY GIRO


select * from PRODUCAO_TAREFAS
where ORDEM_PRODUCAO='75385'


--- RESUMO PARA GRÁFICO
SELECT GIRO,QTDE_OP=COUNT(ORDEM_PRODUCAO) FROM (
SELECT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,
DATEPART(dayofyear, GETDATE())-DATEPART(dayofyear, PRODUCAO_TAREFAS.INICIO_REAL) AS GIRO
FROM PRODUCAO_TAREFAS 
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE RECURSO_PRODUTIVO LIKE '003' AND (QTDE_A_PRODUZIR+QTDE_EM_PROCESSO)>0 AND YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2013
) AS GIROS
GROUP BY GIRO





