----- PLANILHA EXCEL
SELECT 'EMBALADA' ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
VENDAS_PROD_EMBALADO.PRODUTO,
VENDAS_PROD_EMBALADO.COR_PRODUTO,
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO 
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,VENDAS_PROD_EMBALADO.PRODUTO,VENDAS_PROD_EMBALADO.COR_PRODUTO,CAIXA_FECHADA
HAVING CAIXA_FECHADA=1 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101' 
UNION ALL
SELECT 'RESERVADA'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
VENDAS_PROD_EMBALADO.PRODUTO,
VENDAS_PROD_EMBALADO.COR_PRODUTO,
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,VENDAS_PROD_EMBALADO.PRODUTO,VENDAS_PROD_EMBALADO.COR_PRODUTO,CAIXA_FECHADA
HAVING CAIXA_FECHADA=0 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101'
UNION ALL
SELECT 'À RESERVAR'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
VENDAS_PRODUTO.PRODUTO,
VENDAS_PRODUTO.COR_PRODUTO,
QTDE_A_RESERVAR=SUM(VENDAS_PRODUTO.QTDE_ENTREGAR-QTDE_EMBALADA) 
FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
WHERE VENDAS.APROVACAO = 'A'
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PRODUTO.ENTREGA,VENDAS_PRODUTO.PRODUTO,VENDAS_PRODUTO.COR_PRODUTO
HAVING PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101'


--- MOSTRAR NO MONITOR
SELECT MOVIMENTO,PERIODO_PCP,NUMERO_ENTREGA,ENTREGA,LIMITE,DIAS_RESTANTE,QTDE=SUM(QTDE_EMBALADA) FROM (
SELECT 'EMBALADA' AS MOVIMENTO ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO 
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,CAIXA_FECHADA
HAVING CAIXA_FECHADA=1 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101' 
UNION ALL
SELECT 'RESERVADA'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,CAIXA_FECHADA
HAVING CAIXA_FECHADA=0 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101'
UNION ALL
SELECT 'À RESERVAR'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_A_RESERVAR=SUM(VENDAS_PRODUTO.QTDE_ENTREGAR-QTDE_EMBALADA) 
FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
WHERE VENDAS.APROVACAO = 'A'
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PRODUTO.ENTREGA
HAVING PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101' ) AS ACOMPANHAMENTO_CARTEIRA
WHERE PERIODO_PCP='2013 MAIO' AND TIPO IN ('ANTECIPADO','FATURAMENTO','RESERVA FISICA','RESERVA SISTEMA','SALDO','TEMP','TEMP 2','VENDA','DISTRIBUIDOR(A) RESIDENTE')
GROUP BY MOVIMENTO,PERIODO_PCP,NUMERO_ENTREGA,ENTREGA,LIMITE,DIAS_RESTANTE
ORDER BY PERIODO_PCP,NUMERO_ENTREGA


-- VIEW PARA GERAÇÃO DOS DADOS PARA MOSTRAR NO MONITOR DE ACOMPANHAMENTO DA CARTEIRA
ALTER VIEW W_ACOMPANHAMENTO_CARTEIRA AS
SELECT MOVIMENTO,PERIODO_PCP,NUMERO_ENTREGA,ENTREGA,LIMITE,DIAS_RESTANTE,QTDE_ORIGINAL=SUM(QTDE_ORIGINAL),QTDE_ENTREGUE=SUM(QTDE_ENTREGUE),QTDE=SUM(QTDE_EMBALADA) FROM (
SELECT 'EMBALADA' AS MOVIMENTO ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_ORIGINAL=0,
QTDE_ENTREGUE=0,
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO 
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,CAIXA_FECHADA
HAVING CAIXA_FECHADA=1 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101' 
UNION ALL
SELECT 'RESERVADA'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_ORIGINAL=0,
QTDE_ENTREGUE=0,
QTDE_EMBALADA=SUM(VENDAS_PROD_EMBALADO.QTDE_EMBALADA) 
FROM VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO = VENDAS_PROD_EMBALADO.COR_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PROD_EMBALADO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PROD_EMBALADO.ENTREGA,CAIXA_FECHADA
HAVING CAIXA_FECHADA=0 AND PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101'
UNION ALL
SELECT 'À RESERVAR'  ,
VENDAS.TIPO,
PERIODO_PCP=RTRIM(VENDAS.PERIODO_PCP),
PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,
PRODUTOS_PERIODOS_ENTREGAS.LIMITE,
DIAS_RESTANTE=DATEPART(dayofyear, PRODUTOS_PERIODOS_ENTREGAS.LIMITE)-DATEPART(dayofyear, GETDATE()),
QTDE_ORIGINAL=SUM(VENDAS_PRODUTO.QTDE_ORIGINAL),
QTDE_ENTREGUE=SUM(VENDAS_PRODUTO.QTDE_ENTREGUE),
QTDE_A_RESERVAR=SUM(VENDAS_PRODUTO.QTDE_ENTREGAR-QTDE_EMBALADA) 
FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA AND PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP
WHERE VENDAS.APROVACAO = 'A'
GROUP BY VENDAS.TIPO,VENDAS.PERIODO_PCP,PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.ENTREGA,PRODUTOS_PERIODOS_ENTREGAS.LIMITE,VENDAS_PRODUTO.ENTREGA
HAVING PRODUTOS_PERIODOS_ENTREGAS.ENTREGA >= '20130101'  ) AS ACOMPANHAMENTO_CARTEIRA
WHERE TIPO NOT IN ('AMOSTRA','BONIFICACAO','BRINDE','MATERIAL PROMOCIONAL','TROCA DE PEÇAS','VENDA INTERNA')
GROUP BY MOVIMENTO,PERIODO_PCP,NUMERO_ENTREGA,ENTREGA,LIMITE,DIAS_RESTANTE


SELECT CAST(QTDE_ENTREGUE+QTDE_ORIGINAL AS INT),* FROM W_ACOMPANHAMENTO_CARTEIRA
WHERE PERIODO_PCP='2013 maio' AND NUMERO_ENTREGA='17' AND QTDE_ORIGINAL<>0


SELECT CAST(500 AS NUMERIC)/CAST(800 AS NUMERIC)


SELECT A.PERIODO_PCP,A.NUMERO_ENTREGA,A.ENTREGA,A.LIMITE,
DIAS_RESTANTE = (SELECT MAX(DIAS_RESTANTE) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE),
QTDE_EMBALADA=(SELECT SUM(QTDE) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='EMBALADA' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
QTDE_RESERVADA=(SELECT SUM(QTDE) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='RESERVADA' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
QTDE_A_RESERVAR=(SELECT SUM(QTDE) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='À RESERVAR' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
QTDE_ORIGINAL=(SELECT SUM(QTDE_ORIGINAL) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='À RESERVAR' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
QTDE_ENTREGUE=(SELECT SUM(QTDE_ENTREGUE) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='À RESERVAR' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
PERC_FAT=(SELECT CAST(CAST(QTDE_ENTREGUE AS NUMERIC)/CAST(QTDE_ORIGINAL AS NUMERIC)*100 AS NUMERIC(10,2)) FROM W_ACOMPANHAMENTO_CARTEIRA B 
              WHERE B.MOVIMENTO='À RESERVAR' AND B.PERIODO_PCP=A.PERIODO_PCP AND B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.ENTREGA=A.ENTREGA AND B.LIMITE=A.LIMITE), 
TOTAL=SUM(QTDE)              
FROM W_ACOMPANHAMENTO_CARTEIRA A 
WHERE A.PERIODO_PCP='2013 maio'
GROUP BY A.PERIODO_PCP,A.NUMERO_ENTREGA,A.ENTREGA,LIMITE
ORDER BY PERIODO_PCP,NUMERO_ENTREGA


