SELECT A.COD_CLIFOR,A.FATURA,C.RAZAO_SOCIAL,B.* FROM CTB_A_RECEBER_FATURA A
INNER JOIN CTB_ACOMPANHAMENTO B ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
INNER JOIN CADASTRO_CLI_FOR C ON C.CLIFOR=A.COD_CLIFOR
WHERE A.LANCAMENTO='229098' AND A.FATURA='032858' AND A.ITEM='93'


SELECT * FROM CTB_ACOMPANHAMENTO
WHERE LANCAMENTO='229098'
