BEGIN TRAN
COMMIT

update F
set F.caixa_numero_cliente=TOTAL.NCC
FROM (
SELECT CAST('0' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CAIXA) AS NCC,A.CAIXA 
FROM FATURAMENTO_CAIXAS A
JOIN (
SELECT DISTINCT PEDIDO,CAIXA FROM FATURAMENTO_PROD
WHERE PEDIDO IN ('72601','72478')
) B ON B.CAIXA=A.CAIXA
WHERE PEDIDO IN ('72601','72478')
) TOTAL 
JOIN FATURAMENTO_CAIXAS F ON F.CAIXA=TOTAL.CAIXA


