---
SELECT qtde_a FROM PRODUCAO_OS_TAREFAS A1 
JOIN PRODUCAO_ORDEM_SERVICO B1 ON B1.ORDEM_SERVICO=A1.ORDEM_SERVICO 
LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=A1.ORDEM_PRODUCAO AND C1.DESC_RECURSO='GRUPO ATHENA VIRTUAL'
LEFT JOIN W_PRODUCAO_ORDEM_HIST_OS d1 on d1.ordem_producao=a1.ORDEM_PRODUCAO AND D1.fase_producao='007' AND D1.DESC_RECURSO='GRUPO ATHENA VIRTUAL'
WHERE b1.DATA='20140409' AND C1.DESC_RECURSO='GRUPO ATHENA VIRTUAL' AND C1.DESC_SETOR_PRODUCAO='OFICINA ATHENA' AND B1.FASE_PRODUCAO='009' AND A1.INDICADOR_TIPO_MOV=1 

SELECT * FROM PRODUCAO_OS_TAREFAS A1 
JOIN PRODUCAO_ORDEM_SERVICO B1 ON B1.ORDEM_SERVICO=A1.ORDEM_SERVICO 
JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=A1.ORDEM_PRODUCAO AND C1.DESC_RECURSO='GRUPO ATHENA 03'
JOIN W_PRODUCAO_ORDEM_HIST_OS d1 on d1.ordem_producao=a1.ORDEM_PRODUCAO AND D1.fase_producao='007' AND D1.DESC_RECURSO='GRUPO ATHENA 03'
WHERE b1.DATA='20140409' AND C1.DESC_RECURSO='GRUPO ATHENA 03' AND C1.DESC_SETOR_PRODUCAO='OFICINA ATHENA' AND B1.FASE_PRODUCAO='009' AND A1.INDICADOR_TIPO_MOV=1 
----




SELECT * FROM PRODUCAO_OS_TAREFAS A1 
JOIN PRODUCAO_ORDEM_SERVICO B1 ON B1.ORDEM_SERVICO=A1.ORDEM_SERVICO 
LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=A1.ORDEM_PRODUCAO 
LEFT JOIN W_PRODUCAO_ORDEM_HIST_OS d1 on d1.ordem_producao=a1.ORDEM_PRODUCAO AND D1.fase_producao='007' AND D1.DESC_RECURSO='GRUPO ATHENA VIRTUAL'
WHERE B1.DATA='20140409' AND C1.DESC_RECURSO='GRUPO ATHENA VIRTUAL' AND C1.DESC_SETOR_PRODUCAO='OFICINA ATHENA' AND B1.FASE_PRODUCAO='009' AND A1.INDICADOR_TIPO_MOV=1 



SELECT DESC_RECURSO,DESC_SETOR_PRODUCAO,ordem_producao,qtde_a=SUM(QTDE_A) 
FROM W_PRODUCAO_ORDEM_HIST_OS
WHERE DATA='20140409' --and ordem_producao in 
--(
--SELECT ORDEM_PRODUCAO FROM PRODUCAO_ORDEM_SERVICO A
--JOIN PRODUCAO_OS_TAREFAS B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO 
--WHERE DATA='20140409' AND FASE_PRODUCAO='009'
--)
GROUP BY DESC_RECURSO,DESC_SETOR_PRODUCAO,ordem_producao



SELECT DESC_RECURSO,DESC_SETOR_PRODUCAO,ordem_producao,qtde_a=SUM(QTDE_A) 
FROM W_PRODUCAO_ORDEM_HIST_OS
WHERE ordem_producao in 
(
SELECT ORDEM_PRODUCAO FROM PRODUCAO_ORDEM_SERVICO A
JOIN PRODUCAO_OS_TAREFAS B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO 
WHERE DATA='20140409' AND FASE_PRODUCAO='009'
) and FASE_PRODUCAO1='008' 
GROUP BY DESC_RECURSO,DESC_SETOR_PRODUCAO,ordem_producao
ORDER BY ordem_producao


SELECT 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_FINALIZADA=SUM(qtde_a) 
FROM W_PRODUCAO_ORDEM_HIST_OS WITH (NOLOCK)
WHERE DATA='20140409' 
AND INDICADOR_TIPO_MOV=1 
AND RECURSO_PRODUTIVO IN ('GAT01','RVATH','REATH')
GROUP BY DESC_SETOR_PRODUCAO,DESC_RECURSO,RECURSO_PRODUTIVO



select * from W_ORDEM_PRODUCAO_OFICINA_NOVA

select * from W_OFICINA_GRUPO_EFICIENCIA
where EMISSAO='20140414'


sp_helptext W_OFICINA_GRUPO_EFICIENCIA

CREATE VIEW W_OFICINA_GRUPO_EFICIENCIA AS  
SELECT FILIAL,  
        DESC_SETOR_PRODUCAO,  
        DESC_RECURSO,  
        EMISSAO,  
        QTDE_OPERADOR,  
        MINUTOS_DISPONIVEIS,  
        TEMPO_PADRAO_TOTAL=SUM(TEMPO_PADRAO*QTDE),  
        EFICIENCIA=ROUND((SUM(TEMPO_PADRAO*QTDE)/(QTDE_OPERADOR*MINUTOS_DISPONIVEIS)*100),0)   
  
FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA  
  
GROUP BY FILIAL,DESC_SETOR_PRODUCAO,DESC_RECURSO,EMISSAO,QTDE_OPERADOR,MINUTOS_DISPONIVEIS  


SELECT * FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA  

SP_HELPTEXT W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA


CREATE VIEW W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA AS   
SELECT DISTINCT A.FILIAL,DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,A.EMISSAO,  
TEMPO_PADRAO=  
(  
SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS   
WHERE TABELA_OPERACOES = C.PRODUTO AND TEMPO_CRONOMETRADO>0   
),   
QTDE=SUM(QTDE),  
QTDE_OPERADOR=(  
    select distinct qtde_operador from ldr_metas_oficina_grupo_nova   
    where desc_recurso=B.DESC_RECURSO and desc_SETOR_producao=B.DESC_SETOR_PRODUCAO   
    and data_producao= A.EMISSAO   
),  
MINUTOS_DISPONIVEIS=(  
    select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova   
    where desc_recurso=B.DESC_RECURSO and desc_setor_producao=B.DESC_setor_PRODUCAO   
    and data_producao= A.EMISSAO   
)  
FROM ESTOQUE_PROD_ENT A,W_ORDEM_PRODUCAO_OFICINA_NOVA B, ESTOQUE_PROD1_ENT C  
WHERE A.ORDEM_PRODUCAO=B.ORDEM_CORTE AND C.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO   
AND C.ORDEM_PRODUCAO=B.ORDEM_PRODUCAO AND A.EMISSAO>='20120101' AND A.EMISSAO<=GETDATE()  
GROUP BY A.FILIAL,DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,A.EMISSAO  




SELECT 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DIA = CASE DATEPART(DW,DATA) 
	  WHEN 1 THEN 'DOMINGO'
	  WHEN 2 THEN 'SEGUNDA'
	  WHEN 3 THEN 'TERÇA'
	  WHEN 4 THEN 'QUARTA'
	  WHEN 5 THEN 'QUINTA'
	  WHEN 6 THEN 'SEXTA'
	  ELSE 'SÁBADO' END,
TEMPO_PADRAO_TOTAL=SUM(TEMPO_PADRAO*QTDE),  
QTDE=SUM(QTDE),
EFICIENCIA=ROUND((SUM(TEMPO_PADRAO*QTDE)/(QTDE_OPERADOR*MINUTOS_DISPONIVEIS)*100),0)   
FROM (
	SELECT DESC_SETOR_PRODUCAO,
	DESC_RECURSO,
	RECURSO_PRODUTIVO,
	PRODUTO,
	DATA,
	TEMPO_PADRAO=  
	(  
	SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS with (nolock)  
	WHERE TABELA_OPERACOES = C.PRODUTO AND TEMPO_CRONOMETRADO>0   
	),   
	QTDE=SUM(QTDE_A),  
	QTDE_OPERADOR=(  
		select distinct qtde_operador from ldr_metas_oficina_grupo_nova with (nolock)  
		where desc_recurso=C.DESC_RECURSO and desc_SETOR_producao=C.DESC_SETOR_PRODUCAO   
		and data_producao= C.DATA   
	),  
	MINUTOS_DISPONIVEIS=(  
		select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova with (nolock)   
		where desc_recurso=C.DESC_RECURSO and desc_setor_producao=C.DESC_setor_PRODUCAO   
		and data_producao= C.DATA   
	)  
	FROM W_PRODUCAO_ORDEM_HIST_OS C with (nolock)
	WHERE DATEPART(WEEK,C.DATA) BETWEEN DATEPART(WEEK,GETDATE()-7) AND DATEPART(WEEK,GETDATE()-7) AND  DATEPART (year, C.DATA) = DATEPART(YEAR,GETDATE())
	AND C.INDICADOR_TIPO_MOV=1 
	AND C.RECURSO_PRODUTIVO IN ('GAT01')
	GROUP BY DESC_SETOR_PRODUCAO,DESC_RECURSO,RECURSO_PRODUTIVO,PRODUTO,DATA
) AS OFICINA_GRUPO
GROUP BY DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA
ORDER BY DATA


select DATEPART(WEEK,GETDATE())

