UPDATE LF_REGISTRO_ENTRADA_ITEM SET VALOR_IMPOSTO_APURACAO = VALOR_IMPOSTO
WHERE VALOR_IMPOSTO_APURACAO <> VALOR_IMPOSTO
AND (ID_IMPOSTO = '01' or ID_IMPOSTO = '02')
 
UPDATE LF_REGISTRO_SAIDA_ITEM SET VALOR_IMPOSTO_APURACAO = VALOR_IMPOSTO
WHERE VALOR_IMPOSTO_APURACAO <> VALOR_IMPOSTO
AND (ID_IMPOSTO = '01' or ID_IMPOSTO = '02')
 
UPDATE LF_REGISTRO_ENTRADA SET VALOR_IMPOSTO_APURACAO = VALOR_IMPOSTO
WHERE VALOR_IMPOSTO_APURACAO <> VALOR_IMPOSTO
AND (ID_IMPOSTO = '01' or ID_IMPOSTO = '02')
 
UPDATE LF_REGISTRO_SAIDA SET VALOR_IMPOSTO_APURACAO = VALOR_IMPOSTO
WHERE VALOR_IMPOSTO_APURACAO <> VALOR_IMPOSTO
AND (ID_IMPOSTO = '01' or ID_IMPOSTO = '02')
