select * from SAW_DEVOLUCAO
where ID_DEVOLUCAO=0000397


select * from SAW_DEVOLUCAO_PROD
where ID_DEVOLUCAO=0000394


insert into SAW_DEVOLUCAO (ID_DEVOLUCAO,EMISSAO,RAZAO_SOCIAL,REPRESENTANTE,GERENTE,BANCO,CC_AGENCIA,CC_CONTA,APROVACAO,APROVADO_POR,TOT_VALOR_ORIGINAL)
values ('0000394','20150520','ROMEU FICHER','LUCIULA APARECIDA BORDIN ','DENI RICARDO MONCAY CECHI','','','','E',NULL,567.00)


UPDATE SAW_DEVOLUCAO_PROD
SET GRADE='42'
where ID_DEVOLUCAO='0000394' AND PRODUTO='42256' AND COR_PRODUTO='TG 450' AND GRADE=''


select * from SAW_DEVOLUCAO_PROD
where ID_DEVOLUCAO='0000394' AND PRODUTO='42256' AND COR_PRODUTO='TG 450' AND GRADE=''



select * from SAW_REQUISICOES_MATERIAL_ITENS
WHERE ID_REQUISICAO=008606



SP_HELPTEXT sp_Insert_Requisicao_Material