SELECT * FROM LCF_NOTA_ENTRADA_ITEM
WHERE SK_ITEM IS NULL


SELECT * FROM LCF_NOTA_SAIDA_ITEM
WHERE SK_ITEM IS NULL

ALTER TABLE LCF_NOTA_ENTRADA_ITEM ALTER COLUMN SK_ITEM INT NOT NULL

ALTER TABLE LCF_NOTA_SAIDA_ITEM ALTER COLUMN SK_ITEM INT NOT NULL

