----- ajuste na tabela entradas_item

select * from ENTRADAS_ITEM
join ENTRADAS on ENTRADAS.NF_ENTRADA=ENTRADAS_ITEM.NF_ENTRADA and ENTRADAS.SERIE_NF_ENTRADA=ENTRADAS_ITEM.SERIE_NF_ENTRADA and ENTRADAS.FILIAL='dr varejo'
where COD_TABELA_FILHA='S' and ENTRADAS.EMISSAO between '20130301' AND '20130331' and rtrim(LEN(codigo_item))=11


update ENTRADAS_ITEM
set REFERENCIA=SUBSTRING(CODIGO_ITEM,7,10)
from ENTRADAS_ITEM
join ENTRADAS on ENTRADAS.NF_ENTRADA=ENTRADAS_ITEM.NF_ENTRADA and ENTRADAS.SERIE_NF_ENTRADA=ENTRADAS_ITEM.SERIE_NF_ENTRADA and ENTRADAS.FILIAL='dr varejo'
where COD_TABELA_FILHA='S' and ENTRADAS.EMISSAO between '20130301' AND '20130331' and rtrim(LEN(codigo_item))=11



update ENTRADAS_ITEM
set REFERENCIA=SUBSTRING(CODIGO_ITEM,8,10)
from ENTRADAS_ITEM
join ENTRADAS on ENTRADAS.NF_ENTRADA=ENTRADAS_ITEM.NF_ENTRADA and ENTRADAS.SERIE_NF_ENTRADA=ENTRADAS_ITEM.SERIE_NF_ENTRADA and ENTRADAS.FILIAL='dr varejo'
where COD_TABELA_FILHA='S' and ENTRADAS.EMISSAO between '20130301' AND '20130331' and rtrim(LEN(codigo_item))>=12



---- ERRO ID_GENERO_ITEM



lx_cade_coluna id_genero_item

select * from LCF_ITEM
WHERE ID_GENERO_ITEM IS NULL

UPDATE LCF_ITEM SET ID_GENERO_ITEM = '84'
WHERE ID_GENERO_ITEM IS NULL

select * from LCF_LX_ITEM_GENERO
WHERE COD_GENERO_SPED = '85'

SELECT * FROM ENTRADAS_ITEM
WHERE DESCRICAO_ITEM = 'EXTINTOR PÓ QUIMICO 06 KG'

SELECT * FROM ENTRADAS
WHERE NF_ENTRADA = '1761'

select  * from CLASSIF_FISCAL
--where COD_GENERO_SPED is null or COD_GENERO_SPED = ''
ORDER BY COD_GENERO_SPED

SELECT * FROM CLASSIF_FISCAL A 
LEFT JOIN LCF_LX_ITEM_GENERO B ON A.COD_GENERO_SPED = B.COD_GENERO_SPED
WHERE B.COD_GENERO_SPED IS NULL

DELETE FROM LCF_ITEM

select * from LCF_ITEM
where ID_GENERO_ITEM is null

SELECT * FROM CLASSIF_FISCAL
WHERE COD_GENERO_SPED IS NULL

UPDATE CLASSIF_FISCAL
SET COD_GENERO_SPED=CLASSIF_REDUZIDA
WHERE COD_GENERO_SPED IS NULL

alter table LCF_ITEM ALTER COLUMN ID_GENERO_ITEM int NOT null
alter table LCF_ITEM ALTER COLUMN ID_GENERO_ITEM int null

UPDATE a SET CLASSIF_FISCAL = B.CLASSIF_FISCAL
FROM ENTRADAS_ITEM A 
JOIN CADASTRO_ITEM_FISCAL B ON A.REFERENCIA=B.CODIGO_ITEM
WHERE A.CLASSIF_FISCAL <> B.CLASSIF_FISCAL



---- conversa

PAULINO

FOI CORRIGIDO

OK

OBRIGADO, POR TUDO...

SO PRA TE INFORMAR

EXISTE UM ITEM ONDE NÃO TINHA CLASSIF FISCAL

DEVIDO A ESSE ITEM ESTAVA ERRADO, NUMA NOTA DE 2010, SO QUE ESSE CAMPO HOJE 
E BLOQUEADO

ENTENDEU

ENTENDI, MAIS UMA VEZ OBRIGADO E BOA NOITE...
FLW
