select * from ESTOQUE_SAI1_MAT
where REQ_MATERIAL='130263'

UPDATE ESTOQUE_SAI_MAT
SET SERIE_NF=null, NF_SAIDA=null, NF_PENDENTE=1, FILIAL_FATURAMENTO=null
where REQ_MATERIAL='130263'


UPDATE ESTOQUE_SAI1_MAT
SET SERIE_NF=null, NF_SAIDA=null, FILIAL_FATURAMENTO=null
where REQ_MATERIAL='130263'

