select * from PARAMETROS
WHERE PARAMETRO LIKE 'VLR%'

UPDATE PARAMETROS
SET VALOR_ATUAL=380
WHERE PARAMETRO = 'VLR_MINIMO_PARCELA_VENDAS'

UPDATE PARAMETROS
SET VALOR_ATUAL=20
WHERE PARAMETRO = 'VLR_MINIMO_PARCELA_MOSTRU'


	UPDATE 	VENDAS_PRODUTO
	SET 	VENDAS_PRODUTO.ENTREGA = CASE WHEN DBO.FX_DIA_SEMANA(VENDAS_PRODUTO.ENTREGA)=1 THEN (VENDAS_PRODUTO.ENTREGA-2) WHEN DBO.FX_DIA_SEMANA(VENDAS_PRODUTO.ENTREGA)=7 THEN (VENDAS_PRODUTO.ENTREGA-1) ELSE (VENDAS_PRODUTO.ENTREGA) END,
	        VENDAS_PRODUTO.LIMITE_ENTREGA = CASE WHEN DBO.FX_DIA_SEMANA(VENDAS_PRODUTO.LIMITE_ENTREGA)=1 THEN (VENDAS_PRODUTO.LIMITE_ENTREGA-2) WHEN DBO.FX_DIA_SEMANA(VENDAS_PRODUTO.LIMITE_ENTREGA)=7 THEN (VENDAS_PRODUTO.LIMITE_ENTREGA-1) ELSE (VENDAS_PRODUTO.LIMITE_ENTREGA) END
	FROM 	VENDAS_PRODUTO, VENDAS
	WHERE 	VENDAS_PRODUTO.PEDIDO = '88772' AND 
	        VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND 
			VENDAS.FILIAL = 'D.R. LINGERIE' AND 
	        DBO.FX_DIA_SEMANA(VENDAS_PRODUTO.ENTREGA) IN(1,7)


UPDATE VENDAS_PRODUTO
SET ENTREGA='20170723',LIMITE_ENTREGA='20170723'
WHERE PEDIDO='88772'


SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO='88772'
ORDER BY ENTREGA DESC


declare @p4 varchar(8000);
set @p4='407859';
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_SEQUENCIAL @TABELA_COLUNA = ''clientes_atacado.clifor'', @EMPRESA = @P1, @SEQUENCIA = @P2 OUTPUT, @UPDATE_SEQUENCIAL = 1, @NEWVALUE = ''''',N'@P1 int,@P2 varchar(8000) OUTPUT',1,@p4 output
select @p4


declare @p4 varchar(8000); set @p4 = '000000'; exec sp_executesql N' /* VISUALLINX ExecuteNonQuery()  */ EXEC LX_SEQUENCIAL @TABELA_COLUNA = ''clientes_atacado.clifor'', @EMPRESA = @P1, @SEQUENCIA = @P2 OUTPUT, @UPDATE_SEQUENCIAL = 1, @NEWVALUE = ''''',N'@P1 int, @P2 varchar(8000) OUTPUT',1,@p4 output select @p4