update B
set B.CONTA_CONTABIL = '1120101'
from CTB_LANCAMENTO A,CTB_LANCAMENTO_ITEM B  
where A.LANCAMENTO=B.LANCAMENTO AND B.LX_TIPO_LANCAMENTO = 'BTR' and (B.CONTA_CONTABIL = '112010401' or B.CONTA_CONTABIL = '112010402') AND YEAR(A.DATA_LANCAMENTO)>=2015


SELECT * from CTB_LANCAMENTO A,CTB_LANCAMENTO_ITEM B  
where A.LANCAMENTO=B.LANCAMENTO AND B.LX_TIPO_LANCAMENTO = 'BTR' and (B.CONTA_CONTABIL = '112010401' or B.CONTA_CONTABIL = '112010402') AND YEAR(A.DATA_LANCAMENTO)>=2015

SELECT * from CTB_LANCAMENTO A,CTB_LANCAMENTO_ITEM B  
where A.LANCAMENTO=B.LANCAMENTO AND B.LX_TIPO_LANCAMENTO = 'BTR' and (B.CONTA_CONTABIL = '1120101') AND YEAR(A.DATA_LANCAMENTO)>=2015


select * from CTB_LANCAMENTO_ITEM
WHERE CONTA_CONTABIL='1120101'

SELECT * FROM CTB_CONTA_PLANO
WHERE CONTA_CONTABIL='1120101'

