select * from MATERIAIS
WHERE material LIKE '50.08%'


update MATERIAIS
set FASE_PRODUCAO='001',SETOR_PRODUCAO='PCP'
WHERE material LIKE '50.08%'


select * from MATERIAIS
WHERE GRUPO LIKE '%50%' or GRUPO LIKE '%60%' or GRUPO LIKE '%70%'

update MATERIAIS
set FASE_PRODUCAO='002',SETOR_PRODUCAO='ALMOXARIFADO'
WHERE GRUPO LIKE '%50%' or GRUPO LIKE '%60%' or GRUPO LIKE '%70%'




select * from PRODUCAO_RESERVA
where ORDEM_PRODUCAO='78900'

SELECT * FROM PRODUTOS_FICHA


SELECT * FROM TBL_SFV_INSTALACOES_REPRESENTANTE
WHERE REPRESENTANTE LIKE '%DENIL%'

UPDATE TBL_SFV_INSTALACOES_REPRESENTANTE
SET LETRA_INSTALACAO='a',QTDE_INSTALACOES=1
WHERE REPRESENTANTE LIKE '%DENIL%'









select * from MATERIAIS
WHERE GRUPO LIKE '%30%' or SUBGRUPO like '%bojo%'
  
update MATERIAIS
set FASE_PRODUCAO='003',SETOR_PRODUCAO='CORTE'
WHERE GRUPO LIKE '%30%' or SUBGRUPO like '%bojo%'

