SELECT B.PRODUTO,A.CAIXA,A.CAIXA_NUMERO_CLIENTE FROM FATURAMENTO_CAIXAS A
JOIN FATURAMENTO_PROD B ON B.CAIXA=A.CAIXA
WHERE B.PRODUTO = '51364 KIT' AND PEDIDO='578359'


BEGIN TRAN

UPDATE A
SET A.CAIXA_NUMERO_CLIENTE='245126'
FROM FATURAMENTO_CAIXAS A
JOIN FATURAMENTO_PROD B ON B.CAIXA=A.CAIXA
WHERE B.PRODUTO = '51364 KIT' AND PEDIDO='578359'


COMMIT