SELECT * FROM PRODUCAO_TAREFAS
WHERE ORDEM_PRODUCAO='54698' AND SEQUENCIA_PRODUTIVA=70

SELECT * FROM PRODUCAO_TAREFAS
WHERE ORDEM_PRODUCAO='54296' AND SEQUENCIA_PRODUTIVA=80


SELECT * FROM PRODUCAO_TAREFAS
WHERE ORDEM_PRODUCAO='58589' AND SEQUENCIA_PRODUTIVA=70


UPDATE PRODUCAO_TAREFAS
SET RECURSO_PRODUTIVO='RVFIO'
WHERE ORDEM_PRODUCAO='54698' AND SEQUENCIA_PRODUTIVA=70


UPDATE PRODUCAO_TAREFAS
SET RECURSO_PRODUTIVO='REFIO'
WHERE ORDEM_PRODUCAO='54296' AND SEQUENCIA_PRODUTIVA=80


UPDATE PRODUCAO_TAREFAS
SET RECURSO_PRODUTIVO='RVFIO'
WHERE ORDEM_PRODUCAO='59015' AND SEQUENCIA_PRODUTIVA=70


SELECT * FROM PRODUCAO_OS_ANTERIOR
WHERE ORDEM_SERVICO='427808' AND ORDEM_PRODUCAO='58589'


UPDATE PRODUCAO_OS_ANTERIOR
SET TAREFA_ANTERIOR='375747'
WHERE ORDEM_SERVICO='427808' AND ORDEM_PRODUCAO='58589'



exec sp_executesql N'
/* lx008125spk  CursorAdapter: CUR_V_PRODUCAO_OS_01(Alias: v_producao_os_01)  */
SELECT PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO, PRODUCAO_ORDEM_SERVICO.RECURSO_PRODUTIVO,   PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO, PRODUCAO_ORDEM_SERVICO.DATA, PRODUCAO_ORDEM_SERVICO.SETOR_PRODUCAO,   PRODUCAO_ORDEM_SERVICO.CONFERIDO_POR, PRODUCAO_ORDEM_SERVICO.OBSERVACAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO,   PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_RECURSOS.TIPO_RECURSO, PRODUCAO_RECURSOS.DESC_RECURSO,   PRODUCAO_RECURSOS.RECURSO_PROPRIO, PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO_PARALELA,   PRODUCAO_ORDEM_SERVICO.FILIAL, PRODUCAO_ORDEM_SERVICO.NF_SAIDA, PRODUCAO_ORDEM_SERVICO.SERIE_NF,   PRODUCAO_ORDEM_SERVICO.NF_ENTRADA, PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV,   PRODUCAO_ORDEM_SERVICO.SEGUNDA_QUALIDADE, SPACE(5) AS RECURSO_ORIGEM, SPACE(40) AS DESC_REC_ORIGEM,   PRODUCAO_ORDEM_SERVICO.ACERTO_ENTRADA, FILIAIS.EMPRESA, PRODUCAO_ORDEM_SERVICO.BENEFICIADOR_TAREFA_ANTERIOR,   PRODUCAO_ORDEM_SERVICO.SERIE_NF_ENTRADA, PRODUCAO_RECURSOS_A.DESC_RECURSO AS DESC_BENEFICIADOR,   PRODUCAO_RECURSOS_A.RECURSO_PRODUTIVO AS NOME_BENEFICIADOR, PRODUCAO_RECURSOS.NOME_CLIFOR,   PRODUCAO_RECURSOS_A.TIPO_RECURSO AS TIPO_BENEFICIADOR ,FILIAIS.EMPRESA  FROM  DBO.PRODUCAO_FASE PRODUCAO_FASE, DBO.PRODUCAO_SETOR PRODUCAO_SETOR,  DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, DBO.FILIAIS FILIAIS, {OJ  DBO.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO   LEFT OUTER JOIN (SELECT DISTINCT A.ORDEM_SERVICO, C.NOME_CLIFOR ,DESC_RECURSO, C.RECURSO_PRODUTIVO ,TIPO_RECURSO FROM PRODUCAO_OS_ANTERIOR A  INNER JOIN PRODUCAO_TAREFAS B ON A.TAREFA_ANTERIOR = B.TAREFA  INNER JOIN PRODUCAO_RECURSOS C ON B.RECURSO_PRODUTIVO = C.RECURSO_PRODUTIVO) PRODUCAO_RECURSOS_A    ON  PRODUCAO_ORDEM_SERVICO.BENEFICIADOR_TAREFA_ANTERIOR = PRODUCAO_RECURSOS_A.NOME_CLIFOR  AND PRODUCAO_RECURSOS_A.ORDEM_SERVICO = PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO }   WHERE Producao_ordem_servico.INDICADOR_TIPO_MOV = 1 AND PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = @P1 AND (((PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO AND    PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO ) AND    PRODUCAO_ORDEM_SERVICO.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO ) AND   PRODUCAO_ORDEM_SERVICO.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO ) AND   PRODUCAO_ORDEM_SERVICO.FILIAL = FILIAIS.FILIAL  ORDER BY PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO, PRODUCAO_ORDEM_SERVICO.DATA',N'@P1 varchar(6)','427808'



exec sp_executesql N'
/* lx008125spk  CursorAdapter: CUR_V_PRODUCAO_OS_01_TAREFAS(Alias: v_producao_os_01_tarefas)  */
SELECT DISTINCT PRODUCAO_OS_TAREFAS.ORDEM_SERVICO, PRODUCAO_OS_TAREFAS.TAREFA, PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_OS_TAREFAS.PRODUTO, PRODUCAO_OS_TAREFAS.COR_PRODUTO, PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV, PRODUCAO_OS_TAREFAS.QTDE_O, PRODUCAO_OS_TAREFAS.O1, PRODUCAO_OS_TAREFAS.O2, PRODUCAO_OS_TAREFAS.O3, PRODUCAO_OS_TAREFAS.O4, PRODUCAO_OS_TAREFAS.O5, 
PRODUCAO_OS_TAREFAS.O6, PRODUCAO_OS_TAREFAS.O7, PRODUCAO_OS_TAREFAS.O8, PRODUCAO_OS_TAREFAS.O9, PRODUCAO_OS_TAREFAS.O10, PRODUCAO_OS_TAREFAS.O11, PRODUCAO_OS_TAREFAS.O12, PRODUCAO_OS_TAREFAS.O13, PRODUCAO_OS_TAREFAS.O14, PRODUCAO_OS_TAREFAS.O15, PRODUCAO_OS_TAREFAS.O16, 0 AS O17, 0 AS O18, 0 AS O19, 0 AS O20, 0 AS O21, 0 AS O22, 0 AS O23, 0 AS O24, 0 AS O25, 0 AS O26, 0 AS O27, 0 AS O28, 0 AS O29, 0 AS O30, 0 AS O31, 0 AS O32, 0 AS O33, 0 AS O34, 0 AS O35, 0 AS O36, 0 AS O37, 0 AS O38, 0 AS O39, 0 AS O40, 0 AS O41, 0 AS O42, 0 AS O43, 0 AS O44, 0 AS O45, 0 AS O46, 0 AS O47, 0 AS O48, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTO_CORES.TIPO_LAVAGEM_TINTURARIA, PRODUTO_CORES.TINTURARIA_LAVAGEM, PRODUTO_CORES.ETIQUETA, PRODUTOS.DESC_PRODUTO, PRODUTO_CORES.COR, PRODUTOS.GRADE, PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA, PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.INICIO_LIBERADO, PRODUCAO_TAREFAS.INICIO_PREVISTO, PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_PREVISTO, PRODUCAO_TAREFAS.FIM_ATUALIZADO, PRODUCAO_TAREFAS.ENCERRAMENTO, PRODUCAO_TAREFAS.QTDE_PREVISTA, PRODUCAO_TAREFAS.QTDE_A_PRODUZIR, PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS.QTDE_FINALIZADA, PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP, PRODUCAO_TAREFAS.QTDE_PERDAS, PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS, PRODUCAO_OS_TAREFAS.CUSTO_PREVISTO, PRODUCAO_OS_TAREFAS.TAREFA_PARALELA FROM  DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS, DBO.PRODUTO_CORES PRODUTO_CORES, DBO.PRODUTOS PRODUTOS, DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS WHERE (((PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTO_CORES.PRODUTO AND  PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTOS.PRODUTO ) AND  PRODUCAO_TAREFAS.TAREFA = PRODUCAO_OS_TAREFAS.TAREFA ) AND  PRODUCAO_OS_TAREFAS.ORDEM_SERVICO = (@P1 )',N'@P1 varchar(6)','427808'



exec sp_executesql N'
/* lx008125spk  CursorAdapter: CUR_V_PRODUCAO_OS_01_ANTERIOR(Alias: v_producao_os_01_anterior)  */
SELECT PRODUCAO_OS_ANTERIOR.TAREFA,  PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO, PRODUCAO_OS_ANTERIOR.PRODUTO,  PRODUCAO_OS_ANTERIOR.COR_PRODUTO, 
PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO,  PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR,  PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA, 
PRODUCAO_OS_ANTERIOR.QTDE_A,  PRODUCAO_OS_ANTERIOR.A1, PRODUCAO_OS_ANTERIOR.A2,  PRODUCAO_OS_ANTERIOR.A3, PRODUCAO_OS_ANTERIOR.A4,  
PRODUCAO_OS_ANTERIOR.A5, PRODUCAO_OS_ANTERIOR.A6,  PRODUCAO_OS_ANTERIOR.A7, PRODUCAO_OS_ANTERIOR.A8,  PRODUCAO_OS_ANTERIOR.A9, 
PRODUCAO_OS_ANTERIOR.A10,  PRODUCAO_OS_ANTERIOR.A11, PRODUCAO_OS_ANTERIOR.A12,  PRODUCAO_OS_ANTERIOR.A13, PRODUCAO_OS_ANTERIOR.A14,  
PRODUCAO_OS_ANTERIOR.A15, PRODUCAO_OS_ANTERIOR.A16,  0 AS A17, 0 AS A18,  0 AS A19, 0 AS A20,  0 AS A21, 0 AS A22,  0 AS A23, 0 AS A24,  0 AS 
A25, 0 AS A26,  0 AS A27, 0 AS A28,  0 AS A29, 0 AS A30,  0 AS A31, 0 AS A32,  0 AS A33, 0 AS A34,  0 AS A35, 0 AS A36,  0 AS A37, 0 AS A38,  
0 AS A39, 0 AS A40,  0 AS A41, 0 AS A42,  0 AS A43, 0 AS A44,  0 AS A45, 0 AS A46,  0 AS A47, 0 AS A48,  
PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,  PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.INICIO_LIBERADO,  
PRODUCAO_TAREFAS.INICIO_PREVISTO, PRODUCAO_TAREFAS.INICIO_REAL,  PRODUCAO_TAREFAS.FIM_PREVISTO, PRODUCAO_TAREFAS.FIM_ATUALIZADO,  PRODUCAO_TAREFAS.ENCERRAMENTO, PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,  PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS.QTDE_FINALIZADA,  PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP, PRODUCAO_TAREFAS.QTDE_PERDAS,  PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.QTDE_PREVISTA, PRODUCAO_TAREFAS.CUSTO_TAREFA,  PRODUCAO_TAREFAS.DESCONTOS_TAREFA, PRODUCAO_TAREFAS.VALOR_TAREFA,  PRODUCAO_TAREFAS.STATUS, PRODUCAO_RECURSOS.TIPO_RECURSO,  PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_TAREFAS.FASE_PRODUCAO,  PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,  PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,  PRODUCAO_TAREFAS.TEMPO_PREPARACAO, PRODUCAO_TAREFAS.METODO_LOTE,  PRODUCAO_TAREFAS.METODO_LOTE_QTDE,  PRODUCAO_TAREFAS.TIPO_TEMPO_PROCESSO,  PRODUCAO_OS_ANTERIOR.COR_ANTERIOR, W_PRODUTOS_CORES.GRADE,  PRODUCAO_OS_ANTERIOR.CUSTO_EFETIVO,  PRODUCAO_OS_ANTERIOR.DESCONTO_APLICADO,  PRODUCAO_OS_ANTERIOR.VALOR_CREDITADO,  PRODUCAO_OS_ANTERIOR.NOME_CLIFOR, PRODUCAO_OS_ANTERIOR.NF_ENTRADA, PRODUCAO_OS_ANTERIOR.CUSTO_MATERIAL_TERCEIRO FROM DBO.PRODUCAO_OS_ANTERIOR PRODUCAO_OS_ANTERIOR,  DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS,  DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS,  DBO.PRODUCAO_FASE PRODUCAO_FASE, DBO.PRODUCAO_SETOR PRODUCAO_SETOR,  DBO.W_PRODUTOS_CORES W_PRODUTOS_CORES WHERE PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO   AND PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO   AND PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO   AND PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO   AND PRODUCAO_OS_ANTERIOR.PRODUTO = W_PRODUTOS_CORES.PRODUTO   AND W_PRODUTOS_CORES.COR_PRODUTO = PRODUCAO_OS_ANTERIOR.COR_ANTERIOR   AND PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR = PRODUCAO_TAREFAS.TAREFA   AND PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO = @P1',N'@P1 varchar(6)','427808'
