SELECT PRODUTOS.PRODUTO, PRECO_FATORES.* FROM PRECO_FATORES, PRODUTOS
WHERE PRODUTOS.PRODUTO='40002'
ORDER BY PRECO_TIPO,SEQUENCIA


SELECT A.PRODUTO,B.CODIGO_TAB_PRECO,B.PRECO1,C.* FROM PRODUTOS A
JOIN PRODUTOS_PRECOS B ON B.PRODUTO=A.PRODUTO
JOIN (SELECT PRODUTOS.PRODUTO, PRECO_FATORES.* FROM PRECO_FATORES, PRODUTOS) C ON C.PRODUTO=A.PRODUTO
WHERE A.PRODUTO = '40002' AND B.CODIGO_TAB_PRECO='BP'
ORDER BY PRECO_TIPO,SEQUENCIA


SELECT * FROM PRODUTOS_FICHA_COR
WHERE PRODUTO='40002'



DECLARE @TAMANHO_BASE CHAR(2)
SET @TAMANHO_BASE = 4

SELECT DISTINCT 
VALOR = CASE @TAMANHO_BASE
   WHEN 1 THEN (PRODUTOS_FICHA.C1 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR
   WHEN 2 THEN (PRODUTOS_FICHA.C2 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR
   WHEN 3 THEN (PRODUTOS_FICHA.C3 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR  
   WHEN 4 THEN (PRODUTOS_FICHA.C4 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR  
END, 
PRODUTOS_FICHA.PRODUTO, PRODUTOS_FICHA_COR.COR_PRODUTO, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTOS_FICHA.ITEM, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, W_MATERIAIS_CORES.DESC_MATERIAL, 
PRODUTOS_FICHA_COR.COR_MATERIAL, W_MATERIAIS_CORES.DESC_COR_MATERIAL, W_MATERIAIS_CORES.UNID_FICHA_TEC, W_MATERIAIS_CORES.FATOR_CONVERSAO, W_MATERIAIS_CORES.UNID_ESTOQUE, PRODUTOS_FICHA.CONSUMO_P_TAMANHO, 
PRODUTOS_FICHA_COR.PORCENTAGEM_CONSUMO, W_MATERIAIS_CORES.CUSTO_A_VISTA_COR, PRODUTOS_FICHA.MATERIAL_PRINCIPAL, W_MATERIAIS_CORES.VARIA_CUSTO_COR, PRODUTOS_FICHA.DESC_USO_MATERIAL, PRODUTOS_FICHA.C1, PRODUTOS_FICHA.C2, 
PRODUTOS_FICHA.C3, PRODUTOS_FICHA.C4, PRODUTOS_FICHA.C5, PRODUTOS_FICHA.C6, PRODUTOS_FICHA.C7, PRODUTOS_FICHA.C8, PRODUTOS_FICHA.C9, PRODUTOS_FICHA.C10, PRODUTOS_FICHA.C11, PRODUTOS_FICHA.C12, PRODUTOS_FICHA.C13, 
PRODUTOS_FICHA.C14, PRODUTOS_FICHA.C15, PRODUTOS_FICHA.C16, 0 AS C17, 0 AS C18, 0 AS C19, 0 AS C20, 0 AS C21, 0 AS C22, 0 AS C23, 0 AS C24, 0 AS C25, 0 AS C26, 0 AS C27, 0 AS C28, 0 AS C29, 0 AS C30, 0 AS C31, 0 AS C32, 0 AS 
C33, 0 AS C34, 0 AS C35, 0 AS C36, 0 AS C37, 0 AS C38, 0 AS C39, 0 AS C40, 0 AS C41, 0 AS C42, 0 AS C43, 0 AS C44, 0 AS C45, 0 AS C46, 0 AS C47, 0 AS C48, W_MATERIAIS_CORES.TIPO, PRODUTOS_FICHA.FASE_PRODUCAO, PRODUTOS_FICHA.SETOR_PRODUCAO, W_MATERIAIS_CORES.FABRICANTE, W_MATERIAIS_CORES.COLECAO, W_MATERIAIS_CORES.SUBGRUPO, W_MATERIAIS_CORES.COMPRIMENTO, W_MATERIAIS_CORES.REVENDA, W_MATERIAIS_CORES.VARIA_MATERIAL_TAMANHO, W_MATERIAIS_CORES.LARGURA, W_MATERIAIS_CORES.DATA_REPOSICAO, W_MATERIAIS_CORES.REF_FABRICANTE, W_MATERIAIS_CORES.ICMS_CUSTOS, W_MATERIAIS_CORES.TAXA_JUROS_CUSTO, W_MATERIAIS_CORES.REFER_FABRICANTE, W_MATERIAIS_CORES.CUSTO_REPOSICAO_COR, MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO, CONVERT(NUMERIC(14,3),0.000) AS CONSUMO_BASE, CONVERT(NUMERIC(14,5),0.00000) AS VALOR, PRODUTO_CORES.PRECO_REPOSICAO_1, PRODUTO_CORES.PRECO_REPOSICAO_2, PRODUTO_CORES.PRECO_REPOSICAO_3, PRODUTO_CORES.PRECO_REPOSICAO_4, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_1, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_2, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_3, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_4 
FROM PRODUTOS_FICHA 
INNER JOIN PRODUTOS_FICHA_COR ON PRODUTOS_FICHA.ITEM = PRODUTOS_FICHA_COR.ITEM AND PRODUTOS_FICHA.PRODUTO = PRODUTOS_FICHA_COR.PRODUTO 
INNER JOIN W_MATERIAIS_CORES ON PRODUTOS_FICHA_COR.MATERIAL = W_MATERIAIS_CORES.MATERIAL AND PRODUTOS_FICHA_COR.COR_MATERIAL = W_MATERIAIS_CORES.COR_MATERIAL 
INNER JOIN PRODUTO_CORES ON PRODUTOS_FICHA_COR.PRODUTO = PRODUTO_CORES.PRODUTO AND PRODUTOS_FICHA_COR.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN MATERIAIS_SUBGRUPO ON W_MATERIAIS_CORES.GRUPO = MATERIAIS_SUBGRUPO.GRUPO AND W_MATERIAIS_CORES.SUBGRUPO = MATERIAIS_SUBGRUPO.SUBGRUPO 
INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUTOS_FICHA.PRODUTO 
WHERE PRODUTOS_FICHA.PRODUTO = '51262' AND MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO = 0 ORDER BY PRODUTOS_FICHA_COR.COR_PRODUTO, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, PRODUTOS_FICHA_COR.COR_MATERIAL


DECLARE @TAMANHO_BASE CHAR(2)
SET @TAMANHO_BASE = 4

SELECT PRODUTO,COR_PRODUTO,SUM(VALOR) FROM (

SELECT DISTINCT 
VALOR = CASE @TAMANHO_BASE
   WHEN 1 THEN (PRODUTOS_FICHA.C1 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR
   WHEN 2 THEN (PRODUTOS_FICHA.C2 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR
   WHEN 3 THEN (PRODUTOS_FICHA.C3 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR  
   WHEN 4 THEN (PRODUTOS_FICHA.C4 / W_MATERIAIS_CORES.FATOR_CONVERSAO) *  W_MATERIAIS_CORES.CUSTO_A_VISTA_COR  
END, 
PRODUTOS_FICHA.PRODUTO, PRODUTOS_FICHA_COR.COR_PRODUTO, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTOS_FICHA.ITEM, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, W_MATERIAIS_CORES.DESC_MATERIAL, 
PRODUTOS_FICHA_COR.COR_MATERIAL, W_MATERIAIS_CORES.DESC_COR_MATERIAL, W_MATERIAIS_CORES.UNID_FICHA_TEC, W_MATERIAIS_CORES.FATOR_CONVERSAO, W_MATERIAIS_CORES.UNID_ESTOQUE, PRODUTOS_FICHA.CONSUMO_P_TAMANHO, 
PRODUTOS_FICHA_COR.PORCENTAGEM_CONSUMO, W_MATERIAIS_CORES.CUSTO_A_VISTA_COR, PRODUTOS_FICHA.MATERIAL_PRINCIPAL, W_MATERIAIS_CORES.VARIA_CUSTO_COR, PRODUTOS_FICHA.DESC_USO_MATERIAL, PRODUTOS_FICHA.C1, PRODUTOS_FICHA.C2, 
PRODUTOS_FICHA.C3, PRODUTOS_FICHA.C4, PRODUTOS_FICHA.C5, PRODUTOS_FICHA.C6, PRODUTOS_FICHA.C7, PRODUTOS_FICHA.C8, PRODUTOS_FICHA.C9, PRODUTOS_FICHA.C10, PRODUTOS_FICHA.C11, PRODUTOS_FICHA.C12, PRODUTOS_FICHA.C13, 
PRODUTOS_FICHA.C14, PRODUTOS_FICHA.C15, PRODUTOS_FICHA.C16, 0 AS C17, 0 AS C18, 0 AS C19, 0 AS C20, 0 AS C21, 0 AS C22, 0 AS C23, 0 AS C24, 0 AS C25, 0 AS C26, 0 AS C27, 0 AS C28, 0 AS C29, 0 AS C30, 0 AS C31, 0 AS C32, 0 AS 
C33, 0 AS C34, 0 AS C35, 0 AS C36, 0 AS C37, 0 AS C38, 0 AS C39, 0 AS C40, 0 AS C41, 0 AS C42, 0 AS C43, 0 AS C44, 0 AS C45, 0 AS C46, 0 AS C47, 0 AS C48, W_MATERIAIS_CORES.TIPO, PRODUTOS_FICHA.FASE_PRODUCAO, PRODUTOS_FICHA.SETOR_PRODUCAO, W_MATERIAIS_CORES.FABRICANTE, W_MATERIAIS_CORES.COLECAO, W_MATERIAIS_CORES.SUBGRUPO, W_MATERIAIS_CORES.COMPRIMENTO, W_MATERIAIS_CORES.REVENDA, W_MATERIAIS_CORES.VARIA_MATERIAL_TAMANHO, W_MATERIAIS_CORES.LARGURA, W_MATERIAIS_CORES.DATA_REPOSICAO, W_MATERIAIS_CORES.REF_FABRICANTE, W_MATERIAIS_CORES.ICMS_CUSTOS, W_MATERIAIS_CORES.TAXA_JUROS_CUSTO, W_MATERIAIS_CORES.REFER_FABRICANTE, W_MATERIAIS_CORES.CUSTO_REPOSICAO_COR, MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO, CONVERT(NUMERIC(14,3),0.000) AS CONSUMO_BASE, CONVERT(NUMERIC(14,5),0.00000) AS VALOR, PRODUTO_CORES.PRECO_REPOSICAO_1, PRODUTO_CORES.PRECO_REPOSICAO_2, PRODUTO_CORES.PRECO_REPOSICAO_3, PRODUTO_CORES.PRECO_REPOSICAO_4, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_1, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_2, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_3, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_4 
FROM PRODUTOS_FICHA 
INNER JOIN PRODUTOS_FICHA_COR ON PRODUTOS_FICHA.ITEM = PRODUTOS_FICHA_COR.ITEM AND PRODUTOS_FICHA.PRODUTO = PRODUTOS_FICHA_COR.PRODUTO 
INNER JOIN W_MATERIAIS_CORES ON PRODUTOS_FICHA_COR.MATERIAL = W_MATERIAIS_CORES.MATERIAL AND PRODUTOS_FICHA_COR.COR_MATERIAL = W_MATERIAIS_CORES.COR_MATERIAL 
INNER JOIN PRODUTO_CORES ON PRODUTOS_FICHA_COR.PRODUTO = PRODUTO_CORES.PRODUTO AND PRODUTOS_FICHA_COR.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN MATERIAIS_SUBGRUPO ON W_MATERIAIS_CORES.GRUPO = MATERIAIS_SUBGRUPO.GRUPO AND W_MATERIAIS_CORES.SUBGRUPO = MATERIAIS_SUBGRUPO.SUBGRUPO 
INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUTOS_FICHA.PRODUTO 
WHERE PRODUTOS_FICHA.PRODUTO = '51262' AND MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO = 0 
) AS TOTAL
GROUP BY PRODUTO,COR_PRODUTO



SELECT 
TAMANHO=CASE CHARINDEX('.',B.TAMANHO_1) WHEN 0 THEN 'TAMANHO BASE É: '+B.TAMANHO_1
END,
TAMANHO=CASE CHARINDEX('.',B.TAMANHO_2) WHEN 0 THEN 'TAMANHO BASE É: '+B.TAMANHO_2
END,
TAMANHO=CASE CHARINDEX('.',B.TAMANHO_3) WHEN 0 THEN 'TAMANHO BASE É: '+B.TAMANHO_3
END,
TAMANHO=CASE CHARINDEX('.',B.TAMANHO_4) WHEN 0 THEN 'TAMANHO BASE É: '+B.TAMANHO_4
END,
b.*
FROM PRODUTOS_TAMANHOS A
JOIN PRODUTOS_TAMANHOS B ON B.GRADE_BASE=A.GRADE
WHERE B.GRADE='P A GG'






