SELECT * FROM CM_ESTOQUE_PA
WHERE COD_CUSTO_MEDIO='31012015' AND FILIAL='DR VAREJO' AND CUSTO_MEDIO_UNITARIO=0

SELECT * FROM CM_ESTOQUE_PA
WHERE COD_CUSTO_MEDIO='31122014' AND FILIAL='DR VAREJO' AND CUSTO_MEDIO_UNITARIO=0


UPDATE A
SET A.VALOR_SALDO=(A.QTDE_SALDO*1.00),A.CUSTO_MEDIO_UNITARIO=(VALOR_SALDO/QTDE_SALDO)
SELECT * FROM CM_ESTOQUE_PA A
WHERE COD_CUSTO_MEDIO='31122014' AND FILIAL='DR VAREJO' AND CUSTO_MEDIO_UNITARIO=0


UPDATE A
SET VALOR=QTDE*1.00
FROM CM_ESTOQUE_PA_COMPOSICAO A WHERE COD_CUSTO_MEDIO='31122014' AND VALOR=0


SELECT * FROM CM_ESTOQUE_PA_COMPOSICAO A 
WHERE COD_CUSTO_MEDIO='31122014' AND VALOR=0


EXECUTE LX_CM_FECHAMENTO_CUSTO_MEDIO ?V_FECHAMENTO_CUSTO_MEDIO_00.COD_CUSTO_MEDIO, ?cEmpresa
EXECUTE LX_CM_COMPOSICAO_CUSTO_PA @COD_CUSTO_MEDIO, @EMPRESA  
EXECUTE LX_CM_CUSTO_PA @COD_CUSTO_MEDIO, @EMPRESA 

