SELECT LOG_ALTERACOES.COLUNA, LOG_ALTERACOES.SEQUENCIAL,  LOG_ALTERACOES.VALOR_NOVO, LOG_ALTERACOES.VALOR_ANTIGO,  
LOG_ALTERACOES.TABELA FROM DBO.LOG_ALTERACOES LOG_ALTERACOES WITH (NOLOCK)
WHERE coluna='ORDEM_PRODUCAO' AND VALOR_ANTIGO='208550' 
order by sequencial



201662     