SELECT PRODUTOS.GRUPO_PRODUTO, CADASTRO_CLI_FOR.UF, VENDAS.FILIAL, 
DATA_EM_ABERTO=DATA_TITULO_EM_ATRASO,
VENDAS.PEDIDO, VENDAS.COLECAO, VENDAS.CODIGO_TAB_PRECO, 
VENDAS.CONDICAO_PGTO, VENDAS.CLIENTE_ATACADO, VENDAS.REPRESENTANTE, 
VENDAS.GERENTE, VENDAS.EMISSAO, VENDAS.TOT_VALOR_ORIGINAL, VENDAS.TOT_VALOR_ENTREGUE, 
VENDAS.TOT_VALOR_CANCELADO, VENDAS.TOT_VALOR_DEVOLVIDO, VENDAS.TOT_VALOR_ENTREGAR, 
VENDAS.DESCONTO, VENDAS.PRIORIDADE, VENDAS.STATUS, VENDAS.APROVACAO, VENDAS.APROVADO_POR, 
VENDAS.PORC_DESCONTO, VENDAS.PORC_DESCONTO_BRUTO, VENDAS.PORC_DESCONTO_DIGITADO, 
VENDAS.DESCONTO_COND_PGTO, VENDAS.TIPO, VENDAS_PRODUTO.PEDIDO, VENDAS_PRODUTO.ENTREGA, 
VENDAS_PRODUTO.LIMITE_ENTREGA, VENDAS_PRODUTO.QTDE_ORIGINAL, VENDAS_PRODUTO.QTDE_EMBALADA, 
QTDE_A_RESERVAR=ISNULL(ROMANEIOS_RESERVAS.QTDE_R,0), 
VENDAS_PRODUTO.QTDE_ENTREGAR, VENDAS_PRODUTO.QTDE_ENTREGUE, VENDAS_PRODUTO.QTDE_DEVOLVIDA, 
VENDAS_PRODUTO.QTDE_CANCELADA, COLECOES.COLECAO, COLECOES.DESC_COLECAO, COND_ATAC_PGTOS.CONDICAO_PGTO, 
COND_ATAC_PGTOS.DESC_COND_PGTO, VENDAS_PRODUTO.PRODUTO,
QTDE_PRODUTO_FALTA=DBO.QTDE_FALTA_PRODUTO(VENDAS.PEDIDO)
FROM VENDAS_PRODUTO VENDAS_PRODUTO with (nolock)
JOIN VENDAS VENDAS with (nolock) ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN COLECOES COLECOES with (nolock) ON COLECOES.COLECAO = VENDAS.COLECAO
JOIN COND_ATAC_PGTOS COND_ATAC_PGTOS with (nolock) ON COND_ATAC_PGTOS.CONDICAO_PGTO = VENDAS.CONDICAO_PGTO
LEFT JOIN ROMANEIOS_RESERVAS ROMANEIOS_RESERVAS with (nolock) ON ROMANEIOS_RESERVAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND ROMANEIOS_RESERVAS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND ROMANEIOS_RESERVAS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO
JOIN CADASTRO_CLI_FOR with (nolock) ON CADASTRO_CLI_FOR.NOME_CLIFOR = VENDAS.CLIENTE_ATACADO
JOIN PRODUTOS WITH (NOLOCK) ON PRODUTOS.PRODUTO = VENDAS_PRODUTO.PRODUTO
LEFT JOIN ( 
      SELECT B.COD_CLIFOR,MAX(A.VENCIMENTO_REAL) AS DATA_TITULO_EM_ATRASO
      FROM CTB_A_RECEBER_PARCELA A WITH (NOLOCK)     
      JOIN CTB_A_RECEBER_FATURA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM    
      WHERE A.VALOR_A_RECEBER > 0 AND A.VENCIMENTO_REAL <= (GETDATE()-3)
      GROUP BY B.COD_CLIFOR
) AS TITULOS_EM_ATRASO ON TITULOS_EM_ATRASO.COD_CLIFOR=CADASTRO_CLI_FOR.CLIFOR 
WHERE ((VENDAS.EMISSAO>={ts '2014-01-01 00:00:00'}) AND (VENDAS.TOT_VALOR_ENTREGAR>0) AND (VENDAS_PRODUTO.ENTREGA>={ts '2014-01-01 00:00:00'}))


--- Grade na Carteira
SELECT *,FALTA=(VE-EMB) FROM (

SELECT PRODUTOS.GRUPO_PRODUTO,
VENDAS.PEDIDO, VENDAS.COLECAO, VENDAS.CODIGO_TAB_PRECO, 
VENDAS.CONDICAO_PGTO, VENDAS.CLIENTE_ATACADO, VENDAS.REPRESENTANTE, 
VENDAS.GERENTE, VENDAS.EMISSAO, VENDAS_PRODUTO.ENTREGA, VENDAS_PRODUTO.LIMITE_ENTREGA, 
VENDAS_PRODUTO.PRODUTO,PRODUTOS_BARRA.COR_PRODUTO,PRODUTOS_BARRA.GRADE,
VO = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.Vo1 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.Vo2 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.Vo3 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.Vo4 
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.Vo5 
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.Vo6 
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.Vo7 
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.Vo8 
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.Vo9 
           WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.Vo10 
           WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.Vo11 
           WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.Vo12 
           WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.Vo13 
           WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.Vo14 
           WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.Vo15 
           WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.Vo16 
END),
VE = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VE1 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VE2 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VE3 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VE4 
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VE5 
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VE6 
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VE7 
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VE8 
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VE9 
           WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VE10 
           WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VE11 
           WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VE12 
           WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VE13 
           WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VE14 
           WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VE15 
           WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VE16 
END),
EMB = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN ISNULL(VENDAS_PROD_EMBALADO.E1,0) 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN ISNULL(VENDAS_PROD_EMBALADO.E2,0) 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN ISNULL(VENDAS_PROD_EMBALADO.E3,0) 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN ISNULL(VENDAS_PROD_EMBALADO.E4,0)  
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN ISNULL(VENDAS_PROD_EMBALADO.E5,0)  
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN ISNULL(VENDAS_PROD_EMBALADO.E6,0)  
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN ISNULL(VENDAS_PROD_EMBALADO.E7,0)  
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN ISNULL(VENDAS_PROD_EMBALADO.E8,0)  
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN ISNULL(VENDAS_PROD_EMBALADO.E9,0)  
           WHEN PRODUTOS_BARRA.tamanho='10' THEN ISNULL(VENDAS_PROD_EMBALADO.E10,0)  
           WHEN PRODUTOS_BARRA.tamanho='11' THEN ISNULL(VENDAS_PROD_EMBALADO.E11,0)  
           WHEN PRODUTOS_BARRA.tamanho='12' THEN ISNULL(VENDAS_PROD_EMBALADO.E12,0)  
           WHEN PRODUTOS_BARRA.tamanho='13' THEN ISNULL(VENDAS_PROD_EMBALADO.E13,0)  
           WHEN PRODUTOS_BARRA.tamanho='14' THEN ISNULL(VENDAS_PROD_EMBALADO.E14,0)  
           WHEN PRODUTOS_BARRA.tamanho='15' THEN ISNULL(VENDAS_PROD_EMBALADO.E15,0)  
           WHEN PRODUTOS_BARRA.tamanho='16' THEN ISNULL(VENDAS_PROD_EMBALADO.E16,0)  
END)
FROM VENDAS_PRODUTO VENDAS_PRODUTO with (nolock)
JOIN VENDAS VENDAS with (nolock) ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN COLECOES COLECOES with (nolock) ON COLECOES.COLECAO = VENDAS.COLECAO
JOIN COND_ATAC_PGTOS COND_ATAC_PGTOS with (nolock) ON COND_ATAC_PGTOS.CONDICAO_PGTO = VENDAS.CONDICAO_PGTO
LEFT JOIN ROMANEIOS_RESERVAS ROMANEIOS_RESERVAS with (nolock) ON ROMANEIOS_RESERVAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND ROMANEIOS_RESERVAS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND ROMANEIOS_RESERVAS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO
JOIN CADASTRO_CLI_FOR with (nolock) ON CADASTRO_CLI_FOR.NOME_CLIFOR = VENDAS.CLIENTE_ATACADO
JOIN PRODUTOS WITH (NOLOCK) ON PRODUTOS.PRODUTO = VENDAS_PRODUTO.PRODUTO

LEFT JOIN (

     SELECT FILIAL,PEDIDO,PRODUTO,COR_PRODUTO,E1=SUM(E1),E2=SUM(E2),E3=SUM(E3),E4=SUM(E4),E5=SUM(E5),E6=SUM(E6),E7=SUM(E7),E8=SUM(E8),E9=SUM(E9),E10=SUM(E10),E11=SUM(E11),E12=SUM(E12),E13=SUM(E13),E14=SUM(E14),E15=SUM(E15),E16=SUM(E16) FROM VENDAS_PROD_EMBALADO with (nolock)
     GROUP BY FILIAL,PEDIDO,PRODUTO,COR_PRODUTO

) AS VENDAS_PROD_EMBALADO ON VENDAS_PROD_EMBALADO.PEDIDO=VENDAS_PRODUTO.PEDIDO AND VENDAS_PROD_EMBALADO.PRODUTO=VENDAS_PRODUTO.PRODUTO AND VENDAS_PROD_EMBALADO.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO 

JOIN (SELECT PRODUTO,COR_PRODUTO,TAMANHO,GRADE FROM PRODUTOS_BARRA with (nolock) WHERE CODIGO_BARRA LIKE '789%') AS PRODUTOS_BARRA ON PRODUTOS_BARRA.PRODUTO=VENDAS_PRODUTO.PRODUTO AND PRODUTOS_BARRA.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO
WHERE ((VENDAS.EMISSAO>={ts '2014-01-01 00:00:00'}) AND (VENDAS_PRODUTO.ENTREGA>={ts '2014-01-01 00:00:00'}))
) AS VENDAS_PRODUTO_VERTICAL
WHERE VENDAS_PRODUTO_VERTICAL.VE>0 



-- Faturamento sem Merchandising
select C.GRIFFE, C.GRUPO_PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.EMISSAO,A.MPADRAO_VALOR_LIQUIDO,A.QTDE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - ((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END )))
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
WHERE B.EMISSAO >='20140101' AND B.EMISSAO <= '20161231' AND A.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'



/* lx100114spk  CursorAdapter: CUR_V_FATURAMENTO_PROD_02(Alias: v_faturamento_prod_02)  */
SELECT W_FATURAMENTO_PROD_02.NF_SAIDA, W_FATURAMENTO_PROD_02.SERIE_NF, W_FATURAMENTO_PROD_02.FILIAL, W_FATURAMENTO_PROD_02.NOME_CLIFOR, W_FATURAMENTO_PROD_02.PRODUTO, W_FATURAMENTO_PROD_02.COR_PRODUTO, W_FATURAMENTO_PROD_02.MOEDA, W_FATURAMENTO_PROD_02.CAMBIO_NA_DATA, W_FATURAMENTO_PROD_02.ITEM, W_FATURAMENTO_PROD_02.ENTREGA, W_FATURAMENTO_PROD_02.PEDIDO_COR, W_FATURAMENTO_PROD_02.PEDIDO, W_FATURAMENTO_PROD_02.CAIXA, W_FATURAMENTO_PROD_02.ROMANEIO, W_FATURAMENTO_PROD_02.PACKS, W_FATURAMENTO_PROD_02.CUSTO_NA_DATA, W_FATURAMENTO_PROD_02.QTDE, W_FATURAMENTO_PROD_02.PRECO, W_FATURAMENTO_PROD_02.MPADRAO_PRECO, W_FATURAMENTO_PROD_02.DESCONTO_ITEM, W_FATURAMENTO_PROD_02.MPADRAO_DESCONTO_ITEM, W_FATURAMENTO_PROD_02.VALOR, W_FATURAMENTO_PROD_02.MPADRAO_VALOR, W_FATURAMENTO_PROD_02.VALOR_PRODUCAO, W_FATURAMENTO_PROD_02.MPADRAO_VALOR_PRODUCAO, W_FATURAMENTO_PROD_02.DIF_PRODUCAO, W_FATURAMENTO_PROD_02.MPADRAO_DIF_PRODUCAO, W_FATURAMENTO_PROD_02.VALOR_LIQUIDO, W_FATURAMENTO_PROD_02.MPADRAO_VALOR_LIQUIDO, 
W_FATURAMENTO_PROD_02.DIF_PRODUCAO_LIQUIDO, W_FATURAMENTO_PROD_02.MPADRAO_DIF_PRODUCAO_LIQUIDO, W_FATURAMENTO_PROD_02.F1, W_FATURAMENTO_PROD_02.F2, 
W_FATURAMENTO_PROD_02.F3, W_FATURAMENTO_PROD_02.F4, W_FATURAMENTO_PROD_02.F5, W_FATURAMENTO_PROD_02.F6, W_FATURAMENTO_PROD_02.F7, W_FATURAMENTO_PROD_02.F8, 
W_FATURAMENTO_PROD_02.F9, W_FATURAMENTO_PROD_02.F10, W_FATURAMENTO_PROD_02.F11, W_FATURAMENTO_PROD_02.F12, W_FATURAMENTO_PROD_02.F13, 
W_FATURAMENTO_PROD_02.F14, W_FATURAMENTO_PROD_02.F15, W_FATURAMENTO_PROD_02.F16, W_FATURAMENTO_PROD_02.F17, W_FATURAMENTO_PROD_02.F18, 
W_FATURAMENTO_PROD_02.F19, W_FATURAMENTO_PROD_02.F20, W_FATURAMENTO_PROD_02.F21, W_FATURAMENTO_PROD_02.F22, W_FATURAMENTO_PROD_02.F23, 
W_FATURAMENTO_PROD_02.F24, W_FATURAMENTO_PROD_02.F25, W_FATURAMENTO_PROD_02.F26, W_FATURAMENTO_PROD_02.F27, W_FATURAMENTO_PROD_02.F28, 
W_FATURAMENTO_PROD_02.F29, W_FATURAMENTO_PROD_02.F30, W_FATURAMENTO_PROD_02.F31, W_FATURAMENTO_PROD_02.F32, W_FATURAMENTO_PROD_02.F33, 
W_FATURAMENTO_PROD_02.F34, W_FATURAMENTO_PROD_02.F35, W_FATURAMENTO_PROD_02.F36, W_FATURAMENTO_PROD_02.F37, W_FATURAMENTO_PROD_02.F38, 
W_FATURAMENTO_PROD_02.F39, W_FATURAMENTO_PROD_02.F40, W_FATURAMENTO_PROD_02.F41, W_FATURAMENTO_PROD_02.F42, W_FATURAMENTO_PROD_02.F43, 
W_FATURAMENTO_PROD_02.F44, W_FATURAMENTO_PROD_02.F45, W_FATURAMENTO_PROD_02.F46, W_FATURAMENTO_PROD_02.F47, W_FATURAMENTO_PROD_02.F48, 
W_FATURAMENTO_PROD_02.EMISSAO, W_FATURAMENTO_PROD_02.CONDICAO_PGTO, W_FATURAMENTO_PROD_02.NATUREZA_SAIDA, W_FATURAMENTO_PROD_02.GERENTE, 
W_FATURAMENTO_PROD_02.REPRESENTANTE, W_FATURAMENTO_PROD_02.DATA_SAIDA, W_FATURAMENTO_PROD_02.TRANSPORTADORA, W_FATURAMENTO_PROD_02.TRANSP_REDESPACHO, 
W_FATURAMENTO_PROD_02.EMPRESA, W_FATURAMENTO_PROD_02.TIPO_FATURAMENTO, W_FATURAMENTO_PROD_02.DESC_PRODUTO, W_FATURAMENTO_PROD_02.COLECAO, W_FATURAMENTO_PROD_02.TABELA_OPERACOES, W_FATURAMENTO_PROD_02.TABELA_MEDIDAS, W_FATURAMENTO_PROD_02.TIPO_PRODUTO, W_FATURAMENTO_PROD_02.GRUPO_PRODUTO, W_FATURAMENTO_PROD_02.SUBGRUPO_PRODUTO, W_FATURAMENTO_PROD_02.LINHA, W_FATURAMENTO_PROD_02.GRIFFE, W_FATURAMENTO_PROD_02.CARTELA, W_FATURAMENTO_PROD_02.REVENDA, W_FATURAMENTO_PROD_02.MODELAGEM, W_FATURAMENTO_PROD_02.FABRICANTE, W_FATURAMENTO_PROD_02.ESTILISTA, W_FATURAMENTO_PROD_02.MODELISTA, W_FATURAMENTO_PROD_02.PERIODO_PCP, W_FATURAMENTO_PROD_02.REFER_FABRICANTE, W_FATURAMENTO_PROD_02.GRADE, W_FATURAMENTO_PROD_02.INATIVO, W_FATURAMENTO_PROD_02.DESC_COR_PRODUTO, W_FATURAMENTO_PROD_02.COR_SORTIDA, W_FATURAMENTO_PROD_02.TINTURARIA_LAVAGEM, W_FATURAMENTO_PROD_02.TIPO_LAVAGEM_TINTURARIA, W_FATURAMENTO_PROD_02.DESC_COND_PGTO, W_FATURAMENTO_PROD_02.DESC_NATUREZA, W_FATURAMENTO_PROD_02.CTB_TIPO_OPERACAO, W_FATURAMENTO_PROD_02.DESC_TIPO_OPERACAO, W_FATURAMENTO_PROD_02.TIPO_OPERACAO, W_FATURAMENTO_PROD_02.DESC_GRUPO_TIPO_OPERACAO, W_FATURAMENTO_PROD_02.COLECAO_VENDA, W_FATURAMENTO_PROD_02.TIPO, W_FATURAMENTO_PROD_02.DESCRICAO_SERIE_NF, W_FATURAMENTO_PROD_02.COD_FILIAL, W_FATURAMENTO_PROD_02.CLIFOR, W_FATURAMENTO_PROD_02.DESC_COLECAO, W_FATURAMENTO_PROD_02.ITEM_IMPRESSAO, W_FATURAMENTO_PROD_02.DESC_COLECAO_VENDA, W_FATURAMENTO_PROD_02.ID_MODIFICACAO, W_FATURAMENTO_PROD_02.DESC_MODIFICACAO,W_FATURAMENTO_PROD_02.MATRIZ_FISCAL,CLIENTES_ATACADO.TIPO AS TIPO_CLIENTE,CLIENTES_ATACADO.REGIAO, W_FATURAMENTO_PROD_02.UF FROM  W_FATURAMENTO_PROD_02 LEFT JOIN CLIENTES_ATACADO CLIENTES_ATACADO ON CLIENTES_ATACADO.CLIENTE_ATACADO=W_FATURAMENTO_PROD_02.NOME_CLIFOR  JOIN PRODUTOS ON W_FATURAMENTO_PROD_02.PRODUTO = PRODUTOS.PRODUTO JOIN FILIAIS ON FILIAIS.FILIAL=W_FATURAMENTO_PROD_02.FILIAL 
WHERE W_FATURAMENTO_PROD_02.EMISSAO >= '20150501' AND W_FATURAMENTO_PROD_02.EMISSAO <= '20161231' --and (PRODUTOS.GRUPO_PRODUTO != 'MERCHANDISING')




SELECT MES=MONTH(W_FATURAMENTO_06.EMISSAO),ANO=YEAR(W_FATURAMENTO_06.EMISSAO),W_FATURAMENTO_06.FILIAL, W_FATURAMENTO_06.SERIE_NF, W_FATURAMENTO_06.NF_SAIDA, W_FATURAMENTO_06.NOME_CLIFOR, 
W_FATURAMENTO_06.NATUREZA_SAIDA,W_FATURAMENTO_06.EMISSAO, W_FATURAMENTO_06.QTDE_TOTAL, W_FATURAMENTO_06.TABELA_FILHA, 
W_FATURAMENTO_06.MPADRAO_VALOR_SUB_ITENS, W_FATURAMENTO_06.MPADRAO_VALOR_TOTAL
FROM W_FATURAMENTO_06   JOIN FILIAIS ON FILIAIS.FILIAL =  W_FATURAMENTO_06.FILIAL  
LEFT JOIN CLIENTES_VAREJO CV ON CV.CODIGO_CLIENTE = W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO 
WHERE W_FATURAMENTO_06.EMISSAO >= '20140101' AND W_FATURAMENTO_06.EMISSAO <= '20161231'  and 
( cod_transacao = 'FATURAMENTO_022' or cod_transacao = 'FATURAMENTO_030' or cod_transacao = 'FATURAMENTO_036') 
AND W_FATURAMENTO_06.TIPO_OPERACAO = 'V'



--- Tempo Médio da OP em Processo
SELECT ORDEM_PRODUCAO_006.ORDEM_PRODUCAO,ORDEM_PRODUCAO_006.NF_SAIDA AS NF_SAIDA_F006,ORDEM_PRODUCAO_006.EMISSAO AS EMISSAO_F006, ORDEM_PRODUCAO_009.NF_SAIDA AS NF_SAIDA_F009,ORDEM_PRODUCAO_009.EMISSAO AS EMISSAO_F009, DIAS=DATEDIFF(DAY,ORDEM_PRODUCAO_006.EMISSAO,ORDEM_PRODUCAO_009.EMISSAO)
FROM PRODUCAO_ORDEM

JOIN (
SELECT D.EMISSAO,C.NF_SAIDA,C.SERIE_NF,A.ORDEM_PRODUCAO,QTDE_O=SUM(A.QTDE_O)
FROM PRODUCAO_OS_TAREFAS A 
JOIN PRODUCAO_TAREFAS B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.TAREFA=A.TAREFA
JOIN (SELECT * FROM PRODUCAO_ORDEM_SERVICO WHERE NF_SAIDA <>'') C ON C.ORDEM_SERVICO=A.ORDEM_SERVICO
JOIN FATURAMENTO D ON D.NF_SAIDA=C.NF_SAIDA AND D.SERIE_NF=C.SERIE_NF
WHERE B.FASE_PRODUCAO='006' --AND B.ORDEM_PRODUCAO='84671'
GROUP BY D.EMISSAO,C.NF_SAIDA,C.SERIE_NF,A.ORDEM_PRODUCAO
) AS ORDEM_PRODUCAO_006 ON ORDEM_PRODUCAO_006.ORDEM_PRODUCAO=PRODUCAO_ORDEM.ORDEM_PRODUCAO

JOIN (
SELECT D.EMISSAO,C.NF_SAIDA,C.SERIE_NF,A.ORDEM_PRODUCAO,QTDE_O=SUM(A.QTDE_O)
FROM PRODUCAO_OS_TAREFAS A 
JOIN PRODUCAO_TAREFAS B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.TAREFA=A.TAREFA
JOIN (SELECT * FROM PRODUCAO_ORDEM_SERVICO WHERE NF_SAIDA <>'') C ON C.ORDEM_SERVICO=A.ORDEM_SERVICO
JOIN FATURAMENTO D ON D.NF_SAIDA=C.NF_SAIDA AND D.SERIE_NF=C.SERIE_NF
WHERE B.FASE_PRODUCAO='009' --AND B.ORDEM_PRODUCAO='84671'
GROUP BY D.EMISSAO,C.NF_SAIDA,C.SERIE_NF,A.ORDEM_PRODUCAO
) AS ORDEM_PRODUCAO_009 ON ORDEM_PRODUCAO_009.ORDEM_PRODUCAO=PRODUCAO_ORDEM.ORDEM_PRODUCAO

WHERE YEAR(ORDEM_PRODUCAO_006.EMISSAO) = 2015 -- AND PRODUCAO_ORDEM.ORDEM_PRODUCAO='84671' 

ORDER BY ORDEM_PRODUCAO



--- Indicadores para a KPMG
--- QTDE DE OP MENSAL 2014
SELECT ANO=YEAR(EMISSAO),MES=MONTH(EMISSAO),QTDE=COUNT(ORDEM_PRODUCAO) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2015
GROUP BY YEAR(EMISSAO),MONTH(EMISSAO)


--- PRAZO MEDIO DE PRODUÇÃO
SELECT AVG(DATEDIFF(DAY,EMISSAO,ENCERRAMENTO)) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2014 AND ENCERRAMENTO IS NOT NULL

SELECT ORDEM_PRODUCAO,AVG(DATEDIFF(DAY,EMISSAO,ENCERRAMENTO)) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2014 AND ENCERRAMENTO IS NOT NULL
GROUP BY ORDEM_PRODUCAO


--- PRAZO MEDIO DO RETORNO DAS OFICINAS
SELECT AVG(DATEDIFF(DAY,RETORNO.INICIO_REAL,RETORNO.ENCERRAMENTO)) FROM (
SELECT DISTINCT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS1.FASE_PRODUCAO1,PRODUCAO_TAREFAS1.INICIO_REAL,PRODUCAO_TAREFAS2.FASE_PRODUCAO2,PRODUCAO_TAREFAS2.ENCERRAMENTO FROM PRODUCAO_TAREFAS
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO1=FASE_PRODUCAO,INICIO_REAL FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='006' AND YEAR(INICIO_REAL)=2014) AS PRODUCAO_TAREFAS1 ON PRODUCAO_TAREFAS1.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO2=FASE_PRODUCAO,ENCERRAMENTO FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='009' AND YEAR(ENCERRAMENTO)=2014) AS PRODUCAO_TAREFAS2 ON PRODUCAO_TAREFAS2.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2014 ) AS RETORNO


SELECT DISTINCT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS1.FASE_PRODUCAO,PRODUCAO_TAREFAS1.INICIO_REAL,PRODUCAO_TAREFAS2.FASE_PRODUCAO,PRODUCAO_TAREFAS2.ENCERRAMENTO FROM PRODUCAO_TAREFAS
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,INICIO_REAL FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='006' AND YEAR(INICIO_REAL)=2014) AS PRODUCAO_TAREFAS1 ON PRODUCAO_TAREFAS1.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,ENCERRAMENTO FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='009' AND YEAR(ENCERRAMENTO)=2014) AS PRODUCAO_TAREFAS2 ON PRODUCAO_TAREFAS2.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2014