SELECT 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO.DATA, 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO,
QTDE_O =SUM(PRODUCAO_OS_TAREFAS.QTDE_O) 
FROM PRODUCAO_ORDEM_SERVICO
JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

JOIN (
 
SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, dbo.PRODUCAO_SETOR PRODUCAO_SETOR, dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, dbo.PRODUTOS PRODUTOS, dbo.PRODUCAO_ORDEM
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

) AS COSTURA
ON PRODUCAO_OS_TAREFAS.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='009' AND PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV=1 AND YEAR(PRODUCAO_ORDEM_SERVICO.DATA)>=2014 AND PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO 

GROUP BY 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO.DATA, 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO





