DECLARE @RECURSO_PRODUTIVO CHAR(10)
SET @RECURSO_PRODUTIVO='GCA06'

SELECT 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR=ISNULL(QTDE_OPERADOR,0),  
MINUTOS_DISPONIVEIS=ISNULL(MINUTOS_DISPONIVEIS,0),  
DIA,
BH=CASE 
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'
THEN '1ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:16' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'
THEN '2ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:31' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'
THEN '3ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:46' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'
THEN '4ª'
END,
META_BH = ISNULL(CASE 
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'
THEN CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))/4)
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:16' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'),0))/3) 
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:31' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'),0))/2) 
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:46' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'),0))/1) 
END,0),
REALIZADO_BH = ISNULL(CASE 
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'
THEN ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'),0)
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:16' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'
THEN ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:16',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'),0)
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:31' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'
THEN ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:31',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'),0)
WHEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:46' AND SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'
THEN ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:46',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'),0)
END,0),
REALIZADO_TOTAL=ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'),0),
META=ISNULL(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))),0),
EFICIENCIA=ISNULL(CONVERT(NUMERIC(6,0),(ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59'),0)/CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))))*100),0)
FROM W_SAW_META_DIA
WHERE RECURSO_PRODUTIVO = @RECURSO_PRODUTIVO
GROUP BY
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA  

---- BI HORARIA TOTAL
DECLARE @RECURSO_PRODUTIVO CHAR(10)
SET @RECURSO_PRODUTIVO='GCA06'

SELECT 
FILIAL,
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA_PRODUCAO,
META_DIA,
BH,
QTDE_BH=SUM(QTDE_O), 
META_BH=CASE 
WHEN BH = '1ª'
THEN CONVERT(NUMERIC(6,0),META_DIA/4)
WHEN BH = '2ª'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'),0))/3) 
WHEN BH = '3ª'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'),0))/2) 
WHEN BH = '4ª'
THEN CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'),0))/1) 
END,
EFIC_BH=
CASE 
WHEN BH = '1ª'
THEN ISNULL(SUM(QTDE_O)/CONVERT(NUMERIC(6,0),META_DIA/4)*100,0)
WHEN BH = '2ª'
THEN ISNULL(SUM(QTDE_O)/CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'),0))/3)*100,0) 
WHEN BH = '3ª'
THEN ISNULL(SUM(QTDE_O)/CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'),0))/2)*100,0) 
WHEN BH = '4ª'
THEN ISNULL(SUM(QTDE_O)/CONVERT(NUMERIC(6,0),(CONVERT(NUMERIC(6,0),META_DIA) - ISNULL(DBO.QTDE_BI_HORARIA(@RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'),0))/1)*100,0) 
END
FROM W_BI_HORARIA 
WHERE RECURSO_PRODUTIVO=@RECURSO_PRODUTIVO AND DATA_PRODUCAO='20150909'
GROUP BY 
FILIAL,
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA_PRODUCAO,
META_DIA,
BH
ORDER BY
FILIAL,
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA_PRODUCAO,
META_DIA,
BH





---- VISÃO PARA MONTAR A BI-HORARIA
alter VIEW DBO.W_BI_HORARIA 
AS 

SELECT 

PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO,
PRODUCAO_ORDEM_SERVICO.SETOR_PRODUCAO,
PRODUCAO_ORDEM_SERVICO.DATA,
PRODUCAO_ORDEM_SERVICO.FILIAL,
PRODUCAO_ORDEM_SERVICO.NF_SAIDA,
PRODUCAO_ORDEM_SERVICO.SERIE_NF,
PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV,
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
LDR_METAS_OFICINA_GRUPO_NOVA.DESC_RECURSO,
LDR_METAS_OFICINA_GRUPO_NOVA.DATA_PRODUCAO,
LDR_METAS_OFICINA_GRUPO_NOVA.META_DIA,
LDR_METAS_OFICINA_GRUPO_NOVA.META_MES,
LDR_METAS_OFICINA_GRUPO_NOVA.QTDE_OPERADOR,
LDR_METAS_OFICINA_GRUPO_NOVA.MINUTOS_DISPONIVEIS,
LDR_METAS_OFICINA_GRUPO_NOVA.HORA_EXTRA,
LDR_METAS_OFICINA_GRUPO_NOVA.RETIRAR_DIA,
LDR_METAS_OFICINA_GRUPO_NOVA.QTDE_FALTAS,
LDR_METAS_OFICINA_GRUPO_NOVA.QTDE_FERIAS,

BH=CASE 
WHEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '00:00' AND SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '09:15'
THEN '1ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '09:16' AND SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '11:30'
THEN '2ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '11:31' AND SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '14:45'
THEN '3ª'
WHEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,16) BETWEEN SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '14:46' AND SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,11) + '23:59'
THEN '4ª'
END,

PRODUCAO_OS_TAREFAS.QTDE_O

FROM PRODUCAO_ORDEM_SERVICO WITH (NOLOCK)
JOIN PRODUCAO_OS_TAREFAS WITH (NOLOCK) ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

JOIN (
 
SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

) AS COSTURA
ON PRODUCAO_OS_TAREFAS.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

JOIN PRODUCAO_ORDEM_SERVICO_HORARIA WITH (NOLOCK) ON PRODUCAO_ORDEM_SERVICO_HORARIA.ORDEM_SERVICO = PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

JOIN LDR_METAS_OFICINA_GRUPO_NOVA WITH (NOLOCK) ON LDR_METAS_OFICINA_GRUPO_NOVA.DESC_SETOR_PRODUCAO = COSTURA.DESC_SETOR_PRODUCAO AND LDR_METAS_OFICINA_GRUPO_NOVA.DESC_RECURSO = COSTURA.DESC_RECURSO AND LDR_METAS_OFICINA_GRUPO_NOVA.DATA_PRODUCAO=PRODUCAO_ORDEM_SERVICO.DATA

WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='009' 
AND PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV=1 


--and LDR_METAS_OFICINA_GRUPO_NOVA.META_DIA IS NOT NULL 


SELECT * FROM W_BI_HORARIA
WHERE DATA='20150909'
