update B
set B.CONTA_CONTABIL = '1120101'
from CTB_LANCAMENTO A,CTB_LANCAMENTO_ITEM B  
where A.LANCAMENTO=B.LANCAMENTO AND B.LX_TIPO_LANCAMENTO = 'BTR' 
and (B.CONTA_CONTABIL = '112010401' or B.CONTA_CONTABIL = '112010402') 
AND YEAR(A.DATA_LANCAMENTO)>=2015


SELECT * FROM CTB_BORDERO
where LANCAMENTO='360614'


select CTB_LANCAMENTO.DATA_LANCAMENTO, CTB_BORDERO.*,* from CTB_LANCAMENTO_ITEM
JOIN CTB_BORDERO ON CTB_BORDERO.LANCAMENTO=CTB_LANCAMENTO_ITEM.LANCAMENTO 
JOIN CTB_LANCAMENTO ON CTB_LANCAMENTO.LANCAMENTO=CTB_LANCAMENTO_ITEM.LANCAMENTO
where LX_TIPO_LANCAMENTO='SCC' AND CONTA_CONTABIL='1120101' AND LAYOUT='0094' --AND YEAR(CTB_LANCAMENTO.DATA_LANCAMENTO)=2015
ORDER BY CTB_LANCAMENTO.DATA_LANCAMENTO DESC


update A
SET A.CONTA_CONTABIL='1110204'
from CTB_LANCAMENTO_ITEM A
JOIN CTB_BORDERO B ON B.LANCAMENTO=A.LANCAMENTO 
where LX_TIPO_LANCAMENTO='SCC' AND CONTA_CONTABIL='1120101' AND LAYOUT='0094'


SELECT * FROM PRODUCAO_TAREFAS


