USE DESENV

SELECT * FROM CTB_BORDERO
WHERE LAYOUT='0155' AND LANCAMENTO='314730'


SELECT * FROM CTB_BORDERO_LOG
WHERE LANCAMENTO='314730'


SELECT * FROM CTB_A_RECEBER_FATURA
WHERE LANCAMENTO='242868' AND ITEM='1'


----------------------


SELECT * FROM CTB_BORDERO_LOG
WHERE LANCAMENTO='314730'

BEGIN TRANSACTION

rollback


UPDATE A
SET A.LX_TIPO_DOCUMENTO='34'
FROM CTB_A_RECEBER_FATURA A
JOIN CTB_BORDERO_LOG B ON B.LANCAMENTO_MOV=A.LANCAMENTO AND B.ITEM_MOV=A.ITEM
WHERE B.LANCAMENTO='314730' 


UPDATE A
SET A.LX_TIPO_DOCUMENTO='34'
SELECT B.*,A.LX_TIPO_DOCUMENTO FROM CTB_A_RECEBER_FATURA A
JOIN CTB_BORDERO_LOG B ON B.LANCAMENTO_MOV=A.LANCAMENTO AND B.ITEM_MOV=A.ITEM
WHERE B.LANCAMENTO='314730' 

