SELECT A.*, B.*,ISNULL(B.VALOR_ORIGINAL,0)+ISNULL(A.VALOR_MULTA_GERADA,0)+ISNULL(A.VALOR_JUROS_GERADO,0)-ISNULL(A.DESCONTO_CONCEDIDO,0)-ISNULL(A.VALOR_MOV,0)-ISNULL(A.VALOR_MULTA_PAGA,0)-ISNULL(A.VALOR_JUROS_PAGO,0) 
FROM CTB_A_RECEBER_MOV A
JOIN CTB_A_RECEBER_PARCELA B ON B.LANCAMENTO=A.LANCAMENTO_MOV AND B.ITEM=A.ITEM_MOV
WHERE B.LANCAMENTO='318475'


SELECT * from CTB_A_RECEBER_PARCELA
WHERE LANCAMENTO='318475'

--- VIEW E TRIGGER PARA ALTERAR
--- W_CTB_A_RECEBER_PARCELA_SALDO
--- ISNULL(A.VALOR_ORIGINAL,0)+ISNULL(SUM(B.VALOR_MULTA_GERADA),0)+ISNULL(SUM(B.VALOR_JUROS_GERADO),0)-ISNULL(SUM(B.DESCONTO_CONCEDIDO),0)-ISNULL(SUM(B.VALOR_MOV),0)-ISNULL(SUM(B.VALOR_MULTA_PAGA),0)-ISNULL(SUM(B.VALOR_JUROS_PAGO),0)+ISNULL(SUM(B.DESCONTO_EFETIVADO),0)


UPDATE B
SET B.VALOR_A_RECEBER=(B.VALOR_ORIGINAL_PADRAO - (A.VALOR_MOV_PADRAO+A.DESCONTO_EFETIVADO_PADRAO))
FROM CTB_A_RECEBER_MOV A
JOIN CTB_A_RECEBER_PARCELA B ON B.LANCAMENTO=A.LANCAMENTO_MOV AND B.ITEM=A.ITEM_MOV
WHERE B.LANCAMENTO='318475'


SELECT * FROM CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='329133'


SELECT * FROM CTB_A_RECEBER_MOV
WHERE LANCAMENTO='329133'


LX_CADE_COLUNA SALDO_PRINCIPAL_DEVIDO

SELECT * FROM W_CTB_A_RECEBER_PARCELA
WHERE LANCAMENTO='318475'

