SELECT PRODUCAO_TAREFAS.TAREFA,PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,
POS.ORDEM_SERVICO,
QTDE_O =sum(PT.QTDE_O) 
FROM PRODUCAO_OS_TAREFAS PT WITH (NOLOCK)
JOIN PRODUCAO_OS_ANTERIOR PA WITH (NOLOCK) ON PA.ORDEM_SERVICO=PT.ORDEM_SERVICO AND PA.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO AND PA.PRODUTO = PT.PRODUTO  AND PA.COR_PRODUTO = PT.COR_PRODUTO  AND PA.TAREFA = PT.TAREFA
JOIN PRODUCAO_ORDEM_SERVICO POS WITH (NOLOCK) ON POS.ORDEM_SERVICO=PT.ORDEM_SERVICO
JOIN PRODUCAO_TAREFAS WITH (NOLOCK) on PRODUCAO_TAREFAS.TAREFA=PA.TAREFA_ANTERIOR
JOIN (
 
SELECT PRODUCAO_TAREFAS.TAREFA,PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO IN ('60','61')
AND PRODUCAO_ORDEM.ORDEM_PRODUCAO='162527'


) AS COSTURA
ON PT.PRODUTO=COSTURA.PRODUTO AND PT.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO 
and PRODUCAO_TAREFAS.TAREFA=costura.TAREFA

JOIN PRODUCAO_ORDEM_SERVICO_HORARIA WITH (NOLOCK) ON PRODUCAO_ORDEM_SERVICO_HORARIA.ORDEM_SERVICO = POS.ORDEM_SERVICO

WHERE PRODUCAO_TAREFAS.FASE_PRODUCAO IN ('60','61') AND COSTURA.RECURSO_PRODUTIVO = RTRIM('GFI05') --AND SUBSTRING(CONVERT(VARCHAR(40),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21),1,16) BETWEEN LTRIM(RTRIM('20151022 11:31')) AND LTRIM(RTRIM('20151022 14:45')) 

GROUP BY  PRODUCAO_TAREFAS.TAREFA,POS.ORDEM_SERVICO,PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA ,CONVERT(VARCHAR(10),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21)
--ORDER BY PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA ,CONVERT(VARCHAR(10),PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,21)


---select * from W_PRODUCAO_ORDEM_HIST_OS


exec sp_executesql N'
/* lx008030spk  CursorAdapter: cur_v_producao_recurso_creditos_01(Alias: v_producao_recurso_creditos_01)  */
SELECT PRODUCAO_OS_ANTERIOR.TAREFA,PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR,  PRODUCAO_ORDEM_SERVICO.DATA, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,   
PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO,   PRODUCAO_ORDEM_SERVICO.NF_ENTRADA, PRODUCAO_TAREFAS.FASE_PRODUCAO,   
PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO,  
PRODUCAO_OS_ANTERIOR.PRODUTO, PRODUTOS.DESC_PRODUTO,   PRODUCAO_OS_ANTERIOR.COR_PRODUTO,  ISNULL(PRODUCAO_TAREFAS_SALDO.QTDE_S,0)AS QTDE_S, QTDE_A_PRODUZIR,   
QTDE_A, QTDE_R,   PRODUCAO_OS_ANTERIOR.CUSTO_EFETIVO, PRODUCAO_OS_ANTERIOR.DESCONTO_APLICADO,  PRODUCAO_OS_ANTERIOR.VALOR_CREDITADO,  
PRODUCAO_ORDEM_SERVICO.CONFERIDO_POR,  PRODUCAO_ORDEM_SERVICO.FILIAL, PRODUCAO_TAREFAS.INICIO_PREVISTO,   PRODUCAO_TAREFAS.INICIO_REAL, 
PRODUCAO_TAREFAS.FIM_PREVISTO,  PRODUCAO_TAREFAS.ENCERRAMENTO, PRODUCAO_ORDEM_SERVICO.OBSERVACAO,  PRODUCAO_TAREFAS.OBS AS OBS_TAREFA, 
PRODUCAO_TAREFAS.FIM_ATUALIZADO,  PRODUCAO_RECURSOS.TIPO_RECURSO,  PRODUCAO_RECURSOS.RECURSO_PROPRIO,  PRODUCAO_RECURSOS.NOME_CLIFOR, PRODUCAO_TAREFAS.CUSTO_TAREFA 
AS CUSTO_PREVISTO,   PRODUCAO_TAREFAS.CUSTO_TAREFA*PRODUCAO_OS_ANTERIOR.QTDE_A AS VALOR_PREVISTO,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO, LINHA,GRIFFE,MODELAGEM,TABELA_OPERACOES,TIPO_PRODUTO, FILIAIS.EMPRESA,PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO  , PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV  
FROM FX_PRODUCAO_RECURSO_CREDITOS() AS PRODUCAO_OS_ANTERIOR  
INNER JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO  AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO  AND PRODUCAO_OS_TAREFAS.PRODUTO = PRODUCAO_OS_ANTERIOR.PRODUTO  AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUCAO_OS_ANTERIOR.COR_PRODUTO  AND PRODUCAO_OS_TAREFAS.TAREFA = PRODUCAO_OS_ANTERIOR.TAREFA  
INNER JOIN PRODUCAO_TAREFAS ON  PRODUCAO_OS_ANTERIOR.TAREFA_AUX = PRODUCAO_TAREFAS.TAREFA  
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
LEFT  JOIN PRODUCAO_TAREFAS_SALDO ON PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO  AND PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO   AND PRODUCAO_OS_ANTERIOR.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO   AND PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA   AND PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR = PRODUCAO_TAREFAS_SALDO.TAREFA   
INNER JOIN PRODUTOS ON PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUTOS.PRODUTO   
INNER JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO   
INNER JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  AND  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO   
INNER JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO   
INNER JOIN FILIAIS ON PRODUCAO_ORDEM_SERVICO.FILIAL  = FILIAIS.FILIAL   
WHERE PRODUCAO_ORDEM_SERVICO.DATA = @P1 AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = @P2',N'@P1 datetime,@P2 varchar(5)','2015-10-22 00:00:00','GFI01'

exec sp_executesql N'
/* lx008030spk  CursorAdapter: cur_v_producao_recurso_creditos_01(Alias: v_producao_recurso_creditos_01)  */
SELECT PRODUCAO_OS_ANTERIOR.TAREFA,PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR,  PRODUCAO_ORDEM_SERVICO.DATA, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,   
PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO,   PRODUCAO_ORDEM_SERVICO.NF_ENTRADA, PRODUCAO_TAREFAS.FASE_PRODUCAO,   
PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO,  
PRODUCAO_OS_ANTERIOR.PRODUTO, PRODUTOS.DESC_PRODUTO,   PRODUCAO_OS_ANTERIOR.COR_PRODUTO,  ISNULL(PRODUCAO_TAREFAS_SALDO.QTDE_S,0)AS QTDE_S, QTDE_A_PRODUZIR,   
QTDE_A, QTDE_R,   PRODUCAO_OS_ANTERIOR.CUSTO_EFETIVO, PRODUCAO_OS_ANTERIOR.DESCONTO_APLICADO,  PRODUCAO_OS_ANTERIOR.VALOR_CREDITADO,  
PRODUCAO_ORDEM_SERVICO.CONFERIDO_POR,  PRODUCAO_ORDEM_SERVICO.FILIAL, PRODUCAO_TAREFAS.INICIO_PREVISTO,   PRODUCAO_TAREFAS.INICIO_REAL, 
PRODUCAO_TAREFAS.FIM_PREVISTO,  PRODUCAO_TAREFAS.ENCERRAMENTO, PRODUCAO_ORDEM_SERVICO.OBSERVACAO,  PRODUCAO_TAREFAS.OBS AS OBS_TAREFA, 
PRODUCAO_TAREFAS.FIM_ATUALIZADO,  PRODUCAO_RECURSOS.TIPO_RECURSO,  PRODUCAO_RECURSOS.RECURSO_PROPRIO,  PRODUCAO_RECURSOS.NOME_CLIFOR, PRODUCAO_TAREFAS.CUSTO_TAREFA 
AS CUSTO_PREVISTO,   PRODUCAO_TAREFAS.CUSTO_TAREFA*PRODUCAO_OS_ANTERIOR.QTDE_A AS VALOR_PREVISTO,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO, LINHA,GRIFFE,MODELAGEM,TABELA_OPERACOES,TIPO_PRODUTO, FILIAIS.EMPRESA,PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO  , PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV  
FROM FX_PRODUCAO_RECURSO_CREDITOS() AS PRODUCAO_OS_ANTERIOR  
INNER JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO  AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO  AND PRODUCAO_OS_TAREFAS.PRODUTO = PRODUCAO_OS_ANTERIOR.PRODUTO  AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUCAO_OS_ANTERIOR.COR_PRODUTO  AND PRODUCAO_OS_TAREFAS.TAREFA = PRODUCAO_OS_ANTERIOR.TAREFA  
INNER JOIN PRODUCAO_TAREFAS ON  PRODUCAO_OS_ANTERIOR.TAREFA_AUX = PRODUCAO_TAREFAS.TAREFA  
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
LEFT  JOIN PRODUCAO_TAREFAS_SALDO ON PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO  AND PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO   AND PRODUCAO_OS_ANTERIOR.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO   AND PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA   AND PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR = PRODUCAO_TAREFAS_SALDO.TAREFA   
INNER JOIN PRODUTOS ON PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUTOS.PRODUTO   
INNER JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO   
INNER JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  AND  PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO   
INNER JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO   
INNER JOIN FILIAIS ON PRODUCAO_ORDEM_SERVICO.FILIAL  = FILIAIS.FILIAL   
WHERE PRODUCAO_ORDEM_SERVICO.DATA = @P1 AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = @P2',N'@P1 datetime,@P2 varchar(5)','2015-10-22 00:00:00','GFI05'


SELECT * FROM FX_PRODUCAO_RECURSO_CREDITOS() AS PRODUCAO_OS_ANTERIOR 
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
INNER JOIN PRODUCAO_TAREFAS ON  PRODUCAO_OS_ANTERIOR.TAREFA_AUX = PRODUCAO_TAREFAS.TAREFA  
WHERE PRODUCAO_ORDEM_SERVICO.DATA = '2015-10-22 00:00:00' AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = 'GFI05'

---- é isso aqui
select * from W_SAW_PRODUCAO_OS_ANTERIOR
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = W_SAW_PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
INNER JOIN PRODUCAO_TAREFAS ON  W_SAW_PRODUCAO_OS_ANTERIOR.tarefa_anterior1 = PRODUCAO_TAREFAS.TAREFA  
WHERE PRODUCAO_ORDEM_SERVICO.DATA = '2015-09-30 00:00:00' AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = 'GFI05' and W_SAW_PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO='162527'


select * from W_SAW_PRODUCAO_OS_ANTERIOR
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = W_SAW_PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
INNER JOIN PRODUCAO_TAREFAS ON  W_SAW_PRODUCAO_OS_ANTERIOR.tarefa_anterior1 = PRODUCAO_TAREFAS.TAREFA  
--INNER JOIN PRODUCAO_ORDEM_SERVICO_HORARIA ON PRODUCAO_ORDEM_SERVICO_HORARIA.ORDEM_SERVICO = W_SAW_PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO
WHERE PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA = '2015-10-09 00:00:00' AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = 'GFI01' and W_SAW_PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO='162527'


SELECT * FROM W_SAW_PRODUCAO_OS_ANTERIOR

CREATE VIEW W_SAW_PRODUCAO_OS_ANTERIOR AS 
SELECT Producao_os_anterior.ORDEM_SERVICO,Producao_os_anterior.tarefa_anterior as tarefa_anterior1, 
Producao_os_anterior.tarefa,
Producao_os_anterior.tarefa_anterior as tarefa_anterior2, 
Producao_os_anterior.ORDEM_PRODUCAO,  
Producao_os_anterior.PRODUTO, 
Producao_os_anterior.COR_PRODUTO,  
case when producao_os_tarefas.INDICADOR_TIPO_MOV = 5 then 0  else Producao_os_anterior.QTDE_A end as qtde_a, 
case when producao_os_tarefas.INDICADOR_TIPO_MOV = 5 then Producao_os_anterior.QTDE_A else 0 end as qtde_r,  
Producao_os_anterior.CUSTO_EFETIVO, 
Producao_os_anterior.DESCONTO_APLICADO,  
Producao_os_anterior.VALOR_CREDITADO
FROM Producao_os_anterior 
inner join producao_os_tarefas on producao_os_tarefas.ORDEM_SERVICO = Producao_os_anterior.ORDEM_SERVICO 
and producao_os_tarefas.ORDEM_producao = Producao_os_anterior.ORDEM_PRODUCAO
and producao_os_tarefas.produto = Producao_os_anterior.produto 
and producao_os_tarefas.cor_produto = Producao_os_anterior.cor_produto 
and producao_os_tarefas.tarefa = Producao_os_anterior.tarefa 
WHERE producao_os_tarefas.INDICADOR_TIPO_MOV<>5 AND producao_os_anterior.qtde_a<>0 
union all
SELECT Producao_os_anterior.ORDEM_SERVICO,Producao_os_anterior.TAREFA,
Producao_os_anterior.tarefa,
Producao_os_anterior.tarefa_anterior,  
Producao_os_anterior.ORDEM_PRODUCAO,  
Producao_os_anterior.PRODUTO, 
Producao_os_anterior.COR_PRODUTO,  
case when producao_os_tarefas.INDICADOR_TIPO_MOV = 5 then 0  else Producao_os_anterior.QTDE_A end as qtde_a, 
case when producao_os_tarefas.INDICADOR_TIPO_MOV = 5 then Producao_os_anterior.QTDE_A else 0 end as qtde_r,  
Producao_os_anterior.CUSTO_EFETIVO, 
Producao_os_anterior.DESCONTO_APLICADO,  
Producao_os_anterior.VALOR_CREDITADO
FROM Producao_os_anterior 
inner join producao_os_tarefas on producao_os_tarefas.ORDEM_SERVICO = Producao_os_anterior.ORDEM_SERVICO 
and producao_os_tarefas.ORDEM_producao = Producao_os_anterior.ORDEM_PRODUCAO
and producao_os_tarefas.produto = Producao_os_anterior.produto 
and producao_os_tarefas.cor_produto = Producao_os_anterior.cor_produto 
and producao_os_tarefas.tarefa = Producao_os_anterior.tarefa 
WHERE producao_os_tarefas.INDICADOR_TIPO_MOV=5 AND producao_os_anterior.qtde_a<>0  


SELECT PRODUCAO_RECURSOS.RECURSO_PRODUTIVO,*,
QTDE1=DBO.QTDE_BI_HORARIA_NOVA(PRODUCAO_RECURSOS.RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '00:00',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:15'),
QTDE2=DBO.QTDE_BI_HORARIA_NOVA(PRODUCAO_RECURSOS.RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '09:16',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:30'),
QTDE3=DBO.QTDE_BI_HORARIA_NOVA(PRODUCAO_RECURSOS.RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '11:31',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:45'),
QTDE4=DBO.QTDE_BI_HORARIA_NOVA(PRODUCAO_RECURSOS.RECURSO_PRODUTIVO,SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '14:46',SUBSTRING(CONVERT(VARCHAR(40),GETDATE(),21),1,11) + '23:59')
FROM DR_METAS_OFICINA_GRUPO with (nolock) 
JOIN PRODUCAO_RECURSOS ON  PRODUCAO_RECURSOS.DESC_RECURSO=DR_METAS_OFICINA_GRUPO.DESC_RECURSO
WHERE  DR_METAS_OFICINA_GRUPO.DESC_SETOR_PRODUCAO='OFICINA FIORUCCI' AND DR_METAS_OFICINA_GRUPO.DESC_RECURSO like 'GRUPO FIORUCCI%' AND 
CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)


