SELECT ENDERECO,NUMERO FROM CADASTRO_CLI_FOR
WHERE NUMERO IS NULL

SELECT DISTINCT CADASTRO_CLI_FOR.CLIFOR,CADASTRO_CLI_FOR.NOME_CLIFOR,ENDERECO,NUMERO FROM VENDAS
JOIN CADASTRO_CLI_FOR ON VENDAS.CLIENTE_ATACADO=CADASTRO_CLI_FOR.NOME_CLIFOR
WHERE EMISSAO >='20120101' AND EMISSAO <= '20131231' AND CADASTRO_CLI_FOR.NUMERO IS NULL 
ORDER BY CADASTRO_CLI_FOR.CLIFOR



