select a.CLIFOR,NOME_CLIFOR,RAZAO_SOCIAL,ENDERECO,NUMERO from CADASTRO_CLI_FOR a
join CLIENTES_ATACADO b on b.CLIENTE_ATACADO=a.NOME_CLIFOR
where b.CLIENTE_ATACADO in (select CLIENTE_ATACADO from VENDAS WHERE EMISSAO between '20110101' and '20131231') and a.NUMERO is null