SELECT C.TIPO, A.CLIFOR,
A.RAZAO_SOCIAL,
A.CGC_CPF,
A.ENDERECO,
A.CIDADE,
A.UF,
A.CADASTRAMENTO,
DATA_ULTIMA_COMPRA=(SELECT MAX(EMISSAO) FROM VENDAS B WHERE B.CLIENTE_ATACADO=A.NOME_CLIFOR) 
FROM CADASTRO_CLI_FOR A
JOIN CLIENTES_ATACADO C ON C.CLIENTE_ATACADO=A.NOME_CLIFOR
WHERE A.INATIVO=0 AND C.INATIVO=0 AND A.PJ_PF='1'