SELECT B.EMAIL,B.RAZAO_SOCIAL, A.* FROM CLIENTES_ATACADO A
JOIN CADASTRO_CLI_FOR B ON B.COD_CLIFOR=A.COD_CLIENTE
WHERE A.FILIAL='DR VAREJO' AND A.TIPO='VAREJO' AND A.INATIVO=0 AND B.EMAIL IS NOT NULL AND 
EXISTS(SELECT DISTINCT CLIENTE_ATACADO FROM VENDAS WHERE CLIENTE_ATACADO=A.CLIENTE_ATACADO AND EMISSAO BETWEEN '20150101' AND '20171231')
