SP_HELP CADASTRO_CLI_FOR


ALTER TABLE CADASTRO_CLI_FOR
  ALTER COLUMN EMAIL VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS

  
--Verificando as collations da tabela
SELECT TABLE_NAME, COLUMN_NAME, COLLATION_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTOS'


SELECT 'ALTER TABLE ' + TABLE_NAME + ' ALTER COLUMN ' + COLUMN_NAME + ' ' + DATA_TYPE + '(' + isnull(CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(4)) + ')','falta')
--CASE
--WHEN DATA_TYPE IN ('Text','NText') THEN DATA_TYPE
--WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN DATA_TYPE + '(MAX)'
--ELSE DATA_TYPE + '(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(4)) + ')'
--END + ' COLLATE '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTOS'




-- Declarando uma variável para armazenar a collation do banco
DECLARE @Collation VARCHAR(30)
SET @Collation = CAST((SELECT DATABASEPROPERTYEX('C:\BANCO\DTBSFV.MDF','Collation')) AS VARCHAR(30))

--Gerando as instruções de ALTER
--Gerar o ALTER <Tabela> e ALTER COLUMN <Coluna>
SELECT 'ALTER TABLE ' + TABLE_NAME + ' ALTER COLUMN ' + COLUMN_NAME + ' ' +

--Definir a sintaxe do tipo de dados
CASE
WHEN DATA_TYPE IN ('Text','NText') THEN DATA_TYPE
WHEN CHARACTER_MAXIMUM_LENGTH = -1 THEN DATA_TYPE + '(MAX)'
ELSE DATA_TYPE + '(' + CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR(4)) + ')'

--Especificar a collation
END + ' COLLATE ' + @Collation + ' ' +

--Especificar a nulabilidade
CASE IS_NULLABLE WHEN 'YES' THEN 'NULL' ELSE 'NOT NULL' END
FROM Information_Schema.Columns

--Filtrar apenas as colunas textuais
--WHERE COLLATION_NAME IS NOT NULL





ALTER TABLE TBL_LOG_IMPORT_EXPORT ALTER COLUMN ACAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE TBL_LOG_IMPORT_EXPORT ALTER COLUMN TIPO_ACAO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE TBL_SFV_CONFIG ALTER COLUMN LETRA_INSTALACAO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LCF_LX_PAIS ALTER COLUMN DESC_PAIS varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LCF_LX_PAIS ALTER COLUMN COD_PAIS_BC varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE LCF_LX_PAIS ALTER COLUMN COD_PAIS_SISCOMEX char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN PEDIDO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN DESC_PRODUTO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN COR_PRODUTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN GRADE varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_PRODUTO_CONFIRMADOS ALTER COLUMN CODIGO_BARRA nvarchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE LCF_LX_UF ALTER COLUMN UF char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LCF_LX_UF ALTER COLUMN DESC_UF varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LCF_LX_MUNICIPIO ALTER COLUMN DESC_MUNICIPIO varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE LCF_LX_MUNICIPIO ALTER COLUMN COD_MUNICIPIO_IBGE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN REPRESENTANTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN GERENTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN REGIAO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN TIPO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN CGC_CPF varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN CLIFOR char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN SEQUENCIAL char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN COD_REPRESENTANTE char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN CONTA_CONTABIL char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE REPRESENTANTES ALTER COLUMN CTB_CONTA_CONTABIL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN NOME_CLIFOR varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CARTEIRA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN BANCO char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CONTA_CONTABIL char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CLIFOR char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CGC_CPF varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN RAZAO_SOCIAL varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN RG_IE varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CEP varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENDERECO varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COMPLEMENTO varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN NUMERO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN BAIRRO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CIDADE varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN UF char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN TELEFONE1 varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN PAIS varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN DDI char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN TELEFONE2 varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN FAX varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN DDD1 char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN RAMAL1 char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN RAMAL2 char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN DDD2 char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_ENDERECO varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_NUMERO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_COMPLEMENTO varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_CIDADE varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_BAIRRO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN DDDFAX char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_UF char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_CEP varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_TELEFONE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_ENDERECO varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_NUMERO varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_COMPLEMENTO varchar(60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_CIDADE varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_UF char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_BAIRRO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_CEP varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_TELEFONE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_DDD char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CONTATO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_CGC varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_IE varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_DDD char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_CGC varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_IE varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CC_AGENCIA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CC_CONTA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CC_NOME_AGENCIA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN REF_ANTERIOR char(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN EMAIL varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN STATUS_ENVIO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_PAIS varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_PAIS varchar(35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_DDI char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_DDI char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN OBS_DE_FATURAMENTO text COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN MESES_SEM_VENCIMENTO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN DATA_FIXA_PGTO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN PASSWEB varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN REPORT_FATURA char(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CODIGO_CHAVE char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COD_CLIFOR char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ENTREGA_RAZAO_SOCIAL varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COBRANCA_RAZAO_SOCIAL varchar(90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CTB_CONTA_CONTABIL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CODIGO_CONTATO char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN IM varchar(14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN IM_ENTREGA varchar(14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN IM_COBRANCA varchar(14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN ID_CLIENTE_SERVIDOR char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CADASTRO_CLI_FOR char(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN INSCRICAO_SUFRAMA char(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CNAE varchar(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN EMAIL_NFE varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COD_MUNICIPIO_IBGE varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COD_MUNICIPIO_IBGE_ENTREGA varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN COD_MUNICIPIO_IBGE_COBRANCA varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CADASTRO_CLI_FOR ALTER COLUMN CODIGO_SPC char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTE_REPRE ALTER COLUMN REPRESENTANTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTE_REPRE ALTER COLUMN CLIENTE_ATACADO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REGIOES_VENDA ALTER COLUMN REGIAO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE REGIOES_VENDA ALTER COLUMN PESO_DA_REGIAO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE REGIOES_VENDA ALTER COLUMN MACRO_REGIAO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE REGIOES_VENDA ALTER COLUMN COD_REGIAO_VENDA char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_PERIODOS_ENTREGAS ALTER COLUMN NUMERO_ENTREGA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_PERIODOS_ENTREGAS ALTER COLUMN PERIODO_PCP varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE FORMA_PGTO ALTER COLUMN CONDICAO_PGTO char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE FORMA_PGTO ALTER COLUMN DESC_COND_PGTO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE FORMA_PGTO ALTER COLUMN TIPO_CONDICAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE FORMA_PGTO ALTER COLUMN COND_PGTO_ENTRADA char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_BARRA ALTER COLUMN CODIGO_BARRA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_BARRA ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_BARRA ALTER COLUMN COR_PRODUTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_BARRA ALTER COLUMN GRADE varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_BARRA ALTER COLUMN NOME_CLIFOR varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_PRECOS ALTER COLUMN CODIGO_TAB_PRECO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_PRECOS ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN PEDIDO_EXTERNO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TIPO_DO_DIGITADOR varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN MOEDA char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN CODIGO_TAB_PRECO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TIPO char(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN CONDICAO_PGTO char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN COLECAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN CLIENTE_ATACADO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN REPRESENTANTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN PEDIDO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN PEDIDO_CLIENTE varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN OBS text COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN FILIAL varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TRANSPORTADORA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN GERENTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN APROVACAO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN APROVADO_POR varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN CONFERIDO_POR varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN STATUS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TIPO_FRETE char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TABELA_FILHA char(18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TIPO_CAIXA char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN PERIODO_PCP varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN NOME_CLIFOR_ENTREGA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN OBS_TRANSPORTE varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN NUMERO_ENTREGA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN TRANSP_REDESPACHO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN PEDIDO_EXTERNO_ORIGEM varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN FILIAL_DIGITACAO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN NATUREZA_SAIDA char(7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN CRITICA varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN ENVIAR varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE ALTER COLUMN SEXO_TIPO char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN COR_PRODUTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN PEDIDO_EXTERNO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN PACKS varchar(24) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN NUMERO_ENTREGA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN STATUS_VENDA_ATUAL char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN ITEM_PEDIDO char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN CODIGO_LOCAL_ENTREGA char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN TIPO_CAIXA char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN DESC_VENDA_CLIENTE varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS_LOTE_PROD ALTER COLUMN ID_MODIFICACAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE LDR_PRODUTO_COR_ENTREGA_FUTURA ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LDR_PRODUTO_COR_ENTREGA_FUTURA ALTER COLUMN COR_PRODUTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE LDR_PRODUTO_COR_ENTREGA_FUTURA ALTER COLUMN PERIODO_PCP varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE LDR_PRODUTO_COR_ENTREGA_FUTURA ALTER COLUMN NUMERO_ENTREGA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE COTA_LIMITE_PERFAT ALTER COLUMN NUMERO_ENTREGA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE COTA_LIMITE_PERFAT ALTER COLUMN PERIODO_PCP varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN GRADE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN QUEBRA_1 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN QUEBRA_2 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN QUEBRA_3 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN QUEBRA_4 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN QUEBRA_5 char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_1 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_2 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_3 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_4 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_5 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_6 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_7 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_8 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_9 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_10 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_11 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_12 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_13 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_14 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_15 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_16 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_17 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_18 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_19 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_20 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_21 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_22 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_23 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_24 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_25 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_26 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_27 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_28 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_29 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_30 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_31 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_32 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_33 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_34 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_35 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_36 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_37 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_38 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_39 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_40 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_41 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_42 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_43 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_44 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_45 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_46 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_47 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN TAMANHO_48 varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN GRADE_BASE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS_TAMANHOS ALTER COLUMN GRADE_CODIGO char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN CODIGO_PRECO char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN MATERIAL char(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN PERIODO_PCP varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN TABELA_OPERACOES varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CLASSIF_FISCAL char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN TIPO_PRODUTO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN TABELA_MEDIDAS varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN DESC_PRODUTO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN GRUPO_PRODUTO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN SUBGRUPO_PRODUTO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN COLECAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN GRADE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN DESC_PROD_NF varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN LINHA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN GRIFFE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN CARTELA char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN UNIDADE char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN REFER_FABRICANTE char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN MODELAGEM char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN FABRICANTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN PONTEIRO_PRECO_TAM char(48) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN TRIBUT_ICMS char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN TRIBUT_ORIGEM char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTOS ALTER COLUMN ESTILISTA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN MODELISTA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN MODELO char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN REDE_LOJAS char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN STATUS_PRODUTO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN OBS text COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN COMPOSICAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN RESTRICAO_LAVAGEM char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN ORCAMENTO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CLIENTE_DO_PRODUTO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CONTA_CONTABIL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN VERSAO_FICHA char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN COD_FLUXO_PRODUTO char(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CONTA_CONTABIL_COMPRA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CONTA_CONTABIL_VENDA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CONTA_CONTABIL_DEV_COMPRA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN CONTA_CONTABIL_DEV_VENDA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN DIAS_COMPRA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN COD_CATEGORIA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTOS ALTER COLUMN COD_SUBCATEGORIA char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN PRODUTO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN COR_PRODUTO char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN DESC_COR_PRODUTO varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN STATUS_VENDA_ATUAL char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN COR_FABRICANTE char(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN TIPO_LAVAGEM_TINTURARIA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN COR char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN MATERIAL char(11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN COR_MATERIAL char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN ETIQUETA char(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN VARIANTE_TAMANHO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN COMPOSICAO char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN CLASSIF_FISCAL char(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE PRODUTO_CORES ALTER COLUMN TRIBUT_ORIGEM char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE SFV_MATERIAL_PROMOCIONAL ALTER COLUMN DESCRICAO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CLIENTE_ATACADO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN COD_CLIENTE char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CONDICAO_PGTO char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN REGIAO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN MATRIZ_CLIENTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN FILIAL varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN PONTUALIDADE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN TRANSPORTADORA varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CONCEITO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN TIPO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN TIPO_BLOQUEIO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CGC_CPF varchar(19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CLIFOR char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN OBS text COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN MOEDA char(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CODIGO_TAB_PRECO char(2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN SEGURO_NUMERO_CONTRATO varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN SEGURO_NUMERO_CLIENTE varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CONTA_CONTABIL char(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN MESES_SEM_VENCIMENTO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CONTA_CONTABIL_ANTECIPACAO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN TRANSP_REDESPACHO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CONTA_CONTABIL_VENDAS_TIPO varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN TRANSPORTADORA2 varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN CTB_CONTA_CONTABIL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE CLIENTES_ATACADO ALTER COLUMN INDICADOR_VENDA char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS ALTER COLUMN PEDIDO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS ALTER COLUMN PEDIDO_EXTERNO char(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
ALTER TABLE VENDAS ALTER COLUMN CLIENTE_ATACADO varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
ALTER TABLE VENDAS ALTER COLUMN REPRESENTANTE varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
