-- Consulta anterior Lenta
select C.GRIFFE, C.GRUPO_PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,a.nf_saida,A.EMISSAO,
A.PRECO, 
A.MPADRAO_PRECO, 
A.DESCONTO_ITEM, 
A.MPADRAO_DESCONTO_ITEM, 
A.VALOR, 
A.MPADRAO_VALOR, 
A.VALOR_PRODUCAO, 
A.MPADRAO_VALOR_PRODUCAO, 
A.DIF_PRODUCAO, 
A.MPADRAO_DIF_PRODUCAO, 
A.VALOR_LIQUIDO, 
A.MPADRAO_VALOR_LIQUIDO, 
A.DIF_PRODUCAO_LIQUIDO, 
A.MPADRAO_DIF_PRODUCAO_LIQUIDO,
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE,
VALOR_LIQUIDO_TOTAL=((A.VALOR_PRODUCAO*A.CAMBIO_NA_DATA) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR_PRODUCAO*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN A.VALOR_PRODUCAO*ABS(B.DESCONTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
WHERE B.EMISSAO >='20160101' AND B.EMISSAO <= '20161231' AND A.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'


-- Nova consulta otimizada
SELECT GRIFFE, GRUPO_PRODUTO,GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO, 
A.DESCONTO_ITEM, 
A.VALOR, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE,
VALOR_LIQUIDO_TOTAL=((A.VALOR*A.CAMBIO_NA_DATA) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN A.VALOR*ABS(B.DESCONTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN FATURAMENTO B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20160101' AND B.EMISSAO <= '20161231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
and b.NF_SAIDA='0072868' and b.SERIE_NF='55'


--- adicionado union para trazer as NFe de consumiveis
SELECT GRIFFE, GRUPO_PRODUTO, A.PRODUTO, GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO, 
A.DESCONTO_ITEM, 
A.VALOR, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE,
VALOR_LIQUIDO_TOTAL=(round((A.VALOR*A.CAMBIO_NA_DATA),4) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN round((A.VALOR*B.VALOR_IMPOSTO_AGREGAR),4)/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN round((A.VALOR*ABS(B.DESCONTO)),4)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN FATURAMENTO B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
union all
SELECT GRIFFE, GRUPO_PRODUTO,PRODUTO,GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO_UNITARIO, 
A.DESCONTO_ITEM, 
A.PRECO_UNITARIO_ORIGINAL, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE_ITEM,
VALOR_LIQUIDO_TOTAL=((A.VALOR_ITEM) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN round((A.VALOR_ITEM*B.VALOR_IMPOSTO_AGREGAR),4)/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) > 0 THEN round((A.PRECO_UNITARIO_ORIGINAL*ABS(B.DESCONTO)),4)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO B WITH (NOLOCK)
JOIN FATURAMENTO_ITEM A WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.CODIGO_ITEM
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
and not exists(select * from faturamento_prod where NF_SAIDA=b.NF_SAIDA and SERIE_NF=b.SERIE_NF)


--- adicionado union para trazer as NFe de consumiveis
SELECT F.DESC_COLECAO, GRIFFE, GRUPO_PRODUTO,B.GERENTE,B.REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,B.EMISSAO,
A.PRECO, 
A.DESCONTO_ITEM, 
A.VALOR, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE,
VALOR_LIQUIDO_TOTAL=((A.VALOR*A.CAMBIO_NA_DATA) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN A.VALOR*ABS(B.DESCONTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN FATURAMENTO B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
LEFT JOIN VENDAS E WITH (NOLOCK) ON E.PEDIDO=A.PEDIDO
LEFT JOIN COLECOES F WITH (NOLOCK) ON F.COLECAO=E.COLECAO
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
union all
SELECT '' AS DESC_COLECAO,GRIFFE, GRUPO_PRODUTO,GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO_UNITARIO, 
A.DESCONTO_ITEM, 
A.PRECO_UNITARIO_ORIGINAL, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE_ITEM,
VALOR_LIQUIDO_TOTAL=((A.VALOR_ITEM) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR_ITEM*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN A.PRECO_UNITARIO_ORIGINAL*ABS(B.DESCONTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO B WITH (NOLOCK)
JOIN FATURAMENTO_ITEM A WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.CODIGO_ITEM
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
and not exists(select * from faturamento_prod where NF_SAIDA=b.NF_SAIDA and SERIE_NF=b.SERIE_NF)


--- SÓ PARA INFORMAÇÕES A LUCIANA
SELECT W_FATURAMENTO_06.FILIAL, W_FATURAMENTO_06.SERIE_NF, W_FATURAMENTO_06.NF_SAIDA, W_FATURAMENTO_06.TIPO_FRETE, W_FATURAMENTO_06.TIPO_FATURAMENTO, W_FATURAMENTO_06.NOME_CLIFOR, W_FATURAMENTO_06.CONDICAO_PGTO, W_FATURAMENTO_06.NATUREZA_SAIDA, 
W_FATURAMENTO_06.TRANSPORTADORA, W_FATURAMENTO_06.TRANSP_REDESPACHO, W_FATURAMENTO_06.COD_TRANSACAO, W_FATURAMENTO_06.EMISSAO, W_FATURAMENTO_06.DATA_SAIDA, W_FATURAMENTO_06.FRETE, W_FATURAMENTO_06.SEGURO, W_FATURAMENTO_06.DESCONTO, W_FATURAMENTO_06.DESCONTO_SEFAZ, 
W_FATURAMENTO_06.DESCONTO_COND_PGTO, W_FATURAMENTO_06.ENCARGO, W_FATURAMENTO_06.VALOR_TOTAL, W_FATURAMENTO_06.QTDE_TOTAL, W_FATURAMENTO_06.NF_FATURA, W_FATURAMENTO_06.FATURA, W_FATURAMENTO_06.NOTA_IMPRESSA, W_FATURAMENTO_06.ACERTO_CONTAS_P_R, 
W_FATURAMENTO_06.TABELA_FILHA, W_FATURAMENTO_06.OBS, W_FATURAMENTO_06.PESO_LIQUIDO, W_FATURAMENTO_06.PESO_BRUTO, W_FATURAMENTO_06.VOLUMES, W_FATURAMENTO_06.TIPO_VOLUME, W_FATURAMENTO_06.CONFERIDO, W_FATURAMENTO_06.CONFERIDO_POR, W_FATURAMENTO_06.ENTREGA_CIF, W_FATURAMENTO_06.NOTA_CANCELADA, W_FATURAMENTO_06.DEVOLUCAO, W_FATURAMENTO_06.REPRESENTANTE, W_FATURAMENTO_06.COMISSAO, W_FATURAMENTO_06.PORCENTAGEM_ACERTO, W_FATURAMENTO_06.GERENTE, W_FATURAMENTO_06.COMISSAO_GERENTE, W_FATURAMENTO_06.DESCONTO_SOBRE_1, W_FATURAMENTO_06.DESCONTO_SOBRE_2, W_FATURAMENTO_06.DESCONTO_SOBRE_3, W_FATURAMENTO_06.DESCONTO_SOBRE_4,   W_FATURAMENTO_06.DESCONTO_BRUTO, W_FATURAMENTO_06.DIF_DESCONTO_BRUTO,   W_FATURAMENTO_06.DESCONTO_BRUTO_1, W_FATURAMENTO_06.DESCONTO_BRUTO_2, W_FATURAMENTO_06.DESCONTO_BRUTO_3, W_FATURAMENTO_06.DESCONTO_BRUTO_4, W_FATURAMENTO_06.CAMBIO_NA_DATA, W_FATURAMENTO_06.COBRAR_MOEDA_PADRAO, W_FATURAMENTO_06.DATA_FATURAMENTO_RELATIVO, W_FATURAMENTO_06.NOME_CLIFOR_ENTREGA, W_FATURAMENTO_06.TABELA_PRECO_FRETE, W_FATURAMENTO_06.VALOR_FRETE, W_FATURAMENTO_06.OBS_TRANSPORTE, W_FATURAMENTO_06.EMPRESA, W_FATURAMENTO_06.CTB_LANCAMENTO, W_FATURAMENTO_06.CTB_ITEM, W_FATURAMENTO_06.NUMERO_CONFERENCIA, W_FATURAMENTO_06.FATURA_FILIAL, W_FATURAMENTO_06.FATURA_NUMERO, W_FATURAMENTO_06.FATURA_SERIE, W_FATURAMENTO_06.AGRUPAMENTO_ITENS, W_FATURAMENTO_06.MPADRAO_DESCONTO, W_FATURAMENTO_06.MPADRAO_DESCONTO_SEFAZ, W_FATURAMENTO_06.MPADRAO_ENCARGO, W_FATURAMENTO_06.MPADRAO_VALOR_SUB_ITENS, W_FATURAMENTO_06.MPADRAO_VALOR_TOTAL, W_FATURAMENTO_06.MPADRAO_SEGURO, W_FATURAMENTO_06.MPADRAO_FRETE, W_FATURAMENTO_06.VALOR_SUB_ITENS, W_FATURAMENTO_06.COMISSAO_VALOR, W_FATURAMENTO_06.COMISSAO_VALOR_GERENTE, W_FATURAMENTO_06.MPADRAO_DESCONTO_COND_PGTO, W_FATURAMENTO_06.MULTI_DESCONTO_ACUMULAR, W_FATURAMENTO_06.PORC_DESCONTO, W_FATURAMENTO_06.PORC_DESCONTO_SEFAZ, W_FATURAMENTO_06.PORC_DESCONTO_COND_PGTO, W_FATURAMENTO_06.PORC_ENCARGO, W_FATURAMENTO_06.PORC_DESCONTO_BRUTO, W_FATURAMENTO_06.PORC_DESCONTO_DIGITADO, W_FATURAMENTO_06.MOEDA, W_FATURAMENTO_06.VALOR_IMPOSTO_AGREGAR, W_FATURAMENTO_06.MPADRAO_IMPOSTO_AGREGAR, W_FATURAMENTO_06.INDICA_CONSUMIDOR_FINAL, W_FATURAMENTO_06.RATEIO_CENTRO_CUSTO, W_FATURAMENTO_06.RATEIO_FILIAL, W_FATURAMENTO_06.TIMESTAMP, W_FATURAMENTO_06.DESC_NATUREZA, 
W_FATURAMENTO_06.CTB_TIPO_OPERACAO, W_FATURAMENTO_06.LX_TIPO_LANCAMENTO, W_FATURAMENTO_06.DESC_TIPO_LANCAMENTO, W_FATURAMENTO_06.DESC_TIPO_OPERACAO, W_FATURAMENTO_06.TIPO_OPERACAO, W_FATURAMENTO_06.DESC_GRUPO_TIPO_OPERACAO, W_FATURAMENTO_06.DESCRICAO_SERIE, 
W_FATURAMENTO_06.ANO_FISCAL, W_FATURAMENTO_06.COD_FILIAL, W_FATURAMENTO_06.CLIFOR, W_FATURAMENTO_06.INDICADOR_FISCAL_TERCEIRO, W_FATURAMENTO_06.PJ_PF, W_FATURAMENTO_06.DESCRICAO_FISCAL_TERCEIRO, W_FATURAMENTO_06.NOME_MOEDA, W_FATURAMENTO_06.DESC_COND_PGTO, 
W_FATURAMENTO_06.DESCRICAO_TIPO, W_FATURAMENTO_06.DESC_RATEIO_FILIAL, W_FATURAMENTO_06.DESC_RATEIO_CENTRO_CUSTO, W_FATURAMENTO_06.ICMS, W_FATURAMENTO_06.ICMS_BASE, W_FATURAMENTO_06.IPI, W_FATURAMENTO_06.IPI_BASE, W_FATURAMENTO_06.IRRF, W_FATURAMENTO_06.IRRF_BASE, 
W_FATURAMENTO_06.INSS, W_FATURAMENTO_06.INSS_BASE, W_FATURAMENTO_06.PIS, W_FATURAMENTO_06.PIS_BASE, W_FATURAMENTO_06.COFINS, W_FATURAMENTO_06.COFINS_BASE, W_FATURAMENTO_06.I_IMPORT, W_FATURAMENTO_06.I_IMPORT_BASE, W_FATURAMENTO_06.IVA, W_FATURAMENTO_06.IVA_BASE, 
W_FATURAMENTO_06.RECARGO, W_FATURAMENTO_06.RECARGO_BASE, W_FATURAMENTO_06.IRPF, W_FATURAMENTO_06.IRPF_BASE, W_FATURAMENTO_06.DICMS, W_FATURAMENTO_06.DICMS_BASE, W_FATURAMENTO_06.ICMS_ST, W_FATURAMENTO_06.ICMS_ST_BASE, W_FATURAMENTO_06.ICMS_STR, 
W_FATURAMENTO_06.ICMS_STR_BASE, W_FATURAMENTO_06.ISS, W_FATURAMENTO_06.ISS_BASE, W_FATURAMENTO_06.IVA_IC, W_FATURAMENTO_06.IVA_IC_BASE, W_FATURAMENTO_06.PC_CSL, W_FATURAMENTO_06.PC_CSL_BASE, W_FATURAMENTO_06.PIS_R, W_FATURAMENTO_06.PIS_R_BASE, W_FATURAMENTO_06.COFINS_R, 
W_FATURAMENTO_06.COFINS_R_BASE, W_FATURAMENTO_06.CSLL_R, W_FATURAMENTO_06.CSLL_R_BASE, W_FATURAMENTO_06.IRRF_R, W_FATURAMENTO_06.IRRF_R_BASE, W_FATURAMENTO_06.INSS_R, W_FATURAMENTO_06.INSS_R_BASE, W_FATURAMENTO_06.ISS_R, W_FATURAMENTO_06.ISS_R_BASE, 
W_FATURAMENTO_06.VALOR_PRODUCAO, W_FATURAMENTO_06.DIF_PRODUCAO, W_FATURAMENTO_06.MPADRAO_DIF_PRODUCAO, W_FATURAMENTO_06.MPADRAO_VALOR_PRODUCAO, W_FATURAMENTO_06.PIS_S, W_FATURAMENTO_06.PIS_S_BASE, W_FATURAMENTO_06.COFINS_S, W_FATURAMENTO_06.COFINS_S_BASE, W_FATURAMENTO_06.CSLL_S, W_FATURAMENTO_06.CSLL_S_BASE, W_FATURAMENTO_06.RTEIVA, W_FATURAMENTO_06.RTEIVA_BASE, W_FATURAMENTO_06.RTEIVA_R, W_FATURAMENTO_06.RTEIVA_R_BASE, W_FATURAMENTO_06.ICA, W_FATURAMENTO_06.ICA_BASE, W_FATURAMENTO_06.RTEICA, W_FATURAMENTO_06.RTEICA_BASE, W_FATURAMENTO_06.RTEFTE, W_FATURAMENTO_06.RTEFTE_BASE, W_FATURAMENTO_06.RTEFTE_R, W_FATURAMENTO_06.RTEFTE_R_BASE, W_FATURAMENTO_06.ICMS_ZF, W_FATURAMENTO_06.ICMS_ZF_BASE, W_FATURAMENTO_06.PIS_ZF, W_FATURAMENTO_06.PIS_ZF_BASE, W_FATURAMENTO_06.COFINS_ZF, W_FATURAMENTO_06.COFINS_ZF_BASE, W_FATURAMENTO_06.DICMS_R, W_FATURAMENTO_06.DICMS_R_BASE, W_FATURAMENTO_06.FECP, W_FATURAMENTO_06.FECP_BASE, W_FATURAMENTO_06.SIMPLES_E, W_FATURAMENTO_06.SIMPLES_E_BASE, W_FATURAMENTO_06.SIMPLES_F, W_FATURAMENTO_06.SIMPLES_F_BASE, W_FATURAMENTO_06.CP_INSS, W_FATURAMENTO_06.CP_INSS_BASE,     CAST((CASE WHEN ISNULL(W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO, '''') = '''' THEN 0 ELSE 1 END ) AS BIT) AS INDICA_CLIENTE_VAREJO, CV.CLIENTE_VAREJO, W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO       
FROM W_FATURAMENTO_06   
JOIN FILIAIS ON FILIAIS.FILIAL =  W_FATURAMENTO_06.FILIAL  
LEFT JOIN CLIENTES_VAREJO CV ON CV.CODIGO_CLIENTE = W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO 
WHERE W_FATURAMENTO_06.EMISSAO >= '20170101' AND W_FATURAMENTO_06.EMISSAO <= '20171231'   and ( cod_transacao = 'FATURAMENTO_022' or cod_transacao = 'FATURAMENTO_030' or cod_transacao = 'FATURAMENTO_036') AND W_FATURAMENTO_06.FILIAL = 'DR VAREJO' 
AND W_FATURAMENTO_06.TIPO_OPERACAO = 'V'
UNION ALL
SELECT W_FATURAMENTO_06.FILIAL, W_FATURAMENTO_06.SERIE_NF, W_FATURAMENTO_06.NF_SAIDA, W_FATURAMENTO_06.TIPO_FRETE, W_FATURAMENTO_06.TIPO_FATURAMENTO, W_FATURAMENTO_06.NOME_CLIFOR, W_FATURAMENTO_06.CONDICAO_PGTO, W_FATURAMENTO_06.NATUREZA_SAIDA, 
W_FATURAMENTO_06.TRANSPORTADORA, W_FATURAMENTO_06.TRANSP_REDESPACHO, W_FATURAMENTO_06.COD_TRANSACAO, W_FATURAMENTO_06.EMISSAO, W_FATURAMENTO_06.DATA_SAIDA, W_FATURAMENTO_06.FRETE, W_FATURAMENTO_06.SEGURO, W_FATURAMENTO_06.DESCONTO, W_FATURAMENTO_06.DESCONTO_SEFAZ, 
W_FATURAMENTO_06.DESCONTO_COND_PGTO, W_FATURAMENTO_06.ENCARGO, W_FATURAMENTO_06.VALOR_TOTAL, W_FATURAMENTO_06.QTDE_TOTAL, W_FATURAMENTO_06.NF_FATURA, W_FATURAMENTO_06.FATURA, W_FATURAMENTO_06.NOTA_IMPRESSA, W_FATURAMENTO_06.ACERTO_CONTAS_P_R, W_FATURAMENTO_06.TABELA_FILHA, W_FATURAMENTO_06.OBS, W_FATURAMENTO_06.PESO_LIQUIDO, W_FATURAMENTO_06.PESO_BRUTO, W_FATURAMENTO_06.VOLUMES, W_FATURAMENTO_06.TIPO_VOLUME, W_FATURAMENTO_06.CONFERIDO, W_FATURAMENTO_06.CONFERIDO_POR, W_FATURAMENTO_06.ENTREGA_CIF, W_FATURAMENTO_06.NOTA_CANCELADA, W_FATURAMENTO_06.DEVOLUCAO, W_FATURAMENTO_06.REPRESENTANTE, W_FATURAMENTO_06.COMISSAO, W_FATURAMENTO_06.PORCENTAGEM_ACERTO, W_FATURAMENTO_06.GERENTE, W_FATURAMENTO_06.COMISSAO_GERENTE, W_FATURAMENTO_06.DESCONTO_SOBRE_1, W_FATURAMENTO_06.DESCONTO_SOBRE_2, W_FATURAMENTO_06.DESCONTO_SOBRE_3, W_FATURAMENTO_06.DESCONTO_SOBRE_4,   W_FATURAMENTO_06.DESCONTO_BRUTO, W_FATURAMENTO_06.DIF_DESCONTO_BRUTO,   W_FATURAMENTO_06.DESCONTO_BRUTO_1, W_FATURAMENTO_06.DESCONTO_BRUTO_2, W_FATURAMENTO_06.DESCONTO_BRUTO_3, W_FATURAMENTO_06.DESCONTO_BRUTO_4, W_FATURAMENTO_06.CAMBIO_NA_DATA, W_FATURAMENTO_06.COBRAR_MOEDA_PADRAO, W_FATURAMENTO_06.DATA_FATURAMENTO_RELATIVO, W_FATURAMENTO_06.NOME_CLIFOR_ENTREGA, W_FATURAMENTO_06.TABELA_PRECO_FRETE, W_FATURAMENTO_06.VALOR_FRETE, W_FATURAMENTO_06.OBS_TRANSPORTE, W_FATURAMENTO_06.EMPRESA, W_FATURAMENTO_06.CTB_LANCAMENTO, W_FATURAMENTO_06.CTB_ITEM, W_FATURAMENTO_06.NUMERO_CONFERENCIA, W_FATURAMENTO_06.FATURA_FILIAL, W_FATURAMENTO_06.FATURA_NUMERO, W_FATURAMENTO_06.FATURA_SERIE, W_FATURAMENTO_06.AGRUPAMENTO_ITENS, W_FATURAMENTO_06.MPADRAO_DESCONTO, W_FATURAMENTO_06.MPADRAO_DESCONTO_SEFAZ, W_FATURAMENTO_06.MPADRAO_ENCARGO, W_FATURAMENTO_06.MPADRAO_VALOR_SUB_ITENS, W_FATURAMENTO_06.MPADRAO_VALOR_TOTAL, W_FATURAMENTO_06.MPADRAO_SEGURO, W_FATURAMENTO_06.MPADRAO_FRETE, W_FATURAMENTO_06.VALOR_SUB_ITENS, W_FATURAMENTO_06.COMISSAO_VALOR, W_FATURAMENTO_06.COMISSAO_VALOR_GERENTE, W_FATURAMENTO_06.MPADRAO_DESCONTO_COND_PGTO, W_FATURAMENTO_06.MULTI_DESCONTO_ACUMULAR, W_FATURAMENTO_06.PORC_DESCONTO, W_FATURAMENTO_06.PORC_DESCONTO_SEFAZ, W_FATURAMENTO_06.PORC_DESCONTO_COND_PGTO, W_FATURAMENTO_06.PORC_ENCARGO, W_FATURAMENTO_06.PORC_DESCONTO_BRUTO, W_FATURAMENTO_06.PORC_DESCONTO_DIGITADO, W_FATURAMENTO_06.MOEDA, 
W_FATURAMENTO_06.VALOR_IMPOSTO_AGREGAR, W_FATURAMENTO_06.MPADRAO_IMPOSTO_AGREGAR, W_FATURAMENTO_06.INDICA_CONSUMIDOR_FINAL, W_FATURAMENTO_06.RATEIO_CENTRO_CUSTO, W_FATURAMENTO_06.RATEIO_FILIAL, W_FATURAMENTO_06.TIMESTAMP, W_FATURAMENTO_06.DESC_NATUREZA, 
W_FATURAMENTO_06.CTB_TIPO_OPERACAO, W_FATURAMENTO_06.LX_TIPO_LANCAMENTO, W_FATURAMENTO_06.DESC_TIPO_LANCAMENTO, W_FATURAMENTO_06.DESC_TIPO_OPERACAO, W_FATURAMENTO_06.TIPO_OPERACAO, W_FATURAMENTO_06.DESC_GRUPO_TIPO_OPERACAO, W_FATURAMENTO_06.DESCRICAO_SERIE, 
W_FATURAMENTO_06.ANO_FISCAL, W_FATURAMENTO_06.COD_FILIAL, W_FATURAMENTO_06.CLIFOR, W_FATURAMENTO_06.INDICADOR_FISCAL_TERCEIRO, W_FATURAMENTO_06.PJ_PF, W_FATURAMENTO_06.DESCRICAO_FISCAL_TERCEIRO, W_FATURAMENTO_06.NOME_MOEDA, W_FATURAMENTO_06.DESC_COND_PGTO, 
W_FATURAMENTO_06.DESCRICAO_TIPO, W_FATURAMENTO_06.DESC_RATEIO_FILIAL, W_FATURAMENTO_06.DESC_RATEIO_CENTRO_CUSTO, W_FATURAMENTO_06.ICMS, W_FATURAMENTO_06.ICMS_BASE, W_FATURAMENTO_06.IPI, W_FATURAMENTO_06.IPI_BASE, W_FATURAMENTO_06.IRRF, W_FATURAMENTO_06.IRRF_BASE, 
W_FATURAMENTO_06.INSS, W_FATURAMENTO_06.INSS_BASE, W_FATURAMENTO_06.PIS, W_FATURAMENTO_06.PIS_BASE, W_FATURAMENTO_06.COFINS, W_FATURAMENTO_06.COFINS_BASE, W_FATURAMENTO_06.I_IMPORT, W_FATURAMENTO_06.I_IMPORT_BASE, W_FATURAMENTO_06.IVA, W_FATURAMENTO_06.IVA_BASE, 
W_FATURAMENTO_06.RECARGO, W_FATURAMENTO_06.RECARGO_BASE, W_FATURAMENTO_06.IRPF, W_FATURAMENTO_06.IRPF_BASE, W_FATURAMENTO_06.DICMS, W_FATURAMENTO_06.DICMS_BASE, W_FATURAMENTO_06.ICMS_ST, W_FATURAMENTO_06.ICMS_ST_BASE, W_FATURAMENTO_06.ICMS_STR, 
W_FATURAMENTO_06.ICMS_STR_BASE, W_FATURAMENTO_06.ISS, W_FATURAMENTO_06.ISS_BASE, W_FATURAMENTO_06.IVA_IC, W_FATURAMENTO_06.IVA_IC_BASE, W_FATURAMENTO_06.PC_CSL, W_FATURAMENTO_06.PC_CSL_BASE, W_FATURAMENTO_06.PIS_R, W_FATURAMENTO_06.PIS_R_BASE, W_FATURAMENTO_06.COFINS_R, 
W_FATURAMENTO_06.COFINS_R_BASE, W_FATURAMENTO_06.CSLL_R, W_FATURAMENTO_06.CSLL_R_BASE, W_FATURAMENTO_06.IRRF_R, W_FATURAMENTO_06.IRRF_R_BASE, W_FATURAMENTO_06.INSS_R, W_FATURAMENTO_06.INSS_R_BASE, W_FATURAMENTO_06.ISS_R, W_FATURAMENTO_06.ISS_R_BASE, W_FATURAMENTO_06.VALOR_PRODUCAO, W_FATURAMENTO_06.DIF_PRODUCAO, W_FATURAMENTO_06.MPADRAO_DIF_PRODUCAO, W_FATURAMENTO_06.MPADRAO_VALOR_PRODUCAO, W_FATURAMENTO_06.PIS_S, W_FATURAMENTO_06.PIS_S_BASE, W_FATURAMENTO_06.COFINS_S, W_FATURAMENTO_06.COFINS_S_BASE, W_FATURAMENTO_06.CSLL_S, W_FATURAMENTO_06.CSLL_S_BASE, W_FATURAMENTO_06.RTEIVA, W_FATURAMENTO_06.RTEIVA_BASE, W_FATURAMENTO_06.RTEIVA_R, W_FATURAMENTO_06.RTEIVA_R_BASE, W_FATURAMENTO_06.ICA, W_FATURAMENTO_06.ICA_BASE, W_FATURAMENTO_06.RTEICA, W_FATURAMENTO_06.RTEICA_BASE, W_FATURAMENTO_06.RTEFTE, W_FATURAMENTO_06.RTEFTE_BASE, W_FATURAMENTO_06.RTEFTE_R, W_FATURAMENTO_06.RTEFTE_R_BASE, W_FATURAMENTO_06.ICMS_ZF, W_FATURAMENTO_06.ICMS_ZF_BASE, W_FATURAMENTO_06.PIS_ZF, W_FATURAMENTO_06.PIS_ZF_BASE, W_FATURAMENTO_06.COFINS_ZF, W_FATURAMENTO_06.COFINS_ZF_BASE, W_FATURAMENTO_06.DICMS_R, W_FATURAMENTO_06.DICMS_R_BASE, W_FATURAMENTO_06.FECP, W_FATURAMENTO_06.FECP_BASE, W_FATURAMENTO_06.SIMPLES_E, W_FATURAMENTO_06.SIMPLES_E_BASE, W_FATURAMENTO_06.SIMPLES_F, W_FATURAMENTO_06.SIMPLES_F_BASE, W_FATURAMENTO_06.CP_INSS, W_FATURAMENTO_06.CP_INSS_BASE,     CAST((CASE WHEN ISNULL(W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO, '''') = '''' THEN 0 ELSE 1 END ) AS BIT) AS INDICA_CLIENTE_VAREJO, CV.CLIENTE_VAREJO, W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO       
FROM W_FATURAMENTO_06   
JOIN FILIAIS ON FILIAIS.FILIAL =  W_FATURAMENTO_06.FILIAL  
LEFT JOIN CLIENTES_VAREJO CV ON CV.CODIGO_CLIENTE = W_FATURAMENTO_06.CODIGO_CLIENTE_VAREJO 
WHERE W_FATURAMENTO_06.EMISSAO >= '20170101' AND W_FATURAMENTO_06.EMISSAO <= '20171231'    and ( cod_transacao = 'FATURAMENTO_023' ) AND W_FATURAMENTO_06.FILIAL = 'DR VAREJO' AND W_FATURAMENTO_06.TIPO_OPERACAO = 'V'



SELECT sum(A.QTDE), sum(((A.VALOR*A.CAMBIO_NA_DATA) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO) >0 THEN A.VALOR*ABS(B.DESCONTO)/B.VALOR_SUB_ITENS ELSE 0 END )  ))
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN FATURAMENTO B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20160101' AND B.EMISSAO <= '20161231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
and b.NF_SAIDA='0072868' and b.SERIE_NF='55'



SELECT "Faturamento" AS Tipo, dbo_FATURAMENTO.CTB_LANCAMENTO AS Lancamento, dbo_FATURAMENTO.CTB_ITEM AS Lanc_Item, 
IIf([dbo_FATURAMENTO].[FILIAL]="D.R. LINGERIE","D.R. LING",[dbo_FATURAMENTO].[FILIAL]) AS Filial, dbo_FATURAMENTO.NATUREZA_SAIDA AS Nat_Op, dbo_NATUREZAS_SAIDAS.DESC_NATUREZA AS Desc_Nat, dbo_FATURAMENTO.NF_SAIDA AS NF, dbo_FATURAMENTO.SERIE_NF AS Serie, dbo_FATURAMENTO.NOME_CLIFOR AS Clifor, dbo_FATURAMENTO.TIPO_FATURAMENTO AS TP, dbo_FATURAMENTO.EMISSAO AS Data, dbo_FATURAMENTO.MPADRAO_VALOR_TOTAL AS Vr, dbo_FATURAMENTO.QTDE_TOTAL as Qtd, dbo_FATURAMENTO.NOTA_CANCELADA AS Cancelada, dbo_FATURAMENTO.CHAVE_NFE, dbo_FATURAMENTO.PROTOCOLO_AUTORIZACAO_NFE, PROP_FATURAMENTO_00238.DATA_PARA_TRANSFERENCIA AS DT_Saida, PROP_FATURAMENTO_00238.PROPRIEDADE AS Prop
FROM ((dbo_FATURAMENTO 
LEFT JOIN dbo_NATUREZAS_SAIDAS ON dbo_FATURAMENTO.NATUREZA_SAIDA = dbo_NATUREZAS_SAIDAS.NATUREZA_SAIDA) 
LEFT JOIN dbo_CADASTRO_CLI_FOR ON dbo_FATURAMENTO.NOME_CLIFOR = dbo_CADASTRO_CLI_FOR.NOME_CLIFOR) 
LEFT JOIN PROP_FATURAMENTO_00238 ON (dbo_FATURAMENTO.NF_SAIDA = PROP_FATURAMENTO_00238.NF_SAIDA) AND (dbo_FATURAMENTO.SERIE_NF = PROP_FATURAMENTO_00238.SERIE_NF) AND (dbo_FATURAMENTO.FILIAL = PROP_FATURAMENTO_00238.FILIAL)
WHERE (((dbo_NATUREZAS_SAIDAS.DESC_NATUREZA) Like "*VENDA*") AND ((dbo_FATURAMENTO.EMISSAO) Between [Data_Inicial] And [Data_Final]) AND ((dbo_FATURAMENTO.NOTA_CANCELADA)=False));
UNION SELECT "Devolucao" AS Tipo, dbo_ENTRADAS.CTB_LANCAMENTO AS Lancamento, dbo_ENTRADAS.CTB_ITEM AS Lanc_Item, IIf([dbo_ENTRADAS].[FILIAL]="D.R. LINGERIE","D.R. LING",[dbo_ENTRADAS].[FILIAL]) AS Filial, dbo_ENTRADAS.NATUREZA AS Nat_Op, dbo_NATUREZAS_ENTRADAS.DESC_NATUREZA AS Desc_Nat, dbo_ENTRADAS.NF_ENTRADA AS NF, dbo_ENTRADAS.SERIE_NF AS Serie, dbo_ENTRADAS.NOME_CLIFOR AS Clifor, dbo_ENTRADAS.TIPO_ENTRADAS AS TP, dbo_ENTRADAS.RECEBIMENTO AS Data, dbo_ENTRADAS.VALOR_TOTAL*(-1) AS Vr, dbo_ENTRADAS.QTDE_TOTAL*(-1) as Qtd, dbo_ENTRADAS.NOTA_CANCELADA AS Cancelada, dbo_ENTRADAS.CHAVE_NFE, dbo_ENTRADAS.PROTOCOLO_AUTORIZACAO_NFE, "" AS DT_Saida, "00238" AS Prop
FROM (dbo_ENTRADAS 
LEFT JOIN dbo_NATUREZAS_ENTRADAS ON dbo_ENTRADAS.NATUREZA = dbo_NATUREZAS_ENTRADAS.NATUREZA) 
LEFT JOIN dbo_CADASTRO_CLI_FOR ON dbo_ENTRADAS.NOME_CLIFOR = dbo_CADASTRO_CLI_FOR.NOME_CLIFOR
WHERE (((dbo_NATUREZAS_ENTRADAS.DESC_NATUREZA) Like "*DEV*") AND ((dbo_ENTRADAS.RECEBIMENTO) Between [Data_Inicial] And [Data_Final]) AND ((dbo_ENTRADAS.NOTA_CANCELADA)=False));

