SELECT PRODUTOS_BARRA.PRODUTO,PRODUTOS_BARRA.COR_PRODUTO,PRODUTOS_BARRA.GRADE,VENDAS.Q_VENDA,ESTOQUE_PRODUTOS.ESTOQUE,PROCESSO.QTDE_S FROM PRODUTOS_BARRA 
INNER JOIN (
SELECT VENDAS.PRODUTO,VENDAS.COR_PRODUTO,VENDAS.GRADE,Q_VENDA=SUM(Q_VENDA) FROM (
    SELECT VENDAS_PRODUTO.PRODUTO,VENDAS_PRODUTO.COR_PRODUTO,PRODUTOS_BARRA.GRADE,
    Q_VENDA=(CASE  WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VO1 
               WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VO2
               WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VO3
               WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VO4
               WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VO5
               WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VO6
               WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VO7
               WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VO8
               WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VO9
               WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VO10
               WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VO11
               WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VO12
               WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VO13
               WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VO14
               WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VO15
               WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VO16
           END)
   FROM VENDAS_PRODUTO 
   INNER JOIN VENDAS ON VENDAS.PEDIDO=VENDAS_PRODUTO.PEDIDO
   INNER JOIN PRODUTOS_BARRA  ON PRODUTOS_BARRA.PRODUTO=VENDAS_PRODUTO.PRODUTO AND PRODUTOS_BARRA.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO
   WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND VENDAS.EMISSAO BETWEEN '20140901' AND '20140930'
) AS VENDAS
GROUP BY VENDAS.PRODUTO,VENDAS.COR_PRODUTO,VENDAS.GRADE) 
AS VENDAS ON VENDAS.PRODUTO=PRODUTOS_BARRA.PRODUTO AND VENDAS.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO AND VENDAS.GRADE=PRODUTOS_BARRA.GRADE

LEFT JOIN (
SELECT ESTOQUE_PRODUTOS.PRODUTO,ESTOQUE_PRODUTOS.COR_PRODUTO,PRODUTOS_BARRA.GRADE,
ESTOQUE =(CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN ESTOQUE_PRODUTOS.ES1 
               WHEN PRODUTOS_BARRA.tamanho='2'  THEN ESTOQUE_PRODUTOS.ES2
               WHEN PRODUTOS_BARRA.tamanho='3'  THEN ESTOQUE_PRODUTOS.ES3
               WHEN PRODUTOS_BARRA.tamanho='4'  THEN ESTOQUE_PRODUTOS.ES4
               WHEN PRODUTOS_BARRA.tamanho='5'  THEN ESTOQUE_PRODUTOS.ES5
               WHEN PRODUTOS_BARRA.tamanho='6'  THEN ESTOQUE_PRODUTOS.ES6
               WHEN PRODUTOS_BARRA.tamanho='7'  THEN ESTOQUE_PRODUTOS.ES7
               WHEN PRODUTOS_BARRA.tamanho='8'  THEN ESTOQUE_PRODUTOS.ES8
               WHEN PRODUTOS_BARRA.tamanho='9'  THEN ESTOQUE_PRODUTOS.ES9
               WHEN PRODUTOS_BARRA.tamanho='10' THEN ESTOQUE_PRODUTOS.ES10
               WHEN PRODUTOS_BARRA.tamanho='11' THEN ESTOQUE_PRODUTOS.ES11
               WHEN PRODUTOS_BARRA.tamanho='12' THEN ESTOQUE_PRODUTOS.ES12
               WHEN PRODUTOS_BARRA.tamanho='13' THEN ESTOQUE_PRODUTOS.ES13
               WHEN PRODUTOS_BARRA.tamanho='14' THEN ESTOQUE_PRODUTOS.ES14
               WHEN PRODUTOS_BARRA.tamanho='15' THEN ESTOQUE_PRODUTOS.ES15
               WHEN PRODUTOS_BARRA.tamanho='16' THEN ESTOQUE_PRODUTOS.ES16
           END)
FROM ESTOQUE_PRODUTOS
INNER JOIN PRODUTOS_BARRA  ON PRODUTOS_BARRA.PRODUTO=ESTOQUE_PRODUTOS.PRODUTO AND PRODUTOS_BARRA.COR_PRODUTO=ESTOQUE_PRODUTOS.COR_PRODUTO
WHERE ESTOQUE_PRODUTOS.FILIAL='DR VAREJO' AND PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%') 
AS ESTOQUE_PRODUTOS ON ESTOQUE_PRODUTOS.PRODUTO=PRODUTOS_BARRA.PRODUTO AND ESTOQUE_PRODUTOS.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO AND ESTOQUE_PRODUTOS.GRADE=PRODUTOS_BARRA.GRADE

LEFT JOIN (
SELECT PRODUCAO.PRODUTO,PRODUCAO.COR_PRODUTO,PRODUCAO.GRADE,QTDE_S=SUM(QTDE_S) FROM (
	SELECT  
	PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,  
	PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, 
	PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, 
	PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO,
	PRODUTOS_BARRA.GRADE,
	QTDE_S = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN PRODUCAO_TAREFAS_SALDO.S1 
				   WHEN PRODUTOS_BARRA.tamanho='2'  THEN PRODUCAO_TAREFAS_SALDO.S2 
				   WHEN PRODUTOS_BARRA.tamanho='3'  THEN PRODUCAO_TAREFAS_SALDO.S3 
				   WHEN PRODUTOS_BARRA.tamanho='4'  THEN PRODUCAO_TAREFAS_SALDO.S4 
				   WHEN PRODUTOS_BARRA.tamanho='5'  THEN PRODUCAO_TAREFAS_SALDO.S5 
				   WHEN PRODUTOS_BARRA.tamanho='6'  THEN PRODUCAO_TAREFAS_SALDO.S6 
				   WHEN PRODUTOS_BARRA.tamanho='7'  THEN PRODUCAO_TAREFAS_SALDO.S7 
				   WHEN PRODUTOS_BARRA.tamanho='8'  THEN PRODUCAO_TAREFAS_SALDO.S8 
				   WHEN PRODUTOS_BARRA.tamanho='9'  THEN PRODUCAO_TAREFAS_SALDO.S9 
				   WHEN PRODUTOS_BARRA.tamanho='10' THEN PRODUCAO_TAREFAS_SALDO.S10 
				   WHEN PRODUTOS_BARRA.tamanho='11' THEN PRODUCAO_TAREFAS_SALDO.S11 
				   WHEN PRODUTOS_BARRA.tamanho='12' THEN PRODUCAO_TAREFAS_SALDO.S12 
				   WHEN PRODUTOS_BARRA.tamanho='13' THEN PRODUCAO_TAREFAS_SALDO.S13 
				   WHEN PRODUTOS_BARRA.tamanho='14' THEN PRODUCAO_TAREFAS_SALDO.S14 
				   WHEN PRODUTOS_BARRA.tamanho='15' THEN PRODUCAO_TAREFAS_SALDO.S15 
				   WHEN PRODUTOS_BARRA.tamanho='16' THEN PRODUCAO_TAREFAS_SALDO.S16 
			   END)
	           
	FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, dbo.PRODUCAO_SETOR PRODUCAO_SETOR, dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, dbo.PRODUTOS PRODUTOS, DBO.PRODUTOS_BARRA PRODUTOS_BARRA
	WHERE PRODUCAO_TAREFAS_SALDO.PRODUTO=PRODUTOS_BARRA.PRODUTO AND 
	PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO AND 
	PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
	PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
	PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
	PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
	PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
	PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
	PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
	PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND 
	PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','007') 
) AS PRODUCAO
GROUP BY PRODUCAO.PRODUTO,PRODUCAO.COR_PRODUTO,PRODUCAO.GRADE) 
AS PROCESSO ON PROCESSO.PRODUTO=PRODUTOS_BARRA.PRODUTO AND PROCESSO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO AND PROCESSO.GRADE=PRODUTOS_BARRA.GRADE

WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' 
ORDER BY PRODUTOS_BARRA.PRODUTO,PRODUTOS_BARRA.COR_PRODUTO

