SELECT * FROM W_MONITORA_EMAIL
WHERE DATAENVIO >='20170118' AND SITUACAO = '2 - Falhou'

SELECT * FROM W_MONITORA_EMAIL
WHERE ASSUNTO LIKE '%Grade ou Qtde Total alterada depois de aprovado%' --destinatario='financeiro1@drling.com.br' DATAENVIO >='20170118' AND SITUACAO = '2 - Falhou'
ORDER BY DATAENVIO

SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO='87920'


UPDATE VENDAS_PRODUTO
SET VO1=360
WHERE PEDIDO='87920' AND PRODUTO='5205-D2-G'

EXEC SP_PEDIDO_GRADE_ALTERADA_ENVIAR_EMAIL_PCP '87920', '5205-D1-G', '001'