SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'CAN ATE 3110 EM 0810'



SELECT PROGRAMACAO,ENTRADA_ESTOQUE.EMISSAO,PROGRAMACAO.GRADE,PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO, ENTRADA_ESTOQUE.QTDE, 
EN_1=ISNULL(ENTRADA_ESTOQUE.EN_1,0),EN_2=ISNULL(ENTRADA_ESTOQUE.EN_2,0),EN_3=ISNULL(ENTRADA_ESTOQUE.EN_3,0),EN_4=ISNULL(ENTRADA_ESTOQUE.EN_4,0),EN_5=ISNULL(ENTRADA_ESTOQUE.EN_5,0), 
EN_6=ISNULL(ENTRADA_ESTOQUE.EN_6,0),EN_7=ISNULL(ENTRADA_ESTOQUE.EN_7,0),EN_8=ISNULL(ENTRADA_ESTOQUE.EN_8,0),EN_9=ISNULL(ENTRADA_ESTOQUE.EN_9,0),EN_10=ISNULL(ENTRADA_ESTOQUE.EN_10,0), 
EN_11=ISNULL(ENTRADA_ESTOQUE.EN_11,0),EN_12=ISNULL(ENTRADA_ESTOQUE.EN_12,0),EN_13=ISNULL(ENTRADA_ESTOQUE.EN_13,0),EN_14=ISNULL(ENTRADA_ESTOQUE.EN_14,0),EN_15=ISNULL(ENTRADA_ESTOQUE.EN_15,0), 
EN_16=ISNULL(ENTRADA_ESTOQUE.EN_16,0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'CAN ATE 3110 EM 0810'
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO, 
ESTOQUE_PROD1_ENT.COR_PRODUTO, QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE), EN_1=SUM(ESTOQUE_PROD1_ENT.EN_1), EN_2=SUM(ESTOQUE_PROD1_ENT.EN_2), 
EN_3=SUM(ESTOQUE_PROD1_ENT.EN_3), EN_4=SUM(ESTOQUE_PROD1_ENT.EN_4), EN_5=SUM(ESTOQUE_PROD1_ENT.EN_5), EN_6=SUM(ESTOQUE_PROD1_ENT.EN_6), 
EN_7=SUM(ESTOQUE_PROD1_ENT.EN_7), EN_8=SUM(ESTOQUE_PROD1_ENT.EN_8), EN_9=SUM(ESTOQUE_PROD1_ENT.EN_9), EN_10=SUM(ESTOQUE_PROD1_ENT.EN_10), 
EN_11=SUM(ESTOQUE_PROD1_ENT.EN_11), EN_12=SUM(ESTOQUE_PROD1_ENT.EN_12), EN_13=SUM(ESTOQUE_PROD1_ENT.EN_13), EN_14=SUM(ESTOQUE_PROD1_ENT.EN_14), 
EN_15=SUM(ESTOQUE_PROD1_ENT.EN_15), EN_16=SUM(ESTOQUE_PROD1_ENT.EN_16) 
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS, 
DBO.PRODUTO_CORES PRODUTO_CORES  
WHERE ESTOQUE_PROD_ENT.EMISSAO >= '20141008' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD_ENT.EMISSAO <= '20141009' AND 
ESTOQUE_PROD1_ENT.FILIAL = 'ESTOQUE EM TRANSICAO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTO_CORES.PRODUTO AND 
ESTOQUE_PROD1_ENT.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, PRODUTOS.GRADE, ESTOQUE_PROD1_ENT.PRODUTO, ESTOQUE_PROD1_ENT.COR_PRODUTO 
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO AND ENTRADA_ESTOQUE.COR_PRODUTO=PROGRAMACAO.COR_PRODUTO 
ORDER BY PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,ENTRADA_ESTOQUE.EMISSAO




--- ALTERAÇÃO DA PROGRAMAÇÃO PARA VERIFICAR ENTRADAS NA FASE 009
SELECT PROGRAMACAO,PRODUCAO_ENTRADA_ESTOQUE.DATA,PROGRAMACAO.GRADE,PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO, PRODUCAO_ENTRADA_ESTOQUE.QTDE, 
O1=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O1,0),O2=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O2,0),O3=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O3,0),O4=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O4,0),O5=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O5,0), 
O6=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O6,0),O7=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O7,0),O8=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O8,0),O9=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O9,0),O10=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O10,0), 
O11=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O11,0),O12=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O12,0),O13=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O13,0),O14=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O14,0),O15=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O15,0), 
O16=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O16,0),
P1=ISNULL(PROGRAMACAO.P1,0), 
P2=ISNULL(PROGRAMACAO.P2,0),  
P3=ISNULL(PROGRAMACAO.P3,0),  
P4=ISNULL(PROGRAMACAO.P4,0),  
P5=ISNULL(PROGRAMACAO.P5,0),  
P6=ISNULL(PROGRAMACAO.P6,0),  
P7=ISNULL(PROGRAMACAO.P7,0),  
P8=ISNULL(PROGRAMACAO.P8,0),  
P9=ISNULL(PROGRAMACAO.P9,0),  
P10=ISNULL(PROGRAMACAO.P10,0),  
P11=ISNULL(PROGRAMACAO.P11,0),  
P12=ISNULL(PROGRAMACAO.P12,0),  
P13=ISNULL(PROGRAMACAO.P13,0),  
P14=ISNULL(PROGRAMACAO.P14,0),  
P15=ISNULL(PROGRAMACAO.P15,0),  
P16=ISNULL(PROGRAMACAO.P16,0)  
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL 
FROM  PRODUTOS PRODUTOS WITH (NOLOCK), PRODUTO_CORES PRODUTO_CORES WITH (NOLOCK), 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD WITH (NOLOCK), DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA WITH (NOLOCK) 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'CAN ATE 3110 EM 0810'
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT DISTINCT 
PRODUCAO_ORDEM_SERVICO.DATA,
PRODUCAO_OS_TAREFAS.PRODUTO, 
PRODUCAO_OS_TAREFAS.COR_PRODUTO, 
QTDE=SUM(PRODUCAO_OS_TAREFAS.QTDE_O), 
O1=SUM(PRODUCAO_OS_TAREFAS.O1), 
O2=SUM(PRODUCAO_OS_TAREFAS.O2), 
O3=SUM(PRODUCAO_OS_TAREFAS.O3), 
O4=SUM(PRODUCAO_OS_TAREFAS.O4), 
O5=SUM(PRODUCAO_OS_TAREFAS.O5), 
O6=SUM(PRODUCAO_OS_TAREFAS.O6), 
O7=SUM(PRODUCAO_OS_TAREFAS.O7), 
O8=SUM(PRODUCAO_OS_TAREFAS.O8), 
O9=SUM(PRODUCAO_OS_TAREFAS.O9), 
O10=SUM(PRODUCAO_OS_TAREFAS.O10), 
O11=SUM(PRODUCAO_OS_TAREFAS.O11), 
O12=SUM(PRODUCAO_OS_TAREFAS.O12), 
O13=SUM(PRODUCAO_OS_TAREFAS.O13), 
O14=SUM(PRODUCAO_OS_TAREFAS.O14), 
O15=SUM(PRODUCAO_OS_TAREFAS.O15), 
O16=SUM(PRODUCAO_OS_TAREFAS.O16)
FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS with (nolock), 
DBO.PRODUTO_CORES PRODUTO_CORES with (nolock), 
DBO.PRODUTOS PRODUTOS with (nolock), 
DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock),
DBO.PRODUCAO_ORDEM_SERVICO 
WHERE (((PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTO_CORES.PRODUTO AND  
PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  
PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTOS.PRODUTO ) AND  
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_OS_TAREFAS.TAREFA ) AND  
PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO AND 
PRODUCAO_ORDEM_SERVICO.DATA >='20141008' AND PRODUCAO_ORDEM_SERVICO.DATA <='20141009' AND 
PRODUCAO_TAREFAS.FASE_PRODUCAO='009' AND 
PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV='1'
GROUP BY PRODUCAO_ORDEM_SERVICO.DATA,
PRODUCAO_OS_TAREFAS.PRODUTO, 
PRODUCAO_OS_TAREFAS.COR_PRODUTO
) AS PRODUCAO_ENTRADA_ESTOQUE ON PRODUCAO_ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO AND PRODUCAO_ENTRADA_ESTOQUE.COR_PRODUTO=PROGRAMACAO.COR_PRODUTO 
ORDER BY PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,PRODUCAO_ENTRADA_ESTOQUE.DATA




--- PRODUÇÃO FASE 009
SELECT 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO.DATA, 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO,
QTDE_O =SUM(PRODUCAO_OS_TAREFAS.QTDE_O) 
FROM PRODUCAO_ORDEM_SERVICO
JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

JOIN (
 
SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

) AS COSTURA
ON PRODUCAO_OS_TAREFAS.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='009' AND PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV=1 AND YEAR(PRODUCAO_ORDEM_SERVICO.DATA)>=2014 AND PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO 

GROUP BY 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO.DATA, 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO




SELECT PROGRAMACAO,
PRODUCAO_ENTRADA_ESTOQUE.DATA,
PROGRAMACAO.GRADE,
PROGRAMACAO.PRODUTO,
PROGRAMACAO.COR_PRODUTO, 
PRODUCAO_ENTRADA_ESTOQUE.QTDE, 
A1=CASE WHEN ISNULL(PROGRAMACAO.P1,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O1,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O1,0) ELSE 0 END,
A2=CASE WHEN ISNULL(PROGRAMACAO.P2,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O2,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O2,0) ELSE 0 END,
A3=CASE WHEN ISNULL(PROGRAMACAO.P3,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O3,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O3,0) ELSE 0 END,
A4=CASE WHEN ISNULL(PROGRAMACAO.P4,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O4,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O4,0) ELSE 0 END,
A5=CASE WHEN ISNULL(PROGRAMACAO.P5,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O5,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O5,0) ELSE 0 END,
A6=CASE WHEN ISNULL(PROGRAMACAO.P6,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O6,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O6,0) ELSE 0 END,
A7=CASE WHEN ISNULL(PROGRAMACAO.P7,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O7,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O7,0) ELSE 0 END,
A8=CASE WHEN ISNULL(PROGRAMACAO.P8,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O8,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O8,0) ELSE 0 END,
A9=CASE WHEN ISNULL(PROGRAMACAO.P9,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O9,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O9,0) ELSE 0 END,
A10=CASE WHEN ISNULL(PROGRAMACAO.P10,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O10,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O10,0) ELSE 0 END,
A11=CASE WHEN ISNULL(PROGRAMACAO.P11,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O11,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O11,0) ELSE 0 END,
A12=CASE WHEN ISNULL(PROGRAMACAO.P12,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O12,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O12,0) ELSE 0 END,
A13=CASE WHEN ISNULL(PROGRAMACAO.P13,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O13,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O13,0) ELSE 0 END,
A14=CASE WHEN ISNULL(PROGRAMACAO.P14,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O14,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O14,0) ELSE 0 END,
A15=CASE WHEN ISNULL(PROGRAMACAO.P15,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O15,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O15,0) ELSE 0 END,
A16=CASE WHEN ISNULL(PROGRAMACAO.P16,0) > 0 AND ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O16,0) > 0
THEN ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O16,0) ELSE 0 END,

O1=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O1,0),
O2=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O2,0),
O3=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O3,0),
O4=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O4,0),
O5=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O5,0), 
O6=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O6,0),
O7=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O7,0),
O8=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O8,0),
O9=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O9,0),
O10=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O10,0), 
O11=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O11,0),
O12=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O12,0),
O13=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O13,0),
O14=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O14,0),
O15=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O15,0), 
O16=ISNULL(PRODUCAO_ENTRADA_ESTOQUE.O16,0),
P1=ISNULL(PROGRAMACAO.P1,0), 
P2=ISNULL(PROGRAMACAO.P2,0),  
P3=ISNULL(PROGRAMACAO.P3,0),  
P4=ISNULL(PROGRAMACAO.P4,0),  
P5=ISNULL(PROGRAMACAO.P5,0),  
P6=ISNULL(PROGRAMACAO.P6,0),  
P7=ISNULL(PROGRAMACAO.P7,0),  
P8=ISNULL(PROGRAMACAO.P8,0),  
P9=ISNULL(PROGRAMACAO.P9,0),  
P10=ISNULL(PROGRAMACAO.P10,0),  
P11=ISNULL(PROGRAMACAO.P11,0),  
P12=ISNULL(PROGRAMACAO.P12,0),  
P13=ISNULL(PROGRAMACAO.P13,0),  
P14=ISNULL(PROGRAMACAO.P14,0),  
P15=ISNULL(PROGRAMACAO.P15,0),  
P16=ISNULL(PROGRAMACAO.P16,0)  
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO,DATA_PROGRAMACAO=PRODUCAO_PROGRAMA.DATA, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL 
FROM  PRODUTOS PRODUTOS WITH (NOLOCK), PRODUTO_CORES PRODUTO_CORES WITH (NOLOCK), 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD WITH (NOLOCK), DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA WITH (NOLOCK) 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO )  AND PRODUCAO_PROG_PROD.PROGRAMACAO = 'CAN ATE 3110 EM 0810' --PRODUCAO_PROGRAMA.DATA >= '20140101'
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT DISTINCT 
PRODUCAO_ORDEM_SERVICO.DATA,
PRODUCAO_OS_TAREFAS.PRODUTO, 
PRODUCAO_OS_TAREFAS.COR_PRODUTO, 
QTDE=SUM(PRODUCAO_OS_TAREFAS.QTDE_O), 
O1=SUM(PRODUCAO_OS_TAREFAS.O1), 
O2=SUM(PRODUCAO_OS_TAREFAS.O2), 
O3=SUM(PRODUCAO_OS_TAREFAS.O3), 
O4=SUM(PRODUCAO_OS_TAREFAS.O4), 
O5=SUM(PRODUCAO_OS_TAREFAS.O5), 
O6=SUM(PRODUCAO_OS_TAREFAS.O6), 
O7=SUM(PRODUCAO_OS_TAREFAS.O7), 
O8=SUM(PRODUCAO_OS_TAREFAS.O8), 
O9=SUM(PRODUCAO_OS_TAREFAS.O9), 
O10=SUM(PRODUCAO_OS_TAREFAS.O10), 
O11=SUM(PRODUCAO_OS_TAREFAS.O11), 
O12=SUM(PRODUCAO_OS_TAREFAS.O12), 
O13=SUM(PRODUCAO_OS_TAREFAS.O13), 
O14=SUM(PRODUCAO_OS_TAREFAS.O14), 
O15=SUM(PRODUCAO_OS_TAREFAS.O15), 
O16=SUM(PRODUCAO_OS_TAREFAS.O16)
FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS with (nolock), 
DBO.PRODUTO_CORES PRODUTO_CORES with (nolock), 
DBO.PRODUTOS PRODUTOS with (nolock), 
DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock),
DBO.PRODUCAO_ORDEM_SERVICO 
WHERE (((PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTO_CORES.PRODUTO AND  
PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  
PRODUCAO_OS_TAREFAS.PRODUTO = PRODUTOS.PRODUTO ) AND  
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_OS_TAREFAS.TAREFA ) AND  
PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO AND 
PRODUCAO_ORDEM_SERVICO.DATA >='20140101' AND PRODUCAO_ORDEM_SERVICO.DATA <=GETDATE() AND 
PRODUCAO_TAREFAS.FASE_PRODUCAO='009' AND 
PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV='1'
GROUP BY PRODUCAO_ORDEM_SERVICO.DATA,
PRODUCAO_OS_TAREFAS.PRODUTO, 
PRODUCAO_OS_TAREFAS.COR_PRODUTO
) AS PRODUCAO_ENTRADA_ESTOQUE ON PRODUCAO_ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO AND PRODUCAO_ENTRADA_ESTOQUE.COR_PRODUTO=PROGRAMACAO.COR_PRODUTO 
ORDER BY PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,PRODUCAO_ENTRADA_ESTOQUE.DATA

