SELECT PRODUTOS.GRUPO_PRODUTO, FATURAMENTO.NOME_CLIFOR, FATURAMENTO.EMISSAO,FATURAMENTO.REPRESENTANTE, FATURAMENTO.GERENTE,QTDE=SUM(FATURAMENTO_PROD.QTDE),MVALOR=SUM(FATURAMENTO_PROD.VALOR*FATURAMENTO_PROD.CAMBIO_NA_DATA) 
FROM DRVAREJO.dbo.CADASTRO_CLI_FOR CADASTRO_CLI_FOR with (nolock), 
DRVAREJO.dbo.FATURAMENTO FATURAMENTO with (nolock), 
DRVAREJO.dbo.W_FATURAMENTO_06 W_FATURAMENTO_06 with (nolock),
DRVAREJO.dbo.FATURAMENTO_PROD WITH (NOLOCK),
DRVAREJO.dbo.PRODUTOS WITH (NOLOCK)
WHERE CADASTRO_CLI_FOR.NOME_CLIFOR = FATURAMENTO.NOME_CLIFOR AND 
CADASTRO_CLI_FOR.NOME_CLIFOR = W_FATURAMENTO_06.NOME_CLIFOR AND 
FATURAMENTO.NF_SAIDA = W_FATURAMENTO_06.NF_SAIDA AND 
FATURAMENTO.FILIAL = W_FATURAMENTO_06.FILIAL AND 
FATURAMENTO.SERIE_NF = W_FATURAMENTO_06.SERIE_NF AND
FATURAMENTO_PROD.NF_SAIDA = FATURAMENTO.NF_SAIDA AND 
FATURAMENTO_PROD.SERIE_NF = FATURAMENTO.SERIE_NF AND
FATURAMENTO_PROD.PRODUTO = PRODUTOS.PRODUTO AND
((FATURAMENTO.EMISSAO>={ts '2011-01-01 00:00:00'}) AND 
(FATURAMENTO.COD_TRANSACAO='FATURAMENTO_022') AND 
(W_FATURAMENTO_06.DESC_GRUPO_TIPO_OPERACAO='VENDA'))
GROUP BY PRODUTOS.GRUPO_PRODUTO, FATURAMENTO.NOME_CLIFOR, FATURAMENTO.EMISSAO,FATURAMENTO.REPRESENTANTE, FATURAMENTO.GERENTE,FATURAMENTO.MPADRAO_VALOR_TOTAL



