SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO,
       E.REGIAO,
       PERIODO_PCP=RTRIM(B.PERIODO_PCP),
       B.NUMERO_ENTREGA,
       A.ENTREGA,
       A.LIMITE_ENTREGA,
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A, 
     VENDAS B, 
     PRODUTOS C, 
     CADASTRO_CLI_FOR D,
     CLIENTES_ATACADO E
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      E.CLIENTE_ATACADO = D.NOME_CLIFOR AND
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20130101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO,
         E.REGIAO,
         B.PERIODO_PCP,
         B.NUMERO_ENTREGA,
         A.ENTREGA,
         A.LIMITE_ENTREGA
HAVING B.GERENTE IN ('JOSE ANTONIO SARMENTO','SARMENTO','SARMENTO - DR','SERGIO PIRES','SERGIO PIRES - DR','CELSO MACHADO','MARCUS ROBERTO','MARCUS CARIOCA','SILZOMAR VINICIO','VENDA DIRETA','DENI RICARDO MONCAY CECHI','JOSE MARIO','JOSE MARIO ARRUDA','MAURILIO ALBUQUERQUE','MAURILIO FERNANDES','MAURILIO FERNANDES - DR')


SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO_FATURAMENTO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       E.REGIAO,
       PERIODO_PCP=RTRIM(F.PERIODO_PCP),
       F.NUMERO_ENTREGA,       
       A.ENTREGA,
       QTDE=SUM(A.QTDE), 
       VALOR=SUM(A.VALOR)
FROM FATURAMENTO_PROD A, 
     FATURAMENTO B, 
     PRODUTOS C, 
     CADASTRO_CLI_FOR D,
	 CLIENTES_ATACADO E,
	 VENDAS F
WHERE A.NF_SAIDA = B.NF_SAIDA AND A.SERIE_NF = B.SERIE_NF 
      AND C.PRODUTO = A.PRODUTO 
      AND B.NOME_CLIFOR = D.NOME_CLIFOR 
      AND E.CLIENTE_ATACADO = D.NOME_CLIFOR
      AND F.PEDIDO = A.PEDIDO AND F.TABELA_FILHA='VENDAS_PRODUTO'
      AND ((B.TABELA_FILHA='FATURAMENTO_PROD') AND (B.EMISSAO>='20130101') AND (B.NOTA_CANCELADA=0)) 
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO_FATURAMENTO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO,
   	     E.REGIAO,
         F.PERIODO_PCP,
         F.NUMERO_ENTREGA,
   	     A.ENTREGA
   	     
HAVING B.GERENTE IN ('JOSE ANTONIO SARMENTO','SARMENTO','SARMENTO - DR','SERGIO PIRES','SERGIO PIRES - DR','CELSO MACHADO','MARCUS ROBERTO','MARCUS CARIOCA','SILZOMAR VINICIO','VENDA DIRETA','JOSE MARIO','JOSE MARIO ARRUDA','MAURILIO ALBUQUERQUE','MAURILIO FERNANDES','MAURILIO FERNANDES - DR','DENI RICARDO MONCAY CECHI')


