--- adicionado union para trazer as NFe de consumiveis
SELECT GRIFFE, GRUPO_PRODUTO,A.PRODUTO,GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO, 
A.DESCONTO_ITEM, 
A.VALOR, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE,
VALOR_LIQUIDO_TOTAL=((A.VALOR*A.CAMBIO_NA_DATA) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO+B.DESCONTO_COND_PGTO) >0 THEN A.VALOR*ABS(B.DESCONTO+B.DESCONTO_COND_PGTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN FATURAMENTO B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
union all
SELECT GRIFFE, GRUPO_PRODUTO,A.CODIGO_ITEM,GERENTE,REPRESENTANTE,NOME_CLIFOR,B.NF_SAIDA,EMISSAO,
A.PRECO_UNITARIO, 
A.DESCONTO_ITEM, 
A.PRECO_UNITARIO_ORIGINAL, 
B.VALOR_IMPOSTO_AGREGAR,
A.QTDE_ITEM,
VALOR_LIQUIDO_TOTAL=((A.VALOR_ITEM) + ((CASE WHEN B.VALOR_IMPOSTO_AGREGAR <>0 THEN A.VALOR_ITEM*B.VALOR_IMPOSTO_AGREGAR/B.VALOR_SUB_ITENS ELSE 0 END )) -
(CASE WHEN ABS(B.DESCONTO+B.DESCONTO_COND_PGTO) >0 THEN A.PRECO_UNITARIO_ORIGINAL*ABS(B.DESCONTO+B.DESCONTO_COND_PGTO)/B.VALOR_SUB_ITENS ELSE 0 END )  )
FROM FATURAMENTO B WITH (NOLOCK)
JOIN FATURAMENTO_ITEM A WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.CODIGO_ITEM
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE B.EMISSAO >='20170101' AND B.EMISSAO <= '20171231' AND D.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO'
and not exists(select * from faturamento_prod where NF_SAIDA=b.NF_SAIDA and SERIE_NF=b.SERIE_NF)