select b.filial,C.GRIFFE, C.GRUPO_PRODUTO,a.PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.TIPO_FATURAMENTO,A.NF_SAIDA, A.EMISSAO,A.MPADRAO_VALOR_LIQUIDO,
A.QTDE,F.MATRIZ_CLIENTE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - 
((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END ))),
C.TIPO_PRODUTO,A.TIPO_OPERACAO,D.PRECO1 AS CUSTO,G.UF,H.REGIAO, TIPO_CLIENTE.VALOR_PROPRIEDADE AS TIPO_CLIENTE,RTRIM(I.VALOR_PROPRIEDADE) AS FATOR_KIT
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
LEFT JOIN PRODUTOS_PRECOS D WITH (NOLOCK) ON D.PRODUTO=A.PRODUTO AND D.CODIGO_TAB_PRECO=c.CODIGO_PRECO
LEFT JOIN CLIENTES_ATACADO F WITH (NOLOCK) ON F.CLIENTE_ATACADO=A.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.NOME_CLIFOR=A.NOME_CLIFOR
LEFT JOIN LCF_LX_REGIOES_BRASIL H WITH (NOLOCK) ON H.UF=G.UF
LEFT JOIN (SELECT PROPRIEDADE,CLIENTE_ATACADO,VALOR_PROPRIEDADE FROM PROP_CLIENTES_ATACADO WITH (NOLOCK) WHERE PROPRIEDADE='00261') AS TIPO_CLIENTE ON 
		 TIPO_CLIENTE.CLIENTE_ATACADO=F.CLIENTE_ATACADO
LEFT JOIN PROP_PRODUTOS_GRIFFES I WITH (NOLOCK) ON I.GRIFFE=C.GRIFFE
WHERE B.EMISSAO between '20160101' AND '20161231' AND B.FILIAL='DR VAREJO'
--and a.produto='v1233'