select * from CADASTRO_CLI_FOR
WHERE NOME_CLIFOR LIKE 'MARIA CARLA%'

SELECT * FROM CLIENTES_ATACADO
WHERE CLIFOR='513556'

SELECT * FROM CLIENTE_REPRE
WHERE CLIENTE_ATACADO='MARIA CARLA DA SILVA CAST'
