SELECT PROGRAMACAO.PROGRAMACAO,PROGRAMACAO.GRADE,PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,PROGRAMACAO.DESC_COR_PRODUTO,PROGRAMACAO.DESC_COR_PRODUTO,PRODUCAO_TAREFAS_SALDO.QTDE_S, 
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO,PRODUCAO_TAREFAS_SALDO.RECURSO_PRODUTIVO,PRODUCAO_TAREFAS_SALDO.DESC_RECURSO,PRODUCAO_TAREFAS_SALDO.SETOR_PRODUCAO, 
PRODUCAO_TAREFAS_SALDO.DESC_SETOR_PRODUCAO,PRODUCAO_TAREFAS_SALDO.FASE_PRODUCAO,convert(char(10),PRODUCAO_TAREFAS_SALDO.INICIO_REAL,103) as inicio_real,convert(char(10),PRODUCAO_TAREFAS_SALDO.FIM_ATUALIZADO,103) as fim_atualizado, 
PROGRAMACAO.QTDE_GERADA, S1=ISNULL(PRODUCAO_TAREFAS_SALDO.S1,0),S2=ISNULL(PRODUCAO_TAREFAS_SALDO.S2,0),S3=ISNULL(PRODUCAO_TAREFAS_SALDO.S3,0),S4=ISNULL(PRODUCAO_TAREFAS_SALDO.S4,0),S5=ISNULL(PRODUCAO_TAREFAS_SALDO.S5,0), 
S6=ISNULL(PRODUCAO_TAREFAS_SALDO.S6,0),S7=ISNULL(PRODUCAO_TAREFAS_SALDO.S7,0),S8=ISNULL(PRODUCAO_TAREFAS_SALDO.S8,0),S9=ISNULL(PRODUCAO_TAREFAS_SALDO.S9,0),S10=ISNULL(PRODUCAO_TAREFAS_SALDO.S10,0), 
S11=ISNULL(PRODUCAO_TAREFAS_SALDO.S11,0),S12=ISNULL(PRODUCAO_TAREFAS_SALDO.S12,0),S13=ISNULL(PRODUCAO_TAREFAS_SALDO.S13,0),S14=ISNULL(PRODUCAO_TAREFAS_SALDO.S14,0),S15=ISNULL(PRODUCAO_TAREFAS_SALDO.S15,0), 
S16=ISNULL(PRODUCAO_TAREFAS_SALDO.S16,0) 
FROM 
( 
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = '01.09.17'
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, 
PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, 
PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, 
PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, 
PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_TAREFAS_SALDO.S13, 
PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16, 
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO, PRODUCAO_TAREFAS.INICIO_PREVISTO, 
PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_ATUALIZADO, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, 
PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, 
PRODUCAO_ORDEM.PREVISAO_FIM, PRODUCAO_ORDEM.PROGRAMACAO, PRODUCAO_ORDEM.TIPO_ORDEM_PRODUCAO, PRODUTOS.GRADE, 
PRODUCAO_TAREFAS.FASE_PRODUCAO FROM  DBO.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, DBO.PRODUTOS PRODUTOS, 
DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, DBO.PRODUCAO_ORDEM PRODUCAO_ORDEM, DBO.PRODUCAO_ORDEM_COR PRODUCAO_ORDEM_COR, 
DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, DBO.PRODUCAO_SETOR PRODUCAO_SETOR 
WHERE ((((((((PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND  
PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO ) AND  
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO ) AND  
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO ) AND  
PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO ) AND  
PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO )  AND PRODUCAO_ORDEM.FILIAL='D.R. LINGERIE' AND PRODUCAO_TAREFAS_SALDO.QTDE_S >0 AND PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0 )  AS PRODUCAO_TAREFAS_SALDO 
ON PRODUCAO_TAREFAS_SALDO.PRODUTO=PROGRAMACAO.PRODUTO AND PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PROGRAMACAO.COR_PRODUTO 
JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS.FASE_PRODUCAO=PRODUCAO_TAREFAS_SALDO.FASE_PRODUCAO AND PRODUCAO_TAREFAS.ORDEM_PRODUCAO=PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO 
ORDER BY PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA desc,PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO






SELECT VENDAS_PRODUTO.PEDIDO, VENDAS.CLIENTE_ATACADO, VENDAS.REPRESENTANTE, VENDAS_PRODUTO.PRODUTO, ENTREGA, VENDAS.CADASTRAMENTO, VENDAS.EMISSAO, VENDAS_PRODUTO.COR_PRODUTO, LIMITE_ENTREGA, QTDE_EMBALADA, QTDE_ENTREGAR, QTDE_ENTREGUE,   QTDE_DEVOLVIDA, QTDE_CANCELADA, PRECO1, PRECO2, PRECO3, PRECO4,   VENDAS_PRODUTO.DESCONTO_ITEM, IPI, VO1, VO2, VO3, VO4, VO5, VO6, VO7, VO8, VO9, VO10, VO11, VO12, VO13, VO14, VO15, VO16, VO17, VO18, VO19, VO20, VO21, VO22, VO23, VO24, VO25, VO26,   VO27, VO28, VO29, VO30, VO31, VO32, VO33, VO34, VO35, VO36, VO37, VO38, VO39, VO40, VO41, VO42, VO43, VO44, VO45, VO46, VO47, VO48, VE1, VE2, VE3, VE4, VE5, VE6, VE7, VE8, VE9, VE10, VE11, VE12, VE13, VE14, VE15, VE16, VE17, VE18, VE19, VE20, VE21,   VE22, VE23, VE24, VE25, VE26, VE27, VE28, VE29, VE30, VE31, VE32, VE33, VE34, VE35, VE36, VE37, VE38, VE39, VE40, VE41, VE42, VE43, VE44, VE45, VE46, VE47, VE48, PACKS,   VENDAS_PRODUTO.STATUS_VENDA_ATUAL, VENDAS.NUMERO_ENTREGA,   VENDAS.COLECAO AS COLECAO_VENDA, VENDAS.CODIGO_TAB_PRECO, VENDAS.TIPO, PRODUTOS.TABELA_OPERACOES, PRODUTOS.TABELA_MEDIDAS, PRODUTOS.TIPO_PRODUTO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO,   PRODUTOS.GRADE, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUTOS.CARTELA, PRODUTOS.REFER_FABRICANTE, PRODUTOS.MODELAGEM, PRODUTOS.FABRICANTE, PRODUTOS.ESTILISTA, PRODUTOS.MODELISTA, PRODUTOS.PERIODO_PCP, PRODUTO_CORES.DESC_COR_PRODUTO,   PRODUTO_CORES.COR_SORTIDA,   PRODUTO_CORES.TIPO_LAVAGEM_TINTURARIA, QTDE_ORIGINAL, PRODUTOS.REVENDA, 
PRODUTOS.SORTIMENTO_COR, PRODUTOS.SORTIMENTO_TAMANHO, PRODUTO_CORES.TINTURARIA_LAVAGEM,   PRODUTO_CORES.SORTIMENTO_COR SORTIMENTO, VENDAS.GERENTE, VENDAS.PEDIDO_CLIENTE, VENDAS.PRIORIDADE, VENDAS.APROVACAO, VENDAS.APROVADO_POR, VENDAS.CONDICAO_PGTO, 
COND_ATAC_PGTOS.DESC_COND_PGTO,CLIENTES_ATACADO.CLIFOR, CADASTRO_CLI_FOR.RAZAO_SOCIAL,   CADASTRO_CLI_FOR.CIDADE, CADASTRO_CLI_FOR.UF, CADASTRO_CLI_FOR.PAIS, REGIAO, VENDAS.MOEDA,   VALOR_CANCELADO VALOR_CANCELADO_MOEDA, CONVERT(NUMERIC(14, 2), 
VALOR_CANCELADO*CAMBIO_ATUAL) VALOR_CANCELADO, VALOR_ORIGINAL VALOR_ORIGINAL_MOEDA,   CONVERT(NUMERIC(14, 2), VALOR_ORIGINAL*CAMBIO_ATUAL) VALOR_ORIGINAL, VALOR_ENTREGAR VALOR_ENTREGAR_MOEDA,   CONVERT(NUMERIC(14, 2), VALOR_ENTREGAR*CAMBIO_ATUAL) VALOR_ENTREGAR, 
VALOR_ENTREGUE VALOR_ENTREGUE_MOEDA,   ENTREGUE_MOEDA_PADRAO VALOR_ENTREGUE, VALOR_DEVOLVIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (VENDAS.TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-ISNULL(VENDAS.RECARGO,   0)-VENDAS.VALOR_IPI)=0 THEN 0 
ELSE (VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO)/(VENDAS.TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-ISNULL(VENDAS.RECARGO, 0)-VENDAS.VALOR_IPI)*100 END) DESCONTO_NO_TOTAL,     CONVERT(NUMERIC(14, 2), CASE WHEN 
(VENDAS.TOT_VALOR_ORIGINAL-VENDAS.ENCARGO+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-ISNULL(VENDAS.RECARGO,   0)-VENDAS.VALOR_IPI)=0 THEN 0 ELSE VENDAS.ENCARGO/(VENDAS.TOT_VALOR_ORIGINAL-VENDAS.ENCARGO+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-ISNULL(VENDAS.RECARGO, 
0)-VENDAS.VALOR_IPI)*100 END) ENCARGO_NO_TOTAL,   CONVERT(NUMERIC(14, 2),   CASE WHEN (VENDAS.TOT_VALOR_ORIGINAL-ISNULL(VENDAS.RECARGO, 0)-VENDAS.VALOR_IPI)=0 THEN 0 ELSE ISNULL(VENDAS.RECARGO, 0)/(VENDAS.TOT_VALOR_ORIGINAL-ISNULL(VENDAS.RECARGO, 
0)-VENDAS.VALOR_IPI)*100 END) RECARGO_NO_TOTAL,   CONVERT(NUMERIC(14, 2),   CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ENTREGAR ELSE (VALOR_ENTREGAR-(VALOR_ENTREGAR*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ENTREGAR*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_ENTREGAR*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ENTREGAR*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ENTREGAR)*IPI)/100) END) VALOR_ENTREGAR_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ENTREGAR ELSE (VALOR_ENTREGAR-(VALOR_ENTREGAR*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ENTREGAR*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_ENTREGAR*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ENTREGAR*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ENTREGAR)*IPI)/100) END*CAMBIO_ATUAL) VALOR_ENTREGAR_LIQUIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ORIGINAL ELSE (VALOR_ORIGINAL-(VALOR_ORIGINAL*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ORIGINAL*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_ORIGINAL*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ORIGINAL*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ORIGINAL)*IPI)/100) 
END) VALOR_ORIGINAL_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ORIGINAL ELSE 
(VALOR_ORIGINAL-(VALOR_ORIGINAL*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))-(VALOR_ORIGINAL*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_ORIGINAL*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ORIGINAL*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ORIGINAL)*IPI)/100) 
END*CAMBIO_ATUAL) VALOR_ORIGINAL_LIQUIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_CANCELADO ELSE 
(VALOR_CANCELADO-(VALOR_CANCELADO*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))-(VALOR_CANCELADO*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_CANCELADO*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_CANCELADO*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_CANCELADO)*IPI)/100) 
END) VALOR_CANCELADO_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), 
CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_CANCELADO ELSE (VALOR_CANCELADO-(VALOR_CANCELADO*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+
VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-
(VALOR_CANCELADO*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_CANCELADO*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-
VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_CANCELADO*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_CANCELADO)*IPI)/100) END*CAMBIO_ATUAL) VALOR_CANCELADO_LIQUIDO,   VENDAS_PRODUTO.ID_MODIFICACAO, 
MODIFICACAO_FICHA_TECNICA.DESC_MODIFICACAO, VENDAS_PRODUTO.DESC_VENDA_CLIENTE, VENDAS.INDICADOR_VENDA,  CLIENTES_ATACADO.MATRIZ_CLIENTE    FROM    VENDAS    JOIN VENDAS_PRODUTO ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO    
JOIN PRODUTOS ON VENDAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO    
JOIN PRODUTO_CORES ON VENDAS_PRODUTO.PRODUTO = PRODUTO_CORES.PRODUTO   AND VENDAS_PRODUTO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO    
JOIN COND_ATAC_PGTOS ON VENDAS.CONDICAO_PGTO = COND_ATAC_PGTOS.CONDICAO_PGTO    
JOIN CLIENTES_ATACADO ON VENDAS.CLIENTE_ATACADO = CLIENTES_ATACADO.CLIENTE_ATACADO    
JOIN CADASTRO_CLI_FOR   ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR    
JOIN W_MOEDAS_CONVERSAO ON VENDAS.MOEDA = W_MOEDAS_CONVERSAO.MOEDA    
LEFT JOIN MODIFICACAO_FICHA_TECNICA ON VENDAS_PRODUTO.ID_MODIFICACAO =   MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO    
WHERE ENTREGA >= '20170303' AND ENTREGA <= '20170831' and (VENDAS.TOT_QTDE_ENTREGAR > '0' AND VENDAS.FILIAL = 'D.R. LINGERIE') and (( ( ( PRODUTOS.PRODUTO IN ('40714') and  produtos.INATIVO = CAST(0 AS BIT) ) ))) AND VENDAS.APROVACAO = 'A'





-----------------------------------------------------------
SELECT 
VENDAS_PROD_ANALITICO.PEDIDO_CLIENTE, 
VENDAS_PROD_ANALITICO.PEDIDO, 
VENDAS_PROD_ANALITICO.CLIENTE_ATACADO, 
VENDAS_PROD_ANALITICO.PRODUTO, 
VENDAS_PROD_ANALITICO.ENTREGA, 
VENDAS_PROD_ANALITICO.COR_PRODUTO, 
VENDAS_PROD_ANALITICO.LIMITE_ENTREGA, 
VENDAS_PROD_ANALITICO.QTDE_ENTREGAR, 
VENDAS_PROD_ANALITICO.DESC_PRODUTO, 
VENDAS_PROD_ANALITICO.DESC_COR_PRODUTO,   
VENDAS_PROD_ANALITICO.RAZAO_SOCIAL,   
VENDAS_PROD_ANALITICO.VALOR_ORIGINAL, 
VENDAS_PROD_ANALITICO.VALOR_ENTREGAR, 
PRODUCAO_TAREFAS_SALDO.QTDE_S, 
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO,
PRODUCAO_TAREFAS_SALDO.RECURSO_PRODUTIVO,
PRODUCAO_TAREFAS_SALDO.DESC_RECURSO,
PRODUCAO_TAREFAS_SALDO.SETOR_PRODUCAO, 
PRODUCAO_TAREFAS_SALDO.DESC_SETOR_PRODUCAO,
PRODUCAO_TAREFAS_SALDO.FASE_PRODUCAO,
VENDAS_PROD_ANALITICO.QTDE_ENTREGAR, 
VENDAS_PROD_ANALITICO.VE1, 
VENDAS_PROD_ANALITICO.VE2, 
VENDAS_PROD_ANALITICO.VE3, 
VENDAS_PROD_ANALITICO.VE4, 
VENDAS_PROD_ANALITICO.VE5, 
VENDAS_PROD_ANALITICO.VE6, 
VENDAS_PROD_ANALITICO.VE7, 
VENDAS_PROD_ANALITICO.VE8, 
VENDAS_PROD_ANALITICO.VE9, 
VENDAS_PROD_ANALITICO.VE10, 
VENDAS_PROD_ANALITICO.VE11, 
VENDAS_PROD_ANALITICO.VE12,  
VENDAS_PROD_ANALITICO.VE13,  
VENDAS_PROD_ANALITICO.VE14,  
VENDAS_PROD_ANALITICO.VE15,  
VENDAS_PROD_ANALITICO.VE16,  
S1=ISNULL(PRODUCAO_TAREFAS_SALDO.S1,0),
S2=ISNULL(PRODUCAO_TAREFAS_SALDO.S2,0),
S3=ISNULL(PRODUCAO_TAREFAS_SALDO.S3,0),
S4=ISNULL(PRODUCAO_TAREFAS_SALDO.S4,0),
S5=ISNULL(PRODUCAO_TAREFAS_SALDO.S5,0), 
S6=ISNULL(PRODUCAO_TAREFAS_SALDO.S6,0),
S7=ISNULL(PRODUCAO_TAREFAS_SALDO.S7,0),
S8=ISNULL(PRODUCAO_TAREFAS_SALDO.S8,0),
S9=ISNULL(PRODUCAO_TAREFAS_SALDO.S9,0),
S10=ISNULL(PRODUCAO_TAREFAS_SALDO.S10,0), 
S11=ISNULL(PRODUCAO_TAREFAS_SALDO.S11,0),
S12=ISNULL(PRODUCAO_TAREFAS_SALDO.S12,0),
S13=ISNULL(PRODUCAO_TAREFAS_SALDO.S13,0),
S14=ISNULL(PRODUCAO_TAREFAS_SALDO.S14,0),
S15=ISNULL(PRODUCAO_TAREFAS_SALDO.S15,0),
S16=ISNULL(PRODUCAO_TAREFAS_SALDO.S16,0) 
FROM 
( 
SELECT VENDAS_PRODUTO.PEDIDO, VENDAS.CLIENTE_ATACADO, VENDAS.REPRESENTANTE, VENDAS_PRODUTO.PRODUTO, ENTREGA, VENDAS.CADASTRAMENTO, VENDAS.EMISSAO, VENDAS_PRODUTO.COR_PRODUTO, LIMITE_ENTREGA, QTDE_EMBALADA, QTDE_ENTREGAR, QTDE_ENTREGUE,   QTDE_DEVOLVIDA, QTDE_CANCELADA, PRECO1, PRECO2, PRECO3, PRECO4,   VENDAS_PRODUTO.DESCONTO_ITEM, IPI, VO1, VO2, VO3, VO4, VO5, VO6, VO7, VO8, VO9, VO10, VO11, VO12, VO13, VO14, VO15, VO16, VO17, VO18, VO19, VO20, VO21, VO22, VO23, VO24, VO25, VO26,   VO27, VO28, VO29, VO30, VO31, VO32, VO33, VO34, VO35, VO36, VO37, VO38, VO39, VO40, VO41, VO42, VO43, VO44, VO45, VO46, VO47, VO48, VE1, VE2, VE3, VE4, VE5, VE6, VE7, VE8, VE9, VE10, VE11, VE12, VE13, VE14, VE15, VE16, VE17, VE18, VE19, VE20, VE21,   VE22, VE23, VE24, VE25, VE26, VE27, VE28, VE29, VE30, VE31, VE32, VE33, VE34, VE35, VE36, VE37, VE38, VE39, VE40, VE41, VE42, VE43, VE44, VE45, VE46, VE47, VE48, PACKS,   VENDAS.NUMERO_ENTREGA,   VENDAS.COLECAO AS COLECAO_VENDA, VENDAS.CODIGO_TAB_PRECO, VENDAS.TIPO, PRODUTOS.TABELA_OPERACOES, PRODUTOS.TABELA_MEDIDAS, PRODUTOS.TIPO_PRODUTO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO,   PRODUTOS.GRADE, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUTOS.CARTELA, PRODUTOS.REFER_FABRICANTE, PRODUTOS.MODELAGEM, PRODUTOS.FABRICANTE, PRODUTOS.ESTILISTA, PRODUTOS.MODELISTA, PRODUTOS.PERIODO_PCP, PRODUTO_CORES.DESC_COR_PRODUTO,   PRODUTO_CORES.COR_SORTIDA, PRODUTO_CORES.STATUS_VENDA_ATUAL,   PRODUTO_CORES.TIPO_LAVAGEM_TINTURARIA, QTDE_ORIGINAL, PRODUTOS.REVENDA, 
PRODUTOS.SORTIMENTO_COR, PRODUTOS.SORTIMENTO_TAMANHO, PRODUTO_CORES.TINTURARIA_LAVAGEM,   PRODUTO_CORES.SORTIMENTO_COR SORTIMENTO, VENDAS.GERENTE, VENDAS.PEDIDO_CLIENTE, VENDAS.PRIORIDADE, VENDAS.APROVACAO, VENDAS.APROVADO_POR, VENDAS.CONDICAO_PGTO, 
COND_ATAC_PGTOS.DESC_COND_PGTO,CLIENTES_ATACADO.CLIFOR, CADASTRO_CLI_FOR.RAZAO_SOCIAL,   CADASTRO_CLI_FOR.CIDADE, CADASTRO_CLI_FOR.UF, CADASTRO_CLI_FOR.PAIS, REGIAO, VENDAS.MOEDA,   VALOR_CANCELADO VALOR_CANCELADO_MOEDA, CONVERT(NUMERIC(14, 2), 
VALOR_CANCELADO*CAMBIO_ATUAL) VALOR_CANCELADO, VALOR_ORIGINAL VALOR_ORIGINAL_MOEDA,   CONVERT(NUMERIC(14, 2), VALOR_ORIGINAL*CAMBIO_ATUAL) VALOR_ORIGINAL, VALOR_ENTREGAR VALOR_ENTREGAR_MOEDA,   CONVERT(NUMERIC(14, 2), VALOR_ENTREGAR*CAMBIO_ATUAL) VALOR_ENTREGAR, 
VALOR_ENTREGUE VALOR_ENTREGUE_MOEDA,   ENTREGUE_MOEDA_PADRAO VALOR_ENTREGUE, VALOR_DEVOLVIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (VENDAS.TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-ISNULL(VENDAS.RECARGO,   0)-VENDAS.VALOR_IPI)=0 THEN 0 
ELSE (VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO)/(VENDAS.TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-ISNULL(VENDAS.RECARGO, 0)-VENDAS.VALOR_IPI)*100 END) DESCONTO_NO_TOTAL,     CONVERT(NUMERIC(14, 2), CASE WHEN 
(VENDAS.TOT_VALOR_ORIGINAL-VENDAS.ENCARGO+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-ISNULL(VENDAS.RECARGO,   0)-VENDAS.VALOR_IPI)=0 THEN 0 ELSE VENDAS.ENCARGO/(VENDAS.TOT_VALOR_ORIGINAL-VENDAS.ENCARGO+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-ISNULL(VENDAS.RECARGO, 
0)-VENDAS.VALOR_IPI)*100 END) ENCARGO_NO_TOTAL,   CONVERT(NUMERIC(14, 2),   CASE WHEN (VENDAS.TOT_VALOR_ORIGINAL-ISNULL(VENDAS.RECARGO, 0)-VENDAS.VALOR_IPI)=0 THEN 0 ELSE ISNULL(VENDAS.RECARGO, 0)/(VENDAS.TOT_VALOR_ORIGINAL-ISNULL(VENDAS.RECARGO, 
0)-VENDAS.VALOR_IPI)*100 END) RECARGO_NO_TOTAL,   CONVERT(NUMERIC(14, 2),   CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ENTREGAR ELSE (VALOR_ENTREGAR-(VALOR_ENTREGAR*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ENTREGAR*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_ENTREGAR*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ENTREGAR*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ENTREGAR)*IPI)/100) END) VALOR_ENTREGAR_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ENTREGAR ELSE (VALOR_ENTREGAR-(VALOR_ENTREGAR*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ENTREGAR*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_ENTREGAR*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ENTREGAR*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ENTREGAR)*IPI)/100) END*CAMBIO_ATUAL) VALOR_ENTREGAR_LIQUIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ORIGINAL ELSE (VALOR_ORIGINAL-(VALOR_ORIGINAL*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-(VALOR_ORIGINAL*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_ORIGINAL*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ORIGINAL*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ORIGINAL)*IPI)/100) 
END) VALOR_ORIGINAL_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_ORIGINAL ELSE 
(VALOR_ORIGINAL-(VALOR_ORIGINAL*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))-(VALOR_ORIGINAL*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_ORIGINAL*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_ORIGINAL*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_ORIGINAL)*IPI)/100) 
END*CAMBIO_ATUAL) VALOR_ORIGINAL_LIQUIDO,   CONVERT(NUMERIC(14, 2), CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_CANCELADO ELSE 
(VALOR_CANCELADO-(VALOR_CANCELADO*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))-(VALOR_CANCELADO*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   
0))))+(VALOR_CANCELADO*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_CANCELADO*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_CANCELADO)*IPI)/100) 
END) VALOR_CANCELADO_LIQUIDO_MOEDA,   CONVERT(NUMERIC(14, 2), 
CASE WHEN (TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VENDAS.VALOR_IPI-ISNULL(VENDAS.RECARGO,   0))=0 THEN VALOR_CANCELADO ELSE (VALOR_CANCELADO-(VALOR_CANCELADO*(VENDAS.DESCONTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+
VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))-
(VALOR_CANCELADO*(VENDAS.DESCONTO_COND_PGTO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO,   0))))+(VALOR_CANCELADO*(VENDAS.ENCARGO/(TOT_VALOR_ORIGINAL+VENDAS.DESCONTO+VENDAS.DESCONTO_COND_PGTO-
VENDAS.ENCARGO-VALOR_IPI-ISNULL(RECARGO, 0))))+(VALOR_CANCELADO*(ISNULL(RECARGO, 0)/(TOT_VALOR_ORIGINAL-VALOR_IPI-ISNULL(RECARGO,   0)))))+(((VALOR_CANCELADO)*IPI)/100) END*CAMBIO_ATUAL) VALOR_CANCELADO_LIQUIDO,   VENDAS_PRODUTO.ID_MODIFICACAO, 
MODIFICACAO_FICHA_TECNICA.DESC_MODIFICACAO, VENDAS_PRODUTO.DESC_VENDA_CLIENTE, VENDAS.INDICADOR_VENDA,  CLIENTES_ATACADO.MATRIZ_CLIENTE    FROM    VENDAS    JOIN VENDAS_PRODUTO ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO    
JOIN PRODUTOS ON VENDAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO    
JOIN PRODUTO_CORES ON VENDAS_PRODUTO.PRODUTO = PRODUTO_CORES.PRODUTO   AND VENDAS_PRODUTO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO    
JOIN COND_ATAC_PGTOS ON VENDAS.CONDICAO_PGTO = COND_ATAC_PGTOS.CONDICAO_PGTO    
JOIN CLIENTES_ATACADO ON VENDAS.CLIENTE_ATACADO = CLIENTES_ATACADO.CLIENTE_ATACADO    
JOIN CADASTRO_CLI_FOR   ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR    
JOIN W_MOEDAS_CONVERSAO ON VENDAS.MOEDA = W_MOEDAS_CONVERSAO.MOEDA    
LEFT JOIN MODIFICACAO_FICHA_TECNICA ON VENDAS_PRODUTO.ID_MODIFICACAO =   MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO    
WHERE ENTREGA >= '20170303' AND ENTREGA <= '20170831' and 
(VENDAS.TOT_QTDE_ENTREGAR > '0' AND VENDAS.FILIAL = 'D.R. LINGERIE') and 
(( ( ( PRODUTOS.PRODUTO IN ('40714') and produto_cores.COR_PRODUTO ='012' and  
produtos.INATIVO = CAST(0 AS BIT) ) ))) AND VENDAS.APROVACAO = 'A'
) AS VENDAS_PROD_ANALITICO
LEFT JOIN ( 
SELECT PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, 
PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, 
PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, 
PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, 
PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_TAREFAS_SALDO.S13, 
PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16, 
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO, PRODUCAO_TAREFAS.INICIO_PREVISTO, 
PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_ATUALIZADO, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, 
PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, 
PRODUCAO_ORDEM.PREVISAO_FIM, PRODUCAO_ORDEM.PROGRAMACAO, PRODUCAO_ORDEM.TIPO_ORDEM_PRODUCAO, PRODUTOS.GRADE, 
PRODUCAO_TAREFAS.FASE_PRODUCAO FROM  DBO.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, DBO.PRODUTOS PRODUTOS, 
DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, DBO.PRODUCAO_ORDEM PRODUCAO_ORDEM, DBO.PRODUCAO_ORDEM_COR PRODUCAO_ORDEM_COR, 
DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, DBO.PRODUCAO_SETOR PRODUCAO_SETOR 
WHERE ((((((((PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND  
PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO ) AND  
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO ) AND  
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO ) AND 
PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO ) AND  
PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO )  AND PRODUCAO_ORDEM.FILIAL='D.R. LINGERIE' AND PRODUCAO_TAREFAS_SALDO.QTDE_S >0 AND PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0 )  AS PRODUCAO_TAREFAS_SALDO 
ON PRODUCAO_TAREFAS_SALDO.PRODUTO=VENDAS_PROD_ANALITICO.PRODUTO AND PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=VENDAS_PROD_ANALITICO.COR_PRODUTO 
JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS.FASE_PRODUCAO=PRODUCAO_TAREFAS_SALDO.FASE_PRODUCAO AND PRODUCAO_TAREFAS.ORDEM_PRODUCAO=PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO 
ORDER BY VENDAS_PROD_ANALITICO.PRODUTO,VENDAS_PROD_ANALITICO.COR_PRODUTO,PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA desc,PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO





SELECT * FROM (
SELECT PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, 
PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, 
PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, 
PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, 
PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_TAREFAS_SALDO.S13, 
PRODUCAO_TAREFAS_SALDO.S14, PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16, 
PRODUCAO_TAREFAS_SALDO.ULTIMO_CUSTO_PREVISTO, PRODUCAO_TAREFAS.INICIO_PREVISTO, 
PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_ATUALIZADO, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, 
PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, 
PRODUCAO_ORDEM.PREVISAO_FIM, PRODUCAO_ORDEM.PROGRAMACAO, PRODUCAO_ORDEM.TIPO_ORDEM_PRODUCAO, PRODUTOS.GRADE, 
PRODUCAO_TAREFAS.FASE_PRODUCAO FROM  DBO.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, DBO.PRODUTOS PRODUTOS, 
DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, DBO.PRODUCAO_ORDEM PRODUCAO_ORDEM, DBO.PRODUCAO_ORDEM_COR PRODUCAO_ORDEM_COR, 
DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, DBO.PRODUCAO_SETOR PRODUCAO_SETOR 
WHERE ((((((((PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND  
PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO ) AND  
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO ) AND  
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO ) AND 
PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO ) AND  
PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO ) AND  
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO )  AND PRODUCAO_ORDEM.FILIAL='D.R. LINGERIE' AND PRODUCAO_TAREFAS_SALDO.QTDE_S >0 AND PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0 )  AS PRODUCAO_TAREFAS_SALDO 
JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS.FASE_PRODUCAO=PRODUCAO_TAREFAS_SALDO.FASE_PRODUCAO AND PRODUCAO_TAREFAS.ORDEM_PRODUCAO=PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO 
where produto='40714'
ORDER BY PRODUCAO_TAREFAS_SALDO.PRODUTO,PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA desc,PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO
