SELECT FILIAL='', FATURAMENTO_ITEM.NF_SAIDA, FATURAMENTO_ITEM.SERIE_NF, ITEM_IMPRESSAO=CAST('000' AS INT) + ROW_NUMBER() OVER(ORDER BY ITEM_IMPRESSAO),
FATURAMENTO_ITEM.SUB_ITEM_TAMANHO, FATURAMENTO_ITEM.DESCRICAO_ITEM, 
QTDE_ITEM = (FATURAMENTO_ITEM.QTDE_ITEM/c.qtde_total)*60 , FATURAMENTO_ITEM.CODIGO_ITEM, FATURAMENTO_ITEM.COD_TABELA_FILHA, TRIBUT_ICMS='', 
FATURAMENTO_ITEM.TRIBUT_ORIGEM, FATURAMENTO_ITEM.UNIDADE, VALOR_ITEM = ROUND((FATURAMENTO_ITEM.PRECO_UNITARIO * ((FATURAMENTO_ITEM.QTDE_ITEM/c.qtde_total) * 60)),2), FATURAMENTO_ITEM.CLASSIF_FISCAL,
FATURAMENTO_ITEM.PRECO_UNITARIO, FATURAMENTO_ITEM.PORCENTAGEM_ITEM_RATEIO, 
CODIGO_FISCAL_OPERACAO='1902', FATURAMENTO_ITEM.DESCONTO_ITEM, FATURAMENTO_ITEM.PESO, FATURAMENTO_ITEM.CONTA_CONTABIL, 
QTDE_RETORNAR_BENEFICIAMENTO = (FATURAMENTO_ITEM.QTDE_ITEM/c.qtde_total)*60, FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO, FATURAMENTO_ITEM.MPADRAO_DESCONTO_ITEM, 
MPADRAO_VALOR_ITEM = ROUND((FATURAMENTO_ITEM.PRECO_UNITARIO * ((FATURAMENTO_ITEM.QTDE_ITEM/c.qtde_total) * 60)),2), FATURAMENTO_ITEM.FAIXA, FATURAMENTO_ITEM.COMISSAO_ITEM, FATURAMENTO_ITEM.COMISSAO_ITEM_GERENTE, 
FATURAMENTO_ITEM.INDICADOR_CFOP, FATURAMENTO_ITEM.QTDE_DEVOLVIDA, ID_EXCECAO_IMPOSTO='', FATURAMENTO_ITEM.REFERENCIA, FATURAMENTO_ITEM.REFERENCIA_ITEM, 
FATURAMENTO_ITEM.REFERENCIA_PEDIDO, CTB_LX_INDICADOR_CFOP.DESCRICAO_INDICADOR_CFOP, TRIBUT_ORIGEM_DESCRICAO=TRIBUT_ORIGEM.DESCRICAO, TRIBUT_ICMS_DESCRICAO=  TRIBUT_ICMS.DESCRICAO, 
CTB_CONTA_PLANO.DESC_CONTA, CLASSIF_FISCAL.DESC_CLASSIFICACAO, CONVERT(BIT, 0) AS GERAR_IMPOSTO, ISNULL(FATURAMENTO_ITEM.MPADRAO_VALOR_ENCARGOS, 0)  AS MPADRAO_VALOR_ENCARGOS, 
ISNULL(FATURAMENTO_ITEM.MPADRAO_VALOR_DESCONTOS, 0) AS MPADRAO_VALOR_DESCONTOS, ISNULL(FATURAMENTO_ITEM.NAO_SOMA_VALOR, 0) AS NAO_SOMA_VALOR, CONVERT(BIT, 0) AS POSSUI_SUBS_TRIBUTARIA, 
CASE WHEN (FATURAMENTO_ITEM.PRECO_UNITARIO + FATURAMENTO_ITEM.DESCONTO_ITEM) = 0 THEN 0  ELSE CONVERT(NUMERIC(8, 4), (FATURAMENTO_ITEM.DESCONTO_ITEM / (FATURAMENTO_ITEM.PRECO_UNITARIO + 
FATURAMENTO_ITEM.DESCONTO_ITEM)) * 100) END PORC_DESCONTO_ITEM, CONVERT(NUMERIC(14, 2), FATURAMENTO_ITEM.PRECO_UNITARIO  + FATURAMENTO_ITEM.DESCONTO_ITEM) AS PRECO_BRUTO, 
CONVERT(NUMERIC(14, 2), FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO + FATURAMENTO_ITEM.MPADRAO_DESCONTO_ITEM) AS MPADRAO_PRECO_BRUTO, FATURAMENTO_ITEM.OBS_ITEM, CADASTRO_ITEM_FISCAL.ITEM_FISCAL_GRUPO, 
CADASTRO_ITEM_GRUPO.DESC_ITEM_FISCAL_GRUPO, FATURAMENTO_ITEM.ITEM_NFE, FIMP.NAO_FATURA, FATURAMENTO_ITEM.MPADRAO_SEGURO_ITEM, FATURAMENTO_ITEM.MPADRAO_FRETE_ITEM, FATURAMENTO_ITEM.MPADRAO_ENCARGO_ITEM, 
CTB_FILIAL_RATEIO.RATEIO_FILIAL, FATURAMENTO_ITEM.RATEIO_CENTRO_CUSTO, CTB_FILIAL_RATEIO.DESC_RATEIO_FILIAL, CTB_CENTRO_CUSTO_RATEIO.DESC_RATEIO_CENTRO_CUSTO, FATURAMENTO_ITEM.ORIGEM_ITEM, 
FATURAMENTO_ITEM.VALOR_IMPOSTO_ITEM, FATURAMENTO_ITEM.PRECO_UNITARIO_ORIGINAL, FATURAMENTO_ITEM.CODIGO_FCI,           
FATURAMENTO_ITEM.ID_SUB_PROJETO, AF_SUB_PROJETO.NOME_SUB_PROJETO, CASE  WHEN FATURAMENTO_ITEM.ORIGEM_ITEM='P' THEN PRODUTOS.TIPO_ITEM_SPED  WHEN FATURAMENTO_ITEM.ORIGEM_ITEM='M' THEN MATERIAIS.TIPO_ITEM_SPED 
 WHEN FATURAMENTO_ITEM.ORIGEM_ITEM='I' THEN CADASTRO_ITEM_FISCAL.TIPO_ITEM_SPED END TIPO_ITEM_SPED, FATURAMENTO_ITEM.VALOR_IMPOSTO_ITEM_MUNICIPAL, FATURAMENTO_ITEM.VALOR_IMPOSTO_ITEM_ESTADUAL, 
FATURAMENTO_ITEM.ID_CEST_NCM, TABELA_LX_CEST.DESCRICAO FROM      FATURAMENTO_ITEM  JOIN      TRIBUT_ICMS ON        FATURAMENTO_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS JOIN      TRIBUT_ORIGEM ON       
FATURAMENTO_ITEM.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM JOIN      CTB_LX_INDICADOR_CFOP  ON        FATURAMENTO_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP JOIN      CLASSIF_FISCAL ON  
FATURAMENTO_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL LEFT JOIN CTB_CONTA_PLANO ON        FATURAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL 
LEFT JOIN CADASTRO_ITEM_FISCAL ON  ( CADASTRO_ITEM_FISCAL.CODIGO_ITEM=FATURAMENTO_ITEM.CODIGO_ITEM) LEFT JOIN CADASTRO_ITEM_GRUPO ON ( CADASTRO_ITEM_GRUPO.ITEM_FISCAL_GRUPO=CADASTRO_ITEM_FISCAL.ITEM_FISCAL_GRUPO) 
LEFT JOIN CTB_EXCECAO_IMPOSTO AS FIMP ON        ( FATURAMENTO_ITEM.ID_EXCECAO_IMPOSTO= FIMP.ID_EXCECAO_IMPOSTO) LEFT JOIN CTB_FILIAL_RATEIO ON        '' = 
CTB_FILIAL_RATEIO.RATEIO_FILIAL LEFT JOIN CTB_CENTRO_CUSTO_RATEIO ON        FATURAMENTO_ITEM.RATEIO_CENTRO_CUSTO = CTB_CENTRO_CUSTO_RATEIO.RATEIO_CENTRO_CUSTO 
LEFT JOIN AF_SUB_PROJETO ON        AF_SUB_PROJETO.ID_SUB_PROJETO = FATURAMENTO_ITEM.ID_SUB_PROJETO LEFT JOIN PRODUTOS ON        PRODUTOS.PRODUTO=FATURAMENTO_ITEM.REFERENCIA LEFT JOIN MATERIAIS ON 
MATERIAIS.MATERIAL=FATURAMENTO_ITEM.REFERENCIA LEFT JOIN CEST_NCM ON		  CEST_NCM.ID=FATURAMENTO_ITEM.ID_CEST_NCM LEFT JOIN TABELA_LX_CEST ON		  TABELA_LX_CEST.ID = CEST_NCM.ID_CEST 
JOIN (select distinct nf_saida,serie_nf,material,ORDEM_PRODUCAO from estoque_sai1_mat with (nolock) where NF_SAIDA is not null and ORDEM_PRODUCAO is not null ) b on b.NF_SAIDA=FATURAMENTO_ITEM.NF_SAIDA 
and b.SERIE_NF=FATURAMENTO_ITEM.SERIE_NF and b.MATERIAL=FATURAMENTO_ITEM.CODIGO_ITEM 
JOIN producao_ordem c on c.ordem_producao=b.ordem_producao WHERE c.ORDEM_PRODUCAO='232506' AND FATURAMENTO_ITEM.COD_TABELA_FILHA='M' 