DECLARE @ITEM INT, @TOTAL_ITEM INT
SET @ITEM = 0
SET @TOTAL_ITEM = 0

SELECT PEDIDO,PRODUTO,
TOTAL_ITEM=SUM(QTDE_ITEM1+QTDE_ITEM2+QTDE_ITEM3+QTDE_ITEM4+QTDE_ITEM5+ 
QTDE_ITEM6+QTDE_ITEM7+QTDE_ITEM8+QTDE_ITEM9+QTDE_ITEM10+QTDE_ITEM11+QTDE_ITEM12)
FROM (
select PEDIDO,PRODUTO,COR_PRODUTO,
QTDE_ITEM1 = 
    ( CASE WHEN (VO1  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM2 = 
    ( CASE WHEN (VO2  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM3 = 
    ( CASE WHEN (VO3  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM4 = 
    ( CASE WHEN (VO4  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM5 = 
    ( CASE WHEN (VO5  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM6 = 
    ( CASE WHEN (VO6  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM7 = 
    ( CASE WHEN (VO7  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM8 = 
    ( CASE WHEN (VO8  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM9 = 
    ( CASE WHEN (VO9  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM10 = 
    ( CASE WHEN (VO10  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM11 = 
    ( CASE WHEN (VO11  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END),
QTDE_ITEM12 = 
    ( CASE WHEN (VO12  > 0) THEN (@ITEM + 1) ELSE (@ITEM) END)
   
from VENDAS_PRODUTO
WHERE PEDIDO IN ('580841')
--WHERE PEDIDO IN ('576550')
) AS PEDIDOS
GROUP BY PEDIDO,PRODUTO




