SELECT distinct VENDAS_PRODUTO.PEDIDO FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO=VENDAS_PRODUTO.PEDIDO
JOIN PRODUTOS ON PRODUTOS.PRODUTO=VENDAS_PRODUTO.PRODUTO
WHERE ENTREGA<='20150228' AND QTDE_ENTREGAR>0 AND VENDAS.OBS LIKE '%ENCABIDADO%' AND PRODUTOS.GRUPO_PRODUTO='CUECA'