SELECT TOP 50 VENDAS.GERENTE,VENDAS.REPRESENTANTE,PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
VENDAS.EMISSAO,
VENDAS_PRODUTO.ENTREGA,                     
VENDAS_PRODUTO.LIMITE_ENTREGA,                     
QTDE_ORIGINAL= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.Vo1 
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.Vo2 
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.Vo3 
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.Vo4 
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.Vo5 
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.Vo6 
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.Vo7 
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.Vo8 
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.Vo9 
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.Vo10 
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.Vo11 
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.Vo12 
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.Vo13 
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.Vo14 
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.Vo15 
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.Vo16 
                     END),
QTDE_ENTREGAR= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VE1 
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VE2 
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VE3 
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VE4 
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VE5 
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VE6 
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VE7 
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VE8 
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VE9 
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VE10 
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VE11 
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VE12 
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VE13 
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VE14 
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VE15 
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VE16 
                     END)
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
LEFT JOIN (SELECT * FROM VENDAS_PRODUTO) AS VENDAS_PRODUTO
  ON VENDAS_PRODUTO.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND VENDAS_PRODUTO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO  
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND VENDAS.TIPO = 'BRINDE'
ORDER BY QTDE_ORIGINAL DESC



SELECT PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO,PRODUCAO_TAREFAS_SALDO.PRODUTO,PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,PRODUTOS_BARRA.GRADE,PRODUTOS_BARRA.TAMANHO,
QTDE_S = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN PRODUCAO_TAREFAS_SALDO.S1 
               WHEN PRODUTOS_BARRA.tamanho='2'  THEN PRODUCAO_TAREFAS_SALDO.S2 
               WHEN PRODUTOS_BARRA.tamanho='3'  THEN PRODUCAO_TAREFAS_SALDO.S3 
               WHEN PRODUTOS_BARRA.tamanho='4'  THEN PRODUCAO_TAREFAS_SALDO.S4 
               WHEN PRODUTOS_BARRA.tamanho='5'  THEN PRODUCAO_TAREFAS_SALDO.S5 
               WHEN PRODUTOS_BARRA.tamanho='6'  THEN PRODUCAO_TAREFAS_SALDO.S6 
               WHEN PRODUTOS_BARRA.tamanho='7'  THEN PRODUCAO_TAREFAS_SALDO.S7 
               WHEN PRODUTOS_BARRA.tamanho='8'  THEN PRODUCAO_TAREFAS_SALDO.S8 
               WHEN PRODUTOS_BARRA.tamanho='9'  THEN PRODUCAO_TAREFAS_SALDO.S9 
               WHEN PRODUTOS_BARRA.tamanho='10' THEN PRODUCAO_TAREFAS_SALDO.S10 
               WHEN PRODUTOS_BARRA.tamanho='11' THEN PRODUCAO_TAREFAS_SALDO.S11 
               WHEN PRODUTOS_BARRA.tamanho='12' THEN PRODUCAO_TAREFAS_SALDO.S12 
               WHEN PRODUTOS_BARRA.tamanho='13' THEN PRODUCAO_TAREFAS_SALDO.S13 
               WHEN PRODUTOS_BARRA.tamanho='14' THEN PRODUCAO_TAREFAS_SALDO.S14 
               WHEN PRODUTOS_BARRA.tamanho='15' THEN PRODUCAO_TAREFAS_SALDO.S15 
               WHEN PRODUTOS_BARRA.tamanho='16' THEN PRODUCAO_TAREFAS_SALDO.S16 
           END)
FROM PRODUTOS_BARRA
join PRODUCAO_TAREFAS_SALDO on PRODUCAO_TAREFAS_SALDO.PRODUTO=PRODUTOS_BARRA.PRODUTO and
	 PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO
	  
WHERE CODIGO_BARRA_PADRAO=1 AND PRODUCAO_TAREFAS_SALDO.PRODUTO='1233' AND ORDEM_PRODUCAO='58817'
ORDER BY 1



SELECT * FROM PRODUCAO_TAREFAS_SALDO
WHERE ORDEM_PRODUCAO='58817'

