--- custo operacao extra
exec sp_executesql N'
/* lx040004  CursorAdapter: cur_v_produtos_00_ope_extra(Alias: v_produtos_00_ope_extra)  */
SELECT PRODUTOS_OPE_EXTRA.PRODUTO, PRODUTOS_OPE_EXTRA.OPERACAO_EXTRA, PRODUTOS_OPE_EXTRA.SEQUENCIA, PRODUTOS_OPE_EXTRA.TEMPO_HORAS, PRODUTOS_OPE_EXTRA.CUSTO_OPERACAO 
FROM PRODUTOS_OPE_EXTRA 
WHERE PRODUTOS_OPE_EXTRA.PRODUTO = @P1',N'@P1 varchar(4)','1233'

--- custo operacao
exec sp_executesql N'
/* VISUALLINX Execute(Alias:vTmpCusto)  */
 SELECT * FROM PRODUTO_OPERACOES_ROTAS,PRODUCAO_FASE,PRODUCAO_SETOR,PRODUCAO_RECURSOS  
 WHERE TABELA_OPERACOES = @P1 and  PRODUTO_OPERACOES_ROTAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO AND  
 PRODUTO_OPERACOES_ROTAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND   
 PRODUTO_OPERACOES_ROTAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO AND  
 PRODUTO_OPERACOES_ROTAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO  and 
 PRODUTO_OPERACOES_ROTAS.fase_producao=@P2  and
 PRODUTO_OPERACOES_ROTAS.SETOR_PARALELO_NUMERO =@P4  
 ORDER BY PRODUTO_OPERACOES_ROTAS.SEQUENCIA_PRODUTIVA,  PRODUTO_OPERACOES_ROTAS.SETOR_PARALELO_NUMERO, PRODUTO_OPERACOES_ROTAS.FASE_PRODUCAO,  PRODUTO_OPERACOES_ROTAS.SETOR_PRODUCAO, PRODUTO_OPERACOES_ROTAS.RECURSO_PRODUTIVO ',N'@P1 varchar(4),@P2 varchar(3),@P3 varchar(7),@P4 varchar(1)','1233','007','','0'


exec sp_executesql N'
/* lx040004  CursorAdapter: cur_v_produtos_00_custo(Alias: v_produtos_00_custo)  */
SELECT DISTINCT PRODUTOS_FICHA.PRODUTO, PRODUTOS_FICHA_COR.COR_PRODUTO, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTOS_FICHA.ITEM, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, 
W_MATERIAIS_CORES.DESC_MATERIAL, PRODUTOS_FICHA_COR.COR_MATERIAL, W_MATERIAIS_CORES.DESC_COR_MATERIAL, W_MATERIAIS_CORES.UNID_FICHA_TEC, W_MATERIAIS_CORES.FATOR_CONVERSAO, 
W_MATERIAIS_CORES.UNID_ESTOQUE, PRODUTOS_FICHA.CONSUMO_P_TAMANHO, PRODUTOS_FICHA_COR.PORCENTAGEM_CONSUMO, W_MATERIAIS_CORES.CUSTO_A_VISTA_COR, PRODUTOS_FICHA.MATERIAL_PRINCIPAL, 
W_MATERIAIS_CORES.VARIA_CUSTO_COR, PRODUTOS_FICHA.DESC_USO_MATERIAL, PRODUTOS_FICHA.C1, PRODUTOS_FICHA.C2, PRODUTOS_FICHA.C3, PRODUTOS_FICHA.C4, PRODUTOS_FICHA.C5, PRODUTOS_FICHA.C6, 
PRODUTOS_FICHA.C7, PRODUTOS_FICHA.C8, PRODUTOS_FICHA.C9, PRODUTOS_FICHA.C10, PRODUTOS_FICHA.C11, PRODUTOS_FICHA.C12, PRODUTOS_FICHA.C13, PRODUTOS_FICHA.C14, PRODUTOS_FICHA.C15, 
PRODUTOS_FICHA.C16, 0 AS C17, 0 AS C18, 0 AS C19, 0 AS C20, 0 AS C21, 0 AS C22, 0 AS C23, 0 AS C24, 0 AS C25, 0 AS C26, 0 AS C27, 0 AS C28, 0 AS C29, 0 AS C30, 0 AS C31, 0 AS C32, 0 AS 
C33, 0 AS C34, 0 AS C35, 0 AS C36, 0 AS C37, 0 AS C38, 0 AS C39, 0 AS C40, 0 AS C41, 0 AS C42, 0 AS C43, 0 AS C44, 0 AS C45, 0 AS C46, 0 AS C47, 0 AS C48, W_MATERIAIS_CORES.TIPO, PRODUTOS_FICHA.FASE_PRODUCAO, PRODUTOS_FICHA.SETOR_PRODUCAO, W_MATERIAIS_CORES.FABRICANTE, W_MATERIAIS_CORES.COLECAO, W_MATERIAIS_CORES.SUBGRUPO, W_MATERIAIS_CORES.COMPRIMENTO, W_MATERIAIS_CORES.REVENDA, W_MATERIAIS_CORES.VARIA_MATERIAL_TAMANHO, W_MATERIAIS_CORES.LARGURA, W_MATERIAIS_CORES.DATA_REPOSICAO, W_MATERIAIS_CORES.REF_FABRICANTE, W_MATERIAIS_CORES.ICMS_CUSTOS, W_MATERIAIS_CORES.TAXA_JUROS_CUSTO, W_MATERIAIS_CORES.REFER_FABRICANTE, W_MATERIAIS_CORES.CUSTO_REPOSICAO_COR, MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO, CONVERT(NUMERIC(14,3),0.000) AS CONSUMO_BASE, CONVERT(NUMERIC(14,5),0.00000) AS VALOR, PRODUTO_CORES.PRECO_REPOSICAO_1, PRODUTO_CORES.PRECO_REPOSICAO_2, PRODUTO_CORES.PRECO_REPOSICAO_3, PRODUTO_CORES.PRECO_REPOSICAO_4, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_1, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_2, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_3, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_4 FROM PRODUTOS_FICHA INNER JOIN PRODUTOS_FICHA_COR ON PRODUTOS_FICHA.ITEM = PRODUTOS_FICHA_COR.ITEM AND PRODUTOS_FICHA.PRODUTO = PRODUTOS_FICHA_COR.PRODUTO INNER JOIN W_MATERIAIS_CORES ON PRODUTOS_FICHA_COR.MATERIAL = W_MATERIAIS_CORES.MATERIAL AND PRODUTOS_FICHA_COR.COR_MATERIAL = W_MATERIAIS_CORES.COR_MATERIAL INNER JOIN PRODUTO_CORES ON PRODUTOS_FICHA_COR.PRODUTO = PRODUTO_CORES.PRODUTO AND PRODUTOS_FICHA_COR.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO INNER JOIN MATERIAIS_SUBGRUPO ON W_MATERIAIS_CORES.GRUPO = MATERIAIS_SUBGRUPO.GRUPO AND W_MATERIAIS_CORES.SUBGRUPO = MATERIAIS_SUBGRUPO.SUBGRUPO WHERE PRODUTOS_FICHA.PRODUTO = @P1 AND MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO = 0 ORDER BY PRODUTOS_FICHA_COR.COR_PRODUTO, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, PRODUTOS_FICHA_COR.COR_MATERIAL',N'@P1 varchar(5)','42157'



--- custo material
exec sp_executesql N'
/* lx040004  CursorAdapter: cur_v_produtos_00_custo(Alias: v_produtos_00_custo)  */
SELECT DISTINCT PRODUTOS_FICHA.PRODUTO, PRODUTOS_FICHA_COR.COR_PRODUTO, 
PRODUTO_CORES.DESC_COR_PRODUTO, PRODUTOS_FICHA.ITEM, W_MATERIAIS_CORES.GRUPO, 
PRODUTOS_FICHA_COR.MATERIAL, W_MATERIAIS_CORES.DESC_MATERIAL, 
PRODUTOS_FICHA_COR.COR_MATERIAL, W_MATERIAIS_CORES.DESC_COR_MATERIAL, 
W_MATERIAIS_CORES.UNID_FICHA_TEC, W_MATERIAIS_CORES.FATOR_CONVERSAO, 
W_MATERIAIS_CORES.UNID_ESTOQUE, PRODUTOS_FICHA.CONSUMO_P_TAMANHO, 
PRODUTOS_FICHA_COR.PORCENTAGEM_CONSUMO, W_MATERIAIS_CORES.CUSTO_A_VISTA_COR, 
PRODUTOS_FICHA.MATERIAL_PRINCIPAL, W_MATERIAIS_CORES.VARIA_CUSTO_COR, 
PRODUTOS_FICHA.DESC_USO_MATERIAL, PRODUTOS_FICHA.C1, PRODUTOS_FICHA.C2, 
PRODUTOS_FICHA.C3, PRODUTOS_FICHA.C4, PRODUTOS_FICHA.C5, PRODUTOS_FICHA.C6, 
PRODUTOS_FICHA.C7, PRODUTOS_FICHA.C8, PRODUTOS_FICHA.C9, PRODUTOS_FICHA.C10, 
PRODUTOS_FICHA.C11, PRODUTOS_FICHA.C12, PRODUTOS_FICHA.C13, PRODUTOS_FICHA.C14, 
PRODUTOS_FICHA.C15, PRODUTOS_FICHA.C16, 0 AS C17, 0 AS C18, 0 AS C19, 0 AS C20, 
0 AS C21, 0 AS C22, 0 AS C23, 0 AS C24, 0 AS C25, 0 AS C26, 0 AS C27, 0 AS C28, 
0 AS C29, 0 AS C30, 0 AS C31, 0 AS C32, 0 AS C33, 0 AS C34, 0 AS C35, 0 AS C36, 
0 AS C37, 0 AS C38, 0 AS C39, 0 AS C40, 0 AS C41, 0 AS C42, 0 AS C43, 0 AS C44, 
0 AS C45, 0 AS C46, 0 AS C47, 0 AS C48, W_MATERIAIS_CORES.TIPO, 
PRODUTOS_FICHA.FASE_PRODUCAO, PRODUTOS_FICHA.SETOR_PRODUCAO, 
W_MATERIAIS_CORES.FABRICANTE, W_MATERIAIS_CORES.COLECAO, W_MATERIAIS_CORES.SUBGRUPO, 
W_MATERIAIS_CORES.COMPRIMENTO, W_MATERIAIS_CORES.REVENDA, 
W_MATERIAIS_CORES.VARIA_MATERIAL_TAMANHO, W_MATERIAIS_CORES.LARGURA, 
W_MATERIAIS_CORES.DATA_REPOSICAO, W_MATERIAIS_CORES.REF_FABRICANTE, 
W_MATERIAIS_CORES.ICMS_CUSTOS, W_MATERIAIS_CORES.TAXA_JUROS_CUSTO, 
W_MATERIAIS_CORES.REFER_FABRICANTE, W_MATERIAIS_CORES.CUSTO_REPOSICAO_COR, 
MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO, CONVERT(NUMERIC(14,3),0.000) AS CONSUMO_BASE, 
CONVERT(NUMERIC(14,5),0.00000) AS VALOR, PRODUTO_CORES.PRECO_REPOSICAO_1, 
PRODUTO_CORES.PRECO_REPOSICAO_2, PRODUTO_CORES.PRECO_REPOSICAO_3, 
PRODUTO_CORES.PRECO_REPOSICAO_4, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_1, 
PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_2, PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_3, 
PRODUTO_CORES.PRECO_A_VISTA_REPOSICAO_4 

FROM PRODUTOS_FICHA 
INNER JOIN PRODUTOS_FICHA_COR ON PRODUTOS_FICHA.ITEM = PRODUTOS_FICHA_COR.ITEM AND 
PRODUTOS_FICHA.PRODUTO = PRODUTOS_FICHA_COR.PRODUTO 
INNER JOIN W_MATERIAIS_CORES ON PRODUTOS_FICHA_COR.MATERIAL = W_MATERIAIS_CORES.MATERIAL 
AND PRODUTOS_FICHA_COR.COR_MATERIAL = W_MATERIAIS_CORES.COR_MATERIAL 
INNER JOIN PRODUTO_CORES ON PRODUTOS_FICHA_COR.PRODUTO = PRODUTO_CORES.PRODUTO 
AND PRODUTOS_FICHA_COR.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN MATERIAIS_SUBGRUPO ON W_MATERIAIS_CORES.GRUPO = MATERIAIS_SUBGRUPO.GRUPO 
AND W_MATERIAIS_CORES.SUBGRUPO = MATERIAIS_SUBGRUPO.SUBGRUPO 

WHERE PRODUTOS_FICHA.PRODUTO = @P1 AND MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO = 0 
ORDER BY PRODUTOS_FICHA_COR.COR_PRODUTO, W_MATERIAIS_CORES.GRUPO, PRODUTOS_FICHA_COR.MATERIAL, 
PRODUTOS_FICHA_COR.COR_MATERIAL',N'@P1 varchar(4)','42157'


select * from PRODUTOS_FICHA
where PRODUTO='42157'

SELECT CUSTO_MATERIAIS.DESC_PRODUTO,CUSTO_MATERIAIS.PRODUTO,CUSTO_MATERIAIS.COR_PRODUTO,
CUSTO_OPERACAO_EXTRA=W_PRODUTOS_OPE_EXTRA.CUSTO_OPERACAO,
CUSTO_OPERACAO=PRODUTO_OPERACOES_ROTAS.CUSTO_SUGERIDO*(PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOMETRADO+PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOM_FIXO),
CUSTO_MATERIAL=SUM(VALOR),
TOTAL=W_PRODUTOS_OPE_EXTRA.CUSTO_OPERACAO+(PRODUTO_OPERACOES_ROTAS.CUSTO_SUGERIDO*(PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOMETRADO+PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOM_FIXO))+SUM(VALOR)
  FROM (
SELECT DISTINCT PRODUTOS_FICHA.PRODUTO, PRODUTOS_FICHA_COR.COR_PRODUTO, PRODUTO_CORES.DESC_COR_PRODUTO, 
PRODUTOS_FICHA_COR.MATERIAL, W_MATERIAIS_CORES.DESC_MATERIAL,PRODUTOS.DESC_PRODUTO, 
PRODUTOS_FICHA_COR.COR_MATERIAL, W_MATERIAIS_CORES.DESC_COR_MATERIAL, 
CASE PRODUTOS.TAMANHO_BASE 
WHEN 1 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C1/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 2 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C2/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 3 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C3/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 4 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C4/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 5 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C5/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 6 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C6/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 7 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C7/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 8 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C8/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 9 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C9/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR)) 
WHEN 10 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C10/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 11 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C11/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 12 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C12/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 13 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C13/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 14 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C14/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 15 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C15/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))
WHEN 16 THEN CONVERT(NUMERIC(14,5),((PRODUTOS_FICHA.C16/W_MATERIAIS_CORES.FATOR_CONVERSAO)* W_MATERIAIS_CORES.CUSTO_A_VISTA_COR))

END AS VALOR

FROM PRODUTOS_FICHA 
INNER JOIN PRODUTOS_FICHA_COR ON PRODUTOS_FICHA.ITEM = PRODUTOS_FICHA_COR.ITEM AND 
PRODUTOS_FICHA.PRODUTO = PRODUTOS_FICHA_COR.PRODUTO 
INNER JOIN W_MATERIAIS_CORES ON PRODUTOS_FICHA_COR.MATERIAL = W_MATERIAIS_CORES.MATERIAL 
AND PRODUTOS_FICHA_COR.COR_MATERIAL = W_MATERIAIS_CORES.COR_MATERIAL 
INNER JOIN PRODUTO_CORES ON PRODUTOS_FICHA_COR.PRODUTO = PRODUTO_CORES.PRODUTO 
AND PRODUTOS_FICHA_COR.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN MATERIAIS_SUBGRUPO ON W_MATERIAIS_CORES.GRUPO = MATERIAIS_SUBGRUPO.GRUPO 
AND W_MATERIAIS_CORES.SUBGRUPO = MATERIAIS_SUBGRUPO.SUBGRUPO 
INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUTOS_FICHA.PRODUTO

WHERE PRODUTOS_FICHA.PRODUTO = '42157' AND 
MATERIAIS_SUBGRUPO.IGNORAR_EM_FORMACAO_PRECO = 0 
) AS CUSTO_MATERIAIS
INNER JOIN W_PRODUTOS_OPE_EXTRA ON W_PRODUTOS_OPE_EXTRA.PRODUTO=CUSTO_MATERIAIS.PRODUTO
INNER JOIN PRODUTO_OPERACOES_ROTAS ON PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES=CUSTO_MATERIAIS.PRODUTO

WHERE PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES='42157' AND 
PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOMETRADO>0

GROUP BY CUSTO_MATERIAIS.DESC_PRODUTO,CUSTO_MATERIAIS.PRODUTO,CUSTO_MATERIAIS.COR_PRODUTO,
W_PRODUTOS_OPE_EXTRA.CUSTO_OPERACAO,
PRODUTO_OPERACOES_ROTAS.CUSTO_SUGERIDO*(PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOMETRADO+PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOM_FIXO)


alter view w_produtos_ope_extra as
SELECT PRODUTO,CUSTO_OPERACAO=SUM(CUSTO_OPERACAO) FROM PRODUTOS_OPE_EXTRA
group by PRODUTO

select * from PRODUTO_OPERACOES_ROTAS
where PRODUTO_OPERACOES_ROTAS.TEMPO_CRONOMETRADO>0 and PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES='40040'

