-- TABELA PARA INSERT 
select * FROM PRODUTO_SETOR_CUSTO
SELECT * FROM PRODUTO_RECURSO_CUSTO

-- LINHA INDUSTRIAL
SELECT * FROM PRODUTIV_LINHA_INDUSTRIAL

-- O QUE ESTÁ NA FASE
SELECT * FROM PRODUCAO_SETOR
WHERE FASE_PRODUCAO='006'

exec sp_executesql N'INSERT INTO DBO.PRODUTO_SETOR_CUSTO (LINHA_INDUSTRIAL,FASE_PRODUCAO,SETOR_PRODUCAO,UNIDADE_TEMPO) VALUES (@P1 ,@P2 ,@P3 ,@P4 )',N'@P1 varchar(25),@P2 varchar(25),@P3 varchar(25),@P4 varchar(1)','01 - CALCINHA            ','006                      ','RECJULIETE               ','M'
exec sp_executesql N'INSERT INTO DBO.PRODUTO_SETOR_CUSTO (LINHA_INDUSTRIAL,FASE_PRODUCAO,SETOR_PRODUCAO,UNIDADE_TEMPO) VALUES (@P1 ,@P2 ,@P3 ,@P4 )',N'@P1 varchar(25),@P2 varchar(25),@P3 varchar(25),@P4 varchar(1)','10 - ANAGUA              ','006                      ','RECJULIETE               ','M'



