SELECT VENDAS.CLIENTE_ATACADO,VENDAS_PRODUTO.* FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
WHERE QTDE_ENTREGAR > 0 AND 
PRODUTO = '40354' AND COR_PRODUTO LIKE 'NT%' OR  
PRODUTO = '40903' AND COR_PRODUTO LIKE 'PT%' OR
PRODUTO = '40903' AND COR_PRODUTO LIKE 'BC%' OR
PRODUTO = '42153' AND COR_PRODUTO LIKE 'PT%' OR 
PRODUTO = '42164' AND COR_PRODUTO LIKE 'BC%' OR
PRODUTO = '42365' AND COR_PRODUTO LIKE 'PK%' OR
PRODUTO = '42365' AND COR_PRODUTO LIKE 'BC%' OR 
PRODUTO = '42620' AND COR_PRODUTO LIKE 'BC%' OR
PRODUTO = '42620' AND COR_PRODUTO LIKE 'PT%'
ORDER BY PEDIDO, PRODUTO, COR_PRODUTO

SELECT * FROM (
SELECT VENDAS_PRODUTO.PEDIDO,PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO, 
QTDE_ENTREGAR= (CASE  WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VE1 
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VE2
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VE3
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VE4
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VE5
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VE6
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VE7
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VE8
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VE9
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VE10
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VE11
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VE12
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VE13
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VE14
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VE15
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VE16
                     END)
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
JOIN (SELECT * FROM VENDAS_PRODUTO) AS VENDAS_PRODUTO
  ON VENDAS_PRODUTO.PRODUTO=PRODUTOS_BARRA.PRODUTO 
  AND VENDAS_PRODUTO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND PRODUTOS_BARRA.CODIGO_BARRA_PADRAO=1
AND VENDAS_PRODUTO.QTDE_ENTREGAR > 0 AND 
VENDAS_PRODUTO.PRODUTO = '40354' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'NT%' OR  
VENDAS_PRODUTO.PRODUTO = '40903' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'PT%' OR
VENDAS_PRODUTO.PRODUTO = '40903' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'BC%' OR
VENDAS_PRODUTO.PRODUTO = '42153' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'PT%' OR 
VENDAS_PRODUTO.PRODUTO = '42164' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'BC%' OR
VENDAS_PRODUTO.PRODUTO = '42365' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'PK%' OR
VENDAS_PRODUTO.PRODUTO = '42365' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'BC%' OR 
VENDAS_PRODUTO.PRODUTO = '42620' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'BC%' OR
VENDAS_PRODUTO.PRODUTO = '42620' AND VENDAS_PRODUTO.COR_PRODUTO LIKE 'PT%'
) AS FINAL
WHERE QTDE_ENTREGAR>0
