SELECT REPRESENTANTE,GERENTE,PEDIDO,PRODUTO,COR_PRODUTO,GRADE,QTDE_TAM FROM (
SELECT B.PEDIDO,A.REPRESENTANTE,A.GERENTE,B.PRODUTO,B.COR_PRODUTO,D.GRADE,
QTDE_TAM=(CASE WHEN D.tamanho='1'  THEN B.F1
               WHEN D.tamanho='2'  THEN B.F2
               WHEN D.tamanho='3'  THEN B.F3
               WHEN D.tamanho='4'  THEN B.F4
               WHEN D.tamanho='5'  THEN B.F5
               WHEN D.tamanho='6'  THEN B.F6
               WHEN D.tamanho='7'  THEN B.F7
               WHEN D.tamanho='8'  THEN B.F8
               WHEN D.tamanho='9'  THEN B.F9
               WHEN D.tamanho='10'  THEN B.F10
               WHEN D.tamanho='11'  THEN B.F11
               WHEN D.tamanho='12'  THEN B.F12
               WHEN D.tamanho='13'  THEN B.F13
               WHEN D.tamanho='14'  THEN B.F14
               WHEN D.tamanho='15'  THEN B.F15
               WHEN D.tamanho='16'  THEN B.F16
           END),
B.PRECO 
FROM FATURAMENTO A WITH (NOLOCK)  
JOIN FATURAMENTO_PROD B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND A.FILIAL='DR VAREJO' 
JOIN CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.NOME_CLIFOR=A.NOME_CLIFOR 
JOIN PRODUTOS_BARRA D WITH (NOLOCK) ON D.PRODUTO = B.PRODUTO AND D.COR_PRODUTO = B.COR_PRODUTO
WHERE A.NF_SAIDA='029019' AND A.SERIE_NF = '2' AND D.CODIGO_BARRA_PADRAO=1
) AS PRODUTOS_DEVOLUCAO
WHERE QTDE_TAM>0
ORDER BY PRODUTO, COR_PRODUTO, GRADE 
