exec sp_executesql N'
/* lx100106spk  CursorAdapter: CUR_V_FATURAMENTO_05_ENT_DEV_MP_SEL(Alias: v_faturamento_05_ent_dev_mp_sel)  */
SELECT ENTRADAS.FILIAL,ENTRADAS.NOME_CLIFOR, ENTRADAS.NF_ENTRADA, ENTRADAS.SERIE_NF_ENTRADA, ENTRADAS_ITEM.ITEM_IMPRESSAO AS ITEM_IMPRESSAO_ENTRADA , ENTRADAS_ITEM.SUB_ITEM_TAMANHO AS SUB_ITEM_ENTRADA, 
ORIGEM_ENTRADA_SAIDA=''S'',   QTDE_DEVOLVIDA = ESTOQUE_RET1_MAT.QTDE,  ENTRADAS.EMISSAO, ENTRADAS_ITEM.CODIGO_ITEM, ENTRADAS_ITEM.REFERENCIA, ENTRADAS_ITEM.REFERENCIA_ITEM, ENTRADAS_ITEM.DESCRICAO_ITEM, 
ENTRADAS_ITEM.DESCRICAO_ITEM DESC_REFERENCIA,     CONVERT(NUMERIC(17,5), (((ENTRADAS_ITEM.PRECO_UNITARIO-ENTRADAS_ITEM.DESCONTO_ITEM)/ESTOQUE_RET1_MAT.FATOR_CONVERSAO_UNIDADE)/ENTRADAS.CAMBIO_NA_DATA)) AS PRECO_UNITARIO,   
((ENTRADAS_ITEM.PRECO_UNITARIO-ENTRADAS_ITEM.DESCONTO_ITEM)/ENTRADAS.CAMBIO_NA_DATA) AS PRECO, ENTRADAS_ITEM.DESCONTO_ITEM,   ENTRADAS_ITEM.UNIDADE, VALOR = (ESTOQUE_RET1_MAT.QTDE * 
(CONVERT(NUMERIC(17,5),(((ENTRADAS_ITEM.PRECO_UNITARIO-ENTRADAS_ITEM.DESCONTO_ITEM)/ESTOQUE_RET1_MAT.FATOR_CONVERSAO_UNIDADE)/ENTRADAS.CAMBIO_NA_DATA)))),   ENTRADAS_ITEM.CLASSIF_FISCAL,  ENTRADAS_ITEM.TRIBUT_ORIGEM, 
ENTRADAS_ITEM.TRIBUT_ORIGEM,   ENTRADAS_ITEM.CONTA_CONTABIL, ENTRADAS_ITEM.INDICADOR_CFOP, ENTRADAS_ITEM.TRIBUT_ICMS,  ENTRADAS.RECEBIMENTO, CASE WHEN RTRIM(ISNULL(ENTRADAS_ITEM.TIMESTAMP,'''')) = '''' THEN '''' ELSE 
DBO.FX_PRODUCAO_PRECO(CONVERT(NUMERIC(16,2),DBO.FX_PRODUCAO_PRECO(ENTRADAS_ITEM.TIMESTAMP,''F''))/ENTRADAS.CAMBIO_NA_DATA,''T'') END TIMESTAMP, TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO,  TRIBUT_ORIGEM.DESCRICAO AS 
TRIBUT_ORIGEM_DESCRICAO,  CTB_CONTA_PLANO.DESC_CONTA, CLASSIF_FISCAL.DESC_CLASSIFICACAO,   CTB_LX_INDICADOR_CFOP.DESCRICAO_INDICADOR_CFOP, CONVERT(BIT,1) AS GERAR_ITEM, ENTRADAS_ITEM.CODIGO_FISCAL_OPERACAO,''M'' AS 
COD_TABELA_FILHA, ENTRADAS_ITEM.FAIXA, SUB_ITEM_SAIDA=CONVERT(SMALLINT,1), ENTRADAS.MOEDA, ENTRADAS.CAMBIO_NA_DATA, ENTRADAS.PORC_DESCONTO, ENTRADAS.PORC_ENCARGO, ENTRADAS.AGRUPAMENTO_ITENS, ''M'' AS ORIGEM_ITEM    FROM  
DBO.ENTRADAS_ITEM ENTRADAS_ITEM    
JOIN DBO.ENTRADAS ENTRADAS  ON (ENTRADAS_ITEM.NOME_CLIFOR = ENTRADAS.NOME_CLIFOR  AND  ENTRADAS_ITEM.NF_ENTRADA = ENTRADAS.NF_ENTRADA AND  ENTRADAS_ITEM.SERIE_NF_ENTRADA = ENTRADAS.SERIE_NF_ENTRADA)   
JOIN DBO.ESTOQUE_RET_MAT ESTOQUE_RET_MAT ON (ENTRADAS_ITEM.NOME_CLIFOR=ESTOQUE_RET_MAT.NOME_CLIFOR   AND ENTRADAS_ITEM.NF_ENTRADA=ESTOQUE_RET_MAT.NF_ENTRADA AND ENTRADAS_ITEM.SERIE_NF_ENTRADA=ESTOQUE_RET_MAT.SERIE_NF_ENTRADA)   
JOIN DBO.ESTOQUE_RET1_MAT ESTOQUE_RET1_MAT ON (ESTOQUE_RET_MAT.FILIAL=ESTOQUE_RET1_MAT.FILIAL AND    ESTOQUE_RET_MAT.REQ_MATERIAL=ESTOQUE_RET1_MAT.REQ_MATERIAL   AND ENTRADAS_ITEM.ITEM_IMPRESSAO = ESTOQUE_RET1_MAT.ITEM_IMPRESSAO  AND  ENTRADAS_ITEM.REFERENCIA = ESTOQUE_RET1_MAT.MATERIAL)   
INNER JOIN DBO.TRIBUT_ICMS TRIBUT_ICMS   ON  ENTRADAS_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS     
INNER JOIN DBO.CTB_LX_INDICADOR_CFOP CTB_LX_INDICADOR_CFOP   ON  ENTRADAS_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP    
INNER JOIN DBO.CLASSIF_FISCAL CLASSIF_FISCAL  ON  ENTRADAS_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL    
LEFT OUTER JOIN DBO.CTB_CONTA_PLANO CTB_CONTA_PLANO  ON  ENTRADAS_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL   
INNER JOIN DBO.TRIBUT_ORIGEM TRIBUT_ORIGEM       ON  TRIBUT_ORIGEM.TRIBUT_ORIGEM = ENTRADAS_ITEM.TRIBUT_ORIGEM    
JOIN DBO.NATUREZAS_ENTRADAS NATUREZAS_ENTRADAS ON (ENTRADAS.NATUREZA=NATUREZAS_ENTRADAS.NATUREZA)   
WHERE ENTRADAS_ITEM.COD_TABELA_FILHA = ''M''  AND  Entradas.serie_nf_entrada <> ''E1''  AND  Entradas.nf_entrada = ''1188'' AND  (ENTRADAS_ITEM.QTDE_ITEM-ENTRADAS_ITEM.QTDE_DEVOLVIDA)>0 AND NATUREZAS_ENTRADAS.CTB_TIPO_OPERACAO IN (200,201,202,205,208,209,210,215,230) AND   ENTRADAS.NOME_CLIFOR = @P1    ORDER BY ENTRADAS.NOME_CLIFOR, ENTRADAS.NF_ENTRADA, ENTRADAS.SERIE_NF_ENTRADA',N'@P1 varchar(13)','FILATI MALHAS'


select * from ENTRADAS_ITEM
WHERE NF_ENTRADA='53174' AND SERIE_NF_ENTRADA='2' AND REFERENCIA='01.06.0009'

UPDATE ENTRADAS_ITEM
SET ITEM_IMPRESSAO='001'
WHERE NF_ENTRADA='53174' AND SERIE_NF_ENTRADA='2' AND REFERENCIA='50.03.0005'


UPDATE ESTOQUE_RET1_MAT
SET ITEM_IMPRESSAO='002'
where REQ_MATERIAL='042358' AND MATERIAL='50.03.0032'



SELECT * FROM ESTOQUE_RET1_MAT
WHERE REQ_MATERIAL='042358'


SELECT * FROM ESTOQUE_RET_MAT
WHERE NF_ENTRADA='1188'






exec sp_executesql N'
/* VISUALLINX Execute(Alias:CUR_DEVS)  */
SELECT  Entradas_item.comissao_item, Entradas_item.comissao_item_gerente, Entradas_item.desconto_item, Entradas.porc_desconto, Entradas.porc_encargo, Entradas_item.NOME_CLIFOR, Entradas_item.NF_ENTRADA, Entradas_item.SERIE_NF_ENTRADA ,  Entradas_item.ITEM_IMPRESSAO , Entradas_item.SUB_ITEM_TAMANHO,   Entradas.RECEBIMENTO, ESTOQUE_RET1_MAT.QTDE ,  Entradas_item.REFERENCIA,  Entradas_item.REFERENCIA_ITEM, Entradas.EMISSAO, Entradas.RECEBIMENTO, Entradas_item.CODIGO_ITEM, Entradas_item.DESCRICAO_ITEM ,convert(numeric(17,5), 
(((Entradas_item.PRECO_UNITARIO-Entradas_item.desconto_item)/Estoque_ret1_mat.FATOR_CONVERSAO_UNIDADE)/Entradas.cambio_na_data)) AS PRECO_UNITARIO, Entradas_item.UNIDADE, CONVERT(NUMERIC(4,2),1) AS 
FATOR_CONVERSAO_UNIDADE,case when rtrim(isnull(entradas_item.timestamp,'''')) = '''' then ''''else 
dbo.fx_producao_preco(convert(numeric(17,5),dbo.fx_producao_preco(entradas_item.timestamp,''F''))/entradas.cambio_na_data,''T'') end TIMESTAMP, Entradas.MOEDA, Entradas.CAMBIO_NA_DATA,  Estoque_ret1_mat.req_material, 
Estoque_ret1_mat.MATERIAL , Estoque_ret1_mat.COR_MATERIAL, Entradas_item.Classif_Fiscal,  Entradas_item.Tribut_Origem,  Entradas_item.Conta_Contabil, Entradas_item.Tribut_Icms, Entradas_item.Indicador_cfop, 
Tribut_icms.DESCRICAO AS tribut_icms_descricao,  Tribut_origem.DESCRICAO AS tribut_origem_descricao,  Ctb_conta_plano.DESC_CONTA, Classif_fiscal.DESC_CLASSIFICACAO,   Ctb_lx_indicador_cfop.DESCRICAO_INDICADOR_CFOP, 
AGRUPAMENTO_ITENS = case when ENTRADAS.AGRUPAMENTO_ITENS in (2,3) then  ENTRADAS.AGRUPAMENTO_ITENS+1 else ENTRADAS.AGRUPAMENTO_ITENS end from  dbo.ENTRADAS_ITEM Entradas_item  join dbo.ESTOQUE_RET_MAT Estoque_ret_mat on 
(Entradas_item.NOME_CLIFOR=Estoque_ret_mat.NOME_CLIFOR AND Entradas_item.NF_ENTRADA=Estoque_ret_mat.NF_ENTRADA AND Entradas_item.SERIE_NF_ENTRADA=Estoque_ret_mat.SERIE_NF_ENTRADA) 
join dbo.ESTOQUE_RET1_MAT Estoque_ret1_mat on ( Estoque_ret_mat.FILIAL=Estoque_ret1_mat.FILIAL AND  Estoque_ret_mat.REQ_MATERIAL=Estoque_ret1_mat.REQ_MATERIAL AND Entradas_item.ITEM_IMPRESSAO = Estoque_ret1_mat.ITEM_IMPRESSAO  AND  Entradas_item.REFERENCIA = Estoque_ret1_mat.MATERIAL) 
join dbo.ENTRADAS Entradas on (Entradas_item.NOME_CLIFOR=Entradas.NOME_CLIFOR AND Entradas_item.NF_ENTRADA=Entradas.NF_ENTRADA AND Entradas_item.SERIE_NF_ENTRADA=Entradas.SERIE_NF_ENTRADA) join dbo.NATUREZAS_ENTRADAS Naturezas_entradas On (Entradas.Natureza=Naturezas_entradas.Natureza) INNER JOIN dbo.TRIBUT_ICMS Tribut_icms ON  Entradas_item.TRIBUT_ICMS = Tribut_icms.TRIBUT_ICMS    INNER JOIN dbo.CTB_LX_INDICADOR_CFOP Ctb_lx_indicador_cfop ON  Entradas_item.INDICADOR_CFOP = Ctb_lx_indicador_cfop.INDICADOR_CFOP   INNER JOIN dbo.CLASSIF_FISCAL Classif_fiscal ON  Entradas_item.CLASSIF_FISCAL = Classif_fiscal.CLASSIF_FISCAL  INNER JOIN dbo.TRIBUT_ORIGEM Tribut_origem ON  Tribut_origem.TRIBUT_ORIGEM = Entradas_item.TRIBUT_ORIGEM   LEFT OUTER JOIN dbo.CTB_CONTA_PLANO Ctb_conta_plano ON  Entradas_item.CONTA_CONTABIL = Ctb_conta_plano.CONTA_CONTABIL  WHERE Naturezas_entradas.CTB_TIPO_OPERACAO in (200,201,202,205,208,209,210,215,230) AND ((Entradas_item.QTDE_ITEM - Entradas_item.QTDE_DEVOLVIDA) > 0) AND Entradas_item.NOME_CLIFOR = @P1  AND  Entradas_item.NF_ENTRADA LIKE RTRIM(@P2) AND  Estoque_ret1_mat.MATERIAL = @P3 AND Estoque_ret1_mat.COR_MATERIAL = @P4  AND  Entradas.serie_nf_entrada <> ''E1'' ORDER BY Entradas.RECEBIMENTO DESC ',N'@P1 varchar(8),@P2 varchar(5),@P3 varchar(10),@P4 varchar(6)','TERLIZZI','53174','50.03.0032','AR0094'



select * from ESTOQUE_RET1_MAT
where REQ_MATERIAL='042358' AND MATERIAL='50.03.0032'


