SELECT VENDAS.GERENTE,VENDAS.REPRESENTANTE,
ENTRADAS.NATUREZA,
NATUREZAS_ENTRADAS.DESC_NATUREZA,
ESTOQUE_PROD_ENT.EMISSAO,
ENTRADAS.OBS,
ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO, 
ESTOQUE_PROD1_ENT.FILIAL, 
ESTOQUE_PROD1_ENT.ITEM_IMPRESSAO, 
ESTOQUE_PROD1_ENT.PRODUTO, 
ESTOQUE_PROD1_ENT.COR_PRODUTO, 
ESTOQUE_PROD1_ENT.TAREFA, 
ESTOQUE_PROD1_ENT.ORDEM_PRODUCAO, 
ESTOQUE_PROD1_ENT.ID_MODIFICACAO, 
ESTOQUE_PROD1_ENT.QTDE, 
ESTOQUE_PROD1_ENT.EN_1, 
ESTOQUE_PROD1_ENT.EN_2, 
ESTOQUE_PROD1_ENT.EN_3, 
ESTOQUE_PROD1_ENT.EN_4, 
ESTOQUE_PROD1_ENT.EN_5, 
ESTOQUE_PROD1_ENT.EN_6, 
ESTOQUE_PROD1_ENT.EN_7, 
ESTOQUE_PROD1_ENT.EN_8, 
ESTOQUE_PROD1_ENT.EN_9, 
ESTOQUE_PROD1_ENT.EN_10, 
ESTOQUE_PROD1_ENT.EN_11, 
ESTOQUE_PROD1_ENT.EN_12, 
ESTOQUE_PROD1_ENT.EN_13, 
ESTOQUE_PROD1_ENT.EN_14, 
ESTOQUE_PROD1_ENT.EN_15, 
ESTOQUE_PROD1_ENT.EN_16, 
ESTOQUE_PROD1_ENT.CUSTO1, 
ESTOQUE_PROD1_ENT.CUSTO2, 
ESTOQUE_PROD1_ENT.CUSTO3, 
ESTOQUE_PROD1_ENT.CUSTO4, 
ESTOQUE_PROD1_ENT.DESCONTO_ITEM, 
ESTOQUE_PROD1_ENT.VALOR, 
ESTOQUE_PROD1_ENT.PEDIDO_VENDA, ESTOQUE_PROD1_ENT.PEDIDO_VENDA_ENTREGA, ESTOQUE_PROD1_ENT.PEDIDO_VENDA_ITEM, ESTOQUE_PROD_ENT.PEDIDO, ESTOQUE_PROD_ENT.ENTREGA_PEDIDO, ESTOQUE_PROD_ENT.NOME_CLIFOR, ESTOQUE_PROD_ENT.NF_ENTRADA, ESTOQUE_PROD_ENT.SERIE_NF_ENTRADA, PRODUTOS.CLASSIF_FISCAL, PRODUTOS.DESC_PRODUTO, PRODUTOS.DESC_PROD_NF, PRODUTOS.UNIDADE, PRODUTOS.REFER_FABRICANTE, PRODUTOS.GRADE, PRODUTOS.VARIA_CUSTO_COR, PRODUTOS.VARIA_CUSTO_TAM, PRODUTOS.VARIA_PRECO_COR, PRODUTOS.VARIA_PRECO_TAM, PRODUTOS.PONTEIRO_PRECO_TAM, PRODUTOS.TRIBUT_ICMS 
FROM ESTOQUE_PROD1_ENT with (nolock)
INNER JOIN ESTOQUE_PROD_ENT with (nolock) ON ESTOQUE_PROD1_ENT.FILIAL = ESTOQUE_PROD_ENT.FILIAL AND ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO 
INNER JOIN PRODUTOS with (nolock) ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
INNER JOIN PRODUTO_CORES with (nolock) ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTO_CORES.PRODUTO AND ESTOQUE_PROD1_ENT.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
INNER JOIN ENTRADAS with (nolock) ON ESTOQUE_PROD_ENT.NF_ENTRADA = ENTRADAS.NF_ENTRADA AND ESTOQUE_PROD_ENT.NOME_CLIFOR = ENTRADAS.NOME_CLIFOR AND ESTOQUE_PROD_ENT.SERIE_NF_ENTRADA = ENTRADAS.SERIE_NF_ENTRADA 
INNER JOIN FILIAIS with (nolock) ON FILIAIS.FILIAL = ENTRADAS.FILIAL 
LEFT JOIN PRODUTOS_INDICADOR_CFOP with (nolock) ON ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS_INDICADOR_CFOP.PRODUTO AND PRODUTOS_INDICADOR_CFOP.FILIAL = FILIAIS.FILIAL 
LEFT JOIN COMPRAS with (nolock) ON ESTOQUE_PROD_ENT.PEDIDO = COMPRAS.PEDIDO 
LEFT JOIN MODIFICACAO_FICHA_TECNICA with (nolock) ON ESTOQUE_PROD1_ENT.ID_MODIFICACAO = MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO 
JOIN VENDAS with (nolock) ON VENDAS.PEDIDO = ESTOQUE_PROD1_ENT.PEDIDO_VENDA
JOIN NATUREZAS_ENTRADAS with (nolock) ON NATUREZAS_ENTRADAS.NATUREZA = ENTRADAS.NATUREZA
WHERE ESTOQUE_PROD_ENT.EMISSAO >= '20120101' AND ENTRADAS.NATUREZA='250.01' 
