select * from (
SELECT FATURAMENTO_PROD.PRODUTO,
FATURAMENTO_PROD.COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO,
PRODUTOS_BARRA.CODIGO_BARRA,
FATURAMENTO_PROD.ITEM_IMPRESSAO,
QTDE = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN SUM(FATURAMENTO_PROD.F1)
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN SUM(FATURAMENTO_PROD.F2) 
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN SUM(FATURAMENTO_PROD.F3)  
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN SUM(FATURAMENTO_PROD.F4)  
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN SUM(FATURAMENTO_PROD.F5)  
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN SUM(FATURAMENTO_PROD.F6)  
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN SUM(FATURAMENTO_PROD.F7)  
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN SUM(FATURAMENTO_PROD.F8)  
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN SUM(FATURAMENTO_PROD.F9)  
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN SUM(FATURAMENTO_PROD.F10)  
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN SUM(FATURAMENTO_PROD.F11)  
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN SUM(FATURAMENTO_PROD.F12)  
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN SUM(FATURAMENTO_PROD.F13)  
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN SUM(FATURAMENTO_PROD.F14) 
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN SUM(FATURAMENTO_PROD.F15)  
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN SUM(FATURAMENTO_PROD.F16)  
                     END)
FROM FATURAMENTO_PROD
JOIN PRODUTOS_BARRA ON PRODUTOS_BARRA.PRODUTO=FATURAMENTO_PROD.PRODUTO AND PRODUTOS_BARRA.COR_PRODUTO=FATURAMENTO_PROD.COR_PRODUTO 
WHERE NF_SAIDA='031516' AND SERIE_NF='2' AND PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' and PRODUTOS_BARRA.CODIGO_BARRA_PADRAO=1
GROUP BY FATURAMENTO_PROD.PRODUTO,
FATURAMENTO_PROD.COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO,
PRODUTOS_BARRA.CODIGO_BARRA,
FATURAMENTO_PROD.ITEM_IMPRESSAO
) as final
where QTDE>0



SELECT * FROM FATURAMENTO_PROD
WHERE NF_SAIDA='031516' AND SERIE_NF='2'
