select * from DR_METAS_OFICINA_GRUPO
WHERE DATA_PRODUCAO>'20150601' AND DESC_SETOR_PRODUCAO LIKE '%LANÇA%'

SELECT * FROM PRODUCAO_RECURSOS
WHERE DESC_RECURSO LIKE 'receb%' 'GRUPO LANÇADORA%'

SELECT * FROM PRODUCAO_RECURSOS
WHERE DESC_RECURSO LIKE 'retorn%'


SELECT * FROM W_OFICINA_GRUPO_EFICIENCIA
WHERE EMISSAO='20150624'


SP_HELPTEXT W_OFICINA_GRUPO_EFICIENCIA


CREATE VIEW [dbo].[W_OFICINA_GRUPO_EFICIENCIA] AS    
SELECT FILIAL,    
        DESC_SETOR_PRODUCAO,    
        DESC_RECURSO,    
        EMISSAO,    
        QTDE_OPERADOR,    
        MINUTOS_DISPONIVEIS,   
        QTDE_PROD=SUM(QTDE),   
        TEMPO_PADRAO_TOTAL=SUM(TEMPO_PADRAO*QTDE),    
        EFICIENCIA=ROUND((SUM(TEMPO_PADRAO*QTDE)/(QTDE_OPERADOR*MINUTOS_DISPONIVEIS)*100),0)     
    
FROM   W_OFICINA_GRUPO_REFERENCIA_TEMPO    
    
GROUP BY FILIAL,DESC_SETOR_PRODUCAO,DESC_RECURSO,EMISSAO,QTDE_OPERADOR,MINUTOS_DISPONIVEIS    


SELECT * FROM PRODUCAO_TAREFAS
WHERE RECURSO_PRODUTIVO='GLA05' AND QTDE_EM_PROCESSO>0



