
SELECT 'EXEC sp_dropuser '''+name+'''' FROM SYSUSERS
WHERE hasdbaccess=1

EXEC sp_dropuser 'dbo'
EXEC sp_dropuser 'DENI RICARDO'
EXEC sp_dropuser 'JOSE MARIO'
EXEC sp_dropuser 'SERGIO PIRES'
EXEC sp_dropuser 'LUCIANA JACOME'
EXEC sp_dropuser 'ELANO'
EXEC sp_dropuser 'TAYNARA'
EXEC sp_dropuser 'REGIANE MARTINS'
EXEC sp_dropuser 'CHARLES'
EXEC sp_dropuser 'CRIS'
EXEC sp_dropuser 'CARLA'
EXEC sp_dropuser 'LUIZ'
EXEC sp_dropuser 'SELVERTRE'
EXEC sp_dropuser 'FRANCISCO BRENDO'
EXEC sp_dropuser 'WALTER WANDERSON'
EXEC sp_dropuser 'THYARA JAHNY'
EXEC sp_dropuser 'FLAVIO REIS'
EXEC sp_dropuser 'LEANDRO FREITAS'
EXEC sp_dropuser 'RENATA CARVALHO'
EXEC sp_dropuser 'OFELIA'
EXEC sp_dropuser 'MAIA-BRINDE'
EXEC sp_dropuser 'EVANDIR'
EXEC sp_dropuser 'gianeide'
EXEC sp_dropuser 'SILVESTRE SANTOS'
EXEC sp_dropuser 'VILMAR'
EXEC sp_dropuser 'TUANIA'
EXEC sp_dropuser 'FIORUCCI'
EXEC sp_dropuser 'CAROL'
EXEC sp_dropuser 'JOSY'
EXEC sp_dropuser 'LUCAS'
EXEC sp_dropuser 'JANAINA FRANÇA'
EXEC sp_dropuser 'ANA PAULA'
EXEC sp_dropuser 'SANDRA'
EXEC sp_dropuser 'VIVIANAFREITAS'
EXEC sp_dropuser 'CHARLES MADEIRO'
EXEC sp_dropuser 'VITOR'
EXEC sp_dropuser 'VANESSA'
EXEC sp_dropuser 'ANDREA FERREIRA'
EXEC sp_dropuser 'JOAO CARLOS'
EXEC sp_dropuser 'ITAITINGA'
EXEC sp_dropuser 'ELITE'
EXEC sp_dropuser 'ATHENA'
EXEC sp_dropuser 'JULIETE'
EXEC sp_dropuser 'IURY'
EXEC sp_dropuser 'CRISLON'
EXEC sp_dropuser 'AIRTON'
EXEC sp_dropuser 'RAFAEL SOARES'
EXEC sp_dropuser 'ALEXSANDRO'
EXEC sp_dropuser 'AFRODITE'
EXEC sp_dropuser 'LENO'
EXEC sp_dropuser 'ALTAIR'
EXEC sp_dropuser 'HELOI'
EXEC sp_dropuser 'EMANUEL'
EXEC sp_dropuser 'ELISANGELA OLIVEIRA'
EXEC sp_dropuser 'JANIA'
EXEC sp_dropuser 'VANIELE'
EXEC sp_dropuser 'RENAN'
EXEC sp_dropuser 'JANIELY'
EXEC sp_dropuser 'KEDILA'
EXEC sp_dropuser 'EDMAR JUNIOR'
EXEC sp_dropuser 'PATRICIA TEIXEIRA'
EXEC sp_dropuser 'ANDRE PAIVA'
EXEC sp_dropuser 'CARLINHO'
EXEC sp_dropuser 'REGINALDO'
EXEC sp_dropuser 'KARINAMKT'
EXEC sp_dropuser 'MKT'
EXEC sp_dropuser 'GUILHERME'
EXEC sp_dropuser 'ALEX SANTIAGO'
EXEC sp_dropuser 'CINTIA'
EXEC sp_dropuser 'VITORIA'
EXEC sp_dropuser 'MARCELO HOLANDA'
EXEC sp_dropuser 'GERBESON'
EXEC sp_dropuser 'DAVI'
EXEC sp_dropuser 'GEOVANI'
EXEC sp_dropuser 'ERIVAN'
EXEC sp_dropuser 'CASSIA'
EXEC sp_dropuser 'ADRIANA'
EXEC sp_dropuser 'GILIARD'
EXEC sp_dropuser 'FELIPE'
EXEC sp_dropuser 'MARCELO FREITAS'
EXEC sp_dropuser 'SAMANTA'
EXEC sp_dropuser 'LUCIENE'
EXEC sp_dropuser 'RONALDO'
EXEC sp_dropuser 'SHEILA KELY'
EXEC sp_dropuser 'MARIA JANAINA'
EXEC sp_dropuser 'RAFAEL MARTINS'
EXEC sp_dropuser 'AMANDA'
EXEC sp_dropuser 'PATRICIA INACIO'
EXEC sp_dropuser 'APRENDIZ'
EXEC sp_dropuser 'WILLIAM'
EXEC sp_dropuser 'AURELIO'
