SELECT DISTINCT VENDAS.GERENTE,VENDAS.REPRESENTANTE,VENDAS.PERIODO_PCP,VENDAS.NUMERO_ENTREGA,VENDAS_PRODUTO.NUMERO_ENTREGA,VENDAS.PEDIDO FROM VENDAS
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS.PEDIDO
WHERE VENDAS_PRODUTO.NUMERO_ENTREGA<>VENDAS.NUMERO_ENTREGA AND VENDAS_PRODUTO.QTDE_ENTREGAR>0 --AND VENDAS.TIPO = 'BRINDE'
ORDER BY VENDAS.GERENTE,VENDAS.REPRESENTANTE,VENDAS.PERIODO_PCP


UPDATE VENDAS_PRODUTO
SET NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA,ENTREGA=PRODUTOS_PERIODOS_ENTREGAS.ENTREGA, LIMITE_ENTREGA=PRODUTOS_PERIODOS_ENTREGAS.LIMITE
FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS_PRODUTO.PEDIDO=VENDAS.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS ON PRODUTOS_PERIODOS_ENTREGAS.PERIODO_PCP=VENDAS.PERIODO_PCP 
 AND PRODUTOS_PERIODOS_ENTREGAS.NUMERO_ENTREGA=VENDAS.NUMERO_ENTREGA
WHERE VENDAS_PRODUTO.NUMERO_ENTREGA<>VENDAS.NUMERO_ENTREGA AND VENDAS_PRODUTO.QTDE_ENTREGAR>0 --AND VENDAS.TIPO <> 'BRINDE' 
AND VENDAS.PEDIDO IN ('552044','551902')
      
