select * from FATURAMENTO_ENTRADA_DEVOLUCAO
WHERE NF_ENTRADA='046474'

select * from FATURAMENTO_ENTRADA_DEVOLUCAO
WHERE NF_ENTRADA='045507'

select * from ENTRADAS_ITEM
WHERE NF_ENTRADA='045507'


INSERT INTO FATURAMENTO_ENTRADA_DEVOLUCAO (
[FILIAL]      ,[ITEM_IMPRESSAO_ENTRADA]      ,[ITEM_IMPRESSAO_SAIDA]      
,[NF_ENTRADA]      ,[NF_SAIDA]      ,[NOME_CLIFOR]      
,[ORIGEM_ENTRADA_SAIDA]      ,[QTDE_DEVOLVIDA]
      ,[SERIE_NF]      ,[SERIE_NF_ENTRADA]
      ,[SUB_ITEM_ENTRADA]      ,[SUB_ITEM_SAIDA])
VALUES('DR VAREJO','0217','0001','045507','039265','ELBIA ALEGRE DE FERNANDES',
'E',19860.00,'2','4',4,4)








