SELECT DISTINCT V.PEDIDO,V.CLIENTE_ATACADO,CC.ENTREGA_CIDADE,CC.ENTREGA_UF,VP.ENTREGA,VP.LIMITE_ENTREGA FROM VENDAS_PRODUTO VP
JOIN VENDAS V ON V.PEDIDO=VP.PEDIDO
JOIN CADASTRO_CLI_FOR CC ON CC.NOME_CLIFOR=V.CLIENTE_ATACADO 
WHERE VP.ENTREGA BETWEEN '20131101' AND '20131130' AND V.APROVACAO='A'
