exec sp_executesql N'
/* lx100107spk  CursorAdapter: Cur_v_faturamento_05_os_produtos(Alias: v_faturamento_05_os_produtos)  */
SELECT  DISTINCT FILHA=CONVERT(VARCHAR(20),''FATURAMENTO_ITEM''), PRODUCAO_ORDEM_SERVICO.NF_SAIDA,       CONSUMIVEL_ITEM=(SELECT MAX(CODIGO_ITEM) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))),   PRODUTOS.DESC_PRODUTO DESC_CONSUMIVEL,    MATERIAIS.DESC_MATERIAL,  PRODUCAO_ORDEM_SERVICO.FILIAL,    CONVERT(NUMERIC(9, 3),     QTDE_O) QTDE, PRODUTOS.UNIDADE,   CONVERT(NUMERIC(15, 5),    (SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO,  CONVERT(NUMERIC(15, 5),  0) DESCONTO_ITEM,     IPI = CONVERT(NUMERIC(11,2),0),    ICMS = CONVERT(NUMERIC(11,2),0),  IRRF = CONVERT(NUMERIC(11,2),0),    CONVERT(NUMERIC(15, 5),   ((SELECT MAX(PRECO_UNITARIO) FROM 
FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND 
((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))))*QTDE_O) VALOR,  PRODUCAO_ORDEM_SERVICO.SERIE_NF,      CAMBIO_NA_DATA = 
CONVERT(INT,1),  MOEDA = FATURAMENTO.MOEDA,   PESO = CONVERT(INT,1),    PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO  , SPACE(8) REQ_MATERIAL,   SPACE(25) FILIAL_REQ,   SPACE(10) AS COMPRIMENTO, SPACE(3) AS ITEM, 
MATERIAIS_CORES.COR_MATERIAL,  MATERIAIS.MATERIAL,  CONVERT(VARCHAR(4),'''')  CODIGO_FISCAL_OPERACAO, MATERIAIS.INDICADOR_CFOP, DESCRICAO_INDICADOR_CFOP ,   QTDE_O AS QUANTIDADE, COD_TABELA_FILHA=''O'',   
MATERIAIS.TRIBUT_ICMS,  TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, MATERIAIS.TRIBUT_ORIGEM,    TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO, MATERIAIS.CLASSIF_FISCAL,  CLASSIF_FISCAL.DESC_CLASSIFICACAO, 
MATERIAIS_CORES.CUSTO_REPOSICAO AS TIMESTAMP,   MATERIAIS.CONTA_CONTABIL,  CTB_CONTA_PLANO.DESC_CONTA,    FAIXA=''1'', GERAR_ITEM= CONVERT(BIT,0), SPACE(4) AS ITEM_IMPRESSAO,     CONVERT(NUMERIC(15, 5), 
MATERIAIS_CORES.CUSTO_REPOSICAO) PRECO, PRODUTOS.PRODUTO  ,   PRODUTOS.GRADE, PRODUTOS.PRODUTO  AS REFERENCIA, PRODUTOS.DESC_PRODUTO, PRODUCAO_OS_TAREFAS.COR_PRODUTO,   QTDE_O, O1, O2, O3, O4, O5, O6, O7, O8, O9, O10, O11, 
O12, O13, O14, O15, O16, O17, O18, O19, O20, O21,   O22, O23, O24, O25, O26, O27, O28, O29, O30, O31, O32, O33, O34, O35, O36, O37, O38, O39, O40, O41, O42,  O43, O44, O45, O46, O47, O48, PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO, 
PRODUTO_CORES.DESC_COR_PRODUTO,   CONVERT(NUMERIC(15, 5), (SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  
FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO_BRUTO,  CONVERT(NUMERIC(8, 4), 0) PORC_DESCONTO_ITEM, ORIGEM_ITEM = ''P''   FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS     JOIN DBO.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO ON (PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO)    JOIN PRODUTO_CORES ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTO_CORES.PRODUTO AND   PRODUCAO_OS_TAREFAS.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  JOIN DBO.PRODUTOS   PRODUTOS ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTOS.PRODUTO)  JOIN   DBO.PRODUTOS_TAMANHOS PRODUTOS_TAMANHOS ON (PRODUTOS.GRADE=PRODUTOS_TAMANHOS.GRADE)   JOIN FATURAMENTO ON (PRODUCAO_ORDEM_SERVICO.NF_SAIDA=FATURAMENTO.NF_SAIDA AND PRODUCAO_ORDEM_SERVICO.SERIE_NF=FATURAMENTO.SERIE_NF  AND PRODUCAO_ORDEM_SERVICO.FILIAL=FATURAMENTO.FILIAL)   LEFT JOIN MATERIAIS ON (PRODUTOS.MATERIAL = MATERIAIS.MATERIAL )    LEFT JOIN MATERIAIS_CORES ON (PRODUTOS.MATERIAL = MATERIAIS_CORES.MATERIAL   AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = MATERIAIS_CORES.COR_MATERIAL)     LEFT JOIN CTB_LX_INDICADOR_CFOP ON (MATERIAIS.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP)        LEFT JOIN TRIBUT_ICMS ON (PRODUTOS.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS)      LEFT JOIN TRIBUT_ORIGEM ON (PRODUTOS.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM)      LEFT JOIN CLASSIF_FISCAL ON (PRODUTOS.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL)      LEFT JOIN CTB_CONTA_PLANO ON (PRODUTOS.CONTA_CONTABIL=CTB_CONTA_PLANO.CONTA_CONTABIL)   WHERE FATURAMENTO.NF_SAIDA = @P1     AND FATURAMENTO.FILIAL = @P2     AND  FATURAMENTO.SERIE_NF = @P3',N'@P1 varchar(6),@P2 varchar(9),@P3 varchar(1)','024886','DR VAREJO','4'




SELECT PRODUCAO_OS_TAREFAS.* 
FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS     
JOIN DBO.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO ON (PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO)    
JOIN PRODUTO_CORES ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTO_CORES.PRODUTO AND   PRODUCAO_OS_TAREFAS.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  
JOIN DBO.PRODUTOS   PRODUTOS ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTOS.PRODUTO)  
JOIN   DBO.PRODUTOS_TAMANHOS PRODUTOS_TAMANHOS ON (PRODUTOS.GRADE=PRODUTOS_TAMANHOS.GRADE)   
JOIN FATURAMENTO ON (PRODUCAO_ORDEM_SERVICO.NF_SAIDA=FATURAMENTO.NF_SAIDA AND PRODUCAO_ORDEM_SERVICO.SERIE_NF=FATURAMENTO.SERIE_NF  AND PRODUCAO_ORDEM_SERVICO.FILIAL=FATURAMENTO.FILIAL)   
LEFT JOIN MATERIAIS ON (PRODUTOS.MATERIAL = MATERIAIS.MATERIAL )    
LEFT JOIN MATERIAIS_CORES ON (PRODUTOS.MATERIAL = MATERIAIS_CORES.MATERIAL   AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = MATERIAIS_CORES.COR_MATERIAL)     
LEFT JOIN CTB_LX_INDICADOR_CFOP ON (MATERIAIS.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP)        
LEFT JOIN TRIBUT_ICMS ON (PRODUTOS.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS)      
LEFT JOIN TRIBUT_ORIGEM ON (PRODUTOS.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM)      
LEFT JOIN CLASSIF_FISCAL ON (PRODUTOS.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL)      
LEFT JOIN CTB_CONTA_PLANO ON (PRODUTOS.CONTA_CONTABIL=CTB_CONTA_PLANO.CONTA_CONTABIL)   
WHERE FATURAMENTO.FILIAL = 'dr varejo' AND  FATURAMENTO.SERIE_NF = '4' and
NOME_CLIFOR like '%D ANJOU INTIMA%' AND FATURAMENTO.EMISSAO>='20140101' AND FATURAMENTO.EMISSAO<='20141231' AND PRODUCAO_OS_TAREFAS.PRODUTO IN ('51169','51472','52372')

