SELECT ESTOQUE_PRODUTOS.FILIAL,PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO, 
QTDE_ESTOQUE= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN ESTOQUE_PRODUTOS.ES1 
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN ESTOQUE_PRODUTOS.ES2 
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN ESTOQUE_PRODUTOS.ES3 
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN ESTOQUE_PRODUTOS.ES4 
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN ESTOQUE_PRODUTOS.ES5 
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN ESTOQUE_PRODUTOS.ES6 
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN ESTOQUE_PRODUTOS.ES7 
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN ESTOQUE_PRODUTOS.ES8 
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN ESTOQUE_PRODUTOS.ES9 
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN ESTOQUE_PRODUTOS.ES10 
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN ESTOQUE_PRODUTOS.ES11 
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN ESTOQUE_PRODUTOS.ES12 
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN ESTOQUE_PRODUTOS.ES13 
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN ESTOQUE_PRODUTOS.ES14 
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN ESTOQUE_PRODUTOS.ES15 
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN ESTOQUE_PRODUTOS.ES16 
                     END)
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
LEFT JOIN (

SELECT PRODUTO,COR_PRODUTO,FILIAL,DATA_CUSTO_MEDIO,DATA_ULT_CUSTO,
ULTIMA_SAIDA  ,ULTIMA_ENTRADA,DISPONIVEL,ESTOQUE,EMBALADO,TRANSITO,
FAT_DEV,ES1,ES2,ES3,ES4,ES5  ,ES6,ES7,ES8,ES9,ES10,ES11,ES12,ES13,
ES14,ES15,ES16,ES17,ES18,ES19,ES20,ES21,ES22,ES23,ES24,ES25  ,ES26,
ES27,ES28,ES29,ES30,ES31,ES32,ES33,ES34,ES35,ES36,ES37,ES38,ES39,ES40,
ES41,ES42,ES43,ES44  ,ES45,ES46,ES47,ES48,TABELA_OPERACOES,TABELA_MEDIDAS,
TIPO_PRODUTO,DESC_PRODUTO  ,GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO,GRADE,
LINHA,GRIFFE,CARTELA,UNIDADE  ,PESO,REVENDA,MODELAGEM,FABRICANTE,
REFER_FABRICANTE,VARIA_PRECO_COR  ,VARIA_PRECO_TAM,PONTEIRO_PRECO_TAM,
ESTILISTA,MODELISTA,PERIODO_PCP  ,GIRO_ENTREGA,DESC_COR_PRODUTO,
TINTURARIA_LAVAGEM,TIPO_LAVAGEM_TINTURARIA  ,MATERIAL,COR_MATERIAL,
ETIQUETA,CUSTO_MEDIO1,CUSTO_MEDIO2,CUSTO_MEDIO3  ,CUSTO_MEDIO4,
ULTIMO_CUSTO1,ULTIMO_CUSTO4,ULTIMO_CUSTO3  ,ULTIMO_CUSTO2,
CUSTO4_A_VALORIZAR  ,CUSTO3_A_VALORIZAR  ,CUSTO2_A_VALORIZAR  ,
CUSTO1_A_VALORIZAR  ,VALOR_ESTOQUE  ,VALOR_DISPONIVEL  ,VALOR_EMBALADO  ,
VALOR_TRANSITO  ,EMB1  ,EMB2  ,EMB3  ,EMB4  ,EMB5  ,EMB6  ,EMB7  ,EMB8  ,
EMB9  ,EMB10  ,EMB11  ,EMB12  ,EMB13  ,EMB14  ,EMB15  ,EMB16  ,EMB17  ,
EMB18  ,EMB19  ,EMB20  ,EMB21  ,EMB22  ,EMB23  ,EMB24  ,EMB25  ,EMB26  ,
EMB27  ,EMB28  ,EMB29  ,EMB30  ,EMB31  ,EMB32  ,EMB33  ,EMB34  ,EMB35  ,
EMB36  ,EMB37  ,EMB38  ,EMB39  ,EMB40  ,EMB41  ,EMB42  ,EMB43  ,EMB44  ,
EMB45  ,EMB46  ,EMB47  ,EMB48  ,CUSTO_REPOSICAO1  ,CUSTO_REPOSICAO2  ,
CUSTO_REPOSICAO3  ,CUSTO_REPOSICAO4  ,VARIA_CUSTO_COR  ,VARIA_CUSTO_TAM  ,
EMPRESA  ,MATRIZ_FISCAL  ,MAT_CONTABIL  ,INATIVO  ,CATEGORIA_PRODUTO  ,
SUBCATEGORIA_PRODUTO  ,CUSTO_REP_UNITARIO  ,CUSTO_REP_TOTAL 
FROM W_ESTOQUE_PRODUTOS_00

) 
AS ESTOQUE_PRODUTOS
  ON ESTOQUE_PRODUTOS.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND ESTOQUE_PRODUTOS.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND ESTOQUE_PRODUTOS.FILIAL='FORA DE LINHA'


SELECT ESTOQUE_PRODUTOS.FILIAL,
PRODUTOS.GRUPO_PRODUTO,
PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO, 
QTDE_ESTOQUE= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN ESTOQUE_PRODUTOS.ES1 
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN ESTOQUE_PRODUTOS.ES2 
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN ESTOQUE_PRODUTOS.ES3 
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN ESTOQUE_PRODUTOS.ES4 
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN ESTOQUE_PRODUTOS.ES5 
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN ESTOQUE_PRODUTOS.ES6 
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN ESTOQUE_PRODUTOS.ES7 
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN ESTOQUE_PRODUTOS.ES8 
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN ESTOQUE_PRODUTOS.ES9 
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN ESTOQUE_PRODUTOS.ES10 
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN ESTOQUE_PRODUTOS.ES11 
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN ESTOQUE_PRODUTOS.ES12 
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN ESTOQUE_PRODUTOS.ES13 
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN ESTOQUE_PRODUTOS.ES14 
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN ESTOQUE_PRODUTOS.ES15 
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN ESTOQUE_PRODUTOS.ES16 
                     END)
FROM ESTOQUE_PRODUTOS ESTOQUE_PRODUTOS 
JOIN PRODUTOS PRODUTOS ON ESTOQUE_PRODUTOS.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=ESTOQUE_PRODUTOS.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=ESTOQUE_PRODUTOS.COR_PRODUTO 
LEFT JOIN (SELECT * FROM PRODUTOS_BARRA) AS PRODUTOS_BARRA
  ON ESTOQUE_PRODUTOS.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND ESTOQUE_PRODUTOS.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
JOIN FILIAIS ON FILIAIS.FILIAL=ESTOQUE_PRODUTOS.FILIAL 
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND ESTOQUE_PRODUTOS.FILIAL='FORA DE LINHA'




PRODUTOS_BARRA.CODIGO_BARRA LIKE '78%' 
AND FILIAIS.MATRIZ_FISCAL IS NOT NULL



SELECT SUM(ESTOQUE) FROM ESTOQUE_PRODUTOS
