select * from CTB_LANCAMENTO
WHERE LANCAMENTO='398583' --and  ITEM=17

begin tran
rollback
INSERT INTO CTB_LANCAMENTO_ITEM
SELECT [EMPRESA]
      ,[LANCAMENTO]
      ,[ITEM]=(SELECT COUNT(ITEM)+1 FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[CONTA_CONTABIL]='112010402'
      ,[LX_TIPO_LANCAMENTO]='LMD'
      ,[CREDITO]=0.00
      ,[DEBITO]=(SELECT SUM(CREDITO) FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[HISTORICO]='DEBITO REF'
      ,[CODIGO_HISTORICO]='LMD'
      ,[RATEIO_CENTRO_CUSTO]
      ,[CONCILIADO]
      ,[PERMITE_ALTERACAO]
      ,[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=(SELECT SUM(CREDITO) FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[CREDITO_MOEDA]=0.00
      ,[GERADO_AUTOMATICO_TIPO]
      ,[DATA_DIGITACAO]
      ,[RATEIO_FILIAL]
      ,[COD_CLIFOR]=null
      ,[MOEDA]
      ,[CAMBIO_NA_DATA]
      ,[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]
      ,[VALOR_FINANCEIRO_PADRAO]
      ,[DATA_MOV]
      ,[USUARIO_MOV]
      ,[DOCUMENTO]
  FROM [DRVAREJO].[dbo].[CTB_LANCAMENTO_ITEM] A
WHERE LANCAMENTO='386420' AND ITEM=1
commit


INSERT INTO CTB_LANCAMENTO_ITEM
SELECT [EMPRESA]
      ,[LANCAMENTO]
      ,[ITEM]=(SELECT COUNT(ITEM)+1 FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[CONTA_CONTABIL]='112010402'
      ,[LX_TIPO_LANCAMENTO]='LMD'
      ,[CREDITO]=0.00
      ,[DEBITO]=(SELECT SUM(CREDITO) FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[HISTORICO]='DEBITO REF'
      ,[CODIGO_HISTORICO]='LMD'
      ,[RATEIO_CENTRO_CUSTO]
      ,[CONCILIADO]
      ,[PERMITE_ALTERACAO]
      ,[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=(SELECT SUM(CREDITO) FROM CTB_LANCAMENTO_ITEM WHERE LANCAMENTO=A.LANCAMENTO)
      ,[CREDITO_MOEDA]=0.00
      ,[GERADO_AUTOMATICO_TIPO]
      ,[DATA_DIGITACAO]
      ,[RATEIO_FILIAL]
      ,[COD_CLIFOR]=null
      ,[MOEDA]
      ,[CAMBIO_NA_DATA]
      ,[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]
      ,[VALOR_FINANCEIRO_PADRAO]
      ,[DATA_MOV]
      ,[USUARIO_MOV]
      ,[DOCUMENTO]
  FROM [DRVAREJO].[dbo].[CTB_LANCAMENTO_ITEM] A
WHERE LANCAMENTO='387640' AND ITEM=1



select * from CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='386420' 

select * from CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='405153' 

update CTB_LANCAMENTO_ITEM
set CONTA_CONTABIL='112010311',CREDITO=5099.65,CREDITO_MOEDA=5099.65,DEBITO=0.00,DEBITO_MOEDA=0.00
WHERE LANCAMENTO='405153' and  ITEM=10

update CTB_LANCAMENTO_ITEM
set CONTA_CONTABIL='1120101',CREDITO=0.00,CREDITO_MOEDA=0.00,DEBITO=5099.65,DEBITO_MOEDA=5099.65
WHERE LANCAMENTO='405153' and  ITEM=11


--alterar os lançamentos – 
--401366 : D-(LTD) – 1120101 e C-(RCC) - 112010311 e 
405153 : D-(LTD) – 1120101 e C-(RCC) – 112010311 ITEM 10 r$ 5.099,65



update CTB_LANCAMENTO_ITEM
set CONTA_CONTABIL='1120101'
WHERE LANCAMENTO='398583' and  ITEM=1


SELECT * FROM CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='405098' and  ITEM=12


update CTB_LANCAMENTO_ITEM
set DEBITO=2686,CREDITO=0,DEBITO_MOEDA=2686,CREDITO_MOEDA=0
WHERE LANCAMENTO='405098' and  ITEM=12

update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=33058.40,DEBITO_MOEDA=0,CREDITO_MOEDA=33058.40
WHERE LANCAMENTO='327100' and  ITEM=2

update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=19781.40,DEBITO_MOEDA=0,CREDITO_MOEDA=19781.40
WHERE LANCAMENTO='327100' and  ITEM=3

update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=95356.80,DEBITO_MOEDA=0,CREDITO_MOEDA=95356.80
WHERE LANCAMENTO='327100' and  ITEM=4

update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=95356.80,DEBITO_MOEDA=0,CREDITO_MOEDA=95356.80
WHERE LANCAMENTO='327100' and  ITEM=5




update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=217951.30,DEBITO_MOEDA=0,CREDITO_MOEDA=217951.30
WHERE LANCAMENTO='347223' AND ITEM=1

update CTB_LANCAMENTO_ITEM
set DEBITO=217951.30,CREDITO=0,DEBITO_MOEDA=217951.30,CREDITO_MOEDA=0
WHERE LANCAMENTO='347223' AND ITEM=2



DELETE from CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='371503' AND ITEM=46

delete from CTB_LANCAMENTO_ITEM
WHERE LANCAMENTO='371503' AND ITEM=47


update CTB_LANCAMENTO_ITEM
set DEBITO=0,CREDITO=0,DEBITO_MOEDA=0,CREDITO_MOEDA=0
WHERE  LANCAMENTO in (
'326293',
'326296',
'326309',
'326333',
'326334',
'326336',
'326772',
'326848',
'327835',
'327837',
'327953',
'330147',
'334982',
'337009',
'338361',
'341777',
'342273',
'343668',
'349645',
'350331',
'356540',
'356720',
'357194',
'361528',
'366991',
'368236',
'368546',
'368814',
'373185',
'378482',
'380738',
'381402',
'381962',
'384090',
'384604',
'385368',
'386794',
'388734')


INSERT INTO CTB_BORDERO_PARCELA_CMD
SELECT [EMPRESA]
      ,[LANCAMENTO_MOV]
      ,[ITEM_MOV]
      ,[ID_PARCELA]
      ,[LX_TIPO_OCORRENCIA]
      ,[LANCAMENTO]
      ,[DATA_OCORRENCIA]
      ,[OCORRENCIA_IGNORADA]
      ,[OCORRENCIA]
      ,[MOTIVO_REJEICAO] FROM paulino.dbo.CTB_BORDERO_PARCELA_CMD
WHERE LANCAMENTO='327100' AND ITEM_MOV=3 and LANCAMENTO_MOV='326983'


SELECT * from CTB_BORDERO_PARCELA_CMD
WHERE LANCAMENTO='327100' AND ITEM_MOV=3 and LANCAMENTO_MOV='327053'



SELECT * FROM CTB_BORDERO_PARCELA_NOTA
WHERE LANCAMENTO='327100' AND ITEM_MOV=3


exec sp_executesql N'
/* lx009035spk  CursorAdapter: CUR_V_CTB_LANCAMENTO_01_BORDERO_NOTA_PARC(Alias: v_ctb_lancamento_01_bordero_nota_parc)  */
SELECT CTB_BORDERO_PARCELA_NOTA.OCORRENCIA, CTB_BORDERO_PARCELA_NOTA.EMPRESA,  CTB_BORDERO_PARCELA_NOTA.LAYOUT,  CTB_BORDERO_PARCELA_NOTA.LX_TOPOLOGIA,  CTB_BORDERO_PARCELA_NOTA.ID_PARCELA,  CTB_BORDERO_PARCELA_NOTA.POSICAO,  CTB_BORDERO_PARCELA_NOTA.LX_TIPO_OCORRENCIA,  CTB_BORDERO_PARCELA_NOTA.LANCAMENTO_MOV,  CTB_BORDERO_PARCELA_NOTA.ITEM_MOV,  CTB_BORDERO_PARCELA_NOTA.LANCAMENTO,  CTB_BORDERO_PARCELA_NOTA.VALOR_CAMPO, CTB_BORDERO_LAYOUT_VALIDA.DESCRICAO_CAMPO, CTB_BORDERO_PARCELA_NOTA.PARAMETROS, CTB_BORDERO_LAYOUT_CMD.DESC_COMANDO, CTB_BORDERO_LAYOUT_CMD.DESC_PARAMS, CTB_BORDERO_LAYOUT_CMD.COMANDO, CTB_BORDERO_LAYOUT_CMD.LX_TIPO_CONTEUDO, CTB_BORDERO_LAYOUT_CAMPO.TAMANHO, CTB_BORDERO_LAYOUT_CAMPO.DECIMAIS, CTB_BORDERO_LAYOUT.LX_TIPO_BORDERO, CTB_BORDERO_LAYOUT_CMD.LX_TIPO_DADO FROM CTB_BORDERO_PARCELA_NOTA JOIN CTB_BORDERO_LAYOUT ON CTB_BORDERO_PARCELA_NOTA.LAYOUT=CTB_BORDERO_LAYOUT.LAYOUT JOIN CTB_BORDERO_LAYOUT_CAMPO ON CTB_BORDERO_PARCELA_NOTA.LAYOUT=CTB_BORDERO_LAYOUT_CAMPO.LAYOUT AND CTB_BORDERO_PARCELA_NOTA.LX_TOPOLOGIA=CTB_BORDERO_LAYOUT_CAMPO.LX_TOPOLOGIA AND CTB_BORDERO_PARCELA_NOTA.POSICAO=CTB_BORDERO_LAYOUT_CAMPO.POSICAO JOIN CTB_BORDERO_LAYOUT_CMD ON CTB_BORDERO_LAYOUT_CAMPO.ID_COMANDO=CTB_BORDERO_LAYOUT_CMD.ID_COMANDO LEFT JOIN CTB_BORDERO_LAYOUT_VALIDA ON CTB_BORDERO_PARCELA_NOTA.LAYOUT=CTB_BORDERO_LAYOUT_VALIDA.LAYOUT AND CTB_BORDERO_PARCELA_NOTA.POSICAO=CTB_BORDERO_LAYOUT_VALIDA.POSICAO AND CTB_BORDERO_PARCELA_NOTA.LX_TOPOLOGIA=CTB_BORDERO_LAYOUT_VALIDA.LX_TOPOLOGIA AND CTB_BORDERO_PARCELA_NOTA.VALOR_CAMPO=CTB_BORDERO_LAYOUT_VALIDA.VALOR_CAMPO WHERE CTB_BORDERO_PARCELA_NOTA.EMPRESA = CAST(@P1 AS INT)  AND CTB_BORDERO_PARCELA_NOTA.LANCAMENTO = CAST(@P2 AS INT)',N'@P1 int,@P2 int',1,327100


exec sp_executesql N'
/* lx009035spk  CursorAdapter: CUR_V_CTB_LANCAMENTO_01(Alias: v_ctb_lancamento_01)  */
SELECT CTB_LANCAMENTO.EMPRESA, CTB_LANCAMENTO.LANCAMENTO, CTB_LANCAMENTO.LOTE_LANCAMENTO, CTB_LANCAMENTO.COD_FILIAL,   CTB_LANCAMENTO.DATA_LANCAMENTO, CTB_LANCAMENTO.DATA_DIGITACAO, CTB_LANCAMENTO.DATA_CONCILIADO, CTB_LANCAMENTO.CONCILIADO,   CTB_LANCAMENTO.INDICA_DEPARA, CTB_LANC_PADRAO.PERMITIR_INCLUSAO, EMPRESA.DESC_EMPRESA, FILIAIS.FILIAL, CTB_LANCAMENTO.LANCAMENTO_PADRAO,   CTB_LANC_PADRAO.DESC_LANCAMENTO_PADRAO, CTB_LX_LANCAMENTO_TIPO.DESC_TIPO_LANCAMENTO, CTB_LX_LANCAMENTO_TIPO.CONTROLE_SISTEMA,   CTB_LX_LANCAMENTO_TIPO.SOMENTE_LANC_CONTABIL, CTB_LX_LANCAMENTO_TIPO.INDICA_ID_CONTABIL_TERCEIRO,   CTB_LX_LANCAMENTO_TIPO.INDICADOR_TABELA_ORIGEM, CTB_LX_LANCAMENTO_TIPO.CREDITO_DEBITO,   CTB_LANC_PADRAO.INATIVA, CTB_LANC_PADRAO.LX_TIPO_LANCAMENTO, CTB_LANCAMENTO.TIPO_MOVIMENTO, CTB_MOVIMENTO_TIPO.LX_GRUPO_MOVIMENTO,   CTB_MOVIMENTO_TIPO.DESC_TIPO_MOVIMENTO, CTB_LANCAMENTO.GERADO_INTEGRACAO, CTB_LOTE.DESC_LOTE,   CTB_LOTE.DATA_EXPORTACAO, CTB_LOTE.CONCILIADO AS LOTE_CONCILIADO, CTB_LOTE.DATA_INICIAL, CTB_LOTE.DATA_FINAL,   CTB_LOTE.TIPO_LOTE, CTB_LANCAMENTO.GERADO_VALOR_FINANCEIRO , CTB_LANCAMENTO.USUARIO_ASSINATURA,   CTB_LANCAMENTO.DATA_ASSINATURA, CTB_LANCAMENTO.NUMERO_CORRELATIVO, CTB_LANCAMENTO.TIPO_COMPROVANTE, CTB_COMPROVANTE_TIPO.DESC_TIPO_COMPROVANTE  FROM  CTB_LANCAMENTO INNER JOIN EMPRESA ON  CTB_LANCAMENTO.EMPRESA = EMPRESA.EMPRESA    INNER JOIN CTB_MOVIMENTO_TIPO ON  CTB_LANCAMENTO.TIPO_MOVIMENTO = CTB_MOVIMENTO_TIPO.TIPO_MOVIMENTO    LEFT OUTER JOIN FILIAIS ON  CTB_LANCAMENTO.COD_FILIAL = FILIAIS.COD_FILIAL    LEFT OUTER JOIN CTB_LANC_PADRAO ON  CTB_LANCAMENTO.LANCAMENTO_PADRAO = CTB_LANC_PADRAO.LANCAMENTO_PADRAO    LEFT OUTER JOIN CTB_LX_LANCAMENTO_TIPO ON  CTB_LANC_PADRAO.LX_TIPO_LANCAMENTO = CTB_LX_LANCAMENTO_TIPO.LX_TIPO_LANCAMENTO    LEFT OUTER JOIN CTB_LOTE CTB_LOTE  ON  CTB_LANCAMENTO.LOTE_LANCAMENTO = CTB_LOTE.LOTE_LANCAMENTO LEFT JOIN CTB_COMPROVANTE_TIPO ON CTB_COMPROVANTE_TIPO.TIPO_COMPROVANTE = CTB_LANCAMENTO.TIPO_COMPROVANTE  WHERE str(ctb_lancamento.empresa)+str(ctb_lancamento.lancamento) in (select str(empresa)+str(lancamento) from ctb_bordero where lx_tipo_bordero in (1,2,9,16,17)) AND CTB_LANCAMENTO.LANCAMENTO = @P1 ORDER BY CTB_LANCAMENTO.EMPRESA, CTB_LANCAMENTO.LANCAMENTO',N'@P1 int',327100


exec sp_executesql N'
/* lx009035spk  CursorAdapter: CUR_V_CTB_LANCAMENTO_01_ITEM(Alias: v_ctb_lancamento_01_item)  */
SELECT   CTB_LANCAMENTO_ITEM.ITEM, CTB_LANCAMENTO_ITEM.EMPRESA, CTB_LANCAMENTO_ITEM.LANCAMENTO,  CTB_LANCAMENTO_ITEM.COD_CLIFOR, CTB_LANCAMENTO_ITEM.CONTA_CONTABIL, CTB_LANCAMENTO_ITEM.CREDITO,  CTB_LANCAMENTO_ITEM.DEBITO, CTB_LANCAMENTO_ITEM.HISTORICO, CTB_LANCAMENTO_ITEM.CODIGO_HISTORICO,  CTB_LANCAMENTO_ITEM.RATEIO_CENTRO_CUSTO, CTB_LANCAMENTO_ITEM.CONCILIADO, CTB_LANCAMENTO_ITEM.MOEDA,  CTB_LANCAMENTO_ITEM.DATA_DIGITACAO, CADASTRO_CLI_FOR.NOME_CLIFOR, CTB_CONTA_PLANO.CODIGO_RESUMIDO,  CTB_CONTA_PLANO.DESC_CONTA, CTB_LX_LANCAMENTO_TIPO.DESC_TIPO_LANCAMENTO, CADASTRO_CLI_FOR.RAZAO_SOCIAL,  CADASTRO_CLI_FOR.CGC_CPF, CADASTRO_CLI_FOR.RG_IE, CADASTRO_CLI_FOR.UF, CADASTRO_CLI_FOR.PAIS,  CTB_CONTA_PLANO.DESC_CONTA_REDUZIDA, CTB_CENTRO_CUSTO_RATEIO.DESC_RATEIO_CENTRO_CUSTO,  CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO, CTB_LANCAMENTO_ITEM.PERMITE_ALTERACAO,  CTB_LANCAMENTO_ITEM.DISPARA_FORMULA, CTB_LX_LANCAMENTO_TIPO.CREDITO_DEBITO,  CTB_LX_LANCAMENTO_TIPO.INDICA_ID_CONTABIL_TERCEIRO,CTB_LX_LANCAMENTO_TIPO.SOMENTE_LANC_CONTABIL, CTB_LX_LANCAMENTO_TIPO.INATIVO_PARA_LANCTO_MANUAL, CTB_LANCAMENTO_ITEM.DEBITO_MOEDA,  CTB_LANCAMENTO_ITEM.CREDITO_MOEDA, CTB_LANCAMENTO_ITEM.CAMBIO_NA_DATA, CTB_CONTA_PLANO.TIPO_CONTA,  CTB_LX_LANCAMENTO_TIPO.CONTA_PADRAO,  CTB_LANCAMENTO_ITEM.RATEIO_FILIAL, CTB_FILIAL_RATEIO.DESC_RATEIO_FILIAL, CTB_LANCAMENTO_ITEM.ID_CONTRAPARTIDA,CTB_CONTA_PLANO.BANCO,CTB_LANCAMENTO_ITEM.VALOR_FINANCEIRO, CTB_LANCAMENTO_ITEM.VALOR_FINANCEIRO_PADRAO FROM         CTB_LANCAMENTO_ITEM INNER JOIN CTB_CONTA_PLANO ON CTB_LANCAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL INNER JOIN CTB_LX_LANCAMENTO_TIPO ON  CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO = CTB_LX_LANCAMENTO_TIPO.LX_TIPO_LANCAMENTO LEFT OUTER JOIN CTB_FILIAL_RATEIO ON CTB_LANCAMENTO_ITEM.RATEIO_FILIAL = CTB_FILIAL_RATEIO.RATEIO_FILIAL LEFT OUTER JOIN CADASTRO_CLI_FOR ON CTB_LANCAMENTO_ITEM.COD_CLIFOR = CADASTRO_CLI_FOR.COD_CLIFOR LEFT OUTER JOIN CTB_CENTRO_CUSTO_RATEIO ON  CTB_LANCAMENTO_ITEM.RATEIO_CENTRO_CUSTO = CTB_CENTRO_CUSTO_RATEIO.RATEIO_CENTRO_CUSTO WHERE     CTB_LANCAMENTO_ITEM.EMPRESA = @P1 AND CTB_LANCAMENTO_ITEM.LANCAMENTO = @P2 ORDER BY CTB_LANCAMENTO_ITEM.EMPRESA, CTB_LANCAMENTO_ITEM.CONTA_CONTABIL, CTB_LANCAMENTO_ITEM.COD_CLIFOR,  CTB_LANCAMENTO_ITEM.LANCAMENTO, CTB_LANCAMENTO_ITEM.ITEM',N'@P1 int,@P2 int',1,327100


exec sp_executesql N'
/* lx009035spk  CursorAdapter: CUR_V_CTB_LANCAMENTO_01_BORDERO(Alias: v_ctb_lancamento_01_bordero)  */
SELECT CTB_BORDERO.EMPRESA, CTB_BORDERO.LANCAMENTO, CTB_BORDERO.CONTA_PORTADOR,   CTB_BORDERO.LAYOUT, CTB_BORDERO.PROCESSADO,  CTB_BORDERO.LX_TIPO_BORDERO,   CTB_BORDERO.CONTRATO_TAXA, CTB_BORDERO.CONTRATO_DESAGIO, CTB_BORDERO.DATA_CRIACAO,    CTB_BORDERO.NOME_ARQUIVO, CTB_BORDERO.DATA_COMUNICACAO, CTB_BORDERO.OBS,   CTB_BORDERO_LAYOUT.DESC_LAYOUT,  CTB_BORDERO_LAYOUT.DIRETORIO_ARQUIVO,   CTB_BORDERO_LAYOUT.MASCARA_ARQUIVO, CTB_BORDERO_LAYOUT.SEQUENCIAL_LAYOUT,    CTB_BORDERO_LAYOUT.TAMANHO_REGISTRO, CTB_BORDERO_LAYOUT.LISTA_CODIGO_LIQUIDACAO,   CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA,    CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA_FINAL,   CTB_BORDERO_LAYOUT.INATIVO, CTB_BORDERO_LAYOUT.LOTE,  CTB_CONTA_PLANO.ID_CARTEIRA_COBRANCA,   CTB_CARTEIRA_COBRANCA.DESCONTADA, CTB_CARTEIRA_COBRANCA.CARTEIRA,   CTB_CONTA_PLANO.DESC_CONTA,  CTB_CONTA_PLANO.CODIGO_RESUMIDO, CTB_BORDERO.CONTRATO_IOF,   CTB_BORDERO_LAYOUT.GERAR_NUMERO_BANCARIO, CTB_CONTA_CORRENTE.BANCO,   CTB_CONTA_CORRENTE.AGENCIA, CTB_CONTA_CORRENTE.NUMERO_CONTA_CORRENTE, CTB_BORDERO.ARQUIVO,   CTB_BORDERO_LAYOUT.MASCARA_DATA, CTB_BORDERO_LAYOUT.GERA_LOTE_BANCO,  CTB_BORDERO_LAYOUT.TIPO_VALOR, CTB_BORDERO_LAYOUT.INDICA_TERMINADOR, CTB_BORDERO_LAYOUT.TRANSACAO, CTB_BORDERO.DATA_LANC_DESCONTO, CTB_BORDERO.TAXA_DESCONTO, CTB_BORDERO.VALOR_DESCONTO, CTB_BORDERO.SEQUENCIAL_LAYOUT AS SEQUENCIAL_LAYOUT_BORDERO  FROM CTB_BORDERO   JOIN CTB_BORDERO_LAYOUT   ON CTB_BORDERO_LAYOUT.LAYOUT=CTB_BORDERO.LAYOUT   LEFT JOIN CTB_CONTA_PLANO   ON CTB_BORDERO.CONTA_PORTADOR=CTB_CONTA_PLANO.CONTA_CONTABIL   LEFT JOIN CTB_CARTEIRA_COBRANCA   ON CTB_CONTA_PLANO.ID_CARTEIRA_COBRANCA=CTB_CARTEIRA_COBRANCA.ID_CARTEIRA_COBRANCA   LEFT JOIN CTB_CONTA_LAYOUT   ON CTB_BORDERO.LAYOUT=CTB_CONTA_LAYOUT.LAYOUT   AND CTB_BORDERO.CONTA_PORTADOR=CTB_CONTA_LAYOUT.CONTA_PORTADOR   LEFT JOIN CTB_CONTA_PLANO CTB_CONTA_CORRENTE   ON CTB_CONTA_LAYOUT.CONTA_CORRENTE=CTB_CONTA_CORRENTE.CONTA_CONTABIL   WHERE     (CTB_BORDERO.EMPRESA = CAST(@P1 AS INT))   AND (CTB_BORDERO.LANCAMENTO = CAST(@P2 AS INT))',N'@P1 int,@P2 int',1,327100


exec sp_executesql N'
/* lx009035spk  CursorAdapter: CUR_V_CTB_LANCAMENTO_01_BORDERO_REC_PARC(Alias: v_ctb_lancamento_01_bordero_rec_parc)  */
SELECT CTB_BORDERO_PARCELA_CMD.OCORRENCIA,CTB_BORDERO_PARCELA_CMD.EMPRESA,CTB_BORDERO_PARCELA_CMD.LANCAMENTO_MOV,CTB_BORDERO_PARCELA_CMD.OCORRENCIA_IGNORADA,CTB_BORDERO_PARCELA_CMD.ITEM_MOV,         CTB_BORDERO_PARCELA_CMD.ID_PARCELA,  CTB_BORDERO_PARCELA_CMD.LX_TIPO_OCORRENCIA,CTB_BORDERO_PARCELA_CMD.DATA_OCORRENCIA,CTB_BORDERO_PARCELA_CMD.LANCAMENTO,         CTB_LX_BORDERO_OCORRENCIA.DESCRICAO_OCORRENCIA,CTB_A_RECEBER_PARCELA.VENCIMENTO,CTB_A_RECEBER_PARCELA.NUMERO_BANCARIO,  CTB_A_RECEBER_PARCELA.VALOR_ORIGINAL_PADRAO,         CTB_A_RECEBER_PARCELA.VALOR_ORIGINAL,         CTB_A_RECEBER_PARCELA.DIAS_PRORROGADOS,CTB_A_RECEBER_PARCELA.DESCONTO_VENC,CTB_A_RECEBER_PARCELA.DATA_DESCONTO_VENC,CTB_A_RECEBER_PARCELA.AGENCIA,  CTB_A_RECEBER_FATURA.FATURA,         CTB_A_RECEBER_FATURA.LX_TIPO_DOCUMENTO,DT.TIPO_DOCUMENTO,CTB_A_RECEBER_FATURA.CODIGO_CONSUMIDOR,CTB_A_RECEBER_FATURA.EMISSAO,CTB_A_RECEBER_FATURA.DOCUMENTO,CTB_A_RECEBER_FATURA.FATURA_IMPRESSA,           CTB_A_RECEBER_FATURA.POSSUI_SAIDA,CTB_A_RECEBER_FATURA.COMISSAO_GERENTE,CTB_A_RECEBER_FATURA.PORCENTAGEM_ACERTO,CTB_A_RECEBER_FATURA.COMISSAO,CTB_A_RECEBER_FATURA.CAMBIO_NA_DATA_EMISSAO,         CTB_A_RECEBER_FATURA.JUROS_POR_ATRASO,  CTB_A_RECEBER_FATURA.MULTA_POR_ATRASO,CTB_A_RECEBER_FATURA.SERIE,CTB_A_RECEBER_FATURA.NUMERO_PARCELAS,CTB_A_RECEBER_FATURA.COD_REPRESENTANTE,         CTB_A_RECEBER_FATURA.COD_REPRESENTANTE_GERENTE,CTB_A_RECEBER_FATURA.MOEDA,  CTB_A_RECEBER_FATURA.COD_CLIFOR,CTB_A_RECEBER_FATURA.COD_EMISSOR,CAST(ISNULL(CV.CLIENTE_VAREJO, A.NOME_CLIFOR) AS VARCHAR(25)) NOME_CLIFOR,CAST(ISNULL(CV.CPF_CGC, A.CGC_CPF) AS VARCHAR(19)) CGC_CPF,CAST(ISNULL(CV.RG_IE,   A.RG_IE) AS VARCHAR(19)) RG_IE,         CAST(ISNULL(CV.PF_PJ, A.PJ_PF) AS BIT) PJ_PF,ISNULL(CV.CADASTRAMENTO, A.CADASTRAMENTO) CADASTRAMENTO,CAST(ISNULL(CV.CODIGO_CONTATO, A.CONTATO) AS VARCHAR(40)) CONTATO,         ISNULL(CV.CLIENTE_VAREJO,   A.RAZAO_SOCIAL) RAZAO_SOCIAL,CAST(CASE                WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO, '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO,   '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.ENDERECO, '''')) + '' ''), '''')                ELSE A.ENDERECO                END AS VARCHAR(100)) ENDERECO,ISNULL(CV.NUMERO, A.NUMERO) NUMERO,  ISNULL(CV.COMPLEMENTO, A.COMPLEMENTO) COMPLEMENTO,ISNULL(CV.BAIRRO, A.BAIRRO) BAIRRO,ISNULL(CV.CIDADE, A.CIDADE) CIDADE,         ISNULL (CV.UF, A.UF) UF,ISNULL(CV.CEP, A.CEP) CEP,ISNULL(CV.PAIS, A.PAIS) PAIS,CAST(A.DDI AS CHAR(5)) DDI,ISNULL(CV.DDD,   A.DDD1) DDD1,ISNULL(CV.TELEFONE, A.TELEFONE1) TELEFONE1,CAST(A.TELEFONE2 AS VARCHAR(10)) TELEFONE2,CAST(ISNULL(CV.FAX, A.FAX) AS VARCHAR(10)) FAX,CAST(A.RAMAL1 AS CHAR(5)) RAMAL1,CAST(A.DDD2 AS CHAR(5)) DDD2,  CAST(A.RAMAL2 AS CHAR(5)) RAMAL2,         CAST(A.DDDFAX AS CHAR(5)) DDDFAX,CAST(ISNULL(CAST(CV.EMAIL AS CHAR(40)), A.EMAIL) AS CHAR(40)) EMAIL,CAST(CASE                WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO,   '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO, '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.ENDERECO,   '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.NUMERO, '''')) + '' '')                                                         + RTRIM(ISNULL(CV.COMPLEMENTO, '''')),   '''')                ELSE LTRIM(RTRIM(ISNULL(CV.ENDERECO, A.COBRANCA_ENDERECO)))                     + '', ''                     + LTRIM(RTRIM(ISNULL(CV.NUMERO, ISNULL(A.COBRANCA_NUMERO, '''') )))                     + '',   ''                     + LTRIM(RTRIM(ISNULL(CV.COMPLEMENTO, ISNULL(A.COBRANCA_COMPLEMENTO, ''''))) )                END AS CHAR(100)) COBRANCA_ENDERECO,ISNULL(CV.CIDADE, A.COBRANCA_CIDADE) COBRANCA_CIDADE,ISNULL(CV.BAIRRO,   A.COBRANCA_BAIRRO) COBRANCA_BAIRRO,ISNULL(CV.UF, A.COBRANCA_UF) COBRANCA_UF,         ISNULL(CV.CEP, A.COBRANCA_CEP) COBRANCA_CEP,ISNULL(CV.TELEFONE, A.COBRANCA_TELEFONE) COBRANCA_TELEFONE,CAST(A.COBRANCA_DDI AS CHAR(5)) COBRANCA_DDI,ISNULL(CV.DDD,   A.COBRANCA_DDD) COBRANCA_DDD,         ISNULL(CV.CPF_CGC, A.COBRANCA_CGC) COBRANCA_CGC,ISNULL(CV.RG_IE, A.COBRANCA_IE) COBRANCA_IE,ISNULL(CV.PAIS, A.COBRANCA_PAIS) COBRANCA_PAIS,  CAST(CASE                WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO, '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO,   '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.ENDERECO, '''')) + '' '')                                                         + LTRIM(RTRIM(ISNULL(CV.NUMERO,   '''')) + '' '')                                                         + RTRIM(ISNULL(CV.COMPLEMENTO, '''')), '''')                ELSE A.ENTREGA_ENDERECO                END AS CHAR(100)) ENTREGA_ENDERECO,ISNULL(CV.CIDADE, A.ENTREGA_CIDADE) ENTREGA_CIDADE,  ISNULL(CV.UF, A.ENTREGA_UF) ENTREGA_UF,ISNULL(CV.BAIRRO, A.ENTREGA_BAIRRO) ENTREGA_BAIRRO,         ISNULL(CV.CEP, A.ENTREGA_CEP) ENTREGA_CEP,CAST(A.ENTREGA_DDI AS CHAR(5)) ENTREGA_DDI,ISNULL(CV.DDD, A.ENTREGA_DDD) ENTREGA_DDD,ISNULL(CV.TELEFONE,   A.ENTREGA_TELEFONE) ENTREGA_TELEFONE,         ISNULL(CV.CPF_CGC, A.ENTREGA_CGC) ENTREGA_CGC,ISNULL(CV.RG_IE, A.ENTREGA_IE) ENTREGA_IE,ISNULL(CV.PAIS, A.ENTREGA_PAIS) ENTREGA_PAIS,CAST(A.CC_AGENCIA AS CHAR(20)) CC_AGENCIA,           CAST(A.CC_CONTA AS CHAR(20)) CC_CONTA,CAST(A.CC_NOME_AGENCIA AS CHAR(30)) CC_NOME_AGENCIA,SALDO.VENCIMENTO_REAL,SALDO.VALOR_A_RECEBER,SALDO.VALOR_A_RECEBER_PADRAO,SALDO.SALDO_PRINCIPAL_DEVIDO,         SALDO.SALDO_MULTA_GERADA,  SALDO.SALDO_JUROS_GERADO,SALDO.SALDO_DESCONTO_CONCEDIDO,SALDO.TOTAL_PRINCIPAL_RECEBIDO,SALDO.TOTAL_MULTA_PAGA,SALDO.TOTAL_JUROS_PAGO,SALDO.TOTAL_DESCONTO_EFETIVADO,         CTB_BORDERO_LAYOUT.LAYOUT,CTB_BORDERO_LAYOUT.DESC_LAYOUT,  CTB_BORDERO_LAYOUT.DIRETORIO_ARQUIVO,CTB_BORDERO_LAYOUT.MASCARA_ARQUIVO,CTB_BORDERO_LAYOUT.SEQUENCIAL_LAYOUT,         CTB_BORDERO_LAYOUT.TAMANHO_REGISTRO,CTB_BORDERO_LAYOUT.LISTA_CODIGO_LIQUIDACAO,CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA,  CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA_FINAL,         CTB_BORDERO_LAYOUT.INATIVO,         CTB_BORDERO_LAYOUT.LOTE,CTB_CONTA_LAYOUT.CONTA_PORTADOR,CTB_CONTA_LAYOUT.CONTA_CORRENTE,CTB_CONTA_CORRENTE.BANCO AS BANCO_CONTA_CORRENTE,  CTB_CONTA_CORRENTE.AGENCIA AS AGENCIA_CONTA_CORRENTE,         CTB_CONTA_CORRENTE.NUMERO_CONTA_CORRENTE,FILIAL.CGC_CPF CNPJ_FILIAL,                DATA_INI = CONVERT(VARCHAR(6), MIN(CTB_A_RECEBER_FATURA.EMISSAO), 112)                           + ''01'',  DATA_FIM = DATEADD(D, -1, DATEADD(M, 1, CONVERT(VARCHAR(6), MAX(CTB_A_RECEBER_FATURA.EMISSAO), 112)                                                                          + ''01'')),CRM.DATA_PAGAMENTO,  FATURA_10 = CASE                                                                                                                    WHEN LEN(RTRIM(LTRIM(FATURA))                                                                                                                               + RTRIM(LTRIM(CTB_A_RECEBER_PARCELA.ID_PARCELA))) > 10 THEN                                                                                                                    ''#D'' + RTRIM(LTRIM(FATURA))                                                                                                                      + RTRIM(LTRIM(CTB_A_RECEBER_PARCELA.ID_PARCELA))                                                                                                                    END,DATA_CAD_CLIENTE = A.CADASTRAMENTO,  TIPO_CLIENTE = CASE                                                                                                                                                                          WHEN A.INATIVO = 1 THEN ''3''                                                                                                                                                                            ELSE                                                                                                                                                                              CASE                                                                                                                                                                              WHEN   DATEDIFF(YY,                                                                                                                                                                                   A.CADASTRAMENTO,                                                                                                                                                                                     GETDATE()) >= 1 THEN                                                                                                                                                                                ''1''                                                                                                                                                                                ELSE ''2''                                                                                                                                                                            END                                                                                                                                                                          END,ENVIADO_SERASA = 0,         DATA_NASCIMENTO = ISNULL(CV.ANIVERSARIO, A.ANIVERSARIO),  SEXO = ISNULL(CV.SEXO,   '''')  FROM   CTB_BORDERO_PARCELA_CMD         INNER JOIN CTB_A_RECEBER_PARCELA                 ON CTB_BORDERO_PARCELA_CMD.EMPRESA = CTB_A_RECEBER_PARCELA.EMPRESA                    AND CTB_BORDERO_PARCELA_CMD.LANCAMENTO_MOV =   CTB_A_RECEBER_PARCELA.LANCAMENTO                    AND CTB_BORDERO_PARCELA_CMD.ITEM_MOV = CTB_A_RECEBER_PARCELA.ITEM                    AND CTB_BORDERO_PARCELA_CMD.ID_PARCELA = CTB_A_RECEBER_PARCELA.ID_PARCELA         INNER JOIN   CTB_A_RECEBER_FATURA                 ON CTB_A_RECEBER_PARCELA.EMPRESA = CTB_A_RECEBER_FATURA.EMPRESA                    AND CTB_A_RECEBER_PARCELA.LANCAMENTO = CTB_A_RECEBER_FATURA.LANCAMENTO                    AND CTB_A_RECEBER_PARCELA.ITEM =   CTB_A_RECEBER_FATURA.ITEM         LEFT JOIN CTB_A_RECEBER_MOV CRM                ON CTB_A_RECEBER_PARCELA.EMPRESA = CRM.EMPRESA                   AND CTB_A_RECEBER_PARCELA.LANCAMENTO = CRM.LANCAMENTO_MOV                   AND   CTB_A_RECEBER_PARCELA.ITEM = CRM.ITEM_MOV                   AND 
CTB_A_RECEBER_PARCELA.ID_PARCELA = CRM.ID_PARCELA         INNER JOIN CADASTRO_CLI_FOR A                 ON CTB_A_RECEBER_FATURA.COD_CLIFOR = A.COD_CLIFOR         INNER JOIN   CADASTRO_CLI_FOR 
FILIAL                 ON CTB_A_RECEBER_FATURA.COD_EMISSOR = FILIAL.COD_CLIFOR         INNER JOIN CTB_LX_BORDERO_OCORRENCIA                 ON CTB_BORDERO_PARCELA_CMD.LX_TIPO_OCORRENCIA = 
CTB_LX_BORDERO_OCORRENCIA.LX_TIPO_OCORRENCIA           INNER JOIN W_CTB_A_RECEBER_PARCELA_SALDO SALDO                 ON CTB_A_RECEBER_PARCELA.EMPRESA = SALDO.EMPRESA                    AND 
CTB_A_RECEBER_PARCELA.LANCAMENTO = SALDO.LANCAMENTO                    AND CTB_A_RECEBER_PARCELA.ITEM =   SALDO.ITEM                    AND CTB_A_RECEBER_PARCELA.ID_PARCELA = SALDO.ID_PARCELA         
INNER JOIN CTB_BORDERO                 ON CTB_BORDERO_PARCELA_CMD.EMPRESA = CTB_BORDERO.EMPRESA                    AND CTB_BORDERO_PARCELA_CMD.LANCAMENTO =   CTB_BORDERO.LANCAMENTO         INNER JOIN 
CTB_BORDERO_LAYOUT                 ON CTB_BORDERO.LAYOUT = CTB_BORDERO_LAYOUT.LAYOUT         INNER JOIN CTB_CONTA_LAYOUT                 ON CTB_BORDERO.LAYOUT = 
CTB_CONTA_LAYOUT.LAYOUT                    AND   CTB_BORDERO.CONTA_PORTADOR = CTB_CONTA_LAYOUT.CONTA_PORTADOR         INNER JOIN CTB_CONTA_PLANO CTB_CONTA_CORRENTE                 ON 
CTB_CONTA_LAYOUT.CONTA_CORRENTE = CTB_CONTA_CORRENTE.CONTA_CONTABIL         LEFT JOIN CLIENTES_VAREJO CV                  ON CTB_A_RECEBER_FATURA.CODIGO_CONSUMIDOR = CV.CODIGO_CLIENTE         LEFT JOIN 
CTB_LX_DOCUMENTO_TIPO DT                ON CTB_A_RECEBER_FATURA.LX_TIPO_DOCUMENTO = DT.LX_TIPO_DOCUMENTO  WHERE CTB_BORDERO_PARCELA_CMD.EMPRESA =   @P1 AND   CTB_BORDERO_PARCELA_CMD.LANCAMENTO = 
@P2        GROUP  BY CTB_BORDERO_PARCELA_CMD.OCORRENCIA,CTB_BORDERO_PARCELA_CMD.EMPRESA,CTB_BORDERO_PARCELA_CMD.LANCAMENTO_MOV,  
CTB_BORDERO_PARCELA_CMD.OCORRENCIA_IGNORADA,CTB_BORDERO_PARCELA_CMD.ITEM_MOV,  
CTB_BORDERO_PARCELA_CMD.ID_PARCELA,CTB_BORDERO_PARCELA_CMD.LX_TIPO_OCORRENCIA,CTB_BORDERO_PARCELA_CMD.DATA_OCORRENCIA,CTB_BORDERO_PARCELA_CMD.LANCAMENTO,  CTB_LX_BORDERO_OCORRENCIA.DESCRICAO_OCORRENCIA,  CTB_A_RECEBER_PARCELA.VENCIMENTO,CTB_A_RECEBER_PARCELA.NUMERO_BANCARIO,CTB_A_RECEBER_PARCELA.VALOR_ORIGINAL_PADRAO,CTB_A_RECEBER_PARCELA.VALOR_ORIGINAL,CTB_A_RECEBER_PARCELA.DIAS_PRORROGADOS,    CTB_A_RECEBER_PARCELA.DESCONTO_VENC,CTB_A_RECEBER_PARCELA.DATA_DESCONTO_VENC,CTB_A_RECEBER_PARCELA.AGENCIA,CTB_A_RECEBER_FATURA.FATURA,CTB_A_RECEBER_FATURA.LX_TIPO_DOCUMENTO,  CTB_A_RECEBER_FATURA.CODIGO_CONSUMIDOR,CTB_A_RECEBER_FATURA.EMISSAO,  CTB_A_RECEBER_FATURA.DOCUMENTO,CTB_A_RECEBER_FATURA.FATURA_IMPRESSA,CTB_A_RECEBER_FATURA.POSSUI_SAIDA,  CTB_A_RECEBER_FATURA.COMISSAO_GERENTE,  CTB_A_RECEBER_FATURA.PORCENTAGEM_ACERTO,CTB_A_RECEBER_FATURA.COMISSAO,  CTB_A_RECEBER_FATURA.CAMBIO_NA_DATA_EMISSAO,CTB_A_RECEBER_FATURA.JUROS_POR_ATRASO,CTB_A_RECEBER_FATURA.MULTA_POR_ATRASO,  CTB_A_RECEBER_FATURA.SERIE,CTB_A_RECEBER_FATURA.NUMERO_PARCELAS,CTB_A_RECEBER_FATURA.COD_REPRESENTANTE,  CTB_A_RECEBER_FATURA.COD_REPRESENTANTE_GERENTE,CTB_A_RECEBER_FATURA.MOEDA,  CTB_A_RECEBER_FATURA.COD_CLIFOR,CTB_A_RECEBER_FATURA.COD_EMISSOR,CAST(ISNULL(CV.CLIENTE_VAREJO, A.NOME_CLIFOR) AS VARCHAR(25)),CAST(ISNULL(CV.CPF_CGC,   A.CGC_CPF) AS VARCHAR(19)),CAST(ISNULL(CV.RG_IE, A.RG_IE) AS VARCHAR(19)),CAST(ISNULL(CV.PF_PJ, A.PJ_PF) AS BIT),ISNULL(CV.CADASTRAMENTO, A.CADASTRAMENTO),CAST(ISNULL(CV.CODIGO_CONTATO, A.CONTATO) AS VARCHAR(40)),  ISNULL(CV.CLIENTE_VAREJO,   A.RAZAO_SOCIAL),CAST(CASE                   WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO, '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO,   '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.ENDERECO, '''')) + '' ''), '''')                   ELSE A.ENDERECO                 END AS VARCHAR(100)),ISNULL(CV.NUMERO, A.NUMERO),ISNULL(CV.COMPLEMENTO,   A.COMPLEMENTO),ISNULL(CV.BAIRRO, A.BAIRRO),ISNULL(CV.CIDADE, A.CIDADE),ISNULL(CV.UF, A.UF),ISNULL(CV.CEP, A.CEP),  ISNULL(CV.PAIS, A.PAIS),CAST(A.DDI AS CHAR(5)),ISNULL(CV.DDD, A.DDD1),ISNULL(CV.TELEFONE, A.TELEFONE1),  CAST(A.TELEFONE2 AS VARCHAR(10)),CAST(ISNULL(CV.FAX, A.FAX) AS VARCHAR(10)),CAST(A.RAMAL1 AS CHAR(5)),CAST(A.DDD2 AS CHAR(5)),CAST(A.RAMAL2 AS CHAR(5)),CAST(A.DDDFAX AS CHAR(5)),CAST(ISNULL(CAST(CV.EMAIL AS CHAR(40)), A.EMAIL) AS CHAR(40)),  CAST(CASE                   WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO, '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO,   '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.ENDERECO, '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.NUMERO,   '''')) + '' '')                                                            + RTRIM(ISNULL(CV.COMPLEMENTO, '''')), '''')                   ELSE LTRIM(RTRIM(ISNULL(CV.ENDERECO, A.COBRANCA_ENDERECO)))                        + '',   ''                        + LTRIM(RTRIM(ISNULL(CV.NUMERO, ISNULL(A.COBRANCA_NUMERO, ''''))))                        + '',      ''                        + LTRIM(RTRIM(ISNULL(CV.COMPLEMENTO, ISNULL(A.COBRANCA_COMPLEMENTO,   ''''))) )                 END AS CHAR(100)),ISNULL(CV.CIDADE, A.COBRANCA_CIDADE),ISNULL(CV.BAIRRO, A.COBRANCA_BAIRRO),ISNULL(CV.UF, A.COBRANCA_UF),ISNULL(CV.CEP, A.COBRANCA_CEP),  ISNULL(CV.TELEFONE, A.COBRANCA_TELEFONE),  CAST(A.COBRANCA_DDI AS CHAR(5)),ISNULL(CV.DDD, A.COBRANCA_DDD),ISNULL(CV.CPF_CGC, A.COBRANCA_CGC),ISNULL(CV.RG_IE, A.COBRANCA_IE),  ISNULL(CV.PAIS, A.COBRANCA_PAIS),  CAST(CASE                   WHEN CV.ENDERECO IS NOT NULL THEN ISNULL(LTRIM(RTRIM(ISNULL(CV.TIPO_LOGRADOURO, '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.LOGRADOURO,   '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.ENDERECO, '''')) + '' '')                                                            + LTRIM(RTRIM(ISNULL(CV.NUMERO,   '''')) + '' '')                                                            + RTRIM(ISNULL(CV.COMPLEMENTO, '''')), '''')                   ELSE A.ENTREGA_ENDERECO                 END AS CHAR(100)),ISNULL(CV.CIDADE, A.ENTREGA_CIDADE),ISNULL(CV.UF,   A.ENTREGA_UF),ISNULL(CV.BAIRRO, A.ENTREGA_BAIRRO),ISNULL(CV.CEP, A.ENTREGA_CEP),CAST(A.ENTREGA_DDI AS CHAR(5)),ISNULL  (CV.DDD, A.ENTREGA_DDD),ISNULL(CV.TELEFONE, A.ENTREGA_TELEFONE),ISNULL(CV.CPF_CGC, A.ENTREGA_CGC),ISNULL(CV.RG_IE, A.ENTREGA_IE),  ISNULL(CV.PAIS, A.ENTREGA_PAIS),CAST(A.CC_AGENCIA AS CHAR(20)),  CAST(A.CC_CONTA AS CHAR(20)),CAST(A.CC_NOME_AGENCIA AS CHAR(30)),SALDO.VENCIMENTO_REAL,SALDO.VALOR_A_RECEBER,SALDO.VALOR_A_RECEBER_PADRAO,SALDO.SALDO_PRINCIPAL_DEVIDO,  SALDO.SALDO_MULTA_GERADA,  SALDO.SALDO_JUROS_GERADO,SALDO.SALDO_DESCONTO_CONCEDIDO,SALDO.TOTAL_PRINCIPAL_RECEBIDO,SALDO.TOTAL_MULTA_PAGA,SALDO.TOTAL_JUROS_PAGO,SALDO.TOTAL_DESCONTO_EFETIVADO,CTB_BORDERO_LAYOUT.LAYOUT,  CTB_BORDERO_LAYOUT.DESC_LAYOUT,  CTB_BORDERO_LAYOUT.DIRETORIO_ARQUIVO,CTB_BORDERO_LAYOUT.MASCARA_ARQUIVO,CTB_BORDERO_LAYOUT.SEQUENCIAL_LAYOUT,CTB_BORDERO_LAYOUT.TAMANHO_REGISTRO,  CTB_BORDERO_LAYOUT.LISTA_CODIGO_LIQUIDACAO,CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA,  CTB_BORDERO_LAYOUT.SEQUENCIAL_NUMERO_BOLETA_FINAL,CTB_BORDERO_LAYOUT.INATIVO,CTB_BORDERO_LAYOUT.LOTE,  CTB_CONTA_LAYOUT.CONTA_PORTADOR,  CTB_CONTA_LAYOUT.CONTA_CORRENTE,CTB_CONTA_CORRENTE.BANCO,CTB_CONTA_CORRENTE.AGENCIA,  CTB_CONTA_CORRENTE.NUMERO_CONTA_CORRENTE,FILIAL.CGC_CPF,CRM.DATA_PAGAMENTO,A.CADASTRAMENTO,A.INATIVO,  CTB_A_RECEBER_PARCELA.ID_PARCELA,CV.ENVIADO_SERASA,CV.ANIVERSARIO,A.ANIVERSARIO,CV.SEXO,DT.TIPO_DOCUMENTO,CV.COMPLEMENTO,CV.NUMERO,CV.ENDERECO,  CV.LOGRADOURO,CV.TIPO_LOGRADOURO,A.COBRANCA_ENDERECO,  A.COBRANCA_NUMERO,  A.COBRANCA_COMPLEMENTO   ',N'@P1 int,@P2 int',1,327100
