select pedido,PEDIDO_EXTERNO,EMISSAO,CADASTRAMENTO from VENDAS
WHERE TOT_QTDE_ORIGINAL=0 and TOT_VALOR_ORIGINAL=0 and TABELA_FILHA='VENDAS_PRODUTO'
order by EMISSAO


DELETE from VENDAS
WHERE TOT_QTDE_ORIGINAL=0 and TOT_VALOR_ORIGINAL=0 and TABELA_FILHA='VENDAS_PRODUTO'

SELECT * FROM VENDAS_LOTE_COPIA_PEDIDO
WHERE PEDIDO_EXTERNO='X001.001452'

