--- EXECUÇÃO NO EXCEL GO E VAREJO
EXEC SP_ORDEM_PRODUCAO_MATERIAIS_DISPONIVEIS_GO_VAREJO
SELECT ORDEM_PRODUCAO,QTDE_O,FASE_PRODUCAO,SETOR_PRODUCAO,PRODUTO,COR_PRODUTO,RECURSO_PRODUTIVO 
FROM ORDEM_PRODUCAO_NA_FASE_PCP_GO_VAREJO A
WHERE NOT EXISTS(SELECT * FROM ORDEM_PRODUCAO_COM_PENDENCIAS_GO_VAREJO WHERE ORDEM_PRODUCAO=A.ORDEM_PRODUCAO)