SELECT GRUPOS.RECURSO_PRODUTIVO,MATERIAIS.DESC_MATERIAL,  ESTOQUE_MATERIAIS.QTDE_ESTOQUE,PRODUCAO_RESERVA.* 
FROM PRODUCAO_RESERVA
JOIN ESTOQUE_MATERIAIS ON ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL
JOIN MATERIAIS ON MATERIAIS.MATERIAL = ESTOQUE_MATERIAIS.MATERIAL
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_RESERVA.ORDEM_PRODUCAO
JOIN (
SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS
WHERE FASE_PRODUCAO='007'
) AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO 
WHERE RESERVA>0 AND ESTOQUE_MATERIAIS.FILIAL='DR VAREJO'



SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS
WHERE FASE_PRODUCAO='007'
