select C.GRUPO_PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.EMISSAO,A.QTDE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - ((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END )))
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
WHERE B.EMISSAO >='20120101' AND B.EMISSAO <= '20141231' AND A.TIPO_OPERACAO='V' AND B.FILIAL='DR VAREJO' 






