use SIGMA

-- EXECUTAR ANTES DE FAZER O PROCESSO DE IMPORTAÇÃO DO XML DA NFE
EXEC SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS 'SIGMA ATHENA'

EXEC SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS 'SIGMA CONDOMINIO'

EXEC SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS 'SIGMA'


-- IMPORTA FATURAMENTO DA DR PARA OFICINA
EXEC IMPORTA_FATURAMENTO_DR_PARA_OFICINA 'SIGMA ATHENA','SIGMA ATHENA'

EXEC IMPORTA_FATURAMENTO_DR_PARA_OFICINA 'SIGMA CONDOMINIO','SIGMA CONDOMINIO'

EXEC IMPORTA_FATURAMENTO_DR_PARA_OFICINA 'SIGMA','SIGMA'


SELECT * FROM DRLINGERIE.DBO.FATURAMENTO
WHERE NF_SAIDA='0000495' AND SERIE_NF='112'

SELECT * FROM CADASTRO_CLI_FOR
WHERE NOME_CLIFOR='D.R. LINGERIE            '



