select D.DESC_NATUREZA, B.FILIAL,C.GRIFFE, C.GRUPO_PRODUTO,A.GERENTE,A.REPRESENTANTE,E.PAIS,E.RAZAO_SOCIAL, A.NOME_CLIFOR,A.EMISSAO,A.MPADRAO_VALOR_LIQUIDO,A.QTDE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - ((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END )))
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
JOIN NATUREZAS_SAIDAS D WITH (NOLOCK) ON D.NATUREZA_SAIDA=B.NATUREZA_SAIDA
JOIN CADASTRO_CLI_FOR E WITH (NOLOCK) ON E.NOME_CLIFOR=A.NOME_CLIFOR
WHERE B.EMISSAO >='20150101' AND B.EMISSAO <= '20151231' AND A.TIPO_OPERACAO='V' AND D.DESC_NATUREZA LIKE '%VENDA%EXP%'