SELECT CNPJ=SUBSTRING(B.CGC_CPF,1,8), C.MATRIZ_CLIENTE ,MPADRAO_VALOR_TOTAL=SUM(A.MPADRAO_VALOR_TOTAL)
FROM FATURAMENTO A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.NOME_CLIFOR
JOIN CLIENTES_ATACADO C ON C.CLIENTE_ATACADO=A.NOME_CLIFOR
JOIN NATUREZAS_SAIDAS D ON D.NATUREZA_SAIDA=A.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20160101' AND '20161231' AND A.FILIAL = 'D.R. LINGERIE' AND D.TIPO_OPERACAO='V'
GROUP BY SUBSTRING(B.CGC_CPF,1,8),C.MATRIZ_CLIENTE
UNION ALL
SELECT CNPJ='00000000',MATRIZ_CLIENTE='VAREJO', MPADRAO_VALOR_TOTAL=SUM(A.MPADRAO_VALOR_TOTAL)
FROM FATURAMENTO A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.NOME_CLIFOR
JOIN CLIENTES_ATACADO C ON C.CLIENTE_ATACADO=A.NOME_CLIFOR
JOIN NATUREZAS_SAIDAS D ON D.NATUREZA_SAIDA=A.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20160101' AND '20161231' AND A.FILIAL = 'DR VAREJO' AND D.TIPO_OPERACAO='V'
