SELECT faturamento.TIPO_FATURAMENTO, FATURAMENTO.EMISSAO,FATURAMENTO.NF_SAIDA,FATURAMENTO.SERIE_NF,FATURAMENTO.NOME_CLIFOR,
FATURAMENTO_PROD.PEDIDO,VENDAS.PERIODO_PCP,QTDE=SUM(FATURAMENTO_PROD.QTDE) 
FROM FATURAMENTO_PROD
JOIN FATURAMENTO ON FATURAMENTO.NF_SAIDA=FATURAMENTO_PROD.NF_SAIDA
JOIN VENDAS ON VENDAS.PEDIDO = FATURAMENTO_PROD.PEDIDO
WHERE VENDAS.PERIODO_PCP LIKE '2013 FEVEREIRO' AND FATURAMENTO.TABELA_FILHA='FATURAMENTO_PROD' AND 
FATURAMENTO.EMISSAO>='20130101' AND 
FATURAMENTO.EMISSAO<='20130131'
GROUP BY faturamento.TIPO_FATURAMENTO,FATURAMENTO.EMISSAO,FATURAMENTO.NF_SAIDA,FATURAMENTO.SERIE_NF,FATURAMENTO.NOME_CLIFOR,
FATURAMENTO_PROD.PEDIDO,VENDAS.PERIODO_PCP

