UPDATE A
SET A.QTDE_FALTAS=napsi_tbl_relacao_oficinas.qtde_faltas_dia, A.QTDE_OPERADOR=napsi_tbl_relacao_oficinas.qtde_oper_dia,A.QTDE_FERIAS=napsi_tbl_relacao_oficinas.qtde_oper_afastados
FROM LDR_METAS_OFICINA_GRUPO_NOVA A
JOIN PRODUCAO_RECURSOS ON PRODUCAO_RECURSOS.DESC_RECURSO=A.DESC_RECURSO
JOIN napsi_tbl_relacao_oficinas ON napsi_tbl_relacao_oficinas.desc_recurso_produtivo=PRODUCAO_RECURSOS.RECURSO_PRODUTIVO
WHERE A.DESC_SETOR_PRODUCAO IN('OFICINA ATHENA','OFICINA FIORUCCI CONFECCOES','OFICINA AFRODITE CANINDE') AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103) AND napsi_tbl_relacao_oficinas.qtde_oper_dia>0

SELECT * FROM napsi_tbl_relacao_oficinas


SELECT napsi_tbl_relacao_oficinas.desc_recurso_produtivo,napsi_tbl_relacao_oficinas.qtde_faltas_dia,napsi_tbl_relacao_oficinas.qtde_oper_dia,napsi_tbl_relacao_oficinas.qtde_oper_afastados,LDR_METAS_OFICINA_GRUPO_NOVA.QTDE_OPERADOR, 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO
FROM LDR_METAS_OFICINA_GRUPO_NOVA
JOIN PRODUCAO_RECURSOS ON PRODUCAO_RECURSOS.DESC_RECURSO=LDR_METAS_OFICINA_GRUPO_NOVA.DESC_RECURSO
JOIN napsi_tbl_relacao_oficinas ON napsi_tbl_relacao_oficinas.desc_recurso_produtivo=PRODUCAO_RECURSOS.RECURSO_PRODUTIVO
where LDR_METAS_OFICINA_GRUPO_NOVA.DESC_SETOR_PRODUCAO IN('OFICINA ATHENA','OFICINA FIORUCCI CONFECCOES','OFICINA AFRODITE CANINDE') AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103) --AND napsi_tbl_relacao_oficinas.qtde_oper_dia>0
ORDER BY DESC_SETOR_PRODUCAO,LDR_METAS_OFICINA_GRUPO_NOVA.DESC_RECURSO


SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA
WHERE DESC_RECURSO LIKE '%CANINDE%' AND DATA_PRODUCAO='20150623'


update LDR_METAS_OFICINA_GRUPO_NOVA
set QTDE_OPERADOR=11
where DESC_RECURSO='GRUPO AFRODITE CANINDE 06' and DATA_PRODUCAO='20150624'


update LDR_METAS_OFICINA_GRUPO_NOVA
set QTDE_OPERADOR=12
where DESC_RECURSO='GRUPO AFRODITE CANINDE 15' and DATA_PRODUCAO='20150624'
