SELECT TOP 1 
PRODUTOS_TAMANHOS.TAMANHO_1,
PRODUTOS_TAMANHOS.TAMANHO_2,PRODUTOS_TAMANHOS.TAMANHO_3,PRODUTOS_TAMANHOS.TAMANHO_4,PRODUTOS_TAMANHOS.TAMANHO_5,PRODUTOS_TAMANHOS.TAMANHO_6,PRODUTOS_TAMANHOS.TAMANHO_7,
PRODUTOS_TAMANHOS.TAMANHO_8,PRODUTOS_TAMANHOS.TAMANHO_9,PRODUTOS_TAMANHOS.TAMANHO_10,PRODUTOS_TAMANHOS.TAMANHO_11,PRODUTOS_TAMANHOS.TAMANHO_12,
PRODUCAO_TAREFAS_SALDO.QTDE_S,PRODUCAO_TAREFAS_SALDO.S1,PRODUCAO_TAREFAS_SALDO.S2,PRODUCAO_TAREFAS_SALDO.S3,PRODUCAO_TAREFAS_SALDO.S4,PRODUCAO_TAREFAS_SALDO.S5,PRODUCAO_TAREFAS_SALDO.S6,PRODUCAO_TAREFAS_SALDO.S7,
PRODUCAO_TAREFAS_SALDO.S8,PRODUCAO_TAREFAS_SALDO.S9,PRODUCAO_TAREFAS_SALDO.S10,PRODUCAO_TAREFAS_SALDO.S11,PRODUCAO_TAREFAS_SALDO.S12,PRODUCAO_TAREFAS_SALDO.S13,PRODUCAO_TAREFAS_SALDO.S14,PRODUCAO_TAREFAS_SALDO.S15,
DESC_SETOR_PRODUCAO=SUBSTRING(COSTURA.DESC_SETOR_PRODUCAO,9,10),COSTURA.DESC_RECURSO,PRODUCAO_ORDEM.PRODUTO,PRODUCAO_ORDEM_COR.COR_PRODUTO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_ORDEM.PRIORIDADE, 
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_TAREFAS.INICIO_REAL, 
GIRO=DATEDIFF(DAY, PRODUCAO_TAREFAS.INICIO_REAL, GETDATE()), 
PRODUCAO_TAREFAS.FIM_ATUALIZADO AS FIM_LIBERADO , PRODUCAO_TAREFAS.QTDE_A_PRODUZIR, PRODUCAO_TAREFAS.QTDE_EM_PROCESSO 
FROM PRODUCAO_TAREFAS WITH (NOLOCK)
INNER JOIN PRODUCAO_ORDEM WITH (NOLOCK) ON PRODUCAO_ORDEM.ORDEM_PRODUCAO = PRODUCAO_TAREFAS.ORDEM_PRODUCAO 
INNER JOIN PRODUCAO_ORDEM_COR WITH (NOLOCK) ON PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO AND PRODUCAO_ORDEM_COR.PRODUTO=PRODUCAO_ORDEM.PRODUTO  
INNER JOIN PRODUCAO_RECURSOS WITH (NOLOCK) ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO=PRODUCAO_RECURSOS.RECURSO_PRODUTIVO

LEFT JOIN (

SELECT PRODUTOS.GRADE,PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE WITH (NOLOCK), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS WITH (NOLOCK), 
dbo.PRODUCAO_SETOR PRODUCAO_SETOR WITH (NOLOCK), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS WITH (NOLOCK), 
dbo.PRODUTOS PRODUTOS, dbo.PRODUCAO_ORDEM WITH (NOLOCK)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007' 

 ) AS COSTURA

ON PRODUCAO_ORDEM_COR.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (

SELECT PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO,  PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.PRODUTO,  PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S,  
PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2,  PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4,  PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6,  
PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8,  PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10,  PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12,  
PRODUCAO_TAREFAS_SALDO.S13, PRODUCAO_TAREFAS_SALDO.S14,  PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16,  0 AS S17, 0 AS S18,  0 AS S19, 0 AS S20,  0 AS S21, 0 AS S22,  0 
AS S23, 0 AS S24,  0 AS S25, 0 AS S26,  0 AS S27, 0 AS S28,  0 AS S29, 0 AS S30,  0 AS S31, 0 AS S32,  0 AS S33, 0 AS S34,  0 AS S35, 0 AS S36,  0 AS S37, 0 AS S38,  0 AS S39, 0 
AS S40,  0 AS S41, 0 AS S42,  0 AS S43, 0 AS S44,  0 AS S45, 0 AS S46,  0 AS S47, 0 AS S48,  PRODUCAO_TAREFAS_SALDO.TIMESTAMP, PRODUTO_CORES.DESC_COR_PRODUTO,  
PRODUCAO_TAREFAS.SEQUENCIA_PRODUTIVA,  PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO,  
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO,  
PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO,  
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO,  
PRODUCAO_TAREFAS.INICIO_LIBERADO, PRODUCAO_TAREFAS.INICIO_PREVISTO,  
PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_PREVISTO,  
PRODUCAO_TAREFAS.FIM_ATUALIZADO, PRODUCAO_TAREFAS.ENCERRAMENTO,  
PRODUCAO_TAREFAS.QTDE_PREVISTA, PRODUCAO_TAREFAS.QTDE_A_PRODUZIR,  
PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS.QTDE_FINALIZADA,  
PRODUCAO_TAREFAS.QTDE_ALTERACAO_OP, PRODUCAO_TAREFAS.QTDE_PERDAS,  
PRODUCAO_TAREFAS.QTDE_ALT_OUTRAS_TAREFAS,  PRODUCAO_TAREFAS.CUSTO_TAREFA, 
PRODUCAO_TAREFAS.DESCONTOS_TAREFA,  PRODUCAO_TAREFAS.VALOR_TAREFA, 
PRODUCAO_TAREFAS.STATUS,  PRODUCAO_TAREFAS.TIPO_TEMPO_PROCESSO, 
PRODUCAO_TAREFAS.METODO_LOTE,  PRODUCAO_TAREFAS.METODO_LOTE_QTDE, 
PRODUCAO_TAREFAS.TIPO_TAREFA,  PRODUCAO_TAREFAS.TEMPO_OPERACAO 
FROM DBO.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO WITH (NOLOCK),  DBO.PRODUTO_CORES 
PRODUTO_CORES WITH (NOLOCK),  DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS WITH (NOLOCK),  DBO.PRODUCAO_FASE 
PRODUCAO_FASE WITH (NOLOCK), DBO.PRODUCAO_SETOR PRODUCAO_SETOR WITH (NOLOCK),  DBO.PRODUCAO_RECURSOS 
PRODUCAO_RECURSOS WITH (NOLOCK) WHERE PRODUTO_CORES.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO   AND 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO   AND 
PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA   AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO   AND 
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO AND PRODUCAO_TAREFAS.SETOR_PRODUCAO='RECATHENA'  

) AS PRODUCAO_TAREFAS_SALDO

ON PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO=PRODUCAO_ORDEM.ORDEM_PRODUCAO

JOIN PRODUTOS_TAMANHOS WITH (NOLOCK) ON PRODUTOS_TAMANHOS.GRADE=COSTURA.GRADE

WHERE (PRODUCAO_TAREFAS.SETOR_PRODUCAO='RECATHENA' AND 
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO='RCATF' AND COSTURA.RECURSO_PRODUTIVO='GAT02') 
AND (PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0)  AND (PRODUCAO_ORDEM_COR.QTDE_P>0) 
ORDER BY PRODUCAO_ORDEM.PRIORIDADE,PRODUCAO_ORDEM.ORDEM_PRODUCAO


