--- ARQUIVO DE MATERIAIS - DR

SELECT B.MATERIAL,B.COR_MATERIAL,'' PECA,'' PARTIDA,A.QUANTIDADE,0 QTDE_AUX,'' 
LOCALIZACAO,'' LARGURA FROM SAW_INVENT_DR A
JOIN MATERIAIS_CORES B ON B.CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO


SELECT A.MATERIAL,A.COR_MATERIAL,'' PECA,'' PARTIDA,
QUANTIDADE=(SELECT SUM(QUANTIDADE) FROM SAW_INVENT_DR WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO) 
,0 QTDE_AUX,'' LOCALIZACAO,'' LARGURA, CODIGO_EXPORTACAO 
FROM MATERIAIS_CORES A
WHERE CODIGO_EXPORTACAO='0000000026496'


SELECT A.MATERIAL,A.COR_MATERIAL,
QUANTIDADE=(SELECT cast(SUM(QUANTIDADE) as CHAR(15)) FROM SAW_INVENT_DR WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
,0 QTDE_AUX,'' LOCALIZACAO,'' LARGURA, CODIGO_EXPORTACAO 
FROM MATERIAIS_CORES A
JOIN MATERIAIS B ON B.MATERIAL=A.MATERIAL
WHERE (B.GRUPO LIKE '%BOJO%') AND EXISTS (SELECT * FROM SAW_INVENT_DR WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
order by MATERIAL,COR_MATERIAL



--- ARQUIVO PARA INVENTARIO DE MATERIAIS
SELECT '"'+MATERIAL+'","'+COR_MATERIAL+'",,,'+LTRIM(RTRIM(QUANTIDADE))+',0,,0' FROM (
SELECT A.MATERIAL,A.COR_MATERIAL,
QUANTIDADE=(SELECT cast(SUM(QUANTIDADE) as CHAR(15)) FROM SAW_INVENT_DR WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
,0 QTDE_AUX,'' LOCALIZACAO,'' LARGURA, CODIGO_EXPORTACAO 
FROM MATERIAIS_CORES A
JOIN MATERIAIS B ON B.MATERIAL=A.MATERIAL
WHERE (B.GRUPO LIKE '%BOJO%') AND EXISTS (SELECT * FROM SAW_INVENT_DR WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
) FINAL



SELECT SUM(QUANTIDADE) FROM SAW_INVENT_DR
WHERE CODIGO_EXPORTACAO='0000000026496'


SELECT * FROM SAW_INVENT_DR
WHERE TIPO_CONTAGEM LIKE '%BOJO%'




( MATERIAL c(11), COR_MATERIAL c(10), PECA c(6), 
PARTIDA c(6), QTDE n(10,3), QTDE_AUX n(10,3), 
LOCALIZACAO c(8), LARGURA n(10,3) )




---- ARQUIVO DE MATERIAIS FILIAL DR VAREJO
--- ARQUIVO PARA INVENTARIO DE MATERIAIS
SELECT '"'+MATERIAL+'","'+COR_MATERIAL+'",,,'+LTRIM(RTRIM(QUANTIDADE))+',0,,0' FROM (
SELECT A.MATERIAL,A.COR_MATERIAL,
QUANTIDADE=(SELECT cast(SUM(QTDE) as CHAR(15)) FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
,0 QTDE_AUX,'' LOCALIZACAO,'' LARGURA, CODIGO_EXPORTACAO 
FROM MATERIAIS_CORES A
JOIN MATERIAIS B ON B.MATERIAL=A.MATERIAL
WHERE EXISTS (SELECT * FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=A.CODIGO_EXPORTACAO)
) FINAL


SELECT MATERIAL,COR_MATERIAL,COUNT(CODIGO_EXPORTACAO) FROM MATERIAIS_CORES
GROUP BY MATERIAL,COR_MATERIAL
HAVING COUNT(CODIGO_EXPORTACAO)>0


SELECT * FROM ESTOQUE_MAT_CONTAGEM
WHERE NOME_CONTAGEM='INV DEZ 2015 LDR'

--- EXISTE
SELECT 
B.MATERIAL,
B.COR_MATERIAL,
QUANTIDADE=(SELECT SUM(QTDE) FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=B.CODIGO_EXPORTACAO)  
FROM ESTOQUE_MAT_CTG_ITENS A
JOIN MATERIAIS_CORES B ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL
WHERE NOME_CONTAGEM='INV DEZ 2015 LDR' AND EXISTS (SELECT * FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=B.CODIGO_EXPORTACAO)


--- NÃO EXISTE
SELECT 
B.MATERIAL,
B.COR_MATERIAL,
QUANTIDADE=(SELECT SUM(QTDE) FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=B.CODIGO_EXPORTACAO)  
FROM ESTOQUE_MAT_CTG_ITENS A
JOIN MATERIAIS_CORES B ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL
WHERE NOME_CONTAGEM='INV DEZ 2015 LDR' AND NOT EXISTS (SELECT * FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=B.CODIGO_EXPORTACAO)


DELETE FROM A
FROM ESTOQUE_MAT_CTG_ITENS A
JOIN MATERIAIS_CORES B ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL
WHERE NOME_CONTAGEM='INV DEZ 2015 LDR' AND NOT EXISTS (SELECT * FROM SAW_INVENT_MATERIA_PRIMA WHERE CODIGO_EXPORTACAO=B.CODIGO_EXPORTACAO)






