-- GERA O ARQUIVO
SELECT '"'+LTRIM (RTRIM(B.CODIGO_BARRA))+'",'+ CAST (SUM(EP.ENPQT_ESTOQUE) AS VARCHAR) CODBARRA
FROM PRODUTOS_BARRA B
JOIN T_ENDDEP_PRODUTO EP ON EP.ISN_PRODUTO = B.ISN_PRODUTO AND EP.COR_PRODUTO = B.COR_PRODUTO AND EP.TAMANHO_PRODUTO = B.GRADE
JOIN T_ENDERECO_DEPOSITO A ON (EP.ISN_ENDERECO = A.ISN_ENDERECO)
WHERE
B.CODIGO_BARRA_PADRAO='1'
--AND B.PRODUTO LIKE '%%' AND ISN_REGIAO_DEPOSITO = 37
GROUP BY B.CODIGO_BARRA
ORDER BY B.CODIGO_BARRA


----------------------------------------------------------------------------------------------------------------------------------
--CONFERE ENDEREÇOS--
SELECT RTRIM(B.CODIGO_BARRA) CODBARRA, SUM(A.ENPQT_ESTOQUE) QTD, E.ENDNR_APTO, B.PRODUTO, B.COR_PRODUTO, B.GRADE, C.GRIFFE, E.ISN_REGIAO_DEPOSITO,D.NR_IDENTIDADE, E.ENDNR_RUA, ENDNR_BLOCO
FROM PRODUTOS_BARRA B
JOIN T_ENDDEP_PRODUTO A ON A.ISN_PRODUTO = B.ISN_PRODUTO AND A.COR_PRODUTO = B.COR_PRODUTO AND A.TAMANHO_PRODUTO = B.GRADE
JOIN T_ENDERECO_DEPOSITO E ON (E.ISN_ENDERECO = A.ISN_ENDERECO)
JOIN PRODUTOS C ON C.PRODUTO=B.PRODUTO
JOIN T_REGIAO_DEPOSITO D ON D.ISN_REGIAO_DEPOSITO=E.ISN_REGIAO_DEPOSITO
WHERE
B.CODIGO_BARRA_PADRAO='1' and e.ISN_REGIAO_DEPOSITO='37'
GROUP BY B.CODIGO_BARRA, E.ENDNR_APTO, B.PRODUTO, B.COR_PRODUTO, B.GRADE, C.GRIFFE, E.ISN_REGIAO_DEPOSITO,D.NR_IDENTIDADE, E.ENDNR_RUA, ENDNR_BLOCO
ORDER BY B.CODIGO_BARRA



select * from T_ENDDEP_PRODUTO