SELECT TOP 1 DESC_SETOR_PRODUCAO=SUBSTRING(COSTURA.DESC_SETOR_PRODUCAO,9,10),COSTURA.DESC_RECURSO,PRODUCAO_ORDEM.PRODUTO,PRODUCAO_ORDEM_COR.COR_PRODUTO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_ORDEM.PRIORIDADE, 
PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_TAREFAS.INICIO_REAL, 
GIRO=DATEDIFF(DAY, PRODUCAO_TAREFAS.INICIO_REAL, GETDATE()), 
PRODUCAO_TAREFAS.FIM_ATUALIZADO AS FIM_LIBERADO , PRODUCAO_TAREFAS.QTDE_A_PRODUZIR, PRODUCAO_TAREFAS.QTDE_EM_PROCESSO 
FROM PRODUCAO_TAREFAS WITH (NOLOCK)
INNER JOIN PRODUCAO_ORDEM WITH (NOLOCK) ON PRODUCAO_ORDEM.ORDEM_PRODUCAO = PRODUCAO_TAREFAS.ORDEM_PRODUCAO 
INNER JOIN PRODUCAO_ORDEM_COR WITH (NOLOCK) ON PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO AND PRODUCAO_ORDEM_COR.PRODUTO=PRODUCAO_ORDEM.PRODUTO  
INNER JOIN PRODUCAO_RECURSOS WITH (NOLOCK) ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO=PRODUCAO_RECURSOS.RECURSO_PRODUTIVO

LEFT JOIN (

SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE WITH (NOLOCK), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS WITH (NOLOCK), 
dbo.PRODUCAO_SETOR PRODUCAO_SETOR WITH (NOLOCK), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS WITH (NOLOCK), 
dbo.PRODUTOS PRODUTOS, dbo.PRODUCAO_ORDEM WITH (NOLOCK)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007' 

 ) AS COSTURA

ON PRODUCAO_ORDEM_COR.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

WHERE (PRODUCAO_TAREFAS.RECURSO_PRODUTIVO='RCATH' AND COSTURA.RECURSO_PRODUTIVO='GAT01' ) 
AND (PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0)  AND (PRODUCAO_ORDEM_COR.QTDE_P>0) 
ORDER BY PRODUCAO_ORDEM.PRIORIDADE



SELECT PRODUCAO_ORDEM.PRODUTO, PRODUCAO_ORDEM_COR.COR_PRODUTO, PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_ORDEM.PRIORIDADE, PRODUCAO_TAREFAS.FASE_PRODUCAO, PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_TAREFAS.INICIO_REAL, DATEDIFF(DAY, PRODUCAO_TAREFAS.INICIO_REAL, GETDATE()) AS GIRO, PRODUCAO_TAREFAS.FIM_ATUALIZADO AS FIM_LIBERADO, PRODUCAO_TAREFAS.QTDE_A_PRODUZIR, PRODUCAO_TAREFAS.QTDE_EM_PROCESSO FROM PRODUCAO_TAREFAS WITH (NOLOCK) INNER JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO = PRODUCAO_TAREFAS.ORDEM_PRODUCAO INNER JOIN PRODUCAO_ORDEM_COR ON PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO AND PRODUCAO_ORDEM_COR.PRODUTO = PRODUCAO_ORDEM.PRODUTO INNER JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO WHERE (PRODUCAO_TAREFAS.RECURSO_PRODUTIVO LIKE 'GAT01') AND (PRODUCAO_TAREFAS.QTDE_EM_PROCESSO > 0) AND (PRODUCAO_ORDEM_COR.QTDE_P > 0) ORDER BY PRODUCAO_ORDEM.PRIORIDADE

