SELECT * FROM (
SELECT PRODUTOS.DESC_PROD_NF,faturamento_prod.pedido,faturamento_prod.filial,FATURAMENTO_PROD.NF_SAIDA,FATURAMENTO_PROD.SERIE_NF,PRODUTOS_BARRA.CODIGO_BARRA,PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
QTDE = (CASE  WHEN PRODUTOS_BARRA.tamanho='1'  THEN FATURAMENTO_PROD.F1 
              WHEN PRODUTOS_BARRA.tamanho='2'  THEN FATURAMENTO_PROD.F2
              WHEN PRODUTOS_BARRA.tamanho='3'  THEN FATURAMENTO_PROD.F3
              WHEN PRODUTOS_BARRA.tamanho='4'  THEN FATURAMENTO_PROD.F4
              WHEN PRODUTOS_BARRA.tamanho='5'  THEN FATURAMENTO_PROD.F5
              WHEN PRODUTOS_BARRA.tamanho='6'  THEN FATURAMENTO_PROD.F6
              WHEN PRODUTOS_BARRA.tamanho='7'  THEN FATURAMENTO_PROD.F7
              WHEN PRODUTOS_BARRA.tamanho='8'  THEN FATURAMENTO_PROD.F8
              WHEN PRODUTOS_BARRA.tamanho='9'  THEN FATURAMENTO_PROD.F9
              WHEN PRODUTOS_BARRA.tamanho='10' THEN FATURAMENTO_PROD.F10
              WHEN PRODUTOS_BARRA.tamanho='11' THEN FATURAMENTO_PROD.F11
              WHEN PRODUTOS_BARRA.tamanho='12' THEN FATURAMENTO_PROD.F12 
              WHEN PRODUTOS_BARRA.tamanho='13' THEN FATURAMENTO_PROD.F13 
              WHEN PRODUTOS_BARRA.tamanho='14' THEN FATURAMENTO_PROD.F14
              WHEN PRODUTOS_BARRA.tamanho='15' THEN FATURAMENTO_PROD.F15 
              WHEN PRODUTOS_BARRA.tamanho='16' THEN FATURAMENTO_PROD.F16 
        END)
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
LEFT JOIN (SELECT * FROM FATURAMENTO_PROD) AS FATURAMENTO_PROD
  ON FATURAMENTO_PROD.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND FATURAMENTO_PROD.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND FATURAMENTO_PROD.NF_SAIDA = '042518' AND SERIE_NF='1'
) AS FINAL
WHERE QTDE>0


