--- DENI RICARDO
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       D.ENDERECO,
       D.NUMERO,
       D.BAIRRO,
       D.CEP,
       D.DDD1,
       D.TELEFONE1,
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A WITH (NOLOCK), 
     VENDAS B WITH (NOLOCK), 
     PRODUTOS C WITH (NOLOCK), 
     CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.ENDERECO,
         D.NUMERO,
         D.BAIRRO,
         D.CEP,
         D.DDD1,
         D.TELEFONE1,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'DENI%')
UNION ALL
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       D.ENDERECO,
       D.NUMERO,
       D.BAIRRO,
       D.CEP,
       D.DDD1,
       D.TELEFONE1,
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM LDR.DRVAREJO.DBO.VENDAS_PRODUTO A WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.VENDAS B WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.PRODUTOS C WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.ENDERECO,
         D.NUMERO,
         D.BAIRRO,
         D.CEP,
         D.DDD1,
         D.TELEFONE1,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'DENI%')




--- MARCUS CARIOCA
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A WITH (NOLOCK), 
     VENDAS B WITH (NOLOCK), 
     PRODUTOS C WITH (NOLOCK), 
     CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A' AND A.PEDIDO NOT IN (SELECT DISTINCT A.PEDIDO FROM VENDAS_CANC_PROD A WITH (NOLOCK)
JOIN VENDAS_CANCELAMENTO B WITH (NOLOCK) ON B.NUM_CANCELAMENTO=A.NUM_CANCELAMENTO AND B.TIPO_CANCELAMENTO IN ('SOLICIT. REPRESENTANTE','SOLICIT.CLIENTE'))
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE IN ('MARCUS ROBERTO','MARCUS CARIOCA'))

UNION ALL

SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM LDR.DRVAREJO.DBO.VENDAS_PRODUTO A WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.VENDAS B WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.PRODUTOS C WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A' AND A.PEDIDO NOT IN (SELECT DISTINCT A.PEDIDO FROM LDR.DRVAREJO.DBO.VENDAS_CANC_PROD A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.VENDAS_CANCELAMENTO B WITH (NOLOCK) ON B.NUM_CANCELAMENTO=A.NUM_CANCELAMENTO AND B.TIPO_CANCELAMENTO IN ('SOLICIT. REPRESENTANTE','SOLICIT.CLIENTE'))
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE IN ('MARCUS ROBERTO','MARCUS CARIOCA'))



--- JOSE MARIO
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A WITH (NOLOCK), 
     VENDAS B WITH (NOLOCK), 
     PRODUTOS C WITH (NOLOCK), 
     CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE IN ('CELSO MACHADO','JOSE MARIO ARRUDA','JOSE MARIO') )

UNION ALL

SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM LDR.DRVAREJO.DBO.VENDAS_PRODUTO A WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.VENDAS B WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.PRODUTOS C WITH (NOLOCK), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE IN ('CELSO MACHADO','JOSE MARIO ARRUDA','JOSE MARIO') )



-- sergio pires
SELECT REGIAO=RTRIM(E.REGIAO),GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A with (nolock), 
     VENDAS B with (nolock), 
     PRODUTOS C with (nolock), 
     CADASTRO_CLI_FOR D with (nolock),
     CLIENTES_ATACADO E with (nolock)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      B.CLIENTE_ATACADO = E.CLIENTE_ATACADO AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20100101')) AND
      B.APROVACAO='A'
GROUP BY E.REGIAO,B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'SERGIO PIRES%' OR B.GERENTE LIKE 'MAURILIO%')

UNION ALL

SELECT REGIAO=RTRIM(E.REGIAO),GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM LDR.DRVAREJO.DBO.VENDAS_PRODUTO A with (nolock), 
     LDR.DRVAREJO.DBO.VENDAS B with (nolock), 
     LDR.DRVAREJO.DBO.PRODUTOS C with (nolock), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D with (nolock),
     LDR.DRVAREJO.DBO.CLIENTES_ATACADO E with (nolock)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      B.CLIENTE_ATACADO = E.CLIENTE_ATACADO AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20100101')) AND
      B.APROVACAO='A'
GROUP BY E.REGIAO,B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'SERGIO PIRES%' OR B.GERENTE LIKE 'MAURILIO%')


--- sarmento
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM VENDAS_PRODUTO A with (nolock), 
     VENDAS B with (nolock), 
     PRODUTOS C with (nolock), 
     CADASTRO_CLI_FOR D with (nolock)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'SARMENTO%') or (B.GERENTE = 'JOSE ANTONIO SARMENTO')

UNION ALL

SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE_ORIGINAL), 
       VALOR=SUM(A.VALOR_ORIGINAL)
FROM LDR.DRVAREJO.DBO.VENDAS_PRODUTO A with (nolock), 
     LDR.DRVAREJO.DBO.VENDAS B with (nolock), 
     LDR.DRVAREJO.DBO.PRODUTOS C with (nolock), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D with (nolock)
WHERE A.PEDIDO = B.PEDIDO AND 
      C.PRODUTO = A.PRODUTO AND 
      B.CLIENTE_ATACADO = D.NOME_CLIFOR AND 
      ((B.TABELA_FILHA='VENDAS_PRODUTO') AND (B.EMISSAO>='20090101')) AND
      B.APROVACAO='A'
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING (B.GERENTE LIKE 'SARMENTO%') or (B.GERENTE = 'JOSE ANTONIO SARMENTO')




--- faturamento

--- marcus carioca
SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO_FATURAMENTO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE), 
       VALOR=SUM(A.VALOR)
FROM FATURAMENTO_PROD A with (nolock), 
     FATURAMENTO B with (nolock), 
     PRODUTOS C with (nolock), 
     CADASTRO_CLI_FOR D with (nolock)
WHERE A.NF_SAIDA = B.NF_SAIDA AND A.SERIE_NF = B.SERIE_NF 
      AND C.PRODUTO = A.PRODUTO 
      AND B.NOME_CLIFOR = D.NOME_CLIFOR 
      AND ((B.TABELA_FILHA='FATURAMENTO_PROD') AND (B.EMISSAO>='20090101') AND (B.NOTA_CANCELADA=0)) 
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO_FATURAMENTO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING B.GERENTE In('MARCUS ROBERTO','MARCUS CARIOCA')

UNION ALL

SELECT GERENTE=RTRIM(B.GERENTE), 
       REPRESENTANTE=RTRIM(B.REPRESENTANTE),
       D.UF,
       CIDADE=RTRIM(D.CIDADE),
       D.RAZAO_SOCIAL,
       B.TIPO_FATURAMENTO, 
       A.PRODUTO, 
       C.LINHA, 
       B.EMISSAO, 
       QTDE=SUM(A.QTDE), 
       VALOR=SUM(A.VALOR)
FROM LDR.DRVAREJO.DBO.FATURAMENTO_PROD A with (nolock), 
     LDR.DRVAREJO.DBO.FATURAMENTO B with (nolock), 
     LDR.DRVAREJO.DBO.PRODUTOS C with (nolock), 
     LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D with (nolock)
WHERE A.NF_SAIDA = B.NF_SAIDA AND A.SERIE_NF = B.SERIE_NF 
      AND C.PRODUTO = A.PRODUTO 
      AND B.NOME_CLIFOR = D.NOME_CLIFOR 
      AND ((B.TABELA_FILHA='FATURAMENTO_PROD') AND (B.EMISSAO>='20090101') AND (B.NOTA_CANCELADA=0)) 
GROUP BY B.GERENTE, 
         B.REPRESENTANTE,
         D.UF,
         D.CIDADE,
         D.RAZAO_SOCIAL, 
         B.TIPO_FATURAMENTO, 
         A.PRODUTO, 
         C.LINHA, 
         B.EMISSAO
HAVING B.GERENTE In('MARCUS ROBERTO','MARCUS CARIOCA')
