--- IMPORTA PEDIDO
--- PEGA A SEQUENCIA DO PROXIMO PEDIDO
declare @p4 varchar(8000)
set @p4='0'
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_SEQUENCIAL @TABELA_COLUNA = ''VENDAS.PEDIDO'', @EMPRESA = @P1, @SEQUENCIA = @P2 OUTPUT, @UPDATE_SEQUENCIAL = 1, @NEWVALUE = ''''',N'@P1 int,@P2 varchar(8000) OUTPUT',1,@p4 output
select @p4
--- IMPORTA CAPA DO PEDIDO
INSERT INTO VENDAS ([PEDIDO]      ,[ROMANEIO]      ,[COLECAO]      ,[PEDIDO_EXTERNO]      ,[DATA_ENVIO]
      ,[CODIGO_TAB_PRECO]      ,[TIPO]      ,[DATA_RECEBIMENTO]      ,[CONDICAO_PGTO]      ,[FILIAL]
      ,[CLIENTE_ATACADO]      ,[TRANSPORTADORA]      ,[MOEDA]      ,[REPRESENTANTE]      ,[COMISSAO]
      ,[GERENTE]      ,[COMISSAO_GERENTE]      ,[EMISSAO]      ,[CADASTRAMENTO]      ,[PEDIDO_CLIENTE]
      ,[TOT_QTDE_ORIGINAL]      ,[TOT_QTDE_ENTREGUE]      ,[TOT_QTDE_EMBALADA]      ,[TOT_QTDE_DEVOLVIDA]
      ,[TOT_QTDE_CANCELADA]      ,[TOT_QTDE_ENTREGAR]      ,[TOT_VALOR_ORIGINAL]      ,[TOT_VALOR_ENTREGUE]
      ,[TOT_VALOR_CANCELADO]      ,[TOT_VALOR_DEVOLVIDO]      ,[TOT_VALOR_ENTREGAR]      ,[DESCONTO]
      ,[ENCARGO]      ,[VALOR_IPI]      ,[PORCENTAGEM_ACERTO]      ,[CTRL_MULT_ENTREGAS]      ,[ENTREGA_CIF]
      ,[ENTREGA_ACEITAVEL]      ,[PRIORIDADE]      ,[STATUS]      ,[ACEITA_JUNTAR_PED]      ,[APROVACAO]
      ,[APROVADO_POR]      ,[CONFERIDO]      ,[CONFERIDO_POR]      ,[TABELA_FILHA]      ,[OBS]
      ,[DESCONTO_SOBRE_1]      ,[DESCONTO_SOBRE_2]      ,[DESCONTO_SOBRE_3]      ,[DESCONTO_SOBRE_4]
      ,[TOT_BRUTO_ENTREGUE]      ,[ACEITA_PECAS_PEQUENAS]      ,[ACEITA_PECAS_COM_CORTE]      ,[FRETE_CORTESIA]
      ,[TIPO_FRETE]      ,[CODIGO_LOCAL_ENTREGA]      ,[DATA_PARA_TRANSFERENCIA]      ,[PROMOTOR]
      ,[DATA_FATURAMENTO_RELATIVO]      ,[TOT_QTDE_ENTREGUE_TERC]      ,[TOT_VALOR_ENTREGUE_TERC]
      ,[RECARGO]      ,[TOT_ENTREGUE_MOEDA_PADRAO]      ,[INDICA_LOCAL_SEPARACAO]      ,[PEDIDO_VENDA_ORIGEM]
      ,[EXPEDICAO_COMPLETO_PEDIDO]      ,[EXPEDICAO_COMPLETO_PACK]      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]      ,[EXPEDICAO_COMPLETO_COORDENADO]      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]      ,[EXPEDICAO_PORCENTAGEM_MINIMA]      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[MULTI_DESCONTO_ACUMULAR]      ,[TIPO_CAIXA]      ,[FILIAL_DIGITACAO]
      ,[NUMERO_ENTREGA]      ,[PERIODO_PCP]      ,[NOME_CLIFOR_ENTREGA]      ,[TIPO_RATEIO]      ,[EXPEDICAO_NAO_JUNTAR_PRODUTO_CAIXA]
      ,[TRANSP_REDESPACHO]      ,[OBS_TRANSPORTE]      ,[DESCONTO_ENCARGO_ITEM]      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO_1]      ,[DESCONTO_BRUTO_2]      ,[DESCONTO_BRUTO_3]      ,[DESCONTO_BRUTO_4]      ,[DESCONTO_BRUTO]
      ,[PORC_DESCONTO_COND_PGTO]      ,[PORC_DESCONTO]      ,[PORC_ENCARGO]      ,[PORC_DESCONTO_BRUTO]      ,[PORC_DESCONTO_DIGITADO]
      ,[DESCONTO_COND_PGTO]      ,[NATUREZA_SAIDA]      ,[IMPRIMIR_ENDERECO_COBRANCA]      ,[COBRAR_MOEDA_PADRAO]      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]      ,[EXPEDICAO_ADEQUACAO_COR]      ,[EXPEDICAO_ADEQUACAO_TAMANHO]      ,[BANCO]
      ,[AGENCIA]      ,[COMISSAO_VALOR]      ,[COMISSAO_VALOR_GERENTE]      ,[VALOR_ANTECIPACAO]      ,[VALOR_SUB_ITENS]
      ,[PEDIDO_CONFERENCIA]      ,[INDICADOR_VENDA]      ,[COD_LICENCIADO]      ,[ENVIA_CLIENTE]      ,[TAB_PRECO_SERVICO]
      ,[CODIGO_CLIENTE_VAREJO]      ,[ISN_CLIENTE]      ,[PEDQT_VOLUMES]      ,[ISN_MANIFESTO]      ,[PEDFG_FLOWRACK]
      ,[PEDFG_STATUS]      ,[PEDDT_INI_CONF_FLOWRACK]      ,[PEDDT_FIM_CONF_FLOWRACK]      ,[PEDDT_INICIO_CONFERENCIA]
      ,[PEDDT_FIM_CONFERENCIA]      ,[ISN_SEPARADOR]      ,[PEDFG_IMPRESSO_MAPA]      ,[PEDDT_INICIO_IMPRESSAO]
      ,[ISN_USUCONFERENTE]      ,[DATA_APROVACAO])
SELECT '97481'
      ,[ROMANEIO]
      ,[COLECAO]
      ,[PEDIDO_EXTERNO]
      ,[DATA_ENVIO]
      ,[CODIGO_TAB_PRECO]
      ,[TIPO]
      ,[DATA_RECEBIMENTO]
      ,[CONDICAO_PGTO]
      ,[FILIAL]
      ,[CLIENTE_ATACADO]
      ,[TRANSPORTADORA]
      ,[MOEDA]
      ,[REPRESENTANTE]
      ,[COMISSAO]
      ,[GERENTE]
      ,[COMISSAO_GERENTE]
      ,[EMISSAO]
      ,[CADASTRAMENTO]
      ,[PEDIDO_CLIENTE]
      ,[TOT_QTDE_ORIGINAL]
      ,[TOT_QTDE_ENTREGUE]
      ,[TOT_QTDE_EMBALADA]
      ,[TOT_QTDE_DEVOLVIDA]
      ,[TOT_QTDE_CANCELADA]
      ,[TOT_QTDE_ENTREGAR]
      ,[TOT_VALOR_ORIGINAL]
      ,[TOT_VALOR_ENTREGUE]
      ,[TOT_VALOR_CANCELADO]
      ,[TOT_VALOR_DEVOLVIDO]
      ,[TOT_VALOR_ENTREGAR]
      ,[DESCONTO]
      ,[ENCARGO]
      ,[VALOR_IPI]
      ,[PORCENTAGEM_ACERTO]
      ,[CTRL_MULT_ENTREGAS]
      ,[ENTREGA_CIF]
      ,[ENTREGA_ACEITAVEL]
      ,[PRIORIDADE]
      ,[STATUS]
      ,[ACEITA_JUNTAR_PED]
      ,[APROVACAO]
      ,[APROVADO_POR]
      ,[CONFERIDO]
      ,[CONFERIDO_POR]
      ,[TABELA_FILHA]
      ,[OBS]
      ,[DESCONTO_SOBRE_1]
      ,[DESCONTO_SOBRE_2]
      ,[DESCONTO_SOBRE_3]
      ,[DESCONTO_SOBRE_4]
      ,[TOT_BRUTO_ENTREGUE]
      ,[ACEITA_PECAS_PEQUENAS]
      ,[ACEITA_PECAS_COM_CORTE]
      ,[FRETE_CORTESIA]
      ,[TIPO_FRETE]
      ,[CODIGO_LOCAL_ENTREGA]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[PROMOTOR]
      ,[DATA_FATURAMENTO_RELATIVO]
      ,[TOT_QTDE_ENTREGUE_TERC]
      ,[TOT_VALOR_ENTREGUE_TERC]
      ,[RECARGO]
      ,[TOT_ENTREGUE_MOEDA_PADRAO]
      ,[INDICA_LOCAL_SEPARACAO]
      ,[PEDIDO_VENDA_ORIGEM]
      ,[EXPEDICAO_COMPLETO_PEDIDO]
      ,[EXPEDICAO_COMPLETO_PACK]
      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]
      ,[EXPEDICAO_COMPLETO_COORDENADO]
      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]
      ,[EXPEDICAO_PORCENTAGEM_MINIMA]
      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[MULTI_DESCONTO_ACUMULAR]
      ,[TIPO_CAIXA]
      ,[FILIAL_DIGITACAO]
      ,[NUMERO_ENTREGA]
      ,[PERIODO_PCP]
      ,[NOME_CLIFOR_ENTREGA]
      ,[TIPO_RATEIO]
      ,[EXPEDICAO_NAO_JUNTAR_PRODUTO_CAIXA]
      ,[TRANSP_REDESPACHO]
      ,[OBS_TRANSPORTE]
      ,[DESCONTO_ENCARGO_ITEM]
      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO_1]
      ,[DESCONTO_BRUTO_2]
      ,[DESCONTO_BRUTO_3]
      ,[DESCONTO_BRUTO_4]
      ,[DESCONTO_BRUTO]
      ,[PORC_DESCONTO_COND_PGTO]
      ,[PORC_DESCONTO]
      ,[PORC_ENCARGO]
      ,[PORC_DESCONTO_BRUTO]
      ,[PORC_DESCONTO_DIGITADO]
      ,[DESCONTO_COND_PGTO]
      ,[NATUREZA_SAIDA]
      ,[IMPRIMIR_ENDERECO_COBRANCA]
      ,[COBRAR_MOEDA_PADRAO]
      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]
      ,[EXPEDICAO_ADEQUACAO_COR]
      ,[EXPEDICAO_ADEQUACAO_TAMANHO]
      ,[BANCO]
      ,[AGENCIA]
      ,[COMISSAO_VALOR]
      ,[COMISSAO_VALOR_GERENTE]
      ,[VALOR_ANTECIPACAO]
      ,[VALOR_SUB_ITENS]
      ,[PEDIDO_CONFERENCIA]
      ,[INDICADOR_VENDA]
      ,[COD_LICENCIADO]
      ,[ENVIA_CLIENTE]
      ,[TAB_PRECO_SERVICO]
      ,[CODIGO_CLIENTE_VAREJO]
      ,[ISN_CLIENTE]
      ,[PEDQT_VOLUMES]
      ,[ISN_MANIFESTO]
      ,[PEDFG_FLOWRACK]
      ,[PEDFG_STATUS]
      ,[PEDDT_INI_CONF_FLOWRACK]
      ,[PEDDT_FIM_CONF_FLOWRACK]
      ,[PEDDT_INICIO_CONFERENCIA]
      ,[PEDDT_FIM_CONFERENCIA]
      ,[ISN_SEPARADOR]
      ,[PEDFG_IMPRESSO_MAPA]
      ,[PEDDT_INICIO_IMPRESSAO]
      ,[ISN_USUCONFERENTE]
      ,[DATA_APROVACAO]
  FROM [dbo].[VENDAS]
WHERE PEDIDO='PEDIDO_TESTE'

--- IMPORTA ITENS DO PEDIDO
INSERT INTO VENDAS_PRODUTO ([PEDIDO],[PRODUTO]      ,[COR_PRODUTO]      ,[ENTREGA]      ,[SEQUENCIAL_DIGITACAO]
      ,[ITEM_PEDIDO]      ,[NUMERO_CONJUNTO]      ,[PACKS]      ,[LIMITE_ENTREGA]      ,[CODIGO_LOCAL_ENTREGA]
      ,[NUMERO_ENTREGA]      ,[STATUS_VENDA_ATUAL]      ,[QTDE_ORIGINAL]      ,[QTDE_EMBALADA]      ,[QTDE_ENTREGAR]
      ,[QTDE_ENTREGUE]      ,[QTDE_DEVOLVIDA]      ,[QTDE_CANCELADA]      ,[PRECO1]      ,[PRECO2]      ,[PRECO3]
      ,[PRECO4]      ,[DESCONTO_ITEM]      ,[IPI]      ,[VALOR_CANCELADO]      ,[VALOR_ORIGINAL]      ,[VALOR_ENTREGAR]
      ,[VALOR_DEVOLVIDO]      ,[VALOR_ENTREGUE]      ,[ENTREGUE_MOEDA_PADRAO]      ,[VO1]      ,[VO2]      ,[VO3]
      ,[VO4]      ,[VO5]      ,[VO6]      ,[VO7]      ,[VO8]      ,[VO9]      ,[VO10]      ,[VO11]      ,[VO12]
      ,[VO13]      ,[VO14]      ,[VO15]      ,[VO16]      ,[VO17]      ,[VO18]      ,[VO19]      ,[VO20]
      ,[VE1]      ,[VE2]      ,[VE3]      ,[VE4]      ,[VE5]      ,[VE6]      ,[VE7]      ,[VE8]      ,[VE9]
      ,[VE10]      ,[VE11]      ,[VE12]      ,[VE13]      ,[VE14]      ,[VE15]      ,[VE16]      ,[VE17]
      ,[VE18]      ,[VE19]      ,[VE20]
      ,[ORDEM_PRODUCAO]      ,[PEDIDO_COMPRA]      ,[TIPO_CAIXA]      ,[NUMERO_CAIXAS]      ,[DESC_VENDA_CLIENTE]
      ,[DESCONTO_PROMOCAO_ITEM]      ,[COMISSAO_ITEM]      ,[COMISSAO_ITEM_GERENTE]      ,[PORCENTAGEM_ITEM_RATEIO]      ,[DATA_PARA_TRANSFERENCIA]      ,[ID_MODIFICACAO]
      ,[LICENCIADO_ROYALTIES]      ,[ID_VENDA_ENTREGA_FUTURA]      ,[IPEVL_CHECADO]
      ,[IPEQT_CHECKFLOWRACK]      ,[ISN_PEDIDO]      ,[ISN_PRODUTO]      ,[IPENM_LOTE])
SELECT '97481',B.PRODUTO,B.COR_PRODUTO,'2017-07-21 00:00:00.000',CAST('0' AS INT)+ ROW_NUMBER() OVER(ORDER BY B.CODIGO_BARRA),
REPLICATE('0',4-LEN(CAST('0' AS INT)+ ROW_NUMBER() OVER(ORDER BY B.CODIGO_BARRA)))+CAST(CAST('0' AS INT)+ ROW_NUMBER() OVER(ORDER BY B.CODIGO_BARRA) AS CHAR(4)),
'0','','2017-07-21 00:00:00.000','','','1',CAST(A.F3 AS INT),0,CAST(A.F3 AS INT),0,0,0,C.PRECO1,0,0,0,0,0,0,C.PRECO1*CAST(A.F3 AS INT),C.PRECO1*CAST(A.F3 AS INT),
0,0,0,
CASE WHEN B.tamanho=1 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=2 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=3 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=4 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=5 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=6 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=7 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=8 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=9 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=10 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=11 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=12 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=13 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=14 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=15 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=16 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=17 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=18 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=19 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=20 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=1 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=2 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=3 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=4 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=5 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=6 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=7 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=8 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=9 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=10 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=11 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=12 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=13 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=14 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=15 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=16 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=17 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=18 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=19 THEN CAST(A.F3 AS INT) ELSE 0 END,
CASE WHEN B.tamanho=20 THEN CAST(A.F3 AS INT) ELSE 0 END,
NULL,NULL,NULL,'0',NULL,0,1.5,0,1,GETDATE(),NULL,0.0000,NULL,NULL,NULL,NULL,NULL,NULL
FROM OPENROWSET ('Microsoft.Ace.OLEDB.12.0'
,'Excel 12.0; Database=c:\temp\PEDIDOS_LASA_AGO_DEZ_2017.xlsx; Extended Properties=''EXCEL 12.0;HDR=NO;IMEX=1'
,'SELECT * FROM [AG 1212$]') AS A
JOIN PRODUTOS_BARRA B ON B.CODIGO_BARRA=A.F2 COLLATE SQL_Latin1_General_CP1_CI_AS
JOIN PRODUTOS_PRECOS C ON C.PRODUTO=B.PRODUTO AND C.CODIGO_TAB_PRECO='99'



SELECT * FROM VENDAS_PRODUTO
WHERE QTDE_ORIGINAL=0 AND PEDIDO='97481'


DELETE FROM VENDAS_PRODUTO
WHERE QTDE_ORIGINAL=0 AND PEDIDO='97481'





SELECT * FROM OPENROWSET ('Microsoft.Ace.OLEDB.12.0'
,'Excel 12.0; Database=c:\temp\PEDIDOS_LASA_AGO_DEZ_2017.xlsx; Extended Properties=''EXCEL 12.0;HDR=NO;IMEX=1'
,'SELECT * FROM [AG 0308  297336$]') AS A
JOIN PRODUTOS_BARRA B ON B.CODIGO_BARRA=A.F2 COLLATE SQL_Latin1_General_CP1_CI_AS
JOIN PRODUTOS_PRECOS C ON C.PRODUTO=B.PRODUTO AND C.CODIGO_TAB_PRECO='99'

SELECT * FROM VENDAS
WHERE CLIENTE_ATACADO='LOJAS AMERICANAS CD RJ' AND PEDIDO='pedido_teste'

SELECT SUM(QTDE_ORIGINAL) FROM VENDAS_PRODUTO
WHERE PEDIDO='pedido_teste'

DELETE FROM VENDAS_PRODUTO
WHERE PEDIDO='pedido_teste'
