
INSERT INTO LDR_PRODUTO_COR_ENTREGA_FUTURA 
(PRODUTO,COR_PRODUTO,PERIODO_PCP,NUMERO_ENTREGA,ENTREGA,LIMITE)

SELECT PRODUTO_CORES.PRODUTO,PRODUTO_CORES.COR_PRODUTO,'2014 OUTUBRO','37','2014-10-01 00:00:00.000','2014-10-11 00:00:00.000' FROM PRODUTO_CORES
JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUTO_CORES.PRODUTO
WHERE PRODUTOS.GRUPO_PRODUTO='CUECA' AND PRODUTOS.COD_CATEGORIA='01' AND PRODUTO_CORES.PRODUTO+PRODUTO_CORES.COR_PRODUTO NOT IN
(
	SELECT PRODUTO+COR_PRODUTO FROM LDR_PRODUTO_COR_ENTREGA_FUTURA
)
ORDER BY PRODUTO_CORES.PRODUTO




select * from LDR_PRODUTO_COR_ENTREGA_FUTURA
ORDER BY PRODUTO
