DECLARE @DATAINI CHAR(10),@DATAFIM CHAR(10)
SELECT @DATAINI = '01/10/2013'
SELECT @DATAFIM = '31/12/2013'

SELECT * FROM (
SELECT DISTINCT PRODUTO, 
(SELECT QTDE=ISNULL(SUM(QTDE),0) FROM W_INDICADORES_COMERCIAL_INDUSTRIAL WITH (NOLOCK)
 WHERE TIPO='PREVISÃO (VENDAS)' 
 AND EMISSAO_INICIAL >= CONVERT (DATE, @DATAINI, 103)
 AND EMISSAO_FINAL <= CONVERT (DATE, @DATAFIM, 103)
 AND PRODUTO=I.PRODUTO ) AS PREVISAO,

(SELECT QTDE=ISNULL(SUM(QTDE),0) FROM W_INDICADORES_COMERCIAL_INDUSTRIAL WITH (NOLOCK)
 WHERE TIPO='CARTEIRA (VENDAS ENTREGAR)' 
 AND EMISSAO_INICIAL >= CONVERT (DATE, @DATAINI, 103)
 AND EMISSAO_FINAL <= CONVERT (DATE, @DATAFIM, 103)
 AND PRODUTO=I.PRODUTO ) AS CARTEIRA,
 
(SELECT QTDE=ISNULL(SUM(QTDE),0) FROM W_INDICADORES_COMERCIAL_INDUSTRIAL WITH (NOLOCK)
 WHERE TIPO='PROCESSO' 
 AND PRODUTO=I.PRODUTO ) AS PROCESSO,

(SELECT QTDE=ISNULL(SUM(QTDE),0) FROM W_INDICADORES_COMERCIAL_INDUSTRIAL WITH (NOLOCK)
 WHERE TIPO='ESTOQUE'
 AND PRODUTO=I.PRODUTO ) AS ESTOQUE
 
FROM W_INDICADORES_COMERCIAL_INDUSTRIAL I
WHERE (EMISSAO_INICIAL >= CONVERT (DATE, @DATAINI, 103) AND EMISSAO_FINAL <= CONVERT (DATE, @DATAFIM, 103) 
OR EMISSAO_INICIAL >= CONVERT (DATE, '01-01-1900', 103) AND EMISSAO_FINAL <= CONVERT (DATE, '01-01-1900', 103)) 
) AS INDICADORES
WHERE PRODUTO NOT IN ('4000','5000','7000') AND (PREVISAO+CARTEIRA+PROCESSO>0)
ORDER BY PRODUTO



SELECT PRODUTO, (SELECT ISNULL(SUM(QTDE), 0) AS QTDE FROM W_INDICADORES_COMERCIAL_INDUSTRIAL WITH (NOLOCK) WHERE (TIPO = 'PREVISÃO (VENDAS)') AND (EMISSAO_INICIAL >= CONVERT (DATE, @DATAINI, 103)) AND (EMISSAO_FINAL <= CONVERT (DATE, @DATAFIM, 103)) AND (PRODUTO = I.PRODUTO)) AS PREVISAO, (SELECT ISNULL(SUM(QTDE), 0) AS QTDE FROM W_INDICADORES_COMERCIAL_INDUSTRIAL AS W_INDICADORES_COMERCIAL_INDUSTRIAL_3 WITH (NOLOCK) WHERE (TIPO = 'CARTEIRA (VENDAS ENTREGAR)') AND (EMISSAO_INICIAL >= CONVERT (DATE, @DATAINI, 103)) AND (EMISSAO_FINAL <= CONVERT (DATE, @DATAFIM, 103)) AND (PRODUTO = I.PRODUTO)) AS CARTEIRA, (SELECT ISNULL(SUM(QTDE), 0) AS QTDE FROM W_INDICADORES_COMERCIAL_INDUSTRIAL AS W_INDICADORES_COMERCIAL_INDUSTRIAL_2 WITH (NOLOCK) WHERE (TIPO = 'PROCESSO') AND (PRODUTO = I.PRODUTO)) AS PROCESSO, (SELECT ISNULL(SUM(QTDE), 0) AS QTDE FROM W_INDICADORES_COMERCIAL_INDUSTRIAL AS W_INDICADORES_COMERCIAL_INDUSTRIAL_1 WITH (NOLOCK) WHERE (TIPO = 'ESTOQUE (DISPONÍVEL)') AND (PRODUTO = I.PRODUTO)) AS ESTOQUE FROM W_INDICADORES_COMERCIAL_INDUSTRIAL AS I ORDER BY PRODUTO



SELECT * FROM W_INDICADORES_COMERCIAL_INDUSTRIAL I
--WHERE EMISSAO_INICIAL >= '20131001' AND EMISSAO_FINAL <= '20131031'
ORDER BY PRODUTO


ALTER VIEW W_INDICADORES_COMERCIAL_INDUSTRIAL AS
SELECT TIPO='PREVISÃO (VENDAS)', VENDA_PREVISAO.EMISSAO_INICIAL,VENDA_PREVISAO.EMISSAO_FINAL,PRODUTO,QTDE=SUM(QTDE)  FROM VENDA_PREVISAO_PRODUTO WITH (NOLOCK)
JOIN VENDA_PREVISAO WITH (NOLOCK) ON VENDA_PREVISAO.PREVISAO_VENDA=VENDA_PREVISAO_PRODUTO.PREVISAO_VENDA
WHERE VENDA_PREVISAO.EMISSAO_INICIAL >= '20130101' 
GROUP BY VENDA_PREVISAO.EMISSAO_INICIAL,VENDA_PREVISAO.EMISSAO_FINAL,PRODUTO
UNION ALL 
SELECT 'CARTEIRA (VENDAS ENTREGAR)',VENDAS_PRODUTO.ENTREGA,VENDAS_PRODUTO.LIMITE_ENTREGA, PRODUTO,QTDE=SUM(QTDE_ENTREGAR) FROM VENDAS_PRODUTO WITH (NOLOCK)  
JOIN VENDAS WITH (NOLOCK) ON VENDAS.PEDIDO=VENDAS_PRODUTO.PEDIDO
WHERE VENDAS_PRODUTO.LIMITE_ENTREGA >= '20130101' 
GROUP BY VENDAS_PRODUTO.ENTREGA,VENDAS_PRODUTO.LIMITE_ENTREGA,PRODUTO
UNION ALL
SELECT 'PROCESSO',DATAINI='',DATAFIM='',PRODUTO,QTDE=SUM(QTDE_S) FROM PRODUCAO_TAREFAS_SALDO WITH (NOLOCK)
JOIN PRODUCAO_TAREFAS WITH (NOLOCK) ON PRODUCAO_TAREFAS.TAREFA=PRODUCAO_TAREFAS_SALDO.TAREFA
WHERE PRODUCAO_TAREFAS.FASE_PRODUCAO NOT IN ('001')
GROUP BY PRODUTO
UNION ALL
SELECT 'ESTOQUE',DATAINI='',DATAFIM='',PRODUTO,ESTOQUE FROM (
SELECT EP.FILIAL,EP.PRODUTO,
ESTOQUE = (SELECT SUM(ESTOQUE) FROM ESTOQUE_PRODUTOS WITH (NOLOCK) WHERE PRODUTO=EP.PRODUTO AND FILIAL=EP.FILIAL)
--RESERVA = (SELECT ISNULL(SUM(QTDE_EMBALADA),0) FROM VENDAS_PROD_EMBALADO WITH (NOLOCK) WHERE FILIAL=EP.FILIAL AND PRODUTO=EP.PRODUTO)
FROM ESTOQUE_PRODUTOS EP WITH (NOLOCK)
WHERE EP.FILIAL='DR VAREJO'
GROUP BY EP.FILIAL,EP.PRODUTO ) AS ESTOQUE


select SUM(ESTOQUE) from ESTOQUE_PRODUTOS
WHERE PRODUTO='40605' AND FILIAL='dr varejo'

select SUM(QTDE_EMBALADA) from VENDAS_PROD_EMBALADO
WHERE PRODUTO='40605' AND FILIAL='dr varejo'



/* VISUALLINX Execute(Alias:xCurPrevisao)  */
LX_MRP_GERA_PREVISAO_VENDA 
@cPrevisaoVenda = 'PREV OUTUBRO/2013', @nQtdePrevisaoSemana = 90000, @nSemanaInicioPrevisao = 0, 
@nSemanaFimPrevisao = 5, @dInicioVenda = '20131001', @dFimVenda = '20131031', @nInicioSemana = 2, 
@sFiltroVendas = '',@sFiltroProduto = '',@dInicioGeracao = '20131009',@nTipoProcesso = 2


UPDATE VENDA_PREVISAO
SET EMISSAO_INICIAL='20131101',EMISSAO_FINAL='20131130'
WHERE PREVISAO_VENDA='PREV NOVEMBRO/2013'

/* VISUALLINX Execute(Alias:xCurPrevisao)  */
LX_MRP_GERA_PREVISAO_VENDA 
@cPrevisaoVenda = 'PREV NOVEMBRO/2013', @nQtdePrevisaoSemana = 112500, @nSemanaInicioPrevisao = 0, 
@nSemanaFimPrevisao = 4, @dInicioVenda = '20131101', @dFimVenda = '20131130', @nInicioSemana = 2, 
@sFiltroVendas = '',@sFiltroProduto = '',@dInicioGeracao = '20131022',@nTipoProcesso = 2

UPDATE VENDA_PREVISAO
SET EMISSAO_INICIAL='20131101',EMISSAO_FINAL='20131130'
WHERE PREVISAO_VENDA='PREV NOVEMBRO/2013'


/* VISUALLINX Execute(Alias:xCurPrevisao)  */
LX_MRP_GERA_PREVISAO_VENDA 
@cPrevisaoVenda = 'PREV DEZEMBRO/2013', @nQtdePrevisaoSemana = 50000, @nSemanaInicioPrevisao = 0, 
@nSemanaFimPrevisao = 4, @dInicioVenda = '20131201', @dFimVenda = '20131231', @nInicioSemana = 2, 
@sFiltroVendas = '',@sFiltroProduto = '',@dInicioGeracao = '20131022',@nTipoProcesso = 2


UPDATE VENDA_PREVISAO
SET EMISSAO_INICIAL='20131201',EMISSAO_FINAL='20131231'
WHERE PREVISAO_VENDA='PREV DEZEMBRO/2013'


select SUM(QTDE) from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV OUTUBRO/2013'

select SUM(QTDE) from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV NOVEMBRO/2013'

select SUM(QTDE) from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV DEZEMBRO/2013'


DELETE from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV OUTUBRO/2013'

DELETE from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV NOVEMBRO/2013'

DELETE from VENDA_PREVISAO_PRODUTO
where PREVISAO_VENDA='PREV DEZEMBRO/2013'


SELECT * FROM VENDA_PREVISAO

sp_helptext LX_MRP_GERA_PREVISAO_VENDA