SELECT 'PLANO DE PRODUÇÃO' AS ACAO, 
PLANEJADO = (SELECT SUM(B.QTDE_PROGRAMADA) FROM PRODUCAO_PROGRAMA A JOIN PRODUCAO_PROG_PROD B ON B.PROGRAMACAO=A.PROGRAMACAO WHERE A.PROGRAMACAO=AA.PROGRAMACAO),
REALIZADO = (SELECT SUM(B.QTDE_PROGRAMADA) FROM PRODUCAO_PROGRAMA A JOIN PRODUCAO_PROG_PROD B ON B.PROGRAMACAO=A.PROGRAMACAO WHERE A.PROGRAMACAO=AA.PROGRAMACAO)
FROM PRODUCAO_PROGRAMA AA 
WHERE AA.PROGRAMACAO='PREV JUL/2015' AND AA.DATA 




SELECT 'ABASTECIMENTO' AS MOVIMENTO,PLANEJADO=SUM(B.QTDE_PROGRAMADA) 
FROM PRODUCAO_PROGRAMA A
JOIN PRODUCAO_PROG_PROD B ON B.PROGRAMACAO=A.PROGRAMACAO
WHERE A.PROGRAMACAO='PREV JUL/2015'


EXEC msdb.dbo.sp_addrolemember @rolename = 'DatabaseMailUserRole'
    ,@membername = 'carla';
GO


USE msdb;
--add our user
CREATE USER  CARLA FOR LOGIN  CARLA; 
--give this user rights to use dbmail
exec sp_addrolemember 'DatabaseMailUserRole', 'CARLA'
