---- Inclusão de NCM nas tabelas SPED
INSERT INTO LCF_LX_NCM (COD_NCM,DESC_NCM) 
SELECT REPLACE(CLASSIF_FISCAL,'.',''),DESC_CLASSIFICACAO FROM CLASSIF_FISCAL
WHERE REPLACE(CLASSIF_FISCAL,'.','') NOT IN (SELECT COD_NCM FROM LCF_LX_NCM)
