---- ORIGINAL
select
PEDIDO.PEDCN_PEDIDO,
SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, (CHARINDEX('/', PEDIDO.PEDCN_PEDIDO)-1)) AS PEDIDO,
recpedido.RPENR_CODIGO AS CAIXA,
iterec.IRPNR_QUANTIDADE AS QUANTIDADE,
PROD.PROCC_PRODUTO AS PRODUTO,
prod.PRODS_TAM AS TAMANHO,
COR.CORNR_COR AS COR,
pb.CODIGO_BARRA as codigoBarras,
recpedido.RPEVL_PESO as PesoBruto,
(recpedido.RPEVL_PESO -recpedido.RPEVL_PESO_RECIPIENTE) AS PesoLiquido,
SEPARADOR.SEPNM_SEPARADOR AS EMBALADOR ,
PEDIDO.PEDDT_FIM_CONFERENCIA AS DATA_EMBALAGEM
 from
WMS_RECIPIENTE_PEDIDO recpedido
inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC ON recpedido.ISN_REC_PED = ITEREC.ISN_RECIPIENTE
INNER JOIN WMS_PRODUTO PROD ON PROD.ISN_PRODUTO = ITEREC.ISN_PRODUTO
inner join WMS_CORES cor on prod.PRONR_COR = cor.ISN_COR
INNER JOIN WMS_PEDIDO PEDIDO ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO
INNER join WMS_BARRA pb on pb.isn_produto = prod.isn_produto and prod.PRODS_TAM = pb.GRADE
INNER JOIN WMS_SEPARADOR SEPARADOR ON SEPARADOR.ISN_SEPARADOR = PEDIDO.ISN_SEPARADOR
where --PEDIDO.PEDCN_PEDIDO like '%/%' and recpedido.RPEVL_PESO is not null and
pedido.pedcn_pedido = '60063/1'


ALTER VIEW W_WMS_LINX_RESERVA AS 
---- VISAO PARA INTEGRAÇÃO WMS x LINX - CAPA
SELECT RECPEDIDO.ISN_REC_PED AS CAIXA,
       SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, (CHARINDEX('/',PEDIDO.PEDCN_PEDIDO)-1)) AS PEDIDO,
       isnull(recpedido.RPEVL_PESO,0) as PESO_BRUTO,
       ISNULL(recpedido.RPEVL_PESO - recpedido.RPEVL_PESO_RECIPIENTE,0) AS PESO_LIQUIDO,
       sum(iterec.IRPNR_QUANTIDADE) AS QUANTIDADE
  FROM WMS_RECIPIENTE_PEDIDO recpedido WITH (NOLOCK)
  INNER JOIN WMS_PEDIDO PEDIDO WITH (NOLOCK) ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO 
  inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC WITH (NOLOCK) ON recpedido.ISN_REC_PED = ITEREC.ISN_RECIPIENTE 
  where PEDIDO.PEDCN_PEDIDO like '%/%' AND recpedido.RPEVL_PESO is not null and PEDIDO.PEDFG_ERP = 'N' 
  --pedido.pedcn_pedido = '60063/1'
  group by recpedido.ISN_REC_PED,
       SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, (CHARINDEX('/',
       PEDIDO.PEDCN_PEDIDO)-1)),
       recpedido.RPEVL_PESO,
       ISNULL(recpedido.RPEVL_PESO - recpedido.RPEVL_PESO_RECIPIENTE,0)
       
GO       
        
ALTER VIEW W_WMS_LINX_RESERVA_ITEM AS
---- VISAO PARA INTEGRAÇÃO WMS x LINX - ITENS
SELECT ROMANEIO,PEDIDO,CAIXA,PRODUTO,COR AS COR_PRODUTO, 
QTDE_EMBALADA = ISNULL(SUM([1]),0)+ISNULL(SUM([2]),0)+ISNULL(SUM([3]),0)+ISNULL(SUM([4]),0)+ISNULL(SUM([5]),0)+
                ISNULL(SUM([6]),0)+ISNULL(SUM([7]),0)+ISNULL(SUM([8]),0)+ISNULL(SUM([9]),0)+ISNULL(SUM([10]),0)+
                ISNULL(SUM([11]),0)+ISNULL(SUM([12]),0)+ISNULL(SUM([13]),0)+ISNULL(SUM([14]),0)+ISNULL(SUM([15]),0)+ISNULL(SUM([16]),0),
E1=ISNULL(SUM([1]),0),
E2=ISNULL(SUM([2]),0),
E3=ISNULL(SUM([3]),0),
E4=ISNULL(SUM([4]),0),
E5=ISNULL(SUM([5]),0),
E6=ISNULL(SUM([6]),0),
E7=ISNULL(SUM([7]),0),
E8=ISNULL(SUM([8]),0),
E9=ISNULL(SUM([9]),0),
E10=ISNULL(SUM([10]),0),
E11=ISNULL(SUM([11]),0),
E12=ISNULL(SUM([12]),0),
E13=ISNULL(SUM([13]),0),
E14=ISNULL(SUM([14]),0),
E15=ISNULL(SUM([15]),0),
E16=ISNULL(SUM([16]),0)
FROM (
	SELECT recpedido.ISN_REC_PED AS CAIXA,
	       PEDIDO.PEDCN_PEDIDO AS ROMANEIO,  
	       SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, (CHARINDEX('/',
	       PEDIDO.PEDCN_PEDIDO)-1)) AS PEDIDO,
	       PROD.PROCC_PRODUTO AS PRODUTO,
           COR.CORNR_COR AS COR,
		   prod.PRODS_TAM AS GRADE,
	       PRODUTOS_BARRA.TAMANHO,
           SUM(iterec.IRPNR_QUANTIDADE) AS QUANTIDADE
	  FROM WMS_RECIPIENTE_PEDIDO recpedido WITH (NOLOCK)
	  inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC WITH (NOLOCK) ON recpedido.ISN_REC_PED = ITEREC.ISN_RECIPIENTE 
	  INNER JOIN WMS_PRODUTO PROD WITH (NOLOCK) ON PROD.ISN_PRODUTO = ITEREC.ISN_PRODUTO 
	  inner join WMS_CORES cor WITH (NOLOCK) on prod.PRONR_COR = cor.ISN_COR 
	  INNER JOIN WMS_PEDIDO PEDIDO WITH (NOLOCK) ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO 
	  INNER join WMS_BARRA pb WITH (NOLOCK) on pb.isn_produto = prod.isn_produto and prod.PRODS_TAM = pb.GRADE
	  INNER JOIN DRLINGERIE.DBO.PRODUTOS_BARRA PRODUTOS_BARRA WITH (NOLOCK) ON PRODUTOS_BARRA.CODIGO_BARRA = PB.CODIGO_BARRA
	  where PEDIDO.PEDCN_PEDIDO like '%/%' AND recpedido.RPEVL_PESO is not null and PEDIDO.PEDFG_ERP = 'N' 
	  --pedido.pedcn_pedido = '60063/1'
	  GROUP BY recpedido.ISN_REC_PED,
	        PEDIDO.PEDCN_PEDIDO,
			SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, (CHARINDEX('/',
			PEDIDO.PEDCN_PEDIDO)-1)),
			PROD.PROCC_PRODUTO,
			COR.CORNR_COR,
			prod.PRODS_TAM,
			PRODUTOS_BARRA.TAMANHO
) WMS_RECIPIENTE_PEDIDO 
PIVOT (SUM(QUANTIDADE) FOR TAMANHO IN ([1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16])) AS VENDAS_PROD_EMBALADO
GROUP BY ROMANEIO,PEDIDO,CAIXA,PRODUTO,COR
