--- 1o
--- REGIOES DE VENDA
INSERT INTO [REGIOES_VENDA]
           ([REGIAO]
           ,[PESO_DA_REGIAO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[MACRO_REGIAO]
           ,[COD_REGIAO_VENDA]
           ,[NIVEL_REGIAO]
           ,[INATIVO]
           ,[COD_TIPO_REGIAO_VENDA])
SELECT [REGIAO]
      ,[PESO_DA_REGIAO]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[MACRO_REGIAO]
      ,CAST('100069' AS INT)+ ROW_NUMBER() OVER(ORDER BY COD_REGIAO_VENDA) AS Row
      ,[NIVEL_REGIAO]
      ,[INATIVO]
      ,[COD_TIPO_REGIAO_VENDA]
FROM LDR.DRVAREJO.DBO.REGIOES_VENDA A
WHERE INATIVO=0 AND NOT EXISTS (SELECT * FROM REGIOES_VENDA WHERE REGIAO=A.REGIAO)           


--- 2o
--- CLIENTE_ATAC_BLOQ
INSERT INTO CLIENTE_ATAC_BLOQ
SELECT [TIPO_BLOQUEIO]
      ,[BLOQUEIA_CREDITO]
      ,[EXCLUSIVO_LINX]
      ,[DATA_PARA_TRANSFERENCIA]
FROM LDR.DRVAREJO.DBO.CLIENTE_ATAC_BLOQ A
WHERE NOT EXISTS(SELECT * FROM CLIENTE_ATAC_BLOQ WHERE TIPO_BLOQUEIO=A.TIPO_BLOQUEIO )


--- 3o 
--- CLIENTE_ATAC_PONT
INSERT INTO CLIENTE_ATAC_PONT
SELECT [PONTUALIDADE]
      ,[PESO_PONTUALIDADE]
      ,[MAIOR_ATRASO]
      ,[FREQUENCIA]
      ,[DATA_PARA_TRANSFERENCIA]
FROM LDR.DRVAREJO.DBO.CLIENTE_ATAC_PONT A
WHERE NOT EXISTS (SELECT * FROM CLIENTE_ATAC_PONT WHERE PONTUALIDADE=A.PONTUALIDADE)

--- 4o
--- CLIENTE_CONCEITOS
INSERT INTO CLIENTE_CONCEITOS
SELECT [CONCEITO]
      ,[PESO_DO_CONCEITO]
      ,[DATA_PARA_TRANSFERENCIA]
FROM LDR.DRVAREJO.DBO.CLIENTE_CONCEITOS A
WHERE NOT EXISTS(SELECT * FROM CLIENTE_CONCEITOS WHERE CONCEITO=A.CONCEITO )


--- 5o
--- CLIENTE_ATAC_TIPOS
INSERT INTO CLIENTE_ATAC_TIPOS
SELECT [TIPO]
      ,[PESO_DO_TIPO]
      ,[DESCONTO_MARGEM_CONTRIBUICAO]
      ,[DATA_PARA_TRANSFERENCIA]
  FROM LDR.DRVAREJO.DBO.CLIENTE_ATAC_TIPOS A
WHERE NOT EXISTS(SELECT * FROM CLIENTE_ATAC_TIPOS WHERE TIPO=A.TIPO)  

  
--- 6o 
--- TIPOS REPRESENTANTES
INSERT INTO REPRE_TIPOS
SELECT [TIPO]
      ,[DATA_PARA_TRANSFERENCIA]
FROM LDR.DRVAREJO.DBO.REPRE_TIPOS A
WHERE NOT EXISTS (SELECT TIPO FROM REPRE_TIPOS WHERE TIPO=A.TIPO)

--- 7o 
--- CADASTRO_CLI_FOR ( REPRESENTANTES )
INSERT INTO CADASTRO_CLI_FOR
           ([NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,[CONTA_CONTABIL]
           ,[CLIFOR]
           ,[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,[INATIVO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,[COD_CLIFOR]
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,[CLI_FOR])
SELECT [NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,A.[CONTA_CONTABIL]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
           ,A.[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,A.[INATIVO]
           ,A.[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,A.[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,A.[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
FROM LDR.DRVAREJO.DBO.[CADASTRO_CLI_FOR] A
JOIN LDR.DRVAREJO.DBO.[REPRESENTANTES] B ON B.REPRESENTANTE = A.NOME_CLIFOR
WHERE IND_REPRESENTANTE=1 AND B.INATIVO=0 AND A.INATIVO=0  
AND NOT EXISTS (SELECT * FROM REPRESENTANTES WHERE REPRESENTANTE=B.REPRESENTANTE) 
AND NOT EXISTS (SELECT * FROM CADASTRO_CLI_FOR WHERE NOME_CLIFOR=A.NOME_CLIFOR)
AND B.REPRESENTANTE<>'DENI RICARDO MONCAY CECHI'

--- 8o 
--- GERENTES
INSERT INTO [REPRESENTANTES]
           ([REPRESENTANTE]
           ,[GERENTE]
           ,[REGIAO]
           ,[TIPO]
           ,[COMISSAO]
           ,[PORCENTAGEM_ACERTO]
           ,[ACERTO_PGTO]
           ,[INATIVO]
           ,[MARGEM_NEGOCIACAO]
           ,[DESCONTO_COMISSAO]
           ,[CGC_CPF]
           ,[CLIFOR]
           ,[SEQUENCIAL]
           ,[COMISSAO_GERENTE]
           ,[IRRF]
           ,[COD_REPRESENTANTE]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[CONTA_CONTABIL]
           ,[CTB_CONTA_CONTABIL])
SELECT A.REPRESENTANTE
           ,'FABRICA'
           ,A.REGIAO
           ,A.TIPO
           ,A.COMISSAO
           ,A.PORCENTAGEM_ACERTO
           ,A.ACERTO_PGTO           
           ,A.INATIVO           
           ,A.MARGEM_NEGOCIACAO
           ,A.DESCONTO_COMISSAO
           ,A.CGC_CPF
           ,B.CLIFOR
           ,A.SEQUENCIAL
           ,A.COMISSAO_GERENTE
           ,A.IRRF
           ,B.CLIFOR
           ,A.DATA_PARA_TRANSFERENCIA
           ,A.CONTA_CONTABIL
           ,'1125001003'--A.CTB_CONTA_CONTABIL
FROM LDR.DRVAREJO.DBO.REPRESENTANTES A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.REPRESENTANTE
WHERE A.INATIVO=0
AND NOT EXISTS (SELECT * FROM REPRESENTANTES WHERE REPRESENTANTE=A.REPRESENTANTE) 
AND A.REPRESENTANTE IN(
'BRINDES - MERCHANDISING',  
'DENI RICARDO MONCAY CECHI',
'JOSE ANTONIO SARMENTO',    
'JOSE MARIO',               
'MARCUS CARIOCA',           
'SARMENTO - DR',            
'SERGIO PIRES',             
'SERGIO PIRES - DR',        
'VENDA DIRETA',            
'VENDA DIRETA - SERGIO PIR',
'VENDA DIRETA EXPORTACAO',
'VENDA DIRETA NACIONAL',    
'VENDA INTERNA')

--- 9o
--- ALTERAR REPRESENTANTES PARA GERENTES
UPDATE REPRESENTANTES
SET GERENTE=REPRESENTANTE
WHERE REPRESENTANTE IN(
'BRINDES - MERCHANDISING',  
'DENI RICARDO MONCAY CECHI',
'JOSE ANTONIO SARMENTO',    
'JOSE MARIO',               
'MARCUS CARIOCA',           
'SARMENTO - DR',            
'SERGIO PIRES',             
'SERGIO PIRES - DR',        
'VENDA DIRETA',            
'VENDA DIRETA - SERGIO PIR',
'VENDA DIRETA EXPORTACAO',
'VENDA DIRETA NACIONAL',    
'VENDA INTERNA')

--- 10o
--- REPRESENTANTES
INSERT INTO [REPRESENTANTES]
           ([REPRESENTANTE]
           ,[GERENTE]
           ,[REGIAO]
           ,[TIPO]
           ,[COMISSAO]
           ,[PORCENTAGEM_ACERTO]
           ,[ACERTO_PGTO]
           ,[INATIVO]
           ,[MARGEM_NEGOCIACAO]
           ,[DESCONTO_COMISSAO]
           ,[CGC_CPF]
           ,[CLIFOR]
           ,[SEQUENCIAL]
           ,[COMISSAO_GERENTE]
           ,[IRRF]
           ,[COD_REPRESENTANTE]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[CONTA_CONTABIL]
           ,[CTB_CONTA_CONTABIL])
SELECT A.REPRESENTANTE
           ,A.GERENTE
           ,A.REGIAO
           ,A.TIPO
           ,A.COMISSAO
           ,A.PORCENTAGEM_ACERTO
           ,A.ACERTO_PGTO           
           ,A.INATIVO           
           ,A.MARGEM_NEGOCIACAO
           ,A.DESCONTO_COMISSAO
           ,A.CGC_CPF
           ,B.CLIFOR
           ,A.SEQUENCIAL
           ,A.COMISSAO_GERENTE
           ,A.IRRF
           ,B.CLIFOR
           ,A.DATA_PARA_TRANSFERENCIA
           ,A.CONTA_CONTABIL
           ,'1125001003'--A.CTB_CONTA_CONTABIL
FROM LDR.DRVAREJO.DBO.REPRESENTANTES A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.REPRESENTANTE
WHERE A.INATIVO=0
AND not EXISTS (SELECT * FROM REPRESENTANTES WHERE REPRESENTANTE=A.REPRESENTANTE) 
AND A.GERENTE 
IN('BRINDES - MERCHANDISING',  
'DENI RICARDO MONCAY CECHI',
'JOSE ANTONIO SARMENTO',    
'JOSE MARIO',               
'MARCUS CARIOCA',           
'SARMENTO - DR',            
'SERGIO PIRES',             
'SERGIO PIRES - DR',        
'VENDA DIRETA',            
'VENDA DIRETA - SERGIO PIR',
'VENDA DIRETA EXPORTACAO',
'VENDA DIRETA NACIONAL',    
'VENDA INTERNA')

--- 11o
--- FORNECEDOR TIPO
INSERT INTO FORNECEDOR_TIPOS
SELECT [TIPO]
      ,[DATA_PARA_TRANSFERENCIA]
FROM LDR.DRVAREJO.DBO.FORNECEDOR_TIPOS A
WHERE NOT EXISTS(SELECT * FROM FORNECEDOR_TIPOS WHERE TIPO=A.TIPO)

--- 12o
--- FORNECEDOR SUBTIPO
INSERT INTO FORNECEDOR_SUBTIPO
SELECT [SUBTIPO_FORNECEDOR]
      ,[TIPO]
      ,[DATA_PARA_TRANSFERENCIA]
  FROM LDR.DRVAREJO.DBO.FORNECEDOR_SUBTIPO A
WHERE NOT EXISTS(SELECT * FROM FORNECEDOR_SUBTIPO WHERE SUBTIPO_FORNECEDOR=A.SUBTIPO_FORNECEDOR AND TIPO=A.TIPO) AND 
SUBTIPO_FORNECEDOR='REPRESENTAÇÃO' AND TIPO='SERVICOS'

--- 13o
--- FORNECEDORES
INSERT INTO FORNECEDORES
SELECT [FORNECEDOR]
      ,[CENTRO_CUSTO]
      ,[TIPO]
      ,[SUBTIPO_FORNECEDOR]
      ,B.CLIFOR
      ,B.CLIFOR
      ,[CONDICAO_PGTO]
      ,A.[CGC_CPF]
      ,[FORNECE_MATERIAIS]
      ,[FORNECE_PROD_ACAB]
      ,[FORNECE_MAT_CONSUMO]
      ,[BENEFICIADOR]
      ,[FORNECE_OUTROS]
      ,[MOEDA]
      ,A.[INATIVO]
      ,A.[DATA_PARA_TRANSFERENCIA] 
      ,[LICENCIADO]
      ,[LICENDIADO_ROYALTIES]
      ,A.[CONTA_CONTABIL]
      ,'2125001'--[CTB_CONTA_CONTABIL]
      ,[LICENCIADO_ROYALTIES]
      ,[CQFOR_CLASSIFICACAO]
      ,[INDICA_CQFOR]
      ,[DIAS_DESCONTO_VENCIMENTO]
      ,[DESCONTO_VENCIMENTO]
      ,[VALOR_MINIMO_PEDIDO]
      ,[INDICA_TRANSPORTADORA]
      ,[LX_METODO_PAGAMENTO]
  FROM LDR.DRVAREJO.DBO.[FORNECEDORES] A
  JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.FORNECEDOR
WHERE EXISTS(SELECT * FROM REPRESENTANTES WHERE REPRESENTANTE=A.FORNECEDOR) 
AND A.FORNECEDOR <> 'DENI RICARDO MONCAY CECHI'  


--- 14o
--- FORMA DE PAGTO
INSERT INTO FORMA_PGTO
SELECT [CONDICAO_PGTO]
      ,[DESC_COND_PGTO]
      ,[TIPO_CONDICAO]
      ,[NUMERO_PARCELAS]
      ,[DESCONTO]
      ,[ENCARGO]
      ,[DESCONTO_ITEM]
      ,[DESCONTO_FATURAMENTO]
      ,[ENCARGO_FATURAMENTO]
      ,[DESCONTO_ITEM_FATURAMENTO]
      ,[DIAS_DESCONTO_VENCIMENTO]
      ,[DESCONTO_VENCIMENTO]
      ,[EXCLUSIVO_LINX]
      ,[CONDICAO_ESPECIAL]
      ,[VALOR_MINIMO_PARCELAMENTO]
      ,[VALOR_MAXIMO_PARCELAMENTO]
      ,[NOVO_PARCELAMENTO_MINIMO]
      ,[NOVO_PARCELAMENTO_MAXIMO]
      ,[INCIDE_SOBRE_PRECO]
      ,[PORC_ANTECIPACAO]
      ,[INDICA_PARCELAS_IGUAIS]
      ,[PARCELA_ARRED_MENOR]
      ,[PARCELA_ARRED_MAIOR]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[COND_PGTO_ENTRADA]
      ,[LX_TIPO_DOCUMENTO]
      ,[INDICA_NAO_ENVIO_BORDERO]
FROM LDR.DRVAREJO.DBO.FORMA_PGTO A
WHERE NOT EXISTS (SELECT * FROM FORMA_PGTO WHERE CONDICAO_PGTO=A.CONDICAO_PGTO)

--- 15o
--- FORMA_PGTO_PARCELA
INSERT INTO FORMA_PGTO_PARCELA
SELECT [CONDICAO_PGTO]
      ,[PARCELA]
      ,[DIAS_PARCELA]
      ,[PORCENTAGEM]
      ,[LX_TIPO_DOCUMENTO]
  FROM LDR.DRVAREJO.DBO.[FORMA_PGTO_PARCELA] A
WHERE NOT EXISTS(SELECT * FROM [FORMA_PGTO_PARCELA] WHERE CONDICAO_PGTO=A.CONDICAO_PGTO AND PARCELA=A.PARCELA)  

--- 16o
--- CLIENTES ATACADO ( REPRESENTANTES/GERENTES )
INSERT INTO CLIENTES_ATACADO
SELECT [CLIENTE_ATACADO]
      ,B.[CLIFOR]
      ,[CONDICAO_PGTO]
      ,[REGIAO]
      ,[MATRIZ_CLIENTE]
      ,[FILIAL]
      ,[PONTUALIDADE]
      ,'NOSSO CARRO'--[TRANSPORTADORA]
      ,[CONCEITO]
      ,[TIPO]
      ,[TIPO_BLOQUEIO]
      ,A.[CGC_CPF]
      ,B.[CLIFOR]
      ,[FRETE_A_PAGAR]
      ,[PRIORIDADE]
      ,[SEM_CREDITO]
      ,[LIMITE_CREDITO]
      ,[BLOQUEIO_EXPEDICAO]
      ,[BLOQUEIO_FATURAMENTO]
      ,[ACEITA_JUNTAR_PED]
      ,[BLOQUEIO_PEDIDOS]
      ,[NUMERO_PEDIDOS]
      ,[DATA_MAIOR_PEDIDO]
      ,[MAIOR_PEDIDO]
      ,[DATA_MAIOR_QTDE_PEDIDO]
      ,[MAIOR_QTDE_PEDIDO]
      ,[MAIOR_SALDO]
      ,[DATA_MAIOR_SALDO]
      ,[NUMERO_ATRASOS]
      ,[MAIOR_ATRASO]
      ,[PGTOS_CARTORIO]
      ,[NUMERO_DEVOLUCOES]
      ,[DATA_MAIOR_DEVOLUCAO]
      ,[MAIOR_DEVOLUCAO]
      ,[DATA_MAIOR_QTDE_DEV]
      ,[MAIOR_QTDE_DEV]
      ,[NUMERO_PRORROGACOES]
      ,[MAIOR_PRORROGACAO]
      ,[DESCONTO_FATURAMENTO]
      ,[OBS]
      ,A.[INATIVO]
      ,[MOEDA]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,[INDICA_FRANQUIA]
      ,'01'--[CODIGO_TAB_PRECO]
      ,[FATOR_CUSTO_FRANQUIA]
      ,[DESCONTO_PEDIDO_VENDA]
      ,[SEGURO_NUMERO_CONTRATO]
      ,[SEGURO_NUMERO_CLIENTE]
      ,[SEGURO_VALIDADE]
      ,A.[CONTA_CONTABIL] 
      ,A.[MESES_SEM_VENCIMENTO]
      ,[EXPEDICAO_COMPLETO_PEDIDO]
      ,[EXPEDICAO_COMPLETO_PACK]
      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]
      ,[EXPEDICAO_COMPLETO_COORDENADO]
      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]
      ,[EXPEDICAO_PORCENTAGEM_MINIMA]
      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[EXPEDICAO_VALOR_MAXIMO]
      ,[CONTA_CONTABIL_ANTECIPACAO]
      ,'NOSSO CARRO'--[TRANSP_REDESPACHO]
      ,[CONTA_CONTABIL_VENDAS_TIPO]
      ,'NOSSO CARRO'--[TRANSPORTADORA2]
      ,'1125001001'--[CTB_CONTA_CONTABIL]
      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO]
      ,[DESCONTO_BRUTO_1]
      ,[DESCONTO_BRUTO_2]
      ,[DESCONTO_BRUTO_3]
      ,[DESCONTO_BRUTO_4]
      ,[DESCONTO_SOBRE_1]
      ,[DESCONTO_SOBRE_2]
      ,[DESCONTO_SOBRE_3]
      ,[DESCONTO_SOBRE_4]
      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]
      ,[EXPEDICAO_ADEQUACAO_COR]
      ,[EXPEDICAO_ADEQUACAO_TAMANHO]
      ,[MULTI_DESCONTO_ACUMULAR]
      ,[INDICADOR_VENDA]
      ,[DATA_MAIOR_ATRASO]
      ,[MAIOR_VALOR_FATURADO]
      ,[DATA_MAIOR_VALOR_FATURADO]
      ,[DT_ULTIMA_VENDA]
      ,[DT_PENULTIMA_VENDA]
      ,[DT_ANTEPENULTIMA_VENDA]
      ,[DT_PRIMEIRA_VENDA]
      ,[CONTEUDO_XPED_NFE]
  FROM LDR.DRVAREJO.DBO.[CLIENTES_ATACADO] A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.CLIENTE_ATACADO  
WHERE EXISTS(SELECT * FROM REPRESENTANTES WHERE REPRESENTANTE=A.CLIENTE_ATACADO) AND B.IND_REPRESENTANTE=1 AND A.CLIENTE_ATACADO<>'DENI RICARDO MONCAY CECHI'

--- 17o
--- CLIENTE REPRE
INSERT INTO CLIENTE_REPRE
SELECT A.[REPRESENTANTE]
      ,A.[CLIENTE_ATACADO]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,A.[COMISSAO]
      ,A.[REPRESENTANTE_PRINCIPAL]
  FROM LDR.DRVAREJO.DBO.[CLIENTE_REPRE] A
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=A.CLIENTE_ATACADO 
JOIN REPRESENTANTES C ON C.REPRESENTANTE=A.REPRESENTANTE
WHERE NOT EXISTS(SELECT * FROM CLIENTE_REPRE WHERE REPRESENTANTE=A.REPRESENTANTE AND CLIENTE_ATACADO=A.CLIENTE_ATACADO)  
AND B.CTB_CONTA_CONTABIL='1125001001' AND B.INATIVO=0


--- 18o
--- CLIENTES ATACADO QUE COMPRARAM NOS ULTIMOS 3 ANOS
--- CADASTRO_CLI_FOR 
INSERT INTO CADASTRO_CLI_FOR
           ([NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,[CONTA_CONTABIL]
           ,[CLIFOR]
           ,[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,[INATIVO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,[COD_CLIFOR]
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,[CLI_FOR])
SELECT A.[NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,A.[CONTA_CONTABIL]
           ,CAST('509221' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row1
           ,A.[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,A.[INATIVO]
           ,A.[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,A.[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,CAST('509221' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row2
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,A.[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,CAST('509221' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row3
FROM LDR.DRVAREJO.DBO.[CADASTRO_CLI_FOR] A
JOIN (
SELECT A.CLIFOR,A.NOME_CLIFOR,
DATA_ULTIMA_COMPRA=(SELECT MAX(EMISSAO) FROM LDR.DRVAREJO.DBO.VENDAS B WHERE B.CLIENTE_ATACADO=A.NOME_CLIFOR) 
FROM LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR A
JOIN LDR.DRVAREJO.DBO.CLIENTES_ATACADO C ON C.CLIENTE_ATACADO=A.NOME_CLIFOR
WHERE A.INATIVO=0 AND C.INATIVO=0 AND A.PJ_PF='1'
GROUP BY A.CLIFOR,A.NOME_CLIFOR
HAVING DATEDIFF(DD,(SELECT MAX(EMISSAO) FROM LDR.DRVAREJO.DBO.VENDAS B WHERE B.CLIENTE_ATACADO=A.NOME_CLIFOR),GETDATE())<=1095 
) B ON B.NOME_CLIFOR=A.NOME_CLIFOR
WHERE NOT EXISTS (SELECT * FROM CADASTRO_CLI_FOR WHERE NOME_CLIFOR=A.NOME_CLIFOR) 

--- 19o
--- CLIENTES ATACADO
INSERT INTO CLIENTES_ATACADO
SELECT [CLIENTE_ATACADO]
      ,B.[CLIFOR]
      ,[CONDICAO_PGTO]
      ,[REGIAO]
      ,[CLIENTE_ATACADO]
      ,[FILIAL]
      ,[PONTUALIDADE]
      ,'NOSSO CARRO'--[TRANSPORTADORA]
      ,[CONCEITO]
      ,[TIPO]
      ,[TIPO_BLOQUEIO]
      ,A.[CGC_CPF]
      ,B.[CLIFOR]
      ,[FRETE_A_PAGAR]
      ,[PRIORIDADE]
      ,[SEM_CREDITO]
      ,[LIMITE_CREDITO]
      ,[BLOQUEIO_EXPEDICAO]
      ,[BLOQUEIO_FATURAMENTO]
      ,[ACEITA_JUNTAR_PED]
      ,[BLOQUEIO_PEDIDOS]
      ,[NUMERO_PEDIDOS]
      ,[DATA_MAIOR_PEDIDO]
      ,[MAIOR_PEDIDO]
      ,[DATA_MAIOR_QTDE_PEDIDO]
      ,[MAIOR_QTDE_PEDIDO]
      ,[MAIOR_SALDO]
      ,[DATA_MAIOR_SALDO]
      ,[NUMERO_ATRASOS]
      ,[MAIOR_ATRASO]
      ,[PGTOS_CARTORIO]
      ,[NUMERO_DEVOLUCOES]
      ,[DATA_MAIOR_DEVOLUCAO]
      ,[MAIOR_DEVOLUCAO]
      ,[DATA_MAIOR_QTDE_DEV]
      ,[MAIOR_QTDE_DEV]
      ,[NUMERO_PRORROGACOES]
      ,[MAIOR_PRORROGACAO]
      ,[DESCONTO_FATURAMENTO]
      ,[OBS]
      ,A.[INATIVO]
      ,[MOEDA]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,[INDICA_FRANQUIA]
      ,'01'--[CODIGO_TAB_PRECO]
      ,[FATOR_CUSTO_FRANQUIA]
      ,[DESCONTO_PEDIDO_VENDA]
      ,[SEGURO_NUMERO_CONTRATO]
      ,[SEGURO_NUMERO_CLIENTE]
      ,[SEGURO_VALIDADE]
      ,A.[CONTA_CONTABIL] 
      ,A.[MESES_SEM_VENCIMENTO]
      ,[EXPEDICAO_COMPLETO_PEDIDO]
      ,[EXPEDICAO_COMPLETO_PACK]
      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]
      ,[EXPEDICAO_COMPLETO_COORDENADO]
      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]
      ,[EXPEDICAO_PORCENTAGEM_MINIMA]
      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[EXPEDICAO_VALOR_MAXIMO]
      ,[CONTA_CONTABIL_ANTECIPACAO]
      ,'NOSSO CARRO'--[TRANSP_REDESPACHO]
      ,[CONTA_CONTABIL_VENDAS_TIPO]
      ,'NOSSO CARRO'--[TRANSPORTADORA2]
      ,'1125001001'--[CTB_CONTA_CONTABIL]
      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO]
      ,[DESCONTO_BRUTO_1]
      ,[DESCONTO_BRUTO_2]
      ,[DESCONTO_BRUTO_3]
      ,[DESCONTO_BRUTO_4]
      ,[DESCONTO_SOBRE_1]
      ,[DESCONTO_SOBRE_2]
      ,[DESCONTO_SOBRE_3]
      ,[DESCONTO_SOBRE_4]
      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]
      ,[EXPEDICAO_ADEQUACAO_COR]
      ,[EXPEDICAO_ADEQUACAO_TAMANHO]
      ,[MULTI_DESCONTO_ACUMULAR]
      ,[INDICADOR_VENDA]
      ,[DATA_MAIOR_ATRASO]
      ,[MAIOR_VALOR_FATURADO]
      ,[DATA_MAIOR_VALOR_FATURADO]
      ,[DT_ULTIMA_VENDA]
      ,[DT_PENULTIMA_VENDA]
      ,[DT_ANTEPENULTIMA_VENDA]
      ,[DT_PRIMEIRA_VENDA]
      ,[CONTEUDO_XPED_NFE]
  FROM LDR.DRVAREJO.DBO.[CLIENTES_ATACADO] A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.CLIENTE_ATACADO  
WHERE NOT EXISTS(SELECT * FROM CLIENTES_ATACADO WHERE CLIENTE_ATACADO=A.CLIENTE_ATACADO) AND B.INDICA_CLIENTE=1 AND A.CLIENTE_ATACADO<>'DENI RICARDO MONCAY CECHI' AND A.CLIENTE_ATACADO<>''


--- 20o
--- CLIENTE REPRE 
INSERT INTO CLIENTE_REPRE
SELECT A.[REPRESENTANTE]
      ,A.[CLIENTE_ATACADO]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,A.[COMISSAO]
      ,A.[REPRESENTANTE_PRINCIPAL]
  FROM LDR.DRVAREJO.DBO.[CLIENTE_REPRE] A
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=A.CLIENTE_ATACADO 
JOIN REPRESENTANTES C ON C.REPRESENTANTE=A.REPRESENTANTE
WHERE NOT EXISTS(SELECT * FROM CLIENTE_REPRE WHERE REPRESENTANTE=A.REPRESENTANTE AND CLIENTE_ATACADO=A.CLIENTE_ATACADO)  
AND B.CTB_CONTA_CONTABIL='1125001001' AND B.INATIVO=0


-------------------------------- BALCONISTAS --------------------------------------
SELECT * FROM DRLINGERIE.DBO.SEQUENCIAIS
WHERE TABELA_COLUNA='CLIENTES_ATACADO.CLIFOR'

--- 21o
--- CLIENTES BANCONISTAS  
--- CADASTRO_CLI_FOR 
INSERT INTO CADASTRO_CLI_FOR
           ([NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,[CONTA_CONTABIL]
           ,[CLIFOR]
           ,[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,[INATIVO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,[COD_CLIFOR]
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,[CLI_FOR])
SELECT A.[NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,A.[CONTA_CONTABIL]
           ,CAST('507963' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row1
           ,A.[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,A.[INATIVO]
           ,A.[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,A.[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,CAST('507963' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row2
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,A.[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,CAST('507963' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row3
FROM LDR.DRVAREJO.DBO.[CADASTRO_CLI_FOR] A
JOIN (
SELECT A.CLIFOR,A.NOME_CLIFOR,
DATA_ULTIMA_COMPRA=(SELECT MAX(EMISSAO) FROM LDR.DRVAREJO.DBO.VENDAS B WHERE B.CLIENTE_ATACADO=A.NOME_CLIFOR) 
FROM LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR A
JOIN LDR.DRVAREJO.DBO.CLIENTES_ATACADO C ON C.CLIENTE_ATACADO=A.NOME_CLIFOR
WHERE A.INATIVO=0 AND C.INATIVO=0 AND A.PJ_PF='0' AND C.TIPO = 'BALCONISTA'
GROUP BY A.CLIFOR,A.NOME_CLIFOR
HAVING DATEDIFF(DD,(SELECT MAX(EMISSAO) FROM LDR.DRVAREJO.DBO.VENDAS B WHERE B.CLIENTE_ATACADO=A.NOME_CLIFOR),GETDATE())<=1095 
) B ON B.NOME_CLIFOR=A.NOME_CLIFOR
WHERE NOT EXISTS (SELECT * FROM CADASTRO_CLI_FOR WHERE NOME_CLIFOR=A.NOME_CLIFOR) 



--- 22o
--- CLIENTES ATACADO
INSERT INTO CLIENTES_ATACADO
SELECT [CLIENTE_ATACADO]
      ,B.[CLIFOR]
      ,[CONDICAO_PGTO]
      ,[REGIAO]
      ,[CLIENTE_ATACADO]
      ,[FILIAL]
      ,[PONTUALIDADE]
      ,'NOSSO CARRO'--[TRANSPORTADORA]
      ,[CONCEITO]
      ,[TIPO]
      ,[TIPO_BLOQUEIO]
      ,A.[CGC_CPF]
      ,B.[CLIFOR]
      ,[FRETE_A_PAGAR]
      ,[PRIORIDADE]
      ,[SEM_CREDITO]
      ,[LIMITE_CREDITO]
      ,[BLOQUEIO_EXPEDICAO]
      ,[BLOQUEIO_FATURAMENTO]
      ,[ACEITA_JUNTAR_PED]
      ,[BLOQUEIO_PEDIDOS]
      ,[NUMERO_PEDIDOS]
      ,[DATA_MAIOR_PEDIDO]
      ,[MAIOR_PEDIDO]
      ,[DATA_MAIOR_QTDE_PEDIDO]
      ,[MAIOR_QTDE_PEDIDO]
      ,[MAIOR_SALDO]
      ,[DATA_MAIOR_SALDO]
      ,[NUMERO_ATRASOS]
      ,[MAIOR_ATRASO]
      ,[PGTOS_CARTORIO]
      ,[NUMERO_DEVOLUCOES]
      ,[DATA_MAIOR_DEVOLUCAO]
      ,[MAIOR_DEVOLUCAO]
      ,[DATA_MAIOR_QTDE_DEV]
      ,[MAIOR_QTDE_DEV]
      ,[NUMERO_PRORROGACOES]
      ,[MAIOR_PRORROGACAO]
      ,[DESCONTO_FATURAMENTO]
      ,[OBS]
      ,A.[INATIVO]
      ,[MOEDA]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,[INDICA_FRANQUIA]
      ,'VA'--[CODIGO_TAB_PRECO]
      ,[FATOR_CUSTO_FRANQUIA]
      ,[DESCONTO_PEDIDO_VENDA]
      ,[SEGURO_NUMERO_CONTRATO]
      ,[SEGURO_NUMERO_CLIENTE]
      ,[SEGURO_VALIDADE]
      ,A.[CONTA_CONTABIL] 
      ,A.[MESES_SEM_VENCIMENTO]
      ,[EXPEDICAO_COMPLETO_PEDIDO]
      ,[EXPEDICAO_COMPLETO_PACK]
      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]
      ,[EXPEDICAO_COMPLETO_COORDENADO]
      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]
      ,[EXPEDICAO_PORCENTAGEM_MINIMA]
      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[EXPEDICAO_VALOR_MAXIMO]
      ,[CONTA_CONTABIL_ANTECIPACAO]
      ,'NOSSO CARRO'--[TRANSP_REDESPACHO]
      ,[CONTA_CONTABIL_VENDAS_TIPO]
      ,'NOSSO CARRO'--[TRANSPORTADORA2]
      ,'1125001001'--[CTB_CONTA_CONTABIL]
      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO]
      ,[DESCONTO_BRUTO_1]
      ,[DESCONTO_BRUTO_2]
      ,[DESCONTO_BRUTO_3]
      ,[DESCONTO_BRUTO_4]
      ,[DESCONTO_SOBRE_1]
      ,[DESCONTO_SOBRE_2]
      ,[DESCONTO_SOBRE_3]
      ,[DESCONTO_SOBRE_4]
      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]
      ,[EXPEDICAO_ADEQUACAO_COR]
      ,[EXPEDICAO_ADEQUACAO_TAMANHO]
      ,[MULTI_DESCONTO_ACUMULAR]
      ,[INDICADOR_VENDA]
      ,[DATA_MAIOR_ATRASO]
      ,[MAIOR_VALOR_FATURADO]
      ,[DATA_MAIOR_VALOR_FATURADO]
      ,[DT_ULTIMA_VENDA]
      ,[DT_PENULTIMA_VENDA]
      ,[DT_ANTEPENULTIMA_VENDA]
      ,[DT_PRIMEIRA_VENDA]
      ,[CONTEUDO_XPED_NFE]
  FROM LDR.DRVAREJO.DBO.[CLIENTES_ATACADO] A
JOIN CADASTRO_CLI_FOR B ON B.NOME_CLIFOR=A.CLIENTE_ATACADO  
WHERE NOT EXISTS(SELECT * FROM CLIENTES_ATACADO WHERE CLIENTE_ATACADO=A.CLIENTE_ATACADO) AND B.INDICA_CLIENTE=1 AND A.CLIENTE_ATACADO<>'DENI RICARDO MONCAY CECHI' AND A.CLIENTE_ATACADO<>''


--- 23o
--- CLIENTE REPRE 
INSERT INTO CLIENTE_REPRE
SELECT A.[REPRESENTANTE]
      ,A.[CLIENTE_ATACADO]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,A.[COMISSAO]
      ,A.[REPRESENTANTE_PRINCIPAL]
  FROM LDR.DRVAREJO.DBO.[CLIENTE_REPRE] A
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=A.CLIENTE_ATACADO 
JOIN REPRESENTANTES C ON C.REPRESENTANTE=A.REPRESENTANTE
WHERE NOT EXISTS(SELECT * FROM CLIENTE_REPRE WHERE REPRESENTANTE=A.REPRESENTANTE AND CLIENTE_ATACADO=A.CLIENTE_ATACADO)  
AND B.CTB_CONTA_CONTABIL='1125001001' AND B.INATIVO=0 AND B.TIPO='BALCONISTA'

-----------------------------------------------------------------------------------

--- APOIO AO BANCO TESTE COM AS NOVAS CONTAS CRIADAS PELO ELTON
INSERT INTO CTB_CONTA_TIPO
SELECT [TIPO_CONTA]
      ,[DESC_CONTA_TIPO]
      ,[CONTA_OBRIGATORIA]
      ,[INDICA_ID_CONTABIL_TERCEIRO]
  FROM [DRLINGERIE].[dbo].[CTB_CONTA_TIPO] A 
WHERE NOT EXISTS(SELECT * FROM CTB_CONTA_TIPO WHERE TIPO_CONTA=A.TIPO_CONTA)

INSERT INTO CTB_CONTA_PLANO
SELECT [CONTA_CONTABIL]
      ,[RATEIO_CENTRO_CUSTO]
      ,[CODIGO_HISTORICO]
      ,[LX_GRUPO_FLUXO]
      ,[DESC_CONTA]
      ,[TIPO_CONTA]
      ,[INATIVA]
      ,[CODIGO_RESUMIDO]
      ,[CONTA_CORRENTE]
      ,[ULTIMO_CHEQUE]
      ,[EXPORTACAO_CONTA_CONTABIL]
      ,[EXPORTACAO_TIPO]
      ,[CONTA_PORTADORA]
      ,[DESC_CONTA_REDUZIDA]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[ID_CARTEIRA_COBRANCA]
      ,[DESC_DETALHADA]
      ,[BANCO]
      ,[AGENCIA]
      ,[NUMERO_CONTA_CORRENTE]
      ,[COD_CLIFOR]
      ,[MOEDA]
      ,[LX_GRUPO_CONTABIL]
      ,[LANCAMENTO_PADRAO]
      ,[LANCAMENTO_PADRAO_DEFLACAO]
      ,[LIMITE_CONTA_CORRENTE]
      ,[SALDO_BLOQ_CONTA_CORRENTE]
      ,[PREVISAO_DESPESA]
      ,[ID_IMPOSTO]
      ,[COD_FILIAL]
      ,[INDICA_CONSOLIDACAO]
      ,[INDICA_CTRL_ORCAMENTO]
      ,[CONVENIO]
  FROM [DRLINGERIE].[dbo].[CTB_CONTA_PLANO] A
WHERE NOT EXISTS (SELECT * FROM CTB_CONTA_PLANO WHERE CONTA_CONTABIL=A.CONTA_CONTABIL) 


--- DESCOBRE AS TRIGGERS CRIADAS NA DR
SELECT     name, OBJECT_NAME(parent_obj) AS tabela
FROM         sysobjects
WHERE     (xtype = 'TR') and name like 'D%'


--- DESCOBRE AS TRIGGERS CRIADAS NA LDR
SELECT     name, OBJECT_NAME(parent_obj) AS tabela
FROM         LDR.DRVAREJO.DBO.sysobjects A
WHERE     (xtype = 'TR') and name like 'LDR%' and not exists(
SELECT name, OBJECT_NAME(parent_obj) AS tabela
FROM         sysobjects
WHERE     (xtype = 'TR') AND name=A.NAME
)
ORDER BY TABELA



USE [DRVAREJO]
GO

/****** Object:  Table [dbo].[COTA_LIMITE_PERFAT]    Script Date: 12/08/2015 15:35:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COTA_LIMITE_PERFAT](
	[NUMERO_ENTREGA] [char](2) NOT NULL,
	[PERIODO_PCP] [varchar](25) NOT NULL,
	[QTDE_LIMITE] [numeric](14, 0) NULL,
	[FECHADO] [bit] NULL,
 CONSTRAINT [PK_COTA_LIMITE_PERFAT] PRIMARY KEY CLUSTERED 
(
	[NUMERO_ENTREGA] ASC,
	[PERIODO_PCP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

UPDATE COTA_LIMITE_PERFAT
SET FECHADO=0
FROM COTA_LIMITE_PERFAT A
JOIN PRODUTOS_PERIODOS_ENTREGAS B ON B.NUMERO_ENTREGA=A.NUMERO_ENTREGA AND B.PERIODO_PCP=A.PERIODO_PCP
WHERE B.ENTREGA>'20160101' AND B.ENTREGA<='20160331'



SELECT * FROM COTA_LIMITE_PERFAT
WHERE FECHADO=0
ORDER BY NUMERO_ENTREGA

INSERT INTO COTA_LIMITE_PERFAT
SELECT NUMERO_ENTREGA,PERIODO_PCP,50000,1 FROM PRODUTOS_PERIODOS_ENTREGAS
WHERE ENTREGA>'20150101'


SELECT * FROM PRODUTOS_PERIODOS_PCP
WHERE PERIODO_PCP LIKE 'DEZ%2015'

SELECT * FROM PRODUTOS_PERIODOS_ENTREGAS
WHERE PERIODO_PCP LIKE 'DEZ%2015'

ORDER BY NUMERO_ENTREGA




USE [DRVAREJO]
GO

/****** Object:  Table [dbo].[LDR_PRODUTOS_PERIODOS_ENTREGAS_FUTURAS]    Script Date: 12/08/2015 16:05:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LDR_PRODUTOS_PERIODOS_ENTREGAS_FUTURAS](
	[PRODUTO] [char](12) NULL,
	[COR_PRODUTO] [char](10) NULL,
	[ENTREGA] [datetime] NULL,
	[PEDIDO_EXTERNO] [char](12) NULL,
	[NUMERO_ENTREGA] [char](2) NULL,
	[LIMITE_ENTREGA] [datetime] NULL,
	[ENVIAR_EMAIL] [bit] NULL,
	[REPRESENTANTE] [varchar](25) NULL,
	[CLIENTE_ATACADO] [varchar](25) NULL,
	[NUMERO_ENTREGA_REP] [char](2) NULL,
	[GERENTE] [varchar](25) NULL,
	[QTDE_ORIGINAL] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



SELECT * FROM LDR_PRODUTO_COR_ENTREGA_FUTURA


INSERT INTO LDR_PRODUTO_COR_ENTREGA_FUTURA
SELECT PRODUTO,COR_PRODUTO,'DEZEMBRO 2015','49','20151129','20151205' 
FROM PRODUTO_CORES
WHERE PRODUTO LIKE 'V%'







CREATE TABLE [dbo].[LDR_PRODUTO_COR_ENTREGA_FUTURA](
	[PRODUTO] [char](12) NOT NULL,
	[COR_PRODUTO] [char](10) NOT NULL,
	[PERIODO_PCP] [varchar](25) NOT NULL,
	[NUMERO_ENTREGA] [char](2) NOT NULL,
	[ENTREGA] [datetime] NOT NULL,
	[LIMITE] [datetime] NOT NULL,
 CONSTRAINT [PK_LDR_PRODUTO_COR_ENTREGA_FUTURA] PRIMARY KEY CLUSTERED 
(
	[PRODUTO] ASC,
	[COR_PRODUTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



USE [DRVAREJO]
GO

/****** Object:  Table [dbo].[SFV_MATERIAL_PROMOCIONAL]    Script Date: 12/08/2015 16:37:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

SELECT * FROM SFV_MATERIAL_PROMOCIONAL

CREATE TABLE [dbo].[SFV_MATERIAL_PROMOCIONAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


---- CONTAS A RECEBER E CONTAS A PAGAR
SELECT DISTINCT B.CONTA_PORTADOR,C.DESC_CONTA 
FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
WHERE B.VALOR_A_RECEBER>0
union all
SELECT DISTINCT B.CONTA_PORTADOR,C.DESC_CONTA 
FROM LDR.DRVAREJO.DBO.CTB_A_PAGAR_FATURA A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.CTB_A_PAGAR_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
WHERE B.VALOR_A_PAGAR>0



--- lancamentos contas a receber
--- CLIENTES
SELECT DISTINCT D.NOME_CLIFOR,D.CGC_CPF
FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001' 
AND NOT EXISTS(SELECT * FROM CADASTRO_CLI_FOR WHERE CGC_CPF=D.CGC_CPF)


SELECT *
FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001'
AND NOT EXISTS(SELECT * FROM CADASTRO_CLI_FOR WHERE CGC_CPF=D.CGC_CPF)



--- CADASTRO_CLI_FOR 
INSERT INTO CADASTRO_CLI_FOR
           ([NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,[CONTA_CONTABIL]
           ,[CLIFOR]
           ,[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,[INATIVO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,[COD_CLIFOR]
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,[CLI_FOR])
SELECT RTRIM(A.[NOME_CLIFOR])+'V'
           ,[CARTEIRA]
           ,[BANCO]
           ,A.[CONTA_CONTABIL]
           ,CAST('509225' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row1
           ,A.[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,A.[INATIVO]
           ,A.[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,A.[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,CAST('509225' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row2
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,A.[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,CAST('509225' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row3
FROM LDR.DRVAREJO.DBO.[CADASTRO_CLI_FOR] A WITH (NOLOCK)
WHERE A.CGC_CPF IN(
'01734350000144',
'06376136000187',     
'07144564000147',     
'07149375000167',
'12261563000112',
'18096204000133',     
'18902002000131',     
'20722612000103')     

SP_HELP CADASTRO_CLI_FOR

SELECT * FROM SEQUENCIAIS
WHERE TABELA_COLUNA='CLIENTES_ATACADO.CLIFOR'


--- CLIENTES ATACADO
INSERT INTO CLIENTES_ATACADO
SELECT C.NOME_CLIFOR
      ,C.[CLIFOR]
      ,[CONDICAO_PGTO]
      ,[REGIAO]
      ,C.NOME_CLIFOR
      ,[FILIAL]
      ,[PONTUALIDADE]
      ,'NOSSO CARRO'--[TRANSPORTADORA]
      ,[CONCEITO]
      ,[TIPO]
      ,[TIPO_BLOQUEIO]
      ,A.[CGC_CPF]
      ,C.[CLIFOR]
      ,[FRETE_A_PAGAR]
      ,[PRIORIDADE]
      ,[SEM_CREDITO]
      ,[LIMITE_CREDITO]
      ,[BLOQUEIO_EXPEDICAO]
      ,[BLOQUEIO_FATURAMENTO]
      ,[ACEITA_JUNTAR_PED]
      ,[BLOQUEIO_PEDIDOS]
      ,[NUMERO_PEDIDOS]
      ,[DATA_MAIOR_PEDIDO]
      ,[MAIOR_PEDIDO]
      ,[DATA_MAIOR_QTDE_PEDIDO]
      ,[MAIOR_QTDE_PEDIDO]
      ,[MAIOR_SALDO]
      ,[DATA_MAIOR_SALDO]
      ,[NUMERO_ATRASOS]
      ,[MAIOR_ATRASO]
      ,[PGTOS_CARTORIO]
      ,[NUMERO_DEVOLUCOES]
      ,[DATA_MAIOR_DEVOLUCAO]
      ,[MAIOR_DEVOLUCAO]
      ,[DATA_MAIOR_QTDE_DEV]
      ,[MAIOR_QTDE_DEV]
      ,[NUMERO_PRORROGACOES]
      ,[MAIOR_PRORROGACAO]
      ,[DESCONTO_FATURAMENTO]
      ,[OBS]
      ,A.[INATIVO]
      ,[MOEDA]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,[INDICA_FRANQUIA]
      ,'VA'--[CODIGO_TAB_PRECO]
      ,[FATOR_CUSTO_FRANQUIA]
      ,[DESCONTO_PEDIDO_VENDA]
      ,[SEGURO_NUMERO_CONTRATO]
      ,[SEGURO_NUMERO_CLIENTE]
      ,[SEGURO_VALIDADE]
      ,A.[CONTA_CONTABIL] 
      ,A.[MESES_SEM_VENCIMENTO]
      ,[EXPEDICAO_COMPLETO_PEDIDO]
      ,[EXPEDICAO_COMPLETO_PACK]
      ,[EXPEDICAO_COMPLETO_TAMANHOS]
      ,[EXPEDICAO_COMPLETO_COR]
      ,[EXPEDICAO_COMPLETO_COORDENADO]
      ,[EXPEDICAO_COMPLETO_CARTELA]
      ,[EXPEDICAO_PORCENTAGEM_MAIOR]
      ,[EXPEDICAO_PORCENTAGEM_MINIMA]
      ,[EXPEDICAO_PORCENTAGEM_TIPO]
      ,[EXPEDICAO_VALOR_MAXIMO]
      ,[CONTA_CONTABIL_ANTECIPACAO]
      ,'NOSSO CARRO'--[TRANSP_REDESPACHO]
      ,[CONTA_CONTABIL_VENDAS_TIPO]
      ,'NOSSO CARRO'--[TRANSPORTADORA2]
      ,'1125001001'--[CTB_CONTA_CONTABIL]
      ,[EXPEDICAO_COMPLETO_FAIXAS]
      ,[DESCONTO_BRUTO]
      ,[DESCONTO_BRUTO_1]
      ,[DESCONTO_BRUTO_2]
      ,[DESCONTO_BRUTO_3]
      ,[DESCONTO_BRUTO_4]
      ,[DESCONTO_SOBRE_1]
      ,[DESCONTO_SOBRE_2]
      ,[DESCONTO_SOBRE_3]
      ,[DESCONTO_SOBRE_4]
      ,[EXPEDICAO_PORC_ADEQUACAO]
      ,[EXPEDICAO_QTDE_ADEQUACAO]
      ,[EXPEDICAO_ADEQUACAO_COR]
      ,[EXPEDICAO_ADEQUACAO_TAMANHO]
      ,[MULTI_DESCONTO_ACUMULAR]
      ,[INDICADOR_VENDA]
      ,[DATA_MAIOR_ATRASO]
      ,[MAIOR_VALOR_FATURADO]
      ,[DATA_MAIOR_VALOR_FATURADO]
      ,[DT_ULTIMA_VENDA]
      ,[DT_PENULTIMA_VENDA]
      ,[DT_ANTEPENULTIMA_VENDA]
      ,[DT_PRIMEIRA_VENDA]
      ,[CONTEUDO_XPED_NFE]
  FROM LDR.DRVAREJO.DBO.[CLIENTES_ATACADO] A WITH (NOLOCK)
JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR B WITH (NOLOCK) ON B.NOME_CLIFOR=A.CLIENTE_ATACADO
JOIN CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CGC_CPF=B.CGC_CPF
WHERE C.CGC_CPF IN(
'01734350000144',
'06376136000187',     
'07144564000147',     
'07149375000167',
'12261563000112',
'18096204000133',     
'18902002000131',     
'20722612000103')     

DELETE FROM CTB_LANCAMENTO
WHERE USUARIO='TI-LDR'

SELECT * FROM CTB_HIST_PADRAO
WHERE CODIGO_HISTORICO='LMD'

--- LANCAMENTOS
INSERT INTO CTB_LANCAMENTO
SELECT CAST('284377' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.LANCAMENTO) AS Row1
      ,[EMPRESA]
      ,[TIPO_MOVIMENTO]
      ,[LOTE_LANCAMENTO]
      ,[LANCAMENTO_PADRAO]=NULL
      ,[GERADO_INTEGRACAO]='0'
      ,[CONCILIADO]
      ,[DATA_CONCILIADO]
      ,[DATA_LANCAMENTO]
      ,[DATA_DIGITACAO]
      ,[COD_FILIAL]='000003'
      ,[ID_ASSINATURA_DOCUMENTO]
      ,[USUARIO]='TI-LDR'
      ,[LANCAMENTO_CAIXA]
      ,[TERMINAL]
      ,[PARCELA]
      ,[CAMBIO_NA_DATA_EMISSAO]
      ,[GERADO_VALOR_FINANCEIRO]
      ,[USUARIO_ASSINATURA]
      ,[DATA_ASSINATURA]
      ,[NUMERO_CORRELATIVO]=A.LANCAMENTO
      ,[TIPO_COMPROVANTE]
      ,[INDICA_DEPARA]
  FROM LDR.DRVAREJO.DBO.[CTB_LANCAMENTO] A WITH (NOLOCK) 
WHERE A.LANCAMENTO IN(
	SELECT DISTINCT A.LANCAMENTO
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001'
)

DELETE FROM CTB_LANCAMENTO_ITEM
WHERE CONTA_CONTABIL='9990001' AND LANCAMENTO>284377

SELECT * FROM CTB_LANCAMENTO_ITEM
WHERE CONTA_CONTABIL='9990001' AND LANCAMENTO>284377

---- debito
INSERT INTO CTB_LANCAMENTO_ITEM
SELECT A.[EMPRESA]
      ,B.[LANCAMENTO]
      ,A.[ITEM]
      ,[CONTA_CONTABIL]='9990001'
      ,[LX_TIPO_LANCAMENTO]
      ,[CREDITO]=0.00
      ,[DEBITO]=0.00
      ,[HISTORICO]
      ,[CODIGO_HISTORICO]
      ,A.[RATEIO_CENTRO_CUSTO]
      ,A.[CONCILIADO]
      ,A.[PERMITE_ALTERACAO]
      ,A.[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=0.00
      ,[CREDITO_MOEDA]=0.00
      ,A.[GERADO_AUTOMATICO_TIPO]
      ,A.[DATA_DIGITACAO]
      ,[RATEIO_FILIAL]='000003'
      ,[COD_CLIFOR]=D.CLIFOR
      ,A.[MOEDA]
      ,A.[CAMBIO_NA_DATA]
      ,A.[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]=0.00
      ,[VALOR_FINANCEIRO_PADRAO]=0.00
      ,A.[DATA_MOV]
      ,A.[USUARIO_MOV]
      ,A.[DOCUMENTO]
FROM LDR.DRVAREJO.DBO.[CTB_LANCAMENTO_ITEM] A WITH (NOLOCK) 
JOIN CTB_LANCAMENTO B WITH (NOLOCK) ON B.NUMERO_CORRELATIVO=A.LANCAMENTO
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CLIFOR=A.COD_CLIFOR
JOIN CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CGC_CPF=C.CGC_CPF AND D.NOME_CLIFOR=C.NOME_CLIFOR
WHERE RTRIM(CAST(B.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001'
)

---- EXCEÇÕES
INSERT INTO CTB_LANCAMENTO_ITEM
SELECT A.[EMPRESA]
      ,B.[LANCAMENTO]
      ,A.[ITEM]
      ,[CONTA_CONTABIL]='9990001'
      ,[LX_TIPO_LANCAMENTO]
      ,[CREDITO]=0.00
      ,[DEBITO]=0.00
      ,[HISTORICO]
      ,[CODIGO_HISTORICO]
      ,A.[RATEIO_CENTRO_CUSTO]
      ,A.[CONCILIADO]
      ,A.[PERMITE_ALTERACAO]
      ,A.[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=0.00
      ,[CREDITO_MOEDA]=0.00
      ,A.[GERADO_AUTOMATICO_TIPO]
      ,A.[DATA_DIGITACAO]
      ,[RATEIO_FILIAL]='000003'
      ,[COD_CLIFOR]=D.CLIFOR
      ,A.[MOEDA]
      ,A.[CAMBIO_NA_DATA]
      ,A.[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]=0.00
      ,[VALOR_FINANCEIRO_PADRAO]=0.00
      ,A.[DATA_MOV]
      ,A.[USUARIO_MOV]
      ,A.[DOCUMENTO]
FROM LDR.DRVAREJO.DBO.[CTB_LANCAMENTO_ITEM] A WITH (NOLOCK) 
JOIN CTB_LANCAMENTO B WITH (NOLOCK) ON B.NUMERO_CORRELATIVO=A.LANCAMENTO
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CLIFOR=A.COD_CLIFOR
JOIN CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CGC_CPF=C.CGC_CPF 
WHERE RTRIM(CAST(B.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
) AND A.COD_CLIFOR = '030130' AND D.NOME_CLIFOR='NANCY BALDERRAMA'


INSERT INTO CTB_LANCAMENTO_ITEM
SELECT A.[EMPRESA]
      ,B.[LANCAMENTO]
      ,A.[ITEM]
      ,[CONTA_CONTABIL]='9990001'
      ,[LX_TIPO_LANCAMENTO]
      ,[CREDITO]=0.00
      ,[DEBITO]=0.00
      ,[HISTORICO]
      ,[CODIGO_HISTORICO]
      ,A.[RATEIO_CENTRO_CUSTO]
      ,A.[CONCILIADO]
      ,A.[PERMITE_ALTERACAO]
      ,A.[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=0.00
      ,[CREDITO_MOEDA]=0.00
      ,A.[GERADO_AUTOMATICO_TIPO]
      ,A.[DATA_DIGITACAO]
      ,[RATEIO_FILIAL]='000003'
      ,[COD_CLIFOR]=D.CLIFOR
      ,A.[MOEDA]
      ,A.[CAMBIO_NA_DATA]
      ,A.[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]=0.00
      ,[VALOR_FINANCEIRO_PADRAO]=0.00
      ,A.[DATA_MOV]
      ,A.[USUARIO_MOV]
      ,A.[DOCUMENTO]
FROM LDR.DRVAREJO.DBO.[CTB_LANCAMENTO_ITEM] A WITH (NOLOCK) 
JOIN CTB_LANCAMENTO B WITH (NOLOCK) ON B.NUMERO_CORRELATIVO=A.LANCAMENTO
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CLIFOR=A.COD_CLIFOR
JOIN CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CGC_CPF=C.CGC_CPF 
WHERE RTRIM(CAST(B.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
) AND A.COD_CLIFOR 
IN('001143',
'001448',
'001462',
'018424',
'018858',
'021152',
'030371')
----


---- credito
INSERT INTO CTB_LANCAMENTO_ITEM
SELECT A.[EMPRESA]
      ,A.[LANCAMENTO]
      ,A.[ITEM]+10
      ,[CONTA_CONTABIL]='9990001'
      ,[LX_TIPO_LANCAMENTO]='LMC'
      ,[CREDITO]=0.00--=A.DEBITO
      ,[DEBITO]=0.00--=A.CREDITO
      ,[HISTORICO]='CREDITO REF'
      ,[CODIGO_HISTORICO]='LMC'
      ,[RATEIO_CENTRO_CUSTO]='31'
      ,A.[CONCILIADO]
      ,A.[PERMITE_ALTERACAO]
      ,A.[DISPARA_FORMULA]
      ,[DEBITO_MOEDA]=0.00--=A.CREDITO_MOEDA
      ,[CREDITO_MOEDA]=0.00--=A.DEBITO_MOEDA
      ,A.[GERADO_AUTOMATICO_TIPO]
      ,A.[DATA_DIGITACAO]
      ,A.[RATEIO_FILIAL]
      ,A.[COD_CLIFOR]
      ,A.[MOEDA]
      ,A.[CAMBIO_NA_DATA]
      ,A.[ID_CONTRAPARTIDA]
      ,[VALOR_FINANCEIRO]=0.00
      ,[VALOR_FINANCEIRO_PADRAO]=0.00
      ,A.[DATA_MOV]
      ,A.[USUARIO_MOV]
      ,A.[DOCUMENTO]
FROM CTB_LANCAMENTO_ITEM A
WHERE CONTA_CONTABIL='9990001' AND LANCAMENTO>284377


INSERT INTO CTB_LX_DOCUMENTO_TIPO
SELECT [LX_TIPO_DOCUMENTO]
      ,[TIPO_DOCUMENTO]
      ,[SERIE_NF]
      ,[NOME_RECIBO]
      ,[INATIVO]
      ,[TIPO_PGTO]
      ,[LX_TIPO_PADRAO]
      ,[VALIDA_VALOR]
      ,[VALOR_MINIMO]
      ,[VALOR_MAXIMO]
FROM LDR.DRVAREJO.DBO.CTB_LX_DOCUMENTO_TIPO A WITH (NOLOCK)
WHERE NOT EXISTS(SELECT * FROM CTB_LX_DOCUMENTO_TIPO WITH (NOLOCK) WHERE LX_TIPO_DOCUMENTO=A.LX_TIPO_DOCUMENTO)


--- CNPJ E NOME IGUAIS
INSERT INTO CTB_A_RECEBER_FATURA
SELECT A.[EMPRESA]
      ,H.[LANCAMENTO]
      ,A.[ITEM]
      ,A.[FATURA]
      ,A.[LX_TIPO_DOCUMENTO]
      ,A.[CODIGO_CONSUMIDOR]
      ,A.[EMISSAO]
      ,A.[DOCUMENTO]
      ,A.[FATURA_IMPRESSA]
      ,A.[POSSUI_SAIDA]
      ,A.[COMISSAO_GERENTE]
      ,A.[PORCENTAGEM_ACERTO]
      ,A.[COMISSAO]
      ,A.[CAMBIO_NA_DATA_EMISSAO]
      ,A.[JUROS_POR_ATRASO]
      ,A.[MULTA_POR_ATRASO]
      ,A.[SERIE]
      ,A.[NUMERO_PARCELAS]
      ,[COD_REPRESENTANTE]=F.CLIFOR
      ,[COD_REPRESENTANTE_GERENTE]=G.CLIFOR
      ,A.[MOEDA]
      ,[COD_CLIFOR]=E.COD_CLIFOR
      ,[COD_EMISSOR]='000003'
      ,A.[INDICA_PROTESTO]
FROM LDR.DRVAREJO.dbo.[CTB_A_RECEBER_FATURA] A WITH (NOLOCK)
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR B WITH (NOLOCK) ON B.CLIFOR=A.COD_CLIFOR
LEFT JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CLIFOR=A.COD_REPRESENTANTE
LEFT JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_REPRESENTANTE_GERENTE
JOIN CADASTRO_CLI_FOR E WITH (NOLOCK) ON E.CGC_CPF=B.CGC_CPF AND E.NOME_CLIFOR=B.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR F WITH (NOLOCK) ON F.CGC_CPF=C.CGC_CPF AND F.NOME_CLIFOR=C.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.CGC_CPF=D.CGC_CPF AND G.NOME_CLIFOR=D.NOME_CLIFOR
JOIN CTB_LANCAMENTO H WITH (NOLOCK) ON H.NUMERO_CORRELATIVO=A.LANCAMENTO
WHERE RTRIM(CAST(H.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001'
) --AND EXISTS(SELECT * FROM REPRESENTANTES WITH (NOLOCK) WHERE COD_REPRESENTANTE=F.CLIFOR)



---- EXCEÇÕES
INSERT INTO CTB_A_RECEBER_FATURA
SELECT A.[EMPRESA]
      ,H.[LANCAMENTO]
      ,A.[ITEM]
      ,A.[FATURA]
      ,A.[LX_TIPO_DOCUMENTO]
      ,A.[CODIGO_CONSUMIDOR]
      ,A.[EMISSAO]
      ,A.[DOCUMENTO]
      ,A.[FATURA_IMPRESSA]
      ,A.[POSSUI_SAIDA]
      ,A.[COMISSAO_GERENTE]
      ,A.[PORCENTAGEM_ACERTO]
      ,A.[COMISSAO]
      ,A.[CAMBIO_NA_DATA_EMISSAO]
      ,A.[JUROS_POR_ATRASO]
      ,A.[MULTA_POR_ATRASO]
      ,A.[SERIE]
      ,A.[NUMERO_PARCELAS]
      ,[COD_REPRESENTANTE]=NULL
      ,[COD_REPRESENTANTE_GERENTE]=NULL
      ,A.[MOEDA]
      ,[COD_CLIFOR]=C.COD_CLIFOR
      ,[COD_EMISSOR]='000003'
      ,A.[INDICA_PROTESTO]
FROM LDR.DRVAREJO.dbo.[CTB_A_RECEBER_FATURA] A WITH (NOLOCK)
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR B WITH (NOLOCK) ON B.CLIFOR=A.COD_CLIFOR
JOIN CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CGC_CPF=B.CGC_CPF
JOIN CTB_LANCAMENTO H WITH (NOLOCK) ON H.NUMERO_CORRELATIVO=A.LANCAMENTO
WHERE RTRIM(CAST(H.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
) AND A.COD_CLIFOR = '030130' AND C.NOME_CLIFOR='NANCY BALDERRAMA'


INSERT INTO CTB_A_RECEBER_FATURA
SELECT A.[EMPRESA]
      ,H.[LANCAMENTO]
      ,A.[ITEM]
      ,A.[FATURA]
      ,A.[LX_TIPO_DOCUMENTO]
      ,A.[CODIGO_CONSUMIDOR]
      ,A.[EMISSAO]
      ,A.[DOCUMENTO]
      ,A.[FATURA_IMPRESSA]
      ,A.[POSSUI_SAIDA]
      ,A.[COMISSAO_GERENTE]
      ,A.[PORCENTAGEM_ACERTO]
      ,A.[COMISSAO]
      ,A.[CAMBIO_NA_DATA_EMISSAO]
      ,A.[JUROS_POR_ATRASO]
      ,A.[MULTA_POR_ATRASO]
      ,A.[SERIE]
      ,A.[NUMERO_PARCELAS]
      ,[COD_REPRESENTANTE]=NULL
      ,[COD_REPRESENTANTE_GERENTE]=NULL
      ,A.[MOEDA]
      ,[COD_CLIFOR]=C.COD_CLIFOR
      ,[COD_EMISSOR]='000003'
      ,A.[INDICA_PROTESTO]
FROM LDR.DRVAREJO.dbo.[CTB_A_RECEBER_FATURA] A WITH (NOLOCK)
JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR B WITH (NOLOCK) ON B.CLIFOR=A.COD_CLIFOR
JOIN CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CGC_CPF=B.CGC_CPF
JOIN CTB_LANCAMENTO H WITH (NOLOCK) ON H.NUMERO_CORRELATIVO=A.LANCAMENTO
WHERE RTRIM(CAST(H.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
) AND A.COD_CLIFOR 
IN('001143',
'001448',
'001462',
'018424',
'018858',
'021152',
'030371')
----


--- CLIENTES COM MESMO NOME E CNPJ DIFERENTES
SELECT DISTINCT B.[CGC_CPF]CNPJ_CLIENTE
FROM LDR.DRVAREJO.dbo.[CTB_A_RECEBER_FATURA] A WITH (NOLOCK)
LEFT JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR B WITH (NOLOCK) ON B.CLIFOR=A.COD_CLIFOR
LEFT JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR C WITH (NOLOCK) ON C.CLIFOR=A.COD_REPRESENTANTE
LEFT JOIN LDR.DRVAREJO.dbo.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_REPRESENTANTE_GERENTE
LEFT JOIN CADASTRO_CLI_FOR E WITH (NOLOCK) ON E.CGC_CPF=B.CGC_CPF AND E.NOME_CLIFOR=B.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR F WITH (NOLOCK) ON F.CGC_CPF=C.CGC_CPF AND F.NOME_CLIFOR=C.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.CGC_CPF=D.CGC_CPF AND G.NOME_CLIFOR=D.NOME_CLIFOR
JOIN CTB_LANCAMENTO H WITH (NOLOCK) ON H.NUMERO_CORRELATIVO=A.LANCAMENTO
WHERE E.COD_CLIFOR IS NULL AND H.NUMERO_CORRELATIVO IN(
	SELECT DISTINCT A.LANCAMENTO
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
)

SELECT * FROM CTB_A_RECEBER_FATURA
WHERE FATURA='038850'


DELETE FROM CTB_A_RECEBER_FATURA
WHERE COD_EMISSOR='000003' AND LANCAMENTO>284377


INSERT INTO CTB_A_RECEBER_PARCELA
SELECT B.[LANCAMENTO] 
      ,A.[ITEM]
      ,A.[ID_PARCELA]
      ,[CONTA_PORTADOR]='1125001001'
      ,A.[VENCIMENTO]
      ,A.[NUMERO_BANCARIO]
      ,A.[VALOR_ORIGINAL_PADRAO]
      ,A.[VALOR_ORIGINAL]
      ,A.[DIAS_PRORROGADOS]
      ,A.[DESCONTO_VENC]
      ,A.[DATA_DESCONTO_VENC]
      ,A.[AGENCIA]
      ,A.[EMPRESA]
      ,A.[CAMBIO_FIXO_PGTO]
      ,A.[VENCIMENTO_REAL]
      ,A.[VALOR_A_RECEBER]
      ,A.[CAMBIO_NA_DATA_EMISSAO]
      ,A.[VALOR_MULTA_PAGA_PADRAO]
      ,A.[VALOR_JUROS_PAGO_PADRAO]
      ,A.[DESCONTO_EFETIVADO_PADRAO]
      ,A.[BANCO]
      ,A.[INDICA_PROTESTO]
      ,A.[DATA_PARA_TRANSFERENCIA]
      ,A.[VALOR_JUROS_DESCONTO]
      ,A.[EMPRESA_DESPESA_DESCONTO]
      ,A.[LANCAMENTO_DESPESA_DESCONTO]
      ,A.[ITEM_DESPESA_DESCONTO]
      ,A.[LOJA_CHAVE]
      ,A.[INDICA_ESTORNO_COMISSAO]
      ,A.[DATA_ENVIO_SCI]
      ,A.[DATA_BAIXA_SCI]
      ,A.[DATA_ENVIO_SERASA]
      ,A.[DATA_BAIXA_SERASA]
      ,A.[INDICA_NAO_ENVIO_BORDERO]
      ,A.[CONTRATO_GRUPO]
  FROM LDR.DRVAREJO.dbo.[CTB_A_RECEBER_PARCELA] A WITH (NOLOCK)
JOIN CTB_LANCAMENTO B WITH (NOLOCK) ON B.NUMERO_CORRELATIVO=A.LANCAMENTO  
--JOIN CTB_A_RECEBER_FATURA C WITH (NOLOCK) ON C.LANCAMENTO=B.LANCAMENTO AND C.ITEM=A.ITEM
WHERE RTRIM(CAST(B.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 AND A.COD_EMISSOR='000001'
) AND A.VALOR_A_RECEBER>0 


DELETE FROM CTB_A_RECEBER_PARCELA
WHERE LANCAMENTO>'284377' AND CONTA_PORTADOR='1125001001'

--- CADASTRO DE OCORRENCIA
INSERT INTO CTB_OCORRENCIA
SELECT [OCORRENCIA]
      ,[DESC_OCORRENCIA]
  FROM LDR.DRVAREJO.DBO.[CTB_OCORRENCIA] A
WHERE NOT EXISTS(SELECT * FROM CTB_OCORRENCIA WHERE OCORRENCIA=A.OCORRENCIA)

DELETE FROM CTB_ACOMPANHAMENTO
WHERE LANCAMENTO>'284377'

--- DADOS DO ACOMPANHAMENTO DAS PARCELAS
INSERT INTO CTB_ACOMPANHAMENTO
SELECT A.[EMPRESA] 
      ,C.[LANCAMENTO]
      ,C.[ITEM]
      ,A.[DATA_DIGITACAO]
      ,A.[OCORRENCIA]
      ,A.[SUB_ITEM]
      ,A.[ID_PARCELA]
      ,A.[DATA_ACOMPANHAMENTO]
      ,A.[OBS]
      ,A.[STATUS]
      ,[USUARIO]='SA'
  FROM LDR.DRVAREJO.DBO.[CTB_ACOMPANHAMENTO] A
JOIN CTB_LANCAMENTO B WITH (NOLOCK) ON B.NUMERO_CORRELATIVO=A.LANCAMENTO  
JOIN CTB_LANCAMENTO_ITEM C WITH (NOLOCK) ON C.LANCAMENTO=B.LANCAMENTO AND C.ITEM=A.ITEM
WHERE RTRIM(CAST(B.NUMERO_CORRELATIVO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4)) IN(
	SELECT DISTINCT RTRIM(CAST(A.LANCAMENTO AS CHAR(8)))+CAST(A.ITEM AS CHAR(4))
	FROM LDR.DRVAREJO.DBO.CTB_A_RECEBER_FATURA A WITH (NOLOCK)
	JOIN LDR.DRVAREJO.DBO.CTB_A_RECEBER_PARCELA B WITH (NOLOCK) ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
	JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C WITH (NOLOCK) ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
	JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D WITH (NOLOCK) ON D.CLIFOR=A.COD_CLIFOR
	WHERE B.VALOR_A_RECEBER>0 
)-- AND A.LANCAMENTO='399595'




exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXECUTE LX_CTB_GERA_VINCULO_COMISSAO @P1, @P2 ',N'@P1 int,@P2 int',1,404982
  
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXECUTE LX_CTB_MOVIMENTO_FINANCEIRO @P1, @P2 ',N'@P1 int,@P2 int',1,404982


--- lancamentos contas a pagar    
SELECT DISTINCT D.NOME_CLIFOR
FROM LDR.DRVAREJO.DBO.CTB_A_PAGAR_FATURA A
JOIN LDR.DRVAREJO.DBO.CTB_A_PAGAR_PARCELA B ON B.LANCAMENTO=A.LANCAMENTO AND B.ITEM=A.ITEM
JOIN LDR.DRVAREJO.DBO.CTB_CONTA_PLANO C ON C.CONTA_CONTABIL=B.CONTA_PORTADOR
JOIN LDR.DRVAREJO.DBO.CADASTRO_CLI_FOR D ON D.CLIFOR=A.COD_CLIFOR
WHERE B.VALOR_A_PAGAR>0 
AND NOT EXISTS(SELECT * FROM CADASTRO_CLI_FOR WHERE NOME_CLIFOR=D.NOME_CLIFOR AND CGC_CPF=D.CGC_CPF)


--- CADASTRO_CLI_FOR ( FORNECEDORES )
INSERT INTO CADASTRO_CLI_FOR
           ([NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,[CONTA_CONTABIL]
           ,[CLIFOR]
           ,[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,[INATIVO]
           ,[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,[COD_CLIFOR]
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,[CLI_FOR])
SELECT [NOME_CLIFOR]
           ,[CARTEIRA]
           ,[BANCO]
           ,A.[CONTA_CONTABIL]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
           ,A.[CGC_CPF]
           ,[RAZAO_SOCIAL]
           ,[PJ_PF]
           ,[RG_IE]
           ,[CEP]
           ,[ENDERECO]
           ,[BAIRRO]
           ,[CIDADE]
           ,[UF]
           ,[TELEFONE1]
           ,[PAIS]
           ,[DDI]
           ,[TELEFONE2]
           ,[FAX]
           ,[DDD1]
           ,[RAMAL1]
           ,[RAMAL2]
           ,[DDD2]
           ,[COBRANCA_ENDERECO]
           ,[COBRANCA_CIDADE]
           ,[COBRANCA_BAIRRO]
           ,[DDDFAX]
           ,[COBRANCA_UF]
           ,[COBRANCA_CEP]
           ,[COBRANCA_TELEFONE]
           ,[ENTREGA_ENDERECO]
           ,[ENTREGA_CIDADE]
           ,[ENTREGA_UF]
           ,[ENTREGA_BAIRRO]
           ,[ENTREGA_CEP]
           ,[ENTREGA_TELEFONE]
           ,[COBRANCA_DDD]
           ,[CONTATO]
           ,[COBRANCA_CGC]
           ,[CADASTRAMENTO]
           ,[COBRANCA_IE]
           ,[ANIVERSARIO]
           ,[INDICA_FORNECEDOR]
           ,[INDICA_CLIENTE]
           ,[IND_REPRESENTANTE]
           ,[INDICA_FILIAL]
           ,[ENTREGA_DDD]
           ,[ENTREGA_CGC]
           ,[ENTREGA_IE]
           ,[CC_AGENCIA]
           ,[CC_CONTA]
           ,[CC_NOME_AGENCIA]
           ,[REF_ANTERIOR]
           ,[ATUALIZACAO_EXPORTAR]
           ,[DATA_EXPORTACAO]
           ,[EMAIL]
           ,[STATUS_ENVIO]
           ,A.[INATIVO]
           ,A.[DATA_PARA_TRANSFERENCIA]
           ,[ENTREGA_PAIS]
           ,[COBRANCA_PAIS]
           ,[ENTREGA_DDI]
           ,[COBRANCA_DDI]
           ,[OBS_DE_FATURAMENTO]
           ,[ISENTO_IPI]
           ,[ISENTO_ICMS]
           ,A.[IRRF]
           ,[MESES_SEM_VENCIMENTO]
           ,[DATA_FIXA_PGTO]
           ,[ACEITA_AGRUPAR_FATURA]
           ,[PASSWEB]
           ,[VENCIMENTO_PASSWEB]
           ,[NUMERO_VIAS_FATURA]
           ,[REPORT_FATURA]
           ,[DIAS_ANTECIPACAO_PGTO]
           ,[POSSUI_RECARGO]
           ,[CODIGO_CHAVE]
           ,[TIPO_RELACAO_COMERCIAL]
           ,[ID_CLASIF_CLIFOR]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
           ,[ENTREGA_RAZAO_SOCIAL]
           ,[COBRANCA_RAZAO_SOCIAL]
           ,[INDICADOR_FISCAL_TERCEIRO]
           ,A.[CTB_CONTA_CONTABIL]
           ,[ACEITA_DIAS_FIXO]
           ,[ID_EXCECAO_GRUPO]
           ,[AGRUPAMENTO_ITENS]
           ,[CODIGO_CONTATO]
           ,[IM]
           ,[IM_ENTREGA]
           ,[IM_COBRANCA]
           --,[NOVO_CLIENTE]
           --,[EXPORTADO]
           --,[ID_CLIENTE_SERVIDOR]
           ,[CADASTRO_CLI_FOR]
           ,[INSCRICAO_SUFRAMA]
           ,[NUMERO]
           ,[COMPLEMENTO]
           ,[COBRANCA_NUMERO]
           ,[COBRANCA_COMPLEMENTO]
           ,[ENTREGA_NUMERO]
           ,[ENTREGA_COMPLEMENTO]
           ,[CNAE]
           ,[INCL_AUTO_GRP_ECON]
           ,[EMAIL_NFE]
           ,[COD_MUNICIPIO_IBGE]
           ,[COD_MUNICIPIO_IBGE_ENTREGA]
           ,[COD_MUNICIPIO_IBGE_COBRANCA]
           ,[CODIGO_SPC]
           ,[ENVIADO_SPC]
           ,[IEST]
           ,[LX_STATUS_REGISTRO]
           ,[CLINR_SEQUENCIA_ROTA]
           ,[CLICN_CODIGO_ROTA]
           ,CAST('400051' AS INT)+ ROW_NUMBER() OVER(ORDER BY A.CLIFOR) AS Row
FROM LDR.DRVAREJO.DBO.[CADASTRO_CLI_FOR] A
WHERE A.NOME_CLIFOR IN(
)




exec sp_executesql N'INSERT INTO CTB_LANCAMENTO (EMPRESA,LANCAMENTO,LOTE_LANCAMENTO,COD_FILIAL,DATA_LANCAMENTO,DATA_DIGITACAO,LANCAMENTO_PADRAO,TIPO_MOVIMENTO) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 )',N'@P1 int,@P2 int,@P3 int,@P4 varchar(6),@P5 datetime,@P6 datetime,@P7 int,@P8 tinyint',1,404983,NULL,'000001','2015-12-28 00:00:00','2015-12-28 00:00:00',NULL,1

exec sp_executesql N'INSERT INTO CTB_LANCAMENTO_ITEM (ITEM,EMPRESA,LANCAMENTO,COD_CLIFOR,CONTA_CONTABIL,CREDITO,DEBITO,HISTORICO,CODIGO_HISTORICO,RATEIO_CENTRO_CUSTO,MOEDA,DATA_DIGITACAO,LX_TIPO_LANCAMENTO,PERMITE_ALTERACAO,DEBITO_MOEDA,CREDITO_MOEDA,CAMBIO_NA_DATA,RATEIO_FILIAL,ID_CONTRAPARTIDA) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 )',N'@P1 smallint,@P2 int,@P3 int,@P4 varchar(6),@P5 varchar(20),@P6 numeric(14,2),@P7 numeric(14,2),@P8 varchar(250),@P9 varchar(4),@P10 varchar(15),@P11 varchar(6),@P12 datetime,@P13 varchar(3),@P14 bit,@P15 numeric(14,2),@P16 numeric(14,2),@P17 numeric(11,6),@P18 varchar(15),@P19 tinyint',1,1,404983,'602592','21201               ',1000.00,0,'SUA FATURA NR. [NTP] [NDT]                                                                                                                                                                                                                                ','ITP ','8001           ','R$    ','2015-12-28 00:00:00','ITP',1,0,1000.00,1.000000,'000001         ',1

exec sp_executesql N'INSERT INTO CTB_LANCAMENTO_ITEM (ITEM,EMPRESA,LANCAMENTO,CONTA_CONTABIL,CREDITO,DEBITO,HISTORICO,CODIGO_HISTORICO,RATEIO_CENTRO_CUSTO,MOEDA,DATA_DIGITACAO,LX_TIPO_LANCAMENTO,PERMITE_ALTERACAO,DEBITO_MOEDA,CREDITO_MOEDA,CAMBIO_NA_DATA,RATEIO_FILIAL,ID_CONTRAPARTIDA) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 smallint,@P2 int,@P3 int,@P4 varchar(20),@P5 numeric(14,2),@P6 numeric(14,2),@P7 varchar(250),@P8 varchar(4),@P9 varchar(15),@P10 varchar(6),@P11 datetime,@P12 varchar(3),@P13 bit,@P14 numeric(14,2),@P15 numeric(14,2),@P16 numeric(11,6),@P17 varchar(15),@P18 tinyint',2,1,404983,'1110101             ',0,1000.00,'DEBITO REF.:                                                                                                                                                                                                                                              ','LMD ','8806           ','R$    ','2015-12-28 00:00:00','LMD',1,1000.00,0,1.000000,'000001         ',1

exec sp_executesql N'INSERT INTO CTB_A_PAGAR_FATURA (COD_CLIFOR_SACADO,LANCAMENTO,EMPRESA,ITEM,COD_CLIFOR,ESPECIE_SERIE,LX_TIPO_DOCUMENTO,COD_FILIAL,FATURA,FATURA_SERIE,MOEDA,EMISSAO,DATA_ENTRADA,TAXA_MULTA,TAXA_JUROS,CAMBIO_NA_DATA_EMISSAO,NUMERO_PARCELAS,USUARIO) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(6),@P2 int,@P3 int,@P4 smallint,@P5 varchar(6),@P6 int,@P7 int,@P8 varchar(6),@P9 varchar(20),@P10 varchar(6),@P11 varchar(6),@P12 datetime,@P13 datetime,@P14 numeric(13,10),@P15 numeric(13,10),@P16 numeric(11,6),@P17 tinyint,@P18 varchar(25)','602592',404983,1,1,'602592',1,1,'000001','999999         ','9   ','R$    ','2015-12-28 00:00:00','2015-12-28 00:00:00',0,0,1.000000,2,'SA                       '

exec sp_executesql N'INSERT INTO CTB_A_PAGAR_PARCELA (EMPRESA,ITEM,LANCAMENTO,ID_PARCELA,VALOR_ORIGINAL,VALOR_ORIGINAL_PADRAO,VENCIMENTO,PAGAMENTO_APROVADO,CONTA_PORTADOR,LX_TIPO_DOCUMENTO_PARCELA) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 )',N'@P1 int,@P2 smallint,@P3 int,@P4 varchar(2),@P5 numeric(14,2),@P6 numeric(14,2),@P7 datetime,@P8 varchar(1),@P9 varchar(20),@P10 int',1,1,404983,'A ',500.00,500.00,'2016-01-27 00:00:00','N','21201               ',NULL

exec sp_executesql N'INSERT INTO CTB_A_PAGAR_PARCELA (EMPRESA,ITEM,LANCAMENTO,ID_PARCELA,VALOR_ORIGINAL,VALOR_ORIGINAL_PADRAO,VENCIMENTO,PAGAMENTO_APROVADO,CONTA_PORTADOR,LX_TIPO_DOCUMENTO_PARCELA) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 )',N'@P1 int,@P2 smallint,@P3 int,@P4 varchar(2),@P5 numeric(14,2),@P6 numeric(14,2),@P7 datetime,@P8 varchar(1),@P9 varchar(20),@P10 int',1,1,404983,'B ',500.00,500.00,'2016-02-26 00:00:00','N','21201               ',NULL

exec sp_executesql N'INSERT INTO CTB_ACOMPANHAMENTO (LANCAMENTO,EMPRESA,ITEM,DATA_DIGITACAO,OCORRENCIA,ID_PARCELA,DATA_ACOMPANHAMENTO,OBS,STATUS,USUARIO) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 )',N'@P1 int,@P2 int,@P3 smallint,@P4 datetime,@P5 smallint,@P6 varchar(2),@P7 datetime,@P8 varchar(250),@P9 varchar(2),@P10 varchar(25)',404982,1,1,'2015-12-28 00:00:00',1,'A ','2015-12-28 00:00:00','inclusão de titulos                                                                                                                                                                                                                                       ','E ','SA                       '

exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXECUTE LX_CTB_GERA_VINCULO_COMISSAO @P1, @P2 ',N'@P1 int,@P2 int',1,404983
  
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXECUTE LX_CTB_MOVIMENTO_FINANCEIRO @P1, @P2 ',N'@P1 int,@P2 int',1,404983
  




---- TRANSPORTE DE OPERACOES EXTRAS DA TABELA DE OPERAÇÕES
INSERT INTO PRODUTOS_OPE_EXTRA
SELECT 'V'+RTRIM(A.[PRODUTO])
      ,[OPERACAO_EXTRA]
      ,[SEQUENCIA]
      ,[CUSTO_OPERACAO]
      ,[TEMPO_HORAS]
      ,[CUSTO_TOTAL]
      ,[QTDADE]
      ,[COD_OPERACAO_EXTRA]
FROM LDR.DRVAREJO.[dbo].[PRODUTOS_OPE_EXTRA] A
JOIN PRODUTOS B ON B.PRODUTO='V'+RTRIM(A.PRODUTO)
WHERE NOT EXISTS(SELECT * FROM PRODUTOS_OPE_EXTRA WHERE PRODUTO='V'+RTRIM(A.PRODUTO))

    