SELECT SUBSTRING(PRODUTOS_BARRA.PRODUTO,1,6)+SUBSTRING(PRODUTOS.DESC_PRODUTO,1,27)+SUBSTRING(PRODUTOS_BARRA.GRADE,1,3)+SUBSTRING(CODIGO_BARRA,1,13) 
FROM PRODUTOS_BARRA
JOIN PRODUTOS ON PRODUTOS.PRODUTO=PRODUTOS_BARRA.PRODUTO
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%'




SELECT PRODUTOS_BARRA.PRODUTO,PRODUTOS.DESC_PRODUTO,PRODUTO_CORES.COR_PRODUTO,PRODUTOS_BARRA.GRADE,CODIGO_BARRA 
FROM PRODUTOS_BARRA
JOIN PRODUTOS ON PRODUTOS.PRODUTO=PRODUTOS_BARRA.PRODUTO
JOIN PRODUTO_CORES ON PRODUTO_CORES.PRODUTO = PRODUTOS_BARRA.PRODUTO AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND PRODUTOS_BARRA.CODIGO_BARRA_PADRAO=1

