--- QTDE DE OP MENSAL 2014
SELECT ANO=YEAR(EMISSAO),MES=MONTH(EMISSAO),QTDE=COUNT(ORDEM_PRODUCAO) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2014
GROUP BY YEAR(EMISSAO),MONTH(EMISSAO)


--- PRAZO MEDIO DE PRODUÇÃO
SELECT AVG(DATEDIFF(DAY,EMISSAO,ENCERRAMENTO)) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2014 AND ENCERRAMENTO IS NOT NULL

SELECT ORDEM_PRODUCAO,AVG(DATEDIFF(DAY,EMISSAO,ENCERRAMENTO)) FROM PRODUCAO_ORDEM
WHERE YEAR(EMISSAO)=2014 AND ENCERRAMENTO IS NOT NULL
GROUP BY ORDEM_PRODUCAO


--- PRAZO MEDIO DO RETORNO DAS OFICINAS
SELECT AVG(DATEDIFF(DAY,RETORNO.INICIO_REAL,RETORNO.ENCERRAMENTO)) FROM (
SELECT DISTINCT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS1.FASE_PRODUCAO1,PRODUCAO_TAREFAS1.INICIO_REAL,PRODUCAO_TAREFAS2.FASE_PRODUCAO2,PRODUCAO_TAREFAS2.ENCERRAMENTO FROM PRODUCAO_TAREFAS
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO1=FASE_PRODUCAO,INICIO_REAL FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='006' AND YEAR(INICIO_REAL)=2014) AS PRODUCAO_TAREFAS1 ON PRODUCAO_TAREFAS1.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO2=FASE_PRODUCAO,ENCERRAMENTO FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='009' AND YEAR(ENCERRAMENTO)=2014) AS PRODUCAO_TAREFAS2 ON PRODUCAO_TAREFAS2.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2014 ) AS RETORNO


SELECT DISTINCT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS1.FASE_PRODUCAO,PRODUCAO_TAREFAS1.INICIO_REAL,PRODUCAO_TAREFAS2.FASE_PRODUCAO,PRODUCAO_TAREFAS2.ENCERRAMENTO FROM PRODUCAO_TAREFAS
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,INICIO_REAL FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='006' AND YEAR(INICIO_REAL)=2014) AS PRODUCAO_TAREFAS1 ON PRODUCAO_TAREFAS1.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,ENCERRAMENTO FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='009' AND YEAR(ENCERRAMENTO)=2014) AS PRODUCAO_TAREFAS2 ON PRODUCAO_TAREFAS2.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2014



