SELECT GRUPO,SUBGRUPO,MATERIAL,DESC_MATERIAL,COR_MATERIAL,QTDE_ESTOQUE=ISNULL(QTDE_ESTOQUE,0),QTDE_DISPONIVEL=ISNULL(QTDE_DISPONIVEL,0),RESERVA=SUM(RESERVA)
FROM ( 
SELECT A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,C.GRUPO,C.SUBGRUPO,QTDE_ESTOQUE=ISNULL(D.QTDE_ESTOQUE,0),   
CASE WHEN B.QTDE_DISPONIVEL IS NULL THEN ISNULL(D.QTDE_ESTOQUE,0) ELSE ISNULL(B.QTDE_DISPONIVEL,0) END AS QTDE_DISPONIVEL, RESERVA=SUM(A.RESERVA) FROM PRODUCAO_RESERVA A  
LEFT JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL   
LEFT JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL   
LEFT JOIN ESTOQUE_MATERIAIS D WITH (NOLOCK) ON D.MATERIAL=A.MATERIAL AND D.COR_MATERIAL=A.COR_MATERIAL AND D.FILIAL='DR VAREJO'  
WHERE ORDEM_PRODUCAO IN ('175876')   
GROUP BY A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,C.GRUPO,C.SUBGRUPO,D.QTDE_ESTOQUE,B.QTDE_DISPONIVEL 
) AS FINAL  
WHERE MATERIAL NOT IN (
SELECT DISTINCT A.MATERIAL FROM MATERIAIS A WITH (NOLOCK) 
JOIN MATERIAIS_CORES B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL  
WHERE GETDATE() not BETWEEN B.INICIO_VENDAS AND B.FIM_VENDAS
) AND RESERVA>0 AND RESERVA>QTDE_DISPONIVEL 
GROUP BY GRUPO,SUBGRUPO,MATERIAL,DESC_MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,QTDE_DISPONIVEL 
ORDER BY MATERIAL 

---- LIBERAR MOVIMENTAÇÃO DE OPS SEM SALDOS EM ESTOQUE DE MP
UPDATE MATERIAIS_CORES
SET INICIO_VENDAS='20160101'
where MATERIAL='20.00.0066' AND COR_MATERIAL='003'



SELECT * FROM MATERIAIS_CORES
where MATERIAL='20.00.0066' AND COR_MATERIAL='003'

