select RAZAO_SOCIAL,EMAIL from CADASTRO_CLI_FOR
JOIN CLIENTES_ATACADO ON CLIENTES_ATACADO.CLIENTE_ATACADO=CADASTRO_CLI_FOR.NOME_CLIFOR
where CADASTRO_CLI_FOR.INATIVO=0 AND CLIENTES_ATACADO.INATIVO=0 AND CADASTRO_CLI_FOR.EMAIL NOT LIKE '%@LDR.IND.BR'



if not exists (select * from sys.columns where object_id = object_id ('LCF_APURACAO_VENCIMENTOS') and name = 'BAIXA')
	ALTER TABLE dbo.LCF_APURACAO_VENCIMENTOS ADD BAIXA SMALLDATETIME NULL;