select B.NF_SAIDA,B.SERIE_NF,A.* from PRODUCAO_ORDEM_SERVICO_HORARIA A
JOIN PRODUCAO_ORDEM_SERVICO B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO
where A.ORDEM_SERVICO='519847'

select B.NF_SAIDA,B.SERIE_NF,A.* from PRODUCAO_ORDEM_SERVICO_HORARIA A
JOIN PRODUCAO_ORDEM_SERVICO B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO
where A.ORDEM_SERVICO='519908'
