SELECT LINHA,* FROM PRODUTOS_BARRA PB
JOIN PRODUTOS P ON P.PRODUTO=PB.PRODUTO
JOIN PRODUTO_CORES PC ON PC.PRODUTO = PB.PRODUTO AND PC.COR_PRODUTO = PB.COR_PRODUTO
WHERE P.COD_CATEGORIA='01' AND P.COD_SUBCATEGORIA='01' AND PB.CODIGO_BARRA_PADRAO=1 AND PC.DESC_COR_PRODUTO NOT LIKE '%-FL'
ORDER BY P.LINHA