SELECT TOP 10 * FROM VENDAS

SELECT top 10 * FROM VENDAS_PRODUTO

SELECT top 10 * FROM VENDAS_PROD_EMBALADO

SELECT top 10 * FROM FATURAMENTO

SELECT top 10 * FROM FATURAMENTO_PROD

SELECT top 10 * FROM FATURAMENTO_CAIXAS


