select A.REPRESENTANTE_PRINCIPAL, * from CLIENTE_REPRE A
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=A.CLIENTE_ATACADO
WHERE B.REGIAO='RV-07 ZN-01 ST-09' AND A.REPRESENTANTE='GUSTAVO PRETO DE SOUZA'


UPDATE A
SET REPRESENTANTE_PRINCIPAL=1
from CLIENTE_REPRE A
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=A.CLIENTE_ATACADO
WHERE B.REGIAO='RV-07 ZN-01 ST-09' AND A.REPRESENTANTE='GUSTAVO PRETO DE SOUZA'
