SELECT ESTOQUE_MATERIAIS.QTDE_ESTOQUE,PRODUCAO_RESERVA.* FROM PRODUCAO_RESERVA
JOIN ESTOQUE_MATERIAIS ON ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL
JOIN PRODUCAO_ORDEM ON PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_RESERVA.ORDEM_PRODUCAO
WHERE RESERVA>0 AND ESTOQUE_MATERIAIS.QTDE_ESTOQUE<=0 AND ESTOQUE_MATERIAIS.FILIAL='DR VAREJO'


select sum(RESERVA) from producao_reserva
where MATERIAL='40.04.0017' and COR_MATERIAL='cru'



