SELECT 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA,  
TEMPO_PADRAO_TOTAL,
QTDE_S,
META=CONVERT(NUMERIC(6,0),((QTDE_OPERADOR*MINUTOS_DISPONIVEIS)/(TEMPO_PADRAO_TOTAL/QTDE_S)))
FROM (
SELECT 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA,  
TEMPO_PADRAO_TOTAL=SUM(TEMPO_CRONOMETRADO*QTDE_S),    
QTDE_S=SUM(QTDE_S)
FROM (
SELECT 
DIA = CASE DATEPART(DW,COSTURA.DATA)   
   WHEN 1 THEN 'DOMINGO'  
   WHEN 2 THEN 'SEGUNDA'  
   WHEN 3 THEN 'TERÇA'  
   WHEN 4 THEN 'QUARTA'  
   WHEN 5 THEN 'QUINTA'  
   WHEN 6 THEN 'SEXTA'  
   ELSE 'SÁBADO' 
END,  
COSTURA.PRIORIDADE,((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(RECEBIMENTO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_RECURSO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S 
FROM (

SELECT PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO with (nolock), dbo.PRODUTOS PRODUTOS with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','006.1','007')) AS RECEBIMENTO

LEFT JOIN (
 
SELECT GETDATE() AS DATA,PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.QTDE_S>0 AND DATEPART(WEEK,DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  DATEPART (year, DATA) = DATEPART(YEAR,GETDATE()) AND DATEPART(DAY,DATA) = DATEPART(DAY,GETDATE()) AND RECEBIMENTO.RECURSO_PRODUTIVO LIKE 'G%'  
) AS META
WHERE desc_recurso='GRUPO ATHENA 01'
GROUP BY 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA
) AS FINAL

GROUP BY 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA,  
TEMPO_PADRAO_TOTAL,
QTDE_S


--- DESENVOLVIMENTO DA META
SELECT 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA,
META=CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/AVG(TEMPO_CRONOMETRADO))
FROM W_SAW_META_DIA
WHERE desc_recurso like 'GRUPO AFRODITE CANINDE 01'
GROUP BY
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DIA  

--- TODAS AS OPS NO GRUPO
SELECT 
*
FROM W_SAW_META_DIA
WHERE desc_recurso like 'GRUPO AFRODITE CANINDE 01'



CREATE VIEW W_SAW_META_DIA AS
SELECT 
DIA = CASE DATEPART(DW,COSTURA.DATA)   
   WHEN 1 THEN 'DOMINGO'  
   WHEN 2 THEN 'SEGUNDA'  
   WHEN 3 THEN 'TERÇA'  
   WHEN 4 THEN 'QUARTA'  
   WHEN 5 THEN 'QUINTA'  
   WHEN 6 THEN 'SEXTA'  
   ELSE 'SÁBADO' 
END,  
COSTURA.PRIORIDADE,((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(RECEBIMENTO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_RECURSO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S 
FROM (

SELECT PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO with (nolock), dbo.PRODUTOS PRODUTOS with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','006.1','007')) AS RECEBIMENTO

LEFT JOIN (
 
SELECT GETDATE() AS DATA,PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.QTDE_S>0 AND DATEPART(WEEK,DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  DATEPART (year, DATA) = DATEPART(YEAR,GETDATE()) AND DATEPART(DAY,DATA) = DATEPART(DAY,GETDATE()) AND RECEBIMENTO.RECURSO_PRODUTIVO LIKE 'G%'  


--- META DIA FASE COSTURA
SELECT PRIORIDADE,META_DIA=CONVERT(NUMERIC(6,0),CAPACIDADE) FROM (

SELECT COSTURA.PRIORIDADE,((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(RECEBIMENTO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_RECURSO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S 
FROM (

SELECT PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO with (nolock), dbo.PRODUTOS PRODUTOS with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','006.1','007')) AS RECEBIMENTO

LEFT JOIN (
 
SELECT PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.RECURSO_PRODUTIVO ='GAT01' AND 
COSTURA.RECURSO_PRODUTIVO='GAT01' AND RECEBIMENTO.QTDE_S>0

) AS METAS
ORDER BY PRIORIDADE


--- GRAFICO 1
ALTER VIEW W_SAW_META_SEMANA_MENSAGEM AS
SELECT
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA,
DIA = CASE DATEPART(DW,DATA) 
	  WHEN 1 THEN 'DOMINGO'
	  WHEN 2 THEN 'SEGUNDA'
	  WHEN 3 THEN 'TERÇA'
	  WHEN 4 THEN 'QUARTA'
	  WHEN 5 THEN 'QUINTA'
	  WHEN 6 THEN 'SEXTA'
	  ELSE 'SÁBADO' END,
TEMPO_PADRAO_TOTAL,
QTDE,
EFICIENCIA,
CONVERT(NUMERIC(6,0),((QTDE_OPERADOR*MINUTOS_DISPONIVEIS)/(TEMPO_PADRAO_TOTAL/QTDE))) AS META, 
MENSAGEM=CASE WHEN QTDE>CONVERT(NUMERIC(6,0),((QTDE_OPERADOR*MINUTOS_DISPONIVEIS)/(TEMPO_PADRAO_TOTAL/QTDE))) THEN 'META DO DIA BATIDA, PARABENS!!!' ELSE 'VAMOS LÁ PESSOAL, PRECISAMOS BATER A META DO DIA...' END
FROM (
SELECT 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA,
TEMPO_PADRAO_TOTAL=SUM(TEMPO_PADRAO*QTDE),  
QTDE=SUM(QTDE),
EFICIENCIA=CONVERT(NUMERIC(6,0),ROUND((SUM(TEMPO_PADRAO*QTDE)/(QTDE_OPERADOR*MINUTOS_DISPONIVEIS)*100),0))   
FROM (
	SELECT DESC_SETOR_PRODUCAO,
	DESC_RECURSO,
	RECURSO_PRODUTIVO,
	PRODUTO,
	DATA,
	TEMPO_PADRAO=  
	(  
	SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS with (nolock)  
	WHERE TABELA_OPERACOES = C.PRODUTO AND TEMPO_CRONOMETRADO>0   
	),   
	QTDE=SUM(QTDE_A),  
	QTDE_OPERADOR=(  
		select distinct qtde_operador from ldr_metas_oficina_grupo_nova with (nolock)  
		where desc_recurso=C.DESC_RECURSO and desc_SETOR_producao=C.DESC_SETOR_PRODUCAO   
		and data_producao= C.DATA   
	),  
	MINUTOS_DISPONIVEIS=(  
		select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova with (nolock)   
		where desc_recurso=C.DESC_RECURSO and desc_setor_producao=C.DESC_setor_PRODUCAO   
		and data_producao= C.DATA   
	)  
	FROM W_PRODUCAO_ORDEM_HIST_OS C with (nolock)
	WHERE DATEPART(WEEK,C.DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  DATEPART (year, C.DATA) = DATEPART(YEAR,GETDATE())
	AND C.INDICADOR_TIPO_MOV=1 
	AND C.RECURSO_PRODUTIVO LIKE 'G%'
	GROUP BY DESC_SETOR_PRODUCAO,DESC_RECURSO,RECURSO_PRODUTIVO,PRODUTO,DATA
) AS OFICINA_GRUPO
GROUP BY 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA
) META_E_PRODUCAO_DIARIA

ORDER BY DATEPART(DW,DATA)

SELECT * FROM W_SAW_META_SEMANA_MENSAGEM
WHERE desc_recurso='GRUPO AFRODITE CANINDE 01'
ORDER BY DATEPART(DW,DATA)


SELECT * FROM W_SAW_META_SEMANA
WHERE desc_recurso='GRUPO AFRODITE CANINDE 01'
ORDER BY DATEPART(DW,DATA)



SELECT 
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS, 
DATA, 
DIA,
META=CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/AVG(TEMPO_CRONOMETRADO))
FROM W_SAW_META_SEMANA
WHERE desc_recurso like 'GRUPO AFRODITE CANINDE 01'
GROUP BY
DESC_SETOR_PRODUCAO,  
DESC_RECURSO,  
RECURSO_PRODUTIVO,  
QTDE_OPERADOR,  
MINUTOS_DISPONIVEIS,  
DATA,
DIA
ORDER BY DATEPART(DW,DATA)



ALTER VIEW W_SAW_META_SEMANA AS
SELECT 
DATA,
DIA = CASE DATEPART(DW,COSTURA.DATA)   
   WHEN 1 THEN 'DOMINGO'  
   WHEN 2 THEN 'SEGUNDA'  
   WHEN 3 THEN 'TERÇA'  
   WHEN 4 THEN 'QUARTA'  
   WHEN 5 THEN 'QUINTA'  
   WHEN 6 THEN 'SEXTA'  
   ELSE 'SÁBADO' 
END,  
COSTURA.PRIORIDADE,((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(RECEBIMENTO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_RECURSO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S
FROM (

SELECT PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO with (nolock), dbo.PRODUTOS PRODUTOS with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','006.1','007')) AS RECEBIMENTO

LEFT JOIN (
 
SELECT GETDATE() AS DATA,PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.QTDE_S>0 AND 
DATEPART(WEEK,DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  
DATEPART (year, DATA) = DATEPART(YEAR,GETDATE()) AND 
RECEBIMENTO.RECURSO_PRODUTIVO LIKE 'G%'  


SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA


--- GRAFICO 2
SELECT TOP 1 PRIORIDADE,META_DIA=CONVERT(NUMERIC(6,0),CAPACIDADE) FROM (

SELECT COSTURA.PRIORIDADE,((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(RECEBIMENTO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S 
FROM (

SELECT PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO with (nolock), dbo.PRODUTOS PRODUTOS with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','005','006','007')) AS RECEBIMENTO

LEFT JOIN (
 
SELECT PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.RECURSO_PRODUTIVO ='GAT01' AND 
COSTURA.RECURSO_PRODUTIVO='GAT01' AND RECEBIMENTO.QTDE_S>0

) AS METAS
ORDER BY PRIORIDADE


--- MENSAGEM DO DIA
ALTER VIEW W_SAW_META_DIA_MENSAGEM AS 
SELECT
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DIA = CASE DATEPART(DW,DATA) 
	  WHEN 1 THEN 'DOMINGO'
	  WHEN 2 THEN 'SEGUNDA'
	  WHEN 3 THEN 'TERÇA'
	  WHEN 4 THEN 'QUARTA'
	  WHEN 5 THEN 'QUINTA'
	  WHEN 6 THEN 'SEXTA'
	  ELSE 'SÁBADO' END,
TEMPO_PADRAO_TOTAL,
QTDE,
EFICIENCIA,
CONVERT(NUMERIC(6,0),((QTDE_OPERADOR*MINUTOS_DISPONIVEIS)/(TEMPO_PADRAO_TOTAL/QTDE))) AS META, 
MENSAGEM=CASE WHEN QTDE>CONVERT(NUMERIC(6,0),((QTDE_OPERADOR*MINUTOS_DISPONIVEIS)/(TEMPO_PADRAO_TOTAL/QTDE))) THEN 'META DO DIA BATIDA, PARABENS!!!' ELSE 'VAMOS LÁ PESSOAL, PRECISAMOS BATER A META DO DIA...' END
FROM (
SELECT 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA,
TEMPO_PADRAO_TOTAL=SUM(TEMPO_PADRAO*QTDE),  
QTDE=SUM(QTDE),
EFICIENCIA=ROUND((SUM(TEMPO_PADRAO*QTDE)/(QTDE_OPERADOR*MINUTOS_DISPONIVEIS)*100),0)   
FROM (
	SELECT DESC_SETOR_PRODUCAO,
	DESC_RECURSO,
	RECURSO_PRODUTIVO,
	PRODUTO,
	DATA,
	TEMPO_PADRAO=  
	(  
	SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS with (nolock)  
	WHERE TABELA_OPERACOES = C.PRODUTO AND TEMPO_CRONOMETRADO>0   
	),   
	QTDE=SUM(QTDE_A),  
	QTDE_OPERADOR=(  
		select distinct qtde_operador from ldr_metas_oficina_grupo_nova with (nolock)  
		where desc_recurso=C.DESC_RECURSO and desc_SETOR_producao=C.DESC_SETOR_PRODUCAO   
		and data_producao= C.DATA   
	),  
	MINUTOS_DISPONIVEIS=(  
		select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova with (nolock)   
		where desc_recurso=C.DESC_RECURSO and desc_setor_producao=C.DESC_setor_PRODUCAO   
		and data_producao= C.DATA   
	)  
	FROM W_PRODUCAO_ORDEM_HIST_OS C with (nolock)
	WHERE DATEPART(WEEK,C.DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  DATEPART (year, C.DATA) = DATEPART(YEAR,GETDATE()) AND DATEPART(DAY,C.DATA) = DATEPART(DAY,GETDATE()) AND C.INDICADOR_TIPO_MOV=1 AND C.RECURSO_PRODUTIVO LIKE 'G%'
	GROUP BY DESC_SETOR_PRODUCAO,DESC_RECURSO,RECURSO_PRODUTIVO,PRODUTO,DATA
) AS OFICINA_GRUPO
GROUP BY 
DESC_SETOR_PRODUCAO,
DESC_RECURSO,
RECURSO_PRODUTIVO,
QTDE_OPERADOR,
MINUTOS_DISPONIVEIS,
DATA
) META_E_PRODUCAO_DIARIA
--ORDER BY DATEPART(DW,DATA)

SELECT *
FROM W_SAW_META_DIA
WHERE desc_recurso='GRUPO AFRODITE CANINDE 01'


SELECT *
FROM W_SAW_META_DIA_MENSAGEM
WHERE desc_recurso='GRUPO AFRODITE CANINDE 01'


SELECT *
FROM W_SAW_META_SEMANA_MENSAGEM
WHERE recurso_produtivo='GCA01'
ORDER BY DATEPART(DW,DATA)

-----------------------------------------------------------------------------------

--- META DIA PARA CADA GRUPO


UPDATE A
SET A.META_DIA=META.META_DIA
FROM LDR_METAS_OFICINA_GRUPO_NOVA A
JOIN (
	SELECT DESC_SETOR_PRODUCAO,DESC_RECURSO,	
	META_DIA=ISNULL(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))),0)  
	FROM W_SAW_META_DIA
	--WHERE RECURSO_PRODUTIVO = 'GCA16'
	GROUP BY
	DESC_SETOR_PRODUCAO,  
	DESC_RECURSO,  
	RECURSO_PRODUTIVO,  
	QTDE_OPERADOR,  
	MINUTOS_DISPONIVEIS,  
	DIA  
) META ON META.DESC_SETOR_PRODUCAO=A.DESC_SETOR_PRODUCAO AND META.DESC_RECURSO=A.DESC_RECURSO
WHERE CONVERT(CHAR(10),A.DATA_PRODUCAO,103)=CONVERT(CHAR(10),GETDATE(),103) --AND A.DESC_RECURSO='GRUPO AFRODITE CANINDE 16'



SELECT META.META_DIA, A.* 
FROM LDR_METAS_OFICINA_GRUPO_NOVA A
JOIN (
	SELECT DESC_SETOR_PRODUCAO,DESC_RECURSO,	
	META_DIA=ISNULL(CONVERT(NUMERIC(6,0),(MINUTOS_DISPONIVEIS*QTDE_OPERADOR)/(SUM(TEMPO_CRONOMETRADO*QTDE_S)/SUM(QTDE_S))),0)  
	FROM W_SAW_META_DIA
	WHERE RECURSO_PRODUTIVO = 'GCA16'
	GROUP BY
	DESC_SETOR_PRODUCAO,  
	DESC_RECURSO,  
	RECURSO_PRODUTIVO,  
	QTDE_OPERADOR,  
	MINUTOS_DISPONIVEIS,  
	DIA  
) META ON META.DESC_SETOR_PRODUCAO=A.DESC_SETOR_PRODUCAO AND META.DESC_RECURSO=A.DESC_RECURSO
WHERE CONVERT(CHAR(10),A.DATA_PRODUCAO,103)=CONVERT(CHAR(10),GETDATE(),103) AND A.DESC_RECURSO='GRUPO AFRODITE CANINDE 16'