SELECT POS.FASE_PRODUCAO,(POT.QTDE_O/30), POT.* 
FROM PRODUCAO_OS_TAREFAS POT
INNER JOIN PRODUCAO_ORDEM_SERVICO POS 
ON POS.ORDEM_SERVICO=POT.ORDEM_SERVICO
WHERE POS.FASE_PRODUCAO='009' and 
pos.INDICADOR_TIPO_MOV=1 and
pos.DATA between '20131201' AND '20140115'



