select * from PRODUCAO_ORDEM_HISTORICO
join PRODUCAO_TAREFAS on PRODUCAO_TAREFAS.ORDEM_PRODUCAO=PRODUCAO_ORDEM_HISTORICO.ORDEM_PRODUCAO
where PRODUCAO_TAREFAS.FASE_PRODUCAO='010'


select * from PRODUCAO_TAREFAS
WHERE FASE_PRODUCAO='010'


SELECT PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO, PRODUCAO_ORDEM_SERVICO.RECURSO_PRODUTIVO, PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO, PRODUCAO_ORDEM_SERVICO.SETOR_PRODUCAO, PRODUCAO_ORDEM_SERVICO.DATA, PRODUCAO_ORDEM_SERVICO.CONFERIDO_POR, PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV, PRODUCAO_OS_TAREFAS.TAREFA, PRODUCAO_OS_TAREFAS.ORDEM_SERVICO, PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_OS_TAREFAS.PRODUTO, PRODUCAO_OS_TAREFAS.COR_PRODUTO, PRODUCAO_OS_TAREFAS.QTDE_O, PRODUCAO_OS_TAREFAS.O1, PRODUCAO_OS_TAREFAS.O2, PRODUCAO_OS_TAREFAS.O3, PRODUCAO_OS_TAREFAS.O4, PRODUCAO_OS_TAREFAS.O5, PRODUCAO_OS_TAREFAS.O6, PRODUCAO_OS_TAREFAS.O7, PRODUCAO_OS_TAREFAS.O8, PRODUCAO_OS_TAREFAS.O9, PRODUCAO_OS_TAREFAS.O10, PRODUCAO_OS_TAREFAS.O11, PRODUCAO_OS_TAREFAS.O12, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, dbo.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO, dbo.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS, dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, dbo.PRODUCAO_SETOR PRODUCAO_SETOR
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO AND 
PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = PRODUCAO_OS_TAREFAS.ORDEM_SERVICO AND 
PRODUCAO_ORDEM_SERVICO.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO AND 
PRODUCAO_ORDEM_SERVICO.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO AND 
((PRODUCAO_FASE.FASE_PRODUCAO='007') AND (PRODUCAO_ORDEM_SERVICO.DATA>={ts '2012-01-01 00:00:00'}) AND 
(PRODUCAO_SETOR.DESC_SETOR_PRODUCAO Like 'OFICINA%') AND 
(PRODUCAO_ORDEM_SERVICO.DATA>={ts '2012-01-01 00:00:00'}) AND (PRODUCAO_SETOR.DESC_SETOR_PRODUCAO Like 'OFICINA%'))