SELECT 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA, 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO,
OPERADORES.QTDE_OPERADOR,
OPERADORES.MINUTOS_DISPONIVEIS,
TEMPO_PADRAO.TEMPO_CRONOMETRADO,
QTDE_O =SUM(PRODUCAO_OS_TAREFAS.QTDE_O) 
FROM PRODUCAO_ORDEM_SERVICO
JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

JOIN (
 
SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,PRODUCAO_SETOR.DESC_SETOR_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007'

) AS COSTURA
ON PRODUCAO_OS_TAREFAS.PRODUTO=COSTURA.PRODUTO AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

JOIN PRODUCAO_ORDEM_SERVICO_HORARIA ON PRODUCAO_ORDEM_SERVICO_HORARIA.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO  
ON TEMPO_PADRAO.TABELA_OPERACOES=PRODUCAO_OS_TAREFAS.PRODUTO
  
LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES  
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO  

WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='009' AND PRODUCAO_ORDEM_SERVICO.INDICADOR_TIPO_MOV=1 AND YEAR(PRODUCAO_ORDEM_SERVICO.DATA)>=2014 AND PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO AND COSTURA.RECURSO_PRODUTIVO='GFI10' AND DATA_HORA>='20141023' AND DATA_HORA <= '20141024'

GROUP BY 
COSTURA.DESC_SETOR_PRODUCAO,
COSTURA.RECURSO_PRODUTIVO,
PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,
PRODUCAO_OS_TAREFAS.PRODUTO,
OPERADORES.QTDE_OPERADOR,
OPERADORES.MINUTOS_DISPONIVEIS,
TEMPO_PADRAO.TEMPO_CRONOMETRADO
