-- CABECALHO
select * from PRODUCAO_ORDEM_SERVICO
where DATA='20130502' and FASE_PRODUCAO='009' and ORDEM_SERVICO='382785'

-- ITENS
SELECT * FROM PRODUCAO_OS_TAREFAS
where ORDEM_SERVICO='382785'

select * from PRODUCAO_TAREFAS
where TAREFA='330454'

SELECT  
OFICINA=C.DESC_SETOR_PRODUCAO, 
GRUPO=C.DESC_RECURSO, 
C.TIPO_RECURSO, 
ANO=substring(convert(char(10),B.DATA,103),7,4), 
MES=substring(convert(char(10),B.DATA,103),4,2), 
DIA03=( 
       SELECT SUM(QTDE_O) FROM PRODUCAO_OS_TAREFAS A1 
       JOIN PRODUCAO_ORDEM_SERVICO B1 ON B1.ORDEM_SERVICO=A1.ORDEM_SERVICO
       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=A1.ORDEM_PRODUCAO  
       WHERE DATA='20130503' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND B1.FASE_PRODUCAO='009' AND B1.CONFERIDO_POR='REGIANE JULIETE'
), 
MTCR03=( 
       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA 
       WHERE EMISSAO = '20130503' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL='DR VAREJO'
), 
TOTAL=SUM(QTDE_O),DTRAB=0 FROM PRODUCAO_OS_TAREFAS A 
JOIN PRODUCAO_ORDEM_SERVICO B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO
LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO  
WHERE DATA='20130503' AND B.FASE_PRODUCAO='009' AND B.CONFERIDO_POR='REGIANE JULIETE'
GROUP BY C.DESC_RECURSO, 
C.DESC_SETOR_PRODUCAO, 
C.TIPO_RECURSO, 
substring(convert(char(10),B.DATA,103),7,4), 
substring(convert(char(10),B.DATA,103),4,2) 
order by OFICINA,GRUPO



SELECT * FROM W_ORDEM_PRODUCAO_OFICINA_NOVA
WHERE 


SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA 
WHERE EMISSAO = '20130502' AND DESC_RECURSO LIKE 'GRUPO JULIETE%' AND DESC_SETOR_PRODUCAO LIKE 'OFICINA JULIETE'
       
SELECT * FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA        