USE [DRVAREJO]
GO

/****** Object:  View [dbo].[W_SAW_META_DIA]    Script Date: 10/24/2014 10:33:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[W_SAW_META_DIA] AS
SELECT 
DIA = CASE DATEPART(DW,COSTURA.DATA)   
   WHEN 1 THEN 'DOMINGO'  
   WHEN 2 THEN 'SEGUNDA'  
   WHEN 3 THEN 'TERÇA'  
   WHEN 4 THEN 'QUARTA'  
   WHEN 5 THEN 'QUINTA'  
   WHEN 6 THEN 'SEXTA'  
   ELSE 'SÁBADO' 
END,  
COSTURA.PRIORIDADE,CAPACIDADE=((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO),
DIAS_PRODUCAO=(RECEBIMENTO.QTDE_O/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)),
QTDE_OPERADOR=OPERADORES.QTDE_OPERADOR,MINUTOS_DISPONIVEIS=OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_CRONOMETRADO=TEMPO_PADRAO.TEMPO_CRONOMETRADO,RECEBIMENTO.PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,COSTURA.RECURSO_PRODUTIVO,COSTURA.DESC_RECURSO,RECEBIMENTO.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_O 
FROM (

SELECT PRODUCAO_ORDEM_SERVICO_HORARIA.DATA_HORA,PRODUCAO_OS_TAREFAS.*,PRODUCAO_SETOR.* 
FROM PRODUCAO_ORDEM_SERVICO_HORARIA
JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO_HORARIA.ORDEM_SERVICO
JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_OS_TAREFAS.TAREFA
JOIN PRODUCAO_SETOR ON PRODUCAO_SETOR.FASE_PRODUCAO=PRODUCAO_TAREFAS.FASE_PRODUCAO
WHERE PRODUCAO_TAREFAS.FASE_PRODUCAO IN('009')
AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO='75424'

) AS RECEBIMENTO

LEFT JOIN (
 
SELECT GETDATE() AS DATA,PRODUCAO_ORDEM.PRIORIDADE, PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE with (nolock), dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS with (nolock), dbo.PRODUCAO_SETOR PRODUCAO_SETOR with (nolock), dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS with (nolock), dbo.PRODUTOS PRODUTOS with (nolock), dbo.PRODUCAO_ORDEM with (nolock)
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND
PRODUCAO_FASE.FASE_PRODUCAO='007' AND PRODUCAO_ORDEM.FILIAL='DR VAREJO'

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS with (nolock) WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA with (nolock) WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO

WHERE RECEBIMENTO.QTDE_O>0 AND DATEPART(WEEK,DATA) BETWEEN DATEPART(WEEK,GETDATE()) AND DATEPART(WEEK,GETDATE()) AND  DATEPART (year, DATA) = DATEPART(YEAR,GETDATE()) AND DATEPART(DAY,DATA) = DATEPART(DAY,GETDATE()) AND RECEBIMENTO.RECURSO_PRODUTIVO LIKE 'G%'  



GO


