lx_cade ldr

select * from PRODUTOS_PERIODOS_ENTREGAS_DR_LDR

SELECT * FROM COTA_LIMITE_PERFAT
order by PERIODO_PCP

SELECT DATEPART(WEEK,LIMITE_ENTREGA) ,NUMERO_ENTREGA,ENTREGA,LIMITE_ENTREGA,SUM(QTDE_ORIGINAL) from VENDAS_PRODUTO
WHERE YEAR(ENTREGA)=2013
GROUP BY NUMERO_ENTREGA,ENTREGA,LIMITE_ENTREGA
ORDER BY NUMERO_ENTREGA,ENTREGA,LIMITE_ENTREGA


select * from LCF_NOTA_SAIDA
where SK_TERCEIRO is null

SELECT CTB_ACOMPANHAMENTO.OBS, CTB_A_RECEBER_PARCELA.* FROM CTB_A_RECEBER_PARCELA
JOIN CTB_ACOMPANHAMENTO ON CTB_ACOMPANHAMENTO.LANCAMENTO=CTB_A_RECEBER_PARCELA.LANCAMENTO AND
CTB_ACOMPANHAMENTO.ITEM=CTB_A_RECEBER_PARCELA.ITEM
WHERE CTB_A_RECEBER_PARCELA.LANCAMENTO='241336' AND CTB_ACOMPANHAMENTO.ITEM='93'


SELECT * FROM CTB_ACOMPANHAMENTO
WHERE LANCAMENTO='241336' AND ITEM='93'






lx_cade acompanhamento



