lx_cade_coluna tipo_ocorrencia


select * from CTB_LX_BORDERO_OCORRENCIA
WHERE LX_TIPO_OCORRENCIA='REM'


update CTB_LX_BORDERO_OCORRENCIA 
set DESCRICAO_OCORRENCIA='REMESSA DE TÍTULOS'
WHERE LX_TIPO_OCORRENCIA='REM'


/* VISUALLINX Execute(Alias:Tabela_validacao)  */
select  CTB_LX_BORDERO_OCORRENCIA.DESCRICAO_OCORRENCIA, ctb_lx_bordero_ocorrencia.lx_tipo_ocorrencia, CTB_LX_BORDERO_OCORRENCIA.INATIVO  
from CTB_LX_BORDERO_OCORRENCIA 
where  CTB_LX_BORDERO_OCORRENCIA.DESCRICAO_OCORRENCIA LIKE '%'    
