select b.RECURSO_PRODUTIVO,D.DESC_RECURSO,b.FASE_PRODUCAO,C.DESC_FASE_PRODUCAO, A.EMISSAO,A.ORDEM_PRODUCAO,B.QTDE_EM_PROCESSO 
from PRODUCAO_ORDEM A with (nolock)
JOIN PRODUCAO_TAREFAS B with (nolock) ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
JOIN PRODUCAO_FASE C with (nolock) ON C.FASE_PRODUCAO=B.FASE_PRODUCAO
JOIN PRODUCAO_RECURSOS D with (nolock) ON D.RECURSO_PRODUTIVO=B.RECURSO_PRODUTIVO
WHERE B.QTDE_EM_PROCESSO>0 AND DATEDIFF(DD, A.EMISSAO,GETDATE()) > 60  