--- MAIS RÁPIDA
--- ORDEM DE PRODUCAO SEM FALTA DE MATERIAIS
CREATE PROCEDURE SP_ORDEM_PRODUCAO_MATERIAIS_DISPONIVEIS AS 

--- gera tabela temporaria #ORDEM_PRODUCAO_NA_FASE_PCP
TRUNCATE TABLE ORDEM_PRODUCAO_NA_FASE_PCP

INSERT INTO ORDEM_PRODUCAO_NA_FASE_PCP
SELECT PT.ORDEM_PRODUCAO,poc.QTDE_O,PT.FASE_PRODUCAO,PT.SETOR_PRODUCAO,POC.PRODUTO,POC.COR_PRODUTO,GRUPOS.RECURSO_PRODUTIVO 
FROM PRODUCAO_TAREFAS PT with (nolock)  
JOIN PRODUCAO_ORDEM_COR POC WITH (NOLOCK) ON POC.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO
LEFT JOIN (SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO='007') AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = PT.ORDEM_PRODUCAO 
JOIN PRODUCAO_ORDEM PO WITH (NOLOCK) ON PO.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO AND PO.FILIAL='DR VAREJO'
WHERE FASE_PRODUCAO='001' AND QTDE_EM_PROCESSO>0 

--- gera tabela temporaria #ORDEM_PRODUCAO_COM_PENDENCIAS
TRUNCATE TABLE ORDEM_PRODUCAO_COM_PENDENCIAS

INSERT INTO ORDEM_PRODUCAO_COM_PENDENCIAS
SELECT DISTINCT FINAL.ORDEM_PRODUCAO FROM ( 
   SELECT A.ORDEM_PRODUCAO,A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,A.RESERVA,C.GRUPO,C.SUBGRUPO,QTDE_ESTOQUE=ISNULL(D.QTDE_ESTOQUE,0),   
   CASE WHEN B.QTDE_DISPONIVEL IS NULL THEN ISNULL(D.QTDE_ESTOQUE,0) ELSE ISNULL(B.QTDE_DISPONIVEL,0) END AS QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A WITH (NOLOCK)
   LEFT JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL   
   LEFT JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL   
   LEFT JOIN ESTOQUE_MATERIAIS D WITH (NOLOCK) ON D.MATERIAL=A.MATERIAL AND D.COR_MATERIAL=A.COR_MATERIAL AND D.FILIAL='DR VAREJO'   
        JOIN PRODUCAO_ORDEM E WITH (NOLOCK) ON E.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO AND E.FILIAL='DR VAREJO'
) AS FINAL  
LEFT JOIN (
   SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
   WHERE FASE_PRODUCAO='007'
) AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = FINAL.ORDEM_PRODUCAO 
JOIN (SELECT ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO='001' AND QTDE_EM_PROCESSO>0) AS PT ON PT.ORDEM_PRODUCAO=FINAL.ORDEM_PRODUCAO
WHERE RESERVA>0 AND RESERVA>QTDE_DISPONIVEL AND FINAL.ORDEM_PRODUCAO NOT LIKE '%.%' AND MATERIAL NOT IN (SELECT DISTINCT A.MATERIAL FROM MATERIAIS A WITH (NOLOCK) JOIN MATERIAIS_CORES B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL WHERE GETDATE() NOT BETWEEN B.INICIO_VENDAS AND B.FIM_VENDAS) 
GROUP BY GRUPOS.RECURSO_PRODUTIVO,FINAL.ORDEM_PRODUCAO,MATERIAL,DESC_MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,QTDE_DISPONIVEL 


--- EXECUÇÃO NO EXCEL
EXEC SP_ORDEM_PRODUCAO_MATERIAIS_DISPONIVEIS
SELECT ORDEM_PRODUCAO,QTDE_O,FASE_PRODUCAO,SETOR_PRODUCAO,PRODUTO,COR_PRODUTO,RECURSO_PRODUTIVO 
FROM ORDEM_PRODUCAO_NA_FASE_PCP A
WHERE NOT EXISTS(SELECT * FROM ORDEM_PRODUCAO_COM_PENDENCIAS WHERE ORDEM_PRODUCAO=A.ORDEM_PRODUCAO)

SELECT * FROM ORDEM_PRODUCAO_NA_FASE_PCP 
SELECT * FROM ORDEM_PRODUCAO_COM_PENDENCIAS


-- MAIS LENTA
SELECT ORDEM_PRODUCAO,QTDE_O,FASE_PRODUCAO,SETOR_PRODUCAO,PRODUTO,COR_PRODUTO,RECURSO_PRODUTIVO FROM (
	SELECT PT.ORDEM_PRODUCAO,poc.QTDE_O,PT.FASE_PRODUCAO,PT.SETOR_PRODUCAO,POC.PRODUTO,POC.COR_PRODUTO,GRUPOS.RECURSO_PRODUTIVO 
	FROM PRODUCAO_TAREFAS PT with (nolock)  
	JOIN PRODUCAO_ORDEM_COR POC WITH (NOLOCK) ON POC.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO
	LEFT JOIN (SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO='007') AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = PT.ORDEM_PRODUCAO 
	JOIN PRODUCAO_ORDEM PO WITH (NOLOCK) ON PO.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO AND PO.FILIAL='DR VAREJO'
	WHERE FASE_PRODUCAO='001' AND QTDE_EM_PROCESSO>0 
) A
WHERE NOT EXISTS(
		SELECT distinct FINAL.ORDEM_PRODUCAO FROM ( 
		   SELECT A.ORDEM_PRODUCAO,A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,A.RESERVA,C.GRUPO,C.SUBGRUPO,QTDE_ESTOQUE=ISNULL(D.QTDE_ESTOQUE,0),   
		   CASE WHEN B.QTDE_DISPONIVEL IS NULL THEN ISNULL(D.QTDE_ESTOQUE,0) ELSE ISNULL(B.QTDE_DISPONIVEL,0) END AS QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A WITH (NOLOCK)
		   LEFT JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL   
		   LEFT JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL   
		   LEFT JOIN ESTOQUE_MATERIAIS D WITH (NOLOCK) ON D.MATERIAL=A.MATERIAL AND D.COR_MATERIAL=A.COR_MATERIAL AND D.FILIAL='DR VAREJO'   
                JOIN PRODUCAO_ORDEM E WITH (NOLOCK) ON E.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO AND E.FILIAL='DR VAREJO'
		) AS FINAL  
		LEFT JOIN (
		   SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
		   WHERE FASE_PRODUCAO='007'
		) AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = FINAL.ORDEM_PRODUCAO 
		JOIN (SELECT ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO='001' AND QTDE_EM_PROCESSO>0) AS PT ON PT.ORDEM_PRODUCAO=FINAL.ORDEM_PRODUCAO
		WHERE FINAL.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND RESERVA>0 AND RESERVA>QTDE_DISPONIVEL AND FINAL.ORDEM_PRODUCAO NOT LIKE '%.%' AND MATERIAL NOT IN (SELECT DISTINCT A.MATERIAL FROM MATERIAIS A WITH (NOLOCK) JOIN MATERIAIS_CORES B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL WHERE GETDATE() NOT BETWEEN B.INICIO_VENDAS AND B.FIM_VENDAS) 
		group by GRUPOS.RECURSO_PRODUTIVO,FINAL.ORDEM_PRODUCAO,MATERIAL,DESC_MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,QTDE_DISPONIVEL 
)
