lx_cade_coluna reserva

select ESTOQUE_MATERIAIS.QTDE_ESTOQUE,PRODUCAO_RESERVA.* from PRODUCAO_RESERVA
join ESTOQUE_MATERIAIS on ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL and ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL
where ORDEM_PRODUCAO='51391' and FILIAL='DR VAREJO'

select * from ESTOQUE_MATERIAIS

SELECT RESERVA=SUM(RESERVA), RESERVA_ORIGINAL=SUM(RESERVA_ORIGINAL) FROM PRODUCAO_RESERVA
where MATERIAL='40.03.0017 ' and COR_MATERIAL='PT0124    ' and RESERVA>0

SELECT * FROM PRODUCAO_RESERVA
WHERE ORDEM_PRODUCAO='51391'