--- ORDEM DE PRODUCAO SEM FALTA DE MATERIAIS GO E VAREJO
SELECT FILIAL=RTRIM(C.FILIAL), A.ORDEM_PRODUCAO,B.PRODUTO,QTDE_EM_PROCESSO,FASE_PRODUCAO,SETOR_PRODUCAO,RECURSO_PRODUTIVO 
FROM PRODUCAO_TAREFAS A WITH (NOLOCK) 
JOIN PRODUCAO_ORDEM_COR B WITH (NOLOCK) ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
JOIN PRODUCAO_ORDEM C WITH (NOLOCK) ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
WHERE A.FASE_PRODUCAO IN ('001','00','20','30','100','101','50') AND A.QTDE_EM_PROCESSO>0 AND NOT EXISTS
(	--- ORDEM DE PRODUCAO COM FALTA DE MATERIAIS
    SELECT DISTINCT ORDEM_PRODUCAO FROM (
		SELECT GRUPOS.RECURSO_PRODUTIVO,FILIAL=RTRIM(PO.FILIAL), FINAL.ORDEM_PRODUCAO,FINAL.MATERIAL,DESC_MATERIAL,MC.DESC_COR_MATERIAL,FINAL.COR_MATERIAL,QTDE_ESTOQUE=ISNULL(QTDE_ESTOQUE,0),QTDE_DISPONIVEL=ISNULL(QTDE_DISPONIVEL,0),RESERVA=SUM(RESERVA) 
		FROM ( 
			SELECT A.ORDEM_PRODUCAO,A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,A.RESERVA,C.GRUPO,C.SUBGRUPO,QTDE_ESTOQUE=ISNULL(D.QTDE_ESTOQUE,0),   
			CASE WHEN B.QTDE_DISPONIVEL IS NULL THEN ISNULL(D.QTDE_ESTOQUE,0) ELSE ISNULL(B.QTDE_DISPONIVEL,0) END AS QTDE_DISPONIVEL 
			FROM PRODUCAO_RESERVA A WITH (NOLOCK)
			LEFT JOIN W_ESTOQUE_DISPONIVEL_MATERIAL_GO_VAREJO B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL AND B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO  
			LEFT JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL   
			LEFT JOIN (
					   SELECT MATERIAL,
					   COR_MATERIAL,
					   QTDE_ESTOQUE=SUM(QTDE_ESTOQUE) 
					   FROM ESTOQUE_MATERIAIS WITH (NOLOCK) 
					   WHERE FILIAL IN ('DR VAREJO','D.R. LINGERIE') 
					   GROUP BY MATERIAL,COR_MATERIAL 
			) D ON D.MATERIAL=A.MATERIAL AND D.COR_MATERIAL=A.COR_MATERIAL 
			WHERE A.ORDEM_PRODUCAO NOT LIKE '%.%' AND A.RESERVA>0 
		) AS FINAL  
		LEFT JOIN (
			SELECT ORDEM_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
			WHERE FASE_PRODUCAO IN('007','60','61','62','68')
		) AS GRUPOS ON GRUPOS.ORDEM_PRODUCAO = FINAL.ORDEM_PRODUCAO 
		JOIN (
			SELECT ORDEM_PRODUCAO,FASE_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO IN ('001','00','20','30','100','101','50') AND QTDE_EM_PROCESSO>0
		) AS PT ON PT.ORDEM_PRODUCAO=FINAL.ORDEM_PRODUCAO
		JOIN PRODUCAO_ORDEM PO WITH (NOLOCK) ON PO.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO
		JOIN MATERIAIS_CORES MC WITH (NOLOCK) ON MC.MATERIAL=FINAL.MATERIAL AND MC.COR_MATERIAL=FINAL.COR_MATERIAL

		WHERE FINAL.MATERIAL NOT IN (
									 SELECT DISTINCT A.MATERIAL FROM MATERIAIS A WITH (NOLOCK) 
									 JOIN MATERIAIS_CORES B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL  
									 WHERE GETDATE() NOT BETWEEN B.INICIO_VENDAS AND B.FIM_VENDAS
									) 
		AND RESERVA>0 AND RESERVA>QTDE_DISPONIVEL 

		GROUP BY GRUPOS.RECURSO_PRODUTIVO,PO.FILIAL, FINAL.ORDEM_PRODUCAO,FINAL.MATERIAL,DESC_MATERIAL,MC.DESC_COR_MATERIAL,FINAL.COR_MATERIAL,QTDE_ESTOQUE,QTDE_DISPONIVEL
	) AS ORDEM_PRODUCAO_COM_PENDENCIAS
    WHERE ORDEM_PRODUCAO_COM_PENDENCIAS.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO
)
ORDER BY ORDEM_PRODUCAO
