---- 1A MAIS LENTA
select b.filial,C.GRIFFE, C.GRUPO_PRODUTO,a.PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.TIPO_FATURAMENTO,A.NF_SAIDA, A.EMISSAO,A.MPADRAO_VALOR,
A.MPADRAO_VALOR_LIQUIDO,A.QTDE,F.MATRIZ_CLIENTE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - 
((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END ))),B.DATA_FATURAMENTO_RELATIVO,
C.TIPO_PRODUTO,A.TIPO_OPERACAO,D.PRECO1 AS CUSTO,G.UF,H.REGIAO, TIPO_CLIENTE.VALOR_PROPRIEDADE AS TIPO_CLIENTE,RTRIM(I.VALOR_PROPRIEDADE) AS FATOR_KIT,
A.PEDIDO,A.PEDIDO_CLIENTE
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
JOIN PRODUTOS C WITH (NOLOCK) ON C.PRODUTO=A.PRODUTO
LEFT JOIN PRODUTOS_PRECOS D WITH (NOLOCK) ON D.PRODUTO=A.PRODUTO AND D.CODIGO_TAB_PRECO='CD'
LEFT JOIN CLIENTES_ATACADO F WITH (NOLOCK) ON F.CLIENTE_ATACADO=A.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.NOME_CLIFOR=A.NOME_CLIFOR
LEFT JOIN LCF_LX_REGIOES_BRASIL H WITH (NOLOCK) ON H.UF=G.UF
LEFT JOIN (SELECT PROPRIEDADE,CLIENTE_ATACADO,VALOR_PROPRIEDADE FROM PROP_CLIENTES_ATACADO WITH (NOLOCK) WHERE PROPRIEDADE='00261') AS TIPO_CLIENTE ON 
		 TIPO_CLIENTE.CLIENTE_ATACADO=F.CLIENTE_ATACADO
LEFT JOIN PROP_PRODUTOS_GRIFFES I WITH (NOLOCK) ON I.GRIFFE=C.GRIFFE
WHERE B.EMISSAO between '20170101' AND '20171231'


--- mais eficiente
select b.filial,a.GRIFFE, GRUPO_PRODUTO,a.PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.TIPO_FATURAMENTO,A.NF_SAIDA, A.EMISSAO,A.MPADRAO_VALOR,
A.MPADRAO_VALOR_LIQUIDO,A.QTDE,F.MATRIZ_CLIENTE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - 
((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END ))),B.DATA_FATURAMENTO_RELATIVO,
TIPO_PRODUTO,A.TIPO_OPERACAO,D.PRECO1 AS CUSTO,G.UF,H.REGIAO, TIPO_CLIENTE.VALOR_PROPRIEDADE AS TIPO_CLIENTE,RTRIM(I.VALOR_PROPRIEDADE) AS FATOR_KIT,
A.PEDIDO,A.PEDIDO_CLIENTE
from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
LEFT JOIN PRODUTOS_PRECOS D WITH (NOLOCK) ON D.PRODUTO=A.PRODUTO AND D.CODIGO_TAB_PRECO='CD'
LEFT JOIN CLIENTES_ATACADO F WITH (NOLOCK) ON F.CLIENTE_ATACADO=A.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.NOME_CLIFOR=A.NOME_CLIFOR
LEFT JOIN LCF_LX_REGIOES_BRASIL H WITH (NOLOCK) ON H.UF=G.UF
LEFT JOIN (SELECT PROPRIEDADE,CLIENTE_ATACADO,VALOR_PROPRIEDADE FROM PROP_CLIENTES_ATACADO WITH (NOLOCK) WHERE PROPRIEDADE='00261') AS TIPO_CLIENTE ON 
		 TIPO_CLIENTE.CLIENTE_ATACADO=F.CLIENTE_ATACADO
LEFT JOIN PROP_PRODUTOS_GRIFFES I WITH (NOLOCK) ON I.GRIFFE=a.GRIFFE
WHERE B.EMISSAO between '20170101' AND '20171231'


--- crair tabela melhor performace
drop table tmp_faturamento_diario
select b.filial,a.GRIFFE, GRUPO_PRODUTO,a.PRODUTO,A.GERENTE,A.REPRESENTANTE,A.NOME_CLIFOR,A.TIPO_FATURAMENTO,A.NF_SAIDA, A.EMISSAO,A.MPADRAO_VALOR,
A.MPADRAO_VALOR_LIQUIDO,A.QTDE,F.MATRIZ_CLIENTE,VALOR_LIQUIDO_TOTAL=((A.VALOR_LIQUIDO*A.CAMBIO_NA_DATA) - 
((CASE WHEN ABS(B.VALOR_IMPOSTO_AGREGAR) >0 THEN A.VALOR_LIQUIDO*ABS(B.VALOR_IMPOSTO_AGREGAR)/B.VALOR_SUB_ITENS ELSE 0 END ))),B.DATA_FATURAMENTO_RELATIVO,
TIPO_PRODUTO,A.TIPO_OPERACAO,D.PRECO1 AS CUSTO,G.UF,H.REGIAO, TIPO_CLIENTE.VALOR_PROPRIEDADE AS TIPO_CLIENTE,RTRIM(I.VALOR_PROPRIEDADE) AS FATOR_KIT,
A.PEDIDO,A.PEDIDO_CLIENTE
into tmp_faturamento_diario from W_FATURAMENTO_PROD_02 A WITH (NOLOCK)
JOIN W_FATURAMENTO_06 B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND B.FILIAL=A.FILIAL
LEFT JOIN PRODUTOS_PRECOS D WITH (NOLOCK) ON D.PRODUTO=A.PRODUTO AND D.CODIGO_TAB_PRECO='CD'
LEFT JOIN CLIENTES_ATACADO F WITH (NOLOCK) ON F.CLIENTE_ATACADO=A.NOME_CLIFOR
LEFT JOIN CADASTRO_CLI_FOR G WITH (NOLOCK) ON G.NOME_CLIFOR=A.NOME_CLIFOR
LEFT JOIN LCF_LX_REGIOES_BRASIL H WITH (NOLOCK) ON H.UF=G.UF
LEFT JOIN (SELECT PROPRIEDADE,CLIENTE_ATACADO,VALOR_PROPRIEDADE FROM PROP_CLIENTES_ATACADO WITH (NOLOCK) WHERE PROPRIEDADE='00261') AS TIPO_CLIENTE ON 
		 TIPO_CLIENTE.CLIENTE_ATACADO=F.CLIENTE_ATACADO
LEFT JOIN PROP_PRODUTOS_GRIFFES I WITH (NOLOCK) ON I.GRIFFE=a.GRIFFE
WHERE B.EMISSAO between '20170101' AND '20171231' 


SELECT [filial]
      ,[GRIFFE]
      ,[GRUPO_PRODUTO]
      ,[PRODUTO]
      ,[GERENTE]
      ,[REPRESENTANTE]
      ,[NOME_CLIFOR]
      ,[TIPO_FATURAMENTO]
      ,[NF_SAIDA]
      ,[EMISSAO]
      ,[MPADRAO_VALOR]
      ,[MPADRAO_VALOR_LIQUIDO]
      ,[QTDE]
      ,[MATRIZ_CLIENTE]
      ,[VALOR_LIQUIDO_TOTAL]
      ,[DATA_FATURAMENTO_RELATIVO]
      ,[TIPO_PRODUTO]
      ,[TIPO_OPERACAO]
      ,[CUSTO]
      ,[UF]
      ,[REGIAO]
      ,[TIPO_CLIENTE]
      ,[FATOR_KIT]
      ,[PEDIDO]
      ,[PEDIDO_CLIENTE]
from tmp_faturamento_diario



------- 2A MAIS LENTA
SELECT DISTINCT F.FILIAL,
F.NF_SAIDA,
F.SERIE_NF,
F.PRODUTO,
V.DATA_FATURAMENTO_RELATIVO AS AGENDA,
F.PEDIDO_CLIENTE,
CA.MATRIZ_CLIENTE,
F.NOME_CLIFOR,
F.COR_PRODUTO,
F.TIPO_FATURAMENTO,
MES_FATURAMENTO=DATENAME(M,D.EMISSAO),
EXP_01.PREV_EXP_01,
EXP_02.PREV_EXP_02,
EXP_03.PREV_EXP_03,
F.ITEM,
B.TIPO_PRODUTO,
D.EMISSAO,
EMBARQUE.PORTARIA_SAIDA,
EMBARQUE.HORA_SAIDA,
C.ORDEM AS ORDEM_TAMANHO,
C.GRADE,
C.TAMANHO,
	QTDE = CASE C.ORDEM
		WHEN 1 THEN F.F1		WHEN 2 THEN F.F2		WHEN 3 THEN F.F3		WHEN 4 THEN F.F4
		WHEN 5 THEN F.F5		WHEN 6 THEN F.F6		WHEN 7 THEN F.F7		WHEN 8 THEN F.F8
		WHEN 9 THEN F.F9		WHEN 10 THEN F.F10	WHEN 11 THEN F.F11	WHEN 12 THEN F.F12
		WHEN 13 THEN F.F13	WHEN 14 THEN F.F14	WHEN 15 THEN F.F15	WHEN 16 THEN F.F16
		WHEN 17 THEN F.F17	WHEN 18 THEN F.F18	WHEN 19 THEN F.F19	WHEN 20 THEN F.F20
		WHEN 21 THEN F.F21	WHEN 22 THEN F.F22	WHEN 23 THEN F.F23	WHEN 24 THEN F.F24
		WHEN 25 THEN F.F25	WHEN 26 THEN F.F26	WHEN 27 THEN F.F27	WHEN 28 THEN F.F28
		WHEN 29 THEN F.F29	WHEN 30 THEN F.F30	WHEN 31 THEN F.F31	WHEN 32 THEN F.F32
		WHEN 33 THEN F.F33	WHEN 34 THEN F.F34	WHEN 35 THEN F.F35	WHEN 36 THEN F.F36
		WHEN 37 THEN F.F37	WHEN 38 THEN F.F38	WHEN 39 THEN F.F39	WHEN 40 THEN F.F40
		WHEN 41 THEN F.F41	WHEN 42 THEN F.F42	WHEN 43 THEN F.F43	WHEN 44 THEN F.F44
		WHEN 45 THEN F.F45	WHEN 46 THEN F.F46	WHEN 47 THEN F.F47	WHEN 48 THEN F.F48  ELSE 0 END,
	F.PEDIDO_COR,F.CAIXA,F.PEDIDO,F.ENTREGA,F.DESCONTO_ITEM,F.PRECO,F.PACKS,F.ROMANEIO,F.CUSTO_NA_DATA,F.MOEDA,F.CAMBIO_NA_DATA
FROM W_FATURAMENTO_PROD_02 F WITH (NOLOCK)
	JOIN PRODUTOS B WITH (NOLOCK)ON B.PRODUTO=F.PRODUTO
	JOIN VENDAS V WITH (NOLOCK) ON V.PEDIDO=F.PEDIDO
	JOIN W_FATURAMENTO_06 D WITH (NOLOCK) ON D.NF_SAIDA=F.NF_SAIDA AND D.SERIE_NF=F.SERIE_NF AND D.FILIAL=F.FILIAL
	JOIN CLIENTES_ATACADO CA WITH (NOLOCK) ON CA.CLIENTE_ATACADO=F.NOME_CLIFOR
	JOIN W_PRODUTOS_TAMANHOS_VERTICAL C WITH (NOLOCK) ON C.GRADE=B.GRADE
	LEFT JOIN (
         SELECT NF_SAIDA, FILIAL, PROPRIEDADE, VALOR_PROPRIEDADE AS DATA_EMBARQUE,
         PORTARIA_SAIDA=SUBSTRING(RTRIM(VALOR_PROPRIEDADE),1,10), HORA_SAIDA=SUBSTRING(RTRIM(VALOR_PROPRIEDADE),11,50)
         FROM PROP_FATURAMENTO (NOLOCK)
         WHERE PROPRIEDADE='00238' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EMBARQUE ON EMBARQUE.NF_SAIDA=F.NF_SAIDA AND EMBARQUE.FILIAL=F.FILIAL   
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_01
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00249' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_01 ON EXP_01.PEDIDO=F.PEDIDO  
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_02
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00270' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_02 ON EXP_02.PEDIDO=F.PEDIDO   
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_03
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00272' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_03 ON EXP_03.PEDIDO=F.PEDIDO    

WHERE CASE C.ORDEM
		WHEN 1 THEN F.F1		WHEN 2 THEN F.F2		WHEN 3 THEN F.F3		WHEN 4 THEN F.F4
		WHEN 5 THEN F.F5		WHEN 6 THEN F.F6		WHEN 7 THEN F.F7		WHEN 8 THEN F.F8
		WHEN 9 THEN F.F9		WHEN 10 THEN F.F10	WHEN 11 THEN F.F11	WHEN 12 THEN F.F12
		WHEN 13 THEN F.F13	WHEN 14 THEN F.F14	WHEN 15 THEN F.F15	WHEN 16 THEN F.F16
		WHEN 17 THEN F.F17	WHEN 18 THEN F.F18	WHEN 19 THEN F.F19	WHEN 20 THEN F.F20
		WHEN 21 THEN F.F21	WHEN 22 THEN F.F22	WHEN 23 THEN F.F23	WHEN 24 THEN F.F24
		WHEN 25 THEN F.F25	WHEN 26 THEN F.F26	WHEN 27 THEN F.F27	WHEN 28 THEN F.F28
		WHEN 29 THEN F.F29	WHEN 30 THEN F.F30	WHEN 31 THEN F.F31	WHEN 32 THEN F.F32
		WHEN 33 THEN F.F33	WHEN 34 THEN F.F34	WHEN 35 THEN F.F35	WHEN 36 THEN F.F36
		WHEN 37 THEN F.F37	WHEN 38 THEN F.F38	WHEN 39 THEN F.F39	WHEN 40 THEN F.F40
		WHEN 41 THEN F.F41	WHEN 42 THEN F.F42	WHEN 43 THEN F.F43	WHEN 44 THEN F.F44
		WHEN 45 THEN F.F45	WHEN 46 THEN F.F46	WHEN 47 THEN F.F47	WHEN 48 THEN F.F48  ELSE 0 END <> 0 AND 
		F.TIPO_OPERACAO='V' AND D.EMISSAO >='20160816' AND D.EMISSAO <= '20171231' AND F.PRODUTO NOT LIKE 'V%'



--- criar tabela temporaria
drop table tmp_expedicao_diaria
SELECT DISTINCT F.FILIAL,
F.NF_SAIDA,
F.SERIE_NF,
F.PRODUTO,
V.DATA_FATURAMENTO_RELATIVO AS AGENDA,
F.PEDIDO_CLIENTE,
CA.MATRIZ_CLIENTE,
F.NOME_CLIFOR,
F.COR_PRODUTO,
F.TIPO_FATURAMENTO,
MES_FATURAMENTO=DATENAME(M,D.EMISSAO),
EXP_01.PREV_EXP_01,
EXP_02.PREV_EXP_02,
EXP_03.PREV_EXP_03,
F.ITEM,
B.TIPO_PRODUTO,
D.EMISSAO,
EMBARQUE.PORTARIA_SAIDA,
EMBARQUE.HORA_SAIDA,
C.ORDEM AS ORDEM_TAMANHO,
C.GRADE,
C.TAMANHO,
	QTDE = CASE C.ORDEM
		WHEN 1 THEN F.F1		WHEN 2 THEN F.F2		WHEN 3 THEN F.F3		WHEN 4 THEN F.F4
		WHEN 5 THEN F.F5		WHEN 6 THEN F.F6		WHEN 7 THEN F.F7		WHEN 8 THEN F.F8
		WHEN 9 THEN F.F9		WHEN 10 THEN F.F10	WHEN 11 THEN F.F11	WHEN 12 THEN F.F12
		WHEN 13 THEN F.F13	WHEN 14 THEN F.F14	WHEN 15 THEN F.F15	WHEN 16 THEN F.F16
		WHEN 17 THEN F.F17	WHEN 18 THEN F.F18	WHEN 19 THEN F.F19	WHEN 20 THEN F.F20
		WHEN 21 THEN F.F21	WHEN 22 THEN F.F22	WHEN 23 THEN F.F23	WHEN 24 THEN F.F24
		WHEN 25 THEN F.F25	WHEN 26 THEN F.F26	WHEN 27 THEN F.F27	WHEN 28 THEN F.F28
		WHEN 29 THEN F.F29	WHEN 30 THEN F.F30	WHEN 31 THEN F.F31	WHEN 32 THEN F.F32
		WHEN 33 THEN F.F33	WHEN 34 THEN F.F34	WHEN 35 THEN F.F35	WHEN 36 THEN F.F36
		WHEN 37 THEN F.F37	WHEN 38 THEN F.F38	WHEN 39 THEN F.F39	WHEN 40 THEN F.F40
		WHEN 41 THEN F.F41	WHEN 42 THEN F.F42	WHEN 43 THEN F.F43	WHEN 44 THEN F.F44
		WHEN 45 THEN F.F45	WHEN 46 THEN F.F46	WHEN 47 THEN F.F47	WHEN 48 THEN F.F48  ELSE 0 END,
	F.PEDIDO_COR,F.CAIXA,F.PEDIDO,F.ENTREGA,F.DESCONTO_ITEM,F.PRECO,F.PACKS,F.ROMANEIO,F.CUSTO_NA_DATA,F.MOEDA,F.CAMBIO_NA_DATA
into tmp_expedicao_diaria FROM W_FATURAMENTO_PROD_02 F WITH (NOLOCK)
	JOIN PRODUTOS B WITH (NOLOCK)ON B.PRODUTO=F.PRODUTO
	JOIN VENDAS V WITH (NOLOCK) ON V.PEDIDO=F.PEDIDO
	JOIN W_FATURAMENTO_06 D WITH (NOLOCK) ON D.NF_SAIDA=F.NF_SAIDA AND D.SERIE_NF=F.SERIE_NF AND D.FILIAL=F.FILIAL
	JOIN CLIENTES_ATACADO CA WITH (NOLOCK) ON CA.CLIENTE_ATACADO=F.NOME_CLIFOR
	JOIN W_PRODUTOS_TAMANHOS_VERTICAL C WITH (NOLOCK) ON C.GRADE=B.GRADE
	LEFT JOIN (
         SELECT NF_SAIDA, FILIAL, PROPRIEDADE, VALOR_PROPRIEDADE AS DATA_EMBARQUE,
         PORTARIA_SAIDA=SUBSTRING(RTRIM(VALOR_PROPRIEDADE),1,10), HORA_SAIDA=SUBSTRING(RTRIM(VALOR_PROPRIEDADE),11,50)
         FROM PROP_FATURAMENTO (NOLOCK)
         WHERE PROPRIEDADE='00238' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EMBARQUE ON EMBARQUE.NF_SAIDA=F.NF_SAIDA AND EMBARQUE.FILIAL=F.FILIAL   
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_01
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00249' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_01 ON EXP_01.PEDIDO=F.PEDIDO  
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_02
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00270' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_02 ON EXP_02.PEDIDO=F.PEDIDO   
LEFT JOIN (
         SELECT PEDIDO, PROPRIEDADE, CONVERT (DATETIME, VALOR_PROPRIEDADE,103) AS PREV_EXP_03
         FROM PROP_VENDAS (NOLOCK)
         WHERE PROPRIEDADE='00272' AND VALOR_PROPRIEDADE<>'99/99/9999'
) AS EXP_03 ON EXP_03.PEDIDO=F.PEDIDO    

WHERE CASE C.ORDEM
		WHEN 1 THEN F.F1		WHEN 2 THEN F.F2		WHEN 3 THEN F.F3		WHEN 4 THEN F.F4
		WHEN 5 THEN F.F5		WHEN 6 THEN F.F6		WHEN 7 THEN F.F7		WHEN 8 THEN F.F8
		WHEN 9 THEN F.F9		WHEN 10 THEN F.F10	WHEN 11 THEN F.F11	WHEN 12 THEN F.F12
		WHEN 13 THEN F.F13	WHEN 14 THEN F.F14	WHEN 15 THEN F.F15	WHEN 16 THEN F.F16
		WHEN 17 THEN F.F17	WHEN 18 THEN F.F18	WHEN 19 THEN F.F19	WHEN 20 THEN F.F20
		WHEN 21 THEN F.F21	WHEN 22 THEN F.F22	WHEN 23 THEN F.F23	WHEN 24 THEN F.F24
		WHEN 25 THEN F.F25	WHEN 26 THEN F.F26	WHEN 27 THEN F.F27	WHEN 28 THEN F.F28
		WHEN 29 THEN F.F29	WHEN 30 THEN F.F30	WHEN 31 THEN F.F31	WHEN 32 THEN F.F32
		WHEN 33 THEN F.F33	WHEN 34 THEN F.F34	WHEN 35 THEN F.F35	WHEN 36 THEN F.F36
		WHEN 37 THEN F.F37	WHEN 38 THEN F.F38	WHEN 39 THEN F.F39	WHEN 40 THEN F.F40
		WHEN 41 THEN F.F41	WHEN 42 THEN F.F42	WHEN 43 THEN F.F43	WHEN 44 THEN F.F44
		WHEN 45 THEN F.F45	WHEN 46 THEN F.F46	WHEN 47 THEN F.F47	WHEN 48 THEN F.F48  ELSE 0 END <> 0 AND 
		F.TIPO_OPERACAO='V' AND D.EMISSAO >='20160816' AND D.EMISSAO <= '20171231' AND F.PRODUTO NOT LIKE 'V%'




SELECT [FILIAL]
      ,[NF_SAIDA]
      ,[SERIE_NF]
      ,[PRODUTO]
      ,[AGENDA]
      ,[PEDIDO_CLIENTE]
      ,[MATRIZ_CLIENTE]
      ,[NOME_CLIFOR]
      ,[COR_PRODUTO]
      ,[TIPO_FATURAMENTO]
      ,[MES_FATURAMENTO]
      ,[PREV_EXP_01]
      ,[PREV_EXP_02]
      ,[PREV_EXP_03]
      ,[ITEM]
      ,[TIPO_PRODUTO]
      ,[EMISSAO]
      ,[PORTARIA_SAIDA]
      ,[HORA_SAIDA]
      ,[ORDEM_TAMANHO]
      ,[GRADE]
      ,[TAMANHO]
      ,[QTDE]
      ,[PEDIDO_COR]
      ,[CAIXA]
      ,[PEDIDO]
      ,[ENTREGA]
      ,[DESCONTO_ITEM]
      ,[PRECO]
      ,[PACKS]
      ,[ROMANEIO]
      ,[CUSTO_NA_DATA]
      ,[MOEDA]
      ,[CAMBIO_NA_DATA]
from tmp_expedicao_diaria with (nolock)
