SELECT 'PEDIDOS ENTREGUE' AS SITUACAO,PERIODO_PCP=RTRIM(FINAL.PERIODO_PCP),FINAL.NUMERO_ENTREGA,QTDE=SUM(FINAL.QTDE_FAT),PEDIDO=COUNT(FINAL.PEDIDO) FROM (
SELECT D.PERIODO_PCP,D.NUMERO_ENTREGA,C.LIMITE_ENTREGA,A.PEDIDO,B.EMISSAO,QTDE_FAT=SUM(A.QTDE) FROM FATURAMENTO_PROD A
JOIN FATURAMENTO B ON A.NF_SAIDA=B.NF_SAIDA AND A.SERIE_NF=B.SERIE_NF
JOIN VENDAS_PRODUTO C ON C.PEDIDO=A.PEDIDO AND C.PRODUTO=A.PRODUTO AND C.COR_PRODUTO=A.COR_PRODUTO
JOIN VENDAS D ON D.PEDIDO=A.PEDIDO
WHERE A.ENTREGA>='20130101'
GROUP BY D.PERIODO_PCP,D.NUMERO_ENTREGA,C.LIMITE_ENTREGA,A.PEDIDO,B.EMISSAO
) AS FINAL
GROUP BY FINAL.PERIODO_PCP,FINAL.NUMERO_ENTREGA
UNION ALL
SELECT 'PEDIDOS ENTREGAR' AS SITUACAO, PERIODO_PCP=RTRIM(FINAL.PERIODO_PCP), FINAL.NUMERO_ENTREGA, QTDE=SUM(FINAL.QTDE_ENTREGAR),PEDIDO=COUNT(FINAL.PEDIDO) FROM (
SELECT B.PERIODO_PCP, B.NUMERO_ENTREGA, B.PEDIDO, QTDE_ENTREGAR=SUM(QTDE_ENTREGAR) FROM VENDAS_PRODUTO A
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO
WHERE A.QTDE_ENTREGAR>0 AND A.LIMITE_ENTREGA>='20130101' AND B.APROVACAO='A'
GROUP BY B.PERIODO_PCP, B.NUMERO_ENTREGA, B.PEDIDO) AS FINAL
GROUP BY FINAL.PERIODO_PCP,FINAL.NUMERO_ENTREGA
