SELECT PEDIDO,PRODUTO,COR_PRODUTO,QTDE_ORIGINAL,QTDE_ENTREGAR,QTDE_EMBALADA FROM VENDAS_PRODUTO
WHERE QTDE_ENTREGAR>0 AND QTDE_EMBALADA=0 AND PRODUTO='42252' AND COR_PRODUTO LIKE'RM%'
UNION ALL
SELECT PEDIDO,PRODUTO,COR_PRODUTO,QTDE_ORIGINAL,QTDE_ENTREGAR,QTDE_EMBALADA FROM VENDAS_PRODUTO
WHERE QTDE_ENTREGAR>0 AND QTDE_EMBALADA=0 AND PRODUTO='43462' AND COR_PRODUTO LIKE'CA%'
