select  USUARIO, VENDAS_STATUS_LOG.STATUS, QTDE=COUNT(*) 
from VENDAS_STATUS_LOG
join VENDAS on VENDAS.PEDIDO=VENDAS_STATUS_LOG.PEDIDO
where DATA_ALTERACAO_STATUS between '20170102' and '20170321' and VENDAS_STATUS_LOG.STATUS in ('A','R') and USUARIO in('AMARAL','KEDILA')
GROUP BY USUARIO,VENDAS_STATUS_LOG.STATUS