SELECT [NUMERO_ENTREGA], [PERIODO_PCP], [QTDE_LIMITE], [FECHADO] 
FROM [COTA_LIMITE_PERFAT] 
WHERE ([PERIODO_PCP] LIKE '%' + ? + '%') 
ORDER BY [PERIODO_PCP], [NUMERO_ENTREGA]

INSERT INTO COTA_LIMITE_PERFAT (NUMERO_ENTREGA,PERIODO_PCP,QTDE_LIMITE,FECHADO)
SELECT NUMERO_ENTREGA,PERIODO_PCP,60000,1 FROM PRODUTOS_PERIODOS_ENTREGAS
WHERE PERIODO_PCP LIKE '2016%'