use [SIGMA]
GO
GRANT ALTER ON [dbo].[SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS] TO [paulino]
GO
use [SIGMA]
GO
GRANT CONTROL ON [dbo].[SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS] TO [paulino]
GO
use [SIGMA]
GO
GRANT EXECUTE ON [dbo].[SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS] TO [paulino]
GO
use [SIGMA]
GO
GRANT TAKE OWNERSHIP ON [dbo].[SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS] TO [paulino]
GO
use [SIGMA]
GO
GRANT VIEW DEFINITION ON [dbo].[SP_INCLUI_CADASTROS_AUXILIARES_OFICINAS] TO [paulino]
GO
