select PESO_BRUTO=SUM(FATURAMENTO_CAIXAS.PESO_BRUTO_CAIXA),PESO_LIQUIDO=SUM(FATURAMENTO_CAIXAS.PESO_LIQUIDO_CAIXA) from VENDAS_PROD_EMBALADO
join FATURAMENTO_CAIXAS ON FATURAMENTO_CAIXAS.CAIXA=VENDAS_PROD_EMBALADO.CAIXA
WHERE VENDAS_PROD_EMBALADO.PEDIDO='45680'

