exec sp_executesql N'
/* VISUALLINX Execute(Alias:xCur_Anterior_2)  */
 SELECT DISTINCT  PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, Producao_tarefas.SEQUENCIA_PRODUTIVA, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2,PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6,PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_TAREFAS_SALDO.S13, PRODUCAO_TAREFAS_SALDO.S14,PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16, PRODUCAO_TAREFAS_SALDO.S17, PRODUCAO_TAREFAS_SALDO.S18,PRODUCAO_TAREFAS_SALDO.S19, PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21, PRODUCAO_TAREFAS_SALDO.S22,PRODUCAO_TAREFAS_SALDO.S23, PRODUCAO_TAREFAS_SALDO.S24, PRODUCAO_TAREFAS_SALDO.S25, PRODUCAO_TAREFAS_SALDO.S26,PRODUCAO_TAREFAS_SALDO.S27, PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29, PRODUCAO_TAREFAS_SALDO.S30,PRODUCAO_TAREFAS_SALDO.S31, PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33, PRODUCAO_TAREFAS_SALDO.S34,PRODUCAO_TAREFAS_SALDO.S35, PRODUCAO_TAREFAS_SALDO.S36, PRODUCAO_TAREFAS_SALDO.S37, PRODUCAO_TAREFAS_SALDO.S38,PRODUCAO_TAREFAS_SALDO.S39, PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41, PRODUCAO_TAREFAS_SALDO.S42,PRODUCAO_TAREFAS_SALDO.S43, PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45, PRODUCAO_TAREFAS_SALDO.S46,PRODUCAO_TAREFAS_SALDO.S47, PRODUCAO_TAREFAS_SALDO.S48, Producao_tarefas.SETOR_PARALELO_NUMERO,Producao_tarefas.RECURSO_PRODUTIVO, Producao_tarefas.INICIO_LIBERADO, Producao_tarefas.INICIO_PREVISTO, Producao_tarefas.INICIO_REAL,Producao_tarefas.FIM_PREVISTO, Producao_tarefas.FIM_ATUALIZADO, Producao_tarefas.ENCERRAMENTO, Producao_tarefas.QTDE_A_PRODUZIR,Producao_tarefas.QTDE_EM_PROCESSO, Producao_tarefas.QTDE_FINALIZADA, Producao_tarefas.QTDE_ALTERACAO_OP, Producao_tarefas.QTDE_PERDAS,Producao_tarefas.QTDE_ALT_OUTRAS_TAREFAS, Producao_tarefas.QTDE_PREVISTA, ultimo_custo_previsto as CUSTO_TAREFA, Producao_tarefas.DESCONTOS_TAREFA, Producao_tarefas.VALOR_TAREFA,Producao_tarefas.STATUS, Producao_recursos.TIPO_RECURSO, Producao_recursos.DESC_RECURSO, Producao_tarefas.FASE_PRODUCAO, Producao_fase.DESC_FASE_PRODUCAO, Producao_tarefas.SETOR_PRODUCAO,Producao_setor.DESC_SETOR_PRODUCAO, Producao_tarefas.TEMPO_PREPARACAO, Producao_tarefas.METODO_LOTE,Producao_tarefas.METODO_LOTE_QTDE, Producao_tarefas.TIPO_TEMPO_PROCESSO,W_produtos_cores.GRADE,ultimo_custo_previsto, ORDEM_CORTE,BAIXA_AUTOMATICA_MATERIAL ,  PRODUCAO_ORDEM_COR.ID_MODIFICACAO,MODIFICACAO_FICHA_TECNICA.DESC_MODIFICACAO,   W_PRODUTOS_CORES.DESC_PRODUTO,W_PRODUTOS_CORES.DESC_COR_PRODUTO    FROM PRODUCAO_TAREFAS_SALDO  INNER JOIN Producao_tarefas ON 	PRODUCAO_TAREFAS_SALDO.TAREFA = Producao_tarefas.TAREFA INNER JOIN W_produtos_cores ON 	PRODUCAO_TAREFAS_SALDO.PRODUTO = W_produtos_cores.PRODUTO AND  											PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = W_produtos_cores.COR_PRODUTO INNER JOIN PRODUCAO_ORDEM ON  PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  INNER JOIN Producao_recursos ON Producao_recursos.RECURSO_PRODUTIVO = Producao_tarefas.RECURSO_PRODUTIVO INNER JOIN Producao_setor ON 	Producao_tarefas.FASE_PRODUCAO = Producao_setor.FASE_PRODUCAO AND  										Producao_tarefas.SETOR_PRODUCAO = Producao_setor.SETOR_PRODUCAO INNER JOIN Producao_fase ON Producao_tarefas.FASE_PRODUCAO = Producao_fase.FASE_PRODUCAO LEFT JOIN producao_os_tarefas ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = producao_os_tarefas.ORDEM_PRODUCAO   											AND PRODUCAO_TAREFAS.tarefa = producao_os_tarefas.tarefa   											AND PRODUCAO_TAREFAS_SALDO.PRODUTO = producao_os_tarefas.PRODUTO  											AND PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = producao_os_tarefas.COR_PRODUTO  LEFT JOIN producao_os_LOTES ON  PRODUCAO_TAREFAS.tarefa = producao_os_LOTES.tarefa   											AND producao_os_LOTES.ORDEM_SERVICO = producao_os_tarefas.ORDEM_SERVICO inner join produtos on produtos.produto = producao_tarefas_saldo.produto  INNER JOIN PRODUCAO_ORDEM_COR ON (PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO AND 	  											PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO AND  											  	PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO )  LEFT JOIN MODIFICACAO_FICHA_TECNICA ON (PRODUCAO_ORDEM_COR.ID_MODIFICACAO = MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO)  WHERE PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = @P1 AND ((PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 2 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 4 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 5)   or  PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV is null)  and Producao_tarefas.sequencia_produtiva IN (''50                       '') AND Producao_tarefas.QTDE_em_processo > 0  order by PRODUCAO_TAREFAS_SALDO.TAREFA',N'@P1 varchar(5)','78673'
 

--- anterior
exec sp_executesql N'
/* ORDEM_SERVICO_125 Execute(Alias:xCur_Anterior_2)  */
SELECT DISTINCT PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, Producao_tarefas.SEQUENCIA_PRODUTIVA, PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2,PRODUCAO_TAREFAS_SALDO.S3, PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6,PRODUCAO_TAREFAS_SALDO.S7, PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_TAREFAS_SALDO.S13, PRODUCAO_TAREFAS_SALDO.S14,PRODUCAO_TAREFAS_SALDO.S15, PRODUCAO_TAREFAS_SALDO.S16, 
PRODUCAO_TAREFAS_SALDO.S17, PRODUCAO_TAREFAS_SALDO.S18,PRODUCAO_TAREFAS_SALDO.S19, PRODUCAO_TAREFAS_SALDO.S20, PRODUCAO_TAREFAS_SALDO.S21, PRODUCAO_TAREFAS_SALDO.S22,PRODUCAO_TAREFAS_SALDO.S23, PRODUCAO_TAREFAS_SALDO.S24, 
PRODUCAO_TAREFAS_SALDO.S25, PRODUCAO_TAREFAS_SALDO.S26,PRODUCAO_TAREFAS_SALDO.S27, PRODUCAO_TAREFAS_SALDO.S28, PRODUCAO_TAREFAS_SALDO.S29, PRODUCAO_TAREFAS_SALDO.S30,PRODUCAO_TAREFAS_SALDO.S31, PRODUCAO_TAREFAS_SALDO.S32, PRODUCAO_TAREFAS_SALDO.S33, PRODUCAO_TAREFAS_SALDO.S34,PRODUCAO_TAREFAS_SALDO.S35, PRODUCAO_TAREFAS_SALDO.S36, PRODUCAO_TAREFAS_SALDO.S37, PRODUCAO_TAREFAS_SALDO.S38,PRODUCAO_TAREFAS_SALDO.S39, PRODUCAO_TAREFAS_SALDO.S40, PRODUCAO_TAREFAS_SALDO.S41, PRODUCAO_TAREFAS_SALDO.S42,PRODUCAO_TAREFAS_SALDO.S43, PRODUCAO_TAREFAS_SALDO.S44, PRODUCAO_TAREFAS_SALDO.S45, PRODUCAO_TAREFAS_SALDO.S46,PRODUCAO_TAREFAS_SALDO.S47, PRODUCAO_TAREFAS_SALDO.S48, Producao_tarefas.SETOR_PARALELO_NUMERO,Producao_tarefas.RECURSO_PRODUTIVO, Producao_tarefas.INICIO_LIBERADO, Producao_tarefas.INICIO_PREVISTO, Producao_tarefas.INICIO_REAL,Producao_tarefas.FIM_PREVISTO, Producao_tarefas.FIM_ATUALIZADO, Producao_tarefas.ENCERRAMENTO, Producao_tarefas.QTDE_A_PRODUZIR,Producao_tarefas.QTDE_EM_PROCESSO, Producao_tarefas.QTDE_FINALIZADA, Producao_tarefas.QTDE_ALTERACAO_OP, Producao_tarefas.QTDE_PERDAS,Producao_tarefas.QTDE_ALT_OUTRAS_TAREFAS, Producao_tarefas.QTDE_PREVISTA, ultimo_custo_previsto as CUSTO_TAREFA, Producao_tarefas.DESCONTOS_TAREFA, Producao_tarefas.VALOR_TAREFA,Producao_tarefas.STATUS, Producao_recursos.TIPO_RECURSO, Producao_recursos.DESC_RECURSO, Producao_tarefas.FASE_PRODUCAO, Producao_fase.DESC_FASE_PRODUCAO, Producao_tarefas.SETOR_PRODUCAO,Producao_setor.DESC_SETOR_PRODUCAO, Producao_tarefas.TEMPO_PREPARACAO, Producao_tarefas.METODO_LOTE,Producao_tarefas.METODO_LOTE_QTDE, Producao_tarefas.TIPO_TEMPO_PROCESSO,W_produtos_cores.GRADE,ultimo_custo_previsto, ORDEM_CORTE,BAIXA_AUTOMATICA_MATERIAL ,  PRODUCAO_ORDEM_COR.ID_MODIFICACAO,MODIFICACAO_FICHA_TECNICA.DESC_MODIFICACAO,   W_PRODUTOS_CORES.DESC_PRODUTO,W_PRODUTOS_CORES.DESC_COR_PRODUTO    FROM PRODUCAO_TAREFAS_SALDO  INNER JOIN Producao_tarefas ON 	PRODUCAO_TAREFAS_SALDO.TAREFA = Producao_tarefas.TAREFA INNER JOIN W_produtos_cores ON 	PRODUCAO_TAREFAS_SALDO.PRODUTO = W_produtos_cores.PRODUTO AND  											PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = W_produtos_cores.COR_PRODUTO INNER JOIN PRODUCAO_ORDEM ON  PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  INNER JOIN Producao_recursos ON Producao_recursos.RECURSO_PRODUTIVO = Producao_tarefas.RECURSO_PRODUTIVO INNER JOIN Producao_setor ON 	Producao_tarefas.FASE_PRODUCAO = Producao_setor.FASE_PRODUCAO AND  										Producao_tarefas.SETOR_PRODUCAO = Producao_setor.SETOR_PRODUCAO INNER JOIN Producao_fase ON Producao_tarefas.FASE_PRODUCAO = Producao_fase.FASE_PRODUCAO LEFT JOIN producao_os_tarefas ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = producao_os_tarefas.ORDEM_PRODUCAO   											AND PRODUCAO_TAREFAS.tarefa = producao_os_tarefas.tarefa   											AND PRODUCAO_TAREFAS_SALDO.PRODUTO = producao_os_tarefas.PRODUTO  											AND PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = producao_os_tarefas.COR_PRODUTO  LEFT JOIN producao_os_LOTES ON  PRODUCAO_TAREFAS.tarefa = producao_os_LOTES.tarefa   											AND producao_os_LOTES.ORDEM_SERVICO = producao_os_tarefas.ORDEM_SERVICO inner join produtos on produtos.produto = producao_tarefas_saldo.produto  INNER JOIN PRODUCAO_ORDEM_COR ON (PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO AND 	  											PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO AND  											  	PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO )  LEFT JOIN MODIFICACAO_FICHA_TECNICA ON (PRODUCAO_ORDEM_COR.ID_MODIFICACAO = MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO) join producao_ordem_servico on producao_ordem_servico.ordem_servico=producao_os_tarefas.ordem_servico WHERE PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = @P1 AND ((PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 2 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 4 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 5)   or  PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV is null)  and Producao_tarefas.sequencia_produtiva IN (''55                       '') AND Producao_tarefas.QTDE_em_processo > 0  order by PRODUCAO_TAREFAS_SALDO.TAREFA',N'@P1 varchar(5)','78673'

exec sp_executesql N'
/* VISUALLINX Execute(Alias:xCur_Atual)  */
select producao_ordem.ordem_producao,producao_ordem.produto,producao_ordem.qtde_em_producao,producao_ordem.emissao,producao_ordem.previsao_fim,producao_ordem.programacao ,  Producao_tarefas.TAREFA, 
Producao_tarefas.SEQUENCIA_PRODUTIVA,Producao_tarefas.SETOR_PARALELO_NUMERO, Producao_tarefas.FASE_PRODUCAO, 
Producao_tarefas.SETOR_PRODUCAO,Producao_tarefas.RECURSO_PRODUTIVO,producao_tarefas.INICIO_PREVISTO,producao_tarefas.SEQUENCIA_ANTERIOR,Producao_tarefas.FIM_PREVISTO as 
FIM_PREVISAO_ANTIGO,Producao_tarefas.INICIO_REAL,Producao_tarefas.FIM_PREVISTO,Producao_tarefas.FIM_ATUALIZADO,Producao_tarefas.ENCERRAMENTO, Producao_tarefas.TEMPO_PREPARACAO,  Producao_tarefas.QTDE_PREVISTA, 
Producao_tarefas.QTDE_A_PRODUZIR,Producao_tarefas.QTDE_EM_PROCESSO, Producao_tarefas.QTDE_FINALIZADA,  Producao_tarefas.QTDE_ALTERACAO_OP, Producao_tarefas.QTDE_PERDAS,Producao_tarefas.QTDE_ALT_OUTRAS_TAREFAS, 
Producao_tarefas.DESCONTOS_TAREFA,Producao_tarefas.VALOR_TAREFA, Producao_tarefas.TIPO_TEMPO_PROCESSO,  Producao_tarefas.STATUS, Producao_tarefas.METODO_LOTE,Producao_tarefas.METODO_LOTE_QTDE, Producao_tarefas.INICIO_LIBERADO,Producao_tarefas.OBS, case when b.custo_tarefa is null then case when a.custo_tarefa is null then producao_tarefas.custo_tarefa else a.custo_tarefa end   else b.custo_tarefa end as custo_tarefa,PRODUCAO_RECURSOS.DESC_RECURSO,producao_ordem_cor.cor_produto from producao_Tarefas    inner join producao_ordem on Producao_tarefas.ORDEM_PRODUCAO = Producao_ordem.ORDEM_PRODUCAO     left join producao_ordem_cor on producao_ordem.ordem_producao = producao_ordem_cor.ordem_producao  inner join PRODUCAO_RECURSOS on Producao_tarefas.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO    left join (SELECT distinct tarefa,CUSTO_TAREFA = ((CASE WHEN   (CASE WHEN PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES IS NULL THEN QTDE_TOTAL ELSE   CASE WHEN   (UTILIZA_QTDE_DA_OP_NO_LOTE IS NULL OR UTILIZA_QTDE_DA_OP_NO_LOTE = 0 )   THEN QTDE_LOTE_ECONOMICO  ELSE QTDE_TOTAL END END)= 0 THEN 0 ELSE TEMPO_CRONOM_FIXO/     (CASE WHEN PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES IS NULL THEN QTDE_TOTAL   ELSE   CASE WHEN (UTILIZA_QTDE_DA_OP_NO_LOTE IS NULL OR UTILIZA_QTDE_DA_OP_NO_LOTE = 0 )   THEN QTDE_LOTE_ECONOMICO  ELSE QTDE_TOTAL END END)  END)  +((TEMPO_CRONOMETRADO+TEMPO_CRONOMETRADO_2+TEMPO_CRONOMETRADO_3+TEMPO_CRONOMETRADO_4) ))*CUSTO_SUGERIDO    FROM PRODUCAO_TAREFAS    INNER JOIN PRODUCAO_ORDEM ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO    INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUCAO_ORDEM.PRODUTO    LEFT JOIN PRODUTOS_TAB_OPERACOES ON PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES = PRODUCAO_ORDEM.TABELA_OPERACOES    INNER JOIN PRODUCAO_RECURSO_CUSTO ON PRODUCAO_RECURSO_CUSTO.LINHA_INDUSTRIAL = PRODUTOS_TAB_OPERACOES.LINHA_INDUSTRIAL   AND   PRODUCAO_RECURSO_CUSTO.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND  PRODUCAO_RECURSO_CUSTO.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO     WHERE PRODUCAO_TAREFAS.TIPO_CUSTO = 2 AND PRODUCAO_RECURSO_CUSTO.RECURSO_PRODUTIVO = @P1 and PRODUCAO_TAREFAS.ORDEM_PRODUCAO = @P2  ) a on a.tarefa=Producao_tarefas.tarefa    left join (SELECT distinct PRODUCAO_TAREFAS.tarefa,PRODUTO_RECURSO_CUSTO.produto, case when ltrim(rtrim(PRODUTO_RECURSO_CUSTO.cor_produto))<>''''then  PRODUTO_RECURSO_CUSTO.cor_produto else ''%'' end as cor_produto , CUSTO_TAREFA = case when a.CUSTO_SUGERIDO is null then PRODUTO_RECURSO_CUSTO.CUSTO_SUGERIDO   else a.CUSTO_SUGERIDO end   FROM PRODUCAO_TAREFAS    INNER JOIN PRODUCAO_ORDEM ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO    INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUCAO_ORDEM.PRODUTO    LEFT JOIN PRODUTOS_TAB_OPERACOES ON PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES = PRODUCAO_ORDEM.TABELA_OPERACOES    INNER JOIN PRODUTO_RECURSO_CUSTO ON PRODUTO_RECURSO_CUSTO.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND  PRODUTO_RECURSO_CUSTO.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO      and PRODUTO_RECURSO_CUSTO.PRODUTO = PRODUCAO_ORDEM.PRODUTO   left join (select * FROM DBO.FX_CUSTO_POR_GRADE(@P3,NULL,NULL,NULL,0)) a on  a.produto = PRODUCAO_ORDEM.produto and  a.cor_produto = PRODUTO_RECURSO_CUSTO.cor_produto and  PRODUCAO_TAREFAS.tarefa = a.tarefa  WHERE PRODUCAO_TAREFAS.TIPO_CUSTO = 1 AND PRODUTO_RECURSO_CUSTO.RECURSO_PRODUTIVO = @P4 and PRODUCAO_TAREFAS.ORDEM_PRODUCAO = @P5)   b on b.tarefa=Producao_tarefas.tarefa  and  producao_ordem_cor.cor_produto like rtrim(b.cor_produto)  inner join produtos on produtos.produto = producao_ordem.produto  where qtde_em_producao >0    and FASE_PRODUCAO =@P6  and setor_producao =@P7  and Producao_tarefas.recurso_produtivo =@P8  and producao_ordem.ORDEM_PRODUCAO = @P9 ',N'@P1 varchar(5),@P2 varchar(5),@P3 varchar(6),@P4 varchar(5),@P5 varchar(5),@P6 varchar(5),@P7 varchar(11),@P8 varchar(5),@P9 varchar(5)','PRFIO','78673','453993','PRFIO','78673','006.1','PREFIORUCCI','PRFIO','78673'


---- atual
exec sp_executesql N'
/* ORDEM_SERVICO_125 Execute(Alias:xCur_Atual)  */
select producao_ordem.ordem_producao,producao_ordem.produto,producao_ordem.qtde_em_producao,producao_ordem.emissao,producao_ordem.previsao_fim,producao_ordem.programacao ,  Producao_tarefas.TAREFA, 
Producao_tarefas.SEQUENCIA_PRODUTIVA,Producao_tarefas.SETOR_PARALELO_NUMERO, Producao_tarefas.FASE_PRODUCAO, 
Producao_tarefas.SETOR_PRODUCAO,Producao_tarefas.RECURSO_PRODUTIVO,producao_tarefas.INICIO_PREVISTO,producao_tarefas.SEQUENCIA_ANTERIOR,Producao_tarefas.FIM_PREVISTO as 
FIM_PREVISAO_ANTIGO,Producao_tarefas.INICIO_REAL,Producao_tarefas.FIM_PREVISTO,Producao_tarefas.FIM_ATUALIZADO,Producao_tarefas.ENCERRAMENTO, Producao_tarefas.TEMPO_PREPARACAO,  Producao_tarefas.QTDE_PREVISTA, 
Producao_tarefas.QTDE_A_PRODUZIR,Producao_tarefas.QTDE_EM_PROCESSO, Producao_tarefas.QTDE_FINALIZADA,  Producao_tarefas.QTDE_ALTERACAO_OP, Producao_tarefas.QTDE_PERDAS,Producao_tarefas.QTDE_ALT_OUTRAS_TAREFAS, 
Producao_tarefas.DESCONTOS_TAREFA,Producao_tarefas.VALOR_TAREFA, Producao_tarefas.TIPO_TEMPO_PROCESSO,  Producao_tarefas.STATUS, Producao_tarefas.METODO_LOTE,Producao_tarefas.METODO_LOTE_QTDE, Producao_tarefas.INICIO_LIBERADO,Producao_tarefas.OBS, case when b.custo_tarefa is null then case when a.custo_tarefa is null then producao_tarefas.custo_tarefa else a.custo_tarefa end   else b.custo_tarefa end as custo_tarefa,PRODUCAO_RECURSOS.DESC_RECURSO,producao_ordem_cor.cor_produto from producao_Tarefas    inner join producao_ordem on Producao_tarefas.ORDEM_PRODUCAO = Producao_ordem.ORDEM_PRODUCAO     left join producao_ordem_cor on producao_ordem.ordem_producao = producao_ordem_cor.ordem_producao  inner join PRODUCAO_RECURSOS on Producao_tarefas.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO    left join (SELECT distinct tarefa,CUSTO_TAREFA = ((CASE WHEN   (CASE WHEN PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES IS NULL THEN QTDE_TOTAL ELSE   CASE WHEN   (UTILIZA_QTDE_DA_OP_NO_LOTE IS NULL OR UTILIZA_QTDE_DA_OP_NO_LOTE = 0 )   THEN QTDE_LOTE_ECONOMICO  ELSE QTDE_TOTAL END END)= 0 THEN 0 ELSE TEMPO_CRONOM_FIXO/     (CASE WHEN PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES IS NULL THEN QTDE_TOTAL   ELSE   CASE WHEN (UTILIZA_QTDE_DA_OP_NO_LOTE IS NULL OR UTILIZA_QTDE_DA_OP_NO_LOTE = 0 )   THEN QTDE_LOTE_ECONOMICO  ELSE QTDE_TOTAL END END)  END)  +((TEMPO_CRONOMETRADO+TEMPO_CRONOMETRADO_2+TEMPO_CRONOMETRADO_3+TEMPO_CRONOMETRADO_4) ))*CUSTO_SUGERIDO    FROM PRODUCAO_TAREFAS    INNER JOIN PRODUCAO_ORDEM ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO    INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUCAO_ORDEM.PRODUTO    LEFT JOIN PRODUTOS_TAB_OPERACOES ON PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES = PRODUCAO_ORDEM.TABELA_OPERACOES    INNER JOIN PRODUCAO_RECURSO_CUSTO ON PRODUCAO_RECURSO_CUSTO.LINHA_INDUSTRIAL = PRODUTOS_TAB_OPERACOES.LINHA_INDUSTRIAL   AND   PRODUCAO_RECURSO_CUSTO.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND  PRODUCAO_RECURSO_CUSTO.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO     WHERE PRODUCAO_TAREFAS.TIPO_CUSTO = 2 AND PRODUCAO_RECURSO_CUSTO.RECURSO_PRODUTIVO = @P1 and PRODUCAO_TAREFAS.ORDEM_PRODUCAO = @P2  ) a on a.tarefa=Producao_tarefas.tarefa    left join (SELECT distinct PRODUCAO_TAREFAS.tarefa,PRODUTO_RECURSO_CUSTO.produto, case when ltrim(rtrim(PRODUTO_RECURSO_CUSTO.cor_produto))<>''''then  PRODUTO_RECURSO_CUSTO.cor_produto else ''%'' end as cor_produto , CUSTO_TAREFA = case when a.CUSTO_SUGERIDO is null then PRODUTO_RECURSO_CUSTO.CUSTO_SUGERIDO   else a.CUSTO_SUGERIDO end   FROM PRODUCAO_TAREFAS    INNER JOIN PRODUCAO_ORDEM ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO    INNER JOIN PRODUTOS ON PRODUTOS.PRODUTO = PRODUCAO_ORDEM.PRODUTO    LEFT JOIN PRODUTOS_TAB_OPERACOES ON PRODUTOS_TAB_OPERACOES.TABELA_OPERACOES = PRODUCAO_ORDEM.TABELA_OPERACOES    INNER JOIN PRODUTO_RECURSO_CUSTO ON PRODUTO_RECURSO_CUSTO.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND  PRODUTO_RECURSO_CUSTO.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO      and PRODUTO_RECURSO_CUSTO.PRODUTO = PRODUCAO_ORDEM.PRODUTO   left join (select * FROM DBO.FX_CUSTO_POR_GRADE(@P3,NULL,NULL,NULL,0)) a on  a.produto = PRODUCAO_ORDEM.produto and  a.cor_produto = PRODUTO_RECURSO_CUSTO.cor_produto and  PRODUCAO_TAREFAS.tarefa = a.tarefa  WHERE PRODUCAO_TAREFAS.TIPO_CUSTO = 1 AND PRODUTO_RECURSO_CUSTO.RECURSO_PRODUTIVO = @P4 and PRODUCAO_TAREFAS.ORDEM_PRODUCAO = @P5)   b on b.tarefa=Producao_tarefas.tarefa  and  producao_ordem_cor.cor_produto like rtrim(b.cor_produto)  inner join produtos on produtos.produto = producao_ordem.produto  where qtde_em_producao >0    and FASE_PRODUCAO =@P6  and setor_producao =@P7  and Producao_tarefas.recurso_produtivo =@P8  and producao_ordem.ORDEM_PRODUCAO = @P9 ',N'@P1 varchar(3),@P2 varchar(5),@P3 varchar(6),@P4 varchar(3),@P5 varchar(5),@P6 varchar(3),@P7 varchar(6),@P8 varchar(3),@P9 varchar(5)','008','77417','444886','008','77417','010','RECAPA','008','77417'


SELECT producao_ordem_servico.nf_saida,producao_ordem_servico.serie_nf,  producao_os_tarefas.ordem_servico, 
Producao_tarefas.SETOR_PRODUCAO,Producao_setor.DESC_SETOR_PRODUCAO, Producao_tarefas.TEMPO_PREPARACAO, Producao_tarefas.METODO_LOTE,Producao_tarefas.METODO_LOTE_QTDE, Producao_tarefas.TIPO_TEMPO_PROCESSO,W_produtos_cores.GRADE,ultimo_custo_previsto, ORDEM_CORTE,BAIXA_AUTOMATICA_MATERIAL ,  PRODUCAO_ORDEM_COR.ID_MODIFICACAO,MODIFICACAO_FICHA_TECNICA.DESC_MODIFICACAO,   W_PRODUTOS_CORES.DESC_PRODUTO,W_PRODUTOS_CORES.DESC_COR_PRODUTO    FROM PRODUCAO_TAREFAS_SALDO  INNER JOIN Producao_tarefas ON 	PRODUCAO_TAREFAS_SALDO.TAREFA = Producao_tarefas.TAREFA INNER JOIN W_produtos_cores ON 	PRODUCAO_TAREFAS_SALDO.PRODUTO = W_produtos_cores.PRODUTO AND  											PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = W_produtos_cores.COR_PRODUTO INNER JOIN PRODUCAO_ORDEM ON  PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO  INNER JOIN Producao_recursos ON Producao_recursos.RECURSO_PRODUTIVO = Producao_tarefas.RECURSO_PRODUTIVO INNER JOIN Producao_setor ON 	Producao_tarefas.FASE_PRODUCAO = Producao_setor.FASE_PRODUCAO AND  										Producao_tarefas.SETOR_PRODUCAO = Producao_setor.SETOR_PRODUCAO INNER JOIN Producao_fase ON Producao_tarefas.FASE_PRODUCAO = Producao_fase.FASE_PRODUCAO LEFT JOIN producao_os_tarefas ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO = producao_os_tarefas.ORDEM_PRODUCAO   											AND PRODUCAO_TAREFAS.tarefa = producao_os_tarefas.tarefa   											AND PRODUCAO_TAREFAS_SALDO.PRODUTO = producao_os_tarefas.PRODUTO  											AND PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = producao_os_tarefas.COR_PRODUTO  LEFT JOIN producao_os_LOTES ON  PRODUCAO_TAREFAS.tarefa = producao_os_LOTES.tarefa   											AND producao_os_LOTES.ORDEM_SERVICO = producao_os_tarefas.ORDEM_SERVICO inner join produtos on produtos.produto = producao_tarefas_saldo.produto  INNER JOIN PRODUCAO_ORDEM_COR ON (PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = PRODUCAO_ORDEM_COR.ORDEM_PRODUCAO AND 	  											PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUCAO_ORDEM_COR.PRODUTO AND  											  	PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUCAO_ORDEM_COR.COR_PRODUTO )  LEFT JOIN MODIFICACAO_FICHA_TECNICA ON (PRODUCAO_ORDEM_COR.ID_MODIFICACAO = MODIFICACAO_FICHA_TECNICA.ID_MODIFICACAO) join producao_ordem_servico on producao_ordem_servico.ordem_servico=producao_os_tarefas.ordem_servico WHERE PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO = '77417' 
AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO='REATH' 
AND ((PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 2 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 4 AND PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV <> 5)   or  PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV is null)  and Producao_tarefas.QTDE_em_processo > 0  

exec sp_executesql N'
/* lx100107ldr  CursorAdapter: Cur_v_faturamento_05_os_produtos(Alias: v_faturamento_05_os_produtos)  */
SELECT  DISTINCT FILHA=CONVERT(VARCHAR(20),''FATURAMENTO_ITEM''), PRODUCAO_ORDEM_SERVICO.NF_SAIDA,       CONSUMIVEL_ITEM=(SELECT MAX(CODIGO_ITEM) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = 
FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR 
(CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))),   PRODUTOS.DESC_PRODUTO DESC_CONSUMIVEL,    MATERIAIS.DESC_MATERIAL,  PRODUCAO_ORDEM_SERVICO.FILIAL,    CONVERT(NUMERIC(9, 3),     QTDE_O) QTDE, 
PRODUTOS.UNIDADE,   CONVERT(NUMERIC(15, 5),    (SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  
FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO,  
CONVERT(NUMERIC(15, 5),  0) DESCONTO_ITEM,     IPI = CONVERT(NUMERIC(11,2),0),    ICMS = CONVERT(NUMERIC(11,2),0),  IRRF = CONVERT(NUMERIC(11,2),0),    CONVERT(NUMERIC(15, 5),   ((SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))))*QTDE_O) VALOR,  PRODUCAO_ORDEM_SERVICO.SERIE_NF,      CAMBIO_NA_DATA = CONVERT(INT,1),  MOEDA = FATURAMENTO.MOEDA,   PESO = CONVERT(INT,1),    PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO  , SPACE(8) REQ_MATERIAL,   SPACE(25) FILIAL_REQ,   SPACE(10) AS COMPRIMENTO, SPACE(3) AS ITEM, MATERIAIS_CORES.COR_MATERIAL,  MATERIAIS.MATERIAL,  CONVERT(VARCHAR(4),'''')  CODIGO_FISCAL_OPERACAO, MATERIAIS.INDICADOR_CFOP, DESCRICAO_INDICADOR_CFOP ,   QTDE_O AS QUANTIDADE, COD_TABELA_FILHA=''O'',   MATERIAIS.TRIBUT_ICMS,  TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, MATERIAIS.TRIBUT_ORIGEM,    TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO, MATERIAIS.CLASSIF_FISCAL,  CLASSIF_FISCAL.DESC_CLASSIFICACAO, MATERIAIS_CORES.CUSTO_REPOSICAO AS TIMESTAMP,   MATERIAIS.CONTA_CONTABIL,  CTB_CONTA_PLANO.DESC_CONTA,    FAIXA=''1'', GERAR_ITEM= CONVERT(BIT,0), SPACE(4) AS ITEM_IMPRESSAO,     CONVERT(NUMERIC(15, 5), MATERIAIS_CORES.CUSTO_REPOSICAO) PRECO, PRODUTOS.PRODUTO  ,   PRODUTOS.GRADE, PRODUTOS.PRODUTO  AS REFERENCIA, PRODUTOS.DESC_PRODUTO, PRODUCAO_OS_TAREFAS.COR_PRODUTO,   QTDE_O, O1, O2, O3, O4, O5, O6, O7, O8, O9, O10, O11, O12, O13, O14, O15, O16, O17, O18, O19, O20, O21,   O22, O23, O24, O25, O26, O27, O28, O29, O30, O31, O32, O33, O34, O35, O36, O37, O38, O39, O40, O41, O42,  O43, O44, O45, O46, O47, O48, PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO, PRODUTO_CORES.DESC_COR_PRODUTO,   CONVERT(NUMERIC(15, 5), (SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO_BRUTO,  CONVERT(NUMERIC(8, 4), 0) PORC_DESCONTO_ITEM, ORIGEM_ITEM = ''P''   FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS     JOIN DBO.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO ON (PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO)    JOIN PRODUTO_CORES ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTO_CORES.PRODUTO AND   PRODUCAO_OS_TAREFAS.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  JOIN DBO.PRODUTOS   PRODUTOS ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTOS.PRODUTO)  JOIN   DBO.PRODUTOS_TAMANHOS PRODUTOS_TAMANHOS ON (PRODUTOS.GRADE=PRODUTOS_TAMANHOS.GRADE)   JOIN FATURAMENTO ON (PRODUCAO_ORDEM_SERVICO.NF_SAIDA=FATURAMENTO.NF_SAIDA AND PRODUCAO_ORDEM_SERVICO.SERIE_NF=FATURAMENTO.SERIE_NF  AND PRODUCAO_ORDEM_SERVICO.FILIAL=FATURAMENTO.FILIAL)   LEFT JOIN MATERIAIS ON (PRODUTOS.MATERIAL = MATERIAIS.MATERIAL )    LEFT JOIN MATERIAIS_CORES ON (PRODUTOS.MATERIAL = MATERIAIS_CORES.MATERIAL   AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = MATERIAIS_CORES.COR_MATERIAL)     LEFT JOIN CTB_LX_INDICADOR_CFOP ON (MATERIAIS.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP)        LEFT JOIN TRIBUT_ICMS ON (PRODUTOS.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS)      LEFT JOIN TRIBUT_ORIGEM ON (PRODUTOS.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM)      LEFT JOIN CLASSIF_FISCAL ON (PRODUTOS.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL)      LEFT JOIN CTB_CONTA_PLANO ON (PRODUTOS.CONTA_CONTABIL=CTB_CONTA_PLANO.CONTA_CONTABIL)   WHERE FATURAMENTO.NF_SAIDA = @P1     AND FATURAMENTO.FILIAL = @P2     AND  FATURAMENTO.SERIE_NF = @P3',N'@P1 varchar(6),@P2 varchar(9),@P3 varchar(1)','025711','DR VAREJO','4'


---- PESQUISA OP ENVIADA DE LDR PARA OFICINA
SELECT  DISTINCT FATURAMENTO.EMISSAO, FILHA=CONVERT(VARCHAR(20),'FATURAMENTO_ITEM'), PRODUCAO_ORDEM_SERVICO.NF_SAIDA,       CONSUMIVEL_ITEM=(SELECT MAX(CODIGO_ITEM) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = 
FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR 
(CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))),   PRODUTOS.DESC_PRODUTO DESC_CONSUMIVEL,    MATERIAIS.DESC_MATERIAL,  PRODUCAO_ORDEM_SERVICO.FILIAL,    CONVERT(NUMERIC(9, 3),     QTDE_O) QTDE, 
PRODUTOS.UNIDADE,   CONVERT(NUMERIC(15, 5),    (SELECT MAX(PRECO_UNITARIO) FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  
FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO,  
CONVERT(NUMERIC(15, 5),  0) DESCONTO_ITEM,     IPI = CONVERT(NUMERIC(11,2),0),    ICMS = CONVERT(NUMERIC(11,2),0),  IRRF = CONVERT(NUMERIC(11,2),0),    CONVERT(NUMERIC(15, 5),   ((SELECT MAX(PRECO_UNITARIO) 
FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND 
((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0))))*QTDE_O) VALOR,  PRODUCAO_ORDEM_SERVICO.SERIE_NF,      
CAMBIO_NA_DATA = CONVERT(INT,1),  MOEDA = FATURAMENTO.MOEDA,   PESO = CONVERT(INT,1),    PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO  , SPACE(8) REQ_MATERIAL,   SPACE(25) FILIAL_REQ,   SPACE(10) AS COMPRIMENTO, SPACE(3) AS ITEM, 
MATERIAIS_CORES.COR_MATERIAL,  MATERIAIS.MATERIAL,  CONVERT(VARCHAR(4),'')  CODIGO_FISCAL_OPERACAO, MATERIAIS.INDICADOR_CFOP, DESCRICAO_INDICADOR_CFOP ,   QTDE_O AS QUANTIDADE, COD_TABELA_FILHA='O',   MATERIAIS.TRIBUT_ICMS,  
TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, MATERIAIS.TRIBUT_ORIGEM,    TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO, MATERIAIS.CLASSIF_FISCAL,  CLASSIF_FISCAL.DESC_CLASSIFICACAO, MATERIAIS_CORES.CUSTO_REPOSICAO AS TIMESTAMP,   
MATERIAIS.CONTA_CONTABIL,  CTB_CONTA_PLANO.DESC_CONTA,    FAIXA='1', GERAR_ITEM= CONVERT(BIT,0), SPACE(4) AS ITEM_IMPRESSAO,     CONVERT(NUMERIC(15, 5), MATERIAIS_CORES.CUSTO_REPOSICAO) PRECO, PRODUTOS.PRODUTO  ,   PRODUTOS.GRADE, 
PRODUTOS.PRODUTO  AS REFERENCIA, PRODUTOS.DESC_PRODUTO, PRODUCAO_OS_TAREFAS.COR_PRODUTO,   QTDE_O, O1, O2, O3, O4, O5, O6, O7, O8, O9, O10, O11, O12, O13, O14, O15, O16, O17, O18, O19, O20, O21,   O22, O23, O24, O25, O26, O27, O28, 
O29, O30, O31, O32, O33, O34, O35, O36, O37, O38, O39, O40, O41, O42,  O43, O44, O45, O46, O47, O48, PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO, PRODUTO_CORES.DESC_COR_PRODUTO,   CONVERT(NUMERIC(15, 5), (SELECT MAX(PRECO_UNITARIO) 
FROM FATURAMENTO_ITEM WHERE FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA     AND FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL     AND  FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF  AND ((CHARINDEX(RTRIM(PRODUTOS.PRODUTO),
FATURAMENTO_ITEM.CODIGO_ITEM)>0)  OR (CHARINDEX(RTRIM(MATERIAIS.MATERIAL),FATURAMENTO_ITEM.CODIGO_ITEM)>0)))) CUSTO_BRUTO,  CONVERT(NUMERIC(8, 4), 0) PORC_DESCONTO_ITEM, ORIGEM_ITEM = 'P'   FROM DBO.PRODUCAO_OS_TAREFAS PRODUCAO_OS_TAREFAS     
JOIN DBO.PRODUCAO_ORDEM_SERVICO PRODUCAO_ORDEM_SERVICO ON (PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO=PRODUCAO_OS_TAREFAS.ORDEM_SERVICO)    JOIN PRODUTO_CORES ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTO_CORES.PRODUTO AND   
PRODUCAO_OS_TAREFAS.COR_PRODUTO=PRODUTO_CORES.COR_PRODUTO)  JOIN DBO.PRODUTOS   PRODUTOS ON (PRODUCAO_OS_TAREFAS.PRODUTO=PRODUTOS.PRODUTO)  JOIN   DBO.PRODUTOS_TAMANHOS PRODUTOS_TAMANHOS ON (PRODUTOS.GRADE=PRODUTOS_TAMANHOS.GRADE)   
JOIN FATURAMENTO ON (PRODUCAO_ORDEM_SERVICO.NF_SAIDA=FATURAMENTO.NF_SAIDA AND PRODUCAO_ORDEM_SERVICO.SERIE_NF=FATURAMENTO.SERIE_NF  AND PRODUCAO_ORDEM_SERVICO.FILIAL=FATURAMENTO.FILIAL)   LEFT JOIN MATERIAIS ON 
(PRODUTOS.MATERIAL = MATERIAIS.MATERIAL )    LEFT JOIN MATERIAIS_CORES ON (PRODUTOS.MATERIAL = MATERIAIS_CORES.MATERIAL   AND PRODUCAO_OS_TAREFAS.COR_PRODUTO = MATERIAIS_CORES.COR_MATERIAL)     
LEFT JOIN CTB_LX_INDICADOR_CFOP ON (MATERIAIS.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP)        LEFT JOIN TRIBUT_ICMS ON (PRODUTOS.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS)      
LEFT JOIN TRIBUT_ORIGEM ON (PRODUTOS.TRIBUT_ORIGEM = TRIBUT_ORIGEM.TRIBUT_ORIGEM)      LEFT JOIN CLASSIF_FISCAL ON (PRODUTOS.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL)      
LEFT JOIN CTB_CONTA_PLANO ON (PRODUTOS.CONTA_CONTABIL=CTB_CONTA_PLANO.CONTA_CONTABIL)   
WHERE FATURAMENTO.FILIAL = 'DR VAREJO' AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO='79221' AND PRODUCAO_OS_TAREFAS.PRODUTO='1030 I' AND PRODUCAO_OS_TAREFAS.COR_PRODUTO='AR0094'



---- PESQUISA OP ENVIADA DE OFICINA PARA LDR
SELECT PRODUCAO_OS_TAREFAS.ORDEM_SERVICO,PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF,PRODUCAO_OS_TAREFAS.QTDE_O,
PRODUCAO_OS_TAREFAS.O1,PRODUCAO_OS_TAREFAS.O2,
PRODUCAO_OS_TAREFAS.O3,PRODUCAO_OS_TAREFAS.O4,
PRODUCAO_OS_TAREFAS.O5,PRODUCAO_OS_TAREFAS.O6,
PRODUCAO_OS_TAREFAS.O7,PRODUCAO_OS_TAREFAS.O8,
PRODUCAO_OS_TAREFAS.O9,PRODUCAO_OS_TAREFAS.O10,
PRODUCAO_OS_TAREFAS.O11,PRODUCAO_OS_TAREFAS.O12,
PRODUCAO_OS_TAREFAS.O13,PRODUCAO_OS_TAREFAS.O14,
PRODUCAO_OS_TAREFAS.O15,PRODUCAO_OS_TAREFAS.O16
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
WHERE PRODUCAO_ORDEM_SERVICO.FILIAL='ATHENA CONFECÇÕES' --AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO='77379' 
AND PRODUCAO_ORDEM_SERVICO.NF_SAIDA='000819' AND PRODUCAO_ORDEM_SERVICO.SERIE_NF='101'        


---- PESQUISA OP QUE ENTROU NA LDR
SELECT PRODUCAO_OS_TAREFAS.ORDEM_SERVICO,PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF,PRODUCAO_OS_TAREFAS.QTDE_O,
PRODUCAO_OS_TAREFAS.O1,PRODUCAO_OS_TAREFAS.O2,
PRODUCAO_OS_TAREFAS.O3,PRODUCAO_OS_TAREFAS.O4,
PRODUCAO_OS_TAREFAS.O5,PRODUCAO_OS_TAREFAS.O6,
PRODUCAO_OS_TAREFAS.O7,PRODUCAO_OS_TAREFAS.O8,
PRODUCAO_OS_TAREFAS.O9,PRODUCAO_OS_TAREFAS.O10,
PRODUCAO_OS_TAREFAS.O11,PRODUCAO_OS_TAREFAS.O12,
PRODUCAO_OS_TAREFAS.O13,PRODUCAO_OS_TAREFAS.O14,
PRODUCAO_OS_TAREFAS.O15,PRODUCAO_OS_TAREFAS.O16
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='010' AND  
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO='77379' 



SELECT DISTINCT PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS1.FASE_PRODUCAO,PRODUCAO_TAREFAS1.INICIO_REAL,PRODUCAO_TAREFAS2.FASE_PRODUCAO,PRODUCAO_TAREFAS2.ENCERRAMENTO FROM PRODUCAO_TAREFAS
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,INICIO_REAL FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='006' AND YEAR(INICIO_REAL)=2014) AS PRODUCAO_TAREFAS1 ON PRODUCAO_TAREFAS1.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,ENCERRAMENTO FROM PRODUCAO_TAREFAS WHERE FASE_PRODUCAO='009' AND YEAR(ENCERRAMENTO)=2014) AS PRODUCAO_TAREFAS2 ON PRODUCAO_TAREFAS2.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO
WHERE YEAR(PRODUCAO_TAREFAS.INICIO_REAL)=2014

drop view W_ORDEM_PRODUCAO_NFE_OFICINA

--- CONSULTA OP
ALTER VIEW W_ORDEM_PRODUCAO_RETORNO AS 
SELECT PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,
PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,
PRODUCAO_ORDEM_SERVICO.SERIE_NF,QTDE_O=SUM(PRODUCAO_OS_TAREFAS.QTDE_O),
O1=SUM(PRODUCAO_OS_TAREFAS.O1),O2=SUM(PRODUCAO_OS_TAREFAS.O2),
O3=SUM(PRODUCAO_OS_TAREFAS.O3),O4=SUM(PRODUCAO_OS_TAREFAS.O4),
O5=SUM(PRODUCAO_OS_TAREFAS.O5),O6=SUM(PRODUCAO_OS_TAREFAS.O6),
O7=SUM(PRODUCAO_OS_TAREFAS.O7),O8=SUM(PRODUCAO_OS_TAREFAS.O8),
O9=SUM(PRODUCAO_OS_TAREFAS.O9),O10=SUM(PRODUCAO_OS_TAREFAS.O10),
O11=SUM(PRODUCAO_OS_TAREFAS.O11),O12=SUM(PRODUCAO_OS_TAREFAS.O12),
O13=SUM(PRODUCAO_OS_TAREFAS.O13),O14=SUM(PRODUCAO_OS_TAREFAS.O14),
O15=SUM(PRODUCAO_OS_TAREFAS.O15),O16=SUM(PRODUCAO_OS_TAREFAS.O16)
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='009'
GROUP BY PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF

DROP VIEW W_ORDEM_PRODUCAO_FASE_010

--- VISÃO DA FASE 010
CREATE VIEW W_ORDEM_PRODUCAO_RECEBIMENTO AS 
SELECT PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF,QTDE_O=SUM(PRODUCAO_OS_TAREFAS.QTDE_O),
O1=SUM(PRODUCAO_OS_TAREFAS.O1),O2=SUM(PRODUCAO_OS_TAREFAS.O2),
O3=SUM(PRODUCAO_OS_TAREFAS.O3),O4=SUM(PRODUCAO_OS_TAREFAS.O4),
O5=SUM(PRODUCAO_OS_TAREFAS.O5),O6=SUM(PRODUCAO_OS_TAREFAS.O6),
O7=SUM(PRODUCAO_OS_TAREFAS.O7),O8=SUM(PRODUCAO_OS_TAREFAS.O8),
O9=SUM(PRODUCAO_OS_TAREFAS.O9),O10=SUM(PRODUCAO_OS_TAREFAS.O10),
O11=SUM(PRODUCAO_OS_TAREFAS.O11),O12=SUM(PRODUCAO_OS_TAREFAS.O12),
O13=SUM(PRODUCAO_OS_TAREFAS.O13),O14=SUM(PRODUCAO_OS_TAREFAS.O14),
O15=SUM(PRODUCAO_OS_TAREFAS.O15),O16=SUM(PRODUCAO_OS_TAREFAS.O16)
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='010' --AND PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO='77379' 
GROUP BY PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF

---- CONFERENCIA DA NFE OFICINA X ENTRADA NA FASE 010
SELECT A.ORDEM_PRODUCAO,A.PRODUTO,A.COR_PRODUTO,A.NF_SAIDA,A.SERIE_NF,
F9_QTDE_O=A.QTDE_O,F9_O1=A.O1,F9_O2=A.O2,F9_O3=A.O3,F9_O4=A.O4,F9_O5=A.O5,F9_O6=A.O6,F9_O7=A.O7,F9_O8=A.O8,F9_O9=A.O9,F9_O10=A.O10,F9_O11=A.O11,F9_O12=A.O12,F9_O13=A.O13,F9_O14=A.O14,F9_O15=A.O15,F9_O16=A.O16,
F10_QTDE_O=B.QTDE_O,F10_O1=B.O1,F10_O2=B.O2,F10_O3=B.O3,F10_O4=B.O4,F10_O5=B.O5,F10_O6=B.O6,F10_O7=B.O7,F10_O8=B.O8,F10_O9=B.O9,F10_O10=B.O10,F10_O11=B.O11,F10_O12=B.O12,F10_O13=B.O13,F10_O14=B.O14,F10_O15=B.O15,F10_O16=B.O16 
FROM W_ORDEM_PRODUCAO_RETORNO A
LEFT JOIN W_ORDEM_PRODUCAO_RECEBIMENTO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO
WHERE A.NF_SAIDA='000819' AND A.SERIE_NF='101'


SELECT A.ORDEM_PRODUCAO,A.PRODUTO,A.COR_PRODUTO,A.NF_SAIDA,A.SERIE_NF,C.EMISSAO,
F9_QTDE_O=A.QTDE_O,F9_O1=A.O1,F9_O2=A.O2,F9_O3=A.O3,F9_O4=A.O4,F9_O5=A.O5,F9_O6=A.O6,F9_O7=A.O7,F9_O8=A.O8,F9_O9=A.O9,F9_O10=A.O10,F9_O11=A.O11,F9_O12=A.O12,F9_O13=A.O13,F9_O14=A.O14,F9_O15=A.O15,F9_O16=A.O16,
F10_QTDE_O=B.QTDE_O,F10_O1=B.O1,F10_O2=B.O2,F10_O3=B.O3,F10_O4=B.O4,F10_O5=B.O5,F10_O6=B.O6,F10_O7=B.O7,F10_O8=B.O8,F10_O9=B.O9,F10_O10=B.O10,F10_O11=B.O11,F10_O12=B.O12,F10_O13=B.O13,F10_O14=B.O14,F10_O15=B.O15,F10_O16=B.O16 
FROM W_ORDEM_PRODUCAO_RETORNO A
LEFT JOIN W_ORDEM_PRODUCAO_RECEBIMENTO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO
LEFT JOIN FATURAMENTO C ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF
WHERE A.NF_SAIDA='000953' AND A.SERIE_NF='101'

--- CONSULTA DEA
SELECT C.FILIAL, A.ORDEM_PRODUCAO,A.PRODUTO,A.COR_PRODUTO,A.NF_SAIDA,A.SERIE_NF,C.EMISSAO,
F9_QTDE_O=A.QTDE_O,F9_O1=A.O1,F9_O2=A.O2,F9_O3=A.O3,F9_O4=A.O4,F9_O5=A.O5,F9_O6=A.O6,F9_O7=A.O7,F9_O8=A.O8,F9_O9=A.O9,F9_O10=A.O10,F9_O11=A.O11,F9_O12=A.O12,F9_O13=A.O13,F9_O14=A.O14,F9_O15=A.O15,F9_O16=A.O16,
F10_QTDE_O=B.QTDE_O,F10_O1=B.O1,F10_O2=B.O2,F10_O3=B.O3,F10_O4=B.O4,F10_O5=B.O5,F10_O6=B.O6,F10_O7=B.O7,F10_O8=B.O8,F10_O9=B.O9,F10_O10=B.O10,F10_O11=B.O11,F10_O12=B.O12,F10_O13=B.O13,F10_O14=B.O14,F10_O15=B.O15,F10_O16=B.O16 
FROM W_ORDEM_PRODUCAO_RETORNO A
LEFT JOIN W_ORDEM_PRODUCAO_RECEBIMENTO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO
LEFT JOIN FATURAMENTO C ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF
WHERE C.EMISSAO>'20141231'



SELECT * FROM W_ORDEM_PRODUCAO_RECEBIMENTO

--- CONSULTA OP + LOTE
CREATE VIEW W_ORDEM_PRODUCAO_LOTE_NFE_OFICINA AS 
SELECT PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,
PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,
PRODUCAO_ORDEM_SERVICO.SERIE_NF,PRODUCAO_OS_LOTES.NUMERO_LOTE,
PRODUCAO_ORDEM_LOTES.GRADE_DO_TAMANHO,PRODUCAO_ORDEM_LOTES.TAMANHO,
PRODUCAO_ORDEM_LOTES.QTDE_LOTE
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
LEFT JOIN PRODUCAO_OS_LOTES ON (PRODUCAO_OS_LOTES.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO AND PRODUCAO_OS_LOTES.TAREFA=PRODUCAO_OS_TAREFAS.TAREFA)
LEFT JOIN PRODUCAO_ORDEM_LOTES ON (PRODUCAO_ORDEM_LOTES.ORDEM_PRODUCAO=PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO AND PRODUCAO_ORDEM_LOTES.NUMERO_LOTE=PRODUCAO_OS_LOTES.NUMERO_LOTE)
WHERE PRODUCAO_ORDEM_SERVICO.NF_SAIDA='000953' AND PRODUCAO_ORDEM_SERVICO.SERIE_NF='101'        
ORDER BY PRODUCAO_ORDEM_LOTES.NUMERO_LOTE


DROP VIEW W_ORDEM_PRODUCAO_RETORNO_FACCAO

---- PROCESSO PARA FACÇÃO

--- CONSULTA OP
CREATE VIEW W_ORDEM_PRODUCAO_RECEBIMENTO_FACCAO AS 
SELECT PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,
PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,
PRODUCAO_ORDEM_SERVICO.SERIE_NF,QTDE_O=SUM(PRODUCAO_OS_TAREFAS.QTDE_O),
O1=SUM(PRODUCAO_OS_TAREFAS.O1),O2=SUM(PRODUCAO_OS_TAREFAS.O2),
O3=SUM(PRODUCAO_OS_TAREFAS.O3),O4=SUM(PRODUCAO_OS_TAREFAS.O4),
O5=SUM(PRODUCAO_OS_TAREFAS.O5),O6=SUM(PRODUCAO_OS_TAREFAS.O6),
O7=SUM(PRODUCAO_OS_TAREFAS.O7),O8=SUM(PRODUCAO_OS_TAREFAS.O8),
O9=SUM(PRODUCAO_OS_TAREFAS.O9),O10=SUM(PRODUCAO_OS_TAREFAS.O10),
O11=SUM(PRODUCAO_OS_TAREFAS.O11),O12=SUM(PRODUCAO_OS_TAREFAS.O12),
O13=SUM(PRODUCAO_OS_TAREFAS.O13),O14=SUM(PRODUCAO_OS_TAREFAS.O14),
O15=SUM(PRODUCAO_OS_TAREFAS.O15),O16=SUM(PRODUCAO_OS_TAREFAS.O16)
FROM PRODUCAO_ORDEM_SERVICO 
JOIN PRODUCAO_OS_TAREFAS ON (PRODUCAO_OS_TAREFAS.ORDEM_SERVICO=PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO)
WHERE PRODUCAO_ORDEM_SERVICO.FASE_PRODUCAO='006'
GROUP BY PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_OS_TAREFAS.PRODUTO,PRODUCAO_OS_TAREFAS.COR_PRODUTO,PRODUCAO_ORDEM_SERVICO.NF_SAIDA,PRODUCAO_ORDEM_SERVICO.SERIE_NF



SELECT C.NOME_CLIFOR, C.FILIAL, A.ORDEM_PRODUCAO,A.PRODUTO,A.COR_PRODUTO,A.NF_SAIDA,A.SERIE_NF,C.EMISSAO,
F6_QTDE_O=A.QTDE_O,F6_O1=A.O1,F6_O2=A.O2,F6_O3=A.O3,F6_O4=A.O4,F6_O5=A.O5,F6_O6=A.O6,F6_O7=A.O7,F6_O8=A.O8,F6_O9=A.O9,F6_O10=A.O10,F6_O11=A.O11,F6_O12=A.O12,F6_O13=A.O13,F6_O14=A.O14,F6_O15=A.O15,F6_O16=A.O16,
F10_QTDE_O=B.QTDE_O,F10_O1=B.O1,F10_O2=B.O2,F10_O3=B.O3,F10_O4=B.O4,F10_O5=B.O5,F10_O6=B.O6,F10_O7=B.O7,F10_O8=B.O8,F10_O9=B.O9,F10_O10=B.O10,F10_O11=B.O11,F10_O12=B.O12,F10_O13=B.O13,F10_O14=B.O14,F10_O15=B.O15,F10_O16=B.O16 
FROM W_ORDEM_PRODUCAO_RECEBIMENTO_FACCAO A
LEFT JOIN W_ORDEM_PRODUCAO_RECEBIMENTO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO
LEFT JOIN FATURAMENTO C ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF
WHERE C.EMISSAO>'20141231'


SELECT * FROM W_ORDEM_PRODUCAO_RECEBIMENTO_FACCAO

SP_HELPTEXT W_ORDEM_PRODUCAO_RECEBIMENTO

