SELECT ESTOQUE_SAI1_MAT.MATERIAL, ESTOQUE_SAI1_MAT.COR_MATERIAL, 
ESTOQUE_SAI1_MAT.FILIAL, ESTOQUE_SAI1_MAT.QTDE, ESTOQUE_SAI1_MAT.REQ_MATERIAL, 
ESTOQUE_SAI1_MAT.QTDE_AUX, ESTOQUE_SAI1_MAT.ORDEM_PRODUCAO, 
MATERIAIS_CORES.DESC_COR_MATERIAL, MATERIAIS.UNID_AUXILIAR, 
MATERIAIS.CTRL_UNID_AUX, MATERIAIS.CTRL_PARTIDAS, MATERIAIS.CTRL_PECAS, 
MATERIAIS.DESC_MATERIAL, MATERIAIS.UNID_ESTOQUE, MATERIAIS.CTRL_PECAS_PARCIAL, 
MATERIAIS.LARGURA, ESTOQUE_SAI1_MAT.ITEM, ESTOQUE_SAI1_MAT.CUSTO, 
ESTOQUE_SAI1_MAT.DATA_CUSTO, MATERIAIS.UNID_FICHA_TEC, MATERIAIS.FATOR_CONVERSAO, 
ESTOQUE_SAI1_MAT.MATAR_SALDO_RESERVA, ESTOQUE_SAI1_MAT.FILIAL_FATURAMENTO, 
ESTOQUE_SAI1_MAT.NF_SAIDA, ESTOQUE_SAI1_MAT.SERIE_NF, ESTOQUE_SAI1_MAT.ICMS, 
ESTOQUE_SAI1_MAT.IPI, ESTOQUE_SAI1_MAT.DESCONTO_ITEM, ESTOQUE_SAI1_MAT.PRECO, 
ESTOQUE_SAI1_MAT.VALOR, ESTOQUE_SAI1_MAT.FATOR_CONVERSAO_UNIDADE, 
ESTOQUE_SAI1_MAT.UNIDADE_FATURAMENTO, (QTDE*FATOR_CONVERSAO) AS QTDE_UNID_FICHA, 
CONVERT(NUMERIC(10, 3), 0) AS QTDE_ESTOQUE_ATUAL, 
CONVERT(NUMERIC(10, 3), 0) AS QTDE_ESTOQUE_NOVO, MATERIAIS_CORES.REFER_FABRICANTE, 
MATERIAIS.REF_FABRICANTE, ESTOQUE_SAI1_MAT.PEDIDO, ESTOQUE_SAI1_MAT.ENTREGA, 
PRODUCAO_ORDEM.ORDEM_CORTE, MATERIAIS.DESC_NF, MATERIAIS.CODIGO_ETIQUETA_GRIFFE, 
M_ORDEM_FABRICACAO_ITEM.ORDEM_FABRICACAO, M_ORDEM_FABRICACAO_ITEM.RECURSO_PRODUTIVO, 
SPACE(40) AS DESC_RECURSO, MATERIAIS_COMPOSICAO.DESC_COMPOSICAO, 
SPACE(8) AS ORDEM_SERVICO, ESTOQUE_SAI1_MAT.PERDA, ESTOQUE_SAI1_MAT.RESERVA_AUTOMATICA, 
ESTOQUE_SAI1_MAT.VALOR_BRUTO, (CUSTO*(QTDE+PERDA)) AS TOTAL_LINHA, 
CONVERT(NUMERIC(14, 2), 0) AS DIFERENCA, CONVERT(NUMERIC(10, 3), 0) AS NECESSIDADE_ATUAL, 
ESTOQUE_SAI1_MAT.CONTA_CONTABIL, CTB_CONTA_PLANO.DESC_CONTA, 
ESTOQUE_SAI1_MAT.RATEIO_CENTRO_CUSTO, CTB_CENTRO_CUSTO_RATEIO.DESC_RATEIO_CENTRO_CUSTO, 
ESTOQUE_SAI1_MAT.RATEIO_FILIAL, CTB_FILIAL_RATEIO.DESC_RATEIO_FILIAL,   
ESTOQUE_SAI1_MAT.NF_ENTRADA, ESTOQUE_SAI1_MAT.SERIE_NF_ENTRADA, 
ESTOQUE_SAI1_MAT.NOME_CLIFOR, ENTRADAS.NOME_CLIFOR_TRIANGULAR, 
ESTOQUE_SAI1_MAT.ID_SUB_PROJETO, AF_SUB_PROJETO.NOME_SUB_PROJETO 
FROM ESTOQUE_SAI1_MAT with (nolock)   
INNER JOIN MATERIAIS with (nolock) ON ESTOQUE_SAI1_MAT.MATERIAL = MATERIAIS.MATERIAL   
INNER JOIN MATERIAIS_CORES with (nolock) ON ESTOQUE_SAI1_MAT.MATERIAL = MATERIAIS_CORES.MATERIAL AND ESTOQUE_SAI1_MAT.COR_MATERIAL = MATERIAIS_CORES.COR_MATERIAL   
LEFT JOIN PRODUCAO_ORDEM with (nolock) ON ESTOQUE_SAI1_MAT.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO   
LEFT JOIN M_ORDEM_FABRICACAO_ITEM with (nolock) ON ESTOQUE_SAI1_MAT.ORDEM_PRODUCAO = M_ORDEM_FABRICACAO_ITEM.ORDEM_PRODUCAO   
LEFT JOIN MATERIAIS_COMPOSICAO with (nolock) ON MATERIAIS.COMPOSICAO = MATERIAIS_COMPOSICAO.COMPOSICAO   
LEFT JOIN CTB_CONTA_PLANO with (nolock) ON ESTOQUE_SAI1_MAT.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL   
LEFT JOIN CTB_CENTRO_CUSTO_RATEIO with (nolock) ON ESTOQUE_SAI1_MAT.RATEIO_CENTRO_CUSTO = CTB_CENTRO_CUSTO_RATEIO.RATEIO_CENTRO_CUSTO   
LEFT JOIN CTB_FILIAL_RATEIO with (nolock) ON ESTOQUE_SAI1_MAT.RATEIO_FILIAL = CTB_FILIAL_RATEIO.RATEIO_FILIAL  
LEFT JOIN AF_SUB_PROJETO with (nolock) ON AF_SUB_PROJETO.ID_SUB_PROJETO = ESTOQUE_SAI1_MAT.ID_SUB_PROJETO  
LEFT JOIN ENTRADAS with (nolock) ON ENTRADAS.NF_ENTRADA = ESTOQUE_SAI1_MAT.NF_ENTRADA   AND  ENTRADAS.SERIE_NF_ENTRADA = ESTOQUE_SAI1_MAT.SERIE_NF_ENTRADA  AND  ENTRADAS.NOME_CLIFOR = ESTOQUE_SAI1_MAT.NOME_CLIFOR  
WHERE ESTOQUE_SAI1_MAT.REQ_MATERIAL = '216715' AND ESTOQUE_SAI1_MAT.FILIAL = 'CONTROLE DE QUALIDADE'   
ORDER BY ESTOQUE_SAI1_MAT.FILIAL, ESTOQUE_SAI1_MAT.REQ_MATERIAL, ESTOQUE_SAI1_MAT.MATERIAL, ESTOQUE_SAI1_MAT.COR_MATERIAL



SELECT ESTOQUE_RET1_MAT.MATERIAL,ESTOQUE_RET1_MAT.COR_MATERIAL,ESTOQUE_RET1_MAT.FILIAL, 
ESTOQUE_RET1_MAT.QTDE,ESTOQUE_RET1_MAT.REQ_MATERIAL,ESTOQUE_RET1_MAT.QTDE_AUX,
ESTOQUE_RET1_MAT.ORDEM_PRODUCAO, MATERIAIS_CORES.DESC_COR_MATERIAL, MATERIAIS.UNID_AUXILIAR,
MATERIAIS.CTRL_UNID_AUX, MATERIAIS.CTRL_PARTIDAS,MATERIAIS.CTRL_PECAS,MATERIAIS.DESC_MATERIAL,
MATERIAIS.UNID_ESTOQUE,MATERIAIS.CTRL_PECAS_PARCIAL,MATERIAIS.LARGURA,ESTOQUE_RET1_MAT.ITEM,
0.00000 as CUSTO,ESTOQUE_RET1_MAT.DATA_CUSTO,MATERIAIS.UNID_FICHA_TEC,MATERIAIS.FATOR_CONVERSAO,
ESTOQUE_RET1_MAT.MATAR_SALDO_RESERVA,NULL AS FILIAL_FATURAMENTO,NULL AS NF_SAIDA,NULL AS SERIE_NF,
0.00 AS ICMS,0.00000 AS IPI,ESTOQUE_RET1_MAT.DESCONTO_ITEM,0.00000 AS PRECO,ESTOQUE_RET1_MAT.VALOR,
1.00000 AS FATOR_CONVERSAO_UNIDADE,'' AS UNIDADE_FATURAMENTO,(ESTOQUE_RET1_MAT.QTDE * FATOR_CONVERSAO ) AS QTDE_UNID_FICHA,
CONVERT(NUMERIC(10, 3), 0) AS QTDE_ESTOQUE_ATUAL,CONVERT(NUMERIC(10, 3), 0) AS QTDE_ESTOQUE_NOVO,
MATERIAIS_CORES.REFER_FABRICANTE, MATERIAIS.REF_FABRICANTE,ESTOQUE_RET1_MAT.PEDIDO,ESTOQUE_RET1_MAT.ENTREGA_PEDIDO AS ENTREGA,
NULL AS ORDEM_CORTE,MATERIAIS.DESC_NF,NULL AS CODIGO_ETIQUETA_GRIFFE,NULL AS ORDEM_FABRICACAO,NULL AS RECURSO_PRODUTIVO,
SPACE(40) AS DESC_RECURSO,MATERIAIS_COMPOSICAO.DESC_COMPOSICAO,SPACE(8) AS ORDEM_SERVICO,ESTOQUE_RET1_MAT.PERDA,
0 AS RESERVA_AUTOMATICA,0.00000 AS VALOR_BRUTO,CAST((ESTOQUE_RET1_MAT.CUSTO_ULT_SAIDA * ESTOQUE_RET1_MAT.QTDE ) AS NUMERIC(14,2)) AS TOTAL_LINHA, 
CONVERT(NUMERIC(14, 2), 0) AS DIFERENCA,CONVERT(NUMERIC(10, 3), 0) AS NECESSIDADE_ATUAL, NULL AS CONTA_CONTABIL,
NULL AS DESC_CONTA, NULL AS RATEIO_CENTRO_CUSTO, NULL AS DESC_RATEIO_CENTRO_CUSTO, 
NULL AS RATEIO_FILIAL, NULL AS DESC_RATEIO_FILIAL,NULL AS NF_ENTRADA, NULL AS SERIE_NF_ENTRADA, 
NULL AS NOME_CLIFOR, NULL AS NOME_CLIFOR_TRIANGULAR, NULL AS ID_SUB_PROJETO, NULL AS NOME_SUB_PROJETO 
FROM ESTOQUE_RET1_MAT 
INNER JOIN MATERIAIS ON ESTOQUE_RET1_MAT.MATERIAL = MATERIAIS.MATERIAL 
INNER JOIN MATERIAIS_CORES ON ESTOQUE_RET1_MAT.MATERIAL = MATERIAIS_CORES.MATERIAL AND ESTOQUE_RET1_MAT.COR_MATERIAL = MATERIAIS_CORES.COR_MATERIAL 
INNER JOIN MATERIAIS_COMPOSICAO ON MATERIAIS.COMPOSICAO = MATERIAIS_COMPOSICAO.COMPOSICAO 
WHERE ESTOQUE_RET1_MAT.REQ_MATERIAL = '011257' AND ESTOQUE_RET1_MAT.FILIAL = 'CONTROLE DE QUALIDADE' 



SELECT MATERIAL,COR_MATERIAL,FILIAL,QTDE,REQ_MATERIAL,QTDE_AUX,ORDEM_PRODUCAO, DESC_COR_MATERIAL, UNID_AUXILIAR,CTRL_UNID_AUX, 
CTRL_PARTIDAS,CTRL_PECAS,DESC_MATERIAL,UNID_ESTOQUE,CTRL_PECAS_PARCIAL,LARGURA,ITEM,
CUSTO,DATA_CUSTO,UNID_FICHA_TEC,FATOR_CONVERSAO,MATAR_SALDO_RESERVA,FILIAL_FATURAMENTO,NF_SAIDA,SERIE_NF,
ICMS,IPI,DESCONTO_ITEM,PRECO,VALOR,FATOR_CONVERSAO_UNIDADE,UNIDADE_FATURAMENTO,QTDE_UNID_FICHA,
QTDE_ESTOQUE_ATUAL,QTDE_ESTOQUE_NOVO,REFER_FABRICANTE, REF_FABRICANTE,PEDIDO,ENTREGA,
ORDEM_CORTE,DESC_NF,CODIGO_ETIQUETA_GRIFFE,ORDEM_FABRICACAO,RECURSO_PRODUTIVO,
DESC_RECURSO,DESC_COMPOSICAO,ORDEM_SERVICO,PERDA,RESERVA_AUTOMATICA,VALOR_BRUTO,TOTAL_LINHA, 
DIFERENCA,NECESSIDADE_ATUAL,CONTA_CONTABIL,DESC_CONTA,RATEIO_CENTRO_CUSTO,DESC_RATEIO_CENTRO_CUSTO, 
RATEIO_FILIAL,DESC_RATEIO_FILIAL,NF_ENTRADA,SERIE_NF_ENTRADA,NOME_CLIFOR,NOME_CLIFOR_TRIANGULAR,ID_SUB_PROJETO,NOME_SUB_PROJETO 
