
INSERT INTO TRANSACOES_QUERY
SELECT [COD_TRANSACAO]
      ,'9'+SUBSTRING([CODIGO_QUERY],2,3)
      ,[NOME_QUERY]
      ,[USUARIO]
      ,[PUBLICO]
      ,[CRIACAO]
      ,[ULT_ATUALIZACAO]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[COMANDO_USUARIO]
      ,[COMANDO_SQL]
      ,[APLICACAO]
      ,[EMPRESA]
  FROM LDR.[DRVAREJO].[dbo].[TRANSACOES_QUERY] A
WHERE cod_transacao='lx009019_001' AND NOT EXISTS(SELECT * FROM TRANSACOES_QUERY WHERE COD_TRANSACAO=A.COD_TRANSACAO AND CODIGO_QUERY=A.CODIGO_QUERY)




select * from TRANSACOES_QUERY
where cod_transacao='lx009019_001'
