select SUM(QTDE_EMBALADA),SUM(VALOR_EMBALADO) from VENDAS_PROD_EMBALADO
WHERE PEDIDO='45692'


UPDATE VENDAS_PROD_EMBALADO
SET VENDAS_PROD_EMBALADO.PRECO1=VENDAS_PRODUTO.PRECO1,VENDAS_PROD_EMBALADO.VALOR_EMBALADO=VENDAS_PRODUTO.PRECO1 * VENDAS_PROD_EMBALADO.QTDE_EMBALADA 
from VENDAS_PROD_EMBALADO
JOIN VENDAS_PRODUTO ON VENDAS_PRODUTO.PEDIDO=VENDAS_PROD_EMBALADO.PEDIDO 
AND VENDAS_PRODUTO.PRODUTO=VENDAS_PROD_EMBALADO.PRODUTO
AND VENDAS_PRODUTO.COR_PRODUTO=VENDAS_PROD_EMBALADO.COR_PRODUTO
WHERE VENDAS_PRODUTO.PEDIDO='45692'

