SP_SFV_BUSCA_PAIS
SP_SFV_BUSCA_UF
SP_SFV_BUSCA_REGIOES_VENDA
SP_SFV_BUSCA_MUNICIPIO_FULL
SP_SFV_DADOS_REPRESENTANTE
SP_SFV_BUSCA_REPRESENTANTE_NEW
SP_SFV_BUSCA_CLIENTES_REPRESENTANTE
SP_SFV_BUSCA_PERIODOS_FATURAMENTO
SP_SFV_BUSCA_CONDICOES_PAGAMENTO
SP_SFV_BUSCA_PRODUTOS_BARRA
SP_SFV_BUSCA_PRODUTOS_PRECOS
SP_SFV_BUSCA_PRODUTO_COR_ENTREGA_FUTURA
SP_SFV_BUSCA_PRODUTOS_FULL
SP_SFV_BUSCA_COTA_LIMITE_PERFAT
SP_SFV_BUSCA_PRODUTOS_TAMANHOS
SP_SFV_BUSCA_MATERIAL_PROMOCIONAL
SP_SFV_VENDAS_CONFIRMADOS
SP_SFV_VENDAS_PRODUTO_CONFIRMADOS




    
ALTER Procedure [dbo].[SP_SFV_BUSCA_PERIODOS_FATURAMENTO]    
as     
SET NOCOUNT ON  
  Select *     
    From PRODUTOS_PERIODOS_ENTREGAS with (nolock)     
   Where NUMERO_ENTREGA IN (Select NUMERO_ENTREGA From COTA_LIMITE_PERFAT with (nolock) Where FECHADO = 0)    
     And PERIODO_PCP IN (Select PERIODO_PCP From COTA_LIMITE_PERFAT with (nolock) Where FECHADO = 0)    
     And limite>=getdate()     
Order By limite

