SELECT ((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO) AS CAPACIDADE,
(PRODUCAO_TAREFAS_SALDO.QTDE_S/((OPERADORES.QTDE_OPERADOR*OPERADORES.MINUTOS_DISPONIVEIS)/TEMPO_PADRAO.TEMPO_CRONOMETRADO)) AS DIAS_PRODUCAO,
OPERADORES.QTDE_OPERADOR,OPERADORES.MINUTOS_DISPONIVEIS,TEMPO_PADRAO.TEMPO_CRONOMETRADO,PRODUCAO_TAREFAS.TAREFA, 
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO, PRODUCAO_TAREFAS.ORDEM_PRODUCAO, PRODUCAO_TAREFAS.FASE_PRODUCAO, 
PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, 
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO, 
PRODUCAO_TAREFAS_SALDO.QTDE_S, PRODUCAO_TAREFAS_SALDO.S1, PRODUCAO_TAREFAS_SALDO.S2, PRODUCAO_TAREFAS_SALDO.S3, 
PRODUCAO_TAREFAS_SALDO.S4, PRODUCAO_TAREFAS_SALDO.S5, PRODUCAO_TAREFAS_SALDO.S6, PRODUCAO_TAREFAS_SALDO.S7, 
PRODUCAO_TAREFAS_SALDO.S8, PRODUCAO_TAREFAS_SALDO.S9, PRODUCAO_TAREFAS_SALDO.S10, PRODUCAO_TAREFAS_SALDO.S11, 
PRODUCAO_TAREFAS_SALDO.S12, PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.PRODUTO, 
PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, 
PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, 
PRODUCAO_FASE.DESC_FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, 
dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, 
dbo.PRODUCAO_SETOR PRODUCAO_SETOR, 
dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, 
dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, 
dbo.PRODUTOS PRODUTOS,
(SELECT * FROM PRODUTO_OPERACOES_ROTAS WHERE TEMPO_CRONOMETRADO>0) AS TEMPO_PADRAO,
(SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA WHERE DESC_RECURSO like 'GRUPO%' AND CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
WHERE OPERADORES.DESC_RECURSO=PRODUCAO_RECURSOS.DESC_RECURSO AND OPERADORES.DESC_SETOR_PRODUCAO=PRODUCAO_SETOR.DESC_SETOR_PRODUCAO AND
TEMPO_PADRAO.TABELA_OPERACOES=PRODUCAO_TAREFAS_SALDO.PRODUTO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND 
((PRODUCAO_FASE.FASE_PRODUCAO='006') OR (PRODUCAO_FASE.FASE_PRODUCAO='007') OR (PRODUCAO_FASE.FASE_PRODUCAO='008') OR 
(PRODUCAO_FASE.FASE_PRODUCAO='009'))
