SELECT CAPACIDADE = CASE WHEN ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0)<>0 
                         THEN ((ISNULL(OPERADORES.QTDE_OPERADOR,0)*ISNULL(OPERADORES.MINUTOS_DISPONIVEIS,0))/ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0)) 
                         WHEN ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0)=0 
                         THEN 0 
                    END,
DIAS_PRODUCAO = CASE WHEN ISNULL(OPERADORES.QTDE_OPERADOR,0)*ISNULL(OPERADORES.MINUTOS_DISPONIVEIS,0) <> 0 AND ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0) <> 0
                     THEN ISNULL((RECEBIMENTO.QTDE_S/((ISNULL(OPERADORES.QTDE_OPERADOR,0)*ISNULL(OPERADORES.MINUTOS_DISPONIVEIS,0))/ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0))),0)
                     WHEN ISNULL(OPERADORES.QTDE_OPERADOR,0)*ISNULL(OPERADORES.MINUTOS_DISPONIVEIS,0) = 0 AND ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0) = 0
                     THEN 0
                     ELSE 0
                END,
QTDE_OPERADOR=ISNULL(OPERADORES.QTDE_OPERADOR,0),MINUTOS_DISPONIVEIS=ISNULL(OPERADORES.MINUTOS_DISPONIVEIS,0),TEMPO_CRONOMETRADO=ISNULL(TEMPO_PADRAO.TEMPO_CRONOMETRADO,0),
RECEBIMENTO.PRODUTO,RECEBIMENTO.COR_PRODUTO,RECEBIMENTO.ORDEM_PRODUCAO,
RECEBIMENTO.RECURSO_PRODUTIVO,RECEBIMENTO.DESC_SETOR_PRODUCAO,DOC_FASE=RECEBIMENTO.FASE_PRODUCAO,OFICINA=COSTURA.DESC_SETOR_PRODUCAO,GRUPO=COSTURA.RECURSO_PRODUTIVO,RECEBIMENTO.QTDE_S,RECEBIMENTO.GRADE,RECEBIMENTO.TAMANHO 
FROM (

SELECT  PRODUCAO_TAREFAS.QTDE_EM_PROCESSO, PRODUCAO_TAREFAS_SALDO.TAREFA, PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, 
PRODUCAO_TAREFAS_SALDO.PRODUTO, PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,  
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO, PRODUCAO_RECURSOS.DESC_RECURSO, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO, 
PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, PRODUTOS.LINHA, PRODUTOS.GRIFFE, PRODUCAO_SETOR.SETOR_PRODUCAO, 
PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO,
PRODUTOS_BARRA.GRADE,PRODUTOS_BARRA.TAMANHO,
QTDE_S = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN PRODUCAO_TAREFAS_SALDO.S1 
               WHEN PRODUTOS_BARRA.tamanho='2'  THEN PRODUCAO_TAREFAS_SALDO.S2 
               WHEN PRODUTOS_BARRA.tamanho='3'  THEN PRODUCAO_TAREFAS_SALDO.S3 
               WHEN PRODUTOS_BARRA.tamanho='4'  THEN PRODUCAO_TAREFAS_SALDO.S4 
               WHEN PRODUTOS_BARRA.tamanho='5'  THEN PRODUCAO_TAREFAS_SALDO.S5 
               WHEN PRODUTOS_BARRA.tamanho='6'  THEN PRODUCAO_TAREFAS_SALDO.S6 
               WHEN PRODUTOS_BARRA.tamanho='7'  THEN PRODUCAO_TAREFAS_SALDO.S7 
               WHEN PRODUTOS_BARRA.tamanho='8'  THEN PRODUCAO_TAREFAS_SALDO.S8 
               WHEN PRODUTOS_BARRA.tamanho='9'  THEN PRODUCAO_TAREFAS_SALDO.S9 
               WHEN PRODUTOS_BARRA.tamanho='10' THEN PRODUCAO_TAREFAS_SALDO.S10 
               WHEN PRODUTOS_BARRA.tamanho='11' THEN PRODUCAO_TAREFAS_SALDO.S11 
               WHEN PRODUTOS_BARRA.tamanho='12' THEN PRODUCAO_TAREFAS_SALDO.S12 
               WHEN PRODUTOS_BARRA.tamanho='13' THEN PRODUCAO_TAREFAS_SALDO.S13 
               WHEN PRODUTOS_BARRA.tamanho='14' THEN PRODUCAO_TAREFAS_SALDO.S14 
               WHEN PRODUTOS_BARRA.tamanho='15' THEN PRODUCAO_TAREFAS_SALDO.S15 
               WHEN PRODUTOS_BARRA.tamanho='16' THEN PRODUCAO_TAREFAS_SALDO.S16 
           END)
           
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, dbo.PRODUCAO_SETOR PRODUCAO_SETOR, dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, dbo.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO, dbo.PRODUTOS PRODUTOS, DBO.PRODUTOS_BARRA PRODUTOS_BARRA, DBO.PRODUCAO_ORDEM PRODUCAO_ORDEM
WHERE PRODUCAO_TAREFAS_SALDO.PRODUTO=PRODUTOS_BARRA.PRODUTO AND 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_ORDEM.ORDEM_PRODUCAO AND 
PRODUCAO_TAREFAS_SALDO.PRODUTO = PRODUTOS.PRODUTO AND PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND 
PRODUCAO_FASE.FASE_PRODUCAO IN('001','002','003','004','54','005','006','006.1','007','00','26','57','103','20','30','40','50','500','60','699','700','70','100') AND PRODUCAO_ORDEM.FILIAL in('DR VAREJO','D.R. LINGERIE')

) AS RECEBIMENTO

LEFT JOIN (
 
SELECT PRODUTOS.PRODUTO,PRODUCAO_TAREFAS.ORDEM_PRODUCAO,PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,PRODUCAO_RECURSOS.DESC_RECURSO,
PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_FASE.DESC_FASE_PRODUCAO, PRODUCAO_FASE.FASE_PRODUCAO
FROM dbo.PRODUCAO_FASE PRODUCAO_FASE, dbo.PRODUCAO_RECURSOS PRODUCAO_RECURSOS, dbo.PRODUCAO_SETOR PRODUCAO_SETOR, dbo.PRODUCAO_TAREFAS PRODUCAO_TAREFAS, dbo.PRODUTOS PRODUTOS, dbo.PRODUCAO_ORDEM
WHERE PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO AND 
PRODUCAO_RECURSOS.RECURSO_PRODUTIVO = PRODUCAO_TAREFAS.RECURSO_PRODUTIVO AND 
PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO AND 
PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO AND 
PRODUCAO_ORDEM.PRODUTO=PRODUTOS.PRODUTO AND
PRODUCAO_ORDEM.ORDEM_PRODUCAO=PRODUCAO_TAREFAS.ORDEM_PRODUCAO AND 
PRODUCAO_FASE.FASE_PRODUCAO IN('007') AND PRODUCAO_ORDEM.FILIAL IN ('DR VAREJO','D.R. LINGERIE')

 ) AS COSTURA

ON RECEBIMENTO.PRODUTO=COSTURA.PRODUTO AND RECEBIMENTO.ORDEM_PRODUCAO=COSTURA.ORDEM_PRODUCAO

LEFT JOIN (SELECT PRODUTO_OPERACOES_ROTAS.TABELA_OPERACOES,SUM(TEMPO_CRONOMETRADO) AS TEMPO_CRONOMETRADO FROM PRODUTO_OPERACOES_ROTAS WHERE TEMPO_CRONOMETRADO>0 GROUP BY TABELA_OPERACOES) AS TEMPO_PADRAO
ON TEMPO_PADRAO.TABELA_OPERACOES=RECEBIMENTO.PRODUTO

LEFT JOIN (SELECT * FROM LDR_METAS_OFICINA_GRUPO_NOVA WHERE (DESC_RECURSO like 'GRUPO%' OR DESC_RECURSO like 'EQUIPE%') AND  CONVERT(CHAR(10),DATA_PRODUCAO,103) = CONVERT(CHAR(10),GETDATE(),103)) AS OPERADORES
ON OPERADORES.DESC_RECURSO=COSTURA.DESC_RECURSO AND OPERADORES.DESC_SETOR_PRODUCAO=COSTURA.DESC_SETOR_PRODUCAO

WHERE RECEBIMENTO.QTDE_S>0 AND RECEBIMENTO.RECURSO_PRODUTIVO='EFC01'
ORDER BY RECEBIMENTO.ORDEM_PRODUCAO