
SELECT VENDAS_PRODUTO.PRODUTO,VENDAS_PRODUTO.COR_PRODUTO,ESTOQUE_PRODUTOS.ESTOQUE,QTDE=SUM(QTDE_ORIGINAL) FROM VENDAS_PRODUTO
JOIN VENDAS ON VENDAS.PEDIDO=VENDAS_PRODUTO.PEDIDO
JOIN PRODUTOS ON PRODUTOS.PRODUTO=VENDAS_PRODUTO.PRODUTO
JOIN PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=VENDAS_PRODUTO.PRODUTO AND PRODUTO_CORES.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO 
JOIN ESTOQUE_PRODUTOS ON ESTOQUE_PRODUTOS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND ESTOQUE_PRODUTOS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO AND ESTOQUE_PRODUTOS.FILIAL='DR VAREJO'
WHERE PRODUTOS.COD_CATEGORIA='01' AND PRODUTO_CORES.DESC_COR_PRODUTO NOT LIKE '%-FL' AND VENDAS.EMISSAO BETWEEN '20130701' AND '20140131' 
GROUP BY VENDAS_PRODUTO.PRODUTO,VENDAS_PRODUTO.COR_PRODUTO,ESTOQUE_PRODUTOS.ESTOQUE
ORDER BY VENDAS_PRODUTO.PRODUTO


