SELECT * FROM PRODUCAO_PROGRAMA
where PROGRAMACAO like '%CENARIO%'

SELECT a.MATERIAL,a.COR_MATERIAL,a.PROGRAMACAO,a.NECESSIDADE_PROG, a.QTDE_INSERCOES,a.ENTREGA_INICIAL 
FROM W_materiais_explosao_02 a 
where  a.PROGRAMACAO IN ('CENARIO 3 NOVEMBRO') 


SELECT a.MATERIAL,a.COR_MATERIAL,a.PROGRAMACAO,a.NECESSIDADE_PROG,B.DESC_MATERIAL,B.UNID_ESTOQUE
FROM W_materiais_explosao_02 a WITH (NOLOCK) 
JOIN MATERIAIS B WITH (NOLOCK) ON B.MATERIAL = A.MATERIAL
JOIN MATERIAIS_CORES C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL AND C.COR_MATERIAL=A.COR_MATERIAL
where  a.PROGRAMACAO LIKE 'CENARIO 3 NOVEMBRO'

SELECT a.MATERIAL,a.COR_MATERIAL,a.PROGRAMACAO,a.NECESSIDADE_PROG,B.DESC_MATERIAL,B.UNID_ESTOQUE
FROM W_materiais_explosao_02 a WITH (NOLOCK) 
JOIN MATERIAIS B WITH (NOLOCK) ON B.MATERIAL = A.MATERIAL
JOIN MATERIAIS_CORES C WITH (NOLOCK) ON C.MATERIAL=A.MATERIAL AND C.COR_MATERIAL=A.COR_MATERIAL
where  a.PROGRAMACAO LIKE 'CENARIO%'


exec sp_executesql N'
/* VISUALLINX Execute(Alias:xCur_Temp)  */
SELECT a.MATERIAL,a.COR_MATERIAL,a.PROGRAMACAO,a.NECESSIDADE_PROG, a.QTDE_INSERCOES,a.ENTREGA_INICIAL FROM W_materiais_explosao_02 a where  a.PROGRAMACAO IN (''CENARIO 3 NOVEMBRO'') AND a.material = @P1  and a.cor_material = @P2',N'@P1 varchar(10),@P2 varchar(3)','70.35.0006','001'


exec sp_executesql N'
/* VISUALLINX Execute(Alias:xCur_Temp)  */
SELECT a.MATERIAL,a.COR_MATERIAL,a.PROGRAMACAO,a.NECESSIDADE_PROG, a.QTDE_INSERCOES,a.ENTREGA_INICIAL FROM W_materiais_explosao_02 a where  a.PROGRAMACAO IN (''CENARIO 3 NOVEMBRO'') AND a.material = @P1  and a.cor_material = @P2',N'@P1 varchar(10),@P2 varchar(3)','70.21.0001','999'


