SELECT ENTRADA_ESTOQUE.EMISSAO,PROGRAMACAO.GRADE,PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16, 
EN_1=ISNULL(ENTRADA_ESTOQUE.EN_1,0),EN_2=ISNULL(ENTRADA_ESTOQUE.EN_2,0),EN_3=ISNULL(ENTRADA_ESTOQUE.EN_3,0),EN_4=ISNULL(ENTRADA_ESTOQUE.EN_4,0),EN_5=ISNULL(ENTRADA_ESTOQUE.EN_5,0), 
EN_6=ISNULL(ENTRADA_ESTOQUE.EN_6,0),EN_7=ISNULL(ENTRADA_ESTOQUE.EN_7,0),EN_8=ISNULL(ENTRADA_ESTOQUE.EN_8,0),EN_9=ISNULL(ENTRADA_ESTOQUE.EN_9,0),EN_10=ISNULL(ENTRADA_ESTOQUE.EN_10,0), 
EN_11=ISNULL(ENTRADA_ESTOQUE.EN_11,0),EN_12=ISNULL(ENTRADA_ESTOQUE.EN_12,0),EN_13=ISNULL(ENTRADA_ESTOQUE.EN_13,0),EN_14=ISNULL(ENTRADA_ESTOQUE.EN_14,0),EN_15=ISNULL(ENTRADA_ESTOQUE.EN_15,0), 
EN_16=ISNULL(ENTRADA_ESTOQUE.EN_16,0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7,
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO,
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART JULHO 16 07 12'
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
ESTOQUE_PROD1_ENT.COR_PRODUTO, QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE), EN_1=SUM(ESTOQUE_PROD1_ENT.EN_1), EN_2=SUM(ESTOQUE_PROD1_ENT.EN_2), 
EN_3=SUM(ESTOQUE_PROD1_ENT.EN_3), EN_4=SUM(ESTOQUE_PROD1_ENT.EN_4), EN_5=SUM(ESTOQUE_PROD1_ENT.EN_5), EN_6=SUM(ESTOQUE_PROD1_ENT.EN_6), 
EN_7=SUM(ESTOQUE_PROD1_ENT.EN_7), EN_8=SUM(ESTOQUE_PROD1_ENT.EN_8), EN_9=SUM(ESTOQUE_PROD1_ENT.EN_9), EN_10=SUM(ESTOQUE_PROD1_ENT.EN_10), 
EN_11=SUM(ESTOQUE_PROD1_ENT.EN_11), EN_12=SUM(ESTOQUE_PROD1_ENT.EN_12), EN_13=SUM(ESTOQUE_PROD1_ENT.EN_13), EN_14=SUM(ESTOQUE_PROD1_ENT.EN_14), 
EN_15=SUM(ESTOQUE_PROD1_ENT.EN_15), EN_16=SUM(ESTOQUE_PROD1_ENT.EN_16) 
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS, 
DBO.PRODUTO_CORES PRODUTO_CORES  
WHERE ESTOQUE_PROD_ENT.EMISSAO >= '20120719' AND 
ESTOQUE_PROD_ENT.EMISSAO <= '20120724' AND 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTO_CORES.PRODUTO AND 
ESTOQUE_PROD1_ENT.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, PRODUTOS.GRADE, ESTOQUE_PROD1_ENT.PRODUTO, ESTOQUE_PROD1_ENT.COR_PRODUTO 
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO AND ENTRADA_ESTOQUE.COR_PRODUTO=PROGRAMACAO.COR_PRODUTO 
ORDER BY PROGRAMACAO.PRODUTO,PROGRAMACAO.COR_PRODUTO,ENTRADA_ESTOQUE.EMISSAO


-- COM GRADE
SELECT PRODUTOS.PRODUTO,
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
PRODUTOS_BARRA.TAMANHO, 
PROGRAMADA =   (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN PRODUCAO_PROG_PROD.P1
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN PRODUCAO_PROG_PROD.P2
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN PRODUCAO_PROG_PROD.P3
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN PRODUCAO_PROG_PROD.P4
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN PRODUCAO_PROG_PROD.P5
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN PRODUCAO_PROG_PROD.P6
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN PRODUCAO_PROG_PROD.P7
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN PRODUCAO_PROG_PROD.P8
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN PRODUCAO_PROG_PROD.P9
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN PRODUCAO_PROG_PROD.P10
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN PRODUCAO_PROG_PROD.P11
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN PRODUCAO_PROG_PROD.P12
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN PRODUCAO_PROG_PROD.P13
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN PRODUCAO_PROG_PROD.P14
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN PRODUCAO_PROG_PROD.P15
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN PRODUCAO_PROG_PROD.P16
                     END),
DIA_19 = ISNULL(DBO.QTDE_TAMANHO_EE(PRODUTOS_BARRA.PRODUTO,PRODUTOS_BARRA.COR_PRODUTO,PRODUTOS_BARRA.TAMANHO,'20120719','20120719'),0)                     
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
JOIN (
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7,
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA, 
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO,
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND  
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART JULHO 16 07 12'
) AS PRODUCAO_PROG_PROD ON PRODUCAO_PROG_PROD.PRODUTO=PRODUTOS_BARRA.PRODUTO AND PRODUCAO_PROG_PROD.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART JULHO 16 07 12'



