SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.ORDEM_PRODUCAO, PRODUCAO_PROG_PROD.SOBRA_DE_PRODUTO, PRODUCAO_PROG_PROD.SORTIMENTO_COR, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO, 
PRODUCAO_PROG_PROD.COR_PRODUTO, PRODUCAO_PROG_PROD.ENTREGA_INICIAL, PRODUTO_CORES.DESC_COR_PRODUTO, PRODUCAO_PROG_PROD.QTDE_PROGRAMADA, PRODUTOS.GRADE, PRODUTOS.MODELAGEM, SPACE(9) AS PACK_QTDE, 
PRODUCAO_PROG_PROD.QTDE_GERADA, PRODUCAO_PROG_PROD.P1, PRODUCAO_PROG_PROD.P2, PRODUCAO_PROG_PROD.P3, PRODUCAO_PROG_PROD.P4, PRODUCAO_PROG_PROD.P5, PRODUCAO_PROG_PROD.P6, PRODUCAO_PROG_PROD.P7, 
PRODUCAO_PROG_PROD.P8, PRODUCAO_PROG_PROD.P9, PRODUCAO_PROG_PROD.P10, PRODUCAO_PROG_PROD.P11, PRODUCAO_PROG_PROD.P12, PRODUCAO_PROG_PROD.P13, PRODUCAO_PROG_PROD.P14, PRODUCAO_PROG_PROD.P15, 
PRODUCAO_PROG_PROD.P16, PRODUCAO_PROG_PROD.QTDE_SALDO_EMITIR_OP, 
PRODUCAO_PROG_PROD.S1, PRODUCAO_PROG_PROD.S2, PRODUCAO_PROG_PROD.S3, PRODUCAO_PROG_PROD.S4, PRODUCAO_PROG_PROD.S5, PRODUCAO_PROG_PROD.S6, PRODUCAO_PROG_PROD.S7, PRODUCAO_PROG_PROD.S8, 
PRODUCAO_PROG_PROD.S9, PRODUCAO_PROG_PROD.S10, PRODUCAO_PROG_PROD.S11, PRODUCAO_PROG_PROD.S12, PRODUCAO_PROG_PROD.S13, PRODUCAO_PROG_PROD.S14, PRODUCAO_PROG_PROD.S15, PRODUCAO_PROG_PROD.S16, 
PRODUCAO_PROG_PROD.QTDE_MINIMA_PRODUZIR, PRODUCAO_PROG_PROD.AUMENTO_VENDAS, PRODUCAO_PROG_PROD.ENTREGA_FINAL, PRODUTOS.GRUPO_PRODUTO, PRODUCAO_PROG_PROD.COR_SORTIDA, PRODUTOS.GIRO_ENTREGA,
PRODUTOS.REVENDA, PRODUTOS.SORTIMENTO_COR AS INDICA_SORTIMENTO,PRODUCAO_PROGRAMA.TIPO_PROGRAMACAO, PRODUTOS.SUBGRUPO_PRODUTO, 
PRODUTOS.PERIODO_PCP, PRODUTO_CORES.MATERIAL, PRODUTO_CORES.COR_MATERIAL, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO, PRODUCAO_PROG_PROD.QTDE_EM_OP, PRODUTO_CORES.COR, PRODUCAO_PROGRAMA.PEDIDO, 
PRODUCAO_PROGRAMA.CLIENTE_ATACADO, PRODUTOS.FABRICANTE AS FORNECEDOR, PRODUCAO_PROG_PROD.MATAR_SALDO_PROGRAMACAO AS TEM_MATERIAL FROM  PRODUTOS PRODUTOS, PRODUTO_CORES PRODUTO_CORES, 
PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (((PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO AND  PRODUCAO_PROG_PROD.PRODUTO = PRODUTO_CORES.PRODUTO ) AND 
PRODUCAO_PROG_PROD.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO ) AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND 
PRODUCAO_PROG_PROD.PROGRAMACAO = 'FURO 31/10 EM 26/10'

-------

SELECT 
PROGRAMACAO,
PRODUTO,
DIA01=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '01' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA02=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0)
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '02' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA03=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0)
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '03' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA04=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '04' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA05=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '05' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA06=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '06' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA07=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '07' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA08=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '08' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA09=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '09' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA10=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '10' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA11=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '11' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA12=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '12' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA13=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '13' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA14=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '14' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA15=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '15' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA16=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '16' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA17=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '17' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA18=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '18' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA19=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '19' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA20=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '20' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA21=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '21' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA22=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '22' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA23=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '23' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA24=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '24' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA25=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '25' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA26=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '26' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA27=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '27' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA28=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '28' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA29=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '29' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA30=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '30' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
,
DIA31=
(
SELECT ISNULL(SUM(ENTRADA_ESTOQUE.QTDE),0) 
FROM 
(
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 
LEFT JOIN ( 
SELECT ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO,  
QTDE=SUM(ESTOQUE_PROD1_ENT.QTDE)
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT, 
DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD1_ENT.PRODUTO=PROGRAMACAO.PRODUTO AND DAY(ESTOQUE_PROD_ENT.EMISSAO) = '31' AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO, ESTOQUE_PROD1_ENT.PRODUTO
) AS ENTRADA_ESTOQUE ON ENTRADA_ESTOQUE.PRODUTO=PROGRAMACAO.PRODUTO
)
FROM (
SELECT PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO,QTDE_PROGRAMADA=SUM(PRODUCAO_PROG_PROD.QTDE_PROGRAMADA)
FROM  PRODUTOS PRODUTOS, PRODUCAO_PROG_PROD PRODUCAO_PROG_PROD, DBO.PRODUCAO_PROGRAMA PRODUCAO_PROGRAMA 
WHERE (PRODUCAO_PROG_PROD.PRODUTO = PRODUTOS.PRODUTO  AND  PRODUCAO_PROGRAMA.PROGRAMACAO = PRODUCAO_PROG_PROD.PROGRAMACAO ) AND  
PRODUCAO_PROG_PROD.PROGRAMACAO = 'NEC CART MARÇO 12 03 12 M'
GROUP BY PRODUCAO_PROG_PROD.PROGRAMACAO, PRODUCAO_PROG_PROD.PRODUTO, PRODUTOS.DESC_PRODUTO
) AS PROGRAMACAO 


SELECT ESTOQUE_PROD_ENT.EMISSAO  
FROM DBO.ESTOQUE_PROD1_ENT ESTOQUE_PROD1_ENT,DBO.ESTOQUE_PROD_ENT ESTOQUE_PROD_ENT, DBO.PRODUTOS PRODUTOS 
WHERE ESTOQUE_PROD_ENT.EMISSAO >= '20131001' and ESTOQUE_PROD_ENT.EMISSAO <= GETDATE() AND estoque_prod_ent.ordem_producao is not null and 
ESTOQUE_PROD1_ENT.FILIAL = 'DR VAREJO' AND  
ESTOQUE_PROD_ENT.ROMANEIO_PRODUTO = ESTOQUE_PROD1_ENT.ROMANEIO_PRODUTO AND 
ESTOQUE_PROD_ENT.FILIAL = ESTOQUE_PROD1_ENT.FILIAL AND 
ESTOQUE_PROD1_ENT.PRODUTO = PRODUTOS.PRODUTO 
GROUP BY ESTOQUE_PROD_ENT.EMISSAO
