SELECT 
A.REGIAO,
C.RAZAO_SOCIAL,
QTDE_ATIVOS=(SELECT COUNT(*) FROM CLIENTES_ATACADO WITH (NOLOCK) WHERE REGIAO=A.REGIAO and INATIVO=0 AND TIPO<>'BALCONISTA'),
QTDE_FAT_ULT_12MESES=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE EMISSAO BETWEEN (GETDATE()-365) AND GETDATE() AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL),
QTDE_FAT_ANO_CORRENTE=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE YEAR(EMISSAO) = YEAR(GETDATE()) AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL)
FROM CLIENTES_ATACADO A WITH (NOLOCK)
left JOIN REPRESENTANTES B ON B.REGIAO=A.REGIAO
JOIN CADASTRO_CLI_FOR C ON C.COD_CLIFOR=B.CLIFOR
JOIN (SELECT DISTINCT REPRESENTANTE FROM CLIENTE_REPRE WHERE REPRESENTANTE_PRINCIPAL=1) D ON d.REPRESENTANTE=b.REPRESENTANTE
WHERE A.REGIAO LIKE 'RV-01 ZN-01%' AND A.INATIVO=0 AND B.INATIVO=0 AND C.INATIVO=0
GROUP BY A.REGIAO,C.RAZAO_SOCIAL
order by a.REGIAO

--- FINAL
SELECT 
A.REGIAO,
RAZAO_SOCIAL=(SELECT TOP 1 DD.REPRESENTANTE FROM CADASTRO_CLI_FOR AA WITH (NOLOCK) JOIN CLIENTES_ATACADO BB WITH (NOLOCK) ON BB.CLIENTE_ATACADO=AA.NOME_CLIFOR JOIN CLIENTE_REPRE CC WITH (NOLOCK) ON CC.CLIENTE_ATACADO=BB.CLIENTE_ATACADO JOIN REPRESENTANTES DD WITH (NOLOCK) ON DD.REPRESENTANTE=CC.REPRESENTANTE WHERE BB.REGIAO=A.REGIAO AND CC.REPRESENTANTE_PRINCIPAL=1 AND DD.REPRESENTANTE NOT LIKE '%VENDA%'),
QTDE_ATIVOS=(SELECT COUNT(*) FROM CLIENTES_ATACADO WITH (NOLOCK) WHERE REGIAO=A.REGIAO and INATIVO=0 AND TIPO<>'BALCONISTA'),
QTDE_FAT_ULT_12MESES=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE EMISSAO BETWEEN (GETDATE()-365) AND GETDATE() AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL),
QTDE_FAT_ANO_CORRENTE=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE YEAR(EMISSAO) = YEAR(GETDATE()) AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL)
FROM CLIENTES_ATACADO A WITH (NOLOCK)
left JOIN REPRESENTANTES B ON B.REGIAO=A.REGIAO
WHERE A.REGIAO LIKE 'RV-01 ZN-01%'
GROUP BY A.REGIAO
order by a.REGIAO


SELECT TOP 1 DD.REPRESENTANTE FROM CADASTRO_CLI_FOR AA WITH (NOLOCK) 
JOIN CLIENTES_ATACADO BB WITH (NOLOCK) ON BB.CLIENTE_ATACADO=AA.NOME_CLIFOR 
JOIN CLIENTE_REPRE CC WITH (NOLOCK) ON CC.CLIENTE_ATACADO=BB.CLIENTE_ATACADO
JOIN REPRESENTANTES DD WITH (NOLOCK) ON DD.REPRESENTANTE=CC.REPRESENTANTE
WHERE BB.REGIAO='RV-01 ZN-01 ST-11' AND CC.REPRESENTANTE_PRINCIPAL=1 AND DD.REPRESENTANTE NOT LIKE '%VENDA%'


SELECT 
A.REGIAO,
--C.RAZAO_SOCIAL,
QTDE_ATIVOS=(SELECT COUNT(*) FROM CLIENTES_ATACADO WITH (NOLOCK) WHERE REGIAO=A.REGIAO and INATIVO=0 AND TIPO<>'BALCONISTA'),
QTDE_FAT_ULT_12MESES=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE EMISSAO BETWEEN (GETDATE()-365) AND GETDATE() AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL),
QTDE_FAT_ANO_CORRENTE=(SELECT COUNT(*) FROM (SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA WITH (NOLOCK) JOIN CLIENTES_ATACADO B WITH (NOLOCK) ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR WHERE YEAR(EMISSAO) = YEAR(GETDATE()) AND B.REGIAO=A.REGIAO AND TIPO<>'BALCONISTA' GROUP BY NOME_CLIFOR) AS FINAL)
FROM CLIENTES_ATACADO A WITH (NOLOCK)
left JOIN REPRESENTANTES B ON B.REGIAO=A.REGIAO
--JOIN CADASTRO_CLI_FOR C ON C.COD_CLIFOR=B.CLIFOR
--JOIN (SELECT DISTINCT REPRESENTANTE FROM CLIENTE_REPRE WHERE REPRESENTANTE_PRINCIPAL=1) D ON d.REPRESENTANTE=b.REPRESENTANTE
WHERE A.REGIAO LIKE 'RV-01 ZN-01%' --AND A.INATIVO=0 AND B.INATIVO=0-- AND C.INATIVO=0
GROUP BY A.REGIAO--,C.RAZAO_SOCIAL
order by a.REGIAO

SELECT * FROM CLIENTES_ATACADO
WHERE REGIAO LIKE 'RV-01'

SELECT * FROM REPRESENTANTES
WHERE REGIAO LIKE 'RV-01 ZN-01 ST-20'




SELECT COUNT(*) FROM (
SELECT DISTINCT NOME_CLIFOR FROM FATURAMENTO AA
JOIN CLIENTES_ATACADO B ON B.CLIENTE_ATACADO=AA.NOME_CLIFOR
WHERE YEAR(EMISSAO) = YEAR(GETDATE()) AND B.REGIAO='RV-01 ZN-01 ST-01'
GROUP BY NOME_CLIFOR
) AS FINAL
