--- DENI RICARDO
SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM CLIENTES_ATACADO WITH (NOLOCK)
     JOIN CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-07%' OR CLIENTES_ATACADO.REGIAO LIKE 'RV-02%' )
UNION ALL
SELECT UF,CIDADE,ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR,RAZAO_SOCIAL,CGC_CPF,ENDERECO,CEP,CONTATO,BAIRRO,DDD1,TELEFONE1,TELEFONE2,PAIS,DDI,FAX,RAMAL1,RAMAL2      
FROM OPENQUERY(LDR, 'SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM DRVAREJO.DBO.CLIENTES_ATACADO WITH (NOLOCK) 
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-07%'' OR CLIENTES_ATACADO.REGIAO LIKE ''RV-02%'' )')      



--- MARCUS CARIOCA
SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM CLIENTES_ATACADO 
     JOIN CADASTRO_CLI_FOR ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-09%')

UNION ALL

SELECT UF,CIDADE,ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR,RAZAO_SOCIAL,CGC_CPF,ENDERECO,CEP,CONTATO,BAIRRO,DDD1,TELEFONE1,TELEFONE2,PAIS,DDI,FAX,RAMAL1,RAMAL2      
FROM OPENQUERY(LDR, 'SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM DRVAREJO.DBO.CLIENTES_ATACADO 
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-09%'')')
            


--- JOSE MARIO
SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM CLIENTES_ATACADO WITH (NOLOCK)
     JOIN CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-02%' OR CLIENTES_ATACADO.REGIAO LIKE 'RV-08%')

UNION ALL                  

SELECT UF,CIDADE,ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR,RAZAO_SOCIAL,CGC_CPF,ENDERECO,CEP,CONTATO,BAIRRO,DDD1,TELEFONE1,TELEFONE2,PAIS,DDI,FAX,RAMAL1,RAMAL2      
FROM OPENQUERY(LDR, 'SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM DRVAREJO.DBO.CLIENTES_ATACADO WITH (NOLOCK)
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-02%'' OR CLIENTES_ATACADO.REGIAO LIKE ''RV-08%'')')
      


--- sergio pires
SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM CLIENTES_ATACADO with (nolock)
     JOIN CADASTRO_CLI_FOR with (nolock) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-01%')

UNION ALL      

SELECT UF,CIDADE,ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR,RAZAO_SOCIAL,CGC_CPF,ENDERECO,CEP,CONTATO,BAIRRO,DDD1,TELEFONE1,TELEFONE2,PAIS,DDI,FAX,RAMAL1,RAMAL2      
FROM OPENQUERY(LDR, 'SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM DRVAREJO.DBO.CLIENTES_ATACADO with (nolock)
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR with (nolock) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-01%'')')



--- sarmento
SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM CLIENTES_ATACADO WITH (NOLOCK) 
     JOIN CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-04%')

UNION ALL

SELECT UF,CIDADE,ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR,RAZAO_SOCIAL,CGC_CPF,ENDERECO,CEP,CONTATO,BAIRRO,DDD1,TELEFONE1,TELEFONE2,PAIS,DDI,FAX,RAMAL1,RAMAL2      
FROM OPENQUERY(LDR, 'SELECT CADASTRO_CLI_FOR.UF,       
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    
       QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.CONTATO,
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2
FROM DRVAREJO.DBO.CLIENTES_ATACADO WITH (NOLOCK) 
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR WITH (NOLOCK) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-04%'')')


---- faturamento
---- marcus carioca

SELECT ULTIMO_FATURAMENTO=DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    QTDE_ULTIMO_FATURAMENTO=DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.ENDERECO, 
       RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.UF, 
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2, 
       CADASTRO_CLI_FOR.CONTATO
FROM CLIENTES_ATACADO with (nolock)
     JOIN CADASTRO_CLI_FOR with (nolock) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = '0' AND CLIENTES_ATACADO.INATIVO = '0') 
      AND (CLIENTES_ATACADO.REGIAO LIKE 'RV-09%')

UNION ALL

SELECT ULTIMO_FATURAMENTO,QTDE_ULTIMO_FATURAMENTO,REGIAO,CLIFOR, 
RAZAO_SOCIAL,CGC_CPF,CEP,ENDERECO,CIDADE,BAIRRO,UF,TELEFONE1,PAIS, 
DDI,TELEFONE2,FAX,DDD1,RAMAL1,RAMAL2,CONTATO 
FROM OPENQUERY(LDR,'SELECT ULTIMO_FATURAMENTO=DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR),    QTDE_ULTIMO_FATURAMENTO=DRVAREJO.DBO.QTDE_ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR,DRVAREJO.DBO.ULT_FATURAMENTO(CADASTRO_CLI_FOR.NOME_CLIFOR)),
       REGIAO=RTRIM(CLIENTES_ATACADO.REGIAO) ,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CIDADE=RTRIM(CADASTRO_CLI_FOR.CIDADE) , 
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.UF, 
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.DDD1,     
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2, 
       CADASTRO_CLI_FOR.CONTATO
FROM DRVAREJO.DBO.CLIENTES_ATACADO with (nolock)
     JOIN DRVAREJO.DBO.CADASTRO_CLI_FOR with (nolock) ON CLIENTES_ATACADO.CLIENTE_ATACADO = CADASTRO_CLI_FOR.NOME_CLIFOR 
WHERE (CADASTRO_CLI_FOR.INATIVO = ''0'' AND CLIENTES_ATACADO.INATIVO = ''0'') 
      AND (CLIENTES_ATACADO.REGIAO LIKE ''RV-09%'')')
      