--- SELEÇÃO DE QTDE FATURADOS X ORIGINAL
SELECT * FROM (
-- PEDIDOS FATURADOS
SELECT A.PEDIDO,QTDE_FAT=SUM(A.QTDE)
FROM FATURAMENTO_PROD A
JOIN FATURAMENTO B ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND A.FILIAL=B.FILIAL
WHERE B.EMISSAO BETWEEN '20130101' AND '20130330'
GROUP BY A.PEDIDO
) AS FATURADO 
LEFT JOIN (
-- PEDIDOS 
SELECT A.PEDIDO,QTDE_ORIGINAL=SUM(A.QTDE_ORIGINAL),QTDE_ENTREGAR=SUM(A.QTDE_ENTREGAR)
FROM VENDAS_PRODUTO A
GROUP BY A.PEDIDO ) AS PEDIDOS ON FATURADO.PEDIDO = PEDIDOS.PEDIDO
WHERE QTDE_FAT>QTDE_ORIGINAL



--- SELEÇÃO DE QTDE FATURADOS X ORIGINAL
SELECT * FROM (
-- PEDIDOS FATURADOS
SELECT A.PEDIDO,QTDE_FAT=SUM(A.QTDE)
FROM FATURAMENTO_PROD A
JOIN FATURAMENTO B ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF AND A.FILIAL=B.FILIAL
WHERE a.PEDIDO='572206'
GROUP BY A.PEDIDO
) AS FATURADO 
LEFT JOIN (
-- PEDIDOS 
SELECT A.PEDIDO,QTDE_ORIGINAL=SUM(A.QTDE_ORIGINAL),QTDE_ENTREGAR=SUM(A.QTDE_ENTREGAR)
FROM VENDAS_PRODUTO A
GROUP BY A.PEDIDO ) AS PEDIDOS ON FATURADO.PEDIDO = PEDIDOS.PEDIDO
WHERE (QTDE_ORIGINAL-QTDE_FAT)<>QTDE_ENTREGAR AND QTDE_ENTREGAR>0   ---(QTDE_ENTREGAR >= QTDE_FAT) 




/* VISUALLINX Execute(Alias:cursor_vendas)  */
select pedido from vendas where tabela_filha = 'VENDAS_PRODUTO'  and pedido >= '548535           ' and pedido <= '548535           '



/* VISUALLINX ExecuteNonQuery()  */
  lx_movimenta_vendas_pa '548535      '
  
 
sp_helptext   lx_movimenta_vendas_pa



