SELECT top 50 PRODUTOS.PRODUTO, DESC_PRODUTO, GRADE, TIPO_PRODUTO, GRUPO_PRODUTO,  SUBGRUPO_PRODUTO, PRODUTOS.COLECAO, 
LINHA,GRIFFE, REFER_FABRICANTE, MODELAGEM, FABRICANTE, CARTELA,PRODUTOS.PERIODO_PCP,TABELA_MEDIDAS, 
SUM(QTDE_ORIGINAL) AS SUM_QTDE_ORIGINAL, SUM(QTDE_ENTREGAR) AS SUM_QTDE_ENTREGAR, SUM(QTDE_ENTREGUE) AS 
SUM_QTDE_ENTREGUE,   SUM(QTDE_CANCELADA) AS SUM_QTDE_CANCELADA ,  SUM(QTDE_EMBALADA) AS SUM_QTDE_EMBALADA, 
SUM(QTDE_DEVOLVIDA) AS SUM_QTDE_DEVOLVIDA,   SUM(VALOR_ORIGINAL * VALOR_MULTIPLICAR) AS SUM_VALOR_ORIGINAL, 
SUM(VALOR_ENTREGAR * VALOR_MULTIPLICAR) AS SUM_VALOR_ENTREGAR,  SUM(VALOR_CANCELADO * VALOR_MULTIPLICAR)AS 
SUM_VALOR_CANCELADO, SUM(VALOR_DEVOLVIDO) AS SUM_VALOR_DEVOLVIDO,  SUM(ENTREGUE_MOEDA_PADRAO) AS SUM_VALOR_ENTREGUE, 
CONVERT(NUMERIC(14,2),0) AS PRECO_MEDIO,  CONVERT(NUMERIC(14,2),0) AS PORCENTAGEM_QTDE ,  CONVERT(NUMERIC(14,2),0) 
AS PORCENTAGEM_VALOR, CONVERT(NUMERIC(16, 2), SUM(CASE WHEN (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI) = 0 THEN VALOR_ORIGINAL  
ELSE (VALOR_ORIGINAL  - (VALOR_ORIGINAL  * (DESCONTO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) - (VALOR_ORIGINAL  * 
(ISNULL(DESCONTO_COND_PGTO, 0) / (TOT_VALOR_ORIGINAL + DESCONTO + ISNULL(DESCONTO_COND_PGTO, 0) - 
ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_ORIGINAL  * (ENCARGO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_ORIGINAL  * 
(ISNULL(RECARGO, 0) / (TOT_VALOR_ORIGINAL - ISNULL(RECARGO, 0) - VALOR_IPI))) + ((VALOR_ORIGINAL  * IPI) / 100)) 
* VALOR_MULTIPLICAR END)) SUM_VALOR_ORIGINAL_LIQUIDO, CONVERT(NUMERIC(16, 2), SUM(CASE WHEN (TOT_VALOR_ORIGINAL 
+ DESCONTO + ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI) = 0 THEN VALOR_ENTREGAR  
ELSE (VALOR_ENTREGAR  - (VALOR_ENTREGAR  * (DESCONTO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) - (VALOR_ENTREGAR  * 
(ISNULL(DESCONTO_COND_PGTO, 0) / (TOT_VALOR_ORIGINAL + DESCONTO + ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - 
ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_ENTREGAR  * (ENCARGO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_ENTREGAR  * 
(ISNULL(RECARGO, 0) / (TOT_VALOR_ORIGINAL - ISNULL(RECARGO, 0) - VALOR_IPI))) + ((VALOR_ENTREGAR  * IPI) / 100)) * 
VALOR_MULTIPLICAR END)) SUM_VALOR_ENTREGAR_LIQUIDO, CONVERT(NUMERIC(16, 2), SUM(CASE WHEN (TOT_VALOR_ORIGINAL + 
DESCONTO + ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI) = 0 THEN VALOR_CANCELADO 
ELSE (VALOR_CANCELADO - (VALOR_CANCELADO * (DESCONTO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) - (VALOR_CANCELADO * 
(ISNULL(DESCONTO_COND_PGTO, 0) / (TOT_VALOR_ORIGINAL + DESCONTO + ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - 
ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_CANCELADO * (ENCARGO / (TOT_VALOR_ORIGINAL + DESCONTO + 
ISNULL(DESCONTO_COND_PGTO, 0) - ENCARGO - ISNULL(RECARGO, 0) - VALOR_IPI))) + (VALOR_CANCELADO * 
(ISNULL(RECARGO, 0) / (TOT_VALOR_ORIGINAL - ISNULL(RECARGO, 0) - VALOR_IPI))) + ((VALOR_CANCELADO * IPI) / 100)) 
* VALOR_MULTIPLICAR END)) SUM_VALOR_CANCELADO_LIQUIDO, SPACE(6) AS CLIFOR, FILIAIS.EMPRESA, SUM((VENDAS_PRODUTO.IPI 
* VENDAS_PRODUTO.VALOR_ORIGINAL )/100 ) AS SUM_VALOR_IPI FROM VENDAS_PRODUTO JOIN VENDAS ON 
VENDAS_PRODUTO.PEDIDO = VENDAS.PEDIDO JOIN PRODUTOS ON VENDAS_PRODUTO.PRODUTO = PRODUTOS.PRODUTO JOIN 
W_MOEDAS_CONVERSAO ON VENDAS.MOEDA = W_MOEDAS_CONVERSAO.MOEDA JOIN FILIAIS ON VENDAS.FILIAL = FILIAIS.FILIAL  
WHERE vendas.Emissao >= '20120101' AND vendas.Emissao <= '20121231' and  vendas.aprovacao='A' 
GROUP BY VENDAS_PRODUTO.PRODUTO , PRODUTOS.PRODUTO,DESC_PRODUTO,GRADE, TIPO_PRODUTO, GRUPO_PRODUTO,  
SUBGRUPO_PRODUTO, PRODUTOS.COLECAO,LINHA,   GRIFFE, REFER_FABRICANTE, MODELAGEM,  FABRICANTE  , 
CARTELA,PRODUTOS.PERIODO_PCP,TABELA_MEDIDAS, FILIAIS.EMPRESA
order by SUM_QTDE_ORIGINAL desc