--- RESOLVE PROBLEMA DE ARREDONDAMENTO EM ALGUMAS NFE 
--- Rejeicao: Valor do ICMS difere do produto BC e Aliquota
---
SELECT VALOR_IMPOSTO,VALOR_IMPOSTO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,VALOR_IMPOSTO_CALCULADO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100 
FROM FATURAMENTO_IMPOSTO
WHERE NF_SAIDA='0059567' AND ID_IMPOSTO=1


UPDATE FATURAMENTO_IMPOSTO
SET VALOR_IMPOSTO=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,VALOR_IMPOSTO_CALCULADO=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100
WHERE NF_SAIDA='0059567' AND ID_IMPOSTO=1 AND SERIE_NF='55'

