select * from entradas
WHERE NF_ENTRADA='0088319' AND SERIE_NF_ENTRADA='55'


UPDATE entradas
SET VALOR_IMPOSTO_AGREGAR=-1424.38
WHERE NF_ENTRADA='0088319' AND SERIE_NF_ENTRADA='55' AND ID_IMPOST


select ID_IMPOSTO, VALOR_IMPOSTO, ROUND((TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,2)
from ENTRADAS_IMPOSTO
WHERE NF_ENTRADA='0088393' AND SERIE_NF_ENTRADA='55' AND  --ID_IMPOSTO=1 AND 
ROUND((TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,2) <> VALOR_IMPOSTO


select ITEM_IMPRESSAO,VALOR_IMPOSTO,VALOR_IMPOSTO_ESPELHO
from ENTRADAS_IMPOSTO
WHERE NF_ENTRADA='0088393' AND SERIE_NF_ENTRADA='55' AND --ID_IMPOSTO=1 AND 
VALOR_IMPOSTO_ESPELHO <> VALOR_IMPOSTO




select ID_IMPOSTO, SUM(VALOR_IMPOSTO) from ENTRADAS_IMPOSTO
WHERE NF_ENTRADA='0088319' AND SERIE_NF_ENTRADA='55'
GROUP BY ID_IMPOSTO



---FATURAMENTO---
SELECT VALOR_IMPOSTO,VALOR_IMPOSTO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,VALOR_IMPOSTO_CALCULADO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100 
FROM FATURAMENTO_IMPOSTO
WHERE NF_SAIDA='0083152' AND ID_IMPOSTO=1


UPDATE FATURAMENTO_IMPOSTO
SET VALOR_IMPOSTO=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,VALOR_IMPOSTO_CALCULADO=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100
WHERE NF_SAIDA='0087777' AND ID_IMPOSTO=37 AND SERIE_NF='55'

------------------------------------------------------------------------------
---ENTRADA / DEVOLUÇÃO---
SELECT VALOR_IMPOSTO,VALOR_IMPOSTO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,VALOR_IMPOSTO_CALCULADO_NEW=(TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100 
FROM ENTRADAS_IMPOSTO
WHERE NF_ENTRADA='0073735' AND ID_IMPOSTO=1 AND SERIE_NF_ENTRADA='55'

BEGIN TRAN
ROLLBACK

UPDATE ENTRADAS_IMPOSTO
SET VALOR_IMPOSTO_ESPELHO=ROUND((TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,2), VALOR_IMPOSTO=ROUND((TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,2),VALOR_IMPOSTO_CALC=ROUND((TAXA_IMPOSTO*BASE_IMPOSTO_CALC)/100,2)
WHERE NF_ENTRADA='0088393' AND SERIE_NF_ENTRADA='55'

COMMIT


select * from entradas_imposto where NF_ENTRADA='0080398' AND ID_IMPOSTO=36 AND SERIE_NF_ENTRADA='55'


------------------------------------------------------------------------------

---ENTRADA / DEVOLUÇÃO ICMS-ZF----

SELECT A.VALOR_IMPOSTO_ESPELHO, B.VALOR_IMPOSTO_ESPELHO, * FROM ENTRADAS_IMPOSTO A
JOIN [desenv].[dbo].[ENTRADAS_IMPOSTO] B ON B.NF_ENTRADA=A.NF_ENTRADA AND A.SERIE_NF_ENTRADA=B.SERIE_NF_ENTRADA AND A.ID_IMPOSTO=B.ID_IMPOSTO AND 
A.ITEM_IMPRESSAO=B.ITEM_IMPRESSAO AND A.SUB_ITEM_TAMANHO=B.SUB_ITEM_TAMANHO
WHERE A.NF_ENTRADA='0080398' AND A.SERIE_NF_ENTRADA='55' AND A.ID_IMPOSTO='36'


UPDATE A SET A.VALOR_IMPOSTO_ESPELHO=B.VALOR_IMPOSTO_ESPELHO
--SELECT A.VALOR_IMPOSTO_ESPELHO, B.VALOR_IMPOSTO_ESPELHO, * 
SELECT * FROM ENTRADAS_IMPOSTO A
JOIN [ENTRADAS_IMPOSTO] B ON B.NF_ENTRADA=A.NF_ENTRADA AND A.SERIE_NF_ENTRADA=B.SERIE_NF_ENTRADA AND A.ID_IMPOSTO=B.ID_IMPOSTO AND 
A.ITEM_IMPRESSAO=B.ITEM_IMPRESSAO AND A.SUB_ITEM_TAMANHO=B.SUB_ITEM_TAMANHO
WHERE A.NF_ENTRADA='0088319' AND A.SERIE_NF_ENTRADA='55'



WHERE NF_ENTRADA='0080398' AND ID_IMPOSTO=36 AND SERIE_NF_ENTRADA='55' AND ITEM_IMPRESSAO='0001' AND SUB_ITEM_TAMANHO='3'
