SELECT C.SETOR_PRODUCAO OFICINA,C.RECURSO_PRODUTIVO GRUPO,B.SETOR_PRODUCAO,D.DESC_FASE_PRODUCAO,A.MATERIAL,A.ORDEM_PRODUCAO,A.RESERVA_ORIGINAL,A.RESERVA 
FROM PRODUCAO_RESERVA A WITH (NOLOCK) 
JOIN PRODUCAO_TAREFAS B WITH (NOLOCK) ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
LEFT JOIN (SELECT ORDEM_PRODUCAO,FASE_PRODUCAO,SETOR_PRODUCAO,RECURSO_PRODUTIVO FROM PRODUCAO_TAREFAS WITH (NOLOCK) WHERE FASE_PRODUCAO='007') C ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO 
JOIN PRODUCAO_FASE D WITH (NOLOCK) ON D.FASE_PRODUCAO=B.FASE_PRODUCAO
WHERE A.MATERIAL='60.02.0151' AND B.QTDE_EM_PROCESSO>0 AND A.RESERVA>0


