-- PREVISTO P/ FATURAR
CREATE VIEW W_PREVISTO_FATURAR AS 
SELECT ENTREGA,QTDE_FATURAR_PREVISTA=SUM(QTDE_ENTREGAR)
FROM VENDAS_PRODUTO WITH (NOLOCK)
WHERE ENTREGA >= '20170801'
GROUP BY ENTREGA
GO

-- PCS ENVIADAS PARA APA
ALTER VIEW W_ENVIADAS_PRA_APA AS
SELECT A.ENTREGA,QTDE_EMBALADA_PREVISTA=SUM(A.QTDE_EMBALADA)
FROM (SELECT ENTREGA,PEDIDO,QTDE_EMBALADA=SUM(QTDE_EMBALADA) FROM VENDAS_PRODUTO WITH (NOLOCK) GROUP BY ENTREGA,PEDIDO) A
JOIN VENDAS B WITH (NOLOCK) ON B.PEDIDO=A.PEDIDO
WHERE A.ENTREGA >= '20170801' AND B.PRIORIDADE=9 
GROUP BY A.ENTREGA
HAVING SUM(A.QTDE_EMBALADA) > 0
GO

-- FATURADO
CREATE VIEW W_FATURADO AS
SELECT ENTREGA, QTDE_FATURADA=SUM(QTDE) 
FROM FATURAMENTO_PROD WITH (NOLOCK)
WHERE ENTREGA >= '20170801' 
GROUP BY ENTREGA
GO

-- NÃO EXPEDIDO
CREATE VIEW W_NAO_EXPEDIDO AS
SELECT ENTREGA, QTDE_N_EXPEDIDO=SUM(QTDE)
FROM FATURAMENTO_PROD A WITH (NOLOCK)
JOIN MANIFESTO_FATURAMENTO_DR B WITH (NOLOCK) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
WHERE ENTREGA >= '20170801' 
AND B.DT_MOVIMENTACAO_SAIDA IS NOT NULL 
AND B.SITUACAO='CONFERIDO'
GROUP BY ENTREGA
GO

-- PCS ENVIADAS PARA APA POR PEDIDO
ALTER VIEW [dbo].[W_ENVIADAS_PRA_APA_PEDIDO] AS
SELECT A.ENTREGA,B.PEDIDO,QTDE_EMBALADA_PREVISTA=SUM(A.QTDE_EMBALADA)
FROM (SELECT ENTREGA,PEDIDO,QTDE_EMBALADA=SUM(QTDE_EMBALADA) FROM VENDAS_PRODUTO WITH (NOLOCK) GROUP BY ENTREGA,PEDIDO) A
JOIN VENDAS B WITH (NOLOCK) ON B.PEDIDO=A.PEDIDO
WHERE A.ENTREGA >= '20170801' AND B.PRIORIDADE=9 
GROUP BY A.ENTREGA,B.PEDIDO
HAVING SUM(A.QTDE_EMBALADA)>0


-- FATURADO POR PEDIDO
CREATE VIEW [dbo].[W_FATURADO_PEDIDO] AS
SELECT ENTREGA,PEDIDO, QTDE_FATURADA=SUM(QTDE) 
FROM FATURAMENTO_PROD WITH (NOLOCK)
WHERE ENTREGA >= '20170801' 
GROUP BY ENTREGA,PEDIDO
GO


-- RESULTADO FINAL - DESEMPENHO APA
SELECT 
A.ENTREGA,
A.QTDE_FATURAR_PREVISTA AS 'PREVISTO P/ FATURAR',
ISNULL(B.QTDE_EMBALADA_PREVISTA,0) AS '(+) PCS ENVIADAS P/ APA',
ISNULL(C.QTDE_FATURADA,0) AS '(-) FATURADO',
ISNULL((A.QTDE_FATURAR_PREVISTA+B.QTDE_EMBALADA_PREVISTA)-C.QTDE_FATURADA,0) AS '(=) SALDO A FATURAR',
ISNULL(D.QTDE_N_EXPEDIDO,0) AS 'NÃO EXPEDIDO'
FROM W_PREVISTO_FATURAR A
LEFT JOIN W_ENVIADAS_PRA_APA B ON B.ENTREGA=A.ENTREGA
LEFT JOIN W_FATURADO C ON C.ENTREGA=A.ENTREGA
LEFT JOIN W_NAO_EXPEDIDO D ON D.ENTREGA=A.ENTREGA
ORDER BY A.ENTREGA


---- TESTE
SELECT 
A.ENTREGA,
A.QTDE_FATURAR_PREVISTA AS 'PREVISTO P/ FATURAR',
ISNULL(B.QTDE_EMBALADA_PREVISTA,0) AS '(+) PCS ENVIADAS P/ APA',
ISNULL(C.QTDE_FATURADA,0) AS '(-) FATURADO',
ISNULL((A.QTDE_FATURAR_PREVISTA+B.QTDE_EMBALADA_PREVISTA)-C.QTDE_FATURADA,0) AS '(=) SALDO A FATURAR',
ISNULL(D.QTDE_N_EXPEDIDO,0) AS 'NÃO EXPEDIDO'
FROM W_PREVISTO_FATURAR A
LEFT JOIN W_ENVIADAS_PRA_APA B ON B.ENTREGA=A.ENTREGA
LEFT JOIN W_FATURADO C ON C.ENTREGA=A.ENTREGA
LEFT JOIN W_NAO_EXPEDIDO D ON D.ENTREGA=A.ENTREGA
ORDER BY A.ENTREGA

SELECT A.ENTREGA,SUM(A.QTDE_EMBALADA_PREVISTA)
FROM W_ENVIADAS_PRA_APA_PEDIDO A
JOIN W_FATURADO_PEDIDO B ON B.ENTREGA=A.ENTREGA AND B.PEDIDO=A.PEDIDO
WHERE A.ENTREGA='20170828' 
GROUP BY A.ENTREGA

SELECT A.ENTREGA,SUM(A.QTDE_EMBALADA_PREVISTA)
FROM W_ENVIADAS_PRA_APA_PEDIDO A
WHERE A.ENTREGA='20170828'
GROUP BY A.ENTREGA


SELECT * FROM W_ENVIADAS_PRA_APA_PEDIDO




-- DESEMPENHO INDUSTRIAL

SELECT ESTOQUE_SAI_MAT.REQ_MATERIAL, ESTOQUE_SAI_MAT.FILIAL, ESTOQUE_SAI_MAT.TIPO_MOVIMENTACAO, ESTOQUE_SAI_MAT.EMISSAO, ESTOQUE_SAI_MAT.RESPONSAVEL, ESTOQUE_SAI_MAT.REQUISITANTE, ESTOQUE_SAI_MAT.DESTINO, ESTOQUE_SAI_MAT.FILIAL_DESTINO, ESTOQUE_SAI_MAT.DATA_DIGITACAO, ESTOQUE_SAI1_MAT.REQ_MATERIAL, ESTOQUE_SAI1_MAT.MATERIAL, ESTOQUE_SAI1_MAT.COR_MATERIAL, ESTOQUE_SAI1_MAT.QTDE, MATERIAIS.MATERIAL, MATERIAIS.GRUPO, MATERIAIS.SUBGRUPO, MATERIAIS.FATOR_CONVERSAO, MATERIAIS.UNID_ESTOQUE, MATERIAIS.UNID_FICHA_TEC, PROP_ESTOQUE_SAI_MAT.PROPRIEDADE, PROP_ESTOQUE_SAI_MAT.REQ_MATERIAL, PROP_ESTOQUE_SAI_MAT.VALOR_PROPRIEDADE, MATERIAIS.DESC_MATERIAL, MATERIAIS.TIPO
FROM DRLINGERIE.dbo.ESTOQUE_SAI_MAT ESTOQUE_SAI_MAT, DRLINGERIE.dbo.ESTOQUE_SAI1_MAT ESTOQUE_SAI1_MAT, DRLINGERIE.dbo.MATERIAIS MATERIAIS, DRLINGERIE.dbo.PROP_ESTOQUE_SAI_MAT PROP_ESTOQUE_SAI_MAT
WHERE ESTOQUE_SAI_MAT.REQ_MATERIAL = ESTOQUE_SAI1_MAT.REQ_MATERIAL AND ESTOQUE_SAI_MAT.REQ_MATERIAL = PROP_ESTOQUE_SAI_MAT.REQ_MATERIAL AND ESTOQUE_SAI_MAT.FILIAL = ESTOQUE_SAI1_MAT.FILIAL AND ESTOQUE_SAI_MAT.FILIAL = PROP_ESTOQUE_SAI_MAT.FILIAL AND ESTOQUE_SAI1_MAT.REQ_MATERIAL = PROP_ESTOQUE_SAI_MAT.REQ_MATERIAL AND ESTOQUE_SAI1_MAT.MATERIAL = MATERIAIS.MATERIAL AND ESTOQUE_SAI1_MAT.FILIAL = PROP_ESTOQUE_SAI_MAT.FILIAL AND ((ESTOQUE_SAI_MAT.FILIAL='REVISÃO DE TECIDOS') AND (ESTOQUE_SAI_MAT.EMISSAO>={ts '2012-01-01 00:00:00'}) AND (PROP_ESTOQUE_SAI_MAT.PROPRIEDADE='00084') OR (ESTOQUE_SAI_MAT.FILIAL='REVISAO SEAMLESS') AND (ESTOQUE_SAI_MAT.EMISSAO>={ts '2012-01-01 00:00:00'}) AND (PROP_ESTOQUE_SAI_MAT.PROPRIEDADE='00084') OR (ESTOQUE_SAI_MAT.FILIAL='REVISÃO TECIDO REPROCESSO') AND (ESTOQUE_SAI_MAT.EMISSAO>={ts '2012-01-01 00:00:00'}) AND (PROP_ESTOQUE_SAI_MAT.PROPRIEDADE='00084') OR (ESTOQUE_SAI_MAT.FILIAL='EMBOBINAMENTO') AND (ESTOQUE_SAI_MAT.EMISSAO>={ts '2012-01-01 00:00:00'}) AND (PROP_ESTOQUE_SAI_MAT.PROPRIEDADE='00084') OR (ESTOQUE_SAI_MAT.FILIAL='EMBOBINAMENTO REPROCESSO') AND (ESTOQUE_SAI_MAT.EMISSAO>={ts '2012-01-01 00:00:00'}) AND (PROP_ESTOQUE_SAI_MAT.PROPRIEDADE='00084'))

