SELECT C.*,B.*, A.* FROM FATURAMENTO_ITEM A with (nolock)
JOIN FATURAMENTO B with (nolock) ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
JOIN NATUREZAS_SAIDAS C with (nolock) ON C.NATUREZA_SAIDA=B.NATUREZA_SAIDA
WHERE CONTA_CONTABIL='11401' AND EMISSAO>='20150101'
