
SELECT PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_FICHA.MATERIAL,
W_LDR_PRODUTOS_BARRA.GRADE,
CONSUMO= (CASE WHEN W_LDR_PRODUTOS_BARRA.tamanho='1'  THEN PRODUTOS_FICHA.C1 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='2'  THEN PRODUTOS_FICHA.C2 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='3'  THEN PRODUTOS_FICHA.C3 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='4'  THEN PRODUTOS_FICHA.C4 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='5'  THEN PRODUTOS_FICHA.C5 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='6'  THEN PRODUTOS_FICHA.C6 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='7'  THEN PRODUTOS_FICHA.C7 
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='8'  THEN PRODUTOS_FICHA.C8  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='9'  THEN PRODUTOS_FICHA.C9  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='10' THEN PRODUTOS_FICHA.C10  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='11' THEN PRODUTOS_FICHA.C11  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='12' THEN PRODUTOS_FICHA.C12  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='13' THEN PRODUTOS_FICHA.C13  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='14' THEN PRODUTOS_FICHA.C14  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='15' THEN PRODUTOS_FICHA.C15  
               WHEN W_LDR_PRODUTOS_BARRA.tamanho='16' THEN PRODUTOS_FICHA.C16  
            END)
FROM W_LDR_PRODUTOS_BARRA W_LDR_PRODUTOS_BARRA
JOIN PRODUTOS PRODUTOS ON W_LDR_PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
LEFT JOIN (SELECT * FROM PRODUTOS_FICHA) AS PRODUTOS_FICHA   ON PRODUTOS_FICHA.PRODUTO=W_LDR_PRODUTOS_BARRA.PRODUTO 
WHERE W_LDR_PRODUTOS_BARRA.CODIGO_BARRA_PADRAO=1 AND PRODUTOS_FICHA.MATERIAL LIKE '30%' 
ORDER BY W_LDR_PRODUTOS_BARRA.PRODUTO

CREATE VIEW W_LDR_PRODUTOS_BARRA AS
SELECT DISTINCT CODIGO_BARRA_PADRAO,PRODUTO,TAMANHO,GRADE FROM PRODUTOS_BARRA 

