--- RESERVA DE ORDEM DE PRODUÇÃO X ESTOQUE DISPONIVEL SÓ FASE PCP
CREATE VIEW W_ESTOQUE_DISPONIVEL_MATERIAL_PCP AS
SELECT MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,RESERVA,QTDE_DISPONIVEL=(QTDE_ESTOQUE-RESERVA) FROM (
SELECT PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.COR_MATERIAL,ESTOQUE_MATERIAIS.QTDE_ESTOQUE,RESERVA=SUM(RESERVA)
FROM PRODUCAO_RESERVA WITH (NOLOCK)
JOIN ESTOQUE_MATERIAIS WITH (NOLOCK) ON ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND
ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL AND ESTOQUE_MATERIAIS.FILIAL='DR VAREJO'
WHERE PRODUCAO_RESERVA.ORDEM_PRODUCAO IN (
SELECT ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
WHERE FASE_PRODUCAO in('001') and QTDE_EM_PROCESSO>0
)
GROUP BY PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.COR_MATERIAL,ESTOQUE_MATERIAIS.QTDE_ESTOQUE
) AS ESTOQUE_DISPONIVEL



--- RESERVA DE ORDEM DE PRODUÇÃO X ESTOQUE DISPONIVEL SÓ ALMOXARIFADO
alter VIEW W_ESTOQUE_DISPONIVEL_MATERIAL AS
SELECT MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,RESERVA,QTDE_DISPONIVEL=(QTDE_ESTOQUE-RESERVA) FROM (
SELECT PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.COR_MATERIAL,ESTOQUE_MATERIAIS.QTDE_ESTOQUE,RESERVA=SUM(RESERVA)
FROM PRODUCAO_RESERVA WITH (NOLOCK)
JOIN ESTOQUE_MATERIAIS WITH (NOLOCK) ON ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND
ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL AND ESTOQUE_MATERIAIS.FILIAL='DR VAREJO'
WHERE PRODUCAO_RESERVA.ORDEM_PRODUCAO IN (
SELECT ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
WHERE FASE_PRODUCAO in('002') and QTDE_EM_PROCESSO>0
)
GROUP BY PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.COR_MATERIAL,ESTOQUE_MATERIAIS.QTDE_ESTOQUE
) AS ESTOQUE_DISPONIVEL


SELECT A.ORDEM_PRODUCAO,A.MATERIAL,A.COR_MATERIAL,A.RESERVA,B.QTDE_ESTOQUE,B.QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A
JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL 
WHERE (A.MATERIAL LIKE '01%' or A.MATERIAL LIKE '15%') AND A.RESERVA>B.QTDE_ESTOQUE


WHERE ORDEM_PRODUCAO='75918' AND A.RESERVA>B.QTDE_ESTOQUE


select * from PRODUCAO_RESERVA
WHERE ORDEM_PRODUCAO='75918'


SELECT * FROM (
SELECT ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS WITH (NOLOCK)
WHERE FASE_PRODUCAO='001' and QTDE_EM_PROCESSO>0 ) TESTE
WHERE ORDEM_PRODUCAO='77044'

SELECT * FROM MATERIAIS_SUBGRUPO


SELECT A.ORDEM_PRODUCAO,A.MATERIAL,A.COR_MATERIAL,A.RESERVA,B.QTDE_ESTOQUE,B.QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A WITH (NOLOCK) 
JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL 
JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=B.MATERIAL 
WHERE (C.GRUPO LIKE '01%' OR C.GRUPO LIKE '15%' OR C.GRUPO LIKE '30%' OR C.GRUPO LIKE '40%' OR C.SUBGRUPO LIKE 'BOJO' OR C.SUBGRUPO LIKE 'COLCHETE' OR C.SUBGRUPO LIKE 'ARGOLA' OR C.SUBGRUPO='PASSANTE')  ---AND A.RESERVA>B.QTDE_DISPONIVEL AND ORDEM_PRODUCAO='"+op+"'
order by MATERIAL



SELECT A.ORDEM_PRODUCAO,D.PRODUTO,D.COR_PRODUTO,A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,C.UNID_ESTOQUE,A.RESERVA,B.QTDE_ESTOQUE,B.QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A WITH (NOLOCK) 
JOIN W_ESTOQUE_DISPONIVEL_MATERIAL B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL 
JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=B.MATERIAL 
JOIN PRODUCAO_ORDEM_COR D WITH (NOLOCK) ON D.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO
JOIN PRODUCAO_TAREFAS E WITH (NOLOCK) ON E.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO
WHERE A.RESERVA>B.QTDE_DISPONIVEL AND A.ORDEM_PRODUCAO='77864' AND E.FASE_PRODUCAO='001' AND E.QTDE_EM_PROCESSO>0


SELECT A.ORDEM_PRODUCAO,D.PRODUTO,D.COR_PRODUTO,A.MATERIAL,C.DESC_MATERIAL,A.COR_MATERIAL,C.UNID_ESTOQUE,A.RESERVA,B.QTDE_ESTOQUE,B.QTDE_DISPONIVEL FROM PRODUCAO_RESERVA A WITH (NOLOCK) 
JOIN W_ESTOQUE_DISPONIVEL_MATERIAL_PCP B WITH (NOLOCK) ON B.MATERIAL=A.MATERIAL AND B.COR_MATERIAL=A.COR_MATERIAL 
JOIN MATERIAIS C WITH (NOLOCK) ON C.MATERIAL=B.MATERIAL 
JOIN PRODUCAO_ORDEM_COR D WITH (NOLOCK) ON D.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO
JOIN PRODUCAO_TAREFAS E WITH (NOLOCK) ON E.ORDEM_PRODUCAO = A.ORDEM_PRODUCAO
WHERE E.FASE_PRODUCAO='001' AND E.QTDE_EM_PROCESSO>0 
and A.MATERIAL='30.01.0012' AND A.COR_MATERIAL='BC0035'
order by MATERIAL



SELECT * FROM PRODUCAO_RESERVA
WHERE ORDEM_PRODUCAO='77864'
order by MATERIAL

select * from W_ESTOQUE_DISPONIVEL_MATERIAL
where MATERIAL='30.01.0012'
