--- PEDIDO MAIOR QUE ORIGINAL
SELECT * FROM VENDAS_PRODUTO
WHERE QTDE_ORIGINAL-(QTDE_ENTREGUE+QTDE_EMBALADA)>0 AND PEDIDO='94964'

SELECT pedido,produto,cor_produto,item_pedido,QTDE_ORIGINAL,QTDE_EMBALADA,QTDE_ENTREGAR FROM VENDAS_PRODUTO
WHERE QTDE_ORIGINAL < QTDE_EMBALADA AND PEDIDO='94964'


SELECT * FROM VENDAS
WHERE PEDIDO='576664' 


SELECT PEDIDO, produto,cor_produto,SUM(QTDE) AS QTDE_JA_FATURADA 
FROM FATURAMENTO_PROD 
WHERE PEDIDO = '576656'
GROUP BY PEDIDO, produto,cor_produto


SELECT A.PEDIDO, A.produto,A.cor_produto,b.QTDE_ORIGINAL,SUM(QTDE) AS QTDE_JA_FATURADA 
FROM FATURAMENTO_PROD a
join VENDAS_PRODUTO B ON B.PEDIDO=A.PEDIDO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO
WHERE A.PEDIDO = '586422'
GROUP BY a.PEDIDO, a.produto,a.cor_produto,b.QTDE_ORIGINAL

94964


SELECT * FROM VENDAS_LOTE_PROD_COPIA_PEDIDO
WHERE PEDIDO_EXTERNO='0234l.001156'
 
