--- REQUISIÇÃO RETORNO DAS OPS EM PROCESSO NÃO FINALIZADO
INSERT INTO ESTOQUE_RET1_MAT (MATERIAL,REQ_MATERIAL,COR_MATERIAL,FILIAL,ITEM,CUSTO_ULT_SAIDA,DATA_CUSTO,ENTREGA_PEDIDO,CUSTO_MATERIA_PRIMA,VALOR,ITEM_IMPRESSAO,QTDE) 
SELECT MATERIAL,'047561',COR_MATERIAL,'DR VAREJO',
CAST('100' AS INT)+ ROW_NUMBER() OVER(ORDER BY MATERIAL) AS Row1,
CUSTO_REPOSICAO,NULL,NULL,CUSTO_REPOSICAO,(CUSTO_REPOSICAO*SUM(RESERVA_RETORNO)),
CAST('1000' AS INT)+ ROW_NUMBER() OVER(ORDER BY MATERIAL) AS Row2,
RESERVA_RETORNO=SUM(RESERVA_RETORNO) FROM (
SELECT MP.CUSTO_REPOSICAO,PR.*,PT.QTDE_PREVISTA,PT.QTDE_EM_PROCESSO,RESERVA_RETORNO=CAST((PR.RESERVA_ORIGINAL/PT.QTDE_PREVISTA)*PT.QTDE_EM_PROCESSO AS NUMERIC(9,3))  
FROM PRODUCAO_TAREFAS PT
JOIN PRODUCAO_RESERVA PR ON PR.ORDEM_PRODUCAO=PT.ORDEM_PRODUCAO
JOIN MATERIAIS MP ON MP.MATERIAL=PR.MATERIAL
WHERE PT.QTDE_EM_PROCESSO>0 AND PR.CONSUMIDA>0 AND PT.FASE_PRODUCAO IN('002','003','004','005','006','006.1','007','008')
) MATERIAIS_RETORNO 
GROUP BY MATERIAL,COR_MATERIAL,CUSTO_REPOSICAO



