SELECT *,FALTA=(VE-EMB) FROM (

SELECT FAT.EMISSAO AS DATA,FAT.NF_SAIDA, PRODUTOS.GRUPO_PRODUTO,
COLECOES.DESC_COLECAO,
VENDAS.OBS,
VENDAS.APROVACAO,
VENDAS.TIPO,
VENDAS.PEDIDO_CLIENTE,
VENDAS.PEDIDO, VENDAS.COLECAO, VENDAS.CODIGO_TAB_PRECO,VENDAS.FILIAL, 
VENDAS.CONDICAO_PGTO, VENDAS.CLIENTE_ATACADO, VENDAS.REPRESENTANTE, 
VENDAS.GERENTE, VENDAS.EMISSAO,VENDAS.CADASTRAMENTO, VENDAS_PRODUTO.ENTREGA, VENDAS_PRODUTO.LIMITE_ENTREGA, 
VENDAS_PRODUTO.PRODUTO,
COR_PRODUTO=RTRIM(PRODUTOS_BARRA.COR_PRODUTO)+' - '+RTRIM(PC.DESC_COR_PRODUTO),PRODUTOS_BARRA.GRADE,
VO = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.Vo1 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.Vo2 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.Vo3 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.Vo4 
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.Vo5 
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.Vo6 
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.Vo7 
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.Vo8 
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.Vo9 
           WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.Vo10 
           WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.Vo11 
           WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.Vo12 
           WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.Vo13 
           WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.Vo14 
           WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.Vo15 
           WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.Vo16 
END),
VE = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VE1 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VE2 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VE3 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VE4 
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VE5 
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VE6 
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VE7 
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VE8 
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VE9 
           WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VE10 
           WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VE11 
           WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VE12 
           WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VE13 
           WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VE14 
           WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VE15 
           WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VE16 
END),
EMB = (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN ISNULL(VENDAS_PROD_EMBALADO.E1,0) 
           WHEN PRODUTOS_BARRA.tamanho='2'  THEN ISNULL(VENDAS_PROD_EMBALADO.E2,0) 
           WHEN PRODUTOS_BARRA.tamanho='3'  THEN ISNULL(VENDAS_PROD_EMBALADO.E3,0) 
           WHEN PRODUTOS_BARRA.tamanho='4'  THEN ISNULL(VENDAS_PROD_EMBALADO.E4,0)  
           WHEN PRODUTOS_BARRA.tamanho='5'  THEN ISNULL(VENDAS_PROD_EMBALADO.E5,0)  
           WHEN PRODUTOS_BARRA.tamanho='6'  THEN ISNULL(VENDAS_PROD_EMBALADO.E6,0)  
           WHEN PRODUTOS_BARRA.tamanho='7'  THEN ISNULL(VENDAS_PROD_EMBALADO.E7,0)  
           WHEN PRODUTOS_BARRA.tamanho='8'  THEN ISNULL(VENDAS_PROD_EMBALADO.E8,0)  
           WHEN PRODUTOS_BARRA.tamanho='9'  THEN ISNULL(VENDAS_PROD_EMBALADO.E9,0)  
           WHEN PRODUTOS_BARRA.tamanho='10' THEN ISNULL(VENDAS_PROD_EMBALADO.E10,0)  
           WHEN PRODUTOS_BARRA.tamanho='11' THEN ISNULL(VENDAS_PROD_EMBALADO.E11,0)  
           WHEN PRODUTOS_BARRA.tamanho='12' THEN ISNULL(VENDAS_PROD_EMBALADO.E12,0)  
           WHEN PRODUTOS_BARRA.tamanho='13' THEN ISNULL(VENDAS_PROD_EMBALADO.E13,0)  
           WHEN PRODUTOS_BARRA.tamanho='14' THEN ISNULL(VENDAS_PROD_EMBALADO.E14,0)  
           WHEN PRODUTOS_BARRA.tamanho='15' THEN ISNULL(VENDAS_PROD_EMBALADO.E15,0)  
           WHEN PRODUTOS_BARRA.tamanho='16' THEN ISNULL(VENDAS_PROD_EMBALADO.E16,0)  
END)
FROM VENDAS_PRODUTO VENDAS_PRODUTO with (nolock)
JOIN VENDAS VENDAS with (nolock) ON VENDAS.PEDIDO = VENDAS_PRODUTO.PEDIDO
JOIN COLECOES COLECOES with (nolock) ON COLECOES.COLECAO = VENDAS.COLECAO
JOIN COND_ATAC_PGTOS COND_ATAC_PGTOS with (nolock) ON COND_ATAC_PGTOS.CONDICAO_PGTO = VENDAS.CONDICAO_PGTO
LEFT JOIN ROMANEIOS_RESERVAS ROMANEIOS_RESERVAS with (nolock) ON ROMANEIOS_RESERVAS.PEDIDO = VENDAS_PRODUTO.PEDIDO AND ROMANEIOS_RESERVAS.PRODUTO = VENDAS_PRODUTO.PRODUTO AND ROMANEIOS_RESERVAS.COR_PRODUTO = VENDAS_PRODUTO.COR_PRODUTO
JOIN CADASTRO_CLI_FOR with (nolock) ON CADASTRO_CLI_FOR.NOME_CLIFOR = VENDAS.CLIENTE_ATACADO
JOIN PRODUTOS WITH (NOLOCK) ON PRODUTOS.PRODUTO = VENDAS_PRODUTO.PRODUTO

LEFT JOIN (

     SELECT FILIAL,PEDIDO,PRODUTO,COR_PRODUTO,E1=SUM(E1),E2=SUM(E2),E3=SUM(E3),E4=SUM(E4),E5=SUM(E5),E6=SUM(E6),E7=SUM(E7),E8=SUM(E8),E9=SUM(E9),E10=SUM(E10),E11=SUM(E11),E12=SUM(E12),E13=SUM(E13),E14=SUM(E14),E15=SUM(E15),E16=SUM(E16) FROM VENDAS_PROD_EMBALADO with (nolock) WHERE FILIAL='D.R. LINGERIE' 
     GROUP BY FILIAL,PEDIDO,PRODUTO,COR_PRODUTO

) AS VENDAS_PROD_EMBALADO ON VENDAS_PROD_EMBALADO.PEDIDO=VENDAS_PRODUTO.PEDIDO AND VENDAS_PROD_EMBALADO.PRODUTO=VENDAS_PRODUTO.PRODUTO AND VENDAS_PROD_EMBALADO.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO 
FULL OUTER JOIN (SELECT DISTINCT F.EMISSAO, FP.NF_SAIDA, FP.PEDIDO FROM FATURAMENTO_PROD  FP  with (nolock) JOIN FATURAMENTO F  with (nolock) ON F.NF_SAIDA=FP.NF_SAIDA AND F.SERIE_NF=FP.SERIE_NF WHERE FP.SERIE_NF='55') AS FAT ON FAT.PEDIDO=VENDAS_PRODUTO.PEDIDO
JOIN (
SELECT PRODUTO,COR_PRODUTO,TAMANHO,GRADE 
	FROM PRODUTOS_BARRA with (nolock) 
      WHERE CODIGO_BARRA LIKE '789%' and CODIGO_BARRA_PADRAO='1'
      ) AS PRODUTOS_BARRA ON PRODUTOS_BARRA.PRODUTO=VENDAS_PRODUTO.PRODUTO AND PRODUTOS_BARRA.COR_PRODUTO=VENDAS_PRODUTO.COR_PRODUTO
JOIN PRODUTO_CORES PC ON PC.PRODUTO=PRODUTOS_BARRA.PRODUTO AND PC.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO
WHERE ((VENDAS.EMISSAO>={ts '2015-01-01 00:00:00'}) AND (VENDAS_PRODUTO.ENTREGA>={ts '2015-01-01 00:00:00'}))
) AS VENDAS_PRODUTO_VERTICAL
WHERE VENDAS_PRODUTO_VERTICAL.VE>0 

