select * from VENDAS_LOTE_COPIA_PEDIDO
WHERE PEDIDO_EXTERNO='0083i.400064'

select * from VENDAS_LOTE_PROD_COPIA_PEDIDO
WHERE PEDIDO_EXTERNO='0083i.400064'

SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO='61044'


UPDATE A
SET A.LIMITE_ENTREGA=C.LIMITE
FROM VENDAS_PRODUTO A
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS C ON C.PERIODO_PCP=B.PERIODO_PCP AND B.NUMERO_ENTREGA=C.NUMERO_ENTREGA
WHERE B.FILIAL='DR VAREJO' AND B.PERIODO_PCP='ABRIL 2016' AND A.ENTREGA>A.LIMITE_ENTREGA 



SELECT A.PEDIDO,B.PERIODO_PCP,A.ENTREGA, A.LIMITE_ENTREGA, C.LIMITE 
FROM VENDAS_PRODUTO A
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO
JOIN PRODUTOS_PERIODOS_ENTREGAS C ON C.PERIODO_PCP=B.PERIODO_PCP AND B.NUMERO_ENTREGA=C.NUMERO_ENTREGA
WHERE B.FILIAL='DR VAREJO' AND B.PERIODO_PCP='ABRIL 2016' AND A.ENTREGA>A.LIMITE_ENTREGA -- AND A.PEDIDO='61044'


