SELECT * FROM W_LF_REGISTRO_ENTRADA_IMPOSTO_ITEM

USE [AFRODITE]
GO

/****** Object:  View [dbo].[W_LF_REGISTRO_ENTRADA_IMPOSTO_ITEM]    Script Date: 05/06/2013 13:42:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[W_LF_REGISTRO_ENTRADA_IMPOSTO_ITEM] 
AS

-- 22/03/2012 - WENDEL CRESPIGIO    - INCLUSÃO DO CAMPO ID_EXCECAO_IMPOSTO
-- 21/06/2011 - DEBORAH				- INCLUIR CAMPO COD_MATRIZ_CONTABIL E MATRIZ_CONTABIL
-- 23/02/2011 - LETÍCIA				- INCLUIR CAMPO ESPECIE_SERIE
-- 31/03/2009 - ANDRE MAIA			- INCLUIR OS CAMPOS ID_FISCAL, ID_FISCAL_ITEM, SUB_ITEM_TAMANHO, ITEM_NOTA E MUDAR O JOIN COM A LF_REGISTRO_ENTRADA
-- 08/05/2008 - JOAO RICARDO		- NÃO TRAZER OS IMPOSTOS DE SERVICOS
-- 25/02/2008 - ADRIANO             - INCLUIR O CAMPO TEXTO_LEGAL
-- 04/07/2007 - ADRIANO				- BUSCAR OS CAMPOS DE CLIENTE NAS TABELAS CLIENTES_VAREJO E CADASTRO_CLI_FOR
-- 17/05/2007 - ADRIANO RODRIGUES   - INCLUIR O CAMPO NUMERO_MODELO_FISCAL DA TABELA CTB_ESPECIE_SERIE
-- 14/11/2006 - JOAO RICARDO        - CAMPO BASE IMPOSTO AGREGADO
-- 10/11/2006 - JOAO RICARDO        - INCLUIR O CAMPO ITEM
-- 30/10/2006 - JOAO RICARDO        - TRATAMENTO PARA A NOVA TABELA DE ITENS DO FISCAL
-- 28/08/2006 - ADRIANO             - NÃO PERMITIR NULO NO CAMPO SERIE_NF_OFICIAL
-- 11/04/2006 - ADRIANO             - CORRIGIR O WHERE, NO CAMPO CODIGO_FISCAL_OPERACAO < '9000'
-- 05/01/2006 - ADRIANO             - INCLUSÃO DO CAMPO NF_PROPRIA_EMITIDA
-- 17/11/2005 - JOAO RICARDO        - INCLUSAO DO CAMPO SERIE_NF_OFICIAL
-- 10/11/2005 - ADRIANO             - INCLUSÃO DO CAMPO COD_SERIE_SINTEGRA
-- 29/08/2005 - ADRIANO             - ACRESCENTEI O CAMPO DATA_DIGITACAO DA TABELA ENTRADAS
-- 26/11/2003 - JOÃO RICARDO        - 16:45 - Verificação de campo NAO_SOMA_VALOR para compor o valor_contabil
-- 30/01/2004 - JOÃO RICARDO        - 10:11 - colocar o campo indica_fiscal no where
-- 20/04/2004 - JOÃO RICARDO        - 11:27 - COLOCAR NO VALOR BRUTO DO ITEM O VALOR CONTABIL MENOS OS DESCONTOS
-- 30/06/2004 - ADRIANO RODRIGUES   - Acrescentei o campo UNIDADE da tabela FATURAMENTO_ITEM para a geração do arquivo SISIF do Ceará
-- 07/07/2004 - ADRIANO RODRIGUES   - ACRESCENTEI OS CAMPOS PRECO_UNITARIO, BASE_IMPOSTO_AGREGADO E VALOR_IMPOSTO_AGREGADO
-- 04/10/2004 - joão ricardo        - quando a referencia está null colocar o campo codigo_item
-- 12/11/2004 - JOÃO RICARDO        - VALOR CONTABIL
-- 21/12/2004 - JOÃO RICARDO        - INCLUSÃO DA VIEW PARA BENEFICIAMENTO
-- 24/03/2005 - Adriano Rodrigues   - Acrescentei o campo TRIBUT_ORIGEM 
-- 03/05/2005 - Adriano             - Acrescentei o campo INDICADOR_CFOP
-- 09/05/2005 - Adriano             - ALTEREI O CAMPO CGC_CFP_MATRIZ_FISCAL PARA CGC_CPF_MATRIZ_FISCAL e CGC_CFP_FILIAL PARA CGC_CPF_FILIAL

SELECT 	    NOME_CLIFOR                = C.NOME_CLIFOR, 
			NF_ENTRADA                 = A.NF_ENTRADA, 
			SERIE_NF_ENTRADA           = A.SERIE_NF_ENTRADA, 
			SERIE_NF_OFICIAL		   = ISNULL(D.COD_SERIE_SINTEGRA, A.SERIE_NF_ENTRADA),
			ESPECIE_SERIE			   = E.ESPECIE_SERIE,
			ESPECIE                    = ISNULL(L.DESC_ESPECIE_SERIE,'SEM ESPECIE'), 
			ID_IMPOSTO                 = A.ID_IMPOSTO, 
			IMPOSTO                    = F.IMPOSTO, 
			VALOR_CONTABIL             = ISNULL(A.VALOR_CONTABIL,0.00),
			BASE_IMPOSTO 			      = ISNULL(A.BASE_IMPOSTO,0.00),
			TAXA_IMPOSTO               = A.TAXA_IMPOSTO, 
			VALOR_IMPOSTO 			      = ISNULL(A.VALOR_IMPOSTO,0.00),
			VALOR_IMPOSTO_OUTROS       = ISNULL(A.VALOR_IMPOSTO_OUTROS,0.00),
			VALOR_IMPOSTO_ISENTO       = ISNULL(A.VALOR_IMPOSTO_ISENTO,0.00),
			CODIGO_FISCAL_OPERACAO     = A.CODIGO_FISCAL_OPERACAO,
			DENOMINACAO_CFOP 			   = G.DENOMINACAO,
			LX_CODIGO_APURACAO         = G.LX_CODIGO_APURACAO, 
			RECEBIMENTO                = E.RECEBIMENTO, 
			EMISSAO                    = E.EMISSAO, 
			FILIAL                     = B.FILIAL, 
			COD_FILIAL                 = E.COD_FILIAL, 
			COD_CLIFOR                 = A.COD_CLIFOR,
			CGC_CPF                    = ISNULL(CV.CPF_CGC, C.CGC_CPF), 
			RG_IE                      = ISNULL(CV.RG_IE, C.RG_IE), 
			UF                         = ISNULL(CV.UF, C.UF), 
			EMPRESA                    = E.EMPRESA,
			CONTA_CONTABIL             = A.CONTA_CONTABIL,
			DESC_CONTA                 = H.DESC_CONTA,
			DESCONTO 					   = ISNULL(A.DESCONTO,0.00),
			FRETE   	 					   = ISNULL(A.FRETE,0.00),
			SEGURO						   = ISNULL(A.SEGURO,0.00),
    		ENCARGO						   = ISNULL(A.ENCARGO,0.00),
			BASE_IMPOSTO_AGREGADO	   = ISNULL(A.BASE_IMPOSTO_AGREGADO,0.00),
			VALOR_IMPOSTO_AGREGADO	   = ISNULL(A.VALOR_IMPOSTO_AGREGADO,0.00),
			COD_MATRIZ_FISCAL				= A.COD_MATRIZ_FISCAL, 
			MATRIZ_FISCAL					= J.NOME_CLIFOR,
			CODIGO_ITEM						= A.CODIGO_ITEM,
			TRIBUT_ICMS                = A.TRIBUT_ICMS,
			TRIBUT_ORIGEM              = A.TRIBUT_ORIGEM,
			ITEM_IMPRESSAO             = A.ITEM_IMPRESSAO,
			QTDE_ITEM                  = A.QTDE_ITEM,
			PRECO_UNITARIO             = A.PRECO_UNITARIO,
			VALOR_BRUTO_ITEM 				= A.VALOR_BRUTO_ITEM,
			VALOR_DESCONTOS            = A.VALOR_DESCONTOS,
			DESCRICAO_ITEM             = A.DESCRICAO_ITEM,
			UNIDADE                    = A.UNIDADE,
			CLASSIF_FISCAL             = A.CLASSIF_FISCAL,
			COD_TABELA_FILHA           = A.COD_TABELA_FILHA,
			INDICADOR_CFOP             = A.INDICADOR_CFOP,
			NF_PROPRIA_EMITIDA         = E.NF_PROPRIA_EMITIDA,
			A.ITEM,
			L.NUMERO_MODELO_FISCAL,
			CV.CODIGO_CLIENTE,
			CV.CLIENTE_VAREJO,
			A.TEXTO_LEGAL,
			A.ID_FISCAL,
			A.ID_FISCAL_ITEM,
			A.SUB_ITEM_TAMANHO,
			A.ITEM_NOTA,
			COD_MATRIZ_CONTABIL			= M.COD_CLIFOR,
			MATRIZ_CONTABIL				= M.NOME_CLIFOR,
			A.ID_EXCECAO_IMPOSTO			
FROM LF_REGISTRO_ENTRADA_ITEM A (NOLOCK)
      JOIN LF_REGISTRO_ENTRADA E (NOLOCK) ON 
			A.ID_FISCAL = E.ID_FISCAL
      JOIN FILIAIS B (NOLOCK) ON 
         E.COD_FILIAL      = B.COD_FILIAL
      LEFT JOIN CADASTRO_CLI_FOR C (NOLOCK) ON
         A.COD_CLIFOR            = C.COD_CLIFOR  
      LEFT JOIN CLIENTES_VAREJO CV (NOLOCK) ON
         E.CODIGO_CLIENTE        = CV.CODIGO_CLIENTE
      LEFT JOIN SERIES_NF D (NOLOCK) ON
         A.SERIE_NF_ENTRADA      = D.SERIE_NF
      LEFT JOIN CTB_LX_IMPOSTO_TIPO F (NOLOCK) ON
         A.ID_IMPOSTO               = F.ID_IMPOSTO
      JOIN CTB_LX_NATUREZAS_OPERACAO G (NOLOCK) ON
         A.CODIGO_FISCAL_OPERACAO   = G.CODIGO_FISCAL_OPERACAO
      LEFT JOIN CTB_CONTA_PLANO H (NOLOCK) ON
         A.CONTA_CONTABIL           = H.CONTA_CONTABIL
      LEFT JOIN W_LF_MATRIZ_FISCAL J (NOLOCK) ON
         A.COD_MATRIZ_FISCAL        = J.COD_CLIFOR
      LEFT JOIN CTB_ESPECIE_SERIE L (NOLOCK) ON
         E.ESPECIE_SERIE            = L.ESPECIE_SERIE
      LEFT JOIN W_CTB_MATRIZ_CONTABIL M ON
		 B.MATRIZ					= M.NOME_CLIFOR
WHERE A.ID_IMPOSTO NOT IN (14, 22) AND A.CODIGO_FISCAL_OPERACAO < '9000'


GO


