exec sp_executesql N'
/* lx005102spk  CursorAdapter: CUR_V_ENTRADAS_00_FAT_ITENS(Alias: v_entradas_00_fat_itens)  */
SELECT FATURAMENTO_ITEM.FILIAL, FATURAMENTO_ITEM.NF_SAIDA, FATURAMENTO_ITEM.SERIE_NF, FATURAMENTO_ITEM.QTDE_RETORNAR_BENEFICIAMENTO AS QTDE_RETORNO, FATURAMENTO_ITEM.QTDE_RETORNAR_BENEFICIAMENTO AS QTDE_DISPONIVEL, CAST((FATURAMENTO_ITEM.QTDE_RETORNAR_BENEFICIAMENTO * FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO ) AS NUMERIC(14,2)) AS VALOR_RETORNO, FATURAMENTO_ITEM.ITEM_IMPRESSAO, FATURAMENTO_ITEM.ITEM_IMPRESSAO AS ITEM, FATURAMENTO_ITEM.SUB_ITEM_TAMANHO, FATURAMENTO.EMISSAO, FATURAMENTO_ITEM.CODIGO_ITEM, FATURAMENTO_ITEM.DESCRICAO_ITEM, FATURAMENTO_ITEM.MPADRAO_PRECO_UNITARIO AS PRECO_UNITARIO, FATURAMENTO_ITEM.DESCONTO_ITEM, FATURAMENTO_ITEM.UNIDADE, FATURAMENTO_ITEM.CLASSIF_FISCAL, FATURAMENTO_ITEM.TRIBUT_ORIGEM, FATURAMENTO_ITEM.TRIBUT_ORIGEM, FATURAMENTO_ITEM.CONTA_CONTABIL, FATURAMENTO_ITEM.INDICADOR_CFOP, FATURAMENTO_ITEM.TRIBUT_ICMS, FATURAMENTO_ITEM.UNIDADE, CONVERT(DECIMAL, 1) AS FATOR_CONVERSAO_UNIDADE, DBO.FX_PRODUCAO_PRECO((CAST(DBO.FX_PRODUCAO_PRECO(FATURAMENTO_ITEM.TIMESTAMP, ''F'') AS NUMERIC(14,2)) * POWER((CASE WHEN ISNULL(FATURAMENTO.CAMBIO_NA_DATA, 0) = 0 THEN 1 ELSE FATURAMENTO.CAMBIO_NA_DATA END ), (CASE WHEN DBO.FX_PARAMETRO(''CAMBIO_NA_MOEDA_PADRAO'') = ''.F.'' THEN -1 ELSE 1 END ))), ''T'') AS TIMESTAMP, FATURAMENTO_ITEM.COMISSAO_ITEM, FATURAMENTO_ITEM.COMISSAO_ITEM_GERENTE, REPRESENTANTES.COD_REPRESENTANTE, REPRESENTANTES2.COD_REPRESENTANTE AS COD_REPRESENTANTE_GERENTE, FATURAMENTO_ITEM.REFERENCIA, FATURAMENTO_ITEM.REFERENCIA_ITEM, FATURAMENTO_ITEM.REFERENCIA_PEDIDO, TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO, CTB_CONTA_PLANO.DESC_CONTA, CLASSIF_FISCAL.DESC_CLASSIFICACAO, CTB_LX_INDICADOR_CFOP.DESCRICAO_INDICADOR_CFOP, FATURAMENTO.PORC_ENCARGO, FATURAMENTO.PORC_DESCONTO, CONVERT(BIT, 1) AS PORC_DESCONTO_DIGITADO, FATURAMENTO.CODIGO_LOCAL_ENTREGA, FATURAMENTO.NOME_CLIFOR_ENTREGA, FATURAMENTO.REPRESENTANTE, FATURAMENTO.GERENTE, FATURAMENTO_ITEM.FAIXA, FATURAMENTO_ITEM.COD_TABELA_FILHA, FATURAMENTO.AGRUPAMENTO_ITENS, FATURAMENTO_ITEM.CODIGO_FISCAL_OPERACAO AS CFOP, ISNULL(CASE WHEN CONVERT(INT, @P1)=241 THEN CTB_LX_NATUREZAS_OPERACAO.CFOP_RETORNO_DEVOLUCAO ELSE CTB_LX_NATUREZAS_OPERACAO.CFOP_RETORNO_SIMBOLICO END, SPACE(4)) AS CODIGO_FISCAL_OPERACAO, FATURAMENTO.NOME_CLIFOR AS TERCEIRO_SAIDA,  CAST('''' AS CHAR(15)) NATUREZA, CAST('''' AS CHAR(10)) ITEM_COMPOSICAO FROM FATURAMENTO_ITEM INNER JOIN FATURAMENTO ON FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL AND FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA AND FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF INNER JOIN TRIBUT_ICMS ON FATURAMENTO_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS INNER JOIN CTB_LX_INDICADOR_CFOP ON FATURAMENTO_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP INNER JOIN CLASSIF_FISCAL ON FATURAMENTO_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL INNER JOIN TRIBUT_ORIGEM ON TRIBUT_ORIGEM.TRIBUT_ORIGEM = FATURAMENTO_ITEM.TRIBUT_ORIGEM INNER JOIN CTB_LX_NATUREZAS_OPERACAO ON CTB_LX_NATUREZAS_OPERACAO.CODIGO_FISCAL_OPERACAO = FATURAMENTO_ITEM.CODIGO_FISCAL_OPERACAO INNER JOIN NATUREZAS_SAIDAS ON FATURAMENTO.NATUREZA_SAIDA = NATUREZAS_SAIDAS.NATUREZA_SAIDA INNER JOIN CTB_LX_TIPO_OPERACAO ON NATUREZAS_SAIDAS.CTB_TIPO_OPERACAO = CTB_LX_TIPO_OPERACAO.CTB_TIPO_OPERACAO LEFT JOIN CTB_CONTA_PLANO ON FATURAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL LEFT JOIN REPRESENTANTES ON FATURAMENTO.REPRESENTANTE = REPRESENTANTES.REPRESENTANTE LEFT JOIN REPRESENTANTES AS REPRESENTANTES2 ON FATURAMENTO.GERENTE = REPRESENTANTES2.REPRESENTANTE INNER JOIN FILIAIS ON FATURAMENTO.FILIAL = FILIAIS.FILIAL WHERE  FATURAMENTO.NOME_CLIFOR = ''CARLOS ALBERTO DA SILVA G'' AND  Ctb_lx_tipo_operacao.TIPO_OPERACAO = ''R''  AND FATURAMENTO.SERIE_NF NOT IN ( @P2, @P3 )  AND FATURAMENTO.FILIAL = ''DR VAREJO'' AND  Faturamento.nf_saida = ''0056705'' AND  Faturamento.serie_nf = ''55'' AND  Faturamento.COD_TRANSACAO IN (''FATURAMENTO_022'', ''FATURAMENTO_030'', ''FATURAMENTO_037'', ''FATURAMENTO_052'') AND FATURAMENTO_ITEM.QTDE_RETORNAR_BENEFICIAMENTO > 0',N'@P1 int,@P2 varchar(2),@P3 varchar(2)',242,'E1','E1'

select QTDE_RETORNAR_BENEFICIAMENTO,* from FATURAMENTO_ITEM
WHERE NF_SAIDA='0056705' AND SERIE_NF='55'

UPDATE FATURAMENTO_ITEM
SET QTDE_RETORNAR_BENEFICIAMENTO=QTDE_ITEM
WHERE NF_SAIDA IN ('0056705','0056704','0057623','0058692','0060522') AND SERIE_NF='55' AND QTDE_RETORNAR_BENEFICIAMENTO=0


SELECT ENTRADA_ITEM_RELACIONADO.NOME_CLIFOR, ENTRADA_ITEM_RELACIONADO.NF_ENTRADA, ENTRADA_ITEM_RELACIONADO.SERIE_NF_ENTRADA, ENTRADA_ITEM_RELACIONADO.ITEM_RELACIONADO, ENTRADA_ITEM_RELACIONADO.TIPO_ITEM_RELACIONADO, ENTRADA_ITEM_RELACIONADO.FAT_FILIAL AS FILIAL, ENTRADA_ITEM_RELACIONADO.FAT_NF_SAIDA AS NF_SAIDA, ENTRADA_ITEM_RELACIONADO.FAT_SERIE_NF AS SERIE_NF, ENTRADA_ITEM_RELACIONADO.ITEM_IMPRESSAO, ENTRADA_ITEM_RELACIONADO.FAT_ITEM_IMPRESSAO AS ITEM, ENTRADA_ITEM_RELACIONADO.FAT_SUB_ITEM_TAMANHO AS SUB_ITEM_TAMANHO, ENTRADA_ITEM_RELACIONADO.QTDE_RELACIONADA AS QTDE_RETORNO, ENTRADA_ITEM_RELACIONADO.VALOR_RELACIONADO AS VALOR_RETORNO, ENTRADA_ITEM_RELACIONADO.QTDE_PERDA_PROCESSO, ENTRADA_ITEM_RELACIONADO.CODIGO_FISCAL_OPERACAO, ENTRADA_ITEM_RELACIONADO.QTDE_NAO_BENEFICIADA, ENTRADA_ITEM_RELACIONADO.ITEM_IMPRESSAO AS ITEM_IMPRESSAO_ENTRADA, FATURAMENTO_ITEM.QTDE_RETORNAR_BENEFICIAMENTO AS QTDE_DISPONIVEL, FATURAMENTO_ITEM.CODIGO_ITEM, FATURAMENTO_ITEM.DESCRICAO_ITEM, FATURAMENTO.EMISSAO, FATURAMENTO_ITEM.CODIGO_ITEM, FATURAMENTO_ITEM.DESCRICAO_ITEM, CAST(( ENTRADA_ITEM_RELACIONADO.VALOR_RELACIONADO / ( CASE WHEN ENTRADA_ITEM_RELACIONADO.QTDE_RELACIONADA = 0 THEN 1 ELSE ENTRADA_ITEM_RELACIONADO.QTDE_RELACIONADA END ) ) AS NUMERIC(17,5))AS PRECO_UNITARIO, FATURAMENTO_ITEM.DESCONTO_ITEM, FATURAMENTO_ITEM.UNIDADE, FATURAMENTO_ITEM.CLASSIF_FISCAL, FATURAMENTO_ITEM.TRIBUT_ORIGEM, FATURAMENTO_ITEM.TRIBUT_ORIGEM, FATURAMENTO_ITEM.CONTA_CONTABIL, FATURAMENTO_ITEM.INDICADOR_CFOP, FATURAMENTO_ITEM.TRIBUT_ICMS, FATURAMENTO_ITEM.UNIDADE, CONVERT(DECIMAL, 1) AS FATOR_CONVERSAO_UNIDADE, DBO.FX_PRODUCAO_PRECO(CAST(( DBO.FX_PRODUCAO_PRECO(FATURAMENTO_ITEM.TIMESTAMP, 'F') * POWER(( CASE WHEN ISNULL(FATURAMENTO.CAMBIO_NA_DATA, 0) = 0 THEN 1 ELSE FATURAMENTO.CAMBIO_NA_DATA END ), ( CASE WHEN DBO.FX_PARAMETRO('CAMBIO_NA_MOEDA_PADRAO') = '.T.' THEN 1 ELSE -1 END )) ) AS NUMERIC(14,2)), 'T') AS TIMESTAMP, FATURAMENTO_ITEM.COMISSAO_ITEM, FATURAMENTO_ITEM.COMISSAO_ITEM_GERENTE, REPRESENTANTES.COD_REPRESENTANTE, REPRESENTANTES2.COD_REPRESENTANTE AS COD_REPRESENTANTE_GERENTE, FATURAMENTO_ITEM.REFERENCIA, FATURAMENTO_ITEM.REFERENCIA_ITEM, FATURAMENTO_ITEM.REFERENCIA_PEDIDO, TRIBUT_ICMS.DESCRICAO AS TRIBUT_ICMS_DESCRICAO, TRIBUT_ORIGEM.DESCRICAO AS TRIBUT_ORIGEM_DESCRICAO, CTB_CONTA_PLANO.DESC_CONTA, CLASSIF_FISCAL.DESC_CLASSIFICACAO, CTB_LX_INDICADOR_CFOP.DESCRICAO_INDICADOR_CFOP, FATURAMENTO.PORC_ENCARGO, FATURAMENTO.PORC_DESCONTO, CONVERT(BIT, 1) AS PORC_DESCONTO_DIGITADO, FATURAMENTO.CODIGO_LOCAL_ENTREGA, FATURAMENTO.NOME_CLIFOR_ENTREGA, FATURAMENTO.REPRESENTANTE, FATURAMENTO.GERENTE, FATURAMENTO_ITEM.FAIXA, FATURAMENTO_ITEM.COD_TABELA_FILHA, FATURAMENTO.AGRUPAMENTO_ITENS, FATURAMENTO.NOME_CLIFOR AS TERCEIRO_SAIDA, FATURAMENTO_ITEM.ORIGEM_ITEM, ENTRADA_ITEM_RELACIONADO.ITEM_IMPRESSAO,  ENTRADA_ITEM_RELACIONADO.NATUREZA 
FROM ENTRADA_ITEM_RELACIONADO 
INNER JOIN FATURAMENTO_ITEM ON ENTRADA_ITEM_RELACIONADO.FAT_FILIAL = FATURAMENTO_ITEM.FILIAL AND ENTRADA_ITEM_RELACIONADO.FAT_NF_SAIDA = FATURAMENTO_ITEM.NF_SAIDA AND ENTRADA_ITEM_RELACIONADO.FAT_SERIE_NF = FATURAMENTO_ITEM.SERIE_NF AND ENTRADA_ITEM_RELACIONADO.FAT_ITEM_IMPRESSAO = FATURAMENTO_ITEM.ITEM_IMPRESSAO AND ENTRADA_ITEM_RELACIONADO.FAT_SUB_ITEM_TAMANHO = FATURAMENTO_ITEM.SUB_ITEM_TAMANHO 
INNER JOIN FATURAMENTO ON FATURAMENTO_ITEM.FILIAL = FATURAMENTO.FILIAL AND FATURAMENTO_ITEM.NF_SAIDA = FATURAMENTO.NF_SAIDA AND FATURAMENTO_ITEM.SERIE_NF = FATURAMENTO.SERIE_NF 
INNER JOIN TRIBUT_ICMS ON FATURAMENTO_ITEM.TRIBUT_ICMS = TRIBUT_ICMS.TRIBUT_ICMS 
INNER JOIN CTB_LX_INDICADOR_CFOP ON FATURAMENTO_ITEM.INDICADOR_CFOP = CTB_LX_INDICADOR_CFOP.INDICADOR_CFOP 
INNER JOIN CLASSIF_FISCAL ON FATURAMENTO_ITEM.CLASSIF_FISCAL = CLASSIF_FISCAL.CLASSIF_FISCAL 
INNER JOIN TRIBUT_ORIGEM ON TRIBUT_ORIGEM.TRIBUT_ORIGEM = FATURAMENTO_ITEM.TRIBUT_ORIGEM 
LEFT JOIN CTB_CONTA_PLANO ON FATURAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL 
LEFT JOIN REPRESENTANTES ON FATURAMENTO.REPRESENTANTE = REPRESENTANTES.REPRESENTANTE 
LEFT JOIN REPRESENTANTES REPRESENTANTES2 ON FATURAMENTO.GERENTE=REPRESENTANTES2.REPRESENTANTE 
WHERE ENTRADA_ITEM_RELACIONADO.NF_ENTRADA = ?V_ENTRADAS_00.NF_ENTRADA AND ENTRADA_ITEM_RELACIONADO.NOME_CLIFOR = ?V_ENTRADAS_00.NOME_CLIFOR AND ENTRADA_ITEM_RELACIONADO.SERIE_NF_ENTRADA = ?V_ENTRADAS_00.SERIE_NF_ENTRADA


SELECT * FROM FATURAMENTO_ITEM A
JOIN FATURAMENTO B ON B.NF_SAIDA=A.NF_SAIDA AND B.SERIE_NF=A.SERIE_NF
WHERE A.COD_TABELA_FILHA = 'T' AND B.EMISSAO BETWEEN '20170801' AND GETDATE()


--- ATUALIZAR TODOS OS ITENS QUE FORAM EMITIDOS SEM INDICATIVO DE NFE DE ENVIO
UPDATE C
SET C.DESCRICAO_ITEM=RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA
--SELECT C.*, RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA 
FROM W_ORDEM_SERVICO_ORDEM_PRODUCAO_RETORNO A
JOIN W_ORDEM_SERVICO_ORDEM_PRODUCAO_ENVIO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
JOIN FATURAMENTO_ITEM C WITH (NOLOCK) ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF --AND SUBSTRING(C.CODIGO_ITEM,1,7)=A.ORDEM_SERVICO
JOIN FATURAMENTO D WITH (NOLOCK) ON D.NF_SAIDA=C.NF_SAIDA AND D.SERIE_NF=C.SERIE_NF
WHERE A.ORDEM_PRODUCAO=B.ORDEM_PRODUCAO   
AND C.COD_TABELA_FILHA = 'T'
AND D.EMISSAO BETWEEN '20170801' AND '20170820'--GETDATE()



UPDATE C
SET C.DESCRICAO_ITEM=RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA
SELECT RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA 
FROM W_ORDEM_SERVICO_ORDEM_PRODUCAO_RETORNO A
JOIN W_ORDEM_SERVICO_ORDEM_PRODUCAO_ENVIO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
JOIN FATURAMENTO_ITEM C WITH (NOLOCK) ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF --AND SUBSTRING(C.CODIGO_ITEM,1,7)=A.ORDEM_SERVICO
WHERE A.NF_SAIDA='0000751'
AND A.SERIE_NF='102'
AND A.ORDEM_SERVICO=SUBSTRING('0678549',1,7)
AND A.ORDEM_PRODUCAO=B.ORDEM_PRODUCAO   
AND C.COD_TABELA_FILHA = 'T'

UPDATE C
SET C.DESCRICAO_ITEM=RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA
--SELECT RTRIM(C.DESCRICAO_ITEM)+' OP:'+RTRIM(A.ORDEM_PRODUCAO)+' NF:'+B.NF_SAIDA 
FROM W_ORDEM_SERVICO_ORDEM_PRODUCAO_RETORNO A
JOIN W_ORDEM_SERVICO_ORDEM_PRODUCAO_ENVIO B ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO
JOIN FATURAMENTO_ITEM C WITH (NOLOCK) ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF --AND SUBSTRING(C.CODIGO_ITEM,1,7)=A.ORDEM_SERVICO
WHERE A.NF_SAIDA='0000738'
AND A.SERIE_NF='112'
AND A.ORDEM_SERVICO=SUBSTRING('0747814',1,7)
AND A.ORDEM_PRODUCAO=B.ORDEM_PRODUCAO   
AND C.COD_TABELA_FILHA = 'T'


INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
SELECT PRODUTO,'P',CONTA_CONTABIL,INDICADOR_CFOP FROM PRODUTOS A
WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.PRODUTO) AND A.PRODUTO <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL
----
INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
SELECT MATERIAL,'M',CONTA_CONTABIL,INDICADOR_CFOP FROM MATERIAIS A
WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.MATERIAL) AND A.MATERIAL <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL
----
INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
SELECT CODIGO_ITEM,'I',CONTA_CONTABIL,INDICADOR_CFOP FROM CADASTRO_ITEM_FISCAL A
WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.CODIGO_ITEM) AND A.CODIGO_ITEM <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL


INSERT INTO PARAMETROS_IMPORT_XML( [CODIGO_FISCAL_OPERACAO]
      ,[NATUREZA_ENTRADA]
      ,[RATEIO_CENTRO_CUSTO]
      ,[TIPO_ENTRADAS]
      ,[RATEIO_FILIAL]
      ,[COD_CLIFOR_SACADO]
      ,[natOp]
      ,[COD_TRANSACAO])
SELECT [CODIGO_FISCAL_OPERACAO]
      ,[NATUREZA_ENTRADA]
      ,[RATEIO_CENTRO_CUSTO]
      ,[TIPO_ENTRADAS]
      ,[RATEIO_FILIAL]
      ,'000608'--[COD_CLIFOR_SACADO]
      ,[natOp]
      ,[COD_TRANSACAO]
FROM DESENV.DBO.PARAMETROS_IMPORT_XML


SELECT * FROM PARAMETROS_IMPORT_XML

SELECT * FROM CADASTRO_CLI_FOR
WHERE CGC_CPF='03063646000106'


UPDATE PARAMETROS_IMPORT_XML
SET CODIGO_FISCAL_OPERACAO='1903',
NATUREZA_ENTRADA='241.01',
RATEIO_CENTRO_CUSTO='8007',
TIPO_ENTRADAS='MATERIA PRIMA',
RATEIO_FILIAL='000001',
COD_CLIFOR_SACADO='000608',
NATOP='RETORNO INSUMOS NAO APLIC. INDUSTRIAL.'
WHERE CODIGO_FISCAL_OPERACAO='1903'

UPDATE PARAMETROS_IMPORT_XML
SET NATOP='RETORNO DE MERCADORIA INDUSTRIALIZADA'
WHERE CODIGO_FISCAL_OPERACAO='1902'

UPDATE PARAMETROS_IMPORT_XML
SET COD_CLIFOR_SACADO='700095'


SELECT * FROM XML_NFE_CAPA
WHERE CHNFE='23170803063646000106551020000007511455254716'

SELECT case when charindex('NF:',xProd) > 0 then substring(xProd,charindex('NF:',xProd)+3,10) else '' end,* FROM XML_NFE_ITEM
WHERE CHNFE='23170803063646000106551020000007511455254716'

SELECT * FROM FATURAMENTO_ITEM
WHERE NF_SAIDA='0000751' AND SERIE_NF='102'

ELASTICO POLIESTER - 09 MM - 120% OP:225333 NF:0044146        



--- INICIO TESTE

-- CAPA NFe
DECLARE @XML XML
SET @XML = (
SELECT CAST(BulkColumn AS XML)
FROM OPENROWSET(BULK N'c:\temp\xml\23170803063646000106551020000007521303944350-procNFe.xml', SINGLE_BLOB) -- Informe onde se encontra o arquivo XML
AS Arquivo)
 
;WITH XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe') -- Este ponto deve ser informado o NAMESPACE (xmlns), senão informar esta linha ele não retorna.
 
INSERT INTO XML_NFE_CAPA (chNFe,nProt,dhRecbto,cUF,cNF,natOp,indPag,mod,serie,nNF,dhEmi,dhSaiEnt,tpNF,idDest,cMunFG,tpImp,
tpEmis,cDV,tpAmb,finNFe,indFinal,indPres,procEmi,emit_CNPJ,emit_xNome,emit_xFant,emit_xLgr,emit_nro,emit_xBairro,emit_cMun,
emit_xMun,emit_UF,emit_CEP,emit_cPais,emit_xPais,emit_fone,emit_IE,emit_CRT,dest_CNPJ,dest_xNome,dest_xLgr,dest_nro,dest_xBairro,
dest_cMun,dest_xMun,dest_UF,dest_CEP,dest_cPais,dest_xPais,dest_fone,dest_indIEDest,dest_IE,dest_email,infAdic)

SELECT
		NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') as chNFe
	,              NFe.value('../../../protNFe[1]/infProt[1]/nProt[1]', 'varchar(20)') as nProt
	,              NFe.value('../../../protNFe[1]/infProt[1]/dhRecbto[1]', 'datetime') as dhRecbto
	,              NFe.value('cUF[1]', 'char(2)') as cUF
	,              NFe.value('cNF[1]', 'char(10)') AS cNF
	,              NFe.value('natOp[1]','varchar(max)') as natOp
	,              NFe.value('indPag[1]', 'int') as indPag
	,              NFe.value('mod[1]', 'int') as mod
	,              NFe.value('serie[1]','int') as serie
	,              NFe.value('nNF[1]','char(10)') as nNF
	,              NFe.value('dhEmi[1]','datetime') as dhEmi
	,              NFe.value('dhSaiEnt[1]','datetime') as dhSaiEnt
	,              NFe.value('tpNF[1]','int') as tpNF
	,              NFe.value('idDest[1]','int') as idDest
	,              NFe.value('cMunFG[1]','int') as cMunFG
	,              NFe.value('tpImp[1]','int') as tpImp
	,              NFe.value('tpEmis[1]','int') as tpEmis
	,              NFe.value('cDV[1]','int') as cDV
	,              NFe.value('tpAmb[1]','int') as tpAmb
	,              NFe.value('finNFe[1]','int') as finNFe
	,              NFe.value('indFinal[1]','int') as indFinal
	,              NFe.value('indPres[1]','int') as indPres
	,              NFe.value('procEmi[1]','int') as procEmi
	,              NFe.value('../emit[1]/CNPJ[1]','varchar(20)') as emit_CNPJ
	,              NFe.value('../emit[1]/xNome[1]','varchar(80)') as emit_xNome
	,              NFe.value('../emit[1]/xFant[1]','varchar(30)') as emit_xFant
	,              NFe.value('../emit[1]/enderEmit[1]/xLgr[1]','varchar(max)') as emit_xLgr
	,              NFe.value('../emit[1]/enderEmit[1]/nro[1]','varchar(50)') as emit_nro
	,              NFe.value('../emit[1]/enderEmit[1]/xBairro[1]','varchar(max)') as emit_xBairro
	,              NFe.value('../emit[1]/enderEmit[1]/cMun[1]','int') as emit_cMun
	,              NFe.value('../emit[1]/enderEmit[1]/xMun[1]','varchar(50)') as emit_xMun
	,              NFe.value('../emit[1]/enderEmit[1]/UF[1]','char(2)') as emit_UF
	,              NFe.value('../emit[1]/enderEmit[1]/CEP[1]','char(10)') as emit_CEP
	,              NFe.value('../emit[1]/enderEmit[1]/cPais[1]','char(6)') as emit_cPais
	,              NFe.value('../emit[1]/enderEmit[1]/xPais[1]','char(20)') as emit_xPais
	,              NFe.value('../emit[1]/enderEmit[1]/fone[1]','char(20)') as emit_fone
	,              NFe.value('../emit[1]/IE[1]','char(20)') as emit_IE
	,              NFe.value('../emit[1]/CRT[1]','int') as emit_CRT
	,              NFe.value('../dest[1]/CNPJ[1]','varchar(20)') as dest_CNPJ
	,              NFe.value('../dest[1]/xNome[1]','varchar(80)') as dest_xNome
	,              NFe.value('../dest[1]/enderDest[1]/xLgr[1]','varchar(max)') as dest_xLgr
	,              NFe.value('../dest[1]/enderDest[1]/nro[1]','varchar(50)') as dest_nro
	,              NFe.value('../dest[1]/enderDest[1]/xBairro[1]','varchar(max)') as dest_xBairro
	,              NFe.value('../dest[1]/enderDest[1]/cMun[1]','int') as dest_cMun
	,              NFe.value('../dest[1]/enderDest[1]/xMun[1]','varchar(50)') as dest_xMun
	,              NFe.value('../dest[1]/enderDest[1]/UF[1]','char(2)') as dest_UF
	,              NFe.value('../dest[1]/enderDest[1]/CEP[1]','char(10)') as dest_CEP
	,              NFe.value('../dest[1]/enderDest[1]/cPais[1]','char(6)') as dest_cPais
	,              NFe.value('../dest[1]/enderDest[1]/xPais[1]','char(20)') as dest_xPais
	,              NFe.value('../dest[1]/enderDest[1]/fone[1]','char(20)') as dest_fone
	,              NFe.value('../dest[1]/indIEDest[1]','int') as dest_indIEDest
	,              NFe.value('../dest[1]/IE[1]','char(20)') as dest_IE
	,              NFe.value('../dest[1]/email[1]','varchar(80)') as dest_email
	,              NFe.value('../infAdic[1]/infCpl[1]','varchar(max)') as infAdic
FROM @XML.nodes('//infNFe/ide') AS NFes(NFe) -- Caminho que ira iniciar a varredura
where not exists (select * from XML_NFE_CAPA where chNFe=NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)'))

-- ITENS NFE
DECLARE @XML XML
SET @XML = (
SELECT CAST(BulkColumn AS XML)
FROM OPENROWSET(BULK N'C:\TEMP\XML\23170600119633000113550560000435951190974060-procNFe.xml', SINGLE_BLOB) -- Informe onde se encontra o arquivo XML
AS Arquivo)
 
;WITH XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe') -- Este ponto deve ser informado o NAMESPACE (xmlns), senão informar esta linha ele não retorna.
 
INSERT INTO XML_NFE_ITEM(chNFe,nItem,cProd,cEAN,xProd,NCM,CFOP,uCom,qCom,vUnCom,vProd,cEANTrib,uTrib,qTrib,vUnTrib,indTot,infAdProd,
vTotTrib,ICMS_orig,ICMS_CST,ICMS_modBC,ICMS_vBC,ICMS_pICMS,ICMS_vICMS,IPI_cEnq,IPI_CST,IPI_vBC,IPI_pIPI,IPI_vIPI,PIS_CST,PIS_vBC,
PIS_pPIS,PIS_vPIS,COFINS_CST,COFINS_vBC,COFINS_pCOFINS,COFINS_vCOFINS)
 
SELECT
       NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') AS chNFe
,      NFe.value('@nItem', 'int') AS nItem
,      NFe.value('prod[1]/cProd[1]','varchar(50)') AS cProd
,      NFe.value('prod[1]/cEAN[1]','varchar(30)') AS cEAN
,      NFe.value('prod[1]/xProd[1]','varchar(max)') AS xProd
,      NFe.value('prod[1]/NCM[1]','varchar(20)') AS NCM
,      NFe.value('prod[1]/CFOP[1]','varchar(4)') AS CFOP
,      NFe.value('prod[1]/uCom[1]','varchar(10)') AS uCom
,      NFe.value('prod[1]/qCom[1]','numeric(15,4)') AS qCom
,      NFe.value('prod[1]/vUnCom[1]','numeric(25,10)') AS vUnCom
,      NFe.value('prod[1]/vProd[1]','numeric(15,2)') AS vProd
,      NFe.value('prod[1]/cEANTrib[1]','varchar(30)') AS cEANTrib
,      NFe.value('prod[1]/uTrib[1]','varchar(10)') AS uTrib
,      NFe.value('prod[1]/qTrib[1]','numeric(15,4)') AS qTrib
,      NFe.value('prod[1]/vUnTrib[1]','numeric(25,10)') AS vUnTrib
,      NFe.value('prod[1]/indTot[1]','char(1)') AS indTot
,      NFe.value('prod[1]/infAdProd[1]','varchar(max)') AS infAdProd
       -- ICMS
,      NFe.value('imposto[1]/vTotTrib[1]','numeric(14,2)') AS vTotTrib
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/orig[1]','int') AS ICMS_orig
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/CST[1]','char(5)') AS ICMS_CST
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/modBC[1]','int') AS ICMS_modBC
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/vBC[1]','numeric(14,2)') AS ICMS_vBC
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/pICMS[1]','numeric(18,4)') AS ICMS_pICMS
,      NFe.value('imposto[1]/ICMS[1]/ICMS40[1]/vICMS[1]','numeric(14,2)') AS ICMS_vICMS
       -- IPI
,      NFe.value('imposto[1]/IPI[1]/cEnq[1]','char(3)') AS IPI_cEnq
,      NFe.value('imposto[1]/IPI[1]/IPITrib[1]/CST[1]','char(3)') AS IPI_CST
,      NFe.value('imposto[1]/IPI[1]/IPITrib[1]/vBC[1]','numeric(14,2)') AS IPI_vBC
,      NFe.value('imposto[1]/IPI[1]/IPITrib[1]/pIPI[1]','numeric(18,4)') AS IPI_pIPI
,      NFe.value('imposto[1]/IPI[1]/IPITrib[1]/vIPI[1]','numeric(14,2)') AS IPI_vIPI
       -- PIS
,      NFe.value('imposto[1]/PIS[1]/PISAliq[1]/CST[1]','char(3)') AS PIS_CST
,      NFe.value('imposto[1]/PIS[1]/PISAliq[1]/vBC[1]','numeric(14,2)') AS PIS_vBC
,      NFe.value('imposto[1]/PIS[1]/PISAliq[1]/pPIS[1]','numeric(18,4)') AS PIS_pPIS
,      NFe.value('imposto[1]/PIS[1]/PISAliq[1]/vPIS[1]','numeric(14,2)') AS PIS_vPIS
       -- COFINS
,      NFe.value('imposto[1]/COFINS[1]/COFINSAliq[1]/CST[1]','char(3)') AS COFINS_CST
,      NFe.value('imposto[1]/COFINS[1]/COFINSAliq[1]/vBC[1]','numeric(14,2)') AS COFINS_vBC
,      NFe.value('imposto[1]/COFINS[1]/COFINSAliq[1]/pCOFINS[1]','numeric(18,4)') AS COFINS_pCOFINS
,      NFe.value('imposto[1]/COFINS[1]/COFINSAliq[1]/vCOFINS[1]','numeric(14,2)') AS COFINS_vCOFINS
FROM @XML.nodes('//infNFe/det') AS NFes(NFe) -- Caminho que ira iniciar a varredura
where not exists (select * from XML_NFE_ITEM where chNFe=NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') and nItem=NFe.value('@nItem', 'int'))
order by nItem


 
 
-- TOTAL NFE
DECLARE @XML XML
SET @XML = (
SELECT CAST(BulkColumn AS XML)
FROM OPENROWSET(BULK N'C:\TEMP\XML\23170600119633000113550560000435951190974060-procNFe.xml', SINGLE_BLOB) -- Informe onde se encontra o arquivo XML
AS Arquivo)
 
;WITH XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe') -- Este ponto deve ser informado o NAMESPACE (xmlns), senão informar esta linha ele não retorna.
 
INSERT INTO XML_NFE_TOTAL(chNFe,vBC,vICMS,vICMSDeson,vBCST,vST,vProd,vFrete,vSeg,vDesc,vII,vIPI,vPIS,vCOFINS,vOutro,vNF,vTotTrib)
SELECT
       NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') AS chNFe
,      NFe.value('ICMSTot[1]/vBC[1]','numeric(14,2)') AS vBC
,      NFe.value('ICMSTot[1]/vICMS[1]','numeric(14,2)') AS vICMS
,      NFe.value('ICMSTot[1]/vICMSDeson[1]','numeric(14,2)') AS vICMSDeson
,      NFe.value('ICMSTot[1]/vBCST[1]','numeric(14,2)') AS vBCST
,      NFe.value('ICMSTot[1]/vST[1]','numeric(14,2)') AS vST
,      NFe.value('ICMSTot[1]/vProd[1]','numeric(14,2)') AS vProd
,      NFe.value('ICMSTot[1]/vFrete[1]','numeric(14,2)') AS vFrete
,      NFe.value('ICMSTot[1]/vSeg[1]','numeric(14,2)') AS vSeg
,      NFe.value('ICMSTot[1]/vDesc[1]','numeric(14,2)') AS vDesc
,      NFe.value('ICMSTot[1]/vII[1]','numeric(14,2)') AS vII
,      NFe.value('ICMSTot[1]/vIPI[1]','numeric(14,2)') AS vIPI
,      NFe.value('ICMSTot[1]/vPIS[1]','numeric(14,2)') AS vPIS
,      NFe.value('ICMSTot[1]/vCOFINS[1]','numeric(14,2)') AS vCOFINS
,      NFe.value('ICMSTot[1]/vOutro[1]','numeric(14,2)') AS vOutro
,      NFe.value('ICMSTot[1]/vNF[1]','numeric(14,2)') AS vNF
,      NFe.value('ICMSTot[1]/vTotTrib[1]','numeric(14,2)') AS vTotTrib
--,      NFe.value('../cobr[1]/fat[1]/nFat[1]','numeric(14,2)') AS nFat
--,      NFe.value('../cobr[1]/fat[1]/vOrig[1]','numeric(14,2)') AS vOrig
--,      NFe.value('../cobr[1]/fat[1]/vLiq[1]','numeric(14,2)') AS vLiq
FROM @XML.nodes('//infNFe/total') AS NFes(NFe) -- Caminho que ira iniciar a varredura
 
 
-- Transportadora NFE
DECLARE @XML XML
SET @XML = (
SELECT CAST(BulkColumn AS XML)
FROM OPENROWSET(BULK N'C:\TEMP\XML\23170600119633000113550560000435951190974060-procNFe.xml', SINGLE_BLOB) -- Informe onde se encontra o arquivo XML
AS Arquivo)
 
;WITH XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe') -- Este ponto deve ser informado o NAMESPACE (xmlns), senão informar esta linha ele não retorna.
 
INSERT INTO XML_NFE_TRANSPORTADOR(chNFe,modFrete,CNPJ,xNome,IE,xEnder,xMun,UF,qVol,esp,pesoL,pesoB)
SELECT
       NFe.value('../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') AS chNFe
,      NFe.value('modFrete[1]','int') AS modFrete
,      NFe.value('transporta[1]/CNPJ[1]','char(14)') AS CNPJ
,      NFe.value('transporta[1]/xNome[1]','varchar(80)') AS xNome
,      NFe.value('transporta[1]/IE[1]','char(20)') AS IE
,      NFe.value('transporta[1]/xEnder[1]','varchar(max)') AS xEnder
,      NFe.value('transporta[1]/xMun[1]','varchar(35)') AS xMun
,      NFe.value('transporta[1]/UF[1]','char(2)') AS UF
,      NFe.value('vol[1]/qVol[1]','int') AS qVol
,      NFe.value('vol[1]/esp[1]','varchar(40)') AS esp
,      NFe.value('vol[1]/pesoL[1]','numeric(14,3)') AS pesoL
,      NFe.value('vol[1]/pesoB[1]','numeric(14,3)') AS pesoB
FROM @XML.nodes('//infNFe/transp') AS NFes(NFe) -- Caminho que ira iniciar a varredura
 
 
 
-- Duplicatas NFE
DECLARE @XML XML
SET @XML = (
SELECT CAST(BulkColumn AS XML)
FROM OPENROWSET(BULK N'C:\TEMP\XML\23170600119633000113550560000435951190974060-procNFe.xml', SINGLE_BLOB) -- Informe onde se encontra o arquivo XML
AS Arquivo)
 
;WITH XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe') -- Este ponto deve ser informado o NAMESPACE (xmlns), senão informar esta linha ele não retorna.
 
INSERT INTO XML_NFE_DUPLICATA(chNFe,nFat,vOrig,vLiq,nDup,dVenc,vDup)
SELECT
		   NFe.value('../../../../protNFe[1]/infProt[1]/chNFe[1]', 'varchar(44)') AS chNFe
	,      NFe.value('../fat[1]/nFat[1]','char(10)') AS nFat
	,      NFe.value('../fat[1]/vOrig[1]','numeric(14,2)') AS vOrig
	,      NFe.value('../fat[1]/vLiq[1]','numeric(14,2)') AS vLiq
	,      NFe.value('nDup[1]','char(10)') AS nDup
	,      NFe.value('dVenc[1]','datetime') AS dVenc
	,      NFe.value('vDup[1]','numeric(14,2)') AS vDup
FROM @XML.nodes('//infNFe/cobr/dup') AS NFes(NFe) -- Caminho que ira iniciar a varredura


	---- POPULAR IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM
	begin
		INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
		SELECT PRODUTO,'P',CONTA_CONTABIL,INDICADOR_CFOP FROM PRODUTOS A WITH (NOLOCK)
		WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.PRODUTO) AND A.PRODUTO <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL
		----
		INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
		SELECT MATERIAL,'M',CONTA_CONTABIL,INDICADOR_CFOP FROM MATERIAIS A WITH (NOLOCK)
		WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.MATERIAL) AND A.MATERIAL <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL
		----
		INSERT INTO IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM (REFERENCIA,ORIGEM_ITEM,CONTA_CONTABIL,INDICADOR_CFOP) 
		SELECT CODIGO_ITEM,'I',CONTA_CONTABIL,INDICADOR_CFOP FROM CADASTRO_ITEM_FISCAL A WITH (NOLOCK)
		WHERE NOT EXISTS(SELECT * FROM IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM WHERE REFERENCIA=A.CODIGO_ITEM) AND A.CODIGO_ITEM <> '' AND A.CONTA_CONTABIL IS NOT NULL AND A.INDICADOR_CFOP IS NOT NULL
	end

	--- verificar os itens em FATURAMENTO_ITEM, pois o Linx retira caracteres especiais do XML
	update a
	set a.cProd=b.CODIGO_ITEM
	from XML_NFE_ITEM a with (nolock)
	join DRLINGERIE.dbo.faturamento_item b with (nolock) on substring(b.codigo_item,1,7) = substring(A.CPROD,1,7)
	join DRLINGERIE.dbo.faturamento c with (nolock) on c.CHAVE_NFE=a.chNFe
    where a.xprod like '%O.S.:%' and a.cProd <> b.CODIGO_ITEM and c.CHAVE_NFE='23170811876530000114551040000058751249106062'

    --- GRAVA OS DADOS NAS TABELAS ENTRADAS E ENTRADAS_ITEM E GERA IMPOSTOS E LANÇAMENTO CONTÁBIL
	--- entrada ordem de serviço
	---
	INSERT INTO ENTRADAS (
	NF_ENTRADA,                        
	NOME_CLIFOR,                       
	EMISSAO,                           
	FILIAL,                            
	EMPRESA,                           
	AGRUPAMENTO_ITENS,                 
	COD_TRANSACAO,                     
	NATUREZA,                          
	CONDICAO_PGTO,                     
	RECEBIMENTO,                       
	NF_FATURA,                         
	SERIE_NF_ENTRADA,                  
	TABELA_FILHA,                      
	TRANSF_FILIAL,                     
	TIPO_ENTRADAS,                     
	MOEDA,                             
	MOEDA_COMPRA,                      
	DATA_DIGITACAO,                    
	RATEIO_FILIAL,                     
	RATEIO_CENTRO_CUSTO,               
	DATA_FATURAMENTO_RELATIVO,         
	UTILIZA_DIAS_FIXOS_FORNECEDOR,     
	NOME_CLIFOR_TRIANGULAR,            
	SERIE_NF,                          
	NUMERO_ENTRADA,                    
	FATURA_NOME_CLIFOR,                
	FATURA_SERIE,                      
	FATURA_NUMERO,                     
	DIFERENCA_VALOR,                   
	QTDE_TOTAL,                        
	VALOR_TOTAL,                       
	FRETE_A_PAGAR,
	IMPORTACAO_IMPOSTO,                
	IMPORTACAO_ICMS,                   
	IMPORTACAO_IPI,                    
	IMPORTACAO_ALFANDEGA,              
	IMPORTACAO_OUTRAS_DESPESAS,        
	IMPORTACAO_FRETE,                  
	IMPORTACAO_SEGURO,                 
	IMPORTACAO_DESEMBARACO,            
	PORC_DESCONTO,                     
	PORC_ENCARGO,                      
	COMISSAO_VALOR,                    
	COMISSAO_VALOR_GERENTE,            
	VALOR_IMPOSTO_AGREGAR,             
	VALOR_SUB_ITENS,                   
	CAMBIO_NA_DATA,                    
	ESPECIE_SERIE,                     
	NOTA_CANCELADA,                    
	COD_CLIFOR_SACADO,                 
	IMPORTACAO_TX_CAPATAZIA,           
	CHAVE_NFE,
	PROTOCOLO_AUTORIZACAO_NFE,
	DATA_AUTORIZACAO_NFE,
	INFORMACAO_COMPLEMENTAR,
	TRANSPORTADORA_A_PAGAR)                          

	SELECT 
	REPLICATE(0, (7-LEN(RTRIM(A.nNF))))+RTRIM(A.nNF) AS NF_ENTRADA,                  
	C.NOME_CLIFOR,
	convert(date,A.dhEmi,103),
	D.NOME_CLIFOR,
	1,
	1,
	'ENTRADAS_108',
	F.NATUREZA_ENTRADA,
	'000',
	convert(date,A.dhSaiEnt,103),
	0,
	A.serie,
	'ENTRADAS_NF',
	0,
	F.TIPO_ENTRADAS,
	'R$',
	'R$',
	convert(date,GETDATE(),103),
	D.CLIFOR,
	F.RATEIO_CENTRO_CUSTO,
	NULL,
	0,
	C.NOME_CLIFOR,
	1,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	E.qTrib,
	E.vProd,
	1,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	0,
	E.vProd,
	1.000000,
	55,
	0,
	C.CLIFOR,
	0,
	A.chNFe,
	A.nProt,
	(A.dhRecbto-.125),
	A.infAdic,
	G.xNome
	FROM XML_NFE_CAPA A
	JOIN XML_NFE_TOTAL B ON B.chNFe=A.chNFe
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=A.emit_CNPJ
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=A.dest_CNPJ
	JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
	JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA,TIPO_ENTRADAS,RATEIO_CENTRO_CUSTO FROM PARAMETROS_IMPORT_XML) F ON F.natop=a.natOp 
	LEFT JOIN XML_NFE_TRANSPORTADOR G ON G.chNFe=A.chNFe
	where a.chNFe='23170811876530000114551040000058751249106062'
	AND NOT EXISTS(SELECT * FROM ENTRADAS WHERE CHAVE_NFE=A.CHNFE)

	--- ENTRADAS_ITEM
	INSERT INTO ENTRADAS_ITEM(
	NOME_CLIFOR,                                
	NF_ENTRADA,                                 
	SERIE_NF_ENTRADA,                           
	ITEM_IMPRESSAO,                             
	SUB_ITEM_TAMANHO,                           
	DESCRICAO_ITEM,                             
	QTDE_ITEM,                                  
	PRECO_UNITARIO,                             
	CODIGO_ITEM,                                
	DESCONTO_ITEM,                              
	VALOR_ITEM,                                 
	COD_TABELA_FILHA,                           
	TRIBUT_ICMS,                                
	TRIBUT_ORIGEM,                              
	UNIDADE,                                    
	CLASSIF_FISCAL,                             
	CODIGO_FISCAL_OPERACAO,                     
	PESO,                                       
	CONTA_CONTABIL,                             
	QTDE_RETORNAR_BENEFICIAMENTO,               
	FAIXA,                                      
	COMISSAO_ITEM,                              
	COMISSAO_ITEM_GERENTE,                      
	INDICADOR_CFOP,                             
	QTDE_DEVOLVIDA,                             
	PORCENTAGEM_ITEM_RATEIO,                    
	ID_EXCECAO_IMPOSTO,                         
	REFERENCIA,                                 
	REFERENCIA_ITEM,                            
	REFERENCIA_PEDIDO,                          
	VALOR_ENCARGOS,                             
	VALOR_DESCONTOS,                            
	NAO_SOMA_VALOR,                             
	VALOR_ENCARGOS_IMPORTACAO,                  
	RATEIO_FILIAL,                              
	RATEIO_CENTRO_CUSTO,                        
	VALOR_ENCARGOS_ADUANEIROS,                  
	PORC_ITEM_RATEIO_FRETE,                     
	ITEM_NFE,                                   
	MPADRAO_SEGURO_ITEM,                        
	MPADRAO_FRETE_ITEM,                         
	MPADRAO_ENCARGO_ITEM,                       
	ORIGEM_ITEM,
	PRECO_UNITARIO_ORIGINAL)

	SELECT 
	C.NOME_CLIFOR,
	REPLICATE(0, (7-LEN(RTRIM(B.nNF))))+RTRIM(B.nNF) AS NF_ENTRADA,
	B.SERIE,
	REPLICATE(0, (4-LEN(RTRIM(A.nItem))))+RTRIM(A.nItem) AS  nItem,
	0,
	case when charindex('O.S.:',A.xProd) > 0 then substring(A.XPROD,1,charindex('O.S.:',A.xProd)-1) else A.XPROD end,
	A.QTRIB,
	A.VUNTRIB,
	case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end,
	0,
	A.VPROD,
	'R',
	F.TRIBUT_ICMS,
	ISNULL(F.TRIBUT_ORIGEM,0),
	A.UCOM,
	A.NCM,
	I.CODIGO_FISCAL_OPERACAO,
	0,
	J.CONTA_CONTABIL,
	0,
	'1',
	0,
	0,
	J.INDICADOR_CFOP,
	0,
	((A.QTRIB*A.VUNTRIB)/E.vProd)*100,
	F.ID_EXCECAO_IMPOSTO,
	case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end,
	case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end,
	NULL,
	0,
	0,
	0,
	0,
	D.CLIFOR,
	I.RATEIO_CENTRO_CUSTO,
	0,
	((A.QTRIB*A.VUNTRIB)/E.vProd)*100,
	A.NITEM,
	0,
	0,
	0,
	J.ORIGEM_ITEM,
	A.VUNTRIB
	FROM XML_NFE_ITEM A
	JOIN XML_NFE_CAPA B ON B.chNFe=A.chNFe
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
	JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
	JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA FROM PARAMETROS_IMPORT_XML) B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
	JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA,TIPO_ENTRADAS,RATEIO_CENTRO_CUSTO,CODIGO_FISCAL_OPERACAO FROM PARAMETROS_IMPORT_XML) I ON I.natop=B.natOp 
	LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
	where a.chNFe='23170811876530000114551040000058751249106062'
	AND NOT EXISTS(SELECT * FROM ENTRADAS_ITEM WHERE NF_ENTRADA=B.NNF AND CODIGO_ITEM=A.CPROD)

	--- BUSCA NFE DE SAIDA ENVIO PARA OFICINA
	SELECT @NF_SAIDA_ENVIO = case when charindex('NF:',A.xProd) > 0 then substring(A.xProd,charindex('NF:',A.xProd)+3,10) else '' end 
	select case when charindex('NF:',A.xProd) > 0 then substring(A.xProd,charindex('NF:',A.xProd)+3,10) else '' end  FROM XML_NFE_ITEM A
	JOIN XML_NFE_CAPA B ON B.chNFe=A.chNFe
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
	JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
	JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA FROM PARAMETROS_IMPORT_XML) B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
	JOIN (SELECT DISTINCT NATOP FROM PARAMETROS_IMPORT_XML) I ON I.natop=B.natOp 
	LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
	where a.chNFe='23170811876530000114551040000058751249106062' AND XPROD LIKE '%NF:%'

	--- GERA A TABELA TEMPORARIA PARA BUSCAR ITEM DE NFE SAIDA ORIGEM 
	SELECT [CLASSIF_FISCAL],[CODIGO_FISCAL_OPERACAO],[CODIGO_ITEM],[COD_TABELA_FILHA],[COMISSAO_ITEM]
		  ,[COMISSAO_ITEM_GERENTE],[CONTA_CONTABIL],[DESCONTO_ITEM],[DESCRICAO_ITEM],[FAIXA],[FILIAL]
		  ,[ID_EXCECAO_IMPOSTO],[INDICADOR_CFOP],[ITEM_IMPRESSAO],[MPADRAO_DESCONTO_ITEM],[MPADRAO_PRECO_UNITARIO]
		  ,[MPADRAO_VALOR_ITEM],[NF_SAIDA],[PESO],[PORCENTAGEM_ITEM_RATEIO],[PRECO_UNITARIO],[QTDE_DEVOLVIDA]
		  ,[QTDE_ITEM],[QTDE_RETORNAR_BENEFICIAMENTO],[SERIE_NF],[SUB_ITEM_TAMANHO],[TRIBUT_ICMS]
		  ,[TRIBUT_ORIGEM],[UNIDADE],[VALOR_ITEM],[REFERENCIA],[REFERENCIA_ITEM],[REFERENCIA_PEDIDO]
		  ,[MPADRAO_VALOR_DESCONTOS],[MPADRAO_VALOR_ENCARGOS],[NAO_SOMA_VALOR],[OBS_ITEM],[ITEM_NFE]
		  ,[MPADRAO_SEGURO_ITEM],[MPADRAO_FRETE_ITEM],[MPADRAO_ENCARGO_ITEM],[RATEIO_FILIAL],[RATEIO_CENTRO_CUSTO]
		  ,[ORIGEM_ITEM],[VALOR_IMPOSTO_ITEM],[INDICA_PRODUTO_PROCESSO],[CODIGO_FCI],[PRECO_UNITARIO_ORIGINAL]
		  ,[CTB_TIPO_OPERACAO],[ID_SUB_PROJETO],[VALOR_IMPOSTO_ITEM_MUNICIPAL],[VALOR_IMPOSTO_ITEM_ESTADUAL],[ID_CEST_NCM]
	INTO #FATURAMENTO_ITEM_ORIGEM 
	FROM FATURAMENTO_ITEM WITH (NOLOCK)
	WHERE NF_SAIDA='0047607' AND  SERIE_NF = '56'

	--- ENTRADA_ITEM_RELACIONADO
	--- ITEM COM NF SAIDA E COD_TABELA_FILHA = 'M'
	INSERT INTO ENTRADA_ITEM_RELACIONADO ([ITEM_RELACIONADO],[QTDE_RELACIONADA],[VALOR_RELACIONADO]
		  ,[FAT_FILIAL],[FAT_NF_SAIDA],[FAT_SERIE_NF],[FAT_ITEM_IMPRESSAO],[FAT_SUB_ITEM_TAMANHO]
		  ,[QTDE_PERDA_PROCESSO],[QTDE_NAO_BENEFICIADA],[CODIGO_FISCAL_OPERACAO]
		  ,[ENT_NOME_CLIFOR],[ENT_NF_ENTRADA],[ENT_SERIE_NF_ENTRADA],[ENT_ITEM_IMPRESSAO]
		  ,[ENT_SUB_ITEM_TAMANHO],[NF_ENTRADA],[NOME_CLIFOR],[SERIE_NF_ENTRADA]
		  ,[ITEM_IMPRESSAO],[TIPO_ITEM_RELACIONADO],[SUB_ITEM_TAMANHO],[ITEM_COMPOSICAO],[NATUREZA])
	SELECT A.NITEM,A.QTRIB,A.VPROD,--L.FILIAL,L.NF_SAIDA
		  --,L.SERIE_NF,L.ITEM_IMPRESSAO,L.SUB_ITEM_TAMANHO,
		  0 AS QTDE_PERDA_PROCESSO
		  ,0 AS QTDE_NAO_BENEFICIADA,I.CODIGO_FISCAL_OPERACAO,NULL AS ENT_NOME_CLIFOR, NULL AS ENT_NF_ENTRADA
		  ,NULL AS ENT_SERIE_NF_ENTRADA,NULL AS ENT_ITEM_IMPRESSAO,NULL AS ENT_SUB_ITEM_TAMANHO
		  ,REPLICATE(0, (7-LEN(RTRIM(B.nNF))))+RTRIM(B.nNF) AS NF_ENTRADA
		  ,C.NOME_CLIFOR,B.SERIE AS SERIE_NF_ENTRADA,A.NITEM AS ITEM_IMPRESSAO,0 AS TIPO_ITEM_RELACIONADO
		  ,0 AS SUB_ITEM_TAMANHO,'304' AS ITEM_COMPOSICAO,I.NATUREZA_ENTRADA AS NATUREZA 
	FROM XML_NFE_ITEM A
	JOIN XML_NFE_CAPA B ON B.chNFe=A.chNFe
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
	JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
	JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA FROM PARAMETROS_IMPORT_XML) B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
	JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA,TIPO_ENTRADAS,RATEIO_CENTRO_CUSTO,CODIGO_FISCAL_OPERACAO FROM PARAMETROS_IMPORT_XML) I ON I.natop=B.natOp 
	LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
	--JOIN #FATURAMENTO_ITEM_ORIGEM AS L ON L.CODIGO_ITEM=A.CPROD --AND CAST(L.ITEM_IMPRESSAO AS INT)=A.nItem
	where a.chNFe='23170811876530000114551040000058751249106062' --AND L.COD_TABELA_FILHA='M'

	--- ENTRADA_ITEM_RELACIONADO
	--- ITEM COM NF SAIDA E COD_TABELA_FILHA = 'O'
	INSERT INTO ENTRADA_ITEM_RELACIONADO ([ITEM_RELACIONADO],[QTDE_RELACIONADA],[VALOR_RELACIONADO]
		  ,[FAT_FILIAL],[FAT_NF_SAIDA],[FAT_SERIE_NF],[FAT_ITEM_IMPRESSAO],[FAT_SUB_ITEM_TAMANHO]
		  ,[QTDE_PERDA_PROCESSO],[QTDE_NAO_BENEFICIADA],[CODIGO_FISCAL_OPERACAO]
		  ,[ENT_NOME_CLIFOR],[ENT_NF_ENTRADA],[ENT_SERIE_NF_ENTRADA],[ENT_ITEM_IMPRESSAO]
		  ,[ENT_SUB_ITEM_TAMANHO],[NF_ENTRADA],[NOME_CLIFOR],[SERIE_NF_ENTRADA]
		  ,[ITEM_IMPRESSAO],[TIPO_ITEM_RELACIONADO],[SUB_ITEM_TAMANHO],[ITEM_COMPOSICAO],[NATUREZA])
	SELECT A.NITEM,A.QTRIB,A.VPROD,L.FILIAL,L.NF_SAIDA
		  ,L.SERIE_NF,L.ITEM_IMPRESSAO,L.SUB_ITEM_TAMANHO,0 AS QTDE_PERDA_PROCESSO
		  ,0 AS QTDE_NAO_BENEFICIADA,I.CODIGO_FISCAL_OPERACAO,NULL AS ENT_NOME_CLIFOR, NULL AS ENT_NF_ENTRADA
		  ,NULL AS ENT_SERIE_NF_ENTRADA,NULL AS ENT_ITEM_IMPRESSAO,NULL AS ENT_SUB_ITEM_TAMANHO
		  ,REPLICATE(0, (7-LEN(RTRIM(B.nNF))))+RTRIM(B.nNF) AS NF_ENTRADA
		  ,C.NOME_CLIFOR,B.SERIE AS SERIE_NF_ENTRADA,A.NITEM AS ITEM_IMPRESSAO,0 AS TIPO_ITEM_RELACIONADO
		  ,0 AS SUB_ITEM_TAMANHO,'304' AS ITEM_COMPOSICAO,I.NATUREZA_ENTRADA AS NATUREZA 
	FROM XML_NFE_ITEM A
	JOIN XML_NFE_CAPA B ON B.chNFe=A.chNFe
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
	JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
	JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
	JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA FROM PARAMETROS_IMPORT_XML) B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
	JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA,TIPO_ENTRADAS,RATEIO_CENTRO_CUSTO,CODIGO_FISCAL_OPERACAO FROM PARAMETROS_IMPORT_XML) I ON I.natop=B.natOp 
	LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
	LEFT JOIN #FATURAMENTO_ITEM_ORIGEM L WITH (NOLOCK) ON RTRIM(SUBSTRING(L.CODIGO_ITEM,9,12))=RTRIM(SUBSTRING(A.CPROD,9,12))
	where a.chNFe='23170811876530000114551040000058751249106062' AND L.COD_TABELA_FILHA='O'

		SELECT A.nItem,A.QTRIB,A.VPROD,L.FILIAL,L.NF_SAIDA
			  ,L.SERIE_NF,L.ITEM_IMPRESSAO,L.SUB_ITEM_TAMANHO,0 AS QTDE_PERDA_PROCESSO
			  ,0 AS QTDE_NAO_BENEFICIADA,I.CODIGO_FISCAL_OPERACAO,NULL AS ENT_NOME_CLIFOR, NULL AS ENT_NF_ENTRADA
			  ,NULL AS ENT_SERIE_NF_ENTRADA,NULL AS ENT_ITEM_IMPRESSAO,NULL AS ENT_SUB_ITEM_TAMANHO
			  ,REPLICATE(0, (7-LEN(RTRIM(B.nNF))))+RTRIM(B.nNF) AS NF_ENTRADA
			  ,C.NOME_CLIFOR,B.SERIE AS SERIE_NF_ENTRADA,A.nItem AS ITEM_IMPRESSAO,0 AS TIPO_ITEM_RELACIONADO
			  ,0 AS SUB_ITEM_TAMANHO,'304' AS ITEM_COMPOSICAO,I.NATUREZA_ENTRADA AS NATUREZA 
		FROM XML_NFE_ITEM A
		JOIN XML_NFE_CAPA B with (nolock) ON B.chNFe=A.chNFe
		JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N with (nolock) JOIN PARAMETROS_IMPORT_XML X with (nolock) ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
		JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N with (nolock) JOIN PARAMETROS_IMPORT_XML X with (nolock) ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
		JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM with (nolock) GROUP BY chNfe) E ON E.chNFe=A.chNFe
		JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A with (nolock) JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA FROM PARAMETROS_IMPORT_XML with (nolock)) B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
		JOIN (SELECT DISTINCT NATOP,NATUREZA_ENTRADA,TIPO_ENTRADAS,RATEIO_CENTRO_CUSTO,CODIGO_FISCAL_OPERACAO FROM PARAMETROS_IMPORT_XML with (nolock)) I ON I.natop=B.natOp 
		LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J with (nolock) ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
		LEFT JOIN FATURAMENTO_ITEM L ON L.NF_SAIDA='0047607' AND L.REFERENCIA = case when charindex('O.S.:',A.xProd) > 0 then RTRIM(substring(A.CPROD,9,12)) else A.CPROD end and CAST(L.ITEM_IMPRESSAO AS INT)=A.nItem
		where a.chNFe='23170811876530000114551040000058751249106062' --AND case when charindex('O.S.:',A.xProd) > 0 then RTRIM(substring(A.CPROD,9,12)) else A.CPROD end='40.01.0012'


	SELECT * FROM FATURAMENTO_ITEM
	WHERE NF_SAIDA='0046841'



	--- GERA IMPOSTOS ENTRADA
	EXEC LX_GERA_IMPOSTOS_ENTRADA 'D ANJOU INTIMA','0005806','104',1,1,1

	--- GERA INTEGRAÇÃO 
	EXEC LX_CTB_Integrar_Entrada 'D ANJOU INTIMA','0005806','104'
--- FIM

NF:0044146

SELECT SERIE_NF_ENTRADA,* FROM ENTRADAS
WHERE NF_ENTRADA='0000751'

DECLARE @NF_SAIDA_ENVIO CHAR(15)

SELECT @NF_SAIDA_ENVIO = case when charindex('NF:',A.xProd) > 0 then substring(A.xProd,charindex('NF:',A.xProd)+3,10) else '' end 
FROM XML_NFE_ITEM A
JOIN XML_NFE_CAPA B ON B.chNFe=A.chNFe
JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.COD_CLIFOR_SACADO=N.CLIFOR) C ON C.CGC_CPF=B.emit_CNPJ
JOIN (SELECT DISTINCT CLIFOR,CGC_CPF,NOME_CLIFOR,RAZAO_SOCIAL FROM CADASTRO_CLI_FOR N JOIN PARAMETROS_IMPORT_XML X ON X.RATEIO_FILIAL=N.CLIFOR) D ON D.CGC_CPF=B.dest_CNPJ
JOIN (SELECT chNfe, qTrib=SUM(qTrib),vProd=SUM(vProd) FROM XML_NFE_ITEM GROUP BY chNfe) E ON E.chNFe=A.chNFe
JOIN (SELECT A.*,B.NATOP FROM CTB_EXCECAO_IMPOSTO A JOIN PARAMETROS_IMPORT_XML B ON B.NATUREZA_ENTRADA=A.NATUREZA_ENTRADA WHERE A.INATIVO=0) F ON F.NATOP=B.NATOP
JOIN PARAMETROS_IMPORT_XML I ON I.natop=B.natOp 
LEFT JOIN IMPORT_XML_NFE_REFERENCIAS_ORIGEM_ITEM J ON J.REFERENCIA=case when charindex('O.S.:',A.xProd) > 0 then substring(A.CPROD,9,12) else A.CPROD end
where a.chNFe='23170803063646000106551020000007511455254716' AND XPROD LIKE '%NF:%'
PRINT @NF_SAIDA_ENVIO

SELECT NF_SAIDA,SERIE_NF,* FROM FATURAMENTO_ITEM
WHERE NF_SAIDA='0000751' AND  SERIE_NF = '102' AND DESCRICAO_ITEM LIKE '%'+@NF_SAIDA_ENVIO+'%'

SELECT NF_SAIDA,SERIE_NF,* FROM FATURAMENTO_ITEM
WHERE NF_SAIDA=@NF_SAIDA_ENVIO AND  SERIE_NF = '56'


SELECT DISTINCT NATOP FROM PARAMETROS_IMPORT_XML

SELECT DISTINCT NATOP FROM XML_NFE_CAPA

DELETE  FROM ENTRADA_ITEM_RELACIONADO
WHERE NF_ENTRADA='0005875' AND SERIE_NF_ENTRADA='104'

SELECT * FROM ENTRADA_ITEM_RELACIONADO
WHERE NF_ENTRADA='0005875' AND SERIE_NF_ENTRADA='104'


INSERT INTO ENTRADA_ITEM_RELACIONADO ([ITEM_RELACIONADO],[QTDE_RELACIONADA],[VALOR_RELACIONADO]
,[FAT_FILIAL],[FAT_NF_SAIDA],[FAT_SERIE_NF],[FAT_ITEM_IMPRESSAO],[FAT_SUB_ITEM_TAMANHO]
,[QTDE_PERDA_PROCESSO],[QTDE_NAO_BENEFICIADA],[CODIGO_FISCAL_OPERACAO]
,[ENT_NOME_CLIFOR],[ENT_NF_ENTRADA],[ENT_SERIE_NF_ENTRADA],[ENT_ITEM_IMPRESSAO]
,[ENT_SUB_ITEM_TAMANHO],[NF_ENTRADA],[NOME_CLIFOR],[SERIE_NF_ENTRADA]
,[ITEM_IMPRESSAO],[TIPO_ITEM_RELACIONADO],[SUB_ITEM_TAMANHO],[ITEM_COMPOSICAO],[NATUREZA])

SELECT DISTINCT A.ITEM_NFE,A.QTDE_ITEM,A.VALOR_ITEM,C.FILIAL,C.NF_SAIDA
,C.SERIE_NF,'0001' AS ITEM_IMPRESSAO,C.SUB_ITEM_TAMANHO,0 AS QTDE_PERDA_PROCESSO
,0 AS QTDE_NAO_BENEFICIADA, A.CODIGO_FISCAL_OPERACAO,NULL AS ENT_NOME_CLIFOR, NULL AS ENT_NF_ENTRADA
,NULL AS ENT_SERIE_NF_ENTRADA,NULL AS ENT_ITEM_IMPRESSAO,NULL AS ENT_SUB_ITEM_TAMANHO
,A.NF_ENTRADA
,A.NOME_CLIFOR,A.SERIE_NF_ENTRADA,'0000' AS ITEM_IMPRESSAO,0 AS TIPO_ITEM_RELACIONADO
,0 AS SUB_ITEM_TAMANHO,'304' AS ITEM_COMPOSICAO,B.NATUREZA
FROM ENTRADAS_ITEM A
JOIN ENTRADAS B ON B.NF_ENTRADA=A.NF_ENTRADA AND B.SERIE_NF_ENTRADA=A.SERIE_NF_ENTRADA
LEFT JOIN FATURAMENTO_ITEM C ON C.NF_SAIDA = '0047607' AND C.SERIE_NF='56' AND C.REFERENCIA=A.CODIGO_ITEM 
WHERE B.CHAVE_NFE='23170811876530000114551040000058751249106062' 



SELECT * FROM FATURAMENTO_ITEM 
WHERE NF_SAIDA = '0047607'


DELETE FROM ENTRADAS
WHERE DATA_DIGITACAO='20170821' AND NOME_CLIFOR='D ANJOU INTIMA'





SELECT [chNFe]
      ,[nItem]
      ,[cProd]
      ,[cEAN]
      ,[xProd]
      ,[NCM]
      ,[CFOP]
      ,[uCom]
      ,[qCom]
      ,[vUnCom]
      ,[vProd]
      ,[cEANTrib]
      ,[uTrib]
      ,[qTrib]
      ,[vUnTrib]
      ,[indTot]
      ,[infAdProd]
      ,[vTotTrib]
      ,[ICMS_orig]
      ,[ICMS_CST]
      ,[ICMS_modBC]
      ,[ICMS_vBC]
      ,[ICMS_pICMS]
      ,[ICMS_vICMS]
      ,[IPI_cEnq]
      ,[IPI_CST]
      ,[IPI_vBC]
      ,[IPI_pIPI]
      ,[IPI_vIPI]
      ,[PIS_CST]
      ,[PIS_vBC]
      ,[PIS_pPIS]
      ,[PIS_vPIS]
      ,[COFINS_CST]
      ,[COFINS_vBC]
      ,[COFINS_pCOFINS]
      ,[COFINS_vCOFINS]
FROM XML_NFE_ITEM A
where a.chNFe='23170811876530000114551040000058751249106062'


SELECT [chNFe],[cProd],[cEAN],[xProd],[NCM],[CFOP],[uCom],[vUnCom],[cEANTrib],[uTrib],[vUnTrib]
      ,[indTot],[infAdProd],[vTotTrib],[ICMS_orig],[ICMS_CST],[ICMS_modBC],[ICMS_vBC],[ICMS_pICMS],[ICMS_vICMS],[IPI_cEnq]
      ,[IPI_CST],[IPI_vBC],[IPI_pIPI],[IPI_vIPI],[PIS_CST],[PIS_vBC],[PIS_pPIS],[PIS_vPIS],[COFINS_CST],[COFINS_vBC],[COFINS_pCOFINS]
      ,[COFINS_vCOFINS],[qCom]=SUM([qCom]),[vProd]=SUM([vProd]),[qTrib]=SUM([qTrib])
FROM XML_NFE_ITEM A
where a.chNFe='23170811876530000114551040000058751249106062'
GROUP BY [chNFe],[cProd],[cEAN],[xProd],[NCM],[CFOP],[uCom],[vUnCom],[cEANTrib],[uTrib],[vUnTrib]
      ,[indTot],[infAdProd],[vTotTrib],[ICMS_orig],[ICMS_CST],[ICMS_modBC],[ICMS_vBC],[ICMS_pICMS],[ICMS_vICMS],[IPI_cEnq]
      ,[IPI_CST],[IPI_vBC],[IPI_pIPI],[IPI_vIPI],[PIS_CST],[PIS_vBC],[PIS_pPIS],[PIS_vPIS],[COFINS_CST],[COFINS_vBC],[COFINS_pCOFINS]
      ,[COFINS_vCOFINS]

