SELECT PRODUTOS_BARRA.NOME_CLIFOR,PRODUTOS_BARRA.CODIGO_BARRA,W_FATURAMENTO_PROD_VERTICAL.* 
FROM W_FATURAMENTO_PROD_VERTICAL
JOIN PRODUTOS_BARRA ON PRODUTOS_BARRA.PRODUTO=W_FATURAMENTO_PROD_VERTICAL.PRODUTO AND 
PRODUTOS_BARRA.COR_PRODUTO=W_FATURAMENTO_PROD_VERTICAL.COR_PRODUTO AND 
PRODUTOS_BARRA.TAMANHO=W_FATURAMENTO_PROD_VERTICAL.ORDEM_TAMANHO
WHERE NF_SAIDA='0050717' AND SERIE_NF='55' AND PRODUTOS_BARRA.NOME_CLIFOR='LEADER - CD'
order by CAIXA