select * from USERS_MODULOS
where modulo='EXP'

SELECT * FROM  USERS_TRANSACOES
WHERE COD_TRANSACAO='VENDA_PREVISAO_001     '
ORDER BY ACESSO_BLOQUEADO

SELECT * FROM TRANSACOES
WHERE TITULO LIKE 'PREVISÃO%'

insert into USERS_TRANSACOES (USUARIO,COD_TRANSACAO,ACESSO_BLOQUEADO,INCLUIR,ALTERAR,EXCLUIR,PESQUISAR,ITEM_EXCLUIR,ITEM_INCLUIR) 
select USUARIO,'VENDA_PREVISAO_001',1,0,0,0,0,0,0 from USERS
