---*********************************************** ENTRADAS MATÉRIA PRIMA **********************************************
---*******
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  update NFE_XML set STATUS = @P1, DATA_ULT_MOVTO = getdate(), USUARIO_ULT_MOVTO = @P2 where CHAVE_NFE = @P3',N'@P1 int,@P2 varchar(2),@P3 varchar(44)',10,'SA','23130205257376000108551050000000011184502110'

-- insert entradas
exec sp_executesql N'INSERT INTO ENTRADAS 
(NF_ENTRADA,NOME_CLIFOR,EMISSAO,FILIAL_COBRANCA,FILIAL,EMPRESA,AGRUPAMENTO_ITENS,COD_TRANSACAO,NATUREZA,CONDICAO_PGTO,RECEBIMENTO,NF_FATURA,SERIE_NF_ENTRADA,TABELA_FILHA,TRANSF_FILIAL,TIPO_ENTRADAS,TRANSPORTADORA_A_PAGAR,MOEDA,MOEDA_COMPRA,DATA_DIGITACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,COMPRIMENTO_DE_ROLOS,DATA_FATURAMENTO_RELATIVO,UTILIZA_DIAS_FIXOS_FORNECEDOR,NOME_CLIFOR_TRIANGULAR,SERIE_NF,NUMERO_ENTRADA,FATURA_NOME_CLIFOR,FATURA_SERIE,FATURA_NUMERO,DIFERENCA_VALOR,QTDE_TOTAL,VALOR_TOTAL,FRETE_A_PAGAR,IMPORTACAO_IMPOSTO,IMPORTACAO_ICMS,IMPORTACAO_IPI,IMPORTACAO_ALFANDEGA,IMPORTACAO_OUTRAS_DESPESAS,IMPORTACAO_FRETE,IMPORTACAO_SEGURO,IMPORTACAO_DESEMBARACO,PORC_DESCONTO,PORC_ENCARGO,COMISSAO_VALOR,COMISSAO_VALOR_GERENTE,VALOR_IMPOSTO_AGREGAR,VALOR_SUB_ITENS,CAMBIO_NA_DATA,ESPECIE_SERIE,NOTA_CANCELADA,COD_CLIFOR_SACADO,IMPORTACAO_TX_CAPATAZIA,PROTOCOLO_AUTORIZACAO_NFE,CHAVE_NFE,DATA_AUTORIZACAO_NFE) 
VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 ,@P40 ,@P41 ,@P42 ,@P43 ,@P44 ,@P45 ,@P46 ,@P47 ,@P48 ,@P49 ,@P50 ,@P51 ,@P52 ,@P53 ,@P54 ,@P55 ,@P56 ,@P57 )',N'@P1 varchar(15),@P2 varchar(25),@P3 datetime,@P4 varchar(25),@P5 varchar(25),@P6 int,@P7 smallint,@P8 varchar(23),@P9 varchar(15),@P10 varchar(3),@P11 datetime,@P12 bit,@P13 varchar(6),@P14 varchar(18),@P15 bit,@P16 varchar(25),@P17 varchar(25),@P18 varchar(6),@P19 varchar(6),@P20 datetime,@P21 varchar(15),@P22 varchar(15),@P23 numeric(13,10),@P24 datetime,@P25 bit,@P26 varchar(25),@P27 varchar(3),@P28 int,@P29 varchar(25),@P30 varchar(6),@P31 varchar(15),@P32 bit,@P33 numeric(10,3),@P34 numeric(15,5),@P35 tinyint,@P36 numeric(14,2),@P37 numeric(14,2),@P38 numeric(14,2),@P39 numeric(14,2),@P40 numeric(14,2),@P41 numeric(14,2),@P42 numeric(14,2),@P43 numeric(14,2),@P44 numeric(13,10),@P45 numeric(13,10),@P46 numeric(14,2),@P47 numeric(14,2),@P48 numeric(14,2),@P49 numeric(14,2),@P50 numeric(15,6),@P51 int,@P52 bit,@P53 varchar(6),@P54 numeric(14,2),@P55 varchar(15),@P56 varchar(44),@P57 datetime','56352          ','FILATI INDUSTRIAS        ','2013-04-06 00:00:00','DR VAREJO                ','DR VAREJO                ',1,2,'ENTRADAS_104           ','200.01         ','981','2013-04-06 00:00:00',1,'1     ','ENTRADAS_NF       ',0,'MATERIA PRIMA            ','NOSSO CARRO              ','R$    ','R$    ','2013-04-06 00:00:00','000001         ','31             ',0,NULL,0,'FILATI INDUSTRIAS        ',NULL,NULL,'FILATI INDUSTRIAS        ','1     ','56352          ',0,200.000,6000.00000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6000.00,1.000000,3,0,'600803',0,'               ','23130205257376000108551050000000011184502110',NULL

-- insert entradas_item
exec sp_executesql N'INSERT INTO ENTRADAS_ITEM 
(NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,DESCRICAO_ITEM,QTDE_ITEM,PRECO_UNITARIO,CODIGO_ITEM,DESCONTO_ITEM,VALOR_ITEM,COD_TABELA_FILHA,TRIBUT_ICMS,TRIBUT_ORIGEM,UNIDADE,CLASSIF_FISCAL,CODIGO_FISCAL_OPERACAO,PESO,CONTA_CONTABIL,FAIXA,INDICADOR_CFOP,PORCENTAGEM_ITEM_RATEIO,ID_EXCECAO_IMPOSTO,REFERENCIA,REFERENCIA_ITEM,REFERENCIA_PEDIDO,TIMESTAMP,VALOR_ENCARGOS,VALOR_DESCONTOS,VALOR_ENCARGOS_IMPORTACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,VALOR_ENCARGOS_ADUANEIROS,PORC_ITEM_RATEIO_FRETE,ITEM_NFE,MPADRAO_SEGURO_ITEM,MPADRAO_FRETE_ITEM,MPADRAO_ENCARGO_ITEM,ORIGEM_ITEM) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 varchar(80),@P7 numeric(9,3),@P8 numeric(15,5),@P9 varchar(50),@P10 numeric(15,5),@P11 numeric(14,2),@P12 varchar(1),@P13 varchar(3),@P14 varchar(3),@P15 varchar(5),@P16 varchar(10),@P17 varchar(4),@P18 numeric(9,5),@P19 varchar(20),@P20 varchar(1),@P21 tinyint,@P22 numeric(13,10),@P23 int,@P24 varchar(50),@P25 varchar(12),@P26 varchar(12),@P27 varchar(25),@P28 numeric(14,2),@P29 numeric(14,2),@P30 numeric(14,2),@P31 varchar(15),@P32 varchar(15),@P33 numeric(14,2),@P34 numeric(13,10),@P35 smallint,@P36 numeric(14,2),@P37 numeric(14,2),@P38 numeric(14,2),@P39 varchar(1)','FILATI INDUSTRIAS        ','56352          ','1     ','0001',1,'16192 TECIDO MODAL                                                              ',120.000,38.00000,'1619201.02.0021                                   ',0,4560.00,'M','00 ','0  ','KG   ','6108.22.00','1101',0,'11404               ','1',10,76.0000000000,NULL,'01.02.0021                                        ','            ','16192       ','ÆÆÆÆÆÆÆÆÆÆÆÆ47Ø11111     ',0,0,0,'000001         ','21             ',0,76.0000000000,1,0,0,0,'M'

-- insert estoque
exec sp_executesql N'INSERT INTO ESTOQUE_RET_MAT (REQ_MATERIAL,FILIAL,EMISSAO,RESPONSAVEL,NOME_CLIFOR,NF_ENTRADA,TIPO_MOVIMENTACAO,ACERTO_ENTRADA,RECEBIMENTO,SERIE_NF_ENTRADA,TIPO_ENTRADA) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 )',N'@P1 varchar(8),@P2 varchar(25),@P3 datetime,@P4 varchar(25),@P5 varchar(25),@P6 varchar(15),@P7 varchar(1),@P8 bit,@P9 datetime,@P10 varchar(6),@P11 tinyint','033111  ','DR VAREJO                ','2013-04-06 00:00:00','SA                       ','FILATI INDUSTRIAS        ','56352          ','D',1,'2013-04-06 00:00:00','1     ',3

exec sp_executesql N'INSERT INTO ESTOQUE_RET1_MAT (REQ_MATERIAL,FILIAL,MATERIAL,ITEM,COR_MATERIAL,QTDE,QTDE_AUX,CUSTO_MATERIA_PRIMA,DESCONTO_ITEM,ENTREGA_PEDIDO,VALOR,ITEM_IMPRESSAO,PEDIDO,FATOR_CONVERSAO_UNIDADE,UNIDADE_FORNECEDOR) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 )',N'@P1 varchar(8),@P2 varchar(25),@P3 varchar(11),@P4 varchar(3),@P5 varchar(10),@P6 numeric(9,3),@P7 numeric(9,3),@P8 numeric(15,5),@P9 numeric(15,5),@P10 datetime,@P11 numeric(14,2),@P12 varchar(4),@P13 varchar(8),@P14 numeric(10,5),@P15 varchar(6)','033111  ','DR VAREJO                ','01.02.0021 ','001','PT0124    ',120.000,0,38.00000,0,'2013-03-21 00:00:00',4560.00,'0001','16192   ',1.00000,'KG    '


-- entrada imposto  
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','FILATI INDUSTRIAS        ','56352          ','1     ','0001',1,0,0,0,0,0,0,0,0,2,1,0,0,0


exec sp_executesql N'
/* VISUALLINX Execute(Alias:curImpostos)  */
SELECT ( CASE CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO             WHEN 2  THEN 998             WHEN 7  THEN 999             WHEN 51 THEN 1             WHEN 42 THEN 0             ELSE CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO          END ) AS PRIORIDADE, CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO, CTB_LX_IMPOSTO_TIPO.IMPOSTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA, CTB_LX_IMPOSTO_TIPO.INCIDENCIA) AS INCIDENCIA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.PORCENT_REDUCAO_DE_BASE, 0) AS PORCENT_REDUCAO_DE_BASE, CTB_LX_IMPOSTO_TIPO.ALIQUOTA_FIXA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.TAXA_IMPOSTO, 0) AS TAXA_IMPOSTO_EXCECAO, CTB_LX_IMPOSTO_TIPO.ALIQUOTA AS TAXA_IMPOSTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_ENCARGO, CTB_LX_IMPOSTO_TIPO.AGREGA_APOS_ENCARGO) AS AGREGA_APOS_ENCARGO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_DESCONTO, CTB_LX_IMPOSTO_TIPO.AGREGA_APOS_DESCONTO) AS AGREGA_APOS_DESCONTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.APLICA_ESPELHO_ENTRADA, 0) AS APLICA_ESPELHO_ENTRADA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS, '''') AS ISENTO_OU_OUTROS, CTB_LX_IMPOSTO_TIPO.CALCULO_DECIMAL,        CAST(ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.PORC_RECUPERACAO, 100) AS NUMERIC(13,10)) AS PORC_RECUPERACAO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.VALOR_MIN_ARRECADACAO, CTB_LX_IMPOSTO_TIPO.VALOR_MIN_ARRECADACAO) AS VALOR_MIN_ARRECADACAO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.VALIDA_VALOR_PARCELA, CTB_LX_IMPOSTO_TIPO.VALIDA_VALOR_PARCELA) AS VALIDA_VALOR_PARCELA,        CTB_LX_IMPOSTO_TIPO.NRO_CASAS_DECIMAIS, CTB_EXCECAO_IMPOSTO.CODIGO_CLASSE_TRIBUTACAO, CTB_EXCECAO_IMPOSTO_ITEM.USA_TAB_PRECO_BASE, CTB_EXCECAO_IMPOSTO_ITEM.INDICA_REC_ALIQUOTA_BASE FROM CTB_LX_IMPOSTO_TIPO      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM ON CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO = CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO AND                                            CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = @P1      LEFT JOIN CTB_EXCECAO_IMPOSTO ON CTB_EXCECAO_IMPOSTO.ID_EXCECAO_IMPOSTO = @P2 WHERE ( CTB_LX_IMPOSTO_TIPO.GERA_NA_ENTRADA = 1 OR         CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = @P3 ) ORDER BY 1 DESC',N'@P1 int,@P2 int,@P3 int',739,739,739

exec sp_executesql N'
/* VISUALLINX Execute(Alias:curImpostos)  */
SELECT ( CASE CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO             WHEN 2  THEN 998             WHEN 7  THEN 999             WHEN 51 THEN 1             WHEN 42 THEN 0             ELSE CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO          END ) AS PRIORIDADE, CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO, CTB_LX_IMPOSTO_TIPO.IMPOSTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.INCIDENCIA, CTB_LX_IMPOSTO_TIPO.INCIDENCIA) AS INCIDENCIA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.PORCENT_REDUCAO_DE_BASE, 0) AS PORCENT_REDUCAO_DE_BASE, CTB_LX_IMPOSTO_TIPO.ALIQUOTA_FIXA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.TAXA_IMPOSTO, 0) AS TAXA_IMPOSTO_EXCECAO, CTB_LX_IMPOSTO_TIPO.ALIQUOTA AS TAXA_IMPOSTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_ENCARGO, CTB_LX_IMPOSTO_TIPO.AGREGA_APOS_ENCARGO) AS AGREGA_APOS_ENCARGO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.AGREGA_APOS_DESCONTO, CTB_LX_IMPOSTO_TIPO.AGREGA_APOS_DESCONTO) AS AGREGA_APOS_DESCONTO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.APLICA_ESPELHO_ENTRADA, 0) AS APLICA_ESPELHO_ENTRADA,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.ISENTO_OU_OUTROS, '''') AS ISENTO_OU_OUTROS, CTB_LX_IMPOSTO_TIPO.CALCULO_DECIMAL,        CAST(ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.PORC_RECUPERACAO, 100) AS NUMERIC(13,10)) AS PORC_RECUPERACAO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.VALOR_MIN_ARRECADACAO, CTB_LX_IMPOSTO_TIPO.VALOR_MIN_ARRECADACAO) AS VALOR_MIN_ARRECADACAO,        ISNULL(CTB_EXCECAO_IMPOSTO_ITEM.VALIDA_VALOR_PARCELA, CTB_LX_IMPOSTO_TIPO.VALIDA_VALOR_PARCELA) AS VALIDA_VALOR_PARCELA,        CTB_LX_IMPOSTO_TIPO.NRO_CASAS_DECIMAIS, CTB_EXCECAO_IMPOSTO.CODIGO_CLASSE_TRIBUTACAO, CTB_EXCECAO_IMPOSTO_ITEM.USA_TAB_PRECO_BASE, CTB_EXCECAO_IMPOSTO_ITEM.INDICA_REC_ALIQUOTA_BASE FROM CTB_LX_IMPOSTO_TIPO      LEFT JOIN CTB_EXCECAO_IMPOSTO_ITEM ON CTB_LX_IMPOSTO_TIPO.ID_IMPOSTO = CTB_EXCECAO_IMPOSTO_ITEM.ID_IMPOSTO AND                                            CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = @P1      LEFT JOIN CTB_EXCECAO_IMPOSTO ON CTB_EXCECAO_IMPOSTO.ID_EXCECAO_IMPOSTO = @P2 WHERE ( CTB_LX_IMPOSTO_TIPO.GERA_NA_ENTRADA = 1 OR         CTB_EXCECAO_IMPOSTO_ITEM.ID_EXCECAO_IMPOSTO = @P3 ) ORDER BY 1 DESC',N'@P1 int,@P2 int,@P3 int',739,739,739

exec sp_executesql N'
/* VISUALLINX Execute(Alias:curICMS)  */
SELECT ICMS_Entrada, ICMS_Saida FROM Unidades_Federacao_ICMS, Cadastro_Cli_For WHERE Unidades_Federacao_ICMS.UF = Cadastro_Cli_For.UF AND Cadastro_Cli_For.Nome_CliFor = @P1 AND Unidades_Federacao_ICMS.UF_Destino = @P2',N'@P1 varchar(9),@P2 varchar(2)','DR VAREJO','CE'

exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,0,0,0,0,0,0,0,1,2,1,0,0,0
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,0,0,0,0,0,0,1,14,3,0,0,0
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,7.60000,137.10,1804.00,7.60000,137.10,1804.00,1,6,3,7.60000,137.10,1804.00
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,1.65000,29.77,1804.00,1.65000,29.77,1804.00,1,5,3,1.65000,29.77,1804.00
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,0,0,0,17.00000,126.29,742.88,1,1,3,17.00000,126.29,742.89
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,3.00000,54.12,1804.00,3.00000,54.12,1804.00,1,51,3,3.00000,54.12,1804.00
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','PASSAMANARIA DO NORDESTE ','21544          ','1     ','0001',1,1,3.00000,54.12,1804.00,3.00000,54.12,1804.00,1,12,1,3.00000,54.12,1804.00

-- integrar entrada
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_CTB_Integrar_Entrada @P1, @P2, @P3',N'@P1 varchar(17),@P2 varchar(5),@P3 varchar(1)','FILATI INDUSTRIAS','56352','1'

  
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  DELETE FROM ENTRADAS_OBSERVACAO WHERE NF_ENTRADA = @P1 AND SERIE_NF_ENTRADA = @P2 AND NOME_CLIFOR = @P3',N'@P1 varchar(5),@P2 varchar(1),@P3 varchar(17)','56352','1','FILATI INDUSTRIAS'
  
-- ajustar o pedido
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_MOVIMENTA_COMPRAS_MP '16192'  
  

---*********************************************** ENTRADAS CONSUMIVEIS **********************************************
---*******

  exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  update NFE_XML set STATUS = @P1, DATA_ULT_MOVTO = getdate(), USUARIO_ULT_MOVTO = @P2 where CHAVE_NFE = @P3',N'@P1 int,@P2 varchar(2),@P3 varchar(44)',10,'SA','23130101790247000111550040000000011930624138'
  

-- insert entradas
  exec sp_executesql N'INSERT INTO ENTRADAS 
(NF_ENTRADA,NOME_CLIFOR,EMISSAO,FILIAL,EMPRESA,AGRUPAMENTO_ITENS,COD_TRANSACAO,NATUREZA,CONDICAO_PGTO,RECEBIMENTO,NF_FATURA,SERIE_NF_ENTRADA,TABELA_FILHA,TRANSF_FILIAL,TIPO_ENTRADAS,TRANSPORTADORA_A_PAGAR,MOEDA,MOEDA_COMPRA,DATA_DIGITACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,DATA_FATURAMENTO_RELATIVO,UTILIZA_DIAS_FIXOS_FORNECEDOR,NOME_CLIFOR_TRIANGULAR,SERIE_NF,NUMERO_ENTRADA,FATURA_NOME_CLIFOR,FATURA_SERIE,FATURA_NUMERO,DIFERENCA_VALOR,QTDE_TOTAL,VALOR_TOTAL,FRETE_A_PAGAR,IMPORTACAO_IMPOSTO,IMPORTACAO_ICMS,IMPORTACAO_IPI,IMPORTACAO_ALFANDEGA,IMPORTACAO_OUTRAS_DESPESAS,IMPORTACAO_FRETE,IMPORTACAO_SEGURO,IMPORTACAO_DESEMBARACO,PORC_DESCONTO,PORC_ENCARGO,COMISSAO_VALOR,COMISSAO_VALOR_GERENTE,VALOR_IMPOSTO_AGREGAR,VALOR_SUB_ITENS,CAMBIO_NA_DATA,ESPECIE_SERIE,NOTA_CANCELADA,COD_CLIFOR_SACADO,IMPORTACAO_TX_CAPATAZIA,CHAVE_NFE) 
VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 ,@P40 ,@P41 ,@P42 ,@P43 ,@P44 ,@P45 ,@P46 ,@P47 ,@P48 ,@P49 ,@P50 ,@P51 ,@P52 ,@P53 )',N'@P1 varchar(15),@P2 varchar(25),@P3 datetime,@P4 varchar(25),@P5 int,@P6 smallint,@P7 varchar(23),@P8 varchar(15),@P9 varchar(3),@P10 datetime,@P11 bit,@P12 varchar(6),@P13 varchar(18),@P14 bit,@P15 varchar(25),@P16 varchar(25),@P17 varchar(6),@P18 varchar(6),@P19 datetime,@P20 varchar(15),@P21 varchar(15),@P22 datetime,@P23 bit,@P24 varchar(25),@P25 varchar(3),@P26 int,@P27 varchar(25),@P28 varchar(6),@P29 varchar(15),@P30 bit,@P31 numeric(10,3),@P32 numeric(15,5),@P33 tinyint,@P34 numeric(14,2),@P35 numeric(14,2),@P36 numeric(14,2),@P37 numeric(14,2),@P38 numeric(14,2),@P39 numeric(14,2),@P40 numeric(14,2),@P41 numeric(14,2),@P42 numeric(13,10),@P43 numeric(13,10),@P44 numeric(14,2),@P45 numeric(14,2),@P46 numeric(14,2),@P47 numeric(14,2),@P48 numeric(15,6),@P49 int,@P50 bit,@P51 varchar(6),@P52 numeric(14,2),@P53 varchar(44)','52451          ','LINX SISTEMA             ','2013-04-07 00:00:00','DR VAREJO                ',1,0,'ENTRADAS_109           ','200.01         ','033','2013-04-07 00:00:00',1,'1     ','ENTRADAS_NF       ',0,'CONSUMIVEIS              ','NOSSO CARRO              ','R$    ','R$    ','2013-04-07 00:00:00','000001         ','8013           ',NULL,0,'AJJA                     ',NULL,NULL,'LINX SISTEMA             ','1     ','52451          ',0,1.000,3298.22000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3298.22,1.000000,3,0,'600253',0,'23130101790247000111550040000000011930624138'


-- insert entradas_item
exec sp_executesql N'INSERT INTO ENTRADAS_ITEM 
(NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,DESCRICAO_ITEM,QTDE_ITEM,PRECO_UNITARIO,CODIGO_ITEM,DESCONTO_ITEM,VALOR_ITEM,COD_TABELA_FILHA,TRIBUT_ICMS,TRIBUT_ORIGEM,UNIDADE,CLASSIF_FISCAL,CODIGO_FISCAL_OPERACAO,PESO,CONTA_CONTABIL,QTDE_RETORNAR_BENEFICIAMENTO,FAIXA,COMISSAO_ITEM,COMISSAO_ITEM_GERENTE,INDICADOR_CFOP,QTDE_DEVOLVIDA,PORCENTAGEM_ITEM_RATEIO,ID_EXCECAO_IMPOSTO,REFERENCIA_ITEM,REFERENCIA_PEDIDO,TIMESTAMP,VALOR_ENCARGOS,VALOR_DESCONTOS,NAO_SOMA_VALOR,VALOR_ENCARGOS_IMPORTACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,VALOR_ENCARGOS_ADUANEIROS,PORC_ITEM_RATEIO_FRETE,ITEM_NFE,MPADRAO_SEGURO_ITEM,MPADRAO_FRETE_ITEM,MPADRAO_ENCARGO_ITEM) 
VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 ,@P40 ,@P41 ,@P42 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 varchar(80),@P7 numeric(9,3),@P8 numeric(15,5),@P9 varchar(50),@P10 numeric(15,5),@P11 numeric(14,2),@P12 varchar(1),@P13 varchar(3),@P14 varchar(3),@P15 varchar(5),@P16 varchar(10),@P17 varchar(4),@P18 numeric(9,5),@P19 varchar(20),@P20 numeric(9,3),@P21 varchar(1),@P22 numeric(8,5),@P23 numeric(8,5),@P24 tinyint,@P25 numeric(9,3),@P26 numeric(13,10),@P27 int,@P28 varchar(12),@P29 varchar(12),@P30 varchar(25),@P31 numeric(14,2),@P32 numeric(14,2),@P33 bit,@P34 numeric(14,2),@P35 varchar(15),@P36 varchar(15),@P37 numeric(14,2),@P38 numeric(13,10),@P39 smallint,@P40 numeric(14,2),@P41 numeric(14,2),@P42 numeric(14,2)','LINX SISTEMA             ','52451          ','1     ','0001',0,'MANUTENÇÃO DE SOFTWARE - LINX                                                   ',1.000,3298.22000,'1166.1                                            ',0,3298.22,'C','00 ','0  ','UN   ','0000.00.00','2933',0,'5121001             ',0,'1',0,0,89,0,100.0000000000,NULL,'16/01/13    ','16101       ','ÆÆÆÆÆÆÆÆÆÆ4267Ø22111     ',0,0,0,0,'000001         ','8013           ',0,100.0000000000,1,0,0,0


-- insert entradas_imposto
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','LINX SISTEMA             ','52451          ','1     ','0001',0,1,0,0,0,0,0,0,1,14,3,0,0,0

-- integrar entrada
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_CTB_Integrar_Entrada @P1, @P2, @P3',N'@P1 varchar(12),@P2 varchar(5),@P3 varchar(1)','LINX SISTEMA','52451','1'
  
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  DELETE FROM ENTRADAS_OBSERVACAO WHERE NF_ENTRADA = @P1 AND SERIE_NF_ENTRADA = @P2 AND NOME_CLIFOR = @P3',N'@P1 varchar(5),@P2 varchar(1),@P3 varchar(12)','52451','1','LINX SISTEMA'
    
-- ajustar o pedido
/* VISUALLINX ExecuteNonQuery()  */
  EXEC lx_movimenta_compras_consumo '16101'
  

---*********************************************** ENTRADAS ORDEM DE SERVIÇO **********************************************
---*******

-- INSERT ENTRADAS      
exec sp_executesql N'INSERT INTO ENTRADAS 
(NF_ENTRADA,NOME_CLIFOR,EMISSAO,FILIAL,EMPRESA,AGRUPAMENTO_ITENS,COD_TRANSACAO,NATUREZA,CONDICAO_PGTO,RECEBIMENTO,NF_FATURA,SERIE_NF_ENTRADA,TABELA_FILHA,TRANSF_FILIAL,TIPO_ENTRADAS,MOEDA,MOEDA_COMPRA,DATA_DIGITACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,DATA_FATURAMENTO_RELATIVO,UTILIZA_DIAS_FIXOS_FORNECEDOR,NOME_CLIFOR_TRIANGULAR,SERIE_NF,NUMERO_ENTRADA,FATURA_NOME_CLIFOR,FATURA_SERIE,FATURA_NUMERO,DIFERENCA_VALOR,QTDE_TOTAL,VALOR_TOTAL,FRETE_A_PAGAR,IMPORTACAO_IMPOSTO,IMPORTACAO_ICMS,IMPORTACAO_IPI,IMPORTACAO_ALFANDEGA,IMPORTACAO_OUTRAS_DESPESAS,IMPORTACAO_FRETE,IMPORTACAO_SEGURO,IMPORTACAO_DESEMBARACO,PORC_DESCONTO,PORC_ENCARGO,COMISSAO_VALOR,COMISSAO_VALOR_GERENTE,VALOR_IMPOSTO_AGREGAR,VALOR_SUB_ITENS,CAMBIO_NA_DATA,ESPECIE_SERIE,NOTA_CANCELADA,COD_CLIFOR_SACADO,IMPORTACAO_TX_CAPATAZIA,CHAVE_NFE) 
VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 ,@P40 ,@P41 ,@P42 ,@P43 ,@P44 ,@P45 ,@P46 ,@P47 ,@P48 ,@P49 ,@P50 ,@P51 ,@P52 )',N'@P1 varchar(15),@P2 varchar(25),@P3 datetime,@P4 varchar(25),@P5 int,@P6 smallint,@P7 varchar(23),@P8 varchar(15),@P9 varchar(3),@P10 datetime,@P11 bit,@P12 varchar(6),@P13 varchar(18),@P14 bit,@P15 varchar(25),@P16 varchar(6),@P17 varchar(6),@P18 datetime,@P19 varchar(15),@P20 varchar(15),@P21 datetime,@P22 bit,@P23 varchar(25),@P24 varchar(3),@P25 int,@P26 varchar(25),@P27 varchar(6),@P28 varchar(15),@P29 bit,@P30 numeric(10,3),@P31 numeric(15,5),@P32 tinyint,@P33 numeric(14,2),@P34 numeric(14,2),@P35 numeric(14,2),@P36 numeric(14,2),@P37 numeric(14,2),@P38 numeric(14,2),@P39 numeric(14,2),@P40 numeric(14,2),@P41 numeric(13,10),@P42 numeric(13,10),@P43 numeric(14,2),@P44 numeric(14,2),@P45 numeric(14,2),@P46 numeric(14,2),@P47 numeric(15,6),@P48 int,@P49 bit,@P50 varchar(6),@P51 numeric(14,2),@P52 varchar(44)','452415         ','JULIETE                  ','2013-04-07 00:00:00','DR VAREJO                ',1,1,'ENTRADAS_108           ','240.01         ','000','2013-04-07 00:00:00',0,'1     ','ENTRADAS_NF       ',0,'BENEFICIAMENTO           ','R$    ','R$    ','2013-04-07 00:00:00','000001         ','31             ',NULL,0,'JULIETE                  ',NULL,NULL,NULL,NULL,NULL,0,10.000,100.00000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,100.00,1.000000,3,0,'600216',0,'23130207938560000130551020000000011756173353'

-- INSERT ENTRADAS_ITEM
exec sp_executesql N'INSERT INTO ENTRADAS_ITEM 
(NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,DESCRICAO_ITEM,QTDE_ITEM,PRECO_UNITARIO,CODIGO_ITEM,DESCONTO_ITEM,VALOR_ITEM,COD_TABELA_FILHA,TRIBUT_ICMS,TRIBUT_ORIGEM,UNIDADE,CLASSIF_FISCAL,CODIGO_FISCAL_OPERACAO,PESO,CONTA_CONTABIL,QTDE_RETORNAR_BENEFICIAMENTO,FAIXA,COMISSAO_ITEM,COMISSAO_ITEM_GERENTE,INDICADOR_CFOP,QTDE_DEVOLVIDA,PORCENTAGEM_ITEM_RATEIO,ID_EXCECAO_IMPOSTO,REFERENCIA,REFERENCIA_ITEM,REFERENCIA_PEDIDO,TIMESTAMP,VALOR_ENCARGOS,VALOR_DESCONTOS,NAO_SOMA_VALOR,VALOR_ENCARGOS_IMPORTACAO,RATEIO_FILIAL,RATEIO_CENTRO_CUSTO,VALOR_ENCARGOS_ADUANEIROS,PORC_ITEM_RATEIO_FRETE,ITEM_NFE,MPADRAO_SEGURO_ITEM,MPADRAO_FRETE_ITEM,MPADRAO_ENCARGO_ITEM,ORIGEM_ITEM) 
VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 ,@P19 ,@P20 ,@P21 ,@P22 ,@P23 ,@P24 ,@P25 ,@P26 ,@P27 ,@P28 ,@P29 ,@P30 ,@P31 ,@P32 ,@P33 ,@P34 ,@P35 ,@P36 ,@P37 ,@P38 ,@P39 ,@P40 ,@P41 ,@P42 ,@P43 ,@P44 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 varchar(80),@P7 numeric(9,3),@P8 numeric(15,5),@P9 varchar(50),@P10 numeric(15,5),@P11 numeric(14,2),@P12 varchar(1),@P13 varchar(3),@P14 varchar(3),@P15 varchar(5),@P16 varchar(10),@P17 varchar(4),@P18 numeric(9,5),@P19 varchar(20),@P20 numeric(9,3),@P21 varchar(1),@P22 numeric(8,5),@P23 numeric(8,5),@P24 tinyint,@P25 numeric(9,3),@P26 numeric(13,10),@P27 int,@P28 varchar(50),@P29 varchar(12),@P30 varchar(12),@P31 varchar(25),@P32 numeric(14,2),@P33 numeric(14,2),@P34 bit,@P35 numeric(14,2),@P36 varchar(15),@P37 varchar(15),@P38 numeric(14,2),@P39 numeric(13,10),@P40 smallint,@P41 numeric(14,2),@P42 numeric(14,2),@P43 numeric(14,2),@P44 varchar(1)','JULIETE                  ','452415         ','1     ','0001',0,' BIQUINI FITINESS BRANCO                                                        ',10.000,10.00000,'51015BC0035                                       ',0,100.00,'R','90 ','0  ','PÇ   ','6108.2100 ','1902',0,NULL,0,'1',0,0,10,0,100.0000000000,743,'51015                                             ','BC0035      ',NULL,'ÆÆÆÆÆÆÆÆÆÆÆÆ31Ø11111     ',0,0,0,0,'000001         ','31             ',0,100.0000000000,1,0,0,0,'P'

-- INSERT ENTRADAS_IMPOSTO
exec sp_executesql N'INSERT INTO ENTRADAS_IMPOSTO (NOME_CLIFOR,NF_ENTRADA,SERIE_NF_ENTRADA,ITEM_IMPRESSAO,SUB_ITEM_TAMANHO,AGREGA_APOS_DESCONTO,TAXA_IMPOSTO,VALOR_IMPOSTO,BASE_IMPOSTO,TAXA_IMPOSTO_ESPELHO,VALOR_IMPOSTO_ESPELHO,BASE_IMPOSTO_ESPELHO,AGREGA_APOS_ENCARGO,ID_IMPOSTO,INCIDENCIA,TAXA_IMPOSTO_CALC,VALOR_IMPOSTO_CALC,BASE_IMPOSTO_CALC) VALUES (@P1 ,@P2 ,@P3 ,@P4 ,@P5 ,@P6 ,@P7 ,@P8 ,@P9 ,@P10 ,@P11 ,@P12 ,@P13 ,@P14 ,@P15 ,@P16 ,@P17 ,@P18 )',N'@P1 varchar(25),@P2 varchar(15),@P3 varchar(6),@P4 varchar(4),@P5 int,@P6 bit,@P7 numeric(8,5),@P8 numeric(14,2),@P9 numeric(14,2),@P10 numeric(8,5),@P11 numeric(14,2),@P12 numeric(14,2),@P13 bit,@P14 tinyint,@P15 tinyint,@P16 numeric(8,5),@P17 numeric(14,2),@P18 numeric(14,2)','JULIETE                  ','452415         ','1     ','0001',0,0,0,0,0,0,0,0,0,2,1,0,0,0

-- UPDATE COM BASE NA INFORMAÇÃO DA EXCEÇÃO DO IMPOSTO
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
   UPDATE ENTRADAS SET INFORMACAO_COMPLEMENTAR = '' IPI REDUZIDO A ZERO CONF. DECRETO 6.006 DE 28/12/2006.''  WHERE NF_ENTRADA = @P1 AND SERIE_NF_ENTRADA = @P2 AND NOME_CLIFOR = @P3 ',N'@P1 varchar(6),@P2 varchar(1),@P3 varchar(7)','452415','1','JULIETE'
   
-- INTEGRAR ENTRADA   
exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  */
  EXEC LX_CTB_Integrar_Entrada @P1, @P2, @P3',N'@P1 varchar(7),@P2 varchar(6),@P3 varchar(1)','JULIETE','452415','1'
  
  exec sp_executesql N'
/* VISUALLINX ExecuteNonQuery()  

  DELETE FROM ENTRADAS_OBSERVACAO WHERE NF_ENTRADA = @P1 AND SERIE_NF_ENTRADA = @P2 AND NOME_CLIFOR = @P3',N'@P1 varchar(6),@P2 varchar(1),@P3 varchar(7)','452415','1','JULIETE'


--*************************** TABELAS SUGERIDAS PARA ARMAZENAMGEM DOS DADOS DO ARQUIVO XML *******************************
---*******

-- CAPA DO XML
create table Capa (
Chave44Digitos VarChar(44) NOT NULL,
Versao VarChar(4) NOT NULL,
IdeCNF VarChar(9) NOT NULL,
IdeMod VarChar(2) NOT NULL,
IdeCMunFG VarChar(7) NOT NULL,
IdeCUF VarChar(2) NOT NULL,
IdeDEmi VarChar(10) NOT NULL,
IdeDhCont VarChar(10) NOT NULL,
IdeDSaiEnt VarChar(10) NOT NULL,
IdeFinNFe VarChar(1) NOT NULL,
IdeHSaiEnt VarChar(8) NOT NULL,
IdeIndPag VarChar(1) NOT NULL,
IdeNatOp VarChar(60) NOT NULL,
IdeNNF VarChar(9) NOT NULL,
IdeSerie VarChar(3) NOT NULL,
IdeTpEmis VarChar(1) NOT NULL,
IdeTpImp VarChar(1) NOT NULL,
IdeTpNF VarChar(1) NOT NULL,
IdeXJust VarChar(256) NOT NULL,
IdeProcEmi VarChar(1) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
IdeVerProc VarChar(20) NOT NULL,
versaoXML VarChar(4) NOT NULL,
DigestValueNFe VarChar(28) NOT NULL,
EmitTipoDoc VarChar(4) NOT NULL,
EmitCNPJ_CPF VarChar(14) NOT NULL,
EmitCNAE VarChar(7) NOT NULL,
EmitCRT VarChar(1) NOT NULL,
EmitEnderEmitCEP VarChar(8) NOT NULL,
EmitEnderEmitCMun VarChar(7) NOT NULL,
EmitEnderEmitCPais VarChar(4) NOT NULL,
EmitEnderEmitFone VarChar(14) NOT NULL,
EmitEnderEmitNro VarChar(60) NOT NULL,
EmitEnderEmitUF VarChar(2) NOT NULL,
EmitEnderEmitXBairro VarChar(60) NOT NULL,
EmitEnderEmitXCpl VarChar(60) NOT NULL,
EmitEnderEmitXLgr VarChar(60) NOT NULL,
EmitEnderEmitXMun VarChar(60) NOT NULL,
EmitEnderEmitXPais VarChar(60) NOT NULL,
EmitIE VarChar(14) NOT NULL,
EmitIEST VarChar(14) NOT NULL,
EmitIM VarChar(15) NOT NULL,
EmitXFant VarChar(60) NOT NULL,
EmitXNome VarChar(60) NOT NULL,
DestTipoDoc VarChar(4) NOT NULL,
DestCNPJ_CPF VarChar(14) NOT NULL,
DestEmail VarChar(60) NOT NULL,
DestEnderDestCEP VarChar(8) NOT NULL,
DestEnderDestCMun VarChar(7) NOT NULL,
DestEnderDestCPais VarChar(4) NOT NULL,
DestEnderDestFone VarChar(14) NOT NULL,
DestEnderDestNro VarChar(60) NOT NULL,
DestEnderDestUF VarChar(2) NOT NULL,
DestEnderDestXBairro VarChar(60) NOT NULL,
DestEnderDestXCpl VarChar(60) NOT NULL,
DestEnderDestXLgr VarChar(60) NOT NULL,
DestEnderDestXMun VarChar(60) NOT NULL,
DestEnderDestXPais VarChar(60) NOT NULL,
DestIE VarChar(14) NOT NULL,
DestISUF VarChar(9) NOT NULL,
DestXNome VarChar(60) NOT NULL,
RetiradaTipoDoc VarChar(4) NOT NULL,
RetiradaCNPJ_CPF VarChar(14) NOT NULL,
RetiradaCMun VarChar(7) NOT NULL,
RetiradaNro VarChar(60) NOT NULL,
RetiradaUF VarChar(2) NOT NULL,
RetiradaXBairro VarChar(60) NOT NULL,
RetiradaXCpl VarChar(60) NOT NULL,
RetiradaXLgr VarChar(60) NOT NULL,
RetiradaXMun VarChar(60) NOT NULL,
EntregaTipoDoc VarChar(4) NOT NULL,
EntregaCNPJ_CPF VarChar(14) NOT NULL,
EntregaCMun VarChar(7) NOT NULL,
EntregaNro VarChar(60) NOT NULL,
EntregaUF VarChar(2) NOT NULL,
EntregaXBairro VarChar(60) NOT NULL,
EntregaXCpl VarChar(60) NOT NULL,
EntregaXLgr VarChar(60) NOT NULL,
EntregaXMun VarChar(60) NOT NULL,
TotalICMSTotVBC VarChar(16) NOT NULL,
TotalICMSTotVBCST VarChar(16) NOT NULL,
TotalICMSTotVCOFINS VarChar(16) NOT NULL,
TotalICMSTotVDesc VarChar(16) NOT NULL,
TotalICMSTotVFrete VarChar(16) NOT NULL,
TotalICMSTotVICMS VarChar(16) NOT NULL,
TotalICMSTotVII VarChar(16) NOT NULL,
TotalICMSTotVIPI VarChar(16) NOT NULL,
TotalICMSTotVNF VarChar(16) NOT NULL,
TotalICMSTotVOutro VarChar(16) NOT NULL,
TotalICMSTotVPIS VarChar(16) NOT NULL,
TotalICMSTotVProd VarChar(16) NOT NULL,
TotalICMSTotVSeg VarChar(16) NOT NULL,
TotalICMSTotVST VarChar(16) NOT NULL,
TotalISSQNtotVBC VarChar(16) NOT NULL,
TotalISSQNtotVCOFINS VarChar(16) NOT NULL,
TotalISSQNtotVISS VarChar(16) NOT NULL,
TotalISSQNtotVPIS VarChar(16) NOT NULL,
TotalISSQNtotVServ VarChar(16) NOT NULL,
TotalRetTribVBCIRRF VarChar(16) NOT NULL,
TotalRetTribVBCRetPrev VarChar(16) NOT NULL,
TotalRetTribVIRRF VarChar(16) NOT NULL,
TotalRetTribVRetCOFINS VarChar(16) NOT NULL,
TotalRetTribVRetCSLL VarChar(16) NOT NULL,
TotalRetTribVRetPIS VarChar(16) NOT NULL,
TotalRetTribVRetPrev VarChar(16) NOT NULL,
TranspModFrete VarChar(1) NOT NULL,
TranspRetTranspCFOP VarChar(4) NOT NULL,
TranspRetTranspCMunFG VarChar(7) NOT NULL,
TranspRetTranspPICMSRet VarChar(6) NOT NULL,
TranspRetTranspVBCRet VarChar(16) NOT NULL,
TranspRetTranspVICMSRet VarChar(16) NOT NULL,
TranspRetTranspVServ VarChar(16) NOT NULL,
TranspTransportaTipoDoc VarChar(4) NOT NULL,
TranspTransportaCNPJ_CPF VarChar(14) NOT NULL,
TranspTransportaIE VarChar(14) NOT NULL,
TranspTransportaUF VarChar(2) NOT NULL,
TranspTransportaXEnder VarChar(60) NOT NULL,
TranspTransportaXMun VarChar(60) NOT NULL,
TranspTransportaXNome VarChar(60) NOT NULL,
TranspVeicTranspPlaca VarChar(8) NOT NULL,
TranspVeicTranspRNTC VarChar(20) NOT NULL,
TranspVeicTranspUF VarChar(2) NOT NULL,
CobrFatNFat VarChar(60) NOT NULL,
CobrFatVDesc VarChar(16) NOT NULL,
CobrFatVLiq VarChar(16) NOT NULL,
CobrFatVOrig VarChar(16) NOT NULL,
InfAdicInfAdFisco Text NOT NULL,
InfAdicInfCpl Text NOT NULL,
ExportaUFEmbarq VarChar(2) NOT NULL,
ExportaXLocEmbarq VarChar(60) NOT NULL,
CompraXCont VarChar(60) NOT NULL,
CompraXNEmp VarChar(17) NOT NULL,
CompraXPed VarChar(60) NOT NULL,
ProtocoloChNFe VarChar(44) NOT NULL,
ProtocoloCStat VarChar(3) NOT NULL,
ProtocoloDhRecbto VarChar(10) NOT NULL,
ProtocoloDigestValue VarChar(28) NOT NULL,
ProtocoloNProt VarChar(15) NOT NULL,
ProtocoloVerAplic VarChar(20) NOT NULL,
ProtocoloXMotivo VarChar(255) NOT NULL
);

--- INSERT CAPA
insert into Capa (
Chave44Digitos,
Versao,
IdeCNF,
IdeMod,
IdeCMunFG,
IdeCUF,
IdeDEmi,
IdeDhCont,
IdeDSaiEnt,
IdeFinNFe,
IdeHSaiEnt,
IdeIndPag,
IdeNatOp,
IdeNNF,
IdeSerie,
IdeTpEmis,
IdeTpImp,
IdeTpNF,
IdeXJust,
IdeProcEmi,
IdeTpAmb,
IdeVerProc,
versaoXML,
DigestValueNFe,
EmitTipoDoc,
EmitCNPJ_CPF,
EmitCNAE,
EmitCRT,
EmitEnderEmitCEP,
EmitEnderEmitCMun,
EmitEnderEmitCPais,
EmitEnderEmitFone,
EmitEnderEmitNro,
EmitEnderEmitUF,
EmitEnderEmitXBairro,
EmitEnderEmitXCpl,
EmitEnderEmitXLgr,
EmitEnderEmitXMun,
EmitEnderEmitXPais,
EmitIE,
EmitIEST,
EmitIM,
EmitXFant,
EmitXNome,
DestTipoDoc,
DestCNPJ_CPF,
DestEmail,
DestEnderDestCEP,
DestEnderDestCMun,
DestEnderDestCPais,
DestEnderDestFone,
DestEnderDestNro,
DestEnderDestUF,
DestEnderDestXBairro,
DestEnderDestXCpl,
DestEnderDestXLgr,
DestEnderDestXMun,
DestEnderDestXPais,
DestIE,
DestISUF,
DestXNome,
RetiradaTipoDoc,
RetiradaCNPJ_CPF,
RetiradaCMun,
RetiradaNro,
RetiradaUF,
RetiradaXBairro,
RetiradaXCpl,
RetiradaXLgr,
RetiradaXMun,
EntregaTipoDoc,
EntregaCNPJ_CPF,
EntregaCMun,
EntregaNro,
EntregaUF,
EntregaXBairro,
EntregaXCpl,
EntregaXLgr,
EntregaXMun,
TotalICMSTotVBC,
TotalICMSTotVBCST,
TotalICMSTotVCOFINS,
TotalICMSTotVDesc,
TotalICMSTotVFrete,
TotalICMSTotVICMS,
TotalICMSTotVII,
TotalICMSTotVIPI,
TotalICMSTotVNF,
TotalICMSTotVOutro,
TotalICMSTotVPIS,
TotalICMSTotVProd,
TotalICMSTotVSeg,
TotalICMSTotVST,
TotalISSQNtotVBC,
TotalISSQNtotVCOFINS,
TotalISSQNtotVISS,
TotalISSQNtotVPIS,
TotalISSQNtotVServ,
TotalRetTribVBCIRRF,
TotalRetTribVBCRetPrev,
TotalRetTribVIRRF,
TotalRetTribVRetCOFINS,
TotalRetTribVRetCSLL,
TotalRetTribVRetPIS,
TotalRetTribVRetPrev,
TranspModFrete,
TranspRetTranspCFOP,
TranspRetTranspCMunFG,
TranspRetTranspPICMSRet,
TranspRetTranspVBCRet,
TranspRetTranspVICMSRet,
TranspRetTranspVServ,
TranspTransportaTipoDoc,
TranspTransportaCNPJ_CPF,
TranspTransportaIE,
TranspTransportaUF,
TranspTransportaXEnder,
TranspTransportaXMun,
TranspTransportaXNome,
TranspVeicTranspPlaca,
TranspVeicTranspRNTC,
TranspVeicTranspUF,
CobrFatNFat,
CobrFatVDesc,
CobrFatVLiq,
CobrFatVOrig,
InfAdicInfAdFisco,
InfAdicInfCpl,
ExportaUFEmbarq,
ExportaXLocEmbarq,
CompraXCont,
CompraXNEmp,
CompraXPed,
ProtocoloChNFe,
ProtocoloCStat,
ProtocoloDhRecbto,
ProtocoloDigestValue,
ProtocoloNProt,
ProtocoloVerAplic,
ProtocoloXMotivo
) values (
?Chave44DigitosAsVarChar,
?VersaoAsVarChar,
?IdeCNFAsVarChar,
?IdeModAsVarChar,
?IdeCMunFGAsVarChar,
?IdeCUFAsVarChar,
?IdeDEmiAsVarChar,
?IdeDhContAsVarChar,
?IdeDSaiEntAsVarChar,
?IdeFinNFeAsVarChar,
?IdeHSaiEntAsVarChar,
?IdeIndPagAsVarChar,
?IdeNatOpAsVarChar,
?IdeNNFAsVarChar,
?IdeSerieAsVarChar,
?IdeTpEmisAsVarChar,
?IdeTpImpAsVarChar,
?IdeTpNFAsVarChar,
?IdeXJustAsVarChar,
?IdeProcEmiAsVarChar,
?IdeTpAmbAsVarChar,
?IdeVerProcAsVarChar,
?versaoXMLAsVarChar,
?DigestValueNFeAsVarChar,
?EmitTipoDocAsVarChar,
?EmitCNPJ_CPFAsVarChar,
?EmitCNAEAsVarChar,
?EmitCRTAsVarChar,
?EmitEnderEmitCEPAsVarChar,
?EmitEnderEmitCMunAsVarChar,
?EmitEnderEmitCPaisAsVarChar,
?EmitEnderEmitFoneAsVarChar,
?EmitEnderEmitNroAsVarChar,
?EmitEnderEmitUFAsVarChar,
?EmitEnderEmitXBairroAsVarChar,
?EmitEnderEmitXCplAsVarChar,
?EmitEnderEmitXLgrAsVarChar,
?EmitEnderEmitXMunAsVarChar,
?EmitEnderEmitXPaisAsVarChar,
?EmitIEAsVarChar,
?EmitIESTAsVarChar,
?EmitIMAsVarChar,
?EmitXFantAsVarChar,
?EmitXNomeAsVarChar,
?DestTipoDocAsVarChar,
?DestCNPJ_CPFAsVarChar,
?DestEmailAsVarChar,
?DestEnderDestCEPAsVarChar,
?DestEnderDestCMunAsVarChar,
?DestEnderDestCPaisAsVarChar,
?DestEnderDestFoneAsVarChar,
?DestEnderDestNroAsVarChar,
?DestEnderDestUFAsVarChar,
?DestEnderDestXBairroAsVarChar,
?DestEnderDestXCplAsVarChar,
?DestEnderDestXLgrAsVarChar,
?DestEnderDestXMunAsVarChar,
?DestEnderDestXPaisAsVarChar,
?DestIEAsVarChar,
?DestISUFAsVarChar,
?DestXNomeAsVarChar,
?RetiradaTipoDocAsVarChar,
?RetiradaCNPJ_CPFAsVarChar,
?RetiradaCMunAsVarChar,
?RetiradaNroAsVarChar,
?RetiradaUFAsVarChar,
?RetiradaXBairroAsVarChar,
?RetiradaXCplAsVarChar,
?RetiradaXLgrAsVarChar,
?RetiradaXMunAsVarChar,
?EntregaTipoDocAsVarChar,
?EntregaCNPJ_CPFAsVarChar,
?EntregaCMunAsVarChar,
?EntregaNroAsVarChar,
?EntregaUFAsVarChar,
?EntregaXBairroAsVarChar,
?EntregaXCplAsVarChar,
?EntregaXLgrAsVarChar,
?EntregaXMunAsVarChar,
?TotalICMSTotVBCAsVarChar,
?TotalICMSTotVBCSTAsVarChar,
?TotalICMSTotVCOFINSAsVarChar,
?TotalICMSTotVDescAsVarChar,
?TotalICMSTotVFreteAsVarChar,
?TotalICMSTotVICMSAsVarChar,
?TotalICMSTotVIIAsVarChar,
?TotalICMSTotVIPIAsVarChar,
?TotalICMSTotVNFAsVarChar,
?TotalICMSTotVOutroAsVarChar,
?TotalICMSTotVPISAsVarChar,
?TotalICMSTotVProdAsVarChar,
?TotalICMSTotVSegAsVarChar,
?TotalICMSTotVSTAsVarChar,
?TotalISSQNtotVBCAsVarChar,
?TotalISSQNtotVCOFINSAsVarChar,
?TotalISSQNtotVISSAsVarChar,
?TotalISSQNtotVPISAsVarChar,
?TotalISSQNtotVServAsVarChar,
?TotalRetTribVBCIRRFAsVarChar,
?TotalRetTribVBCRetPrevAsVarChar,
?TotalRetTribVIRRFAsVarChar,
?TotalRetTribVRetCOFINSAsVarChar,
?TotalRetTribVRetCSLLAsVarChar,
?TotalRetTribVRetPISAsVarChar,
?TotalRetTribVRetPrevAsVarChar,
?TranspModFreteAsVarChar,
?TranspRetTranspCFOPAsVarChar,
?TranspRetTranspCMunFGAsVarChar,
?TranspRetTranspPICMSRetAsVarChar,
?TranspRetTranspVBCRetAsVarChar,
?TranspRetTranspVICMSRetAsVarChar,
?TranspRetTranspVServAsVarChar,
?TranspTransportaTipoDocAsVarChar,
?TranspTransportaCNPJ_CPFAsVarChar,
?TranspTransportaIEAsVarChar,
?TranspTransportaUFAsVarChar,
?TranspTransportaXEnderAsVarChar,
?TranspTransportaXMunAsVarChar,
?TranspTransportaXNomeAsVarChar,
?TranspVeicTranspPlacaAsVarChar,
?TranspVeicTranspRNTCAsVarChar,
?TranspVeicTranspUFAsVarChar,
?CobrFatNFatAsVarChar,
?CobrFatVDescAsVarChar,
?CobrFatVLiqAsVarChar,
?CobrFatVOrigAsVarChar,
?InfAdicInfAdFiscoAsText,
?InfAdicInfCplAsText,
?ExportaUFEmbarqAsVarChar,
?ExportaXLocEmbarqAsVarChar,
?CompraXContAsVarChar,
?CompraXNEmpAsVarChar,
?CompraXPedAsVarChar,
?ProtocoloChNFeAsVarChar,
?ProtocoloCStatAsVarChar,
?ProtocoloDhRecbtoAsVarChar,
?ProtocoloDigestValueAsVarChar,
?ProtocoloNProtAsVarChar,
?ProtocoloVerAplicAsVarChar,
?ProtocoloXMotivoAsVarChar
);



-- ITENS DO XML
create table Itens (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
InfAdProd Text NOT NULL,
NumeroItem VarChar(3) NOT NULL,
ProdCEAN VarChar(14) NOT NULL,
ProdCEANTrib VarChar(14) NOT NULL,
ProdCFOP VarChar(4) NOT NULL,
ProdCProd VarChar(60) NOT NULL,
ProdEXTIPI VarChar(3) NOT NULL,
ProdGenero VarChar(2) NOT NULL,
ProdIndTot VarChar(1) NOT NULL,
ProdNCM VarChar(8) NOT NULL,
ProdNItemPed VarChar(6) NOT NULL,
ProdQCom VarChar(16) NOT NULL,
ProdQTrib VarChar(16) NOT NULL,
ProdUCom VarChar(6) NOT NULL,
ProdUTrib VarChar(6) NOT NULL,
ProdVDesc VarChar(16) NOT NULL,
ProdVFrete VarChar(16) NOT NULL,
ProdVOutro VarChar(16) NOT NULL,
ProdVProd VarChar(16) NOT NULL,
ProdVSeg VarChar(16) NOT NULL,
ProdVUnCom VarChar(22) NOT NULL,
ProdVUnTrib VarChar(22) NOT NULL,
ProdXPed VarChar(15) NOT NULL,
ProdXProd VarChar(120) NOT NULL,
ImpostoICMSTipo VarChar(5) NOT NULL,
ImpostoICMSCST_CSOSN VarChar(3) NOT NULL,
ImpostoICMSModBC VarChar(1) NOT NULL,
ImpostoICMSModBCST VarChar(1) NOT NULL,
ImpostoICMSMotDesICMS VarChar(1) NOT NULL,
ImpostoICMSOrig VarChar(1) NOT NULL,
ImpostoICMSPBCOp VarChar(6) NOT NULL,
ImpostoICMSPCredSN VarChar(6) NOT NULL,
ImpostoICMSPICMS VarChar(6) NOT NULL,
ImpostoICMSPICMSST VarChar(6) NOT NULL,
ImpostoICMSPMVAST VarChar(6) NOT NULL,
ImpostoICMSPRedBC VarChar(6) NOT NULL,
ImpostoICMSPRedBCST VarChar(6) NOT NULL,
ImpostoICMSUFST VarChar(2) NOT NULL,
ImpostoICMSVBC VarChar(16) NOT NULL,
ImpostoICMSVBCST VarChar(16) NOT NULL,
ImpostoICMSVBCSTDest VarChar(16) NOT NULL,
ImpostoICMSVBCSTRet VarChar(16) NOT NULL,
ImpostoICMSVCredICMSSN VarChar(16) NOT NULL,
ImpostoICMSVICMS VarChar(16) NOT NULL,
ImpostoICMSVICMSST VarChar(16) NOT NULL,
ImpostoICMSVICMSSTDest VarChar(16) NOT NULL,
ImpostoICMSVICMSSTRet VarChar(16) NOT NULL,
ImpostoIPICST VarChar(2) NOT NULL,
ImpostoIPIPIPI VarChar(6) NOT NULL,
ImpostoIPIQUnid VarChar(17) NOT NULL,
ImpostoIPIVBC VarChar(16) NOT NULL,
ImpostoIPIVIPI VarChar(16) NOT NULL,
ImpostoIPIVUnid VarChar(16) NOT NULL,
ImpostoIPICEnq VarChar(3) NOT NULL,
ImpostoIPIClEnq VarChar(5) NOT NULL,
ImpostoIPICNPJProd VarChar(14) NOT NULL,
ImpostoIPICSelo VarChar(60) NOT NULL,
ImpostoIPIQSelo VarChar(12) NOT NULL,
ImpostoPISCST VarChar(2) NOT NULL,
ImpostoPISPPIS VarChar(6) NOT NULL,
ImpostoPISQBCProd VarChar(17) NOT NULL,
ImpostoPISVAliqProd VarChar(16) NOT NULL,
ImpostoPISVBC VarChar(16) NOT NULL,
ImpostoPISVPIS VarChar(16) NOT NULL,
ImpostoPISSTPPIS VarChar(6) NOT NULL,
ImpostoPISSTQBCProd VarChar(17) NOT NULL,
ImpostoPISSTVAliqProd VarChar(16) NOT NULL,
ImpostoPISSTVBC VarChar(16) NOT NULL,
ImpostoPISSTVPIS VarChar(16) NOT NULL,
ImpostoCOFINSCST VarChar(2) NOT NULL,
ImpostoCOFINSPCOFINS VarChar(6) NOT NULL,
ImpostoCOFINSQBCProd VarChar(17) NOT NULL,
ImpostoCOFINSVAliqProd VarChar(16) NOT NULL,
ImpostoCOFINSVBC VarChar(16) NOT NULL,
ImpostoCOFINSVCOFINS VarChar(16) NOT NULL,
ImpostoCOFINSSTPCOFINS VarChar(6) NOT NULL,
ImpostoCOFINSSTQBCProd VarChar(17) NOT NULL,
ImpostoCOFINSSTVAliqProd VarChar(16) NOT NULL,
ImpostoCOFINSSTVBC VarChar(16) NOT NULL,
ImpostoCOFINSSTVCOFINS VarChar(16) NOT NULL,
ImpostoISSQNCListServ VarChar(4) NOT NULL,
ImpostoISSQNCMunFG VarChar(7) NOT NULL,
ImpostoISSQNCSitTrib VarChar(1) NOT NULL,
ImpostoISSQNVAliq VarChar(6) NOT NULL,
ImpostoISSQNVBC VarChar(16) NOT NULL,
ImpostoISSQNVISSQN VarChar(16) NOT NULL,
ImpostoIIVBC VarChar(16) NOT NULL,
ImpostoIIVDespAdu VarChar(16) NOT NULL,
ImpostoIIVII VarChar(16) NOT NULL,
ImpostoIIVIOF VarChar(16) NOT NULL,
VeicAnoFab VarChar(4) NOT NULL,
VeicAnoMod VarChar(4) NOT NULL,
VeicCCor VarChar(4) NOT NULL,
VeicCCorDETRAN VarChar(2) NOT NULL,
VeicChassi VarChar(17) NOT NULL,
VeicCilin VarChar(4) NOT NULL,
VeicCM3 VarChar(4) NOT NULL,
VeicCMKG VarChar(9) NOT NULL,
VeicCMod VarChar(6) NOT NULL,
VeicCMT VarChar(9) NOT NULL,
VeicCondVeic VarChar(1) NOT NULL,
VeicDist VarChar(4) NOT NULL,
VeicEspVeic VarChar(1) NOT NULL,
VeicLota VarChar(3) NOT NULL,
VeicNMotor VarChar(21) NOT NULL,
VeicNSerie VarChar(9) NOT NULL,
VeicPesoB VarChar(9) NOT NULL,
VeicPesoL VarChar(9) NOT NULL,
VeicPot VarChar(4) NOT NULL,
VeicRENAVAM VarChar(9) NOT NULL,
VeicTpComb VarChar(2) NOT NULL,
VeicTpOp VarChar(1) NOT NULL,
VeicTpPint VarChar(1) NOT NULL,
VeicTpRest VarChar(1) NOT NULL,
VeicTpVeic VarChar(2) NOT NULL,
VeicVIN VarChar(1) NOT NULL,
VeicXCor VarChar(40) NOT NULL,
CombCIDEQBCProd VarChar(17) NOT NULL,
CombCIDEVAliqProd VarChar(16) NOT NULL,
CombCIDEVCIDE VarChar(16) NOT NULL,
CombCODIF VarChar(21) NOT NULL,
CombCProdANP VarChar(9) NOT NULL,
CombICMSCombVBCICMS VarChar(16) NOT NULL,
CombICMSCombVBCICMSST VarChar(16) NOT NULL,
CombICMSCombVICMS VarChar(16) NOT NULL,
CombICMSCombVICMSST VarChar(16) NOT NULL,
CombICMSConsUFCons VarChar(2) NOT NULL,
CombICMSConsVBCICMSSTCons VarChar(16) NOT NULL,
CombICMSConsVICMSSTCons VarChar(16) NOT NULL,
CombICMSInterVBCICMSSTDest VarChar(16) NOT NULL,
CombICMSInterVICMSSTDest VarChar(16) NOT NULL,
CombQTemp VarChar(17) NOT NULL,
CombUFCons VarChar(2) NOT NULL
);


-- INSERT ITENS
insert into Itens (
Chave44Digitos,
IdeTpAmb,
InfAdProd,
NumeroItem,
ProdCEAN,
ProdCEANTrib,
ProdCFOP,
ProdCProd,
ProdEXTIPI,
ProdGenero,
ProdIndTot,
ProdNCM,
ProdNItemPed,
ProdQCom,
ProdQTrib,
ProdUCom,
ProdUTrib,
ProdVDesc,
ProdVFrete,
ProdVOutro,
ProdVProd,
ProdVSeg,
ProdVUnCom,
ProdVUnTrib,
ProdXPed,
ProdXProd,
ImpostoICMSTipo,
ImpostoICMSCST_CSOSN,
ImpostoICMSModBC,
ImpostoICMSModBCST,
ImpostoICMSMotDesICMS,
ImpostoICMSOrig,
ImpostoICMSPBCOp,
ImpostoICMSPCredSN,
ImpostoICMSPICMS,
ImpostoICMSPICMSST,
ImpostoICMSPMVAST,
ImpostoICMSPRedBC,
ImpostoICMSPRedBCST,
ImpostoICMSUFST,
ImpostoICMSVBC,
ImpostoICMSVBCST,
ImpostoICMSVBCSTDest,
ImpostoICMSVBCSTRet,
ImpostoICMSVCredICMSSN,
ImpostoICMSVICMS,
ImpostoICMSVICMSST,
ImpostoICMSVICMSSTDest,
ImpostoICMSVICMSSTRet,
ImpostoIPICST,
ImpostoIPIPIPI,
ImpostoIPIQUnid,
ImpostoIPIVBC,
ImpostoIPIVIPI,
ImpostoIPIVUnid,
ImpostoIPICEnq,
ImpostoIPIClEnq,
ImpostoIPICNPJProd,
ImpostoIPICSelo,
ImpostoIPIQSelo,
ImpostoPISCST,
ImpostoPISPPIS,
ImpostoPISQBCProd,
ImpostoPISVAliqProd,
ImpostoPISVBC,
ImpostoPISVPIS,
ImpostoPISSTPPIS,
ImpostoPISSTQBCProd,
ImpostoPISSTVAliqProd,
ImpostoPISSTVBC,
ImpostoPISSTVPIS,
ImpostoCOFINSCST,
ImpostoCOFINSPCOFINS,
ImpostoCOFINSQBCProd,
ImpostoCOFINSVAliqProd,
ImpostoCOFINSVBC,
ImpostoCOFINSVCOFINS,
ImpostoCOFINSSTPCOFINS,
ImpostoCOFINSSTQBCProd,
ImpostoCOFINSSTVAliqProd,
ImpostoCOFINSSTVBC,
ImpostoCOFINSSTVCOFINS,
ImpostoISSQNCListServ,
ImpostoISSQNCMunFG,
ImpostoISSQNCSitTrib,
ImpostoISSQNVAliq,
ImpostoISSQNVBC,
ImpostoISSQNVISSQN,
ImpostoIIVBC,
ImpostoIIVDespAdu,
ImpostoIIVII,
ImpostoIIVIOF,
VeicAnoFab,
VeicAnoMod,
VeicCCor,
VeicCCorDETRAN,
VeicChassi,
VeicCilin,
VeicCM3,
VeicCMKG,
VeicCMod,
VeicCMT,
VeicCondVeic,
VeicDist,
VeicEspVeic,
VeicLota,
VeicNMotor,
VeicNSerie,
VeicPesoB,
VeicPesoL,
VeicPot,
VeicRENAVAM,
VeicTpComb,
VeicTpOp,
VeicTpPint,
VeicTpRest,
VeicTpVeic,
VeicVIN,
VeicXCor,
CombCIDEQBCProd,
CombCIDEVAliqProd,
CombCIDEVCIDE,
CombCODIF,
CombCProdANP,
CombICMSCombVBCICMS,
CombICMSCombVBCICMSST,
CombICMSCombVICMS,
CombICMSCombVICMSST,
CombICMSConsUFCons,
CombICMSConsVBCICMSSTCons,
CombICMSConsVICMSSTCons,
CombICMSInterVBCICMSSTDest,
CombICMSInterVICMSSTDest,
CombQTemp,
CombUFCons
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?InfAdProdAsText,
?NumeroItemAsVarChar,
?ProdCEANAsVarChar,
?ProdCEANTribAsVarChar,
?ProdCFOPAsVarChar,
?ProdCProdAsVarChar,
?ProdEXTIPIAsVarChar,
?ProdGeneroAsVarChar,
?ProdIndTotAsVarChar,
?ProdNCMAsVarChar,
?ProdNItemPedAsVarChar,
?ProdQComAsVarChar,
?ProdQTribAsVarChar,
?ProdUComAsVarChar,
?ProdUTribAsVarChar,
?ProdVDescAsVarChar,
?ProdVFreteAsVarChar,
?ProdVOutroAsVarChar,
?ProdVProdAsVarChar,
?ProdVSegAsVarChar,
?ProdVUnComAsVarChar,
?ProdVUnTribAsVarChar,
?ProdXPedAsVarChar,
?ProdXProdAsVarChar,
?ImpostoICMSTipoAsVarChar,
?ImpostoICMSCST_CSOSNAsVarChar,
?ImpostoICMSModBCAsVarChar,
?ImpostoICMSModBCSTAsVarChar,
?ImpostoICMSMotDesICMSAsVarChar,
?ImpostoICMSOrigAsVarChar,
?ImpostoICMSPBCOpAsVarChar,
?ImpostoICMSPCredSNAsVarChar,
?ImpostoICMSPICMSAsVarChar,
?ImpostoICMSPICMSSTAsVarChar,
?ImpostoICMSPMVASTAsVarChar,
?ImpostoICMSPRedBCAsVarChar,
?ImpostoICMSPRedBCSTAsVarChar,
?ImpostoICMSUFSTAsVarChar,
?ImpostoICMSVBCAsVarChar,
?ImpostoICMSVBCSTAsVarChar,
?ImpostoICMSVBCSTDestAsVarChar,
?ImpostoICMSVBCSTRetAsVarChar,
?ImpostoICMSVCredICMSSNAsVarChar,
?ImpostoICMSVICMSAsVarChar,
?ImpostoICMSVICMSSTAsVarChar,
?ImpostoICMSVICMSSTDestAsVarChar,
?ImpostoICMSVICMSSTRetAsVarChar,
?ImpostoIPICSTAsVarChar,
?ImpostoIPIPIPIAsVarChar,
?ImpostoIPIQUnidAsVarChar,
?ImpostoIPIVBCAsVarChar,
?ImpostoIPIVIPIAsVarChar,
?ImpostoIPIVUnidAsVarChar,
?ImpostoIPICEnqAsVarChar,
?ImpostoIPIClEnqAsVarChar,
?ImpostoIPICNPJProdAsVarChar,
?ImpostoIPICSeloAsVarChar,
?ImpostoIPIQSeloAsVarChar,
?ImpostoPISCSTAsVarChar,
?ImpostoPISPPISAsVarChar,
?ImpostoPISQBCProdAsVarChar,
?ImpostoPISVAliqProdAsVarChar,
?ImpostoPISVBCAsVarChar,
?ImpostoPISVPISAsVarChar,
?ImpostoPISSTPPISAsVarChar,
?ImpostoPISSTQBCProdAsVarChar,
?ImpostoPISSTVAliqProdAsVarChar,
?ImpostoPISSTVBCAsVarChar,
?ImpostoPISSTVPISAsVarChar,
?ImpostoCOFINSCSTAsVarChar,
?ImpostoCOFINSPCOFINSAsVarChar,
?ImpostoCOFINSQBCProdAsVarChar,
?ImpostoCOFINSVAliqProdAsVarChar,
?ImpostoCOFINSVBCAsVarChar,
?ImpostoCOFINSVCOFINSAsVarChar,
?ImpostoCOFINSSTPCOFINSAsVarChar,
?ImpostoCOFINSSTQBCProdAsVarChar,
?ImpostoCOFINSSTVAliqProdAsVarChar,
?ImpostoCOFINSSTVBCAsVarChar,
?ImpostoCOFINSSTVCOFINSAsVarChar,
?ImpostoISSQNCListServAsVarChar,
?ImpostoISSQNCMunFGAsVarChar,
?ImpostoISSQNCSitTribAsVarChar,
?ImpostoISSQNVAliqAsVarChar,
?ImpostoISSQNVBCAsVarChar,
?ImpostoISSQNVISSQNAsVarChar,
?ImpostoIIVBCAsVarChar,
?ImpostoIIVDespAduAsVarChar,
?ImpostoIIVIIAsVarChar,
?ImpostoIIVIOFAsVarChar,
?VeicAnoFabAsVarChar,
?VeicAnoModAsVarChar,
?VeicCCorAsVarChar,
?VeicCCorDETRANAsVarChar,
?VeicChassiAsVarChar,
?VeicCilinAsVarChar,
?VeicCM3AsVarChar,
?VeicCMKGAsVarChar,
?VeicCModAsVarChar,
?VeicCMTAsVarChar,
?VeicCondVeicAsVarChar,
?VeicDistAsVarChar,
?VeicEspVeicAsVarChar,
?VeicLotaAsVarChar,
?VeicNMotorAsVarChar,
?VeicNSerieAsVarChar,
?VeicPesoBAsVarChar,
?VeicPesoLAsVarChar,
?VeicPotAsVarChar,
?VeicRENAVAMAsVarChar,
?VeicTpCombAsVarChar,
?VeicTpOpAsVarChar,
?VeicTpPintAsVarChar,
?VeicTpRestAsVarChar,
?VeicTpVeicAsVarChar,
?VeicVINAsVarChar,
?VeicXCorAsVarChar,
?CombCIDEQBCProdAsVarChar,
?CombCIDEVAliqProdAsVarChar,
?CombCIDEVCIDEAsVarChar,
?CombCODIFAsVarChar,
?CombCProdANPAsVarChar,
?CombICMSCombVBCICMSAsVarChar,
?CombICMSCombVBCICMSSTAsVarChar,
?CombICMSCombVICMSAsVarChar,
?CombICMSCombVICMSSTAsVarChar,
?CombICMSConsUFConsAsVarChar,
?CombICMSConsVBCICMSSTConsAsVarChar,
?CombICMSConsVICMSSTConsAsVarChar,
?CombICMSInterVBCICMSSTDestAsVarChar,
?CombICMSInterVICMSSTDestAsVarChar,
?CombQTempAsVarChar,
?CombUFConsAsVarChar
);



-- ITENS DI´S
create table Itens_DI (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
NumeroItem VarChar(3) NOT NULL,
nDI VarChar(10) NOT NULL,
dDI VarChar(10) NOT NULL,
xLocDesemb VarChar(60) NOT NULL,
UFDesemb VarChar(2) NOT NULL,
dDesemb VarChar(10) NOT NULL,
cExportador VarChar(60) NOT NULL
);

-- INSERT ITENS DI´S
insert into Itens_DI (
Chave44Digitos,
IdeTpAmb,
NumeroItem,
nDI,
dDI,
xLocDesemb,
UFDesemb,
dDesemb,
cExportador
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?NumeroItemAsVarChar,
?nDIAsVarChar,
?dDIAsVarChar,
?xLocDesembAsVarChar,
?UFDesembAsVarChar,
?dDesembAsVarChar,
?cExportadorAsVarChar
);





-- ITENS DI´S ADIÇÕES
create table Itens_DI_Adicoes (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
NumeroItem VarChar(3) NOT NULL,
nDI VarChar(10) NOT NULL,
nAdicao VarChar(3) NOT NULL,
nSeqAdic VarChar(3) NOT NULL,
cFabricante VarChar(60) NOT NULL,
vDescDI VarChar(16) NOT NULL
);

-- INSERT DI´S ADIÇÕES

insert into Itens_DI_Adicoes (
Chave44Digitos,
IdeTpAmb,
NumeroItem,
nDI,
nAdicao,
nSeqAdic,
cFabricante,
vDescDI
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?NumeroItemAsVarChar,
?nDIAsVarChar,
?nAdicaoAsVarChar,
?nSeqAdicAsVarChar,
?cFabricanteAsVarChar,
?vDescDIAsVarChar
);


-- DUPLICATAS
create table Duplicata (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
DVenc VarChar(16) NOT NULL,
NDup VarChar(60) NOT NULL,
VDup VarChar(16) NOT NULL
);

-- INSERT DUPLICATAS
insert into Duplicata (
Chave44Digitos,
IdeTpAmb,
DVenc,
NDup,
VDup
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?DVencAsVarChar,
?NDupAsVarChar,
?VDupAsVarChar
);


-- NOTAS REFERENCIAS
create table NFe_Referencia (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
RefNFAAMM VarChar(4) NOT NULL,
RefNFCNPJ VarChar(14) NOT NULL,
RefCTe VarChar(44) NOT NULL,
RefNFCUF VarChar(2) NOT NULL,
RefECFMod VarChar(2) NOT NULL,
RefECFNCOO VarChar(6) NOT NULL,
RefECFNECF VarChar(3) NOT NULL,
RefNFMod VarChar(2) NOT NULL,
RefNFPAAMM VarChar(4) NOT NULL,
RefNFPTipoDoc VarChar(4) NOT NULL,
RefNFPCNPJ_CPF VarChar(14) NOT NULL,
RefNFPCUF VarChar(2) NOT NULL,
RefNFPIE VarChar(14) NOT NULL,
RefNFPMod VarChar(2) NOT NULL,
RefNFPNNF VarChar(9) NOT NULL,
RefNFPSerie VarChar(3) NOT NULL,
RefNFNNF VarChar(9) NOT NULL,
RefNFe VarChar(44) NOT NULL,
RefNFSerie VarChar(3) NOT NULL
);


-- INSERT NOTAS REFENCIADAS
insert into NFe_Referencia (
Chave44Digitos,
IdeTpAmb,
RefNFAAMM,
RefNFCNPJ,
RefCTe,
RefNFCUF,
RefECFMod,
RefECFNCOO,
RefECFNECF,
RefNFMod,
RefNFPAAMM,
RefNFPTipoDoc,
RefNFPCNPJ_CPF,
RefNFPCUF,
RefNFPIE,
RefNFPMod,
RefNFPNNF,
RefNFPSerie,
RefNFNNF,
RefNFe,
RefNFSerie
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?RefNFAAMMAsVarChar,
?RefNFCNPJAsVarChar,
?RefCTeAsVarChar,
?RefNFCUFAsVarChar,
?RefECFModAsVarChar,
?RefECFNCOOAsVarChar,
?RefECFNECFAsVarChar,
?RefNFModAsVarChar,
?RefNFPAAMMAsVarChar,
?RefNFPTipoDocAsVarChar,
?RefNFPCNPJ_CPFAsVarChar,
?RefNFPCUFAsVarChar,
?RefNFPIEAsVarChar,
?RefNFPModAsVarChar,
?RefNFPNNFAsVarChar,
?RefNFPSerieAsVarChar,
?RefNFNNFAsVarChar,
?RefNFeAsVarChar,
?RefNFSerieAsVarChar
);




-- VOLUMES
create table Volumes (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
QVol VarChar(15) NOT NULL,
Esp VarChar(60) NOT NULL,
Marca VarChar(60) NOT NULL,
NVol VarChar(60) NOT NULL,
PesoL VarChar(19) NOT NULL,
PesoB VarChar(19) NOT NULL
);

-- INSERT VOLUMES
insert into Volumes (
Chave44Digitos,
IdeTpAmb,
QVol,
Esp,
Marca,
NVol,
PesoL,
PesoB
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?QVolAsVarChar,
?EspAsVarChar,
?MarcaAsVarChar,
?NVolAsVarChar,
?PesoLAsVarChar,
?PesoBAsVarChar
);



-- LACRES
create table Lacres (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
NVol VarChar(60) NOT NULL,
NLacre VarChar(60) NOT NULL
);


-- INSERT LACRES
insert into Lacres (
Chave44Digitos,
IdeTpAmb,
NVol,
NLacre
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?NVolAsVarChar,
?NLacreAsVarChar
);

-- OBNSERVAÇÕES
create table Obs_Contribuinte (
Chave44Digitos VarChar(44) NOT NULL,
IdeTpAmb VarChar(1) NOT NULL,
XCampo VarChar(20) NOT NULL,
XTexto VarChar(60) NOT NULL
);

-- INSERT OBSERVAÇÕES
insert into Obs_Contribuinte (
Chave44Digitos,
IdeTpAmb,
XCampo,
XTexto
) values (
?Chave44DigitosAsVarChar,
?IdeTpAmbAsVarChar,
?XCampoAsVarChar,
?XTextoAsVarChar
);