-- Executar passo a passo:

-- 1o. Passo
-- VERIFICA SE EXISTEM NOTAS CANCELADAS COM REGISTROS NOS CAMPOS LANCAMENTOS CONTABEIS E ITENS DOS LANCAMENTOS
USE [ INFORME SEU BANCO ] 
GO

select PROTOCOLO_CANCELAMENTO_NFE,DATA_CANCELAMENTO,CTB_LANCAMENTO,CTB_ITEM, * 
from FATURAMENTO 
where STATUS_NFE in ('59') and 
(CTB_LANCAMENTO IS NOT NULL OR CTB_ITEM IS NOT NULL) 
order by NF_SAIDA

-- 2o. Passo
-- BAIXA AS TRIGGERS DA TABELA FATURAMENTO, PARA ANULAR OS CAMPOS LANCAMENTO CONTABIL E ITEM DA
-- TABELA FATURAMENTO
USE [ INFORME SEU BANCO ]
GO
/****** Object:  Trigger [LXD_FATURAMENTO]    Script Date: 07/03/2014 17:40:38 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[LXD_FATURAMENTO]'))
DROP TRIGGER [dbo].[LXD_FATURAMENTO]

USE [ INFORME SEU BANCO ]
GO
/****** Object:  Trigger [LXU_FATURAMENTO]    Script Date: 07/03/2014 17:43:00 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[LXU_FATURAMENTO]'))
DROP TRIGGER [dbo].[LXU_FATURAMENTO]

USE [ INFORME SEU BANCO ]
GO
/****** Object:  Trigger [LXI_FATURAMENTO]    Script Date: 07/03/2014 17:41:52 ******/
IF  EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[LXI_FATURAMENTO]'))
DROP TRIGGER [dbo].[LXI_FATURAMENTO]

-- 3o. Passo
-- ANULA OS CAMPOS LANCAMENTO CONTABIL E ITEM DO LANÇAMENTO, PARA CORRIGIR AS APRESENTAÇÕES EM DUPLICIDADE 
-- DOS TITULOS NA CONSULTA E NA BAIXA

UPDATE FATURAMENTO SET CTB_LANCAMENTO=NULL,CTB_ITEM=NULL
where STATUS_NFE in ('49','59') and 
(CTB_LANCAMENTO IS NOT NULL OR CTB_ITEM IS NOT NULL) 

UPDATE FATURAMENTO SET CTB_LANCAMENTO=NULL,CTB_ITEM=NULL
where NF_SAIDA='029071' AND SERIE_NF='2'

UPDATE FATURAMENTO SET CTB_LANCAMENTO=NULL,CTB_ITEM=NULL
where NF_SAIDA='029077' AND SERIE_NF='2'


-- 4o. Passo
-- RECARREGAR AS TRIGGERS SALVAS NA PASTA AJUSTAR FATURAS DUPLICADAS NA BAIXA (DESKTOP), DA TABELA DE ---- -- FATURAMENTO:
-- LXD_FATURAMENTO (MANUALMENTE: VER ARQUIVO NA PASTA)
-- LXI_FATURAMENTO (MANUALMENTE: VER ARQUIVO NA PASTA)
-- LXU_FATURAMENTO (MANUALMENTE: VER ARQUIVO NA PASTA)

-- 5o. Passo
-- APOS A RECARGA DAS TRIGGERS FAZER A MANUTENÇÃO

LX_MANUTENCAO

-- FINAL DO PROCESSO.
 