SELECT  A.PRODUTO,B.PRODUTO,A.COR_PRODUTO,B.COR_PRODUTO,A.PEDIDO,B.PEDIDO,A.ENTREGA,B.ENTREGA FROM FATURAMENTO_PROD A 
JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
a.produto='44940' and b.QTDE_ENTREGAR>0 AND A.PEDIDO='00418' 	
ORDER BY A.PEDIDO

SELECT distinct A.PEDIDO FROM FATURAMENTO_PROD A 
JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
b.QTDE_ENTREGAR>0 --A.PEDIDO='83666' 	
ORDER BY A.PEDIDO

SELECT A.PRODUTO,B.PRODUTO,A.COR_PRODUTO,B.COR_PRODUTO,A.PEDIDO,B.PEDIDO,A.ENTREGA,B.ENTREGA FROM VENDAS_PRODUTO A 
JOIN FATURAMENTO_PROD B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO IN ('00418')


UPDATE A SET A.ENTREGA=B.ENTREGA FROM FATURAMENTO_PROD A 
JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO IN ('00418     ')



--- SELECIONA TODOS OS PEDIDOS COM PROBLEMAS NA QTDE_ENTREGAR E MONTA O COMANDO PARA ATUALIZAR A DATA ENTREGA
SELECT distinct 
'UPDATE A SET A.ENTREGA=B.ENTREGA FROM VENDAS_PRODUTO A 
JOIN FATURAMENTO_PROD B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO 
WHERE A.PEDIDO IN ('''+A.PEDIDO+''')'
FROM FATURAMENTO_PROD A 
LEFT JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE b.QTDE_ENTREGAR>0 --A.PEDIDO='83666' 	

--- SELECIONA TODOS OS PEDIDOS COM PROBLEMAS NA QTDE_ENTREGAR E MONTA O COMANDO PARA RECALCULAR O PEDIDO 
SELECT distinct 
'EXEC LX_MOVIMENTA_VENDAS_PA '''+A.PEDIDO+''''
FROM FATURAMENTO_PROD A 
JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE b.QTDE_ENTREGAR>0 --A.PEDIDO='83666' 	


UPDATE A SET A.ENTREGA=B.ENTREGA FROM VENDAS_PRODUTO A 
JOIN FATURAMENTO_PROD B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO IN ('00418')


--- ATUALIZA A DATA ENTREGA DE CADA PEDIDO
UPDATE A SET A.ENTREGA=B.ENTREGA FROM VENDAS_PRODUTO A   JOIN FATURAMENTO_PROD B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO   WHERE A.PEDIDO IN ('12156')

--- RECALCULO DE CADA PEDIDO
EXEC LX_MOVIMENTA_VENDAS_PA '02931'