SELECT A.PRODUTO,B.PRODUTO,A.COR_PRODUTO,B.COR_PRODUTO,A.PEDIDO,B.PEDIDO,A.ENTREGA,B.ENTREGA FROM FATURAMENTO_PROD A 
LEFT JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO='548518' 	
ORDER BY A.PEDIDO

UPDATE A SET A.ENTREGA=B.ENTREGA FROM FATURAMENTO_PROD A 
LEFT JOIN VENDAS_PRODUTO B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO='548426'  	


UPDATE A SET A.ENTREGA=B.ENTREGA FROM VENDAS_PRODUTO A 
LEFT JOIN FATURAMENTO_PROD B ON A.PEDIDO=B.PEDIDO AND A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO --AND A.ENTREGA=B.ENTREGA
WHERE --B.PEDIDO IS NULL OR B.PRODUTO IS NULL OR B.COR_PRODUTO IS NULL OR B.ENTREGA IS NULL AND 
A.PEDIDO='548426'  	

SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO IN ('548426','549637','549608')
  	