---- CRIADO O TIPO 'REVALIDAR CADASTRO'
SELECT * FROM CLIENTES_ATACADO
WHERE TIPO='REVALIDAR CADASTRO'

UPDATE CLIENTES_ATACADO
SET TIPO='REVALIDAR CADASTRO'
WHERE CLIENTE_ATACADO IN (
SELECT CLIENTE_ATACADO FROM (
SELECT CLIENTE_ATACADO,EMISSAO=MAX(EMISSAO) 
FROM VENDAS
GROUP BY CLIENTE_ATACADO
HAVING MAX(EMISSAO) < GETDATE()-180 
) AS CLIENTE
)





	SELECT VENDAS.CLIENTE_ATACADO,MAX(VENDAS.EMISSAO) 
	FROM VENDAS, CLIENTES_ATACADO
	WHERE VENDAS.CLIENTE_ATACADO='LOJA SONHO INTIMO' AND CLIENTES_ATACADO.CLIENTE_ATACADO=VENDAS.CLIENTE_ATACADO AND VENDAS.APROVACAO='A' AND CLIENTES_ATACADO.TIPO='REVALIDAR CADASTRO'  
	GROUP BY VENDAS.CLIENTE_ATACADO
	HAVING (MAX(VENDAS.EMISSAO) < GETDATE()-180)	
