--- SOLUÇÃO PARA SOLICITAÇÃO DO CLIENTE RENNER
SELECT C.NOME_CLIFOR, B.CODIGO_BARRA,A.*  FROM FATURAMENTO_ITEM A
JOIN PRODUTOS_BARRA B ON RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE)=A.CODIGO_ITEM
JOIN FATURAMENTO C ON C.NF_SAIDA=A.NF_SAIDA AND C.SERIE_NF=A.SERIE_NF AND C.FILIAL=A.FILIAL
WHERE --RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE) ='51309-K7-G001U' AND 
A.NF_SAIDA ='0051487' AND
--'0051469','0051470','0051486','0051487'
CODIGO_BARRA_PADRAO=0 AND B.NOME_CLIFOR LIKE '%RENNER%' AND A.SERIE_NF='55'
ORDER BY A.NF_SAIDA

SELECT * FROM FATURAMENTO_ITEM
WHERE NF_SAIDA ='0051487'

SELECT * FROM PRODUTOS_BARRA
WHERE PRODUTO LIKE 'DR40507'  RTRIM(PRODUTO)+RTRIM(COR_PRODUTO)+RTRIM(GRADE)='DR40507799'


SELECT A.* FROM FATURAMENTO_ITEM A
JOIN PRODUTOS_BARRA B ON RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE)=A.CODIGO_ITEM
WHERE RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE) = '51309-K7-G001U' AND 
A.NF_SAIDA='0051469' AND CODIGO_BARRA_PADRAO=0 AND B.NOME_CLIFOR LIKE '%RENNER%'	


51309-K7-P001U                                    
51309-K7-M001U                                    
51309-K7-G001U                                    

--- ADICIONA O CÓDIGO DO CLIENTE NA DESCRIÇÃO DO ITEM
UPDATE A
SET A.FAIXA=1
FROM FATURAMENTO_ITEM A
JOIN PRODUTOS_BARRA B ON RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE)=A.CODIGO_ITEM
WHERE A.NF_SAIDA='0050867' AND CODIGO_BARRA_PADRAO=0 AND NOME_CLIFOR LIKE '%RENNER%'



--- ADICIONA O CÓDIGO DO CLIENTE NA DESCRIÇÃO DO ITEM
UPDATE A
SET A.DESCRICAO_ITEM=RTRIM(B.CODIGO_BARRA)+' - '+RTRIM(A.DESCRICAO_ITEM)
FROM FATURAMENTO_ITEM A
JOIN PRODUTOS_BARRA B ON RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE)=A.CODIGO_ITEM
WHERE A.NF_SAIDA='0050867' AND CODIGO_BARRA_PADRAO=0 AND NOME_CLIFOR LIKE '%RENNER%'


--- RETIRA O CÓDIGO DO CLIENTE DA DESCRIÇÃO DO ITEM PARA GERAÇÃO DO SPED
UPDATE A
SET A.DESCRICAO_ITEM=SUBSTRING(A.DESCRICAO_ITEM,13,80)
FROM FATURAMENTO_ITEM A
JOIN PRODUTOS_BARRA B ON RTRIM(B.PRODUTO)+RTRIM(B.COR_PRODUTO)+RTRIM(B.GRADE)=A.CODIGO_ITEM
WHERE A.NF_SAIDA='0050867' AND CODIGO_BARRA_PADRAO=0 AND NOME_CLIFOR LIKE '%RENNER%'


DECLARE  @fantasia_cliente varchar(70)

SET  @fantasia_cliente=''

select @fantasia_cliente = CLIENTES_ATACADO.CLIENTE_ATACADO
from  FATURAMENTO_ITEM,FATURAMENTO,CLIENTES_ATACADO
where FATURAMENTO_ITEM.NF_SAIDA  = FATURAMENTO.NF_SAIDA and 
      FATURAMENTO_ITEM.SERIE_NF  = FATURAMENTO.SERIE_NF and
      FATURAMENTO_ITEM.FILIAL    = FATURAMENTO.FILIAL and
      FATURAMENTO.NOME_CLIFOR    = CLIENTES_ATACADO.CLIENTE_ATACADO AND
      FATURAMENTO_ITEM.NF_SAIDA='0050867' AND CLIENTES_ATACADO.CLIENTE_ATACADO LIKE '%RENNER%'

PRINT @fantasia_cliente

