select b.DESCRICAO_ITEM, b.REFERENCIA,b.CODIGO_ITEM,b.SERIE_NF_ENTRADA, a.* 
FROM ENTRADAS A 
JOIN ENTRADAS_ITEM B ON A.NF_ENTRADA =B.NF_ENTRADA AND A.NOME_CLIFOR = B.NOME_CLIFOR
where A.recebimento between '20150601' and '20150630' and b.REFERENCIA <> substring(b.CODIGO_ITEM,1,5) and a.tipo_entradas='BENEFICIAMENTO'



UPDATE B SET REFERENCIA = substring(b.CODIGO_ITEM,8,9)
FROM ENTRADAS A 
JOIN ENTRADAS_ITEM B ON A.NF_ENTRADA =B.NF_ENTRADA AND A.NOME_CLIFOR = B.NOME_CLIFOR
where A.recebimento between '20150601' and '20150630' and b.REFERENCIA <> substring(b.CODIGO_ITEM,1,5) and a.tipo_entradas='BENEFICIAMENTO'



