insert into PRODUTOS_PRECOS (CODIGO_TAB_PRECO,PRODUTO) 
select DISTINCT 'VC',A.PRODUTO from produto_cores a
join PRODUTOS b on b.PRODUTO=a.PRODUTO
where B.GRUPO_PRODUTO<>'VAREJO-MERCHANDISING' AND a.PRODUTO not like 'v%' and b.COD_CATEGORIA='01' AND 
NOT EXISTS(select * from PRODUTOS_PRECOS WHERE PRODUTO=A.PRODUTO AND CODIGO_TAB_PRECO='Vc' )



select * from PRODUTOS_PRECOS
WHERE CODIGO_TAB_PRECO='Vc'

select * from MATERIAIS_PRECO
WHERE CODIGO_TAB_PRECO='Vb'


SELECT * FROM TABELAS_PRECO
WHERE CODIGO_TAB_PRECO in ('VB','vc')


SELECT SAW_REQUISICOES_MATERIAL.ID_REQUISICAO, SAW_REQUISICOES_MATERIAL.OFICINA, SAW_REQUISICOES_MATERIAL.ORDEM_PRODUCAO, SAW_REQUISICOES_MATERIAL.EMISSAO, SAW_REQUISICOES_MATERIAL.STATUS, SAW_REQUISICOES_MATERIAL.CONCLUSAO, SAW_REQUISICOES_MATERIAL_ITENS.ID_REQUISICAO, SAW_REQUISICOES_MATERIAL_ITENS.MATERIAL, SAW_REQUISICOES_MATERIAL_ITENS.COR_MATERIAL, SAW_REQUISICOES_MATERIAL_ITENS.DESC_MATERIAL, SAW_REQUISICOES_MATERIAL_ITENS.DESC_COR_MATERIAL, SAW_REQUISICOES_MATERIAL_ITENS.UNID_ESTOQUE, SAW_REQUISICOES_MATERIAL_ITENS.QTDE_REQUISITADA, SAW_REQUISICOES_MATERIAL_ITENS.QTDE_ATENDIDA, SAW_REQUISICOES_MATERIAL_ITENS.MOTIVO
FROM SAW_REQUISICOES_MATERIAL SAW_REQUISICOES_MATERIAL, SAW_REQUISICOES_MATERIAL_ITENS SAW_REQUISICOES_MATERIAL_ITENS
WHERE SAW_REQUISICOES_MATERIAL.ID_REQUISICAO = SAW_REQUISICOES_MATERIAL_ITENS.ID_REQUISICAO

