--- TABELAS SFV
SELECT * FROM CADASTRO_CLI_FOR
SELECT * FROM CLIENTE_REPRE
SELECT * FROM CLIENTES_ATACADO
SELECT * FROM COTA_LIMITE_PERFAT
SELECT * FROM FORMA_PGTO
SELECT * FROM LCF_LX_MUNICIPIO
SELECT * FROM LCF_LX_PAIS
SELECT * FROM LCF_LX_UF
SELECT * FROM LDR_PRODUTO_COR_ENTREGA_FUTURA
SELECT * FROM PRODUTO_CORES
SELECT * FROM PRODUTOS
SELECT * FROM PRODUTOS_BARRA
SELECT * FROM PRODUTOS_PERIODOS_ENTREGAS
SELECT * FROM PRODUTOS_PRECOS
SELECT * FROM PRODUTOS_TAMANHOS
SELECT * FROM REGIOES_VENDA
SELECT * FROM REPRESENTANTES
SELECT * FROM TBL_SFV_CONFIG


SELECT * FROM SFV_MATERIAL_PROMOCIONAL
SELECT * FROM TBL_LOG_IMPORT_EXPORT

SELECT * FROM VENDAS
SELECT * FROM VENDAS_LOTE
SELECT * FROM VENDAS_LOTE_PROD
SELECT * FROM VENDAS_PRODUTO_CONFIRMADOS



select distinct * from REPRESENTANTES

DANIEL MAGALHAES,09332848000192     
CLENILSON DE JESUS DOS SA,24147731000122              
KARLA VIEIRA FERREIRA,15671039000108         

exec SP_SFV_BUSCA_CLIENTES_REPRESENTANTE 'DANIEL MAGALHAES'


select * from PRODUTOs

select * from REPRESENTANTES
where REPRESENTANTE='KARLA VIEIRA FERREIRA'





SELECT * FROM VENDAS_PROD_EMBALADO


SELECT * FROM VENDAS_PRODUTO
WHERE PEDIDO='E1300-1234'




INSERT INTO CADASTRO_CLI_FOR (
NOME_CLIFOR,CARTEIRA,BANCO,CONTA_CONTABIL,CLIFOR,CGC_CPF,RAZAO_SOCIAL,PJ_PF,RG_IE,CEP,ENDERECO,COMPLEMENTO,NUMERO,BAIRRO,CIDADE,UF,TELEFONE1,PAIS,DDI,TELEFONE2,FAX,DDD1,RAMAL1,RAMAL2,DDD2,COBRANCA_ENDERECO,COBRANCA_NUMERO,COBRANCA_COMPLEMENTO,COBRANCA_CIDADE,COBRANCA_BAIRRO,DDDFAX,COBRANCA_UF,COBRANCA_CEP,COBRANCA_TELEFONE,ENTREGA_ENDERECO,ENTREGA_NUMERO,ENTREGA_COMPLEMENTO,ENTREGA_CIDADE,ENTREGA_UF,ENTREGA_BAIRRO,ENTREGA_CEP,ENTREGA_TELEFONE,COBRANCA_DDD,CONTATO,COBRANCA_CGC,CADASTRAMENTO,COBRANCA_IE,ANIVERSARIO,INDICA_FORNECEDOR,INDICA_CLIENTE,IND_REPRESENTANTE,INDICA_FILIAL,ENTREGA_DDD,ENTREGA_CGC,ENTREGA_IE,CC_AGENCIA,CC_CONTA,CC_NOME_AGENCIA,REF_ANTERIOR,ATUALIZACAO_EXPORTAR,DATA_EXPORTACAO,EMAIL,STATUS_ENVIO,INATIVO,DATA_PARA_TRANSFERENCIA,ENTREGA_PAIS,COBRANCA_PAIS,ENTREGA_DDI,COBRANCA_DDI,OBS_DE_FATURAMENTO,ISENTO_IPI,ISENTO_ICMS,IRRF,MESES_SEM_VENCIMENTO,DATA_FIXA_PGTO,ACEITA_AGRUPAR_FATURA,PASSWEB,VENCIMENTO_PASSWEB,NUMERO_VIAS_FATURA,REPORT_FATURA,DIAS_ANTECIPACAO_PGTO,POSSUI_RECARGO,CODIGO_CHAVE,TIPO_RELACAO_COMERCIAL,ID_CLASIF_CLIFOR,COD_CLIFOR,ENTREGA_RAZAO_SOCIAL,COBRANCA_RAZAO_SOCIAL,INDICADOR_FISCAL_TERCEIRO,CTB_CONTA_CONTABIL,ACEITA_DIAS_FIXO,ID_EXCECAO_GRUPO,AGRUPAMENTO_ITENS,CODIGO_CONTATO,IM,IM_ENTREGA,IM_COBRANCA,NOVO_CLIENTE,EXPORTADO,CADASTRO_CLI_FOR,INSCRICAO_SUFRAMA,CNAE,INCL_AUTO_GRP_ECON,EMAIL_NFE,COD_MUNICIPIO_IBGE,COD_MUNICIPIO_IBGE_ENTREGA,COD_MUNICIPIO_IBGE_COBRANCA,CODIGO_SPC,ENVIADO_SPC)
VALUES (
'ROBERTO CARLOS',NULL,NULL,NULL,'900001','01790247000111','ROBERTO CARLOS BRAGA',1,0,'27000000','RUA DOS CACHOEIROS','','1000','CENTRO','CACHOEIRO DE ITAPEMIRIM','ES','39393939','BRASIL','055'  ,'','','027'  , ''    ,  ''   , ''    ,'RUA DOS CACHOEIROS','1000','','CACHOEIRO DE ITAPEMIRIM','CENTRO',  ''   ,'ES','27000000','39393939','RUA DOS CACHOEIROS','1000','','CACHOEIRO DE ITAPEMIRIM','ES','CENTRO','27000000','39393939','027'  ,'ROBERTO','01790247000111','2016-04-12 13:51:50.450',0,'2016-08-28 00:00:00.000',0,1,0,0,'027'  ,'01790247000111',0,NULL,NULL,NULL,NULL,NULL,NULL,'bebeto@robertocarlos.com.br',NULL,0,NULL,'BRASIL','BRASIL','055'  ,'055'  ,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'900001','ROBERTO CARLOS BRAGA','ROBERTO CARLOS BRAGA',2,NULL,0,NULL,NULL,NULL,'','','',1,0,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL
)

INSERT INTO CADASTRO_CLI_FOR(
NOME_CLIFOR,CARTEIRA,BANCO,CONTA_CONTABIL,CLIFOR,CGC_CPF,RAZAO_SOCIAL,PJ_PF,RG_IE,CEP,ENDERECO,COMPLEMENTO,NUMERO,BAIRRO,CIDADE,UF,TELEFONE1,PAIS,DDI,TELEFONE2,FAX,DDD1,RAMAL1,RAMAL2,DDD2,COBRANCA_ENDERECO,COBRANCA_NUMERO,COBRANCA_COMPLEMENTO,COBRANCA_CIDADE,COBRANCA_BAIRRO,DDDFAX,COBRANCA_UF,COBRANCA_CEP,COBRANCA_TELEFONE,ENTREGA_ENDERECO,ENTREGA_NUMERO,ENTREGA_COMPLEMENTO,ENTREGA_CIDADE,ENTREGA_UF,ENTREGA_BAIRRO,ENTREGA_CEP,ENTREGA_TELEFONE,COBRANCA_DDD,CONTATO,COBRANCA_CGC,CADASTRAMENTO,COBRANCA_IE,ANIVERSARIO,INDICA_FORNECEDOR,INDICA_CLIENTE,IND_REPRESENTANTE,INDICA_FILIAL,ENTREGA_DDD,ENTREGA_CGC,ENTREGA_IE,CC_AGENCIA,CC_CONTA,CC_NOME_AGENCIA,REF_ANTERIOR,ATUALIZACAO_EXPORTAR,DATA_EXPORTACAO,EMAIL,STATUS_ENVIO,INATIVO,DATA_PARA_TRANSFERENCIA,ENTREGA_PAIS,COBRANCA_PAIS,ENTREGA_DDI,COBRANCA_DDI,OBS_DE_FATURAMENTO,ISENTO_IPI,ISENTO_ICMS,IRRF,MESES_SEM_VENCIMENTO,DATA_FIXA_PGTO,ACEITA_AGRUPAR_FATURA,PASSWEB,VENCIMENTO_PASSWEB,NUMERO_VIAS_FATURA,REPORT_FATURA,DIAS_ANTECIPACAO_PGTO,POSSUI_RECARGO,CODIGO_CHAVE,TIPO_RELACAO_COMERCIAL,ID_CLASIF_CLIFOR,COD_CLIFOR,ENTREGA_RAZAO_SOCIAL,COBRANCA_RAZAO_SOCIAL,INDICADOR_FISCAL_TERCEIRO,CTB_CONTA_CONTABIL,ACEITA_DIAS_FIXO,ID_EXCECAO_GRUPO,AGRUPAMENTO_ITENS,CODIGO_CONTATO,IM,IM_ENTREGA,IM_COBRANCA,NOVO_CLIENTE,EXPORTADO,CADASTRO_CLI_FOR,INSCRICAO_SUFRAMA,CNAE,INCL_AUTO_GRP_ECON,EMAIL_NFE,COD_MUNICIPIO_IBGE,COD_MUNICIPIO_IBGE_ENTREGA,COD_MUNICIPIO_IBGE_COBRANCA,CODIGO_SPC,ENVIADO_SPC)
values('JOAO DAS FLORES ES',NULL,NULL,NULL,'Q5JYF7','00057859000137','JOAO DAS FLORES ES',1,'454545455','27000000','RUA DAS PEDRAS','JARDINS DAS FLORES','1000','CENTRO','ARACRUZ','ES','55555555','BRASIL','055'  ,'','', '27'  , ''    , ''    , ''    ,'RUA DAS PEDRAS','1000','JARDINS DAS FLORES','ARACRUZ','CENTRO', ''    ,'ES','27000000','55555555','RUA DAS PEDRAS','1000','JARDINS DAS FLORES','ARACRUZ','ES','CENTRO','27000000','55555555', '27'  ,'JOAO','00057859000137','2016-04-25 15:42:29.040','454545455','2016-04-25 00:00:00.000',0,1,0,0, '27'  ,'00057859000137','454545455',NULL,NULL,NULL,NULL,NULL,NULL,'teste@joao.com.br',NULL,0,NULL,'BRASIL','BRASIL','055'  ,'055'  ,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Q5JYF7','JOAO DAS FLORES ES','JOAO DAS FLORES ES',2,NULL,0,NULL,NULL,NULL,'','','',1,0,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL)

delete from CADASTRO_CLI_FOR
where NOME_CLIFOR='JOAO DAS FLORES ES'


INSERT INTO CLIENTES_ATACADO (
CLIENTE_ATACADO,COD_CLIENTE,CONDICAO_PGTO,REGIAO,MATRIZ_CLIENTE,FILIAL,PONTUALIDADE,TRANSPORTADORA,CONCEITO,TIPO,TIPO_BLOQUEIO,CGC_CPF,CLIFOR,FRETE_A_PAGAR,PRIORIDADE,SEM_CREDITO,LIMITE_CREDITO,BLOQUEIO_EXPEDICAO,BLOQUEIO_FATURAMENTO,ACEITA_JUNTAR_PED,BLOQUEIO_PEDIDOS,NUMERO_PEDIDOS,DATA_MAIOR_PEDIDO,MAIOR_PEDIDO,DATA_MAIOR_QTDE_PEDIDO,MAIOR_QTDE_PEDIDO,MAIOR_SALDO,DATA_MAIOR_SALDO,NUMERO_ATRASOS,MAIOR_ATRASO,PGTOS_CARTORIO,NUMERO_DEVOLUCOES,DATA_MAIOR_DEVOLUCAO,MAIOR_DEVOLUCAO,DATA_MAIOR_QTDE_DEV,MAIOR_QTDE_DEV,NUMERO_PRORROGACOES,MAIOR_PRORROGACAO,DESCONTO_FATURAMENTO,OBS,INATIVO,MOEDA,DATA_PARA_TRANSFERENCIA,INDICA_FRANQUIA,CODIGO_TAB_PRECO,FATOR_CUSTO_FRANQUIA,DESCONTO_PEDIDO_VENDA,SEGURO_NUMERO_CONTRATO,SEGURO_NUMERO_CLIENTE,SEGURO_VALIDADE,CONTA_CONTABIL,MESES_SEM_VENCIMENTO,EXPEDICAO_COMPLETO_PEDIDO,EXPEDICAO_COMPLETO_PACK,EXPEDICAO_COMPLETO_TAMANHOS,EXPEDICAO_COMPLETO_COR,EXPEDICAO_COMPLETO_COORDENADO,EXPEDICAO_COMPLETO_CARTELA,EXPEDICAO_PORCENTAGEM_MAIOR,EXPEDICAO_PORCENTAGEM_MINIMA,EXPEDICAO_PORCENTAGEM_TIPO,EXPEDICAO_VALOR_MAXIMO,CONTA_CONTABIL_ANTECIPACAO,TRANSP_REDESPACHO,CONTA_CONTABIL_VENDAS_TIPO,TRANSPORTADORA2,CTB_CONTA_CONTABIL,EXPEDICAO_COMPLETO_FAIXAS,DESCONTO_BRUTO,DESCONTO_BRUTO_1,DESCONTO_BRUTO_2,DESCONTO_BRUTO_3,DESCONTO_BRUTO_4,DESCONTO_SOBRE_1,DESCONTO_SOBRE_2,DESCONTO_SOBRE_3,DESCONTO_SOBRE_4,EXPEDICAO_PORC_ADEQUACAO,EXPEDICAO_QTDE_ADEQUACAO,EXPEDICAO_ADEQUACAO_COR,EXPEDICAO_ADEQUACAO_TAMANHO,MULTI_DESCONTO_ACUMULAR,INDICADOR_VENDA,DATA_MAIOR_ATRASO,MAIOR_VALOR_FATURADO,DATA_MAIOR_VALOR_FATURADO,DT_ULTIMA_VENDA,DT_PENULTIMA_VENDA,DT_ANTEPENULTIMA_VENDA,DT_PRIMEIRA_VENDA)
VALUES('ROBERTO CARLOS','900001','000','RV-01 ZN-01 ST-14','ROBERTO CARLOS','DR VAREJO','PONTUAL','SEU TRANSPORTE','BOM','VAREJO','COMERCIAL','01790247000111','900001',0,7,0,2500.00,NULL,NULL,1,NULL,0,NULL,0.00,NULL,0,0.00,NULL,0,0,0,0,NULL,0.00,NULL,0,0,0,0.00000,NULL,0,'R$'    ,NULL,0,'VE',0.000,0.0000,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,'95',0,0.00,NULL,NULL,NULL,NULL,'1120101',0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0000000000,0,0,0,0,'V',NULL,0.00,NULL,NULL,NULL,NULL,NULL)

INSERT INTO CLIENTES_ATACADO (
CLIENTE_ATACADO,COD_CLIENTE,CONDICAO_PGTO,REGIAO,MATRIZ_CLIENTE,FILIAL,PONTUALIDADE,TRANSPORTADORA,CONCEITO,TIPO,TIPO_BLOQUEIO,CGC_CPF,CLIFOR,FRETE_A_PAGAR,PRIORIDADE,SEM_CREDITO,LIMITE_CREDITO,BLOQUEIO_EXPEDICAO,BLOQUEIO_FATURAMENTO,ACEITA_JUNTAR_PED,BLOQUEIO_PEDIDOS,NUMERO_PEDIDOS,DATA_MAIOR_PEDIDO,MAIOR_PEDIDO,DATA_MAIOR_QTDE_PEDIDO,MAIOR_QTDE_PEDIDO,MAIOR_SALDO,DATA_MAIOR_SALDO,NUMERO_ATRASOS,MAIOR_ATRASO,PGTOS_CARTORIO,NUMERO_DEVOLUCOES,DATA_MAIOR_DEVOLUCAO,MAIOR_DEVOLUCAO,DATA_MAIOR_QTDE_DEV,MAIOR_QTDE_DEV,NUMERO_PRORROGACOES,MAIOR_PRORROGACAO,DESCONTO_FATURAMENTO,OBS,INATIVO,MOEDA,DATA_PARA_TRANSFERENCIA,INDICA_FRANQUIA,CODIGO_TAB_PRECO,FATOR_CUSTO_FRANQUIA,DESCONTO_PEDIDO_VENDA,SEGURO_NUMERO_CONTRATO,SEGURO_NUMERO_CLIENTE,SEGURO_VALIDADE,CONTA_CONTABIL,MESES_SEM_VENCIMENTO,EXPEDICAO_COMPLETO_PEDIDO,EXPEDICAO_COMPLETO_PACK,EXPEDICAO_COMPLETO_TAMANHOS,EXPEDICAO_COMPLETO_COR,EXPEDICAO_COMPLETO_COORDENADO,EXPEDICAO_COMPLETO_CARTELA,EXPEDICAO_PORCENTAGEM_MAIOR,EXPEDICAO_PORCENTAGEM_MINIMA,EXPEDICAO_PORCENTAGEM_TIPO,EXPEDICAO_VALOR_MAXIMO,CONTA_CONTABIL_ANTECIPACAO,TRANSP_REDESPACHO,CONTA_CONTABIL_VENDAS_TIPO,TRANSPORTADORA2,CTB_CONTA_CONTABIL,EXPEDICAO_COMPLETO_FAIXAS,DESCONTO_BRUTO,DESCONTO_BRUTO_1,DESCONTO_BRUTO_2,DESCONTO_BRUTO_3,DESCONTO_BRUTO_4,DESCONTO_SOBRE_1,DESCONTO_SOBRE_2,DESCONTO_SOBRE_3,DESCONTO_SOBRE_4,EXPEDICAO_PORC_ADEQUACAO,EXPEDICAO_QTDE_ADEQUACAO,EXPEDICAO_ADEQUACAO_COR,EXPEDICAO_ADEQUACAO_TAMANHO,MULTI_DESCONTO_ACUMULAR,INDICADOR_VENDA,DATA_MAIOR_ATRASO,MAIOR_VALOR_FATURADO,DATA_MAIOR_VALOR_FATURADO,DT_ULTIMA_VENDA,DT_PENULTIMA_VENDA,DT_ANTEPENULTIMA_VENDA,DT_PRIMEIRA_VENDA)
values('JOAO DAS FLORES ES','Q5JYF7','000','RV-01 ZN-01 ST-14','JOAO DAS FLORES ES','DR VAREJO','PONTUAL','SEU TRANSPORTE','BOM','VAREJO','COMERCIAL','00057859000137','Q5JYF7',0,7,0,0.00,NULL,NULL,1,NULL,0,NULL,0.00,NULL,0,0.00,NULL,0,0,0,0,NULL,0.00,NULL,0,0,0,0.00000,NULL,0,'R$'    ,NULL,0,'VE',0.000,0.0000,NULL,NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,'95',0,0.00,NULL,NULL,NULL,NULL,'1125001001',0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0000000000,0,0,0,0,'V',NULL,0.00,NULL,NULL,NULL,NULL,NULL)

delete from CLIENTES_ATACADO
where CLIENTE_ATACADO='JOAO DAS FLORES ES'

INSERT INTO CLIENTE_REPRE (
REPRESENTANTE,CLIENTE_ATACADO,DATA_PARA_TRANSFERENCIA,COMISSAO,REPRESENTANTE_PRINCIPAL)
VALUES(
'KARLA VIEIRA FERREIRA','ROBERTO CARLOS','2016-04-12 13:51:50.777',0.00000,1
)


INSERT INTO CLIENTE_REPRE (
REPRESENTANTE,CLIENTE_ATACADO,DATA_PARA_TRANSFERENCIA,COMISSAO,REPRESENTANTE_PRINCIPAL)
VALUES('KARLA VIEIRA FERREIRA','JOAO DAS FLORES ES','2016-04-25 17:32:51.513',0.00000,1)
