USE [DRVAREJO]
GO

/****** Object:  Table [dbo].[LDR_PRODUCAO_ORDEM_AVIAMENTOS]    Script Date: 02/25/2014 07:43:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

DROP TABLE LDR_PRODUCAO_ORDEM_AVIAMENTOS

CREATE TABLE [dbo].[LDR_PRODUCAO_ORDEM_AVIAMENTOS](
	[ORDEM_PRODUCAO] [char](8) NOT NULL,
	[DTA_INICIO_REAL_NSEP] [datetime] NULL,
	[DTA_INICIO_REAL_ESEP] [datetime] NULL,
	[DTA_INICIO_REAL_SEP] [datetime] NULL,
	[DTA_PREVISTO_FIM_SEP] [datetime] NULL,
	[DTA_INICIO_REAL_VIES] [datetime] NULL,
	[DTA_PREVISAO_FIM_VIES] [datetime] NULL,
	[STATUS_SEP_AVIAMENTO] [char](1) NULL,
	[STATUS_VIES] [char](1) NULL,
	[PENDENCIA] [char](1) NULL,
 CONSTRAINT [XPKLDR_PRODUCAO_ORDEM_AVIAMENTOS] PRIMARY KEY NONCLUSTERED 
(
	[ORDEM_PRODUCAO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


