--- VIEW DOS DADOS FINALIZADOS NAS FASES
CREATE VIEW v_producao_recurso_creditos_01 AS 
SELECT PRODUCAO_OS_ANTERIOR.TAREFA,PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR,  PRODUCAO_ORDEM_SERVICO.DATA, 
PRODUCAO_TAREFAS.RECURSO_PRODUTIVO,   PRODUCAO_RECURSOS.DESC_RECURSO, PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO,   
PRODUCAO_ORDEM_SERVICO.NF_ENTRADA, PRODUCAO_TAREFAS.FASE_PRODUCAO,   PRODUCAO_FASE.DESC_FASE_PRODUCAO, 
PRODUCAO_TAREFAS.SETOR_PRODUCAO, PRODUCAO_SETOR.DESC_SETOR_PRODUCAO, PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO,  
PRODUCAO_OS_ANTERIOR.PRODUTO, PRODUTOS.DESC_PRODUTO,   PRODUCAO_OS_ANTERIOR.COR_PRODUTO,  
ISNULL(PRODUCAO_TAREFAS_SALDO.QTDE_S,0)AS QTDE_S, QTDE_A_PRODUZIR,   QTDE_A, QTDE_R,   
PRODUCAO_OS_ANTERIOR.CUSTO_EFETIVO, PRODUCAO_OS_ANTERIOR.DESCONTO_APLICADO,  PRODUCAO_OS_ANTERIOR.VALOR_CREDITADO,  
PRODUCAO_ORDEM_SERVICO.CONFERIDO_POR,  PRODUCAO_ORDEM_SERVICO.FILIAL, PRODUCAO_TAREFAS.INICIO_PREVISTO,   
PRODUCAO_TAREFAS.INICIO_REAL, PRODUCAO_TAREFAS.FIM_PREVISTO,  PRODUCAO_TAREFAS.ENCERRAMENTO, 
PRODUCAO_ORDEM_SERVICO.OBSERVACAO,  PRODUCAO_TAREFAS.OBS AS OBS_TAREFA, PRODUCAO_TAREFAS.FIM_ATUALIZADO,  
PRODUCAO_RECURSOS.TIPO_RECURSO,  PRODUCAO_RECURSOS.RECURSO_PROPRIO,  PRODUCAO_RECURSOS.NOME_CLIFOR, 
PRODUCAO_TAREFAS.CUSTO_TAREFA AS CUSTO_PREVISTO,   PRODUCAO_TAREFAS.CUSTO_TAREFA*PRODUCAO_OS_ANTERIOR.QTDE_A AS VALOR_PREVISTO,
GRUPO_PRODUTO,SUBGRUPO_PRODUTO,COLECAO, LINHA,GRIFFE,MODELAGEM,TABELA_OPERACOES,TIPO_PRODUTO, 
FILIAIS.EMPRESA,PRODUCAO_TAREFAS.SETOR_PARALELO_NUMERO  , PRODUCAO_OS_TAREFAS.INDICADOR_TIPO_MOV  
FROM FX_PRODUCAO_RECURSO_CREDITOS() AS PRODUCAO_OS_ANTERIOR  
INNER JOIN PRODUCAO_OS_TAREFAS ON PRODUCAO_OS_TAREFAS.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO  AND 
PRODUCAO_OS_TAREFAS.ORDEM_PRODUCAO = PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO  AND 
PRODUCAO_OS_TAREFAS.PRODUTO = PRODUCAO_OS_ANTERIOR.PRODUTO  AND 
PRODUCAO_OS_TAREFAS.COR_PRODUTO = PRODUCAO_OS_ANTERIOR.COR_PRODUTO  AND 
PRODUCAO_OS_TAREFAS.TAREFA = PRODUCAO_OS_ANTERIOR.TAREFA  
INNER JOIN PRODUCAO_TAREFAS ON  PRODUCAO_OS_ANTERIOR.TAREFA_AUX = PRODUCAO_TAREFAS.TAREFA  
INNER JOIN PRODUCAO_ORDEM_SERVICO ON PRODUCAO_ORDEM_SERVICO.ORDEM_SERVICO = PRODUCAO_OS_ANTERIOR.ORDEM_SERVICO   
LEFT  JOIN PRODUCAO_TAREFAS_SALDO ON PRODUCAO_OS_ANTERIOR.ORDEM_PRODUCAO = PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO  AND 
PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO   AND 
PRODUCAO_OS_ANTERIOR.COR_PRODUTO = PRODUCAO_TAREFAS_SALDO.COR_PRODUTO   AND 
PRODUCAO_TAREFAS.TAREFA = PRODUCAO_TAREFAS_SALDO.TAREFA   AND 
PRODUCAO_OS_ANTERIOR.TAREFA_ANTERIOR = PRODUCAO_TAREFAS_SALDO.TAREFA   
INNER JOIN PRODUTOS ON PRODUCAO_OS_ANTERIOR.PRODUTO = PRODUTOS.PRODUTO   
INNER JOIN PRODUCAO_FASE ON PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_FASE.FASE_PRODUCAO   
INNER JOIN PRODUCAO_SETOR ON PRODUCAO_TAREFAS.SETOR_PRODUCAO = PRODUCAO_SETOR.SETOR_PRODUCAO  AND  
PRODUCAO_TAREFAS.FASE_PRODUCAO = PRODUCAO_SETOR.FASE_PRODUCAO   
INNER JOIN PRODUCAO_RECURSOS ON PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO   
INNER JOIN FILIAIS ON PRODUCAO_ORDEM_SERVICO.FILIAL  = FILIAIS.FILIAL   

SELECT * FROM v_producao_recurso_creditos_01
WHERE DATA >= '20120725' AND DATA <= '20120725' AND FASE_PRODUCAO = '008'

select * from ldr_metas_oficina_grupo_nova 

SELECT * FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA 

select * from W_ORDEM_PRODUCAO_OFICINA_NOVA

CREATE VIEW W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA AS   
SELECT DISTINCT A.FILIAL,DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,A.EMISSAO,  
TEMPO_PADRAO=  
(  
SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS   
WHERE TABELA_OPERACOES = C.PRODUTO AND TEMPO_CRONOMETRADO>0   
),   
QTDE=SUM(QTDE),  
QTDE_OPERADOR=(  
    select distinct qtde_operador from ldr_metas_oficina_grupo_nova   
    where desc_recurso=B.DESC_RECURSO and desc_SETOR_producao=B.DESC_SETOR_PRODUCAO   
    and data_producao= A.EMISSAO   
),  
MINUTOS_DISPONIVEIS=(  
    select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova   
    where desc_recurso=B.DESC_RECURSO and desc_setor_producao=B.DESC_setor_PRODUCAO   
    and data_producao= A.EMISSAO   
)  
FROM ESTOQUE_PROD_ENT A,W_ORDEM_PRODUCAO_OFICINA_NOVA B, ESTOQUE_PROD1_ENT C  
WHERE A.ORDEM_PRODUCAO=B.ORDEM_CORTE AND C.ROMANEIO_PRODUTO=A.ROMANEIO_PRODUTO   
AND C.ORDEM_PRODUCAO=B.ORDEM_PRODUCAO AND A.EMISSAO>='20120101' AND A.EMISSAO<=GETDATE()  
GROUP BY A.FILIAL,DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,A.EMISSAO  

SELECT  
A.FILIAL, 
OFICINA=a.DESC_SETOR_PRODUCAO, 
GRUPO=a.DESC_RECURSO, 
a.TIPO_RECURSO, 
ANO=substring(convert(char(10),A.DATA,103),7,4), 
MES=substring(convert(char(10),A.DATA,103),4,2), 
DIA01=(
       SELECT SUM(A1.QTDE_A) FROM v_producao_recurso_creditos_01 A1 
       WHERE A1.DATA='20120725' AND A1.DESC_RECURSO=C.DESC_RECURSO AND A1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL 
), 
--MTCR01=( 
--       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA 
--       WHERE EMISSAO = '20120725' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL 
--), 
TOTAL=SUM(QTDE_A),DTRAB=0 
FROM v_producao_recurso_creditos_01 A 
LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO  
WHERE DATA >= '20120725' AND DATA <= '20120725' AND FASE_PRODUCAO = '008'
GROUP BY A.FILIAL,
a.DESC_RECURSO,
a.DESC_SETOR_PRODUCAO, 
a.TIPO_RECURSO, 
substring(convert(char(10),A.DATA,103),7,4), 
substring(convert(char(10),A.DATA,103),4,2) 

** SCRIPT DADOS CABEÇALHO
cSelectALL1=+;
[SELECT  ]+;
[A.FILIAL, ]+;
[OFICINA=C.DESC_SETOR_PRODUCAO, ]+;
[GRUPO=C.DESC_RECURSO, ]+;
[C.TIPO_RECURSO, ]+; 
[ANO=substring(convert(char(10),B.EMISSAO,103),7,4), ]+;
[MES=substring(convert(char(10),B.EMISSAO,103),4,2), ]+;
[DIA01=( ]+;
[       SELECT SUM(B1.QTDE) FROM v_producao_recurso_creditos_01 A1 ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[1]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR01=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[1]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA02=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[2]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR02=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[2]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA03=( ]+;
[      SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[3]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR03=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[3]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA04=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[4]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR04=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[4]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA05=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+; 
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[5]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR05=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[5]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA06=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[6]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR06=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[6]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA07=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[7]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR07=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[7]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA08=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[8]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR08=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[8]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]

cSelectALL2=+;
[DIA09=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[9]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR09=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[9]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA10=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[10]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR10=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[10]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA11=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[11]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR11=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[11]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA12=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[12]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR12=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[12]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA13=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[13]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR13=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[13]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA14=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[14]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR14=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[14]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA15=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[15]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR15=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[15]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA16=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[16]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR16=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[16]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]

cSelectALL3=+;
[DIA17=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[17]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR17=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[17]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA18=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[18]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR18=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[18]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA19=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[19]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR19=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[19]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA20=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[20]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR20=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[20]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA21=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[21]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR21=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[21]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA22=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[22]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR22=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[22]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA23=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[23]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR23=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[23]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA24=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[24]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR24=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[24]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]

cSelectALL4=+;
[DIA25=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[25]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR25=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[25]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA26=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[26]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR26=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[26]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA27=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[27]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR27=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[27]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA28=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[28]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR28=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[28]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA29=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[29]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR29=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[29]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA30=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[30]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR30=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[30]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[DIA31=( ]+;
[       SELECT SUM(B1.QTDE) FROM ESTOQUE_PROD_ENT A1 ]+;
[       JOIN ESTOQUE_PROD1_ENT B1 ON A1.ROMANEIO_PRODUTO=B1.ROMANEIO_PRODUTO ]+;
[       LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C1 ON C1.ORDEM_PRODUCAO=B1.ORDEM_PRODUCAO ]+;
[       WHERE A1.EMISSAO=']+ADatas_Emissao[31]+[' AND C1.DESC_RECURSO=C.DESC_RECURSO AND C1.DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND A1.FILIAL=A.FILIAL ]+;
[), ]+;
[MTCR31=( ]+;
[       SELECT SUM(TEMPO_PADRAO*QTDE) FROM W_OFICINA_GRUPO_REFERENCIA_TEMPO_NOVA ]+;
[       WHERE EMISSAO = ']+ADatas_Emissao[31]+[' AND DESC_RECURSO=C.DESC_RECURSO AND DESC_SETOR_PRODUCAO=C.DESC_SETOR_PRODUCAO AND FILIAL=A.FILIAL ]+;
[), ]+;
[TOTAL=SUM(QTDE),DTRAB=0 FROM v_producao_recurso_creditos_01 A ]+;
[LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO  ]+;
[WHERE ]+xfiltro+[ ]+;
[GROUP BY A.FILIAL, ]+;
[C.DESC_RECURSO, ]+;
[C.DESC_SETOR_PRODUCAO, ]+;
[C.TIPO_RECURSO, ]+;
[substring(convert(char(10),B.EMISSAO,103),7,4), ]+;
[substring(convert(char(10),B.EMISSAO,103),4,2)  ]
