
--- TELA 006202SPK ENTRADA DE MATERIAIS PARA O ESTOQUE
select * from USERS_TRANSACOES
WHERE COD_TRANSACAO='ESTOQUE_RET_MAT_001'

select * from USERS_TRANSACOES
WHERE COD_TRANSACAO='ESTOQUE_RET_MAT_002'