--- disabilitar trigger da tabela abaixo

UPDATE CTB_CONTA_TIPO
SET INDICA_ID_CONTABIL_TERCEIRO=0
WHERE TIPO_CONTA='1120113'


begin tran

UPDATE CTB_CONTA_TIPO
SET INDICA_ID_CONTABIL_TERCEIRO=0
WHERE TIPO_CONTA='1120103'

commit

INSERT INTO CTB_TIPO_LANC_CONTA (LX_TIPO_LANCAMENTO,TIPO_CONTA,CODIGO_HISTORICO) 
VALUES('BTR','1120113','BTR')

