SELECT * FROM TRANSPORTADORAS T
WHERE NOT EXISTS (SELECT DESC_MUNICIPIO FROM LCF_LX_MUNICIPIO WHERE DESC_MUNICIPIO=T.CIDADE)


SELECT * FROM CADASTRO_CLI_FOR F
WHERE INDICA_FORNECEDOR=1 AND NOT EXISTS (SELECT DESC_MUNICIPIO FROM LCF_LX_MUNICIPIO WHERE DESC_MUNICIPIO=F.CIDADE)


SELECT TRANSPORTADORA_A_PAGAR,NF_ENTRADA,SERIE_NF_ENTRADA FROM ENTRADAS E
WHERE RECEBIMENTO BETWEEN '20150801' AND '20150831' AND NOT EXISTS (SELECT TRANSPORTADORA FROM TRANSPORTADORAS WHERE TRANSPORTADORA=E.TRANSPORTADORA_A_PAGAR)
