-- titulos emitidos e com datas de pagamento
SELECT A.FILIAL,A.RAZAO_SOCIAL,A.FATURA,A.ID_PARCELA,A.EMISSAO,A.VENCIMENTO_REAL,A.VALOR_ORIGINAL_PADRAO,
DATA_PAGAMENTO = (SELECT MAX(DATA_PAGAMENTO) FROM CTB_A_RECEBER_MOV B with (nolock) WHERE B.LANCAMENTO_MOV=A.LANCAMENTO and B.ITEM_MOV=A.ITEM and b.ID_PARCELA=a.ID_PARCELA),
VALOR_MOV_PADRAO = (SELECT SUM(VALOR_MOV_PADRAO) FROM CTB_A_RECEBER_MOV B with (nolock) WHERE B.LANCAMENTO_MOV=A.LANCAMENTO and B.ITEM_MOV=A.ITEM and b.ID_PARCELA=a.ID_PARCELA)
FROM W_CTB_A_RECEBER_PARCELA A with (nolock)
WHERE A.EMISSAO >= '20150301' AND A.EMISSAO <= '20150918'


--- titulos recebidos e com data de pagamento
SELECT B.DATA_PAGAMENTO,b.VALOR_MOV_PADRAO,B.DESCONTO_CONCEDIDO, b.VALOR_MOV, A.* 
FROM W_CTB_A_RECEBER_PARCELA A with (nolock)
LEFT JOIN CTB_A_RECEBER_MOV B with (nolock) ON B.LANCAMENTO_MOV=A.LANCAMENTO and B.ITEM_MOV=A.ITEM and b.ID_PARCELA=a.ID_PARCELA
WHERE B.DATA_PAGAMENTO >= '20150301' AND B.DATA_PAGAMENTO <= '20150918'





