-- TROCA DE TABELA PARA OS CLIENTES
UPDATE CLIENTES_ATACADO
SET CODIGO_TAB_PRECO='VE'
WHERE CODIGO_TAB_PRECO='VA'
GO
-- TROCA DE TABELA PARA OS CLIENTES
UPDATE CLIENTES_ATACADO
SET CODIGO_TAB_PRECO='VH'
WHERE CODIGO_TAB_PRECO='VD'
GO
-- TROCA DE TABELA PARA OS CLIENTES
UPDATE CLIENTES_ATACADO
SET CODIGO_TAB_PRECO='VG'
WHERE CODIGO_TAB_PRECO='VF'
GO


NACIONAL	VA	VE
SUFRAMA	VD	VH
PESSOA FÍSICA	VF	VG




SELECT CODIGO_TAB_PRECO,CLIENTE_ATACADO FROM CLIENTES_ATACADO
WHERE  REGIAO = 'RV-01 ZN-01 ST-10' AND CODIGO_TAB_PRECO<>'BM' AND CODIGO_TAB_PRECO<>'BN'

SELECT TIPO,REGIAO, CODIGO_TAB_PRECO,CLIENTE_ATACADO FROM CLIENTES_ATACADO
WHERE FILIAL='DR VAREJO'

CODIGO_TAB_PRECO<>'BN' AND CODIGO_TAB_PRECO <> 'DR' AND TIPO NOT IN('COLABORADOR              ','BALCONISTA               ')

UPDATE CLIENTES_ATACADO
SET CODIGO_TAB_PRECO='BM'
WHERE CODIGO_TAB_PRECO<>'BM' AND CODIGO_TAB_PRECO<>'BN' AND CODIGO_TAB_PRECO <> 'DR' AND TIPO NOT IN('COLABORADOR              ','BALCONISTA               ')







TABELA ANTIGA                              TABELA ATUAL

      BG                                                        BJ
      BH                                                        BK
      BI                                                          BL
