
UPDATE CLIENTE_REPRE
SET REPRESENTANTE_PRINCIPAL=1
WHERE REPRESENTANTE='AGOMAR MARCOS CHAVES' AND CLIENTE_ATACADO in (
'ATACADO BUENO            ',
'EXCLUSIVE',
'GIANY LNGERIE',
'MAGAZINE SCHERER',
'T  T CONFECES')

'CONFECCOES CITTADIN LTDA  ',
'KAKA LINGERIE BY MARTA   ',
'ATACADO BUENO            ',
'CASA IRIS RV-02          ',
'COMERCIO DE PROD. MANUE  ',
'CONFECCOES VARGAS LTDA   ',
'CRIATIVA MODAS RV-02     ',
'DIONISIO POSTAL          ',
'LINDA MORENA MODAS       ',
'ATACADO LIDERANCA        ',
'JADA DIST DE CONF LTDA   ',
'LEONEL DOS SANTOS        ',
'LJ NS APARECIDA          ',
'LOJA CILTA               ',
'LOJA O DOIDAO RV-02      ',
'LOJAO DA MOLEZA          ',
'M I S ZANDINELLO         ',
'R G L OLIVEIRA CONFECCOES ',
'SANGALETTI E CIA         ',
'SUPERMERCADO             ',
'VALDEMIR BORDISSERA E CIA',
'COMERCIAL TRENTO LTDA    ',
'DUDAMAR DIST             ',
'MARANDD MODAS LTDA       ',
'MAISA LINGERIE           ',
'AGOMAR MARCOS CHAVES',
'CAMEBA ENXOVAIS',
'EVIDENCIA LINGERIE',       
'TAILEY CONFECCOES   ',     
'TRENTO CONFECÇÕES',
'PONTO MAIOR',
'SHERITON ATACADO',
'MAQUIVEST',
'MAGAZINE SCHERER',
'EXCLUSIVE',
'LOJA REAL GUARAPUAVA',
'ELIZANDRO POLETTO MAYER',
'T  T CONFECES',
'GIANY LNGERIE')



INSERT INTO CLIENTE_REPRE(REPRESENTANTE,CLIENTE_ATACADO,REPRESENTANTE_PRINCIPAL)
SELECT 'AGOMAR MARCOS CHAVES',CLIENTE_ATACADO,'1' FROM CLIENTES_ATACADO
WHERE REGIAO='RV-07 ZN-01 ST-10' AND CLIENTE_ATACADO NOT IN 
(SELECT CLIENTE_ATACADO FROM CLIENTE_REPRE WHERE REPRESENTANTE='AGOMAR MARCOS CHAVES')


