BEGIN TRAN

--- TROCA DE CAIXA NUMERO DO CLIENTE
UPDATE FATURAMENTO_CAIXAS
SET FATURAMENTO_CAIXAS.CAIXA_NUMERO_CLIENTE = '245126'
FROM FATURAMENTO_PROD
JOIN FATURAMENTO_CAIXAS ON FATURAMENTO_CAIXAS.CAIXA=FATURAMENTO_PROD.CAIXA
WHERE NF_SAIDA='028065' AND SERIE_NF='2' AND PRODUTO='51364 KIT' --AND COR_PRODUTO LIKE 'RM%'

commit

UPDATE FATURAMENTO_CAIXAS
SET FATURAMENTO_CAIXAS.CAIXA_NUMERO_CLIENTE = '263208'
FROM FATURAMENTO_PROD
JOIN FATURAMENTO_CAIXAS ON FATURAMENTO_CAIXAS.CAIXA=FATURAMENTO_PROD.CAIXA
WHERE NF_SAIDA='028069' AND SERIE_NF='2' AND PRODUTO='50251' AND COR_PRODUTO LIKE 'CH%'
