USE DRLINGERIE

select * from VENDAS
WHERE PEDIDO_CLIENTE='6500350658'


select * from VENDAS_PRODUTO
WHERE PEDIDO='97009'


SELECT * FROM #VENDAS_PRODUTO

EXEC SP_TRANSFORMAR_COLUNA_EM_LINHA_PEDIDO_MARISA '97009' 


create PROC SP_TRANSFORMAR_COLUNA_EM_LINHA_PEDIDO_MARISA
@PEDIDO_MARISA CHAR(12)
AS 

Set ANSI_WARNINGS ON
SET ANSI_NULLS ON
SET NOCOUNT ON

DECLARE    @PEDIDO char(12),
           @PRODUTO char(12),
           @COR_PRODUTO char(10),
           @ENTREGA datetime,
           @SEQUENCIAL_DIGITACAO smallint,
           @ITEM_PEDIDO char(4),
           @NUMERO_CONJUNTO smallint,
           @PACKS varchar(24),
           @LIMITE_ENTREGA datetime,
           @CODIGO_LOCAL_ENTREGA char(5),
           @NUMERO_ENTREGA char(2),
           @STATUS_VENDA_ATUAL char(1),
           @QTDE_ORIGINAL int,
           @QTDE_EMBALADA int,
           @QTDE_ENTREGAR int,
           @QTDE_ENTREGUE int,
           @QTDE_DEVOLVIDA int,
           @QTDE_CANCELADA int,
           @PRECO1 numeric(14,2),
           @PRECO2 numeric(14,2),
           @PRECO3 numeric(14,2),
           @PRECO4 numeric(14,2),
           @DESCONTO_ITEM numeric(14,2),
           @IPI numeric(8,5),
           @VALOR_CANCELADO numeric(14,2),
           @VALOR_ORIGINAL numeric(14,2),
           @VALOR_ENTREGAR numeric(14,2),
           @VALOR_DEVOLVIDO numeric(14,2),
           @VALOR_ENTREGUE numeric(14,2),
           @ENTREGUE_MOEDA_PADRAO numeric(14,2),
           @VO1 int,
           @VO2 int,
           @VO3 int,
           @VO4 int,
           @VO5 int,
           @VO6 int,
           @VO7 int,
           @VO8 int,
           @VO9 int,
           @VO10 int,
           @VO11 int,
           @VO12 int,
           @VO13 int,
           @VO14 int,
           @VO15 int,
           @VO16 int,
           @VO17 int,
           @VO18 int,
           @VO19 int,
           @VO20 int,
           @VO21 int,
           @VO22 int,
           @VO23 int,
           @VO24 int,
           @VO25 int,
           @VO26 int,
           @VO27 int,
           @VO28 int,
           @VO29 int,
           @VO30 int,
           @VO31 int,
           @VO32 int,
           @VO33 int,
           @VO34 int,
           @VO35 int,
           @VO36 int,
           @VO37 int,
           @VO38 int,
           @VO39 int,
           @VO40 int,
           @VO41 int,
           @VO42 int,
           @VO43 int,
           @VO44 int,
           @VO45 int,
           @VO46 int,
           @VO47 int,
           @VO48 int,
           @VE1 int,
           @VE2 int,
           @VE3 int,
           @VE4 int,
           @VE5 int,
           @VE6 int,
           @VE7 int,
           @VE8 int,
           @VE9 int,
           @VE10 int,
           @VE11 int,
           @VE12 int,
           @VE13 int,
           @VE14 int,
           @VE15 int,
           @VE16 int,
           @VE17 int,
           @VE18 int,
           @VE19 int,
           @VE20 int,
           @VE21 int,
           @VE22 int,
           @VE23 int,
           @VE24 int,
           @VE25 int,
           @VE26 int,
           @VE27 int,
           @VE28 int,
           @VE29 int,
           @VE30 int,
           @VE31 int,
           @VE32 int,
           @VE33 int,
           @VE34 int,
           @VE35 int,
           @VE36 int,
           @VE37 int,
           @VE38 int,
           @VE39 int,
           @VE40 int,
           @VE41 int,
           @VE42 int,
           @VE43 int,
           @VE44 int,
           @VE45 int,
           @VE46 int,
           @VE47 int,
           @ORDEM_PRODUCAO char(8),
           @VE48 int,
           @PEDIDO_COMPRA char(8),
           @TIPO_CAIXA char(8),
           @NUMERO_CAIXAS smallint,
           @DESC_VENDA_CLIENTE varchar(80),
           @DESCONTO_PROMOCAO_ITEM numeric(8,5),
           @COMISSAO_ITEM numeric(8,5),
           @COMISSAO_ITEM_GERENTE numeric(8,5),
		   @QTDE_LIQUIDA int,
		   @VALOR_LIQUIDO numeric(15,2),
           @PORCENTAGEM_ITEM_RATEIO numeric(13,10),
           @DATA_PARA_TRANSFERENCIA datetime,
           @ID_MODIFICACAO char(6),
           @LICENCIADO_ROYALTIES numeric(8,5),
           @ID_VENDA_ENTREGA_FUTURA int,
		   @ISN_ITEM_PEDIDO int,
           @IPEVL_CHECADO int,
           @IPEQT_CHECKFLOWRACK int,
           @ISN_PEDIDO int,
           @ISN_PRODUTO int,
           @IPENM_LOTE varchar(20),
		   @QTDE int,
		   @POSICAO char(5),
		   @ITEM int

SELECT [PEDIDO]
      ,[PRODUTO]
      ,[COR_PRODUTO]
      ,[ENTREGA]
      ,[SEQUENCIAL_DIGITACAO]
      ,[ITEM_PEDIDO]
      ,[NUMERO_CONJUNTO]
      ,[PACKS]
      ,[LIMITE_ENTREGA]
      ,[CODIGO_LOCAL_ENTREGA]
      ,[NUMERO_ENTREGA]
      ,[STATUS_VENDA_ATUAL]
      ,[QTDE_ORIGINAL]=QTDE
      ,[QTDE_EMBALADA]
      ,[QTDE_ENTREGAR]=QTDE
      ,[QTDE_ENTREGUE]
      ,[QTDE_DEVOLVIDA]
      ,[QTDE_CANCELADA]
      ,[PRECO1]
      ,[PRECO2]
      ,[PRECO3]
      ,[PRECO4]
      ,[DESCONTO_ITEM]
      ,[IPI]
      ,[VALOR_CANCELADO]
      ,[VALOR_ORIGINAL]=QTDE*PRECO1
      ,[VALOR_ENTREGAR]=QTDE*PRECO1
      ,[VALOR_DEVOLVIDO]
      ,[VALOR_ENTREGUE]
      ,[ENTREGUE_MOEDA_PADRAO]
      ,[ORDEM_PRODUCAO]
      ,[PEDIDO_COMPRA]
      ,[TIPO_CAIXA]
      ,[NUMERO_CAIXAS]
      ,[DESC_VENDA_CLIENTE]
      ,[DESCONTO_PROMOCAO_ITEM]
      ,[COMISSAO_ITEM]
      ,[COMISSAO_ITEM_GERENTE]
      ,[QTDE_LIQUIDA]
      ,[VALOR_LIQUIDO]
      ,[PORCENTAGEM_ITEM_RATEIO]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[ID_MODIFICACAO]
      ,[LICENCIADO_ROYALTIES]
      ,[ID_VENDA_ENTREGA_FUTURA]
      ,[ISN_ITEM_PEDIDO]
      ,[IPEVL_CHECADO]
      ,[IPEQT_CHECKFLOWRACK]
      ,[ISN_PEDIDO]
      ,[ISN_PRODUTO]
      ,[IPENM_LOTE]
      ,QTDE,POSICAO
INTO #VENDAS_PRODUTO FROM 
(SELECT 
       [PEDIDO]
      ,[PRODUTO]
      ,[COR_PRODUTO]
      ,[ENTREGA]
      ,[SEQUENCIAL_DIGITACAO]
      ,[ITEM_PEDIDO]
      ,[NUMERO_CONJUNTO]
      ,[PACKS]
      ,[LIMITE_ENTREGA]
      ,[CODIGO_LOCAL_ENTREGA]
      ,[NUMERO_ENTREGA]
      ,[STATUS_VENDA_ATUAL]
      ,[QTDE_ORIGINAL]
      ,[QTDE_EMBALADA]
      ,[QTDE_ENTREGAR]
      ,[QTDE_ENTREGUE]
      ,[QTDE_DEVOLVIDA]
      ,[QTDE_CANCELADA]
      ,[PRECO1]
      ,[PRECO2]
      ,[PRECO3]
      ,[PRECO4]
      ,[DESCONTO_ITEM]
      ,[IPI]
      ,[VALOR_CANCELADO]
      ,[VALOR_ORIGINAL]
      ,[VALOR_ENTREGAR]
      ,[VALOR_DEVOLVIDO]
      ,[VALOR_ENTREGUE]
      ,[ENTREGUE_MOEDA_PADRAO]
      ,[ORDEM_PRODUCAO]
      ,[PEDIDO_COMPRA]
      ,[TIPO_CAIXA]
      ,[NUMERO_CAIXAS]
      ,[DESC_VENDA_CLIENTE]
      ,[DESCONTO_PROMOCAO_ITEM]
      ,[COMISSAO_ITEM]
      ,[COMISSAO_ITEM_GERENTE]
      ,[QTDE_LIQUIDA]
      ,[VALOR_LIQUIDO]
      ,[PORCENTAGEM_ITEM_RATEIO]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[ID_MODIFICACAO]
      ,[LICENCIADO_ROYALTIES]
      ,[ID_VENDA_ENTREGA_FUTURA]
      ,[ISN_ITEM_PEDIDO]
      ,[IPEVL_CHECADO]
      ,[IPEQT_CHECKFLOWRACK]
      ,[ISN_PEDIDO]
      ,[ISN_PRODUTO]
      ,[IPENM_LOTE]
      ,[VO1]
      ,[VO2]
      ,[VO3]
      ,[VO4]
      ,[VO5]
      ,[VO6]
      ,[VO7]
      ,[VO8]
      ,[VO9]
      ,[VO10]
      ,[VO11]
      ,[VO12]
      ,[VO13]
      ,[VO14]
      ,[VO15]
      ,[VO16]
FROM [dbo].[VENDAS_PRODUTO]
WHERE PEDIDO=@PEDIDO_MARISA
) A
UNPIVOT
(
  QTDE FOR POSICAO IN ([VO1],[VO2],[VO3],[VO4],[VO5],[VO6],[VO7],[VO8],[VO9],[VO10])
) AS C
WHERE C.QTDE>0


DECLARE CUR_VENDAS_PRODUTO CURSOR FOR 
SELECT [PEDIDO]
      ,[PRODUTO]
      ,[COR_PRODUTO]
      ,[ENTREGA]
      ,[SEQUENCIAL_DIGITACAO]
      ,[ITEM_PEDIDO]
      ,[NUMERO_CONJUNTO]
      ,[PACKS]
      ,[LIMITE_ENTREGA]
      ,[CODIGO_LOCAL_ENTREGA]
      ,[NUMERO_ENTREGA]
      ,[STATUS_VENDA_ATUAL]
      ,[QTDE_ORIGINAL]
      ,[QTDE_EMBALADA]
      ,[QTDE_ENTREGAR]
      ,[QTDE_ENTREGUE]
      ,[QTDE_DEVOLVIDA]
      ,[QTDE_CANCELADA]
      ,[PRECO1]
      ,[PRECO2]
      ,[PRECO3]
      ,[PRECO4]
      ,[DESCONTO_ITEM]
      ,[IPI]
      ,[VALOR_CANCELADO]
      ,[VALOR_ORIGINAL]
      ,[VALOR_ENTREGAR]
      ,[VALOR_DEVOLVIDO]
      ,[VALOR_ENTREGUE]
      ,[ENTREGUE_MOEDA_PADRAO]
      ,[ORDEM_PRODUCAO]
      ,[PEDIDO_COMPRA]
      ,[TIPO_CAIXA]
      ,[NUMERO_CAIXAS]
      ,[DESC_VENDA_CLIENTE]
      ,[DESCONTO_PROMOCAO_ITEM]
      ,[COMISSAO_ITEM]
      ,[COMISSAO_ITEM_GERENTE]
      ,[QTDE_LIQUIDA]
      ,[VALOR_LIQUIDO]
      ,[PORCENTAGEM_ITEM_RATEIO]
      ,[DATA_PARA_TRANSFERENCIA]
      ,[ID_MODIFICACAO]
      ,[LICENCIADO_ROYALTIES]
      ,[ID_VENDA_ENTREGA_FUTURA]
      ,[ISN_ITEM_PEDIDO]
      ,[IPEVL_CHECADO]
      ,[IPEQT_CHECKFLOWRACK]
      ,[ISN_PEDIDO]
      ,[ISN_PRODUTO]
      ,[IPENM_LOTE]
      ,QTDE,POSICAO
FROM #VENDAS_PRODUTO
OPEN CUR_VENDAS_PRODUTO 

FETCH NEXT FROM CUR_VENDAS_PRODUTO INTO @PEDIDO,@PRODUTO,@COR_PRODUTO,@ENTREGA,@SEQUENCIAL_DIGITACAO,
@ITEM_PEDIDO,@NUMERO_CONJUNTO,@PACKS,@LIMITE_ENTREGA,@CODIGO_LOCAL_ENTREGA,@NUMERO_ENTREGA,@STATUS_VENDA_ATUAL,
@QTDE_ORIGINAL,@QTDE_EMBALADA,@QTDE_ENTREGAR,@QTDE_ENTREGUE,@QTDE_DEVOLVIDA,@QTDE_CANCELADA,@PRECO1,
@PRECO2,@PRECO3,@PRECO4,@DESCONTO_ITEM,@IPI,@VALOR_CANCELADO,@VALOR_ORIGINAL,@VALOR_ENTREGAR,
@VALOR_DEVOLVIDO,@VALOR_ENTREGUE,@ENTREGUE_MOEDA_PADRAO,@ORDEM_PRODUCAO,@PEDIDO_COMPRA,
@TIPO_CAIXA,@NUMERO_CAIXAS,@DESC_VENDA_CLIENTE,@DESCONTO_PROMOCAO_ITEM,@COMISSAO_ITEM,
@COMISSAO_ITEM_GERENTE,@QTDE_LIQUIDA,@VALOR_LIQUIDO,@PORCENTAGEM_ITEM_RATEIO,@DATA_PARA_TRANSFERENCIA,
@ID_MODIFICACAO,@LICENCIADO_ROYALTIES,@ID_VENDA_ENTREGA_FUTURA,@ISN_ITEM_PEDIDO,@IPEVL_CHECADO,
@IPEQT_CHECKFLOWRACK,@ISN_PEDIDO,@ISN_PRODUTO,@IPENM_LOTE,@QTDE,@POSICAO

-- Excluir os itens do pedido
DELETE FROM VENDAS_PRODUTO
WHERE PEDIDO=@PEDIDO_MARISA

SET @ITEM = 11

WHILE @@FETCH_STATUS = 0
BEGIN
	--- QTDE ORIGINAL 
	SET @VO1 = CASE WHEN @POSICAO = 'VO1' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO2 = CASE WHEN @POSICAO = 'VO2' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO3 = CASE WHEN @POSICAO = 'VO3' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO4 = CASE WHEN @POSICAO = 'VO4' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO5 = CASE WHEN @POSICAO = 'VO5' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO6 = CASE WHEN @POSICAO = 'VO6' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO7 = CASE WHEN @POSICAO = 'VO7' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO8 = CASE WHEN @POSICAO = 'VO8' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO9 = CASE WHEN @POSICAO = 'VO9' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VO10 = CASE WHEN @POSICAO = 'VO10' THEN ISNULL(@QTDE,0) ELSE 0 END 
    SET @VO11 = 0
    SET @VO12 = 0
    SET @VO13 = 0
    SET @VO14 = 0
    SET @VO15 = 0
    SET @VO16 = 0
    SET @VO17 = 0
    SET @VO18 = 0
    SET @VO19 = 0
    SET @VO20 = 0
    SET @VO21 = 0
    SET @VO22 = 0
    SET @VO23 = 0
    SET @VO24 = 0
    SET @VO25 = 0
    SET @VO26 = 0
    SET @VO27 = 0
    SET @VO28 = 0
    SET @VO29 = 0
    SET @VO30 = 0
    SET @VO31 = 0
    SET @VO32 = 0
    SET @VO33 = 0
    SET @VO34 = 0
    SET @VO35 = 0
    SET @VO36 = 0
    SET @VO37 = 0
    SET @VO38 = 0
    SET @VO39 = 0
    SET @VO40 = 0
    SET @VO41 = 0
    SET @VO42 = 0
    SET @VO43 = 0
    SET @VO44 = 0
    SET @VO45 = 0
    SET @VO46 = 0
    SET @VO47 = 0
    SET @VO48 = 0

    --- QTDE ENTREGAR
	SET @VE1 = CASE WHEN @POSICAO = 'VE1' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE2 = CASE WHEN @POSICAO = 'VE2' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE3 = CASE WHEN @POSICAO = 'VE3' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE4 = CASE WHEN @POSICAO = 'VE4' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE5 = CASE WHEN @POSICAO = 'VE5' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE6 = CASE WHEN @POSICAO = 'VE6' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE7 = CASE WHEN @POSICAO = 'VE7' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE8 = CASE WHEN @POSICAO = 'VE8' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE9 = CASE WHEN @POSICAO = 'VE9' THEN ISNULL(@QTDE,0) ELSE 0 END 
	SET @VE10 = CASE WHEN @POSICAO = 'VE10' THEN ISNULL(@QTDE,0) ELSE 0 END 

	SET @ITEM_PEDIDO = REPLICATE('0',(4-LEN(@ITEM))) + CAST(@ITEM AS CHAR(4))
    
    --- Inserir novos itens do pedido	
    INSERT INTO VENDAS_PRODUTO ([PEDIDO],[PRODUTO],[COR_PRODUTO],[ENTREGA],[SEQUENCIAL_DIGITACAO],[ITEM_PEDIDO]
      ,[NUMERO_CONJUNTO],[PACKS],[LIMITE_ENTREGA],[CODIGO_LOCAL_ENTREGA],[NUMERO_ENTREGA],[STATUS_VENDA_ATUAL]
      ,[QTDE_ORIGINAL],[QTDE_EMBALADA],[QTDE_ENTREGAR],[QTDE_ENTREGUE],[QTDE_DEVOLVIDA],[QTDE_CANCELADA]
      ,[PRECO1],[PRECO2],[PRECO3],[PRECO4],[DESCONTO_ITEM],[IPI],[VALOR_CANCELADO],[VALOR_ORIGINAL]
      ,[VALOR_ENTREGAR],[VALOR_DEVOLVIDO],[VALOR_ENTREGUE],[ENTREGUE_MOEDA_PADRAO],[VO1],[VO2],[VO3]
      ,[VO4],[VO5],[VO6],[VO7],[VO8],[VO9],[VO10],[VO11],[VO12],[VO13],[VO14],[VO15],[VO16],[VO17]
      ,[VO18],[VO19],[VO20],[VO21],[VO22],[VO23],[VO24],[VO25],[VO26],[VO27],[VO28],[VO29],[VO30]
      ,[VO31],[VO32],[VO33],[VO34],[VO35],[VO36],[VO37],[VO38],[VO39],[VO40],[VO41],[VO42],[VO43]
      ,[VO44],[VO45],[VO46],[VO47],[VO48],[VE1],[VE2],[VE3],[VE4],[VE5],[VE6],[VE7],[VE8],[VE9]
      ,[VE10],[VE11],[VE12],[VE13],[VE14],[VE15],[VE16],[VE17],[VE18],[VE19],[VE20],[VE21],[VE22],[VE23]
      ,[VE24],[VE25],[VE26],[VE27],[VE28],[VE29],[VE30],[VE31],[VE32],[VE33],[VE34],[VE35],[VE36],[VE37]
      ,[VE38],[VE39],[VE40],[VE41],[VE42],[VE43],[VE44],[VE45],[VE46],[VE47],[ORDEM_PRODUCAO],[VE48]
      ,[PEDIDO_COMPRA],[TIPO_CAIXA],[NUMERO_CAIXAS],[DESC_VENDA_CLIENTE],[DESCONTO_PROMOCAO_ITEM],[COMISSAO_ITEM]
      ,[COMISSAO_ITEM_GERENTE],[PORCENTAGEM_ITEM_RATEIO],[DATA_PARA_TRANSFERENCIA]
      ,[ID_MODIFICACAO],[LICENCIADO_ROYALTIES],[ID_VENDA_ENTREGA_FUTURA],[IPEVL_CHECADO]
      ,[IPEQT_CHECKFLOWRACK],[ISN_PEDIDO],[ISN_PRODUTO],[IPENM_LOTE]) VALUES(
       @PEDIDO,@PRODUTO,@COR_PRODUTO,@ENTREGA,@SEQUENCIAL_DIGITACAO,@ITEM_PEDIDO
      ,@NUMERO_CONJUNTO,@PACKS,@LIMITE_ENTREGA,@CODIGO_LOCAL_ENTREGA,@NUMERO_ENTREGA,@STATUS_VENDA_ATUAL
      ,@QTDE_ORIGINAL,@QTDE_EMBALADA,@QTDE_ENTREGAR,@QTDE_ENTREGUE,@QTDE_DEVOLVIDA,@QTDE_CANCELADA
      ,@PRECO1,@PRECO2,@PRECO3,@PRECO4,@DESCONTO_ITEM,@IPI,@VALOR_CANCELADO,@VALOR_ORIGINAL
      ,@VALOR_ENTREGAR,@VALOR_DEVOLVIDO,@VALOR_ENTREGUE,@ENTREGUE_MOEDA_PADRAO,@VO1,@VO2,@VO3
      ,@VO4,@VO5,@VO6,@VO7,@VO8,@VO9,@VO10,@VO11,@VO12,@VO13,@VO14,@VO15,@VO16,@VO17
      ,@VO18,@VO19,@VO20,@VO21,@VO22,@VO23,@VO24,@VO25,@VO26,@VO27,@VO28,@VO29,@VO30
      ,@VO31,@VO32,@VO33,@VO34,@VO35,@VO36,@VO37,@VO38,@VO39,@VO40,@VO41,@VO42,@VO43
      ,@VO44,@VO45,@VO46,@VO47,@VO48,@VE1,@VE2,@VE3,@VE4,@VE5,@VE6,@VE7,@VE8,@VE9
      ,@VE10,@VE11,@VE12,@VE13,@VE14,@VE15,@VE16,@VE17,@VE18,@VE19,@VE20,@VE21,@VE22,@VE23
      ,@VE24,@VE25,@VE26,@VE27,@VE28,@VE29,@VE30,@VE31,@VE32,@VE33,@VE34,@VE35,@VE36,@VE37
      ,@VE38,@VE39,@VE40,@VE41,@VE42,@VE43,@VE44,@VE45,@VE46,@VE47,@ORDEM_PRODUCAO,@VE48
      ,@PEDIDO_COMPRA,@TIPO_CAIXA,@NUMERO_CAIXAS,@DESC_VENDA_CLIENTE,@DESCONTO_PROMOCAO_ITEM,@COMISSAO_ITEM
      ,@COMISSAO_ITEM_GERENTE,@PORCENTAGEM_ITEM_RATEIO,@DATA_PARA_TRANSFERENCIA
      ,@ID_MODIFICACAO,@LICENCIADO_ROYALTIES,@ID_VENDA_ENTREGA_FUTURA,@IPEVL_CHECADO
      ,@IPEQT_CHECKFLOWRACK,@ISN_PEDIDO,@ISN_PRODUTO,@IPENM_LOTE)

	  --- Atualizar o itens algumas colunas
	  UPDATE VENDAS_PRODUTO
	  SET QTDE_ORIGINAL = QTDE_ENTREGAR, VALOR_ORIGINAL=VALOR_ENTREGAR
	  WHERE PEDIDO=@PEDIDO AND ITEM_PEDIDO=@ITEM_PEDIDO

	  --- RECULCULA RESERVA DO PEDIDO LINX
	  EXEC LX_MOVIMENTA_VENDAS_PA @PEDIDO

	  SET @ITEM = @ITEM + 1

    FETCH NEXT FROM CUR_VENDAS_PRODUTO INTO @PEDIDO,@PRODUTO,@COR_PRODUTO,@ENTREGA,@SEQUENCIAL_DIGITACAO,
	@ITEM_PEDIDO,@NUMERO_CONJUNTO,@PACKS,@LIMITE_ENTREGA,@CODIGO_LOCAL_ENTREGA,@NUMERO_ENTREGA,@STATUS_VENDA_ATUAL,
	@QTDE_ORIGINAL,@QTDE_EMBALADA,@QTDE_ENTREGAR,@QTDE_ENTREGUE,@QTDE_DEVOLVIDA,@QTDE_CANCELADA,@PRECO1,
	@PRECO2,@PRECO3,@PRECO4,@DESCONTO_ITEM,@IPI,@VALOR_CANCELADO,@VALOR_ORIGINAL,@VALOR_ENTREGAR,
	@VALOR_DEVOLVIDO,@VALOR_ENTREGUE,@ENTREGUE_MOEDA_PADRAO,@ORDEM_PRODUCAO,@PEDIDO_COMPRA,
	@TIPO_CAIXA,@NUMERO_CAIXAS,@DESC_VENDA_CLIENTE,@DESCONTO_PROMOCAO_ITEM,@COMISSAO_ITEM,
	@COMISSAO_ITEM_GERENTE,@QTDE_LIQUIDA,@VALOR_LIQUIDO,@PORCENTAGEM_ITEM_RATEIO,@DATA_PARA_TRANSFERENCIA,
	@ID_MODIFICACAO,@LICENCIADO_ROYALTIES,@ID_VENDA_ENTREGA_FUTURA,@ISN_ITEM_PEDIDO,@IPEVL_CHECADO,
	@IPEQT_CHECKFLOWRACK,@ISN_PEDIDO,@ISN_PRODUTO,@IPENM_LOTE,@QTDE,@POSICAO

END 
DROP TABLE #VENDAS_PRODUTO
CLOSE CUR_VENDAS_PRODUTO
DEALLOCATE CUR_VENDAS_PRODUTO
GO


DELETE FROM VENDAS_PRODUTO
WHERE PEDIDO='97009' AND ITEM_PEDIDO<>'0001'

