
select b.data_faturamento_relativo,a.* from vendas_produto a
join vendas b on a.pedido=b.pedido
where b.filial = 'D.R. LINGERIE' AND B.TOT_QTDE_ENTREGAR>0 and B.DATA_FATURAMENTO_RELATIVO>'20170101' and
b.pedido = '91209'


--- DIRETO NA DATA FATURAMENTO RELATIVO
update a
set a.entrega=
CASE WHEN DBO.FX_DIA_SEMANA(b.DATA_FATURAMENTO_RELATIVO-12)=1 THEN ((b.DATA_FATURAMENTO_RELATIVO-12)-2) 
     WHEN DBO.FX_DIA_SEMANA(b.DATA_FATURAMENTO_RELATIVO-12)=7 THEN ((b.DATA_FATURAMENTO_RELATIVO-12)-1)
ELSE (b.DATA_FATURAMENTO_RELATIVO-12)
END,
a.limite_entrega=
CASE WHEN DBO.FX_DIA_SEMANA(b.DATA_FATURAMENTO_RELATIVO-12)=1 THEN ((b.DATA_FATURAMENTO_RELATIVO-12)-2) 
     WHEN DBO.FX_DIA_SEMANA(b.DATA_FATURAMENTO_RELATIVO-12)=7 THEN ((b.DATA_FATURAMENTO_RELATIVO-12)-1)
ELSE (b.DATA_FATURAMENTO_RELATIVO-12)
END
from vendas_produto a
join vendas b on a.pedido=b.pedido
where b.filial = 'D.R. LINGERIE' AND B.TOT_QTDE_ENTREGAR>0 and B.TOT_QTDE_ENTREGUE = 0 AND B.DATA_FATURAMENTO_RELATIVO>'20170101' 
and b.pedido = '91209'






--- DEPOIS DO UPDATE
update a
set a.entrega=
CASE WHEN DBO.FX_DIA_SEMANA(A.ENTREGA)=1 THEN (A.ENTREGA-2) 
     WHEN DBO.FX_DIA_SEMANA(A.ENTREGA)=7 THEN (A.ENTREGA-1)
ELSE A.ENTREGA 
END,
a.limite_entrega=
CASE WHEN DBO.FX_DIA_SEMANA(A.LIMITE_ENTREGA)=1 THEN (A.LIMITE_ENTREGA-2) 
     WHEN DBO.FX_DIA_SEMANA(A.LIMITE_ENTREGA)=7 THEN (A.LIMITE_ENTREGA-1) 
ELSE A.LIMITE_ENTREGA 
END
from vendas_produto a WITH (NOLOCK)
join vendas b WITH (NOLOCK) on a.pedido=b.pedido
where b.filial = 'D.R. LINGERIE' AND B.TOT_QTDE_ENTREGAR>0 and B.TOT_QTDE_ENTREGUE = 0 AND B.DATA_FATURAMENTO_RELATIVO>'20170101' 
and b.pedido = '91214'






