SELECT * FROM (
SELECT PRODUTOS.PRODUTO,
PRODUTOS.DESC_PRODUTO, 
PRODUTOS_BARRA.COR_PRODUTO,
PRODUTO_CORES.DESC_COR_PRODUTO,
PRODUTOS_BARRA.GRADE,
EM_PROCESSO.DESC_FASE_PRODUCAO,
ORDEM_PRODUCAO,
QTDE_ORIGINAL= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.Vo1
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.Vo2
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.Vo3
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.Vo4
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.Vo5
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.Vo6
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.Vo7
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.Vo8
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.Vo9
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.Vo10
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.Vo11
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.Vo12
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.Vo13
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.Vo14
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.Vo15
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.Vo16
                     END),
QTDE_ENTREGAR= (CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN VENDAS_PRODUTO.VE1
                     WHEN PRODUTOS_BARRA.tamanho='2'  THEN VENDAS_PRODUTO.VE2
                     WHEN PRODUTOS_BARRA.tamanho='3'  THEN VENDAS_PRODUTO.VE3
                     WHEN PRODUTOS_BARRA.tamanho='4'  THEN VENDAS_PRODUTO.VE4
                     WHEN PRODUTOS_BARRA.tamanho='5'  THEN VENDAS_PRODUTO.VE5
                     WHEN PRODUTOS_BARRA.tamanho='6'  THEN VENDAS_PRODUTO.VE6
                     WHEN PRODUTOS_BARRA.tamanho='7'  THEN VENDAS_PRODUTO.VE7
                     WHEN PRODUTOS_BARRA.tamanho='8'  THEN VENDAS_PRODUTO.VE8
                     WHEN PRODUTOS_BARRA.tamanho='9'  THEN VENDAS_PRODUTO.VE9
                     WHEN PRODUTOS_BARRA.tamanho='10' THEN VENDAS_PRODUTO.VE10
                     WHEN PRODUTOS_BARRA.tamanho='11' THEN VENDAS_PRODUTO.VE11
                     WHEN PRODUTOS_BARRA.tamanho='12' THEN VENDAS_PRODUTO.VE12
                     WHEN PRODUTOS_BARRA.tamanho='13' THEN VENDAS_PRODUTO.VE13
                     WHEN PRODUTOS_BARRA.tamanho='14' THEN VENDAS_PRODUTO.VE14
                     WHEN PRODUTOS_BARRA.tamanho='15' THEN VENDAS_PRODUTO.VE15
                     WHEN PRODUTOS_BARRA.tamanho='16' THEN VENDAS_PRODUTO.VE16
                     END),
QTDE_EM_PROCESSO=(CASE WHEN PRODUTOS_BARRA.tamanho='1'  THEN EM_PROCESSO.S1 
                       WHEN PRODUTOS_BARRA.tamanho='2'  THEN EM_PROCESSO.S2 
                       WHEN PRODUTOS_BARRA.tamanho='3'  THEN EM_PROCESSO.S3
                       WHEN PRODUTOS_BARRA.tamanho='4'  THEN EM_PROCESSO.S4
                       WHEN PRODUTOS_BARRA.tamanho='5'  THEN EM_PROCESSO.S5
                       WHEN PRODUTOS_BARRA.tamanho='6'  THEN EM_PROCESSO.S6
                       WHEN PRODUTOS_BARRA.tamanho='7'  THEN EM_PROCESSO.S7
                       WHEN PRODUTOS_BARRA.tamanho='8'  THEN EM_PROCESSO.S8
                       WHEN PRODUTOS_BARRA.tamanho='9'  THEN EM_PROCESSO.S9
                       WHEN PRODUTOS_BARRA.tamanho='10' THEN EM_PROCESSO.S10
                       WHEN PRODUTOS_BARRA.tamanho='11' THEN EM_PROCESSO.S11
                       WHEN PRODUTOS_BARRA.tamanho='12' THEN EM_PROCESSO.S12
                       WHEN PRODUTOS_BARRA.tamanho='13' THEN EM_PROCESSO.S13
                       WHEN PRODUTOS_BARRA.tamanho='14' THEN EM_PROCESSO.S14
                       WHEN PRODUTOS_BARRA.tamanho='15' THEN EM_PROCESSO.S15
                       WHEN PRODUTOS_BARRA.tamanho='16' THEN EM_PROCESSO.S16
                  END)
FROM PRODUTOS_BARRA PRODUTOS_BARRA 
JOIN PRODUTOS PRODUTOS ON PRODUTOS_BARRA.PRODUTO=PRODUTOS.PRODUTO 
JOIN PRODUTO_CORES PRODUTO_CORES ON PRODUTO_CORES.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND PRODUTO_CORES.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
LEFT JOIN (SELECT PRODUTO,COR_PRODUTO,QTDE_ORIGINAL=SUM(QTDE_ORIGINAL),QTDE_ENTREGAR=SUM(QTDE_ENTREGAR)
      ,VO1=SUM(VO1),VO2=SUM(VO2),VO3=SUM(VO3),VO4=SUM(VO4),VO5=SUM(VO5),VO6=SUM(VO6),VO7=SUM(VO7),VO8=SUM(VO8)
      ,VO9=SUM(VO9),VO10=SUM(VO10),VO11=SUM(VO11),VO12=SUM(VO12),VO13=SUM(VO13),VO14=SUM(VO14),VO15=SUM(VO15)
      ,VO16=SUM(VO16),VE1=SUM(VE1),VE2=SUM(VE2),VE3=SUM(VE3),VE4=SUM(VE4),VE5=SUM(VE5),VE6=SUM(VE6),VE7=SUM(VE7)
      ,VE8=SUM(VE8),VE9=SUM(VE9),VE10=SUM(VE10),VE11=SUM(VE11),VE12=SUM(VE12),VE13=SUM(VE13),VE14=SUM(VE14)
      ,VE15=SUM(VE15),VE16=SUM(VE16) FROM VENDAS_PRODUTO WHERE VENDAS_PRODUTO.QTDE_ENTREGAR>0 GROUP BY PRODUTO,COR_PRODUTO) AS VENDAS_PRODUTO
  ON VENDAS_PRODUTO.PRODUTO=PRODUTOS_BARRA.PRODUTO 
 AND VENDAS_PRODUTO.COR_PRODUTO=PRODUTOS_BARRA.COR_PRODUTO 
LEFT JOIN ( 
SELECT PRODUCAO_TAREFAS_SALDO.PRODUTO,  PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,PRODUCAO_FASE.DESC_FASE_PRODUCAO,
PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO, 
QTDE_S=SUM(PRODUCAO_TAREFAS_SALDO.QTDE_S),
QTDE_EM_PROCESSO=SUM(PRODUCAO_TAREFAS.QTDE_EM_PROCESSO),  
S1=SUM(PRODUCAO_TAREFAS_SALDO.S1), 
S2=SUM(PRODUCAO_TAREFAS_SALDO.S2),  
S3=SUM(PRODUCAO_TAREFAS_SALDO.S3), 
S4=SUM(PRODUCAO_TAREFAS_SALDO.S4),  
S5=SUM(PRODUCAO_TAREFAS_SALDO.S5), 
S6=SUM(PRODUCAO_TAREFAS_SALDO.S6),  
S7=SUM(PRODUCAO_TAREFAS_SALDO.S7), 
S8=SUM(PRODUCAO_TAREFAS_SALDO.S8),  
S9=SUM(PRODUCAO_TAREFAS_SALDO.S9), 
S10=SUM(PRODUCAO_TAREFAS_SALDO.S10),  
S11=SUM(PRODUCAO_TAREFAS_SALDO.S11), 
S12=SUM(PRODUCAO_TAREFAS_SALDO.S12),  
S13=SUM(PRODUCAO_TAREFAS_SALDO.S13), 
S14=SUM(PRODUCAO_TAREFAS_SALDO.S14),  
S15=SUM(PRODUCAO_TAREFAS_SALDO.S15), 
S16=SUM(PRODUCAO_TAREFAS_SALDO.S16) 
FROM DBO.PRODUCAO_TAREFAS_SALDO PRODUCAO_TAREFAS_SALDO,  DBO.PRODUTO_CORES PRODUTO_CORES,  DBO.PRODUCAO_TAREFAS PRODUCAO_TAREFAS,  
DBO.PRODUCAO_FASE PRODUCAO_FASE, DBO.PRODUCAO_SETOR PRODUCAO_SETOR,  DBO.PRODUCAO_RECURSOS PRODUCAO_RECURSOS WHERE PRODUTO_CORES.PRODUTO = PRODUCAO_TAREFAS_SALDO.PRODUTO   AND 
PRODUCAO_TAREFAS_SALDO.COR_PRODUTO = PRODUTO_CORES.COR_PRODUTO   AND PRODUCAO_TAREFAS_SALDO.TAREFA = PRODUCAO_TAREFAS.TAREFA   AND PRODUCAO_FASE.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   
AND PRODUCAO_SETOR.FASE_PRODUCAO = PRODUCAO_TAREFAS.FASE_PRODUCAO   AND PRODUCAO_SETOR.SETOR_PRODUCAO = PRODUCAO_TAREFAS.SETOR_PRODUCAO   AND PRODUCAO_TAREFAS.RECURSO_PRODUTIVO = PRODUCAO_RECURSOS.RECURSO_PRODUTIVO   
AND PRODUCAO_TAREFAS.QTDE_EM_PROCESSO>0
GROUP BY PRODUCAO_TAREFAS_SALDO.PRODUTO,PRODUCAO_TAREFAS_SALDO.COR_PRODUTO,PRODUCAO_FASE.DESC_FASE_PRODUCAO,PRODUCAO_TAREFAS_SALDO.ORDEM_PRODUCAO
) AS EM_PROCESSO  
ON VENDAS_PRODUTO.PRODUTO=EM_PROCESSO.PRODUTO AND VENDAS_PRODUTO.COR_PRODUTO=EM_PROCESSO.COR_PRODUTO
WHERE PRODUTOS_BARRA.CODIGO_BARRA LIKE '789%' AND EM_PROCESSO.QTDE_EM_PROCESSO > 0
--ORDER BY VENDAS_PRODUTO.PRODUTO,VENDAS_PRODUTO.COR_PRODUTO
) AS FINAL
WHERE QTDE_EM_PROCESSO>0
ORDER BY PRODUTO,COR_PRODUTO