--- EM QTDE
SELECT CONDICAO_PGTO,DESC_COND_PGTO,QTDE_VENDA,QTDE_GERAL FROM (

SELECT FATURAMENTO.CONDICAO_PGTO,COND_ATAC_PGTOS.DESC_COND_PGTO,
QTDE_GERAL=(SELECT QTDE_VENDA=COUNT(FATURAMENTO.CONDICAO_PGTO)
FROM LDR.DRVAREJO.DBO.FATURAMENTO
JOIN LDR.DRVAREJO.DBO.COND_ATAC_PGTOS ON COND_ATAC_PGTOS.CONDICAO_PGTO=FATURAMENTO.CONDICAO_PGTO
JOIN LDR.DRVAREJO.DBO.NATUREZAS_SAIDAS ON NATUREZAS_SAIDAS.NATUREZA_SAIDA=FATURAMENTO.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20150101' AND '20151231' AND NATUREZAS_SAIDAS.DESC_NATUREZA LIKE '%VENDA%'
),
QTDE_VENDA=COUNT(FATURAMENTO.CONDICAO_PGTO),
QTDE_TOTAL=SUM(QTDE_TOTAL)
FROM LDR.DRVAREJO.DBO.FATURAMENTO
JOIN LDR.DRVAREJO.DBO.COND_ATAC_PGTOS ON COND_ATAC_PGTOS.CONDICAO_PGTO=FATURAMENTO.CONDICAO_PGTO
JOIN LDR.DRVAREJO.DBO.NATUREZAS_SAIDAS ON NATUREZAS_SAIDAS.NATUREZA_SAIDA=FATURAMENTO.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20150101' AND '20151231' AND NATUREZAS_SAIDAS.DESC_NATUREZA LIKE '%VENDA%'
GROUP BY FATURAMENTO.CONDICAO_PGTO,COND_ATAC_PGTOS.DESC_COND_PGTO

) AS FINAL
ORDER BY QTDE_VENDA DESC


---- EM VALORES
SELECT CONDICAO_PGTO,DESC_COND_PGTO,VALOR_GERAL,VALOR_VENDA,PERCENTUAL=(VALOR_VENDA/VALOR_GERAL) FROM (

SELECT FATURAMENTO.CONDICAO_PGTO,COND_ATAC_PGTOS.DESC_COND_PGTO,
QTDE_GERAL=(SELECT QTDE_VENDA=COUNT(FATURAMENTO.CONDICAO_PGTO)
FROM LDR.DRVAREJO.DBO.FATURAMENTO
JOIN LDR.DRVAREJO.DBO.COND_ATAC_PGTOS ON COND_ATAC_PGTOS.CONDICAO_PGTO=FATURAMENTO.CONDICAO_PGTO
JOIN LDR.DRVAREJO.DBO.NATUREZAS_SAIDAS ON NATUREZAS_SAIDAS.NATUREZA_SAIDA=FATURAMENTO.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20150101' AND '20151231' AND NATUREZAS_SAIDAS.DESC_NATUREZA LIKE '%VENDA%'
),

VALOR_GERAL=(SELECT VALOR_VENDA=SUM(FATURAMENTO.MPADRAO_VALOR_TOTAL)
FROM LDR.DRVAREJO.DBO.FATURAMENTO
JOIN LDR.DRVAREJO.DBO.COND_ATAC_PGTOS ON COND_ATAC_PGTOS.CONDICAO_PGTO=FATURAMENTO.CONDICAO_PGTO
JOIN LDR.DRVAREJO.DBO.NATUREZAS_SAIDAS ON NATUREZAS_SAIDAS.NATUREZA_SAIDA=FATURAMENTO.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20150101' AND '20151231' AND NATUREZAS_SAIDAS.DESC_NATUREZA LIKE '%VENDA%'
),

QTDE_VENDA=COUNT(FATURAMENTO.CONDICAO_PGTO),
QTDE_TOTAL=SUM(QTDE_TOTAL),
VALOR_VENDA=SUM(FATURAMENTO.MPADRAO_VALOR_TOTAL)
FROM LDR.DRVAREJO.DBO.FATURAMENTO
JOIN LDR.DRVAREJO.DBO.COND_ATAC_PGTOS ON COND_ATAC_PGTOS.CONDICAO_PGTO=FATURAMENTO.CONDICAO_PGTO
JOIN LDR.DRVAREJO.DBO.NATUREZAS_SAIDAS ON NATUREZAS_SAIDAS.NATUREZA_SAIDA=FATURAMENTO.NATUREZA_SAIDA
WHERE EMISSAO BETWEEN '20150101' AND '20151231' AND NATUREZAS_SAIDAS.DESC_NATUREZA LIKE '%VENDA%'
GROUP BY FATURAMENTO.CONDICAO_PGTO,COND_ATAC_PGTOS.DESC_COND_PGTO

) AS FINAL
ORDER BY VALOR_VENDA DESC
