--- VENDAS DE CUECAS
SELECT C.GRUPO_PRODUTO,B.*, A.* FROM VENDAS_PRODUTO A
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO
JOIN PRODUTOS C ON C.PRODUTO=A.PRODUTO
WHERE C.GRUPO_PRODUTO='CUECA' AND B.EMISSAO >= '20140101'


--- CLIENTES NOVOS DE CUECAS
SELECT TIPO_CLIENTE=E.TIPO,C.GRUPO_PRODUTO,D.CGC_CPF,D.CLIFOR,D.NOME_CLIFOR,D.RAZAO_SOCIAL,D.CADASTRAMENTO,B.*, A.PRODUTO,A.COR_PRODUTO,A.QTDE_ORIGINAL FROM VENDAS_PRODUTO A
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO
JOIN PRODUTOS C ON C.PRODUTO=A.PRODUTO
JOIN CADASTRO_CLI_FOR D ON D.NOME_CLIFOR=B.CLIENTE_ATACADO
JOIN CLIENTES_ATACADO E ON E.CLIENTE_ATACADO=D.NOME_CLIFOR
WHERE C.GRUPO_PRODUTO='CUECA' AND D.CADASTRAMENTO>='20140901' AND E.CONCEITO='CLIENTE NOVO' 





