
select CAST(SUM(QTDE) AS INT) from faturamento_prod
WHERE NF_SAIDA='017339' AND SERIE_NF='2'

select CAST(SUM(QTDE_ITEM) AS INT) from FATURAMENTO_ITEM
WHERE NF_SAIDA='017339' AND SERIE_NF='2'

select CAST(SUM(QTDE) AS INT) from faturamento_prod
WHERE NF_SAIDA='018368' AND SERIE_NF='2'

select CAST(SUM(QTDE_ITEM) AS INT) from FATURAMENTO_ITEM
WHERE NF_SAIDA='018368' AND SERIE_NF='2'


SELECT A.FILIAL,A.NF_SAIDA,A.SERIE_NF,A.QTDE_FISICO,B.QTDE_FISCAL,DIFERENCA=(A.QTDE_FISICO-B.QTDE_FISCAL) 
FROM ( SELECT FILIAL,NF_SAIDA,SERIE_NF,QTDE_FISICO=CAST(SUM(QTDE) AS INT) FROM FATURAMENTO_PROD GROUP BY FILIAL,NF_SAIDA,SERIE_NF ) A 
JOIN ( SELECT FILIAL,NF_SAIDA,SERIE_NF,QTDE_FISCAL=CAST(SUM(QTDE_ITEM) AS INT) FROM FATURAMENTO_ITEM GROUP BY FILIAL,NF_SAIDA,SERIE_NF ) B  
ON A.FILIAL=B.FILIAL AND A.NF_SAIDA=B.NF_SAIDA AND A.SERIE_NF=B.SERIE_NF
WHERE QTDE_FISICO<>QTDE_FISCAL --AND A.FILIAL='DR VAREJO' AND A.NF_SAIDA='018368' AND A.SERIE_NF='2'
ORDER BY A.NF_SAIDA


