select 
SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, CHARINDEX('/', PEDIDO.PEDCN_PEDIDO)-1) AS PEDIDO,
recpedido.ISN_REC_PED AS CAIXA,
iterec.IRPNR_QUANTIDADE AS QUANTIDADE,
PROD.PROCC_PRODUTO AS PRODUTO,
prod.PRODS_TAM AS TAMANHO,
COR.CORNR_COR AS COR,
pb.CODIGO_BARRA as codigoBarras
 from 
WMS_RECIPIENTE_PEDIDO recpedido
inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC ON recpedido.ISN_REC_PED = ITEREC.IRPNR_CODIGO
INNER JOIN WMS_PRODUTO PROD ON PROD.ISN_PRODUTO = ITEREC.ISN_PRODUTO
inner join WMS_CORES cor on prod.PRONR_COR = cor.ISN_COR
INNER JOIN WMS_PEDIDO PEDIDO ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO
INNER join produtos_barra pb on pb.isn_produto = prod.isn_produto






