select 
SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, CHARINDEX('/', PEDIDO.PEDCN_PEDIDO)-1) AS PEDIDO,
recpedido.ISN_REC_PED AS CAIXA,
iterec.IRPNR_QUANTIDADE AS QUANTIDADE,
PROD.PROCC_PRODUTO AS PRODUTO,
prod.PRODS_TAM AS GRADE,
COR.CORNR_COR AS COR,
pb.CODIGO_BARRA as codigoBarras,
pb.TAMANHO AS POSICAO
 from 
WMS_RECIPIENTE_PEDIDO recpedido
inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC ON recpedido.ISN_REC_PED = ITEREC.IRPNR_CODIGO
INNER JOIN WMS_PRODUTO PROD ON PROD.ISN_PRODUTO = ITEREC.ISN_PRODUTO
inner join WMS_CORES cor on prod.PRONR_COR = cor.ISN_COR
INNER JOIN WMS_PEDIDO PEDIDO ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO
INNER join produtos_barra pb on pb.isn_produto = prod.isn_produto 
where pb.CODIGO_BARRA_PADRAO=1 
order by pedido,CAIXA


select * from VENDAS_PROD_EMBALADO
WHERE PEDIDO='598847'
ORDER BY PRODUTO,COR_PRODUTO


CREATE VIEW W_WMS_PEDIDO_VOLUMES 
AS 

SELECT * FROM (
SELECT
SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, CHARINDEX('/', PEDIDO.PEDCN_PEDIDO)-1) AS PEDIDO,
recpedido.ISN_REC_PED AS CAIXA,
PROD.PROCC_PRODUTO AS PRODUTO,
COR.CORNR_COR AS COR,
prod.PRODS_TAM AS GRADE,
pb.TAMANHO,
sum(iterec.IRPNR_QUANTIDADE) AS QUANTIDADE
 from 
WMS_RECIPIENTE_PEDIDO recpedido
inner join WMS_ITEM_RECIPIENTE_PEDIDO ITEREC ON recpedido.ISN_REC_PED = ITEREC.IRPNR_CODIGO
INNER JOIN WMS_PRODUTO PROD ON PROD.ISN_PRODUTO = ITEREC.ISN_PRODUTO
inner join WMS_CORES cor on prod.PRONR_COR = cor.ISN_COR
INNER JOIN WMS_PEDIDO PEDIDO ON PEDIDO.ISN_PEDIDO = recpedido.ISN_PEDIDO
INNER join produtos_barra pb on pb.isn_produto = prod.isn_produto 
where pb.CODIGO_BARRA_PADRAO=1 
group by 
SUBSTRING(PEDIDO.PEDCN_PEDIDO, 1, CHARINDEX('/', PEDIDO.PEDCN_PEDIDO)-1),
recpedido.ISN_REC_PED,
PROD.PROCC_PRODUTO,
COR.CORNR_COR,
prod.PRODS_TAM,
pb.TAMANHO
) AS PEDIDO_VOLUMES
WHERE RTRIM(PEDIDO)='598847'
order by PRODUTO,COR,GRADE
