CREATE VIEW VISAO_ALMOXARIFADO AS 
SELECT PRODUCAO_ORDEM.ORDEM_PRODUCAO,
PRODUCAO_ORDEM.PRIORIDADE,
PRODUCAO_TAREFAS.INICIO_REAL 
FROM PRODUCAO_ORDEM
JOIN PRODUCAO_TAREFAS ON PRODUCAO_TAREFAS.ORDEM_PRODUCAO=PRODUCAO_ORDEM.ORDEM_PRODUCAO
WHERE FASE_PRODUCAO = '002'

SELECT * FROM PRODUCAO_TAREFAS

SELECT * FROM VISAO_ALMOXARIFADO

UPDATE VISAO_ALMOXARIFADO
SET PRIORIDADE=1
WHERE ORDEM_PRODUCAO='07745'


SELECT * FROM VISAO_ALMOXARIFADO