SELECT * FROM W_ESTOQUE_DISPONIVEL_MATERIAL_GO_VAREJO
WHERE MATERIAL='30.01.0120' AND COR_MATERIAL=''

ALTER VIEW [dbo].[W_ESTOQUE_DISPONIVEL_MATERIAL_GO_VAREJO] AS          
SELECT ORDEM_PRODUCAO,MATERIAL,COR_MATERIAL,QTDE_ESTOQUE,RESERVA,QTDE_DISPONIVEL=(QTDE_ESTOQUE-RESERVA) 
FROM (          
	SELECT PRODUCAO_RESERVA.ORDEM_PRODUCAO,
	PRODUCAO_RESERVA.MATERIAL,
	       PRODUCAO_RESERVA.COR_MATERIAL,
	       QTDE_ESTOQUE=ISNULL(ESTOQUE_MATERIAIS.QTDE_ESTOQUE,0),
	       RESERVA=SUM(RESERVA)          
	FROM PRODUCAO_RESERVA WITH (NOLOCK)          
	LEFT JOIN (
	           SELECT MATERIAL,
	           COR_MATERIAL,
	           QTDE_ESTOQUE=SUM(QTDE_ESTOQUE) 
	           FROM ESTOQUE_MATERIAIS WITH (NOLOCK) 
	           WHERE FILIAL IN ('DR VAREJO','D.R. LINGERIE') 
	           GROUP BY MATERIAL,COR_MATERIAL 
	) ESTOQUE_MATERIAIS ON ESTOQUE_MATERIAIS.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND ESTOQUE_MATERIAIS.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL 
	JOIN MATERIAIS_CORES WITH (NOLOCK) ON MATERIAIS_CORES.MATERIAL=PRODUCAO_RESERVA.MATERIAL AND MATERIAIS_CORES.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL  
	WHERE PRODUCAO_RESERVA.ORDEM_PRODUCAO 
	      IN (          
	           SELECT DISTINCT A.ORDEM_PRODUCAO FROM PRODUCAO_TAREFAS A WITH (NOLOCK)         
	           JOIN PRODUCAO_RESERVA B WITH (NOLOCK) ON B.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO     
	           WHERE (A.FASE_PRODUCAO IN('002','20','30','100','101','50') and A.QTDE_EM_PROCESSO>0) 
	                 AND B.MATERIAL=PRODUCAO_RESERVA.MATERIAL 
	                 AND B.COR_MATERIAL=PRODUCAO_RESERVA.COR_MATERIAL 
	                 AND B.RESERVA>0    
	         ) 
	GROUP BY PRODUCAO_RESERVA.ORDEM_PRODUCAO, PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.MATERIAL,PRODUCAO_RESERVA.COR_MATERIAL,ESTOQUE_MATERIAIS.QTDE_ESTOQUE          
) AS ESTOQUE_DISPONIVEL          
GO


SELECT * FROM PRODUCAO_RESERVA
WHERE ORDEM_PRODUCAO='180120' AND MATERIAL='30.01.0120'

