SELECT E.REGIAO,D.UF, CIDADE=RTRIM(D.CIDADE), D.NOME_CLIFOR,D.RAZAO_SOCIAL, MES=MONTH(B.EMISSAO),ANO=YEAR(B.EMISSAO),QTDE=SUM(A.QTDE_ORIGINAL), VALOR=SUM(A.VALOR_ORIGINAL) 
FROM VENDAS_PRODUTO A with (nolock), VENDAS B with (nolock), PRODUTOS C with (nolock), CADASTRO_CLI_FOR D with (nolock), CLIENTES_ATACADO E with (nolock) 
WHERE A.PEDIDO = B.PEDIDO AND C.PRODUTO = A.PRODUTO AND B.CLIENTE_ATACADO = D.NOME_CLIFOR AND B.CLIENTE_ATACADO = E.CLIENTE_ATACADO AND B.TABELA_FILHA='VENDAS_PRODUTO' AND 
SUBSTRING(CONVERT(CHAR(10),B.EMISSAO,112),1,6) >= SUBSTRING(CONVERT(CHAR(10),(GETDATE()-330),112),1,6) AND SUBSTRING(CONVERT(CHAR(10),B.EMISSAO,112),1,6) <= SUBSTRING(CONVERT(CHAR(10),(GETDATE()),112),1,6) 
AND B.APROVACAO='A' 
GROUP BY E.REGIAO,D.UF, D.CIDADE, D.NOME_CLIFOR,D.RAZAO_SOCIAL, MONTH(B.EMISSAO),YEAR(B.EMISSAO) HAVING (E.REGIAO = 'rv-01 zn-01 st-16')
order by ANO


SELECT MES=MONTH(B.EMISSAO),ANO=YEAR(B.EMISSAO),QTDE=SUM(A.QTDE_ORIGINAL), VALOR=SUM(A.VALOR_ORIGINAL) 
FROM VENDAS_PRODUTO A with (nolock), VENDAS B with (nolock), PRODUTOS C with (nolock), CADASTRO_CLI_FOR D with (nolock), CLIENTES_ATACADO E with (nolock) 
WHERE A.PEDIDO = B.PEDIDO AND C.PRODUTO = A.PRODUTO AND B.CLIENTE_ATACADO = D.NOME_CLIFOR AND B.CLIENTE_ATACADO = E.CLIENTE_ATACADO AND B.TABELA_FILHA='VENDAS_PRODUTO' AND 
SUBSTRING(CONVERT(CHAR(10),B.EMISSAO,112),1,6) >= SUBSTRING(CONVERT(CHAR(10),(GETDATE()-330),112),1,6) AND SUBSTRING(CONVERT(CHAR(10),B.EMISSAO,112),1,6) <= SUBSTRING(CONVERT(CHAR(10),(GETDATE()),112),1,6) 
AND B.APROVACAO='A' and E.REGIAO = 'rv-01 zn-01 st-16'
GROUP BY MONTH(B.EMISSAO),YEAR(B.EMISSAO) 
