SELECT A.PEDIDO,A.PRODUTO,A.COR_PRODUTO,A.GRADE,A.QTDE,QTDE_O=SUM(B.QTDE_O)
FROM V_WMS_PEDIDOS_AGRUPADOS A
JOIN LKD24.DRLINGERIE.DBO.W_VENDAS_PRODUTO_VERTICAL B ON B.PEDIDO=A.PEDIDO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO AND B.GRADE=A.GRADE
--WHERE B.PEDIDO='89590'
GROUP BY A.PEDIDO,A.PRODUTO,A.COR_PRODUTO,A.GRADE,A.QTDE
HAVING SUM(B.QTDE_O) < A.QTDE

SELECT * FROM WMS_RESERVAS_PEDIDO

select * from V_WMS_PEDIDOS_AGRUPADOS
WHERE PEDIDO='91209'


SELECT A.QTD,QTD_REAL=(B.QTDE_O - C.QTDE),B.GRADE,A.* 
FROM WMS_INTEGRACAO_EXP_RESERVAS_INS A
JOIN W_VENDAS_PRODUTO_VERTICAL B ON B.PEDIDO=A.PEDIDO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO AND B.TAMANHO=CAST(SUBSTRING(A.TAMANHO,9,2) AS INT)
JOIN LKD65.SOFTLOGWMS.DBO.V_WMS_PEDIDOS_AGRUPADOS C ON C.PEDIDO=B.PEDIDO AND C.PRODUTO=B.PRODUTO AND C.COR_PRODUTO=B.COR_PRODUTO AND C.GRADE=B.GRADE
WHERE A.PEDIDO='80211' AND 
(B.QTDE_O - C.QTDE) > 0 


-- CONSULTA FINAL RESERVA LINX X WMS
SELECT a.pedido,a.produto,a.cor_produto,b.grade,B.QTDE_O as qtde_original_pedido,isnull(C.QTDE,0) as reservado_wms, reserva_falta_wms=(B.QTDE_O - isnull(C.QTDE,0)), reserva_linx=sum(A.QTD)
FROM WMS_INTEGRACAO_EXP_RESERVAS_INS A
JOIN W_VENDAS_PRODUTO_VERTICAL B ON B.PEDIDO=A.PEDIDO AND B.PRODUTO=A.PRODUTO AND B.COR_PRODUTO=A.COR_PRODUTO AND B.TAMANHO=CAST(SUBSTRING(A.TAMANHO,9,2) AS INT)
left JOIN LKD65.SOFTLOGWMS.DBO.V_WMS_PEDIDOS_AGRUPADOS C ON C.PEDIDO=B.PEDIDO AND C.PRODUTO=B.PRODUTO AND C.COR_PRODUTO=B.COR_PRODUTO AND C.GRADE=B.GRADE
WHERE A.PEDIDO='82721' --AND (B.QTDE_O - C.QTDE) > 0 
GROUP BY a.pedido,a.produto,a.cor_produto,b.grade,B.QTDE_O,C.QTDE,(B.QTDE_O - C.QTDE)



SELECT PEDIDO,PRODUTO,COR_PRODUTO,TAMANHO, SUM(QTD) 
FROM WMS_INTEGRACAO_EXP_RESERVAS_INS
WHERE PEDIDO='82721'
GROUP BY PEDIDO,PRODUTO,COR_PRODUTO,TAMANHO


SELECT * FROM LKD65.SOFTLOGWMS.DBO.V_WMS_PEDIDOS_AGRUPADOS
WHERE PEDIDO =  '90743'
