ALTER VIEW W_OFICINA_GRUPO_REFERENCIA_TEMPO_RETORNO_OFICINA AS   
SELECT DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,B.DATA,  
TEMPO_PADRAO=  
(  
SELECT TEMPO_CRONOMETRADO=SUM(TEMPO_CRONOMETRADO) FROM PRODUTO_OPERACOES_ROTAS   
WHERE TABELA_OPERACOES = A.PRODUTO AND TEMPO_CRONOMETRADO>0   
),   
QTDE=SUM(QTDE_O),  
QTDE_OPERADOR=(  
    select distinct qtde_operador from ldr_metas_oficina_grupo_nova   
    where desc_recurso=C.DESC_RECURSO and desc_SETOR_producao=C.DESC_SETOR_PRODUCAO   
    and data_producao= B.DATA   
),  
MINUTOS_DISPONIVEIS=(  
    select distinct minutos_disponiveis from ldr_metas_oficina_grupo_nova   
    where desc_recurso=C.DESC_RECURSO and desc_setor_producao=C.DESC_setor_PRODUCAO   
    and data_producao= B.DATA   
)
FROM PRODUCAO_OS_TAREFAS A JOIN PRODUCAO_ORDEM_SERVICO B ON B.ORDEM_SERVICO=A.ORDEM_SERVICO LEFT JOIN W_ORDEM_PRODUCAO_OFICINA_NOVA C ON C.ORDEM_PRODUCAO=A.ORDEM_PRODUCAO  
WHERE B.INDICADOR_TIPO_MOV = 1 and (B.DATA >= '20130101' AND B.DATA <= GETDATE()) AND B.FASE_PRODUCAO = '009' --AND DESC_SETOR_PRODUCAO='OFICINA JULIETE' AND DESC_RECURSO='GRUPO JULIETE 03'
GROUP BY DESC_RECURSO,DESC_SETOR_PRODUCAO,PRODUTO,B.DATA  

