-- curva abc de cliente 2012

select a.razao_social,a.email,a.mes,a.qtde,c.qtde_produto,b.media from CURVA_ABC_CLIENTE_2012 a
join MEDIA_VENDAS_CLIENTE_2012 b on b.razao_social=a.razao_social
join QTDE_PRODUTO_CLIENTE_2012 c on c.razao_social=a.razao_social and c.mes=a.mes

ALTER VIEW CURVA_ABC_CLIENTE_2012 AS  
SELECT C.RAZAO_SOCIAL,C.EMAIL,MES=MONTH(B.EMISSAO),QTDE = SUM(A.QTDE_ORIGINAL)  
FROM VENDAS_PRODUTO A  
JOIN VENDAS B ON B.PEDIDO=A.PEDIDO  
JOIN CADASTRO_CLI_FOR C ON C.NOME_CLIFOR=B.CLIENTE_ATACADO  
JOIN CLIENTES_ATACADO D ON D.CLIENTE_ATACADO=B.CLIENTE_ATACADO
WHERE B.EMISSAO >= '20120101' AND B.EMISSAO <= '20121231' AND B.APROVACAO='A' AND D.TIPO <> 'BALCONISTA'
GROUP BY C.RAZAO_SOCIAL,C.EMAIL,MONTH(B.EMISSAO)  

