USE [TESTES]
GO

/****** Object:  UserDefinedFunction [dbo].[FX_MATERIAIS_RECEITA]    Script Date: 11/19/2015 13:50:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER FUNCTION [dbo].[FX_MATERIAIS_RECEITA] (@RECEITA CHAR(15), @QTDE_TOTAL NUMERIC(9, 3), @ABS_RECEITA INT,@RELACAO_BANHO TINYINT )  

RETURNS @MATRECEITA TABLE  (   COD_RECEITA CHAR(15),   COD_RECEITA_ADICIONAL CHAR(15),   DESC_RECEITA VARCHAR(60),   COR_RECEITA CHAR(10),   DESC_COR_RECEITA VARCHAR(25),   ORDEM_RECEITA_ADICIONAL SMALLINT,   ANTERIOR_POSTERIOR CHAR(1) COLLATE DATABASE_DEFAULT ,   ITEM_ORDEM_MATERIAL SMALLINT,   COD_PASSO CHAR(4),   MATERIAL CHAR(11) COLLATE DATABASE_DEFAULT ,   DESC_MATERIAL VARCHAR(40) COLLATE DATABASE_DEFAULT,   COR_MATERIAL CHAR(10) COLLATE DATABASE_DEFAULT ,   DESC_COR_MATERIAL VARCHAR(50) COLLATE DATABASE_DEFAULT,   CONSUMO NUMERIC(10,5),   UNID_ESTOQUE CHAR(5),   CONSUMO_PERCENTUAL BIT,   QTDE_RESERVA NUMERIC(15,9),  
 QTDE_RESERVA_FLOAT FLOAT,  
 TIPO_RECEITA TINYINT)  AS  BEGIN  
	-- 26/03/2009 - SZALONTAI - ADIÇÃO DO PARAMETRO RELACAO_BANHO, POIS UMA RECEITA PODE TER UMA RELAÇÃO DIFERENTE DA QUE ESTA CADASTRADA.

    SET @RELACAO_BANHO = ISNULL(@RELACAO_BANHO,0)
	INSERT INTO @MATRECEITA   	SELECT CASE WHEN @RECEITA=FT_RECEITA_COMPOSICAO.COD_RECEITA                  THEN  FT_RECEITA_COMPOSICAO.COD_RECEITA             ELSE  (SELECT COD_RECEITA                           FROM FT_RECEITA_ADICIONAL                    WHERE COD_FT_RECEITA_ADICIONAL = FT_RECEITA_COMPOSICAO.COD_RECEITA                      AND COD_RECEITA              = @RECEITA)             END,             FT_RECEITA_COMPOSICAO.COD_RECEITA,             FT_RECEITA.DESC_RECEITA,             FT_RECEITA.COR AS COR_RECEITA,             CORES_BASICAS.DESC_COR AS DESC_COR_RECEITA,             CASE WHEN @RECEITA=FT_RECEITA_COMPOSICAO.COD_RECEITA                  THEN  0  
           ELSE (SELECT ITEM_ORDEM                           FROM FT_RECEITA_ADICIONAL                    WHERE COD_FT_RECEITA_ADICIONAL = FT_RECEITA_COMPOSICAO.COD_RECEITA                      AND COD_RECEITA              = @RECEITA)             END,             CASE WHEN @RECEITA=FT_RECEITA_COMPOSICAO.COD_RECEITA             THEN  'M'             ELSE (SELECT ANTERIOR_POSTERIOR                           FROM FT_RECEITA_ADICIONAL                    WHERE COD_FT_RECEITA_ADICIONAL = FT_RECEITA_COMPOSICAO.COD_RECEITA                      AND COD_RECEITA              = @RECEITA)             END ,             FT_RECEITA_COMPOSICAO.ITEM_ORDEM,             FT_RECEITA_COMPOSICAO.COD_PASSO,             FT_RECEITA_COMPOSICAO.MATERIAL,             


		   MATERIAIS.DESC_MATERIAL,             FT_RECEITA_COMPOSICAO.COR_MATERIAL,             MATERIAIS_CORES.DESC_COR_MATERIAL,             FT_RECEITA_COMPOSICAO.CONSUMO,             MATERIAIS.UNID_ESTOQUE,             FT_RECEITA_COMPOSICAO.CONSUMO_PERCENTUAL,             CAST(ROUND(CASE WHEN FT_RECEITA_COMPOSICAO.CONSUMO_PERCENTUAL=1  		   THEN (CAST(FT_RECEITA_COMPOSICAO.CONSUMO AS FLOAT)/100) * CAST(@QTDE_TOTAL AS FLOAT) *1000 *ISNULL(CAST(UNIDADES_CONVERSOES.FATOR_CONVERSAO_UNIDADE AS FLOAT),1)

           ELSE 			(CAST(@QTDE_TOTAL AS FLOAT) * CASE WHEN TIPO_RECEITA=1THEN				CAST(		CASE WHEN @RELACAO_BANHO = 0 
																THEN 
																	CASE WHEN @RECEITA=FT_RECEITA_COMPOSICAO.COD_RECEITA  
																	THEN	(
																				SELECT RELACAO_BANHO  
																				FROM FT_RECEITA  
																				WHERE COD_RECEITA = @RECEITA
																			)  
																	ELSE FT_RECEITA.RELACAO_BANHO  
																	END 
																ELSE @RELACAO_BANHO 
																END AS FLOAT

															)ELSE 1 END* CAST(FT_RECEITA_COMPOSICAO.CONSUMO AS FLOAT)*ISNULL(CAST(UNIDADES_CONVERSOES.FATOR_CONVERSAO_UNIDADE AS FLOAT),1))        
   END,9) AS NUMERIC(15,9))   ,             CAST(ROUND(CASE WHEN FT_RECEITA_COMPOSICAO.CONSUMO_PERCENTUAL=1  		   THEN (CAST(FT_RECEITA_COMPOSICAO.CONSUMO AS FLOAT)/100) * CAST(@QTDE_TOTAL AS FLOAT) *1000 *ISNULL(CAST(UNIDADES_CONVERSOES.FATOR_CONVERSAO_UNIDADE AS FLOAT),1)
           ELSE 			(CAST(@QTDE_TOTAL AS FLOAT) * CASE WHEN TIPO_RECEITA=1THEN				CAST(		CASE WHEN @RELACAO_BANHO = 0 
																THEN 
																	CASE WHEN @RECEITA=FT_RECEITA_COMPOSICAO.COD_RECEITA  
																	THEN	(
																				SELECT RELACAO_BANHO  
																				FROM FT_RECEITA  
																				WHERE COD_RECEITA = @RECEITA
																			)  
																	ELSE FT_RECEITA.RELACAO_BANHO  
																	END 
																ELSE @RELACAO_BANHO 
																END AS FLOAT

															)ELSE 1 END* CAST(FT_RECEITA_COMPOSICAO.CONSUMO AS FLOAT)*ISNULL(CAST(UNIDADES_CONVERSOES.FATOR_CONVERSAO_UNIDADE AS FLOAT),1))         
   END,9) AS FLOAT)   ,TIPO_RECEITA         FROM FT_RECEITA_COMPOSICAO                LEFT JOIN FT_RECEITA                     ON FT_RECEITA_COMPOSICAO.COD_RECEITA = FT_RECEITA.COD_RECEITA                LEFT JOIN CORES_BASICAS                
     ON FT_RECEITA.COR                    = CORES_BASICAS.COR                LEFT JOIN MATERIAIS                     ON FT_RECEITA_COMPOSICAO.MATERIAL    = MATERIAIS.MATERIAL                LEFT JOIN MATERIAIS_CORES                     ON FT_RECEITA_COMPOSICAO.COR_MATERIAL= MATERIAIS_CORES.COR_MATERIAL                    AND FT_RECEITA_COMPOSICAO.MATERIAL    = MATERIAIS_CORES.MATERIAL  			  LEFT JOIN UNIDADES_CONVERSOES 			       ON UNIDADES_CONVERSOES.UNIDADE=MATERIAIS.UNID_ESTOQUE AND UNIDADES_CONVERSOES.UNIDADE_CONVERTIDA='GR'    WHERE FT_RECEITA_COMPOSICAO.COD_RECEITA = @RECEITA         OR (@ABS_RECEITA = 0         AND FT_RECEITA_COMPOSICAO.COD_RECEITA IN(SELECT COD_FT_RECEITA_ADICIONAL                                  FROM FT_RECEITA_ADICIONAL                           WHERE COD_RECEITA = @RECEITA))         RETURN  END




GO


